### ISSUE TITLE
Playtesting 0.3.15 - Jail issues and feedback

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#1004]
1. When breaking into the jail using lockpicks, on the staircase on the position seen in the screenshot, the alarm visual and sound alarm is triggered, but no NPC reaction or being taken to jail is. Player has to go few steps further down to trigger guard's attention, despite alarm being set off already.
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/be96176f-4c87-4b05-95ca-0379464aaad6)
2. Sometime when going down the staircase during a break-in, the alarm is not triggered at all, just the NPC dialogue.
3. While being put in jail, lockpick and opening doors from the second cell doesn't trigger any alarm or NPC reaction, even when they are not sleeping, player can even crouch out of the cell, turn of fuses (except for the one that operates the TV, stand up and read the safe note.
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/5f81f0da-0959-4f8c-833e-bd55ec8b5e5d)
4. When bribing the guard, it may happen to see RM amount not rounded to the to spaces after decimal point
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/14ed249e-0dba-4832-a966-8b6025c09c8b)
5. Actual release time and the time stated by the guard don't match, when asking the guard it's been stated I'll be in jail for 22 hours, however after skipping time 2 times for 4 hours, I got released.
6. If player is taken to jail yet again for jail escape, items gather during the jailtime/jail escape will override the content in the lockers of the original state of player's inventory, loosing it permanently. They should add up to the previous stuff unless there's no more space inside the lockers.
7. Pressing the fuse box buttons (except that concerning TV) doesn't trigger any reaction from the guard when he's not sleeping. Seems like logically it should, maybe not necessary being put back to jail but a warning that if we keep pressing them, he'll throw us back to jail again.
8. Interactive with safe (not opening it yet, just touching it), while the guard is not asleep, doesn't trigger any reaction, neither does cracking the code, only taking owned items.
9. When offering to bribe, choosing second option 1) despite displaying proposed offer in RMs, pays from OCs 2) guard states that it's not worth the risk, but the payment is made and the doors are being opened - jailtime is served, player is free to leave.
10. Standing around in the market zone, when attempting to lock pick the cell doors, doesn't bring the guard's attention, being too close to the doors or to the left of the market zone does.
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/371cdc90-e625-457a-912a-0a08a7bbb6f0)
11. Some items should be illegal to own/controlled/too expensive to not be repossessed for personal (guard's) profit. Stuff like lock picks, green mushrooms, expensive alcohols and/or large amount of alcohol in the inventory, silver and gold items, piggybanks and moneyboxes.
12. Lock picking and opening the first cell (further from the guard), while he is sleeping, makes him instantaneously wake up and get alerted, alarm is not raised anyhow.
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/c34ca1e9-3d45-4c6c-9478-90046a83332b)
13. Can Opener doesn't respawn when player is throw into the same cell where the can opener was already taken.
14. Stuck at the wall waiting activity after triggering the wait interaction and being at the same time released
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/96ea8e44-4f8c-414e-ad06-4e41fca2660e)

Log from that session
[Player.zip](https://github.com/loiste-interactive/Obenseuer-Issues/files/13364257/Player.zip)

**Comment by Nextej** [comment]
16. When lockpicking is interrupted by dialogue, the picking action is executed (either successful, opens the door, or a failure, breaks the pick) instead of being cancelled (does none of the mentioned).
17. When guard is sleeping and player is permitted to roam around (just got released from cell), lockpicking, cracking safe, stealing items doesn't trigger any alarm (with all fuses being on), only adds crime points. Points are also added if all the fuses are off.
18. After being taken to jail, no matter what cell you end up at first, loading up autosave always put you the second cell (closer to the guard).

**Comment by Oskutin** [comment]
1 and 2 are not really issues.
The alarm triggering by the surveilance camera has % chance per few seconds. There's also camera doing the same upstairs.

**Comment by Oskutin** [comment]
4, 5 and 6 are and maybe bugs.

**Comment by Nextej** [comment]
It's a bit weird then, no? You'd assume something such as camera is consistent, also 3 always happens, guard never notices the doors opening and player leaving (if crouching).

**Comment by Oskutin** [comment]
Does 8 happen when player has been released?

**Comment by Oskutin** [comment]
9 is bug.

**Comment by Oskutin** [comment]
12,13 and 14 are bugs or can be bugs.

**Comment by Nextej** [comment]
14 also applies to gameboy 
[Player.zip](https://github.com/loiste-interactive/Obenseuer-Issues/files/13364677/Player.zip)

**Comment by Oskutin** [comment]
Okay, so that happens at the same time when player is waiting, but is also going to be released?

**Comment by Nextej** [comment]
Yes, but not always, sometimes it works normally and player is freed from interaction if they are released, but both cases happened when player was going to be released.

**Comment by Oskutin** [comment]
Fixed 4

**Comment by Oskutin** [comment]
Fixed 9

**Comment by Oskutin** [comment]
Fixed 13

**Comment by Oskutin** [comment]
17 is fixed

**Comment by Oskutin** [comment]
18 is fixed

**Comment by Oskutin** [comment]
5 is fixed

**Comment by Oskutin** [comment]
Can't get the stuck in wait to happen

**Comment by Nextej** [comment]
I had a thought, can you try spamming with interaction button for it to open dialogue window?

**Comment by Oskutin** [comment]
was there saveload between?

**Comment by Oskutin** [comment]
Not sure if that time stuck happens anymore due other changes
Also closing this issue as it's hard to keep up what is fixed, what is bug and what is feature request and general feedback
