### ISSUE TITLE
[Playtesting] Clipping visibility

### ISSUE THREAD

**Issue by Z-O-M-B-I-E** [loiste-interactive/Obenseuer-Issues#1007]
Bushes in the game cut off visibility
![20231115190828_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/46783282/d12a2a44-07c7-4694-b586-2042cb6d3a92)
![20231115190833_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/46783282/664a6cbe-1932-4dc4-89f6-118ed59cdb0f)
![20231115190837_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/46783282/aab7dbf0-e945-4456-8ad6-f253b2906113)
![20231115192804_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/46783282/6846f052-0e78-4a7c-a882-5b26636b8553)
![20231115192807_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/46783282/5f7cff66-2e28-4537-b8e5-268e1ae038af)

**Comment by Oskutin** [comment]
What version you're on?

**Comment by Z-O-M-B-I-E** [comment]
> What version you're on?

0.16

**Comment by Oskutin** [comment]
Fixed
