### ISSUE TITLE
A few windows have no collision

### ISSUE THREAD

**Issue by ontrigger** [loiste-interactive/Obenseuer-Issues#101]
https://user-images.githubusercontent.com/8556074/233792131-8a12a47b-3d85-406b-8e9e-f7a6e66f91ba.mp4

another one here
![image](https://user-images.githubusercontent.com/8556074/233792037-8fc6501b-772d-4a0e-9d05-38d3e380e1a4.png)

**Comment by ontrigger** [comment]
This window too
![image](https://user-images.githubusercontent.com/8556074/233792801-feaa3e1e-0797-415f-b8d0-735604cbc5fb.png)

**Comment by Oskutin** [comment]
Fixed all, There were some other windows missing collisions too.
