### ISSUE TITLE
Playtesting - If player completes objective "Visit that place Malone told you about" after completing "Getting Started" quest, the quest is reactivated without ability to complete it again.

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#1010]
Potentially the same applies to "Go to Kurahaar brothers' farm" objective.

**Comment by Oskutin** [comment]
What quest gets restarted?

**Comment by Nextej** [comment]
"Getting Starter" gets reactivated, all objectives are still completed, just the task is visible on the list of active tasks, and a proper notification, "new task" started, is displayed

**Comment by Nextej** [comment]
bringing it up to attention to the other quest-related issues

**Comment by Zuntti** [comment]
Fixed
