### ISSUE TITLE
[Playtest] Duplicated door

### ISSUE THREAD

**Issue by Z-O-M-B-I-E** [loiste-interactive/Obenseuer-Issues#1011]
![20231115222902_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/46783282/f965d6b0-bb5c-477b-be3b-4da330c3b9c9)
![20231115222905_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/46783282/dd3cb8f5-45e3-4d74-99e5-22c41ab6bc3e)
![20231115222906_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/46783282/db2f5ed2-514d-4012-afa6-bf3c48b2dd53)

**Comment by Oskutin** [comment]
Fixed
