### ISSUE TITLE
[Playtest] Strange object in a bag

### ISSUE THREAD

**Issue by Z-O-M-B-I-E** [loiste-interactive/Obenseuer-Issues#1013]
![20231115221727_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/46783282/175c5d65-7524-449e-8f29-e14cf82701f2)
![20231115221731_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/46783282/59d3a053-aa13-4f47-8fcf-dcbe1b064519)

**Comment by Nextej** [comment]
Location, Kolhola A2 apartment, kitchen room. Seems to be similar issue as the old #517 / #544

**Comment by Oskutin** [comment]
Fixed
