### ISSUE TITLE
[Playtest] Blueprint cannot be picked up

### ISSUE THREAD

**Issue by Z-O-M-B-I-E** [loiste-interactive/Obenseuer-Issues#1014]
Blueprint cannot be picked up

![20231115215424_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/46783282/50fb167c-4b95-429e-9445-41b38efe51dd)

**Comment by Nextej** [comment]
Location, second room of OS-Magazine Advertising Company office.

**Comment by Oskutin** [comment]
Fixed
