### ISSUE TITLE
Playtesting - Hostel keeper NPC is spawned naked.

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#1015]
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/3908fbc0-2ba5-4909-8833-161cba677312)

**Comment by Z-O-M-B-I-E** [comment]
Is this a bug? Ahaha, it seemed to me that it should be so

**Comment by Zuntti** [comment]
Fixed
