### ISSUE TITLE
A need for skill gain modifier for machines/farms that allow to growing/processing high amounts of items at the same time.

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#1020]
A new modifier should be created that reduces (or increases, who knows) the amount of skill gain for processed/planted items. The notable examples are two Kurahaara large farm fields and the pea soup field kitchen that allow to process a lot of items at the same time, massively gaining sometimes even few levels at the same time, allowing to max out certain skills within first few days. For instance a 0,02% modifier to Kurahaara farm for 44 planted crops, would still have roughtly a double skill gain in compare to single slot of regular farm, but now gaining new levels won't be a matter of one single massive plant spam.

**Comment by Oskutin** [comment]
Skill gain is already multiplied by fail chance.

**Comment by Nextej** [comment]
That doesn't solve the issue if the fail chances are multiplied by the amount the skill you have.

**Comment by Oskutin** [comment]
Done
