### ISSUE TITLE
Playtesting - You can offer Ville a stolen Socca Junior, such can easily be acquired from the Pentti's secret room without punishement, would be better to reserve the giving to only non-stolen items.

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#1021]

**Comment by Nextej** [comment]
Hmmm, alright, there is some punishment to you in crime points after you give the wine, hmmm...

**Comment by Oskutin** [comment]
Odd, considering that Ville is criminal.

**Comment by Z-O-M-B-I-E** [comment]
> Hmmm, alright, there is some punishment to you in crime points after you give the wine, hmmm...

Not always
