### ISSUE TITLE
Bag of Green Mushrooms (Low Potency) have not shown effects

### ISSUE THREAD

**Issue by Kastuk** [loiste-interactive/Obenseuer-Issues#1022]
Item got excessful brakes inside Action tab after "Data": null

**Comment by Oskutin** [comment]
You're looking at the farm variant of it

**Comment by Nextej** [comment]
Yeah, normal bag doesn't show any effects either, gotten from the starting package.
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/5d77ff68-9e95-4d5c-aba1-c79c0d932cc8)

**Comment by Oskutin** [comment]
Hmm, fixed
