### ISSUE TITLE
Playtesting - Apartment 4 of Playerment was cleared out of any default furniture, never was upgraded, it's bare now, other apartments preserve their original state unless have the walls upgraded

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#1029]
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/7d3ac1d3-2534-4b02-9fc1-313fe96247f9)
[Crash_Tester.zip](https://github.com/loiste-interactive/Obenseuer-Issues/files/13370879/Crash_Tester.zip)
autosave the latest
[Player.zip](https://github.com/loiste-interactive/Obenseuer-Issues/files/13370880/Player.zip)

**Comment by Zuntti** [comment]
Fixed
