### ISSUE TITLE
Few visual errors I came across during my new playthrough

### ISSUE THREAD

**Issue by TiaLinna** [loiste-interactive/Obenseuer-Issues#1034]
![20231116022439_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/130680276/c4db49f7-b788-4633-bb9f-c0b23fa9f6cd)
![20231116022454_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/130680276/0a09e8ae-c59b-4fe8-8684-138a0578d619)
![20231116022908_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/130680276/d3f16a15-bb61-4c07-9764-f9da9d61beee)
![20231116023353_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/130680276/d986c042-4a88-4679-9d4d-8bfc36a0d556)

The last picture is a one that appeared at the backyard, when I jumped up and down.

**Comment by Oskutin** [comment]
Already fixed
