### ISSUE TITLE
Playtesting - various parts of the descriptions of quests appear in wrong order or are gone missing as the quests progress.

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#1037]
1. "Missing Debitcard" the description is in wrong order, the new bits were added as the objectives went completed
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/737005ff-bda2-448e-aaa3-fcd2170df0b9)
2. "Getting Started" similar situation, I suspect the issue is global so I won't list it all.
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/80b9e858-9760-4353-8beb-31b1cb7cbd72)
3. "Survive in Obenseuer" had originally two-part description, but one was removed as the objective was completed, the missing part concerns pea soup
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/1ea286e7-0bde-4c4d-a4ae-6f3456069a68)

**Comment by Zuntti** [comment]
Fixed
