### ISSUE TITLE
Playtesting - Some unknown furniture at Mobelmann's is missing icon and preview

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#1043]
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/537ec8c0-2b1e-4e38-a67f-13bd3d4db0ac)

**Comment by Oskutin** [comment]
Is there some info in logfile about missing adressable paths?

**Comment by Nextej** [comment]
[Player.zip](https://github.com/loiste-interactive/Obenseuer-Issues/files/13377758/Player.zip)
?

**Comment by Oskutin** [comment]
Doesnt seem to have anything :(

**Comment by Nextej** [comment]
Alright, I was able to buy it, it's the Quarter Pallet

**Comment by Oskutin** [comment]
Ah, the reason was that the adressable list wast not build
