### ISSUE TITLE
Playtesting - After starting "Getting a Passport" quest, if the player finds the Passmore themselves or talk to Anya at Deekula B doors before visiting Mobelmann, it should unlock a unique line of dialogues and objectives.

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#1045]
If player went first to Anya -> add new objective to find passport seller behind O-Market -> when talked, add new objective to figure out passport (+ a description of sorts "I think I found a potential seller but I need a password") -> unlock new dialogue option at Deekula C "do you know the password to a passport seller behind O-Market or know anything else who sells the passports" at Mobelmann and other NPCs.

If player went to passmore first -> when Passmore demands password, add a new dialogue option along the lines "but do you sell passports or not", with a response "password first", and add an associated objective to find what the password is (with similiar description of "I think I found a potential seller or someone who knows where to find one but I need a password first) -> similar new dialogues as above but without certainity that it is the right passport seller

In both cases don't immediately fail objectives at Deekula C, player should feel like they have an alternative to find a seller at C even after finding Passmore.

**Comment by Zuntti** [comment]
This actually almost exists already but is not fully implemented
1. Tell Anya Passed -> Get Task: Getting a passport + objective: Tell Passmore password "Passed"
2. Tell Passed to Passmore Get objective: Get a right password for Passmore

**Comment by Zuntti** [comment]
Added
