### ISSUE TITLE
Playtestin - "Getting a Passport" description after being sent by Passmore to Eliana should be sightly changed to help player with navigation.

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#1046]
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/30c5c8ec-0b66-4073-a6e5-9e181f9afb08)
this bit should be changed to "...talk to Eliana, the photographer at the Kolhola building, and ask..."

**Comment by Zuntti** [comment]
Added
