### ISSUE TITLE
Game is very laggy

### ISSUE THREAD

**Issue by ontrigger** [loiste-interactive/Obenseuer-Issues#105]
I develop unity applications and have experience modding (and optimizing) unity games, so let me give my two cents on the rendering performance of this game:

The first thing I noticed is the complete lack of instancing or static combining of any kind. It seems like this game is built using small tiles/reusable prefabs, and every single wood beam, floor tile and wall is rendered one-by-one. It takes like 18 draws just to render the floor. This problem is best demonstrated on the title screen.

Here we are on the title screen, take a look at the background tenements:
![image](https://user-images.githubusercontent.com/8556074/233795029-63a7c328-e3b3-4614-81a3-d272701d8559.png)
You'd think that a tenement is just a simple model that is rendered in one drawcall, right?
Wrong. Every single grey rectangle in this image is a window, and these windows are being rendered in batches of 3. Objects highlighted in yellow represent one drawcall:
![image](https://user-images.githubusercontent.com/8556074/233795387-16e68284-4cf0-44ac-9493-418ae3321cbc.png)

Now it's time to render the buildings, and once again, it's not just a simple model:
![image](https://user-images.githubusercontent.com/8556074/233796059-09e10281-4242-413f-acc7-6f3560488319.png)
It looks like the tenements are composed of small quad planes, but on further inspection these planes turn out to be 3d objects, making up for a total of 17k vertices just to render a quarter of a building:
![image](https://user-images.githubusercontent.com/8556074/233796214-2859ad3b-4b50-4aca-b934-e08ff461ce2f.png)
The same story continues for grass blades - every single grass clump in the scene is drawn one by one:
![image](https://user-images.githubusercontent.com/8556074/233796396-2b4b66be-3ee8-45d5-aee0-86f97d68582e.png)

The situation with the buildings kind of looks like the work of unity's native static combine feature. Unfortunately, this feature is godawful and does more harm than good. Here's a forum thread detailing some of the issues with it: https://forum.unity.com/threads/unitys-static-batching-why-does-it-shoot-itself-in-the-foot.1051604/.
I would suggest either disabling static combining (if it is even enabled) and opting for instancing/manual combining instead.
Fortunately, it seems like fixing most of the rendering lag would be quite easy, as it's mostly just enabling a checkbox in the material inspector or using an asset store plugin to combine meshes into one.

**Comment by Oskutin** [comment]
Unity fixed this in 2023 version: 

> Anyway, I have some news to share about this issue. Simply put - we've fixed it in Unity 2023. The first version with the fix is 2023.1.0a5. Credit to [@alextyrer](https://forum.unity.com/members/834796/) for the fix!

Sadly we're still in 2019 version, and upgrading may break a lot of things.

**Comment by ontrigger** [comment]
I only linked that thread to show how bad unity's static combining feature is. The methods I described in the OP are fairly easy to implement in order to boost the games perf without switching to a new unity version

**Comment by Oskutin** [comment]
Meshcombining and other optimizations has been done.
There are still probably many laggy areas, but it would be better to report them separately
