### ISSUE TITLE
Playtesting - "Radio Signal" quest, finding just the body, telling Amanda about it and deciding not to tell police about it doesn't add any new objective to the quest, while having it still active.

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#1055]
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/8ea5bc11-a43d-4a19-b424-516eef9a0376)

**Comment by Nextej** [comment]
Task cannot be completed anyhow, at best you can also tell Amanda about Woman in Bed, but that doesn't advances the quest further or unlocks new options or objectives.

**Comment by Zuntti** [comment]
Fixed
