### ISSUE TITLE
Playtesting - When tasked to tell police about the body in B3 basement, it should be possible to use this doorbell intercome or ask the Axel Norberg, is that a place where you can report the body/where can you report a body.

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#1058]
The building may trigger clear associations with a police station
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/15ac4057-a021-4e82-aa01-7d4745146530)
Player should be able to use the doorbell to ask whether they can report the body here
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/afd577bc-0812-4fc5-b9ab-6c7ebeb50056)
or ask Axel Norberg where can they report the body
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/a613d707-f447-405f-bb73-19d16aa8b158)
the response should be that they should find any of the dispatched officers patroling the area if they have any crime to report, otherwise they don't deal with that there (don't need to mention 112 directly).

**Comment by Zuntti** [comment]
Added
