### ISSUE TITLE
Playtesting - to clear up confusions the players may have, perhaps spell it outright that the mines are not available yet in the current version.

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#1061]
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/89c6473e-188a-47e2-90a7-42b409107ad2)
Same notification could be added to Eliana's dialogue/doors/doorbell after completing who lives in the basement #1060 #1051 "No more dialogue in the current version" "Not available yet in the current version"

**Comment by Zuntti** [comment]
Changed and also added new objective for Eliana
