### ISSUE TITLE
Playtesting - Sinks excusively should not show recipes excluded by sink's modifiers

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#1062]
Perhaps with exception of shroom water if normal water is available at the sink (and vice versa with shroomed modifier) and dirty shroom water if dirty water is available at the sink (and vice versa).

**Comment by Zuntti** [comment]
I think the sinks already have it, but the hoses are missing it

**Comment by Nextej** [comment]
Yes, indeed sinks already have and hoses are missing it.

**Comment by Zuntti** [comment]
Fixed
