### ISSUE TITLE
Playtesting - Payphone doesn't display yellow notes, likely caused by reload after it was already used in this save/session

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#1064]
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/a5bb5e31-f9df-4569-bedf-d3b2514fa006)
[Player.zip](https://github.com/loiste-interactive/Obenseuer-Issues/files/13378774/Player.zip)

**Comment by Zuntti** [comment]
Fixed
