### ISSUE TITLE
Playtesting - "Find a Moon" objective, neither crafted directly from distillery nor refilled between containers, a full bottle of turnip moonshine cannot be given to Pate to complete the task anyhow

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#1066]
[Player.zip](https://github.com/loiste-interactive/Obenseuer-Issues/files/13379101/Player.zip)

**Comment by Zuntti** [comment]
Save where this happens? It seems to work for me

**Comment by Nextej** [comment]
[Crash_Tester.zip](https://github.com/loiste-interactive/Obenseuer-Issues/files/13379283/Crash_Tester.zip)
Autosave the latest, the moment before giving in the moonshine, slot 5 the moment before collecting it from distillery

**Comment by Nextej** [comment]
Restarting the game is what gave me an option to give pate the moonshine

**Comment by Zuntti** [comment]
Fixed
