### ISSUE TITLE
Playtesting - sometimes when moving empty containers (bottles) with a right click onto a slot occupied by another container with a liquid inside, the moved bottle disappears.

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#1067]
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/7083f5d3-9d78-4f18-b3de-c7edf653192e)
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/313c1bf3-3a36-458a-87eb-0e0640f0a05a)
[Player.zip](https://github.com/loiste-interactive/Obenseuer-Issues/files/13379461/Player.zip)

**Comment by Nextej** [comment]
[Crash_Tester.zip](https://github.com/loiste-interactive/Obenseuer-Issues/files/13379464/Crash_Tester.zip)
Autosave, try moving some empty bottles one by one into occupied slot by one of the moonshine bottles

**Comment by Oskutin** [comment]
Can't reproduce this

**Comment by Oskutin** [comment]
I remember fixing this exact same issue few days ago. It was caused by trying to merge stacks not working and then swapping the slots. And i fixed that by preventing slot swap when not moving entire stack

**Comment by Nextej** [comment]
There was another similar issue when tried to swap a bottle onto other items, this doesn't seem to happen anymore, but now the other way around does

**Comment by Nextej** [comment]
I don't think the issue is valid anymore
