### ISSUE TITLE
Playtesting - "Me Mash!" quest, if player returns to Pentti and states "Nope, where's my reward?", player can still start selling mash to Pentti afterwards, despite in the context of the dialogue, an offer of making mash for Pentti wasn't mentioned and "Tell Pentti you'll start making mash" objective is failed.

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#1068]
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/27e3f472-3eb6-4d5c-aa1a-dffd2dff2acd)
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/9132a36b-2fb1-4fb6-8f55-396590815414)

**Comment by Nextej** [comment]
Same goes for "Well, that your problem, where's my reward?" line, mash still can be sold afterwards.

**Comment by Zuntti** [comment]
Changed dialogue
