### ISSUE TITLE
Playtesting - "Me Mash!" quest, in response to Pentti that Max cannot make mash, any option proceeding "I could if I knew how to mash" doesn't do anything to advance the dialogue and just closes the dialogue window.

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#1069]
After selecting this
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/db5bede6-472b-448b-b2e8-df6908dd509c)
All of those options close the dialogue with Pentti, Pentti doesn't make any response
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/9c048b29-0f6b-4aac-acfa-f3ade8cce4f9)

**Comment by Zuntti** [comment]
Fixed
