### ISSUE TITLE
Playtesting - When player is sleeping, players is not getting notifications about paid rent and moved-in residents when woken up.

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#1074]

**Comment by Nextej** [comment]
Correction, player gets the notification, the game just doesn't wait with displaying the notification after the player wakes, so if player still sleeps after the notification was received, player won't see it in the first place and after waking up, it will already be faded out.

**Comment by Zuntti** [comment]
Now notifications should be visible when sleeping
