### ISSUE TITLE
Playtesting - player's bank account has too much money, attempting to withdraw more money than it is possible to display makes the money get removed from your pocket. The amount in bank is also too big to be displayed.

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#1078]
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/4f2e366a-3b18-425e-aea3-dbd830015cb0)
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/0a40743c-bffb-4e30-8079-49603a70a72f)

**Comment by Oskutin** [comment]
Fixed
