### ISSUE TITLE
Playtesting - "Letter for Emilie Palmer" quest and its objectives is given two times, the second time when player is at the other side.

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#1080]
To be clear, the quest is not duplicated on the quest list, just triggered two times.

**Comment by Nextej** [comment]
It seems like the game didn't saved state of the task being accepted, Mike acts as if the quest was declined and when approached, asks whether played had changed mind, despite the quest being already started.

Additionally, a reload of autosave made Make alive again.

**Comment by Zuntti** [comment]
Fixed
