### ISSUE TITLE
Playtesting - Mike's dead body at Tenement B no longer spawns any items at all, his inventory is entirely empty. (he should have one steel mechanical watch, gold ring and some junk).

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#1081]

**Comment by Nextej** [comment]
It seems like the game didn't saved state of the task being accepted, Mike acts as if the quest was declined and when approached, asks whether played had changed mind, despite the quest being already started.

Additionally, a reload of autosave made Make alive again.

**Comment by Oskutin** [comment]
Fixed
