### ISSUE TITLE
[Playtest] The light in the bar goes turn off if you stand in the corner, near the chest

### ISSUE THREAD

**Issue by Z-O-M-B-I-E** [loiste-interactive/Obenseuer-Issues#1082]
![20231116201433_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/46783282/0d94cd31-0a03-4e30-94bf-1efe19d9438b)
![20231116201435_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/46783282/cd8b9d3c-5d33-4e8a-9374-9ccf8a60b759)

**Comment by Oskutin** [comment]
Fixed
