### ISSUE TITLE
Playtesting - "Buying the Toll Bridge" quest issues.

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#1085]
1. The description suggest the quest should be started over phone, however when attempting to call, there's no way of expressing an interest of buying the bridge, the description also suggests that David told us to come to visit him, which is also not an available option on the call.
2. Task can only be started after already paid for the bridge, it should be started the moment player begins the talk with David about this topic (unless of course player had already called before and started it that way). Otherwise the quest is immediately started and completed.

None of that happened:
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/8e04ef4e-bffa-4e70-b394-28179317e51c)

**Comment by Nextej** [comment]
3. After buying the bridge and completing the task, you can yet again start a dialogue with David about being interested in buying the bridge.

**Comment by Zuntti** [comment]
Fixed
