### ISSUE TITLE
Playtesting - OSRAT rendering issues near walls and doors

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#1086]
Notable spot to test is the Deekula C3 apartment doors
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/1e763841-ff4e-4e84-b6ec-8a1c13cc08d2)
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/16bacd5e-c600-4d7d-b645-bf6652dcfdbf)
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/d246544c-901f-4fd5-b723-cd17e3831f8f)

**Comment by Oskutin** [comment]
?

**Comment by Oskutin** [comment]
Ah, the lights get culled

**Comment by Nextej** [comment]
Parts of the model disappear - bateries, lights, indicators, antenna, on the third screenshot, entire model is gone.

**Comment by Zuntti** [comment]
Fixed
