### ISSUE TITLE
Playtesting - Furnaces still kinda corrupt other machines and themselves.

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#1087]
1. When map is reloaded when a smelting process had started, Mashing Tuns (and likely alike) have their storage slots grayed out, opening and closing furnace UI (few times if must) fixes it.
2. Started crafting process in furnaces stops, does not progresses, to fix it the power button has to be turned off and on, process continues normally.

**Comment by Oskutin** [comment]
Can't get this to happen.
Should the mashing tun also be processing something?

**Comment by Nextej** [comment]
Mashing tun needs to have fuel started burning and furnance needs to be processing something, reload breaks it. Just tested.

**Comment by Nextej** [comment]
Additionally have some crafting items inside mashing tun, just in case

**Comment by Oskutin** [comment]
Nope, doesn't break. Got log?

**Comment by Oskutin** [comment]
Or a save.

**Comment by Nextej** [comment]
[Player.zip](https://github.com/loiste-interactive/Obenseuer-Issues/files/13384617/Player.zip)
[Crash_Tester.zip](https://github.com/loiste-interactive/Obenseuer-Issues/files/13384621/Crash_Tester.zip)
Slot 5, I've turned sheets into slab, put some shit and yeast into mashing tun slots, powered it with a plank and went out and in to get water from the hose outside, slots were broken

**Comment by Oskutin** [comment]
Could be this:
```
NullReferenceException: Object reference not set to an instance of an object
  at CraftingBase.GetRecipeMultiplier (Recipe recipe) [0x0000a] in <e683973ae0d347cb8ce69ecef2fb4a6e>:0 
  at manufacturingProcess.SetActiveRecipe (Recipe recipe) [0x00003] in <e683973ae0d347cb8ce69ecef2fb4a6e>:0 
  at manufacturingProcess.CheckItems (System.Boolean force) [0x0007e] in <e683973ae0d347cb8ce69ecef2fb4a6e>:0 
  at manufacturingProcess.OnPowerOn () [0x0006c] in <e683973ae0d347cb8ce69ecef2fb4a6e>:0 
  at CraftingBase.PowerOn () [0x00000] in <e683973ae0d347cb8ce69ecef2fb4a6e>:0 
  at CraftingBase.Start () [0x001ca] in <e683973ae0d347cb8ce69ecef2fb4a6e>:0 
  at manufacturingProcess.Start () [0x00010] in <e683973ae0d347cb8ce69ecef2fb4a6e>:0 
  at CraftingBase.OnLoadingGame () [0x0001f] in <e683973ae0d347cb8ce69ecef2fb4a6e>:0 
  at manufacturingProcess.OnLoadingGame () [0x00000] in <e683973ae0d347cb8ce69ecef2fb4a6e>:0 
UnityEngine.GameObject:BroadcastMessage(String, Object, SendMessageOptions)
UnityEngine.GameObject:BroadcastMessage(String, SendMessageOptions)
SaveController:BroadcastAll(String)
<LoadSaveGameDifferentScene>d__46:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
 
```

**Comment by Oskutin** [comment]
I assume in tenement?

**Comment by Nextej** [comment]
yeah

**Comment by Nextej** [comment]
dammit, it was slot 9

**Comment by Oskutin** [comment]
Slot 5 loads in Deekula B and when i go to tenement, its in default condition

**Comment by Nextej** [comment]
Slot's 9, got them mixed up.

**Comment by Oskutin** [comment]
Hmm, loads both of them being off for me.

**Comment by Nextej** [comment]
They are empty on the start, you gotta start the process, Autosave should have the processes started

**Comment by Oskutin** [comment]
Got the error

**Comment by Oskutin** [comment]
I think i got it fixed. One guestion: was the mashing tun processing something in the save?

**Comment by Nextej** [comment]
no

**Comment by Oskutin** [comment]
Fixed
