### ISSUE TITLE
Playtesting - Playerment: lamp levitates upon removing barrel; lamp should be automatically remove along it.

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#1089]
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/360f194b-ac16-46f1-b621-385bf5e794f5)
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/6926bfd8-5728-40e5-a8bd-a57ba20ca8ad)

**Comment by Zuntti** [comment]
Seems to work for me

**Comment by Nextej** [comment]
Oskutin said the same the last time I've reported it on .13 or .14, yet it still happens on playtesting build .16

**Comment by Oskutin** [comment]
Seems to be build only issue then

**Comment by Nextej** [comment]
Same applies to the pile of mold in the bathroom and the biohazard bags, when taken, mushrooms are left levitating.

**Comment by Zuntti** [comment]
Fixed

**Comment by Zuntti** [comment]
https://github.com/loiste-interactive/Obenseuer-Issues/issues/1523
