### ISSUE TITLE
Playtesting - Suggestion: Highlighted indicator for new items/recipes received from mail; similar one could be made for new recipes/blueprints found in the world.

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#1091]
Players will receive a lot of mail; and find a lot of recipes. It would be better if the inventory tab highlighted new stuff the player hadn't examined yet to point their attention towards it for them to hover over the recipe and preview the content.
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/d0e979cf-d2a3-4c8d-91ff-038b86a87b79)
It could also help with navigation for "Missing Debitcard" quest.

**Comment by Nextej** [comment]
@Zuntti This issue is now more prevailed in playtesting, since when you read Pekka or OS magazine, the recipes just pop-up without any sort of notification, so player does not know what's new and what's not

**Comment by Zuntti** [comment]
Added
