### ISSUE TITLE
Playtesting 0.3.16 - Police arrest during sleep are never triggered (despite log stating otherwise), doesn't seem like other events are either.

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#1092]
Been trying to sleep in Playerment and at Deekula B9 apartment beds
[Player.zip](https://github.com/loiste-interactive/Obenseuer-Issues/files/13385747/Player.zip)

**Comment by Oskutin** [comment]
Actually the log just states the arrest is the selected upcoming event, what happens after random amount of sleep. Usually the time to event is longer than the actual sleep time.

**Comment by Nextej** [comment]
Well, I spent a lot of time of sleeping in unsafe beds, either it's broken or really really rare to happen.

**Comment by Oskutin** [comment]
![kuva](https://github.com/loiste-interactive/Obenseuer-Issues/assets/5402150/7c4f6223-854e-4fbb-a8df-d3cea08efec0)

**Comment by Oskutin** [comment]
You got 7h on the first try.

**Comment by Oskutin** [comment]
Increased the propability
