### ISSUE TITLE
Playtesting - "Tunnel B2" quest, after acquiring keys to B2 tunnel, player can go to Deekula Basement first and finish the quest from the other way around, reading first the note, then entering B2 tunnel from opposite side, before they end up in Bergmann tunnels.

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#1095]
Related to #839

Not even a need to have both Hanss' key and B2 keys would solve it, it would need the doors to be openable from only one side (something like a sliding door lock) and require Hanss' key. Perhaps have an custom notification "Blocked from the other side" after using Hanss' key on Deekula Basement level

**Comment by Zuntti** [comment]
Fixed
