### ISSUE TITLE
Playtesting 0.3.16 - Lockpickable doors that have focus moving away from the doors, preventing player from lockpicking them.

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#1098]
- Outside: Eija's Grill doors
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/6f1175a1-2641-406f-b27d-87600c411518)
- Outside: Container Shack transition doors
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/c4df5b8e-4120-45f7-9908-8ea5bb21acfc)
- Outside: Kurahaara house
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/97d20fc7-cc9a-4ff7-a4ee-353408d6ca38)
- Kolhola: Doors between Dentist's office and waiting room
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/21d6c7b0-67ff-457c-9989-ade6d79a94bb)
- Kolhola: Doors between Dentist's office and apartment
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/7338053f-9e58-4659-a096-33357627c668)
- Kolhola: Hostel's laundry room doors
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/ddbb22e4-3097-4507-a900-0073c43194c4)

**Comment by Nextej** [comment]
- Cabinet lockers at gatehouse
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/1e835ed9-8769-4aa0-9b8d-6f9f9988d1d7)

**Comment by Zuntti** [comment]
Fixed
