### ISSUE TITLE
Playtesting 0.3.16 - game crash when loading a level

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#1099]
[Crash_2023-11-17_125008157.zip](https://github.com/loiste-interactive/Obenseuer-Issues/files/13391922/Crash_2023-11-17_125008157.zip)

**Comment by Oskutin** [comment]
Random?

**Comment by Oskutin** [comment]
From the logs and dump it looks the very same as other crashes
