### ISSUE TITLE
Make the getting-rid-of-addiction achievements to require first getting the addiction on that loaded savefile, otherwise just starting new game gives you "recovered" achievements, loading a different character who never had a specific addiction gives you "recovered" achievements and so on.

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#1102]
Some sort of flag checking: gottenAddiction=? recoveredFromAddiction=? or AddictionState=Never/Addicted/Recovered, so the game never has any of the addictions in recovered state before getting the addiction for the first time.

**Comment by Oskutin** [comment]
Should be already, but seems to be somewhat bugged
