### ISSUE TITLE
Update save migration potentially causes sinks placed in the apartment to be marked as "owned".

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#1105]
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/14db5a05-11b9-4ea4-b447-e034fb9cea3e)

**Comment by Oskutin** [comment]
.16 -> .17?

**Comment by Nextej** [comment]
.15 -> .17

**Comment by Nextej** [comment]
it seems like the issue is cause just by picking up the sink furniture and placing it down again.

**Comment by Oskutin** [comment]
Fixed
