### ISSUE TITLE
Cannot talk to Tenement bridge owner about buying bridge

### ISSUE THREAD

**Issue by DegenerateGroundState** [loiste-interactive/Obenseuer-Issues#1107]
Despite reading the note next to the toll booth, calling the owner, expressing interest in buying the bridge, and being instructed to visit his apartment I cannot talk to David Lund about buying the bridge. There are no dialogue options available other than Leave.
![no_options](https://github.com/loiste-interactive/Obenseuer-Issues/assets/23085959/b637519f-ff27-4e90-a9bd-bbeb7a004b55)
![need_talk](https://github.com/loiste-interactive/Obenseuer-Issues/assets/23085959/2af1ebe3-f0ce-4b2d-be74-097856be82c6)

**Comment by Zuntti** [comment]
Fixed
