### ISSUE TITLE
Public 0.3.17 - Getting released from jail and talking to guard or loading save will put player back in jail

### ISSUE THREAD

**Issue by CVariable** [loiste-interactive/Obenseuer-Issues#1109]
When player gets released from jail, talking to the guard after grabbing player stuff results in getting the dialoge of being caught, but without being thrown back in jail. Saving and loading in front of the guard results in being "caught trespassing" and being thrown back in jail.
![jail](https://github.com/loiste-interactive/Obenseuer-Issues/assets/45665371/14ee0e46-ca50-46ed-81f0-1cff1119ffb6)

**Comment by CVariable** [comment]
[jailsave.zip](https://github.com/loiste-interactive/Obenseuer-Issues/files/13400267/jailsave.zip)
This save was made after being released, taking my stuff and drinking some methanol. Loading it results in being caught as soon as the player moves.

**Comment by Ludvig11** [comment]
Also your previous inventory is gone after having spent a second consecutive time there:
![20231128192904_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/31344357/fad8d730-63a2-4d0f-859d-dca805badc2e)

**Comment by Oskutin** [comment]
Fixed
