### ISSUE TITLE
Suggestion for the pause menu ESC behavior

### ISSUE THREAD

**Issue by ontrigger** [loiste-interactive/Obenseuer-Issues#111]
Pressing esc anywhere in the pause menu will exit the pause menu. 
I feel like it would be much better if pressing ESC did the same as pressing the back button. I know it behaves the exact same way in INFRA, but there it made more sense as the pause menu was a tiny phone and you had no problem finding the back button.

**Comment by Zuntti** [comment]
Has already been implemented
