### ISSUE TITLE
Public 0.3.17 - Player is arrested without bounty upon starting game and loading in, but not upon reloading save

### ISSUE THREAD

**Issue by CVariable** [loiste-interactive/Obenseuer-Issues#1112]
This is a 1-day old character which 100% has never been caught trespassing or stealing, so should have no bounty. Yet, upon starting the game and loading the attached savefile, the player is arrested by market square police.
Upon arriving in the prison, the player is then immediately released.
This does not happen when just loading the save from in game or from the main menu, it only happens when the game is launched and the save is loaded for the first time.
[arrestbug.zip](https://github.com/loiste-interactive/Obenseuer-Issues/files/13401155/arrestbug.zip)

**Comment by Oskutin** [comment]
Hmm, it is caused by very expensive stolen goods in inventory (not a bug). The police behavior working only once is a known issue
