### ISSUE TITLE
Low fps in Kolhola A

### ISSUE THREAD

**Issue by Z-O-M-B-I-E** [loiste-interactive/Obenseuer-Issues#1113]
Fps in Kalhola A is about ~30-40. When it's 80-100 outside.

**Comment by Kastuk** [comment]
Whats your settings?
Do you did something inside that Kolhola?
is there many items dropped? 
Its not Deekula A?

**Comment by Nextej** [comment]
Yeah, Kolhola has the worst optimization, even Outside on average is better.

**Comment by Z-O-M-B-I-E** [comment]
Hm. If you start a new game, the problem disappears.
[Slot2.zip](https://github.com/loiste-interactive/Obenseuer-Issues/files/13401401/Slot2.zip)

**Comment by Z-O-M-B-I-E** [comment]
The problem is probably in an abandoned apartment with traps, there is a lot of Moldy Waste

![20231118231607_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/46783282/93ad8a25-a33f-4f40-b7b5-3d483e112a59)
![20231118231612_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/46783282/eded15bd-c4a4-4dee-886e-04858080d814)

**Comment by Z-O-M-B-I-E** [comment]
Is that a lot of rotting fish?

![20231118232900_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/46783282/c8d9cea3-dbe7-4612-8865-f4c2cc410e1e)
![20231118232908_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/46783282/32febac3-2a7f-4b2c-92e1-cab5562a0ea0)
![20231118232910_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/46783282/8551b71b-f45d-42bb-a757-3b560572c595)
![20231118232912_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/46783282/a6c605c4-d8bb-4243-a2c4-c3c5511b726e)
![20231118232918_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/46783282/f365871c-fbbb-44c5-b243-b822d3cdc928)

**Comment by Z-O-M-B-I-E** [comment]
I broke the e key, but optimized it. Now ~80 fps

**Comment by Z-O-M-B-I-E** [comment]
I suppose need make to do self-destruction of mold

**Comment by Oskutin** [comment]
Where did all that mold come from

**Comment by Z-O-M-B-I-E** [comment]
> Where did all that mold come from

Fish?

In Deekula A is also such a place at the very top

![20231119000752_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/46783282/66cb2349-fa0d-451a-88da-d1e743e8f944)

**Comment by Z-O-M-B-I-E** [comment]
Oh no, she appeared again

**Comment by Oskutin** [comment]
What does the log say?

**Comment by Z-O-M-B-I-E** [comment]
> What does the log say?

> Hm. If you start a new game, the problem disappears.
> 
> [Slot2.zip](https://github.com/loiste-interactive/Obenseuer-Issues/files/13401401/Slot2.zip)

[Player.log](https://github.com/loiste-interactive/Obenseuer-Issues/files/13402884/Player.log)

**Comment by Z-O-M-B-I-E** [comment]
It appears immediately after loading the save, even if you remove everything before that

**Comment by Z-O-M-B-I-E** [comment]
This has been partially fixed. Everything seems to be fine with the refrigerator, but the mold on the floor has become more aggressive

**Comment by sarahlupa** [comment]
Just came here to confirm Im down to 10 fps after sleeping in the building, in the hostel, and theirs copious amounts of mold. I'm trying to pick it all up to help with performence, but I can't seem to pick it all up. xD All good though I barely go in that building and atleast it doesn't crash.

**Comment by Z-O-M-B-I-E** [comment]
Fixed
