### ISSUE TITLE
"Getting Started" quest, if player starts additional renovations before returning to Malone to report about the first renovation, the additional ones won't be counted in to the next objective of "Start 5 renovations"

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#1116]
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/8b218e67-1257-488b-aea3-e81099714a4e)
already have 3 more going on 
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/eb11e5c6-f1a1-4f87-9e06-7181bd30e4e4)

**Comment by Zuntti** [comment]
Fixed
