### ISSUE TITLE
Dead uproot plant of wheat is invisible.

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#1117]

**Comment by Nextej** [comment]
Same applies to Rye, it's not just the dead uproot but in general the starting growing stage of Rye and Wheat.
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/f4f947fe-ec8f-42f2-ad01-95cd39b80532)

**Comment by Nextej** [comment]
fully planted rye plantation
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/ec970b12-1241-44cc-9a46-115e9bb27e62)

**Comment by Oskutin** [comment]
Fixed
