### ISSUE TITLE
Cannot eat Mattox Candy Bag

### ISSUE THREAD

**Issue by rosysyntax** [loiste-interactive/Obenseuer-Issues#1119]
See title. Mattox candy bag cannot be consumed.

**Comment by rosysyntax** [comment]
Looks like Evil Bear Candy Bag is also unable to be consumed.

**Comment by Oskutin** [comment]
Can't reproduce these either

**Comment by rosysyntax** [comment]
Likely related to bug #1121 , as it was stolen.
