### ISSUE TITLE
Buying drinks from Pentti does nothing

### ISSUE THREAD

**Issue by rosysyntax** [loiste-interactive/Obenseuer-Issues#1120]
See title. Tried to buy different beverages from Pentti in the basement bar and they didn't appear in my inventory or anywhere around me. Seems to be totally bugged.

**Comment by Oskutin** [comment]
Can't reproduce this neither, can you give me screenshot of the Pentti's trade UI

**Comment by rosysyntax** [comment]
![2023-11-19 15_03_01-Obenseuer](https://github.com/loiste-interactive/Obenseuer-Issues/assets/121929904/15d4fdb7-a613-40c4-ab09-fceb885f2647)
![2023-11-19 15_03_20-Obenseuer](https://github.com/loiste-interactive/Obenseuer-Issues/assets/121929904/09a6b2d7-fb60-4ace-bda4-a61efed246e5)

Here are two screenshots - before buying the mushroom kilju and afterwards.

[Anya_Karenovich.zip](https://github.com/loiste-interactive/Obenseuer-Issues/files/13404497/Anya_Karenovich.zip)

I've also attached my saves - slot 2 is before purchase, slot 1 is after. Hope this helps isolate the issue.

**Comment by rosysyntax** [comment]
Ah, nevermind. The issue seems to have resolved itself, and the purchased item appears below. Weird!
