### ISSUE TITLE
Can't eat/open stolen canned food

### ISSUE THREAD

**Issue by rosysyntax** [loiste-interactive/Obenseuer-Issues#1121]
I was about to open a can when it said "No can opener". I looked at my can opener, and it was at 57%. Thought that was odd, so I got a new can opener later and had the same issue. I then noticed I COULD open another can that was not stolen. So it seems like stolen canned food won't open. This was tested on Canned Pineapple, specifically.

**Comment by CVariable** [comment]
Was the cab opener in your inventory and not your backpack? Are you sure the food was marked stolen, not owned? I've eaten plenty of stolen canned food, but owned food can not be consumed

**Comment by Oskutin** [comment]
Okay,you can eat from stolen cans, but not if its owned/store owned, where it incorrectly states "No can opener".

**Comment by rosysyntax** [comment]
The can opener was in my inventory, yes. Store owned sort of makes sense, but I was definitely attempting to eat foods I had stolen elsewhere that didn't belong to a store.

I also noticed some weird behavior regarding store alarms going off when I had stolen goods from other places in my inventory, so this may be related. Last time was when I stole the disinfectant from the hostel building lobby, then went into the drug store. This immediately set off the alarms. But this has also happened randomly with stolen food.

**Comment by Nextej** [comment]
On previous updates, some items in Kolhola spawned with store ownership, could not be used the same way, it has been fixed since but I wouldn't be surprised if another such case was left unchecked.

**Comment by rosysyntax** [comment]
The disinfectant in Kolhola lobby is definitely store tagged. Here are my saves so this can be verified - slot 2 is when I took the disinfectant (which was not marked stolen in-world, but is labeled stolen in my inventory!), and slot 1 is after walking into the drug store, with the alarms triggered. If you load slot 1 and go to the counter, they actually ring it up, too.

[Anya_Karenovich.zip](https://github.com/loiste-interactive/Obenseuer-Issues/files/13404516/Anya_Karenovich.zip)

**Comment by Oskutin** [comment]
Fixed
