### ISSUE TITLE
After .17 update, Kolhola A13 is permanently locked, cannot be lockpicked either, before the update it was always open

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#1125]
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/b7b94113-dcba-4419-9ba4-6563d00b8c5b)

**Comment by Oskutin** [comment]
Fixed

**Comment by Z-O-M-B-I-E** [comment]
If you load an old save, it is not fixed
