### ISSUE TITLE
White screen - 0.3.17

### ISSUE THREAD

**Issue by Hiddenfoxwere** [loiste-interactive/Obenseuer-Issues#1128]
After effect alcohol - does not pass.

[Slot3.zip](https://github.com/loiste-interactive/Obenseuer-Issues/files/13403634/Slot3.zip)

**Comment by Oskutin** [comment]
Do you have logfile?

**Comment by Hiddenfoxwere** [comment]
Forgot about that.
[logs.zip](https://github.com/loiste-interactive/Obenseuer-Issues/files/13403666/logs.zip)
Both.

**Comment by Oskutin** [comment]
Does reloading latest autosave before this happened work?

**Comment by Hiddenfoxwere** [comment]
Some effect - in ~7:30

**Comment by Oskutin** [comment]
This is potentially fixed now
