### ISSUE TITLE
Public 0.3.17 - Bank Funds get messed up when exchanging back and forth

### ISSUE THREAD

**Issue by CVariable** [loiste-interactive/Obenseuer-Issues#1131]
Exchanging RM into OC into the bank and then trying to get rm back is impossible.
Also, the exchange rate of 1 RM to 98 OC seems broken, given the last value i remember is 0.06 OC per RM.
A nice bonus would be if the game rounded the .79999 number to .8.

Before exchanging to OC:
![grafik](https://github.com/loiste-interactive/Obenseuer-Issues/assets/45665371/26ae3a72-6895-49a9-874a-4439e7769d0f)
After: 
![grafik](https://github.com/loiste-interactive/Obenseuer-Issues/assets/45665371/d0687655-46f1-464c-a151-c1488fca44f8)

Savefile for experimenting:
[bankbroken.zip](https://github.com/loiste-interactive/Obenseuer-Issues/files/13403838/bankbroken.zip)

**Comment by CVariable** [comment]
It looks like the bank's exchange rate for RM to OC goes crazy once the bank runs out of RM. I've gotten exchange rates as high as 138oc per rm, meaning i got like 70000 OC for 500RM. It doesn't seem right

**Comment by Oskutin** [comment]
Fixed
