### ISSUE TITLE
Tenement B door

### ISSUE THREAD

**Issue by Z-O-M-B-I-E** [loiste-interactive/Obenseuer-Issues#1132]
The plank on the door prevents you from interacting with it inside Tenement B

![20231119153421_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/46783282/f47e5616-7fde-4d46-a412-923fe86fde88)
![20231119153422_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/46783282/06a7c478-69f2-477c-98fe-37f3aca867c6)

**Comment by Oskutin** [comment]
Fixed
