### ISSUE TITLE
Public 0.3.17 - Agnes Takala can be rented despite not meeting requirement

### ISSUE THREAD

**Issue by CVariable** [loiste-interactive/Obenseuer-Issues#1135]
![grafik](https://github.com/loiste-interactive/Obenseuer-Issues/assets/45665371/a15f41bb-bf70-4e97-81a8-59908b791b93)
Agnes Takala is supposed to require a shabby stairwell, but she can be rented with just a makeshift stairwell upgrade.

**Comment by Nextej** [comment]
I think it might be a general case where residents can be rented ignoring any tenement upgrade, despite them requiring otherwise, not just limited to Agnes.

**Comment by Zuntti** [comment]
Fixed
