### ISSUE TITLE
Loading save produces gigantic empty tin can

### ISSUE THREAD

**Issue by DegenerateGroundState** [loiste-interactive/Obenseuer-Issues#1137]
Saved the game with a tall empty tin can on my mattress quit and reloaded to discover the can has become huge. At first I thought the level geometry hadn't loaded in correctly but it turns out I was inside it!
[Player.log](https://github.com/loiste-interactive/Obenseuer-Issues/files/13404490/Player.log)
[Slot1.zip](https://github.com/loiste-interactive/Obenseuer-Issues/files/13404491/Slot1.zip)
![3](https://github.com/loiste-interactive/Obenseuer-Issues/assets/23085959/208901ec-9fa6-4962-adbb-0fddf94d9fbf)
![2](https://github.com/loiste-interactive/Obenseuer-Issues/assets/23085959/da7a7f6b-7b99-448d-8cba-f44aa356e9cf)
![1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/23085959/4c8fcf66-6ea6-491f-8244-f8eae5898981)

**Comment by Oskutin** [comment]
Cant reproduce this. Tried placing cans on the bed and save and load.

**Comment by Zuntti** [comment]
Fixed
