### ISSUE TITLE
Debit card on ground outside ATM, intentional?

### ISSUE THREAD

**Issue by DegenerateGroundState** [loiste-interactive/Obenseuer-Issues#1139]
Noticed a debit card spawned on the ground in front of the ATM, if this is intentional the graphic probably shouldn't be standing on edge and half clipped through the ground.
[Autosave.zip](https://github.com/loiste-interactive/Obenseuer-Issues/files/13404659/Autosave.zip)
[Player.log](https://github.com/loiste-interactive/Obenseuer-Issues/files/13404663/Player.log)
![a](https://github.com/loiste-interactive/Obenseuer-Issues/assets/23085959/c96d979f-29fb-4a0c-b0c4-e17e27996cf7)

**Comment by Oskutin** [comment]
Fixed
