### ISSUE TITLE
Jarmo Pettinen standing on desk.

### ISSUE THREAD

**Issue by carys-the-weed-cloud** [loiste-interactive/Obenseuer-Issues#1142]
I moved Jarmo Pettinen into Apartment 5, and upgraded it to Fine, and found Jarmo standing on his desk in his bedroom.

![Untitled](https://github.com/loiste-interactive/Obenseuer-Issues/assets/36204825/e45529c2-6e3d-417f-b0f9-e5b5b1347bbf)

**Comment by carys-the-weed-cloud** [comment]
I also moved Sara Claine into Apartment 3 and upgraded it to Fine and found her clipped into the kitchen table.

![Untitled](https://github.com/loiste-interactive/Obenseuer-Issues/assets/36204825/910cf9a9-cabc-4322-801c-b4fcef437579)

**Comment by carys-the-weed-cloud** [comment]
Ingrid Claesson moved into Apartment 8 also wants to stand on her desk.

![Untitled](https://github.com/loiste-interactive/Obenseuer-Issues/assets/36204825/93cd4139-f3cd-40ef-a897-c3c023929781)

**Comment by Zuntti** [comment]
Fixed
