### ISSUE TITLE
Apartment 5 Fine Balcony Front texture clipping

### ISSUE THREAD

**Issue by carys-the-weed-cloud** [loiste-interactive/Obenseuer-Issues#1143]
I upgraded Apartment 5's Balcony Front to fine and the forward facing window has texture fighting/clipping going on. It is much more active than a screenshot can show.

![Untitled2](https://github.com/loiste-interactive/Obenseuer-Issues/assets/36204825/163e2fd2-ccd1-472f-9c59-9413d7ff7810)

**Comment by carys-the-weed-cloud** [comment]
This actually appears to happen in all Balcony Front's with the front facing window.

**Comment by carys-the-weed-cloud** [comment]
I think this is related that all Balcony Back on the left side, facing the back of the building, that are upgraded to Fine are just black.

![Untitled](https://github.com/loiste-interactive/Obenseuer-Issues/assets/36204825/488935cf-085d-441d-935c-778f39fb2fba)

**Comment by Zuntti** [comment]
Fixed
