### ISSUE TITLE
Feature: Map landmarks

### ISSUE THREAD

**Issue by Zuntti** [loiste-interactive/Obenseuer-Issues#1146]
1. Notification will appear when you find a landmark such as O-market or Deekula A
2. Maybe it would also appear gray on the map when a character mentions its location
3. Landmark would also have more information about the place. 
For example, when you find a Deekula A printing press it would be in the tooltip of that landmark or DR. Pena

**Comment by CVariable** [comment]
I think that feature would help a lot as the game expands into more areas like bazaar and mines, at the current level it's fairly easy to keep track of what is where after a few hours

**Comment by Oskutin** [comment]
![kuva](https://github.com/loiste-interactive/Obenseuer-Issues/assets/5402150/ac03ccb2-5f71-4330-9827-9e56d2a5d44a)
O market and Pharmacy could be preplaced printed icons, while others could be discoverable drawed icons.

Could have compass item and GPS navigator item added at one point.

**Comment by Nextej** [comment]
Perhaps if player talks to rentable NPCs, their location should be marked as "Potential resident"? Not sure if the marker should reveal the name too, or just that there is an NPC, I think that showing requirements would be too much.
