### ISSUE TITLE
Strange empty hatch nearby to the caravan

### ISSUE THREAD

**Issue by Z-O-M-B-I-E** [loiste-interactive/Obenseuer-Issues#1148]
There's not even space in it

![20231119145229_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/46783282/3321f12a-edac-44b8-bc15-c3357a4f3a2b)
![20231119145230_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/46783282/784d6073-0280-4b5e-9a56-d94d6afe6488)
![20231119145232_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/46783282/d301bdeb-c4f6-4b72-9861-f786b36beaf7)

**Comment by Oskutin** [comment]
fixed
