### ISSUE TITLE
Issues with B11

### ISSUE THREAD

**Issue by CBS-S** [loiste-interactive/Obenseuer-Issues#115]
- Several items (empty can, full bottle of water, mash recipe) are marked as "take" but most things are marked "steal"; not sure if this is a bug or deliberate
- Typo in fungal patients letter: "patiens" instead of "patients" at the beginning of second paragraph
- No way to sit on stool (probably not really a bug, but it looks like you should be able to sit there)
- Pressing X at the phone types the number 1
- Pressing P at the phone closes the phone menu and makes the screen go fuzzy
- WASD in the phone menu moves the selected button around, which is nice, but neither enter nor E will let you enter the button you've selected
- Not sure if this is an issue with the room, exactly, but the clock says 12:23 (I think) and if you ask the time from Amanda at the bottom of the stairs she says 21:17.

**Comment by Oskutin** [comment]
Moved the phone control issues there: https://github.com/loiste-interactive/Obenseuer-Issues/issues/6

Other bugs in this location are fixed.
