### ISSUE TITLE
Suggestion: Cleaning mode available for the rest of the Playerment, so player has to clean the apartments as part of examination objective before they can be renovated.

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#1159]
This would also make bleach, cleaning spray and disinfectant more useful than one time triviality at the start. Also you could allow taking the found furniture for yourself or to sell.

Stairwell could also get a much more limited decorative mode that could allow to place stuff like letters or signs and dumpster and move them around.

**Comment by Oskutin** [comment]
Should be requirement of starting upgrades, but not examination.

**Comment by Nextej** [comment]
Whatever that works as a clear indication the apartments need to be cleaned before starting renovation.

**Comment by Nextej** [comment]
Two more thoughts, to be able to clean apartment, it should be fully examined first. Second one, perhaps add trashbag item buyable at O-Market that is required to pickup regular trash (stuff that is neiter given as items nor is put into the furniture list), that would be effective an inverse versions of cleaning spray, counting up uses with each collected trash until the bag "is full" and getting visually full.

**Comment by Nextej** [comment]
Apartments wih SMV bodies inside them should require calling Fungal Treatmen Unit over the phone, after they are initiailly examined, after calling them, within 2 hours a hazard tarp should appear and take next like 12 hours to remove the body, so the player can finalize cleaning state. FTU should probably also take all the shrooms, should player have not taken them before, after the hazard tarp appears, the apartment should also be blocked off I think (perhaps something like that for certain renovations too?)
