### ISSUE TITLE
Prices and requirements for updating tenement

### ISSUE THREAD

**Issue by Z-O-M-B-I-E** [loiste-interactive/Obenseuer-Issues#1164]
Need to add a past improvement

![20231120212923_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/46783282/fbc7e8b2-741c-422d-8cad-8aa59eeef192)

![20231120213015_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/46783282/b01e0727-cef2-40b5-aec7-a3edfb4912d4)

Need to fix final price

![20231120212936_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/46783282/7bb01826-4b7e-41f9-8a84-25723a0a3c1d)

**Comment by Nextej** [comment]
@Oskutin I think it's about that higher level Basement and Heating don't require lower level versions of themselves (which probably all the Basement higher levels should require Makeshift as a starter, but I guess that's up to Zuntti's basement ideas).

And the second thing is that Good electricity has lower RM price than Shit electricity.

**Comment by Z-O-M-B-I-E** [comment]
> @Oskutin I think it's about that higher level Basement and Heating don't require lower level versions of themselves (which probably all the Basement higher levels should require Makeshift as a starter, but I guess that's up to Zuntti's basement ideas). Otherwise I think heating is good as it is.
> 
> And the second thing is that Good electricity has lower RM price than Shit electricity.

Yes
