### ISSUE TITLE
Talking with Max Masher gives us a Beer Mash, while Max talks about the ingredients of one of possible Mushroom Mashes

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#117]
Not sure if that's intentional or not
![image](https://user-images.githubusercontent.com/44178400/234082795-4e13ee4f-eb5f-4df7-a591-3c753f789db1.png)

**Comment by Oskutin** [comment]
He also tells that Pentti hates the mushroom version, and for him he makes the normal mash.
