### ISSUE TITLE
Public 0.3.18 - Cannot complete Buying Toll Bridge Quest

### ISSUE THREAD

**Issue by CVariable** [loiste-interactive/Obenseuer-Issues#1171]
![grafik](https://github.com/loiste-interactive/Obenseuer-Issues/assets/45665371/67b7ffcc-6fe1-4cec-85a7-324463f8dc0b)
Both i and @Fish on OS Discord are unable to talk to David Lund to buy the Bridge. Calling him changes nothing.
My save is migrated from .17, so i'm not sure if it's a save migration issue. Need someone else to confirm.
Here is my save to try:
[bridgebuying.zip](https://github.com/loiste-interactive/Obenseuer-Issues/files/13420168/bridgebuying.zip)

**Comment by CVariable** [comment]
Fish has confirmed they created their character after the update today, so it seems this issue affects old .17 and new .18 saves

**Comment by Zuntti** [comment]
Fixed
