### ISSUE TITLE
Tenant - Ingrid Claesson

### ISSUE THREAD

**Issue by rams95blue** [loiste-interactive/Obenseuer-Issues#1175]
**After you assign and she move to selected apartment, she will still stay in the streets. 
Don't know if this bug only applies to this NPC.**

![1111](https://github.com/loiste-interactive/Obenseuer-Issues/assets/113950769/f0ba6b96-3dc3-438a-8c9e-ed98e6dd82be)
![333111](https://github.com/loiste-interactive/Obenseuer-Issues/assets/113950769/fa196636-b640-40d0-9a70-c7be2b748b99)

**Comment by CVariable** [comment]
Happens to all npcs, and is a known graphical bug. It'll be fixed once the major stuff is done as it doesn't impact the gameplay

**Comment by Zuntti** [comment]
Fixed
