### ISSUE TITLE
Tiny Cage, graphical/animation issues.

### ISSUE THREAD

**Issue by Jawnyboi** [loiste-interactive/Obenseuer-Issues#1177]
The tiny cage has the rat models inside misaligned so that one will stick out of the cage, as well as the door of the cage opening on the wrong axis when interacted with.

![Clipboard01](https://github.com/loiste-interactive/Obenseuer-Issues/assets/4951013/0a136ed3-31ce-4b80-a92c-f415986f51c8)

**Comment by Zuntti** [comment]
Fixed
