### ISSUE TITLE
Lonkka Kurahaara is at three different places at the same time during the day

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#1178]
Bar
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/08438d06-e033-43f4-a897-84bb72c8e610)
House
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/5b05b0d0-68fd-4c5a-9def-4cd2d2fac1a3)
Stall
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/45c3d6da-d59a-4de4-8c58-a9010f34c507)

Only for the stall he is gone during the night.

**Comment by Zuntti** [comment]
Fixed
