### ISSUE TITLE
Martta Lapinjoki has Ville Skoldgangest (which is available to rent separately) and Mirjam Freighter as part of the family.

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#1180]
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/ffd7af56-b61e-4752-99be-b85653ff8e77)
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/83b67f29-2e27-4750-8d5e-4dec979552d8)

**Comment by Zuntti** [comment]
Fixed
