### ISSUE TITLE
Bypassing keypad/card reader doors

### ISSUE THREAD

**Issue by Definitive-Dude** [loiste-interactive/Obenseuer-Issues#1185]
Some doors with a keypad can be opened when standing close enough to them (I think it counts the player as standing on the other side) example in the images is the pharmacy door.
It also works the other way around, for example from inside the boss's penthouse when I got close enough to the door it said it's locked (after I got the code and got in).

![1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/151375023/bf1358fc-fd08-43a6-a695-a2031d9bfb11)
![2](https://github.com/loiste-interactive/Obenseuer-Issues/assets/151375023/f570f772-0404-4167-b389-7324364adf7b)
![3](https://github.com/loiste-interactive/Obenseuer-Issues/assets/151375023/3df939be-c8aa-4070-b7e7-ba9e0ef34f04)

**Comment by Zuntti** [comment]
Fixed
