### ISSUE TITLE
Feedback: The OSRAT device should not be partially hidden when walking

### ISSUE THREAD

**Issue by ontrigger** [loiste-interactive/Obenseuer-Issues#119]
Walking with the osrat device in hand causes it to move down, obscuring the signal strength arrow. Investigating the otherside is really annoying when you have to stop every time you want to see the signal strength.
![20230425003718_1](https://user-images.githubusercontent.com/8556074/234122733-76783ff3-dc91-4add-a34b-d11233c5cfcb.jpg)

**Comment by Nextej** [comment]
Perhaps holding alternative fire button (RMB) should keep the OSRAT leveled fully in player's view, so it looks as same as when standing still?

**Comment by Zuntti** [comment]
Changed animation
