### ISSUE TITLE
Furniture needs to have a way to display short descriptions, similar to regular items, to explain their uses and encourage players to try them out.

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#1193]
It's mostly applies to stuff like 
- Furnaces (what are they used to "to smelting and forming metals" (if specific metals per brick and electric furnaces, state which), what are they powered by "by acetylene gas"),
- farms (explain whether they can grow large plants, whether they allow growing vine-like plants, etc. how the sun/moist modifiers change depending on location),
- Lathe/Drill (explain what they are used for "processing and production of metal items", what skills can be trained on them "perfect to utilize your machining skills", say that they require electrical power once that works),
- Portable Generator (why the hell it's even in the game and what it gives and what is powered by, "by diesel oil") , Furniture Workbench (allows to easily craft furniture from your own workshop/apartment),
- Red Barrel, Blue Plastic Barrel and other crafting furniture (say it's a furniture commonly used to modify and craft into new usable furniture),
- Mashing Tun, Fermenting Barrel, Distillery (say what each does, how to power it, etc.),
- fridge and freezers (say that they need electrical power once that works, say that they can refrigerate and freeze perishable food)
- Sawbucks (same as with lathes/drills),
- Acquarium (state that it's used for growing fish, not storing them).

**Comment by Nextej** [comment]
Perhaps besides hovering your mouse over furniture inventory or at the store, have it displayed at the furniture preview?
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/1a840f1d-1e27-4512-a54d-612f24512d36)

**Comment by Zuntti** [comment]
Added
