### ISSUE TITLE
jomppe takes gold trays

### ISSUE THREAD

**Issue by pinkamedic** [loiste-interactive/Obenseuer-Issues#1196]
i was trying to sell some crops when i noticed i was getting a shit ton of coins and idk why the crops were crap quality and i really shouldint be getting 29k for them and after some testing it turns out jomppe is taking the gold plate i had, i really doubt jomppe is a millionaire that buys gold trays lol

**Comment by pinkamedic** [comment]
i think i know why he accepted it as i stole the goldtray from a bag in his greenhouse

**Comment by Zuntti** [comment]
Already fixed
