### ISSUE TITLE
Went to jail multiple times. Third time merely over of the door had opened by itself/the prison guard.

### ISSUE THREAD

**Issue by Ludvig11** [loiste-interactive/Obenseuer-Issues#1198]
Cop arrested me, I spent time for stealing a backpack, then an other cop questioned and arrested me by talking to him. Third time right after I got the achievement "Petty Criminal / Low Bounty" and the prison guard apparently thought I had escaped, wondered why the gate was open, so maybe that's related somehow?

[Lumi_Pakkanen.zip](https://github.com/loiste-interactive/Obenseuer-Issues/files/13433115/Lumi_Pakkanen.zip)

5 Saves posted. Edit: Video: https://www.youtube.com/watch?v=dlIcfNU2MeU

**Comment by Zuntti** [comment]
Related to https://github.com/loiste-interactive/Obenseuer-Issues/issues/1189
