### ISSUE TITLE
Can't fill bottles at sinks

### ISSUE THREAD

**Issue by CBS-S** [loiste-interactive/Obenseuer-Issues#120]
None of the sinks I've checked have the option to fill bottles, even though each one has qualifiers in the interface (clean, dirty, etc.) that make me think I should be able to get water from them.

**Comment by Oskutin** [comment]
You put the bottles on sink's inventory?

**Comment by CBS-S** [comment]
I tried to but it was greyed out.

**Comment by Oskutin** [comment]
Duplicate of https://github.com/loiste-interactive/Obenseuer-Issues/issues/99
