### ISSUE TITLE
Bugs I have found with pics

### ISSUE THREAD

**Issue by Im-Brandfall** [loiste-interactive/Obenseuer-Issues#1200]
In the hostel, on the table, bottles usually spawn there but sometimes a bottle will keep spawning under the table out of reach. Trash usually spawns floating over the river to the far east near the little buildings where the one stop shop is. Eija's grill doesn't ever give me the food I purchase from her. In Deekula C at the cheap rat vending machine you can get stuck in between the machine and the chair and fall out of the world. If I call the owner of the toll bridge and ask to buy it and start the quest, the guy will just keep telling me to buzz off. A bottle tends to spawn in between the tables near Eija's and you can get stuck there. Prison can actually kill you if your crime is too high. Edit: It's impossible to pickup earrings og any kind when they are on the ground or not in an inventory. A mysterious woman appears for a split second behind the tents in front of the Deekula Complex and disappears, there is a trigger on the ground that spawns her for a second.

I don't know how to prove the Eija grill one as I have no way to make video and the falling through the world one happened once I haven't been able to recreate it yet.

![Screenshot_3](https://github.com/loiste-interactive/Obenseuer-Issues/assets/50027813/e9c177a8-1b63-4ac7-86f0-995d4086843b)
![Screenshot_4](https://github.com/loiste-interactive/Obenseuer-Issues/assets/50027813/a5dfdab9-7abe-4e19-bbfd-be388ec30432)
![Screenshot_5](https://github.com/loiste-interactive/Obenseuer-Issues/assets/50027813/815372be-97d5-4a7d-80d9-814acd39dd03)
![Screenshot_9](https://github.com/loiste-interactive/Obenseuer-Issues/assets/50027813/395f1450-c3f4-4b91-b9fa-df580b3a8515)
![Screenshot_11](https://github.com/loiste-interactive/Obenseuer-Issues/assets/50027813/694d6c84-71f0-4d07-bde9-8e583f0b9f73)

**Comment by Oskutin** [comment]
Fixed
