### ISSUE TITLE
Kolhola A | Apartment A18 & possibly more

### ISSUE THREAD

**Issue by rams95blue** [loiste-interactive/Obenseuer-Issues#1201]
Balcony door in a glitched state with a "open closed" prompt.

https://github.com/loiste-interactive/Obenseuer-Issues/assets/113950769/122ec8af-f2d4-4b3f-984d-a117f7d9d820

(Version 0.3.18)

**Comment by Jawnyboi** [comment]
I've noticed this on several of the balcony doors within the locked Kolhola apartments, it's not just this one.

**Comment by Z-O-M-B-I-E** [comment]
Same

![20231121040631_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/46783282/11a137dd-9a3f-4460-a430-28a5fe1699cb)
![20231121040635_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/46783282/4f975c57-b972-4a51-92a3-15df76c11a07)
![20231121040655_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/46783282/00326129-7a66-40f3-bf2d-d6716e5b338a)
![20231121040702_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/46783282/18c1ca3a-f084-41e7-960c-7d0a3f67b80d)

**Comment by Oskutin** [comment]
Fixed
