### ISSUE TITLE
Public 0.3.18 - Crafted Flower Pot is marked as Owned in player apartment, causing grown plants to be marked stolen

### ISSUE THREAD

**Issue by CVariable** [loiste-interactive/Obenseuer-Issues#1202]
Reported by @VantaGhost on Discord (#help-and-issues, 10:45 22.11.2023).
A flower pot that was crafted by the player from bought, not stolen components, placed in the player apartment is marked as Owned.
That results in plants grown from seeds that are marked neither owned nor stolen to have the stolen flag.
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/45665371/75773b9a-4a5a-4826-b987-c4dca00099cb)
This does not happen with purchased plant beds. 
Testing of crafted plant beds and purchased Flower pots is needed.

**Comment by Zuntti** [comment]
Fixed
