### ISSUE TITLE
Leon Borg's dialogue still act as he was living on the street.

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#1204]
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/aeae4b3c-841d-4954-be72-64496ec9e32a)
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/2f221f57-ee29-43e5-9616-007f626628c4)

**Comment by Zuntti** [comment]
Fixed
