### ISSUE TITLE
Farms and rat cages, amount of available slots is not shown until plant/rat is planted, it was being shown properly before, it's especially important for rat cages to know how big they are

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#1206]
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/79e385a3-34dc-4387-9752-b957cb41c962)
Shows up after being planted
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/693d65af-25a1-41f2-a8c0-b4104506d7ab)

**Comment by Zuntti** [comment]
Fixed
