### ISSUE TITLE
Potentially add the cheapest, weakest flashlight to the O-Market.

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#1207]

**Comment by Kastuk** [comment]
Handheld mushroom lamp (like it been in prototype), can useful even alongside proper light source.
...but not so for OMarket, as it more like symbol of shroom-users.

**Comment by Nextej** [comment]
Clarification, add the already-existing basic flashlight to the O-Market offer, not add entirely new one from scratch.

**Comment by Oskutin** [comment]
![kuva](https://github.com/loiste-interactive/Obenseuer-Issues/assets/5402150/80ddeef9-cc49-4912-8ba7-810dcc0fe8df)
there happens to be a slot for it

**Comment by Oskutin** [comment]
Added
