### ISSUE TITLE
Mental Health % display was inverted, but the colors of the icon were not, when Mental Health is low, it's green

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#1208]
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/b0d8cab7-5997-4f42-ae85-2bf842f70dfc)

**Comment by Oskutin** [comment]
I'm afraid that there could be some other issues too with this.

**Comment by Zuntti** [comment]
Actually it's using the wrong value

**Comment by Zuntti** [comment]
Fixed
