### ISSUE TITLE
Everything Möbelman is selling is too dark to see what it is.

### ISSUE THREAD

**Issue by Ludvig11** [loiste-interactive/Obenseuer-Issues#1209]
![20231122213052_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/31344357/4feedb94-249c-485a-9e52-b7bed4ef5e95)
![20231122213058_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/31344357/804c876d-5a19-4a19-8d63-314709d30b5c)
![20231122213104_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/31344357/adc53c41-df5d-41f8-b1f1-024e0a5be199)
![20231122213117_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/31344357/7e34f34c-d133-40b2-b9a4-ed1bea6c0564)

[2_Lumi_Pakkanen.zip](https://github.com/loiste-interactive/Obenseuer-Issues/files/13444263/2_Lumi_Pakkanen.zip)

**Comment by Oskutin** [comment]
Does this also happen on other furniture crafting stations and so on?

**Comment by Ludvig11** [comment]
> Does this also happen on other furniture crafting stations and so on?

Everything seem fine at Samuel Jonasson's and Mr. Bag .

**Comment by Z-O-M-B-I-E** [comment]
I confirm, I have the same

**Comment by Zuntti** [comment]
Fixed
