### ISSUE TITLE
UI | Prescription Antidepressant & possibly more

### ISSUE THREAD

**Issue by rams95blue** [loiste-interactive/Obenseuer-Issues#1211]
Antidepressant Prescription glitched state that store image icon data from other items, only returning to normal by taking a pill.

https://github.com/loiste-interactive/Obenseuer-Issues/assets/113950769/94766836-9270-4cb5-ba20-eaaef97c303d

(Version 0.3.19)

**Comment by sargonphin** [comment]
This happens on all items, not just the prescription antidepressants ^_^ I have it on the entire first line of my inventory for some reason. backpack included

**Comment by rams95blue** [comment]
> This happens on all items, not just the prescription antidepressants ^_^ I have it on the entire first line of my inventory for some reason. backpack included

Yep, i was about to update this issue, found more glitched items.

**Comment by Zuntti** [comment]
Fixed
