### ISSUE TITLE
"Bird Calendar" at Mr. Bag's is a "Cat Calendar"

### ISSUE THREAD

**Issue by Ludvig11** [loiste-interactive/Obenseuer-Issues#1212]
![20231122221107_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/31344357/3f6256c5-99e7-4546-b547-1e759da5c97c)
[Autosave.zip](https://github.com/loiste-interactive/Obenseuer-Issues/files/13444346/Autosave.zip)

**Comment by CVariable** [comment]
The bird is in the cat :D

**Comment by Zuntti** [comment]
Fixed
