### ISSUE TITLE
Save migration issues with apartment upgrades and their state.

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#1213]
- Player's apartment, makeshift walls upgrade was reverted to bare, only on scene, from UI it's still Makeshift upgrade. (Other had reported higher level upgrades also downgrading to bare).
- Apartment 8, makeshift walls upgrade and makeshift bathroom upgrades were reverted to bare (with all the related furniture), only on the scene, from UI both are still Makeshift, all the default furniture/storage/junk/items were reverted, furniture of reside residents was preserved (accordingly to Makeshift state). Residents are also still present.
- Apartment 10, walls upgrade and bathroom upgrades were reverted to bare (with all the related furniture), only on the scene, from UI both are still Makeshift, all the default furniture/storage/junk/items were reverted, resident was removed from the scene (is still residing in the UI).
- Apartment 9, makeshift walls and shabby heating upgrades were reverted to bare (with all the related furniture), only on the scene, from UI both are still makeshift and shabby accordingly. Apartment was empty, nothing related to residents here.
[Miko_Mortley.zip](https://github.com/loiste-interactive/Obenseuer-Issues/files/13444372/Miko_Mortley.zip)
Save from .18, load slot 3 on .19

**Comment by Zuntti** [comment]
Same as https://github.com/loiste-interactive/Obenseuer-Issues/issues/1210
