### ISSUE TITLE
Previous homeless man Pera Harjus's former resting spot still shows occupied.

### ISSUE THREAD

**Issue by Ludvig11** [loiste-interactive/Obenseuer-Issues#1214]
![20231122211906_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/31344357/e0df0341-2bc4-453c-a0c4-e1174d9385f6)

**Comment by Ierdna100** [comment]
Adding onto this: This applies to all NPCs, not only Pera

**Comment by Zuntti** [comment]
Fixed
