### ISSUE TITLE
Make the return of the old Moonshine Master 9001 as some exclusive to buy furniture, probably at Samuel's.

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#1218]
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/2e7c514a-ce9f-4a87-8a78-8e12be740016)
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/ebe84c72-2361-427f-a389-9be0a68809e0)
really like the look, some alternative wouldn't be bad

**Comment by Oskutin** [comment]
This should be already in game
