### ISSUE TITLE
"Johan Wider" keeps randomly completely changing in appearance. + Muffled Audio when outside.

### ISSUE THREAD

**Issue by Ludvig11** [loiste-interactive/Obenseuer-Issues#1219]
![20231123023555_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/31344357/32fecabe-91a3-4ea8-8c84-48c754292316)
![20231123024102_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/31344357/bfb492b6-3550-4631-a426-3818a94a7faf)
![20231123024156_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/31344357/c7024cf6-f24d-46eb-b292-7a9fc75d1727)
![20231123024251_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/31344357/c2358a9b-a6cb-4d39-9143-7b69da1c820b)
![20231123024320_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/31344357/083a8765-26d2-48bc-b757-d6d8d14d83de)
![20231123024359_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/31344357/75a75886-8b9f-4c17-bdf7-ca87ada7027d)

+++ Audio is screwed, very muffled despite being outside.

[Johan Wider - 3_Lumi_Pakkanen.zip](https://github.com/loiste-interactive/Obenseuer-Issues/files/13445460/Johan.Wider.-.3_Lumi_Pakkanen.zip)

**Comment by Zuntti** [comment]
Fixed Johan Wider

**Comment by Zuntti** [comment]
Fixed
