### ISSUE TITLE
Bought food sometimes show the wrong icons.

### ISSUE THREAD

**Issue by Ludvig11** [loiste-interactive/Obenseuer-Issues#1220]
![20231123003052_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/31344357/21dacfe5-d028-49ab-a993-7b54db2d9950)
![20231123003104_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/31344357/b2dabd02-c96c-41f0-9ebf-d20a2a996ebe)
![20231123004136_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/31344357/b34df14e-c1fa-44fc-8b74-076d65b8b96c)

**Comment by Zuntti** [comment]
Related to https://github.com/loiste-interactive/Obenseuer-Issues/issues/1211
