### ISSUE TITLE
Kolhola freezes the game, eventually crashes.

### ISSUE THREAD

**Issue by UnethicalSpaghetti** [loiste-interactive/Obenseuer-Issues#1221]
even when running on the lowest settings, Loading into Kolhola freezes the game. I remember going there 2 separate times to rent a hostel pod a while back, and noticed each visit my framerate dipped each time. I needed to go there to get access for Passmore, and the last save I had was from a while back. Is there anyway to fix this?

**Comment by Zuntti** [comment]
You can open console F1 and type destroy_all_items

**Comment by Zuntti** [comment]
Fixed
