### ISSUE TITLE
Freeze in main menu

### ISSUE THREAD

**Issue by Kastuk** [loiste-interactive/Obenseuer-Issues#1222]
Both in 3.18 and 3.19 I got freezing at Press Any Key in main menu.
Firstly I was think its my attempt to mod deactivated control keys, but not tested fully.

```
Could not load slot: C:/Users/Kastuk/AppData/LocalLow/Loiste Interactive/Obenseuer/Saves/Friday_Night/Slot7/Info.tnmt 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Exception: Error while parsing: unable to parse; invalid token "
  at FullSerializer.fsResult.AssertSuccess () [0x0000e] in <d70fd7cc0ff646c799723f933a1ce5e9>:0 
  at FullSerializer.fsJsonParser.Parse (System.String input) [0x00009] in <d70fd7cc0ff646c799723f933a1ce5e9>:0 
  at SaveController.DeSerialize (System.String fileName, System.Type type, System.String serializedState) [0x00000] in <db374d9d14764b46b9ad719aafc9684d>:0 
  at SaveController.GetCharacters () [0x000e2] in <db374d9d14764b46b9ad719aafc9684d>:0 
UnityEngine.DebugLogHandler:Internal_LogException(Exception, Object)
UnityEngine.DebugLogHandler:LogException(Exception, Object)
UnityEngine.Logger:LogException(Exception, Object)
UnityEngine.Debug:LogException(Exception)
SaveController:GetCharacters()
LoadMenu:GenerateCharacterList()
LoadMenu:Init()
LoadMenu:Start()
 
(Filename: <d70fd7cc0ff646c799723f933a1ce5e9> Line: 0)

```
[Player-prev 318.log](https://github.com/loiste-interactive/Obenseuer-Issues/files/13446841/Player-prev.318.log)
Freshly updated version. Log of current version become super big in mere minute
[Player 319 100mb.zip](https://github.com/loiste-interactive/Obenseuer-Issues/files/13446845/Player.319.100mb.zip)
![2023-11-23 10_07_21-Greenshot](https://github.com/loiste-interactive/Obenseuer-Issues/assets/36314945/1c142524-8593-4fd8-9591-cbee1ab57980)

Sprinkles got same issue https://steamcommunity.com/app/951240/eventcomments/7529517132617100514/?tscn=1700700653#c4038101970209441708

**Comment by Kastuk** [comment]
Savegame, which error of parsing spam the console
[Slot7.zip](https://github.com/loiste-interactive/Obenseuer-Issues/files/13446963/Slot7.zip)

**Comment by Kastuk** [comment]
I did replace info file with one from other good slot and inside file did renamed slot name.
But seems like it need something more, as theres another parse error at liading the slot with missed " somewhere

**Comment by Kastuk** [comment]
I got same error at my and your way rewriting the info.tnmt
[Player-prev.log](https://github.com/loiste-interactive/Obenseuer-Issues/files/13449009/Player-prev.log)
[Player.log](https://github.com/loiste-interactive/Obenseuer-Issues/files/13449008/Player.log)

**Comment by Zuntti** [comment]
Info.tnmt and Globals.tnmt both are corrupted. Info.tnmt is empty and Globals.tnmt is partially empty. Did the game crash while saving?

**Comment by Kastuk** [comment]
Not sure, I may did AltF4 too fast in hurry to return not mine notebook.
Can just use other slot.

**Comment by Zuntti** [comment]
Fixed freeze
