### ISSUE TITLE
Lockpick duplication while in shop interface

### ISSUE THREAD

**Issue by PeculiarSana** [loiste-interactive/Obenseuer-Issues#1223]
Attempting to refill an incomplete stack (<25) of lockpicks in your equipment slot with a full stack (25) while in a shop interface causes the stack in your equipment slot to become a full stack as well, essentially duplicating the item. 
This works with any shop in the game.

https://github.com/loiste-interactive/Obenseuer-Issues/assets/31283592/edca2ae8-e3c8-4a98-9810-fbc720cf1bb5

**Comment by Zuntti** [comment]
Fixed
