### ISSUE TITLE
[BUG] "Homecoming Celebration" task not working

### ISSUE THREAD

**Issue by sargonphin** [loiste-interactive/Obenseuer-Issues#1224]
The Homecoming Celebration task is not working. It does not advance after poisoning the wine. Restarting the game has no effect.

Running game version 0.3.19 (the version number isn't available in the Pause menu if it's running, only on main menu).

**Comment by Nextej** [comment]
"Poison the bottle" gets checked off after putting it back in the gift and leaving the area, does that not working? Otherwise #911

**Comment by sargonphin** [comment]
OK it worked but the steps in this quest should really be more detailed... there are a lot of open issues because of the confusion XD
