### ISSUE TITLE
[BUG] Player tenement - Clipping through stairs to the basement door

### ISSUE THREAD

**Issue by sargonphin** [loiste-interactive/Obenseuer-Issues#1225]
There's a bug at the stairs of the player tenement leading to the basement where you clip through when you have the courtyard level 4. You need to jump to get on the pavement and continue

(sorry for night time D:)
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/85966195/9882f0f6-3452-419c-89ff-db8ff80ec1a4)

**Comment by Zuntti** [comment]
Fixed
