### ISSUE TITLE
Item dupe glitch possibly results in disappearing items in appt

### ISSUE THREAD

**Issue by nicbou0321** [loiste-interactive/Obenseuer-Issues#1228]
ok so, brand new save game started just for testing purposes. 

everything seems fine until you restart the game, yesterday i was able to play for hours and didnt notice any bug. 
it only started happening after i took a break and closed the game and had it restarted. 

after a game restart, items placed in the appt will suddenly be duplicated, i am not trying to glitch the game, but i am simply trying to take items that is already placed in my appt. 

ill explain exactly what i did and how it happened
i started new save, took a few things, cement bag, some scrap wood, cleaned a few tenant appt and went to the 3rd floor to get the story started. 
gather a few items to test. place them down all together nicely placed so i can easily see what is missing. 
i saved my game before any duping was done. 
i restarted my game, got out and in the appt countless times, nothing disappears. 

as soon as i take 1 item, i took the cement bag, but it duped it. the cement bag was still there on the ground, but i also had it in my inventory. 
i go out and in again, i take the cement bag, now it really picked it up. 
but now the disappearing items begins. 
everytime i go out and back in my appt, there would be one more missing scrap metal. 
specifically this test save. duped cement bag = missing scrap metal

and the more items i pick up that duplicates. the more disappearance that happens. 

in my other save i must have picked up like tens of duped items without noticing. 
when i got back in my appt, literally half of my wood was gone, i must have had a stack of 40 wood placed in my appt, and the lower portion of it was all missing. ignoring other random items that was also missing. 

i really enjoy the game so far, just this one pesky bug that has been killing the fun for me. 
hopefully squashing those bugs wont be too hard. :P

good luck devs, loving the game you made so far. keep up the great work!

**Comment by Zuntti** [comment]
I can't get that disappearing item bug. Fixed duplication bug but I don't know if it really fixes the disappearing items.

**Comment by Zuntti** [comment]
Can I get save where items disappears?

**Comment by nicbou0321** [comment]
> Can I get save where items disappears?

ive started a brand new save and placed a few items on the ground. 

idk if this pic will work, first time github user :P
but this is the items i placed initially. 
![20231124061738_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/151878567/55d94ce1-236f-40c9-8d0f-a7c91667cb6b)

i took the cement bag, and 2 scrap metal. which all duplicated, so i have 2 cement bag in my inventory, and 4 scrap metal in my inventory. 

save slot 1 is before any items was duped
save slot 2 is after i took those items and it duped. 
save slot 3 is after getting in the appt only once, only 2 items is missing. one fire wood and one scrap metal. 
save slot 4 after doing it twice. 2 extra items are missing, same as above. 


i hope this will be helpful
good luck and thank you for the awesome game and quick bug fixing, you are awesome <3

[Obenseuer_Save_Glitch.zip](https://github.com/loiste-interactive/Obenseuer-Issues/files/13458005/Obenseuer_Save_Glitch.zip)

**Comment by nicbou0321** [comment]
> I can't get that disappearing item bug. Fixed duplication bug but I don't know if it really fixes the disappearing items.

also, while looking at the file "Interior Player Tenement.tnmt" in notepad++
i noticed that quite some items that was disappearing was also saved with a negative ID of -1

im no programmer and ive got no clue if its actually affecting it. but just wanted to point this out as well.

**Comment by Zuntti** [comment]
Fixed
