### ISSUE TITLE
[BUG] Glowstick Trail - Mine entrance not working

### ISSUE THREAD

**Issue by sargonphin** [loiste-interactive/Obenseuer-Issues#1229]
The description of the task `Glowstick Trail` states that the key to the mine is somewhere in Hanss' hideout, but there's no key to be found in it. 

Furthermore, the key that unlocks his hideout does not unlock the mine, unlike what it says in the description of the key itself.

I think that is either a bug of the key, or that the key is missing from the hideout/too hard to find in the hideout

**Comment by Nextej** [comment]
Mines are purposely blocked for now, since they are a district for future update, Hanss' key would unlock them.

**Comment by sargonphin** [comment]
Oh so the story of the game cannot be finished?

**Comment by Nextej** [comment]
Nope, there's at least 3 more full-sized districts planned

**Comment by sargonphin** [comment]
Okay then. I think I should revisit the game in a year or so, when it's done XD
