### ISSUE TITLE
Public 0.3.20 - If player is asleep while mashing tun finishes, lots of ashes is spawned on their bed

### ISSUE THREAD

**Issue by CVariable** [loiste-interactive/Obenseuer-Issues#1234]
I let the mashing process run overnight, and when i woke up, this was on my bed, aswell as the mashing tun being full of ash.
This might happen with other machines too.
![grafik](https://github.com/loiste-interactive/Obenseuer-Issues/assets/45665371/378f5420-540a-4dc6-ab6e-06b988b7872b)
![grafik](https://github.com/loiste-interactive/Obenseuer-Issues/assets/45665371/33e08721-d140-4eab-9892-f7e2321a728b)

**Comment by NekoBaron** [comment]
I also had had this issue, I imagine its due to the ash overloading the devices inventory full so it drops it at your feet while you sleep. I imagine its like how when using a craft bench if too much product is made its dropped at your position and that happens to be when your in bed.

**Comment by Oskutin** [comment]
Fixed
