### ISSUE TITLE
Repeating console error message

### ISSUE THREAD

**Issue by CBS-S** [loiste-interactive/Obenseuer-Issues#124]
Opening up the console gives me this message, which repeats over and over without changing.
![20230424180932_1a](https://user-images.githubusercontent.com/86502239/234128213-3f36ba0b-8b82-4c33-acc8-d02066dffb64.jpg)

**Comment by Oskutin** [comment]
Seems to be the same error as this https://github.com/loiste-interactive/Obenseuer-Issues/issues/99
