### ISSUE TITLE
The wardrobe has little space

### ISSUE THREAD

**Issue by Z-O-M-B-I-E** [loiste-interactive/Obenseuer-Issues#1241]
Seriously? This is one of the largest wardrobe

![20231124231546_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/46783282/fd5c0133-eb10-4b7e-bf9d-b05cb907b464)
![20231124231548_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/46783282/3c8c6b25-bad5-4685-8198-347726ad371f)

**Comment by Zuntti** [comment]
Fixed
