### ISSUE TITLE
The passage to the bridge may not close if the player opened and did not pass through the gate

### ISSUE THREAD

**Issue by Z-O-M-B-I-E** [loiste-interactive/Obenseuer-Issues#1243]
![20231124233022_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/46783282/c9b36589-88eb-4dc5-9895-0fd298e38178)
![20231125002250_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/46783282/9939b291-f238-426e-b822-ea31580a35f8)

**Comment by Zuntti** [comment]
Fixed
