### ISSUE TITLE
[BUG] Turning off the TV in the prison leads to infinite jail time

### ISSUE THREAD

**Issue by sargonphin** [loiste-interactive/Obenseuer-Issues#1246]
If you turn off the TV that the guard is watching when set free and asked to pickup your things, the guard gets mad and put you in jail during the dialogue (interrupting it). When the player is placed in jail, the dialogue appears again and makes a permanent loop. It is impossible to get out of it

**Comment by sargonphin** [comment]
I don't know if it is repeatable. I was able to randomly break out of it by pressing escape right before the dialogue, and also it doesn't seem to do it when you remove the fuse

**Comment by toweroglass** [comment]
I can confirm this. I was blessed with the infinite loop only repeating like 3 times. Can also confirm that flipping the fuse lands you in jail but does not loop.

**Comment by Oskutin** [comment]
Can't get this TV thing to happen

**Comment by Oskutin** [comment]
It is possible that something else has fixed this already. Free free to report again if it happens (with saves attached)
