### ISSUE TITLE
Getting "cooked" effect despite Sauna barrelstove being off and at low temperatures.

### ISSUE THREAD

**Issue by Ludvig11** [loiste-interactive/Obenseuer-Issues#1247]
![20231125011849_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/31344357/25316b00-07d3-48cd-866a-612b5bf01846)
[Sauna_Lumi_Pakkanen.zip](https://github.com/loiste-interactive/Obenseuer-Issues/files/13462626/Sauna_Lumi_Pakkanen.zip)

**Comment by Oskutin** [comment]
Fixed
