### ISSUE TITLE
[BUG] Door says "Open Sewers" instead of "Obenseuer" in Deekula C

### ISSUE THREAD

**Issue by sargonphin** [loiste-interactive/Obenseuer-Issues#1248]
A door accessible through Deekula C on the first floor says "Open Sewers" instead of "Obenseuer". This door opens on a small balcony right next tot he Möbelmann sign

Alternatively, the door on the ourside says "Deekula" without mentioning which one it is. I suppose this is on purpose, since this is technically another building?

![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/85966195/7e6d06c2-1c4e-4a2b-84f1-d08b74151c4f)

**Comment by Oskutin** [comment]
Fixed
