### ISSUE TITLE
Weird voices/sounds when drinking alcohol  

### ISSUE THREAD

**Issue by Crlangley** [loiste-interactive/Obenseuer-Issues#125]
I'll be the first to admit i can't say anything about what happens when you drink alcohol in real life nor plan too, but seems very odd that you'll start hearing that creepy sound file after just one drink in the game. Seems like an effect that should of gone to maybe the shroom effects or at least for drinking a lot of alcohol maybe?

**Comment by gehube** [comment]
agreed, maybe it should start after drinking 2 full bottles
