### ISSUE TITLE
Harvesting "Dracaena fragrans" at the Kurahaara farm is reported by Jomppe as "theft".

### ISSUE THREAD

**Issue by Ludvig11** [loiste-interactive/Obenseuer-Issues#1251]
![Obenseuer 2023 11 25 - 01 45 04 13 DVR mp4_snapshot_00 13 484](https://github.com/loiste-interactive/Obenseuer-Issues/assets/31344357/f5371908-ec80-43dc-80c7-9f37cd6903cf)

[Kurahaara_Draceana_Lumi_Pakkanen_Slot3.zip](https://github.com/loiste-interactive/Obenseuer-Issues/files/13462685/Kurahaara_Draceana_Lumi_Pakkanen_Slot3.zip)

**Comment by Z-O-M-B-I-E** [comment]
Not only with this, there are a couple of plants with which the same thing happens (cactus, trees?)

**Comment by Ludvig11** [comment]
He also won't let me sell cabbage for some reason, or doesn't recognize it as something to pay for, as I had stolen it by accident then brought back, but Lettuce was bought.

**Comment by Oskutin** [comment]
Fixed
