### ISSUE TITLE
Some items in the market are not combined

### ISSUE THREAD

**Issue by Z-O-M-B-I-E** [loiste-interactive/Obenseuer-Issues#1252]
For example Septic Low, Hot Dog 
![20231125031403_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/46783282/10283856-3291-4e60-b483-4fcbbafcc611)
![20231125031357_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/46783282/bb855d49-d1cc-436a-b060-1e716266d2f9)

This happened during sorting
![20231125031332_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/46783282/04cfc933-e5cb-4821-9d66-36a31ec3a83f)

The same problem exists with stolen items (I suspect due to the fact that they are stolen in different places)
![20231125031509_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/46783282/da6bbe59-1a09-4b58-a517-cf599d2093cc)

**Comment by Oskutin** [comment]
Fixed
