### ISSUE TITLE
Keypad at entry of B2 maintenance tunnel: Entering wrong code leads to loss of UI

### ISSUE THREAD

**Issue by Ierdna100** [loiste-interactive/Obenseuer-Issues#1258]
When entering the wrong code, some UI bugs occur, i.e.:
- Center dot dissapears
- The tooltip of the last item held in inventory appears when closing inventory

**Comment by Ierdna100** [comment]
Additional UI that dissapears:
- Information popups on doors/characters/etc

**Comment by Oskutin** [comment]
doesn't seem to happen anymore
