### ISSUE TITLE
Right clicking on boxes in inventory and containers keeps the box highlighted

### ISSUE THREAD

**Issue by Crlangley** [loiste-interactive/Obenseuer-Issues#126]
![20230424220211_1](https://user-images.githubusercontent.com/65619937/234358895-abaccff9-0dda-4c32-80a0-71a3f36551d3.jpg)
 
I found closing the container seems to reset it back to normal, but I had a game where the highlighted boxes wouldn't reset to grey in the inventory.  It doesn't seem to matter if the item box has an item in it or not.

**Comment by Oskutin** [comment]
This is duplicate and already fixed
