### ISSUE TITLE
Public 0.3.20 - Dragging O-Market cooking oil into a container steals the contents and breaks the cooking oil item

### ISSUE THREAD

**Issue by CVariable** [loiste-interactive/Obenseuer-Issues#1263]
Before:
![grafik](https://github.com/loiste-interactive/Obenseuer-Issues/assets/45665371/c145c706-9dac-4714-9cfc-46e845cdaa1d)

After dragging the oil into my 20L jug:
![grafik](https://github.com/loiste-interactive/Obenseuer-Issues/assets/45665371/6dc2582a-bd97-416d-b4c1-f68f8027c5dd)

The oil is stolen, the empty bottles spawn as 99 shrooms, and the description upon clicking the shooms is the oil's normal one.

Save for testing:
[CookingOil.zip](https://github.com/loiste-interactive/Obenseuer-Issues/files/13465167/CookingOil.zip)

**Comment by Oskutin** [comment]
Fixed
