### ISSUE TITLE
More bugs and glitches with pics. 

### ISSUE THREAD

**Issue by Im-Brandfall** [loiste-interactive/Obenseuer-Issues#1266]
I recently put in a bug issue before trying to address some bugs that are happening. A mod did tell me that the bugs were fixed however on a fresh character these two are still an issue. Trash still spawns over the river behind the tenement in the little town area to the right. These bottles in Deekula A are not collectable at all. A few new bugs found here: A plank of wood on the door on the inside of Apartment b, before the stairs to the greenhouse is not actually part of the code that loads the outside zone, every building light with a letter on it turns off when the player is under one and looks away and back on when you pan back over. This might be an issue with chunk culling or whatever you are calling it.

![Screenshot_10](https://github.com/loiste-interactive/Obenseuer-Issues/assets/50027813/f8243de4-cb13-42bf-a255-993a17cdd25a)
![Screenshot_11](https://github.com/loiste-interactive/Obenseuer-Issues/assets/50027813/f38e5f93-6382-4031-874d-873a70484ce7)
![Screenshot_12](https://github.com/loiste-interactive/Obenseuer-Issues/assets/50027813/d0f4f084-7d5b-4565-931c-b69b8164ff9d)
![Screenshot_13](https://github.com/loiste-interactive/Obenseuer-Issues/assets/50027813/199793f9-c80b-4033-8672-011e3a23f912)
![Screenshot_14](https://github.com/loiste-interactive/Obenseuer-Issues/assets/50027813/0cd79878-2779-4160-8c00-f5d1d9c57caa)
![Screenshot_15](https://github.com/loiste-interactive/Obenseuer-Issues/assets/50027813/52950145-c2ce-43e3-83bb-3f771896042d)

**Comment by Oskutin** [comment]
These are already solved
