### ISSUE TITLE
Gameplay Bug: Basement Sauna No Fuel Slot

### ISSUE THREAD

**Issue by Anomeat** [loiste-interactive/Obenseuer-Issues#1268]
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/47526549/8e4c627a-80b5-4967-9ef5-33649027a038)
No fuel slot in basement makeshift sauna, 

Was initially avalible, after save and closing the game, and opening and loading back up blocks out the fuel slot.

**Comment by Oskutin** [comment]
Can you upload the save file?

**Comment by Anomeat** [comment]
I can't reliably recreate the bug, but I can see it's effects because it clears any ash and saved up fuel time when playing the game and going in and out of the building.

[Slot1.zip](https://github.com/loiste-interactive/Obenseuer-Issues/files/13467191/Slot1.zip)

**Comment by Oskutin** [comment]
Uh, can't reproduce. Merging this with the old issue. https://github.com/loiste-interactive/Obenseuer-Issues/issues/882
