### ISSUE TITLE
Broken Shelves in O-Market

### ISSUE THREAD

**Issue by Garubon** [loiste-interactive/Obenseuer-Issues#1269]
Found a bug in O-Market. When viewing the bread inventory this uninteractable stack appears and when moused over shows the informaton of the last item I interacted with in my inventory. Placing the stack into my inventory does nothing and the stack still persists. Moldy waste was also all over the floor and bread shelves.
![20231126014216_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/152092772/a2ea9fd1-c634-49a2-b4b0-17eaf1ffed11)
![20231126014228_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/152092772/60c63de3-49c3-4ed6-ad13-13a0c2edb692)
![20231126012007_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/152092772/8a4c6819-8466-4f07-bde7-7f1640ddf4c1)

**Comment by Oskutin** [comment]
Fixed
