### ISSUE TITLE
Public 0.3.20 - Minor: "Owned" Antidepressants in Deekula C 3 Bedroom

### ISSUE THREAD

**Issue by CVariable** [loiste-interactive/Obenseuer-Issues#1272]
![grafik](https://github.com/loiste-interactive/Obenseuer-Issues/assets/45665371/eea61b08-e2dc-4d91-a3ad-a2373fe6e196)
![grafik](https://github.com/loiste-interactive/Obenseuer-Issues/assets/45665371/764ac39b-4a39-40ba-9c70-c73926b3da5c)
![grafik](https://github.com/loiste-interactive/Obenseuer-Issues/assets/45665371/71f13ed0-6ea4-4af0-9832-ec02e95bc819)
The painkillers in the bathroom are correctly marked stolen, not owned.

**Comment by Oskutin** [comment]
Fixed
