### ISSUE TITLE
Suggestion - Craftable shroomlanterns (both as an item (#1274) and a furniture)

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#1273]
Perhaps brass scraps, glass shards and shrooms of the desired color?

Shroomlanters with orange shrooms should be added as placeable furniture (as currently they are only found in mines), being craftable only from a blueprint foudn somewhere around ventilation tunnels of Gatehouse level.
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/4d94c1e7-7d94-4264-8fb8-51feaa19516a)

**Comment by Zuntti** [comment]
Malone is going to give that

**Comment by Nextej** [comment]
Fully implemented already.
