### ISSUE TITLE
Add an indicator that differentiates between owners of stollen items, currently player has no way of knowing why they can't stack stolen items of different owners, perhaps some color indication or name of the apartment to indicated a shared owner or a general owner?

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#1279]

**Comment by Hiddenfoxwere** [comment]
![Obenseuer 2023-11-27 16-17-04-380](https://github.com/loiste-interactive/Obenseuer-Issues/assets/61855188/1d88b559-8b5d-48f9-a454-a7b703629ebc)
![Obenseuer 2023-11-27 16-17-39-256](https://github.com/loiste-interactive/Obenseuer-Issues/assets/61855188/40fe03f0-3a4e-4eb5-97fe-a21aa58ea780)

I'm adding screenshots.

**Comment by Nextej** [comment]
Already implemented
