### ISSUE TITLE
Dropping live Rats turns them into 1 open Sewer coin on the ground

### ISSUE THREAD

**Issue by Crlangley** [loiste-interactive/Obenseuer-Issues#128]
![20230425125920_1](https://user-images.githubusercontent.com/65619937/234362923-25bf836c-43da-4e33-bd27-d32cf7f93f02.jpg)
![20230425125927_1](https://user-images.githubusercontent.com/65619937/234362925-a66f7124-ef64-49ad-802b-4c6b2f1a5297.jpg)

I only had 2 rats to test this and had to use the second to confirm this happened, but when i get a chance i'll try killing one and see if it does the same for a dead rat as well

**Comment by Oskutin** [comment]
Fixed
