### ISSUE TITLE
Tenement and Sauna issues

### ISSUE THREAD

**Issue by Definitive-Dude** [loiste-interactive/Obenseuer-Issues#1280]
Tenement:
Level 3 walls plus a balcony on the northern side of the large apartments adds two doors inside one another (first attached image)
![ss](https://github.com/loiste-interactive/Obenseuer-Issues/assets/151375023/69124455-3db7-4ddd-958a-44f2bfcff8bf)

Sauna:
Exiting the building resets the sauna temperature when you reenter even if there is still fuel burning inside.

Additionally, when the sauna door in Kolhola A is re-locked, all of the ash generated gets scattered at the entrance of the building (shown in the second image)
![11](https://github.com/loiste-interactive/Obenseuer-Issues/assets/151375023/0504b5a8-dacf-41fd-bc79-ebf64cbe0ae7)

**Comment by Zuntti** [comment]
Door is fixed

**Comment by Oskutin** [comment]
Ash is also fixed
