### ISSUE TITLE
0.3.20 - some bug and notice

### ISSUE THREAD

**Issue by Hiddenfoxwere** [loiste-interactive/Obenseuer-Issues#1282]
1. #1279 - 
2. Picking the lock - Skill ~ 10  does not affect the difficulty lock

![Obenseuer 2023-11-27 16-18-19-782](https://github.com/loiste-interactive/Obenseuer-Issues/assets/61855188/2850c33a-5b5f-4e8d-9e66-cff1211efa6f)

3, Second door Dantist locked (after going to room and back to door).
4. Hanging shelf position

![Obenseuer 2023-11-27 17-01-49-963](https://github.com/loiste-interactive/Obenseuer-Issues/assets/61855188/44cc6ef1-b33b-445f-bf45-699a9e18920e)
![Obenseuer 2023-11-27 17-01-57-049](https://github.com/loiste-interactive/Obenseuer-Issues/assets/61855188/75b6a276-3476-4c7f-b6f9-13fb2dd1b29d)

5. Lock pick recipe

![Obenseuer 2023-11-27 17-06-44-972](https://github.com/loiste-interactive/Obenseuer-Issues/assets/61855188/25ccbb95-7e0f-41ae-852f-6729122f5449)

6. After drinking a lot of coffee, the character no longer sleeps, can't miss time on sofa - just in case.
7. Not a bug, maybe a feature - the pipes don't lead anywhere - bassenent

![Obenseuer 2023-11-27 17-34-54-017](https://github.com/loiste-interactive/Obenseuer-Issues/assets/61855188/825b6fcd-e03d-4e8d-94ad-7864dcbacdc2)

8. About stamp for debit card - needed two stamp, but only one instance is used.

![Obenseuer 2023-11-27 17-36-11-216](https://github.com/loiste-interactive/Obenseuer-Issues/assets/61855188/5a94cb1b-bee3-43bf-886b-661dba4a31e8)

About finding Hans - if the mines are not accessible it might make sense to just remove the key.

**Comment by Hiddenfoxwere** [comment]
[Fox_Seibert.zip](https://github.com/loiste-interactive/Obenseuer-Issues/files/13476722/Fox_Seibert.zip)
[logs.zip](https://github.com/loiste-interactive/Obenseuer-Issues/files/13476726/logs.zip)
 Load autosave.

**Comment by Hiddenfoxwere** [comment]
Too lazy and weak check ticket - some is repeated.

**Comment by Hiddenfoxwere** [comment]
Too lazy and weak check ticket - some is repeated.

**Comment by Kastuk** [comment]
I suppose, theres need to be one ticket per one type of issues, as its pretty different ones to fix them all at once and label as particular type of issues. So devs may be already struggling under piles of more organized piles of bugs.

1 is enhancement which is already marked.
2, 3 and 8 is bugs, skill, doors, recipe.
4. Tenement system
5. Not sure what a bug there, did you pick up lockpick recipe and it shows as can opener (lockpicks can be crafted without recipe)?
6. Coffee not let sleep is a feature. But theres no relax to spend time like in prototype.
7. Graphical

Key to mines also can open other two doors out the basement.
