### ISSUE TITLE
Bank account and related quest issue

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#1283]
1. ~~Invoice costs 0 OC and putting it into payment machine doesn't show "pay invoice" button, preventing player from paying it off at all~~ invalid
2. Bank account is empty, lacks initial 320 RM and doesn't seem to receive more weekly.

**Comment by Oskutin** [comment]
Can i have a save file?

**Comment by Nextej** [comment]
First issue is invalid
3. Debit Card invetory icon is missing after picking it up for the first time on Playerment map, reload/map transition fixes it
4. ATM acts as we're about to open the account, which is a bit weird since we already have an attached card and personal information, no?
5. Sometimes the Payment Machine is unsable (interaction key does nothing, no UI opens), possibly for the first interaction in a session or after task update?
[Player.zip](https://github.com/loiste-interactive/Obenseuer-Issues/files/13480502/Player.zip)

**Comment by CVariable** [comment]
Just verified this issue is still present in .22, with a completely new save. It still acts just as i described with the previous save, except that it came about a week earlier in total. 
![grafik](https://github.com/loiste-interactive/Obenseuer-Issues/assets/45665371/be6614ff-ae04-4f2e-b537-8ca604b504eb)

**Comment by Oskutin** [comment]
You can't stuff money to ATM

**Comment by Oskutin** [comment]
Can I have your new save?

**Comment by CVariable** [comment]
[debitcardbug.zip](https://github.com/loiste-interactive/Obenseuer-Issues/files/13591051/debitcardbug.zip)

**Comment by SaladSauce** [comment]
Bank related issue but with Invoices
I put the invoices(2) in the bank payment machine but nothing happens

Also I failed to pay the first invoice because it was stolen in my sleep and I was fined for it
[invoice.zip](https://github.com/user-attachments/files/17344997/invoice.zip)

**Comment by Nextej** [comment]
@SaladSauce open a new ticket if the issue still happens. Also, if you don't pay the invoice in time, you won't be able to use that one in the payment machine afterwards.

**Comment by Necronomicron** [comment]
> Fixed

It seems it's back after the last update (apparently, only for game profiles created after the update). Or maybe I just don't know something?

I got my card on in-game Friday (day 32) and my account had 0 RM.

But I remember at some point, while the quest was in progress, I saw a message in the top left corner that I received some RM into my account (I think it said it was unemployment benefits), but it was much more than 100, something like 320 (the number wasn't multiple of 100 either). Where are those?

Other people with this issue:
https://steamcommunity.com/app/951240/discussions/0/599642824002007783/
https://www.reddit.com/r/Obenseuer/comments/1jh0ops/bank_account_empty/
https://www.reddit.com/r/Obenseuer/comments/1iomik3/is_this_a_bug/

[Slot10.zip](https://github.com/user-attachments/files/19918032/Slot10.zip)

**Comment by Necronomicron** [comment]
It's day 40 now, I still have 0 RM on my bank account.

**Comment by Necronomicron** [comment]
Apparently, it's a known issue and should be fixed soon.
