### ISSUE TITLE
Black lines around apartment doors with decent stairwell

### ISSUE THREAD

**Issue by Bdopz** [loiste-interactive/Obenseuer-Issues#1288]
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/26634538/950d1746-9888-4049-96ee-96005fb40931)
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/26634538/3ad8788c-bf28-4e0b-b916-02b830826d17)

**Comment by Zuntti** [comment]
Fixed
