### ISSUE TITLE
Map seams/errors in level design

### ISSUE THREAD

**Issue by AndreiPopescuVanier** [loiste-interactive/Obenseuer-Issues#1289]
1. Barrel inside of pipe in basement of player's tenement. (Shit heating, no electricity, no water).

![20231127225524_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/150824397/289017e7-d282-421e-b19c-c83e74806629)

2. This wall cloth appears to be rotated 90 degrees wrong

![20231127214849_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/150824397/62a873fe-00d6-4179-a168-af7fa6b72711)

3. Bazaar entrance on player tenement's side has a visible gap in level

![20231122145302_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/150824397/808d91ca-1c3b-4d9a-b8a2-b87f7561a04d)

4. Drill in Deekula has its head rotated wrong by 90 degrees

![20231121171629_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/150824397/a7efcd4f-5c39-4779-a912-75231491ef4e)

5. You can descend in the canals and see the incomplete parts of the Bazaar and future expansions

![20231120183008_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/150824397/2c8de349-8fdb-481c-a89f-8d90e35b34df)

**Comment by Oskutin** [comment]
Fixed 3 and 5

**Comment by Oskutin** [comment]
Fixed
