### ISSUE TITLE
Can't move head around

### ISSUE THREAD

**Issue by TiaLinna** [loiste-interactive/Obenseuer-Issues#129]
I sat down on a couch in Max Mashers apartment and tried to look around, it didn't let me look much around, before snapping my neck back to it's original position, tested on different couches, no problem.

![20230425220647_1](https://user-images.githubusercontent.com/130680276/234381185-eff49d8d-96a7-4890-9a3e-60a60285bcb9.jpg)

**Comment by Zuntti** [comment]
Fixed
