### ISSUE TITLE
Passmore magically restocks his RM balance on location reload.

### ISSUE THREAD

**Issue by DanilGritsenko** [loiste-interactive/Obenseuer-Issues#1290]
This allows you to sell high value items without waiting.

Steps: 

1. Go to passmore, sell items until he no longer has RM.
2. Exit and then enter the Tenement B building.
3. Sell your items again because his RM balance restocked.

[Video on Medal](https://medal.tv/games/requested/clips/1GiHxhoD4SdJDM/d1337zdLBkQf?invite=cr-MSxFNFosMTU5NjMyNjAxLA)

**Comment by Zuntti** [comment]
Fixed
