### ISSUE TITLE
When spending a second consecutive time in jail, all your pre-jail inventory is gone and replaced with the previous jail one, and if save/load you get arrested again.

### ISSUE THREAD

**Issue by Ludvig11** [loiste-interactive/Obenseuer-Issues#1296]
![20231128192904_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/31344357/c5b73082-6802-47d5-a504-6e63505ee0b0)
[Prison-Issues_Lumi_Pakkanen.zip](https://github.com/loiste-interactive/Obenseuer-Issues/files/13491923/Prison-Issues_Lumi_Pakkanen.zip)

**Comment by Oskutin** [comment]
https://github.com/loiste-interactive/Obenseuer-Issues/issues/1109
