### ISSUE TITLE
0.3.21 - Pentti buying mash does not delete it [Pentti's mash buying is abusable for RM]

### ISSUE THREAD

**Issue by CVariable** [loiste-interactive/Obenseuer-Issues#1300]
Before selling him mash:
![grafik](https://github.com/loiste-interactive/Obenseuer-Issues/assets/45665371/1286d4d6-d9e8-4c30-8fb8-a7dc7cbaa0af)
After selling:
![grafik](https://github.com/loiste-interactive/Obenseuer-Issues/assets/45665371/9ca1308c-d642-4a4b-92be-f5f1e1be857f)

Buying the same mash from him costs less than selling it to him brings in. So, repeated selling and buying creates infinite RM until pentti runs out of money.
Price for buying mash from him should probably be increased.

**Comment by Oskutin** [comment]
Seeling stuff for him should delete the items

**Comment by Oskutin** [comment]
Fixed
