### ISSUE TITLE
0.3.21 - Police arresting player during level load breaks the game

### ISSUE THREAD

**Issue by CVariable** [loiste-interactive/Obenseuer-Issues#1302]
Found by SarcasmSelfTestComplete on Discord
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/45665371/0a7518a3-83df-4d93-b10f-2f12d14f2b00)
The police arresting the player while entering the tenement in this situation caused the game to act as if the player was in prison, despite being free. It also caused the time to advance quickly, causing them to quickly die from thirst.
It can apparently be fixed by sleeping in a bed, but if this happens in front of o-market for example, it could be game-breaking, as the auto save saves at the point the player is arrested, seconds before they die of thirst.

**Comment by Oskutin** [comment]
Fixed
