### ISSUE TITLE
Kolhola basement - odd shadows on the floor stays after picking up cans

### ISSUE THREAD

**Issue by Ryder17z** [loiste-interactive/Obenseuer-Issues#1307]
[closeup](https://github.com/loiste-interactive/Obenseuer-Issues/assets/2000703/96afa392-a4f6-4d2c-8bb1-ba470837fcd8)
[image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/2000703/bcf02f37-04b1-4b33-9c2f-400eed9c7334)

**Comment by Z-O-M-B-I-E** [comment]
https://github.com/loiste-interactive/Obenseuer-Issues/issues/910

**Comment by Ryder17z** [comment]
i assume i can close this then.
