### ISSUE TITLE
Dragging an inventory item can sometimes leave it hanging, making it unusable

### ISSUE THREAD

**Issue by Ryder17z** [loiste-interactive/Obenseuer-Issues#1308]
See seed bag: 

![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/2000703/90090595-9b82-4a4d-974d-d5c8177c177e)

**Comment by CVariable** [comment]
This happens when clicking very fast. Using a macro to triple-click will reliably cause it every ~20th stack you move if you move between items quickly. saveloading or changing cell fixes it.

**Comment by NekoBaron** [comment]
Is that whats causing it? I reported it here https://github.com/loiste-interactive/Obenseuer-Issues/issues/1194
Starting to think my mouse sometimes is sending ghost double clicks rapidly, because I certainly dont intentionally rapid click.

**Comment by Ryder17z** [comment]
seems related yea.
