### ISSUE TITLE
Cleaning the graffiti in the first picture below, also clears the astronaut graffiti

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#1311]
Cleaning this
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/f84a6050-2d65-49ae-8d62-07d19ac45294)
gets also rid of this
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/011e8be0-442c-40dc-a992-0c7cd41b169f)

**Comment by Oskutin** [comment]
Fixed
