### ISSUE TITLE
Apartment values got severely reduced in half, this really negatively affects the balance and will require lowering prices of the upgrades even more drastically, previous apartment value worked pretty well, I'd suggest reverting that.

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#1312]

**Comment by Zuntti** [comment]
It seems that Oskutin changed values. Value is now divided by 20.

**Comment by Nextej** [comment]
Is the rent now 1/10 of the apartment value then instead of 1/100 as before the update?

**Comment by Zuntti** [comment]
OC was value/10 and RM value/100. Now it's value/20 and value/200

**Comment by Oskutin** [comment]
https://github.com/loiste-interactive/Obenseuer-Issues/issues/1322
