### ISSUE TITLE
Planter boxes placed in the extension do not get the "sun" modifier

### ISSUE THREAD

**Issue by SarcasmSelfTestComplete** [loiste-interactive/Obenseuer-Issues#1315]
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/152416587/fdcdfd88-5199-42de-a6b7-b366dd3e4405)
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/152416587/f1267d2e-16f8-4a79-ab72-416cac53d57e)
issue is persistent, saving/loading, leaving/re-entering the building changes nothing

**Comment by Oskutin** [comment]
Seem to apply only Shabby extensions?

**Comment by Oskutin** [comment]
Fixed
