### ISSUE TITLE
Suggestion - Fluid Barrels furniture

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#1318]
Add a fluid barrels furniture as an option to stockpile large quantities of fluids.
- Different types, wooden, metal, plastic ones? to store different types liquids (potential for chemistry?)
- Can store one type of liquid at the time, perhaps UI similar to sinks with ability to empty containers (deposit liquid) and fill containers (take out the liquid). Show the amount of liquid in liters somewhere in the UI, perhaps have ability to drain the barrel to clear it out, loosing all the liquid.
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/de43f436-7a6f-47c2-827a-5d10d0058a9a)

![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/f0a10baa-5d66-48cc-a5ba-36bf9d261e84)

- Place vertically, perhaps add a barrel rack furniture that when a barrel is snapped to it, it's placed horizontally.
- Capacity, perhaps 120L?
- Perhaps additionally a larger, singular, horizontally placed (with small visual supports), high-level beer barrels to store alcohols that would have 4-6 times or so more capacity than normal version. Perhaps a metal counterpart could be a large metal tank placed vertically.
- Makeshift sink (bathroom upgrade) and a water dispenser (kolhola hostel) could also benefit from this (solving an issue of them being an infinite source of potable water), being a limited in amount barrels that refill daily (makeshift sinks could further be enhanced with ability to pay someone to daily refill it, but that's an idea for another day).

**Comment by CVariable** [comment]
Definitely make sure to add a confirmation before draining the liquid until the player has a container. If the player tries to fill a container and clicks drain because they think it will drain into the container, they will not be happy to lose their entire barrel of shroombeer

**Comment by Oskutin** [comment]
Implemented
