### ISSUE TITLE
0.3.21 - Only the recipe minimum 10L of Kilju is fermented even when more sugar mash is present.

### ISSUE THREAD

**Issue by MajorMari** [loiste-interactive/Obenseuer-Issues#1319]
~Only tested with Sugar Mash/Kilju with a save started in 0.3.20.~ Observed with varying amounts of sugar mash in 1 to 5 plastic containers (20L to 90L), it only ever pulls and processes 10L. 
Currently reproduced in 10 different fermenters.

**Comment by MajorMari** [comment]
Happens with beer mash/beer as well.

**Comment by MajorMari** [comment]
Reproduced with a new 0.3.21 character.
Also tapping finished 80L mash only empties 40L for each click on "Fill".

**Comment by Oskutin** [comment]
How you got 80L of mash, as that is multiple times of the recipe minimum?

**Comment by MajorMari** [comment]
16 sugar, 16 yeast and 4x 20L water.

**Comment by Oskutin** [comment]
But the fill button is kinda broken?

**Comment by MajorMari** [comment]
Mashing tun before Start click
![1319_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/55257457/89e0294e-e1bf-4e0e-bc11-8d3539018769)

Mashing tun after 1. Fill click
![1319_2](https://github.com/loiste-interactive/Obenseuer-Issues/assets/55257457/d7b82c5b-7b1e-43a5-b0b4-3ed09e6d4093)

Mashing tun after 2. Fill click
![1319_3](https://github.com/loiste-interactive/Obenseuer-Issues/assets/55257457/93ea5135-94ed-4e23-b22d-9c3ca52b2254)

Fermenting Barrel before Start click
![1319_4](https://github.com/loiste-interactive/Obenseuer-Issues/assets/55257457/a8291d3b-ea42-44ce-9005-499610e17ff4)

Fermenting Barrel after Start click
![1319_5](https://github.com/loiste-interactive/Obenseuer-Issues/assets/55257457/69731dc2-72d5-4aaa-8c7a-467c4932aff3)

**Comment by Oskutin** [comment]
Okay so:
Starting mash works normally, but filling only gives limited amount of 40L.
Fermenting is capped to 10L, where the cap should be 100L.

**Comment by Oskutin** [comment]
Fixed the barrel.
