### ISSUE TITLE
0.3.21 - Basement Bullet Time (Chopped up boards have low gravity, flying around the untouched basement)

### ISSUE THREAD

**Issue by aacos091** [loiste-interactive/Obenseuer-Issues#1321]
Started a new save file and played around for a bit. Went to the little basement room once already, but went back to see if the stuff inside the sacks re-spawned. Instead, the boards I chopped up with the axe were flying around in slow motion, the same happens to the boards that were on the doorway; I hit them with the axe and the boards start floating around like we're on the moon. It even blocked me from entering because the biggest board would stay stuck to the doorway even when I hit it with the axe, so I had to crouch under it. Went back to the room after an hour or so to see if it still happens and it does.

![20231129133007_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/5782996/764b5113-ecd7-4fae-8b89-c69c27326d39)
This is when I first saw it happening.

![20231129145428_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/5782996/08498077-c783-4cb9-8988-38df3c578491)
![20231129145444_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/5782996/47920ba9-baa2-4a20-8133-3ccebf10af92)
![20231129151603_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/5782996/81ecb934-ec8d-45f9-8294-ef394bcaa2ee)
![20231129151636_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/5782996/c781edb4-68dd-4bb3-87d7-90156c5203bf)
![20231129151655_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/5782996/017646c8-7a7d-4439-b339-e158f88bdda9)
![20231129151723_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/5782996/642efa1f-311c-416a-a6ea-bdb38a5206b4)
These were an hour later, chopped up boards still have moon gravity.

[Xavier_Lande.zip](https://github.com/loiste-interactive/Obenseuer-Issues/files/13505174/Xavier_Lande.zip)
These are all the saves I have for the character. Slot 3 is when I first saw it happen, Slot 6 and the Autosave was when I went back to check on it.

**Comment by Zuntti** [comment]
Fixed
