### ISSUE TITLE
Falling out of the world in Deekula C4

### ISSUE THREAD

**Issue by GreyGoldFish** [loiste-interactive/Obenseuer-Issues#1325]
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/55509085/573cdaf0-72e8-4afb-a70e-d579cf29f8ed)

Happened while walking in this room. I suspect it's the corner next to the window, but I've been unable to replicate it.

[Player-prev.zip](https://github.com/loiste-interactive/Obenseuer-Issues/files/13514981/Player-prev.zip)

I had to compress the player log file, as it is over 48KB.

**Comment by Oskutin** [comment]
Fixed
