### ISSUE TITLE
Task Tab - Tasks Separation suggestion

### ISSUE THREAD

**Issue by SaladSauce** [loiste-interactive/Obenseuer-Issues#1333]
Currently tasks : Malones main missions, side tasks and Tenement renovations are all piled up into the same bar
Makes looking for a mission your wanting to read about, to know how to progress a bit difficult, since its all piled up with the rest
**INFORMATION OVERLOAD**

You guys hopefully already planing for this, but heres the idea :
![TASKS](https://github.com/loiste-interactive/Obenseuer-Issues/assets/131527748/c570d8ff-7678-47da-abb5-bcab710d522b)

Also after completing a Renovation task, instead of it lingering in the completed tasks, add it to a Hidden category invisible to the player or just, u know, send it to a black hole.
( because its just useless renovation info pilling into the main/side tasks that the player will want to revisit to check on the story telling of the character - just like the Witcher 2&3 )

( also why is it writen like that, I say Tenent but its writen Tenement wtf?! )

**Comment by Zuntti** [comment]
Added
