### ISSUE TITLE
Composting ash

### ISSUE THREAD

**Issue by SaladSauce** [loiste-interactive/Obenseuer-Issues#1335]
Tried using Ash in the Compost thing and it completly skipped it and when straight for the waste item

Not sure if ash is meant to be used elsewhere but dumped in the garbage bin, but **FYI** dev peeps ash is a great source of nutrients for plants, (potash) so at least it should be used in the Compost.

unless this a bug cause by the update

**Comment by Oskutin** [comment]
Added alternative composting recipe, what uses ash
