### ISSUE TITLE
0.3.22 - Visual glitch when walking into market fence

### ISSUE THREAD

**Issue by CVariable** [loiste-interactive/Obenseuer-Issues#1337]
Upon walking into the fence next to the kurahaara stall,, the tarp in front of you aswell as the entire world depending on view angle glitches out.
![grafik](https://github.com/loiste-interactive/Obenseuer-Issues/assets/45665371/4180c936-b567-42d3-8a19-ec03c4ab337f)
![grafik](https://github.com/loiste-interactive/Obenseuer-Issues/assets/45665371/181577aa-9893-488b-81bd-45c7f0cba9f9)

**Comment by Oskutin** [comment]
Fixed

**Comment by Oskutin** [comment]
Oh, still happens, but differently
