### ISSUE TITLE
0.3.22 - Minor: Fermenting Barrel Collision [in Leet Hacker apartment] glitching

### ISSUE THREAD

**Issue by CVariable** [loiste-interactive/Obenseuer-Issues#1339]
Collision is buggy and sends the player flying. Have not taken damage from this yet. Unsure if this happens in other places, need to investigate.

https://github.com/loiste-interactive/Obenseuer-Issues/assets/45665371/2a659afe-95ce-453a-adcb-eb25b90770f2

**Comment by Oskutin** [comment]
Fixed
