### ISSUE TITLE
0.3.22 - Buggy Behaviour of Cooking Oil/Fluids in O-Market (#1263 extended)

### ISSUE THREAD

**Issue by CVariable** [loiste-interactive/Obenseuer-Issues#1342]
After issue #1263 was fixed, the behavior is now even weirder:
Dragging a bottle of cooking oil onto a container the player owns just makes the container disappear permanently.
Dragging it onto a container that is owned by o-market makes the fluid transfer and the empty bottle disappear.
The cooking oil bottle cost 30oc, while the oil in the mason jar cost 34oc, even though the jar should cost 8oc by itself.
Also, the bag of 99 shrooms still appears in the cooking oil's slot.
Video, reproducable in 0.3.22:
https://github.com/loiste-interactive/Obenseuer-Issues/assets/45665371/a03f478c-abf4-4f4f-bda5-f88c13209534

**Comment by Oskutin** [comment]
Fixed being able to extract oil with jars

**Comment by Oskutin** [comment]
Looks like it doesn't destroy the item, but drop it.

**Comment by Oskutin** [comment]
Fixed
