### ISSUE TITLE
Items disapearing in appt bug still happening. 0.3.21

### ISSUE THREAD

**Issue by nicbou0321** [loiste-interactive/Obenseuer-Issues#1343]
restarted a new save with the 0.3.21 update and after coming back in the appt some items was still missing. 
almost everytime i get in/out of the appt some items will disappear. 

this can be easily replicated. start a new save and place a few items in the appt, not furniture, but pickable items. 
after playing for a while, getting in/out. some items will start disappearing. 

when i last did a bug report about it 
Fixed item duplication bug (issue https://github.com/loiste-interactive/Obenseuer-Issues/issues/1228)
before was drastically worse as dozens of items would disappear, but now only one of two items will disappear. 

its very inconsistent and seems like nothing disappears at first. but start placing stuff down and you will see...
cant even keep a teddy bear, big sad as decorating my appt was one of the main reasons why i bought the game. 

pliz fix the nasty bug. your game is awesome and just needs some bug squishing :P

**Comment by Oskutin** [comment]
Can i have a save file?

**Comment by nicbou0321** [comment]
ok so ive been playing for hours on a brand new save again. 
nothing seems to disappear yet....
only thing that did disappear was the rats i let loose in my appt lol. 

i threw everything at the game and put a ton of items on the ground.
i think ive wasted like 4 hours trying to trigger it again but its so inconsistent.... 

here is the other save that still had items disappear. 
[yolo save.zip](https://github.com/loiste-interactive/Obenseuer-Issues/files/13533811/yolo.save.zip)

i hope this is not a waste of time. 
as of today i have tried to trigger it and have not been able to have anything disappear yet. 
but when i started a new save yesterday on 0.3.21 everything was getting lost.. 
its such a difficult bug to track down, very inconsistent.

**Comment by nicbou0321** [comment]
id love to playtest and give that a try myself.

cuz in the changelog about 0.3.22 it only mentions furniture disappearing, nothing about pickable player items itself disappearing. 

also, its only the 3rd time this bug has been though "fixed" yet i cant play without having my items disappear. 

id love to help test see if its actually been fixed too. as of right now im waiting for the newest public release to report my findings. 
but its been the most persistent, and inconsistent bug ive been encountering, and sorry to sound like that dumbass gamer, but this game is literally unplayable with this disappearing items glitch. am i not supposed to touch one of the main features of the game which is the appt itself? 

im literally waiting only for this singular bug to get fixed so i can go back to enjoying myself in obenseuer. 
im eager to try the next patch and report the apparent "fixed" nature of this glitch. 
if not, trust me ill come back with yet another ticket and a brand new save to report my findings. 

keep up the great work devs! yall are awesome. but i do hope this nasty bug has truly been fixed for good.
