### ISSUE TITLE
Clean water in new tenement apartment

### ISSUE THREAD

**Issue by GreyGoldFish** [loiste-interactive/Obenseuer-Issues#1345]
Happened in Leon and Leena Borg's apartment 3.

![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/55509085/7ca6aaa4-85e4-4456-9910-8ee5a726cfcf)

These are my upgrades. Should a makeshift bathroom give you clean water?

![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/55509085/f529bf97-a459-4a26-8d68-7287997dc2c6)

[Autosave.zip](https://github.com/loiste-interactive/Obenseuer-Issues/files/13532752/Autosave.zip)

**Comment by Oskutin** [comment]
Should be replaced with this: https://github.com/loiste-interactive/Obenseuer-Issues/issues/1318

**Comment by Oskutin** [comment]
Implemented
