### ISSUE TITLE
Playtest 0.3.22 - Door/curtain apartment rotation and collision issues.

### ISSUE THREAD

**Issue by MajorMari** [loiste-interactive/Obenseuer-Issues#1350]
With new 0.3.22 character: After some time (didn't notice exactly when) the entrance curtain of the player apartment with makeshift walls lost collision (ie. can walk through when the curtain is visually closed) and the open prompts location have moved 180 degrees.
![1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/55257457/3ff25027-59a6-4a5e-b6d9-1ff967bbec33)
![2](https://github.com/loiste-interactive/Obenseuer-Issues/assets/55257457/8a624fd3-89d5-4138-86eb-5d6ff21a0bf3)
![3](https://github.com/loiste-interactive/Obenseuer-Issues/assets/55257457/82668d25-cb1e-483c-92ed-ec6a65c1cbf7)

Possibly related, possibly save migration issue: Old 0.3.20 character with Decent wall upgrade: Entrance door with practically same issue, just with additional visual rotation.
![5](https://github.com/loiste-interactive/Obenseuer-Issues/assets/55257457/99588eb6-831b-4137-8e72-f56879e044ad)
![4](https://github.com/loiste-interactive/Obenseuer-Issues/assets/55257457/cb5aa5c3-aecc-4e9d-8227-d7af0462280e)

**Comment by SaladSauce** [comment]
I second this, same thing happening AFTER the update

**Comment by Zuntti** [comment]
Fixed
