### ISSUE TITLE
Bergmann Tunnels Fuse Box deletes items

### ISSUE THREAD

**Issue by GreyGoldFish** [loiste-interactive/Obenseuer-Issues#1352]
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/55509085/95eedf4e-b5bb-4403-9d68-bb86247779fd)

Steps to reproduce:

1. Have a fuse in the fuse box.
2. Have a full inventory.
3. Drag fuse to an item in your inventory.
4. Item gets deleted and fuse box replaces it.

**Comment by Oskutin** [comment]
Seems to be same as this: https://github.com/loiste-interactive/Obenseuer-Issues/issues/1342
