### ISSUE TITLE
Settings: FOV and Mouse sensitivity after update is show value 1111 by default

### ISSUE THREAD

**Issue by Kastuk** [loiste-interactive/Obenseuer-Issues#1356]
Something like saved value from previous versions after update. Changing is fixing it.
![20231202204306_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/36314945/f8356d27-f169-44f5-9d17-a1b3e9894a27)

**Comment by Ludvig11** [comment]
![20231202061305_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/31344357/76b106a0-3d1c-43f3-8a80-0b1aee8c5ec9)

FOV can display the same value, at least since the option to use windowless fullscreen was patched in.

**Comment by Zuntti** [comment]
Fixed
