### ISSUE TITLE
item in enviroment does not get added to inventory when picked up

### ISSUE THREAD

**Issue by VaughnRoper** [loiste-interactive/Obenseuer-Issues#1357]
[Slot1.zip](https://github.com/loiste-interactive/Obenseuer-Issues/files/13537320/Slot1.zip)

load the save file, walk to passmores door. check inventory. pick up the electronic parts next to the door. check inventory again. there will be no electronic parts in inventory

https://github.com/loiste-interactive/Obenseuer-Issues/assets/49763757/64b4a66b-30b5-4ff6-911f-e9fda784c1a3

this has happened to me twice with this specific item spawn spot. also a few times with planks

**Comment by CVariable** [comment]
I have never experienced this myself, but using the attached save, i can reproduce the issue every time. Very weird. Also persists when migrated to 3.22, this save is from 3.21.

https://github.com/loiste-interactive/Obenseuer-Issues/assets/45665371/1fa83791-e02b-4917-9223-9ffc572487a0

**Comment by CVariable** [comment]
Also seems to happen with the two plastic bottles behind the electronic parts, but not with the can. Emptying inventory / removing backpack does not influence it. Console has nothing.
