### ISSUE TITLE
Gameplay Bug: Terrarium makes unpickable mushrooms when furniture inventory is full.

### ISSUE THREAD

**Issue by Anomeat** [loiste-interactive/Obenseuer-Issues#1361]
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/47526549/1bb81d44-fd2f-4c5d-931d-11243f7378fa)
Can't pick up harvested mushrooms after having them overflow from the terrarium.

Ingame log (Note warnings occure during harvest from terrarium menu.
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/47526549/c6a3dd0f-fd66-4977-87ae-247640b8f665)

Save file
[Slot1.zip](https://github.com/loiste-interactive/Obenseuer-Issues/files/13538908/Slot1.zip)

**Comment by Oskutin** [comment]
Can't reproduce this, not even from the save.
