### ISSUE TITLE
Cooking Pasta Bolognese queue name not displaying and duplicates can opener

### ISSUE THREAD

**Issue by Tacoliha** [loiste-interactive/Obenseuer-Issues#1363]
Displays "Large empty tin can" in crafting queue (not totally false information), instead of showing item name. After crafting is finished can opener gets duplicated to max durability.
Version: 0.3.21
![Cooking item in queue](https://github.com/loiste-interactive/Obenseuer-Issues/assets/152793429/fd7e9c3d-9f29-47c1-8b61-82f6818f45b1)
![Cooking finished](https://github.com/loiste-interactive/Obenseuer-Issues/assets/152793429/25959bf9-d671-4ebc-8d04-11a112242403)

**Comment by Zuntti** [comment]
Fixed
