### ISSUE TITLE
Suggestion: When crafting a recipe, keep the last crafted recipe open so you don't have to always reselect the same recipe when you're doing a series.

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#137]
https://user-images.githubusercontent.com/44178400/234670840-09de6221-5ec4-4511-a234-37673c71e819.mp4
Edit: Or even allow to schedule multiple recipes so they are being done automatically as long as you're keeping the window open and there are free slots (example, tap 9 times the Water recipe)

**Comment by kaygray** [comment]
Yes, please allow multiple crafting

**Comment by Nextej** [comment]
More suggestions:
1. with recipes added like lockpicks, crafting scheduling is even more important
2. selected recipe preview inside a machine UI closes at few annoying occasions:
 - you've selected a recipe, turns out machine has no power, turning it on closes the recipe and you have to reselect it
 - you're at a stove with 4 slots, an item is being done in the background, you were just meant to select another one to cook, but the one that was being done finished and closed the selected recipe
3. even if all working slots are taken, keep the recipe on so you can immediately select the next one, also referencing back scheduling.

**Comment by Zuntti** [comment]
Updated crafting menu behavior
