### ISSUE TITLE
Police arrest me for trespassing in weird circumstances

### ISSUE THREAD

**Issue by pantherpusher** [loiste-interactive/Obenseuer-Issues#1372]
Basically the issue is that I went into the gatehouse and then down into the prison, and was then immediately arrested by the guard there, but the door wasn't locked and I saw no posted sign to tell me to not just walk in. Basically, I dunno, maybe have the guard just kick me out like "Hey man, you can't be in here" instead of instantly a 1000 point bounty and jail

**Comment by Zuntti** [comment]
Not sure why the door wasn't locked but added authorized personnel only sign to the door and also sign about the camera
