### ISSUE TITLE
0.3.22 new save items disappear still.

### ISSUE THREAD

**Issue by nicbou0321** [loiste-interactive/Obenseuer-Issues#1373]
only weird thing i noticed this save is one time i had a full inventory and i was looking at an item, i removed an empty syringe which landed on what i was looking at, after i took it both items were gone. which was odd. 

played like a solid 4-5 hours, nothing weird was happening yet until at some point i placed down 4 steel bars on a wooden stool when i came back 2 was missing. 

i am very aware of the things i place down, so when something goes missing i notice right away. 

but after playing this game for a long time a lot of errors spams the console. idk if this contributes to the issue.
immediately after the steel bar was lost i saved and packed this zip. restarted the game and am still playing so far nothing else has disappeared. [isda_glitchgone.zip](https://github.com/loiste-interactive/Obenseuer-Issues/files/13574789/isda_glitchgone.zip)
i also packed the player log in the zip. hopefully its gonna be helpful a bit. 

its a lot more stable then initially, dont give up devs! im sure you will get that nasty bug for good.

**Comment by nicbou0321** [comment]
i just want to add that, after 8+ hours of adding random crap all over my appt, and restarting the game every hour or so ish. 
i have not yet encountered an item disappearing again yet.. 
but the constant error spam in the console over time is probably not helping. 

this update has helped a lot. ive been having a blast setting my place up properly and my bed is getting full of all the plushies i can find :P

like ive mentioned, restarting the game every hour or so ensures it stays stable and without errors. it seems to do the trick to not have any other issues with the disappearing items for me so far. 

loving the game so far thanks so much devs for making such a nice game <3

**Comment by nicbou0321** [comment]
more comments and pleasures to add :P

after a solid +10ish hours added on this same save, restarting the game after about an hour ish, trying not to play too long without a restart. its been a pretty solid experience so far. 

ive been having good progress, storing things all around and in buildable storage/furniture. 
until one time i pushed the game too far and didnt restart....

suddenly, a whole ass chest full of materials was gone :(
this is a first for me, furniture goes missing too.. rip. 

save 1 is before things glitched, save 2 and 3 are after its glitched and a bunch of items and the chest disappeared.
other saves seems to be unaffected as they also were before it glitched. 
[isda_glitchgone.zip](https://github.com/loiste-interactive/Obenseuer-Issues/files/13598499/isda_glitchgone.zip)
i also included the player log in the zip

screenshot of the missing chest
![Screenshot (45)](https://github.com/loiste-interactive/Obenseuer-Issues/assets/151878567/d8c206a6-2852-49cc-8825-6d8f19b6c2e1)

to me it kinda feels like some kind of memory leak or something. idk. 
i wish yall devs best of luck in fixing this nasty bug, loving the game so far yall are the best <3

**Comment by Oskutin** [comment]
At one point i head that renting an apartment / resident finishing moving in might cause htis.

**Comment by Zuntti** [comment]
Slot 8 still has it (Time: 10:28) and slot 9 not (Time: 10:32)

**Comment by nicbou0321** [comment]
> I made some changes that might help with this, but it's still a mystery what's causing this bug. Also slot 8 has three bag of green mushrooms and slot 9 does not.

i was hella tired when i wrote. it was 6 am for me lol.
i didnt even notice that slot 9 was the first slot that started glitching. 
its very weird but thank you so much for that small notice, as just that saved me a bit of lost progress. 

im gonna keep torture testing the game, as of writing im on the latest update 0.3.23 and still using this same save. no issues so far. 
im aware things can break at this point but to my knowledge, the game feels and runs solid for about an hour until the coding goes haywire with the error spam in the console, then things starts disappearing. 


i sure hope you guys can find and fix this bug one day as its pretty annoying losing your stuff constantly due to game instability. 
im holding yall at bugpoint right now, better not let thru too many bugs or else... ill have to keep reporting bugs... :P
keep up the great work!
