### ISSUE TITLE
Rats have collisions, you can push 'em or get stuck on them, feels like something that would rather be unsolid to player.

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#138]
https://user-images.githubusercontent.com/44178400/234675396-066fe2f1-0461-43c0-aedc-9ba711a9ac0f.mp4

**Comment by Oskutin** [comment]
But kicking rats is fun

**Comment by Nextej** [comment]
Then they should not be able to block you at last.

**Comment by CBS-S** [comment]
I say let them fight
