### ISSUE TITLE
Floating trash spawns outside of fence

### ISSUE THREAD

**Issue by sewer-dweller** [loiste-interactive/Obenseuer-Issues#1388]
A piece of floating trash spawns just outside of the fence right by the yellow skull sign near the One Stop Shop

Sometimes it's there, sometimes it's not, but I've seen it in every save eventually.

![Screenshot (657)](https://github.com/loiste-interactive/Obenseuer-Issues/assets/153145346/bfcabf25-2e6e-4d79-ba48-00028e9689e8)

**Comment by Oskutin** [comment]
What are your tenement levels?

**Comment by sewer-dweller** [comment]
I'm not sure about levels, but I've never gotten more than my own apartment and the 2nd floor small apartment renovated passed makeshift.

**Comment by Oskutin** [comment]
Can I get a save where this happens?

**Comment by Oskutin** [comment]
Fixed
