### ISSUE TITLE
Gameplay Bug: Mashing Barrel says it's full when it is not, and alternating between two 'full' barrels generates a wall of text.

### ISSUE THREAD

**Issue by CCTV4569** [loiste-interactive/Obenseuer-Issues#1391]
I was trying to sell two mashing barrels (the log-fuel requiring ones), and after emptying the containers and picking them up it said in the build menu that they were still full. Since I had two of them, I was able to alternate between them and noticed that alternating very quickly would also generate a wall of text. So two bugs possibly?

![20231207212253_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/51306552/431be8e5-f617-47ab-b177-10debe7d28bb)

Version: Current (0.3.23)

**Comment by Zuntti** [comment]
Fixed wall of text

**Comment by Zuntti** [comment]
Fixed
