### ISSUE TITLE
Microwave can't be picked up or moved in player apartment

### ISSUE THREAD

**Issue by snortico** [loiste-interactive/Obenseuer-Issues#1392]
Put down old microwave, cannot pick it up or move it. Clicking on it sets it to a random orientation no matter whether on take or move in build menu.
[Slot1.zip](https://github.com/loiste-interactive/Obenseuer-Issues/files/13609276/Slot1.zip)

**Comment by Oskutin** [comment]
Looks like it was some kind of save migration issue, where the microwave lost its furniture reference.

**Comment by Zuntti** [comment]
Changed to be able to remove furniture if furniture reference is missing
