### ISSUE TITLE
Fermenting Barrel still caps at 10L

### ISSUE THREAD

**Issue by cressiwa** [loiste-interactive/Obenseuer-Issues#1393]
![20231208153809_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/153289265/50b22913-aff8-4297-b4fc-1fc230ce07cf)
![20231208153814_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/153289265/4ff1b7b9-70ef-4a13-9b2d-5acacc152d72)
Dropping mash in fermenting barrel implies it would process 16L but caps at 10L. 
Steam version 0.3.23

**Comment by Oskutin** [comment]
Is the barrel from old save?

**Comment by cressiwa** [comment]
> Is the barrel from old save?

Yes. Issue is fixed after the barrel is placed again.
