### ISSUE TITLE
character no longer gets tired

### ISSUE THREAD

**Issue by tharkios** [loiste-interactive/Obenseuer-Issues#1395]
No sign of the tiredness meter after multiple days in-game, or even after popping a full bottle of prescription sleeping pills. (Did drink ~2 liters of coffee at one point, and save started on an earlier patch, either of which might be the problem source.)

**Comment by Oskutin** [comment]
Drinking ~2L of coffee, seems to cause -500 tiredness, meaning that doesn't need to sleep for a week.

**Comment by tharkios** [comment]
Fair enough! If only it worked that well in real life!

**Comment by Oskutin** [comment]
Capped negative tiredness to -100
