### ISSUE TITLE
Mashing issues

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#140]
1. Mushroom Beer/Turnip Mash (and potential any Mash requiring Shrooms) doesn't take "Green Mushrooms" (id: 13560) as the recipe state, it takes instead "Bag Of Green Mushrooms (High/Medium/Low Potency)", however once the recipe is started, the Mushrooms are not taken and can be reused, unlike other ingredients.
2. I kinda preferred the old UI of Mashing Tun where were you just dropping the ingredients straight onto the machine. I don't feel like this crafting system conveins well into Mashing and probably Fermenting. I dunno what can be done about it, nor how others feel about crafting in those machines.

**Comment by Oskutin** [comment]
Fixed
