### ISSUE TITLE
A system to learn building address

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#1401]
- Each building should have an actual address written next to the entrance door, in Poland of instance, building name/address is written across its sides
Trade Street **Deekula A1-8**
Trade Street **Deekula B1-11**
Trade Street **Deekula C1-7**
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/c0c01619-5085-4e1a-ab18-2bfc2a0ee510)

- Looking at the address sign, stairwell entrance number or looking at the entrance doors (except Playerment) should mark the address as learnt, reveled on a map, used in tasks, etc.
- For playerment, additionally also looking (and hovering mouse perhaps?) at the address on the first page of the blueprint to reveal the address.
- Playerment's address should be an objective to learn in "Missing Debitcard" if player hadn't before, used for OS-Magazine to start getting mail, etc.
- Perhaps optionally Malone should be able to ask for the address (only after player is asked for address first via Missing Debitcard for letters to send back to or by OS-Magazine doorbell)
- On mininimap it should replace a regular marker, perhaps make it behave similar to something like on OpenStreetMap? 
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/70f6a7d3-94dc-46c7-8c9a-b4f50088db3f)
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/86316751-0d39-4bc4-83c5-04048e4a6e96)

**Comment by Nextej** [comment]
- Notification for newly found address should also be displayed in similar fashion to mail, rent and other notifications:
```
Address found:
Trade Road Deekula A
```

**Comment by Oskutin** [comment]
All Deekulas have same street number, apartment adresses for example.
Traderoad 1 A2
Traderoad 1 B2
Traderoad 1 C2

Learning playerment address makes no sense, as the adress would be given when player gains the owenership.

Closing this as map markers kinda do the same job now.
