### ISSUE TITLE
Stolen Item Stacking

### ISSUE THREAD

**Issue by alloysiuspercivalblack** [loiste-interactive/Obenseuer-Issues#1406]
There is an issue with the tagging of stolen goods with items of the same type not stacking together if they are stolen. This doesn't happen every time but is very common, it appears to be related to the location they are stolen from but without digging into the code its hard to tell. The most annoying example being stolen nails which you can often have 4 or more stacks of fewer than 5 that don't stack together

**Comment by Ryder17z** [comment]
I'd still consider this a bug as long as there is no official explanation. If the item's owner was visible when hovering over the stack, there wouldn't be any confusion as to why stuff don't stack

**Comment by alloysiuspercivalblack** [comment]
ok, so if not a bug can I make a suggestion that this distinction is meaningless unless their are mechanics related to it planned in the future
