### ISSUE TITLE
Arrested for doing my job.

### ISSUE THREAD

**Issue by Im-Brandfall** [loiste-interactive/Obenseuer-Issues#1407]
Using the harvest all button on vine plants causes Jomppe to increase your crime count like you just stole from him. I haven't tested if it still happens when you load a game, but it has happened once per plant.   Most recent version of the game (the game version doesn't display in the pause menu.)

![Screenshot_12](https://github.com/loiste-interactive/Obenseuer-Issues/assets/50027813/e92fa174-9e6f-4fb8-bc3d-b959b1590020)
[Player - Copy.log](https://github.com/loiste-interactive/Obenseuer-Issues/files/13626358/Player.-.Copy.log)

**Comment by Im-Brandfall** [comment]
Finally got a photo!
![Screenshot_13](https://github.com/loiste-interactive/Obenseuer-Issues/assets/50027813/08de8a08-6f62-411a-8d9f-411d64957223)

**Comment by Im-Brandfall** [comment]
Turns out harvesting any of the vine plants will have him yell at you.

**Comment by Zuntti** [comment]
Fixed
