### ISSUE TITLE
Mr. Duck dialog option still visible after quest

### ISSUE THREAD

**Issue by cressiwa** [loiste-interactive/Obenseuer-Issues#1415]
![20231210194445_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/153289265/141dd9d5-d79a-4a06-8238-f85e33c5bb9a)
![20231210194452_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/153289265/3695160b-0b0f-40b9-ba83-139630412d38)

I took the blue duck ages ago (and have an addiction, help) it's still visible in task items but Mr. Duck's "Give 5 ducks and axe" prompts were still active and removed my items. Mr. Duck also gave the upstairs key for the second time (copy not added to keys).

Steam version 0.3.23

**Comment by Zuntti** [comment]
Fixed
