### ISSUE TITLE
Tomato plant not harvestable at 100%

### ISSUE THREAD

**Issue by cressiwa** [loiste-interactive/Obenseuer-Issues#1416]
![20231210205147_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/153289265/de694eb0-eb09-4c2f-a809-09a03577f403)

Tomato plant not harvestable at 100%. This was only for a minute, I was able to harvest after.

Steam version 0.3.23

**Comment by Zuntti** [comment]
Can I get a save where this happens?

**Comment by cressiwa** [comment]
> Can I get a save where this happens?

Should I try to reproduce then save or would current state be enough? This was a while ago.

Also how do I extract a save file? :)

**Comment by Zuntti** [comment]
You can find saves at "C:\Users\ [username] \AppData\LocalLow\Loiste Interactive\Obenseuer\Saves" but I fixed it now so I don't need it anymore
