### ISSUE TITLE
Stuck on toilet after Stairwell Upgrade to level II

### ISSUE THREAD

**Issue by sashort** [loiste-interactive/Obenseuer-Issues#1417]
Per this Steam Discussion:
 https://steamcommunity.com/app/951240/discussions/2/4029096129896104752/?tscn=1702220279

I have included 2 saves, before and after getting stuck on the toilet.

To produce the bug from Slot1 save;
1. walk up to apartment 4, owned by Nina Lund,
2. and use the toilet. This is where you get stuck.

Slot 2 is the save after the bug occurred. 

[Slot1.zip](https://github.com/loiste-interactive/Obenseuer-Issues/files/13629067/Slot1.zip)
[Slot2.zip](https://github.com/loiste-interactive/Obenseuer-Issues/files/13629070/Slot2.zip)

**Additional problems related to same bug**
It also appears than you cannot use any other toilets by pressing E, despite interact text being visible. No sound is produced in this case. I tested this on Slot1 with: other bucket potties located in my tenement, porta-potty outside my tenement, toilet in the bar, and the toilet in the hostel.

**Comment by Zuntti** [comment]
Fixed
