### ISSUE TITLE
Game crashes when picking up red barrel

### ISSUE THREAD

**Issue by Kewk-Kewk** [loiste-interactive/Obenseuer-Issues#1418]
I placed a red barrel at the start on my playthrough on 0.3.21.
Now i have progressed quiet a bit and wanted to change my apartment on 0.3.23. 
Everything worked quiet smooth this far apart from 1 loading crash. 
But now when i try to either move or pick up the red barrel my game crashes instantly while my ram is slowly overflowing. 
Technically it could be caused by the update, but i thought i should share it. 
Maybe someone knows a workaround or encountered the bug before.

PS. Please help the barrel is completly blocking my new crafting station :(

**Comment by Zuntti** [comment]
Can I get a save where this happens?

**Comment by Kewk-Kewk** [comment]
Thank you!
