### ISSUE TITLE
Edge Case: O-Market Bread shelf shows 99 shrooms when bread hits 0%

### ISSUE THREAD

**Issue by sashort** [loiste-interactive/Obenseuer-Issues#1419]
If you are in the O-Market and a bread shelf's breads reach 0%, the inventory display incorrectly shows 99 Bags of shrooms when you press E to interact with the shelf. Interacting with the shelf 7 more times will fix this bug. The visible loaves of bread will disappear, and the inventory will show as empty.

In Slot3, interact with the white bread on the top shelf immediately after loading. Notice the breads are at 0%. Wait 2-3 seconds and interact with the shelf again. The shrooms are now visible. You can't take them, however.

![bread edge case](https://github.com/loiste-interactive/Obenseuer-Issues/assets/95879519/e8e299d8-492a-435a-8209-e79e5a78c3e7)

[Slot03.zip](https://github.com/loiste-interactive/Obenseuer-Issues/files/13630001/Slot03.zip)

**Comment by Oskutin** [comment]
Should not happen anymore
