### ISSUE TITLE
Menu Feedback

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#142]
1. Remove Space from being an action button, Re: https://github.com/loiste-interactive/Obenseuer-Issues/issues/75
2. When using arrows to navigate up and down, allow the Menu options to loop as well as start navigation from the last highlighted option (so including the ones hovered over by a mouse),

**Comment by ontrigger** [comment]
+1

**Comment by Zuntti** [comment]
Removed space being an action button
