### ISSUE TITLE
Inability to use toilets (all of them) after softlock.

### ISSUE THREAD

**Issue by TheOnlyLynx** [loiste-interactive/Obenseuer-Issues#1421]
While messing about and trying to break the game, I tossed random junk into the "search" spot in a toilet and then used it. (Specifically all slots are full before use) 

Was able to use toilet but then was unable to stand up again. 

Loading back most recent save has resulted in **ALL** toilets being unusable.

Exiting game and booting game once again resolves issue. 

Unable to recreate bug after several attempts.

**Comment by Oskutin** [comment]
Got logfile?

**Comment by TheOnlyLynx** [comment]
[Belladonna_Lyn.zip](https://github.com/loiste-interactive/Obenseuer-Issues/files/13640171/Belladonna_Lyn.zip)


Here you go

**Comment by Zuntti** [comment]
Already fixed https://github.com/loiste-interactive/Obenseuer-Issues/issues/1417
