### ISSUE TITLE
Uncraftable veggie soup

### ISSUE THREAD

**Issue by cressiwa** [loiste-interactive/Obenseuer-Issues#1424]
![20231211213818_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/153289265/9b8b1284-3be4-4501-91e7-6864e56cfab2)

I havent been able to make vegetable soup ever. I dont seem to be missing any ingredients or stove modifier. The recipe does show up and doesnt have any red text anywhere.

Steam version 0.3.23

**Comment by Garubon** [comment]
I've had this with sausage soup too but I wasn't sure if it was because I was using a hotplate or not

**Comment by Zuntti** [comment]
Fixed
