### ISSUE TITLE
Cooking oil not red in wheat dough recipe when it's missing

### ISSUE THREAD

**Issue by cressiwa** [loiste-interactive/Obenseuer-Issues#1425]
![20231211141656_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/153289265/abc9a1ea-b69a-4bfb-a123-8f6d81a22c3c)

Cooking oil seems required but never seems missing(?) in wheat dough recipe. It is needed to actually make it though, its just not red.

Steam version 0.3.23

**Comment by Zuntti** [comment]
Fixed
