### ISSUE TITLE
Hardware Vendor close time 18:00 instead of 17:00 on Thu | hardware Vendor doesn't close if you're standing in the market outside.

### ISSUE THREAD

**Issue by sashort** [loiste-interactive/Obenseuer-Issues#1426]
I've been able to verify the closing time for the Hardware vendor is 18:00 on Thu. It is posted as 17:00, however.
I waited until 17:00 to elapse in Slot4, expecting the tarp to appear over the tent. Nothing happened.
I waited until 18:00 to elapse in Slot5, nothing happened.

I figured some other bug was at play, so I walked into the O-Market at 1 past the hour for both slots.
Upon returning outside on Slot5, slightly past 18:00, the tarp was down over the Hardware vendor tent.
The Hardware vendor was still open in Slot4, indicating they do not close at 17:00, rather 18:00.

[Slots4-5.zip](https://github.com/loiste-interactive/Obenseuer-Issues/files/13640132/Slots4-5.zip)

**It would be funny if right at the closing time, and if you are interacting with the vendor, a dialog appears beneath the inventory window.**
- "Can you hurry up! I'm starving! There's a delicious cat pizza with my name on it back home."
- "Are you done yet? I haven't eaten all day! I have to go pray and listen to blah blah blah before I can even eat, and you're holding me up!"
After closing the window the vendor closes.

**Even funnier, the inventory/interact window closes automatically, the venue closes, and then a dialog box appears:**
- "Sorry, I've had to pee for 2 hours! Come back when I'm open." (Sound of vendor peeing into bottle)
- "I need a drink! Need to get to the bar before the only thing they're serving is shit something or another.... Come back when I'm open!"
- "The nerve of some people! Coming over to shop at the last minute! You'd think I live here and cater to their beckon call any hour of the day!"

**Comment by Zuntti** [comment]
Fixed closing time
