### ISSUE TITLE
Paint buckets should stack (not a high amount, more like 4 or 8 ?)

### ISSUE THREAD

**Issue by Ryder17z** [loiste-interactive/Obenseuer-Issues#1430]
It seems weird that cement and sandbags can be stacked 16x but the physically smaller paint buckets cannot.

I think the paint buckets take up too much inventory space without stacking.

If it stacks in 4 or 8 that would be fine I think. I'm not sure about higher amounts but it doesn't make sense to me that they do not stack at all.

**Comment by Zuntti** [comment]
Changed
