### ISSUE TITLE
Mashing Kettle seems to have inaccessible items in it, preventing sale or disassembly

### ISSUE THREAD

**Issue by thePalindrome** [loiste-interactive/Obenseuer-Issues#1439]
Not sure what it is, but it shows up in the building menu, the workbench, and furniture stores, and nothing I do seems to really help with it!

**Comment by thePalindrome** [comment]
Okay, the Fermenting Bucket and Mashing Tun are also doing the same. Switching between them in the build menu also causes the text to concatenate forever, which is amusing

**Comment by CVariable** [comment]
This is issue #1391

**Comment by thePalindrome** [comment]
Fair enough, it didn't show up in the search, must've used the wrong keywords
