### ISSUE TITLE
UI Suggestions

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#144]
1. Allow to view recipes and blueprints you've acquired from within the inventory, especially for Mashes and Meals, would be way easier to be able to check at any time what else you have to gather.
2. Under notes, allow to have Player's Notes in a form of simple notepad, or even allow to have multiple of them. It kinda goes against the first suggestion, but so like me, you don't have to keep alt-tabbing out of the game to see what items you've noted down in MS Notepad for Mash crafting... the more the game expands, the more potential uses for actual working in-game text based notepad I see.

**Comment by ontrigger** [comment]
Hard agree for the first point. What's the point of getting a recipe if you can't even read it?

**Comment by Nextej** [comment]
About 2. now with renovation mechanic added and tons of recipes and upgrades to choose from, with hell amount of items to get prepared, a way to note that all and keep with you is even more valuable, additionally it would be nice if you could have the notepad window open while any other tab is open, so for instance you can have tenement tab open and a notepad at the same time.
