### ISSUE TITLE
Bug: Interrupted Checkout at O-Market and Skeida Pharmacy

### ISSUE THREAD

**Issue by sashort** [loiste-interactive/Obenseuer-Issues#1440]
1. Get anything you want to buy from either store (move into your inventory.)
2. Click the cash register to start the checkout.
3. Walk out of the store.
4. Walk back into the store.

Those items will still be on the counter, but the cash register will only say you need to pay 1 OC/RM.
If you pay the 1 OC/RM and move the items into your inventory and try to leave, the doors are locked and the alarm goes off.
You have to start the checkout again and pay the full amount minus 1 OC/RM to fully purchase those items.
This happens each time you start to check out, walk out, then, walk back in. Each time you get a piece of crumpled paper.

Best solution in my opinion: clear any items on the counter when walking into the store.
In a real store unpurchased items will get put back on the shelf.
Someone might say that those items disappearing counts as a bug. I would argue and say everything you can buy in the store will respawn and be available for purchase again. The cashier has just placed those items off to the side to restock later.

This solution also eliminates another related bug, where you are stuck paying 1 OC for mold if you leave let bread go bad in the aborted checkout at O-Market.

**Comment by sashort** [comment]
The only exception to this should be prescription medicines.

**Comment by Oskutin** [comment]
Now the conveyor just resets state upon load.
