### ISSUE TITLE
Playtest 0.3.24 - Samuel no longer detects any items in Tenement Contract Work Chest

### ISSUE THREAD

**Issue by CVariable** [loiste-interactive/Obenseuer-Issues#1452]
Despite Items being present in the Tenement Contract Chest, Samuel will not detect or use them. He will only use items currently in the player inventory. This seems to count for all items, persists after saveloading, and is present in both a migrated 0.3.23 aswell as this new .24 save:
[Slot2.zip](https://github.com/loiste-interactive/Obenseuer-Issues/files/13687777/Slot2.zip)
![grafik](https://github.com/loiste-interactive/Obenseuer-Issues/assets/45665371/087c0ae7-3d2a-47fd-ba25-0cc04b7bdccb)
![grafik](https://github.com/loiste-interactive/Obenseuer-Issues/assets/45665371/a54b0937-974a-42e0-a181-36910cc71b4b)

**Comment by Orphiex** [comment]
Also experiencing this problem; I've only experienced it when loading from an old save, and am now testing a new save to see if it's repeatable there.

However, Samuel also fails to detect building materials held in inventory, or more accurately, he detects them but somehow fails to register them as usable:

![20231216160810_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/16548338/cfc4ee49-7430-4ab5-be13-9008d063495e)

**Comment by Zuntti** [comment]
Also fixed
