### ISSUE TITLE
Playtest 0.3.24 - Alarm clock no longer works

### ISSUE THREAD

**Issue by CVariable** [loiste-interactive/Obenseuer-Issues#1453]
Despite having the alarm clock in my inventory, i do not have the slider to set a time to wake up at. It does still display the time like a watch. This persists after saveloading, and happens both in a migrated 0.3.23 and a new 0.3.24 save: 
[Slot3.zip](https://github.com/loiste-interactive/Obenseuer-Issues/files/13687875/Slot3.zip)
![grafik](https://github.com/loiste-interactive/Obenseuer-Issues/assets/45665371/2f985a26-f84f-40f6-8e31-17a75239ba8d)
![grafik](https://github.com/loiste-interactive/Obenseuer-Issues/assets/45665371/3183e144-fc63-4b02-983b-b0cb3049567c)

**Comment by Zuntti** [comment]
Fixed
