### ISSUE TITLE
Playtesting - Kurahaara map icon is given to the player before the player is even aware of the Kurahaara

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#1457]
I propose two conditions, either talk to malone first before the icon is added or talk with kurahaara before the icon is added.

**Comment by Zuntti** [comment]
You mean when you get to the greenhouse with big Kurahaara Brothers Farming Cooperative sign?

**Comment by Zuntti** [comment]
Added a sign above the door
