### ISSUE TITLE
Playtesting - When starting new game, Lonkka Kurahaara is sleeping while the Stall is already open.

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#1458]

**Comment by HealthAngel911** [comment]
It still happening even at this version [0.3.33]
After you go out from border control, and head to the Kurahaara Brothers' stall you can find his stall open and NPC put in sleeping state. Attaching the screenshot.
![20240206010948_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/76599402/28617a24-e25b-4765-9f0e-01d04e3dc285)
