### ISSUE TITLE
Playtest 0.3.24 - Para Haju no longer accepts shroom rollies or an osmo bottle

### ISSUE THREAD

**Issue by pinkamedic** [loiste-interactive/Obenseuer-Issues#1463]
in the current playtest the option to give him a shroom rollie or an osmo bottle is no longer there even after expensing his dialogue

**Comment by pinkamedic** [comment]
on further playing you cannot give malone petronis osmo bottles

**Comment by CVariable** [comment]
This probably includes the turnip head not accepting his turnip moon, the Zebra Zigarette woman, and Dr.Pena.

**Comment by Zuntti** [comment]
Fixed
