### ISSUE TITLE
Playtest 0.3.24 - Dr.Pena has given up on working

### ISSUE THREAD

**Issue by CVariable** [loiste-interactive/Obenseuer-Issues#1465]
Despite having taken a turn number and waiting for the door to open, Dr.Pena will not accept my turn number, no matter how many times i repeat the process. Saveloading does not change this. This save is new from 0.3.24:
[Slot9.zip](https://github.com/loiste-interactive/Obenseuer-Issues/files/13688571/Slot9.zip)

![grafik](https://github.com/loiste-interactive/Obenseuer-Issues/assets/45665371/87b05c2d-e599-4976-b659-b1e44681c5ba)
![grafik](https://github.com/loiste-interactive/Obenseuer-Issues/assets/45665371/7d47f690-00cf-42ac-84e8-8de39e386b05)

**Comment by Oskutin** [comment]
Looks like all dialogue item conditions have broken:
https://github.com/loiste-interactive/Obenseuer-Issues/issues/1463

**Comment by Zuntti** [comment]
Fixed
