### ISSUE TITLE
Playtest 0.3.24 - Cleaning mode can be accessed outside of Tenement

### ISSUE THREAD

**Issue by CVariable** [loiste-interactive/Obenseuer-Issues#1466]
This seems to change nothing except the bottom description appearing, all interactions are normal.
O-Market: 
![grafik](https://github.com/loiste-interactive/Obenseuer-Issues/assets/45665371/9b845153-05eb-4fd5-b8a5-ed21d61fd77d)
Outside map:
![grafik](https://github.com/loiste-interactive/Obenseuer-Issues/assets/45665371/58c212eb-5198-45ac-995b-949408bbc066)
Probably happens on other maps too.

**Comment by Zuntti** [comment]
Fixed
