### ISSUE TITLE
Playtest 0.3.24 - cannot use cleaning spray or disinfect bottles to clean up 

### ISSUE THREAD

**Issue by pinkamedic** [loiste-interactive/Obenseuer-Issues#1467]
in the newest version you cannot clean up the hazmat bags or the graffities in the tenement despite having the needed items

**Comment by Zuntti** [comment]
Seems to work for me. Can I get save where it's not working?

**Comment by pinkamedic** [comment]
> Seems to work for me. Can I get save where it's not working?

im unsure if its an issue anymore as when testing it i cannot get it to repeat
