### ISSUE TITLE
Playtest 0.3.24 - Entering speakeasy drops player under the map

### ISSUE THREAD

**Issue by CVariable** [loiste-interactive/Obenseuer-Issues#1468]
When entering the Tenement A basement, the player will spawn in the dark below the map. Looking upwards reveals the player is falling. This is reproducable upon saveloading, and on a new 0.3.24 save:
[Slot6.zip](https://github.com/loiste-interactive/Obenseuer-Issues/files/13688698/Slot6.zip)

![grafik](https://github.com/loiste-interactive/Obenseuer-Issues/assets/45665371/57511172-a6ce-4965-8449-706c5ed2aee3)

**Comment by Oskutin** [comment]
fixed
