### ISSUE TITLE
Toilet in B8 can lock your camera angle

### ISSUE THREAD

**Issue by CBS-S** [loiste-interactive/Obenseuer-Issues#147]
I'm not sure what the preconditions for this are - it's repeatable in the new game I just started but I didn't run into it in my prior game - but if you're looking at the toilet in B8 and it says "Toilet (Stand Up)" while you're already standing (as opposed to "Toilet (Relief)" if you need to use it) and press E, it flushes the toilet and turns off mouselook so you can't move the camera around. You're essentially trapped at that point because you can't turn around to leave the apartment.

When I reloaded from an autosave, the game seemed normal again, until I went back to B8 and opened the apartment door again, at which point it put me back into the same camera angle and locked me there again. After reproducing this a couple of times, I tried opening other doors first. Those acted normal, and when I got back to B8 it let me use the door without locking the camera again. I think opening the other doors cleared whatever was wrong with the autosave.

**Comment by CBS-S** [comment]
Update: Just tried the winch in B9 and it locked the camera again. I think this save is perma-bugged after all.

**Comment by Oskutin** [comment]
I think this is fixed by now.
