### ISSUE TITLE
Lit Growlight Flowerboxes Maintain "Sun" Value Even When Unpowered

### ISSUE THREAD

**Issue by veliandev** [loiste-interactive/Obenseuer-Issues#1476]
Given the player crafts the Flowerbox with grow lights and set it down in the basement,
When the player examines the status effects of the grow box when the light is enabled (powered)
Then the player can see that the 'Sun' effect is enabled.

But when the player examines the status effects of the grow box when the light is disabled (unpowered),
Then the player can see that the 'Sun' effect is still enabled when it should be replaced with 'Moist'.

**Comment by Oskutin** [comment]
Fixed
