### ISSUE TITLE
Refresh rate not being honored

### ISSUE THREAD

**Issue by DavidGraff** [loiste-interactive/Obenseuer-Issues#1477]
Program seems to forget set refresh rate in settings and defaults to max rate supported by the monitor at re-launch.

Win 11 22631.2861
Radeon 5700 XT w/ Adrenalin 23.12.1 driver
Acer freesync display, max refresh rate 165hz

This display gets wonky at 165hz (flickers, 6-bit with dithering instead of 8-bit color), so I run it at 144 instead. This is with freesync disabled in the driver config. Gets even wonkier with it on, shown refresh rate in the display options immediately reverts back to 165hz.

![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/153752812/0035b4fd-c9b2-48a7-9839-eff182a42add)

On launch
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/153752812/0f5457d3-ff20-4815-85b9-2dc20673d852)

Changed
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/153752812/3eec6f0f-fb58-46a8-bb29-3996dbfa5b0c)

After re-launch
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/153752812/ac590ac8-423e-4fbd-8897-99cbe1e9b860)

Confirmed with the monitor OSD that it is reverting to 165hz and it isn't just a UI display bug.

**Comment by Zuntti** [comment]
Fixed
