### ISSUE TITLE
A need for undeground passsages to allow reaching various locations of Residential districts from undeground traverse.

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#1481]
- Connection from Bergmann Tunnels (there's an unused flooddoors) to Speakeasy (there's several unused doors in the entrance hallways, one could lead to bergmann)
- Connection from Tenement A to Speakeasy (another of those unused doors could be used for that), so the player doesn't have to leave to the outside.
- Connection from undeground (I'm thinking that Deekula Basement has a potential with one unused doors behind boarded pathway) to Playerment (pretty sure there are at least one unused doors in the basement that could be reused).

Reason for them to exist:

- with a police bounty on a player, a way of moving "underground" between key locations, totally avoiding entering the outside
- making the underground section less linear and useless, giving player more reasons to find new routes and shortcuts from known locations (these new paths could be locked behind some keys, lockpicking, blocked paths first).
- shortening the time to load some maps, sure the Speakeasy would be accessible if player first loads tenement A, then outside, then speakeasy, but that's just annoying.
- I don't think an undeground skip around toll bridge is something that'll break balance, it wouldn't be that best way of traverse by default and toll bridge would be faster anyway, especially if player walks around outside mainly.

**Comment by Oskutin** [comment]
This is basically the upcoming mines
