### ISSUE TITLE
Playtesting - Reloading the playerment causes taken furniture (default pre-placed one) to respawn, both in player's apartment and other ones.

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#1482]
Might be happening when game is restarted and then reloaded, not sure.

**Comment by Nextej** [comment]
Alright, not all furniture did respawn, the notable ones that didn't are the shroomlight hooks from apartment 6

**Comment by Nextej** [comment]
[Obenseuer.zip](https://github.com/loiste-interactive/Obenseuer-Issues/files/13697195/Obenseuer.zip)

could not reproduce further
[Mirjami_Hansley.zip](https://github.com/loiste-interactive/Obenseuer-Issues/files/13697200/Mirjami_Hansley.zip)
slot 2 has the issue, slot 3 is fine

**Comment by Oskutin** [comment]
New or old save?

**Comment by Nextej** [comment]
new one

**Comment by Zuntti** [comment]
I have not idea what caused this. Save doesn't seem to throw any error related to this.

Log has these
```
NullReferenceException: Object reference not set to an instance of an object
  at FurniturePlaceable.SetFurnitureInfo (BuildingSystem+FurnitureInfo info, FurnitureManager furnitureManager) [0x00000] in <683983b93376494f9be71bde371c38c6>:0 
  at FurniturePlaceable.Start () [0x0000e] in <683983b93376494f9be71bde371c38c6>:0 
```

**Comment by Oskutin** [comment]
Build only issue? Or fixed already by other fix?

**Comment by Nextej** [comment]
Could be caused by some performance/saving issues? In that session the OS was very demanding and started to become laggy, which made me make the save and restart the game.

**Comment by Nextej** [comment]
Not replicable, crash log from that previous session
[Crash_2023-12-17_161711196.zip](https://github.com/loiste-interactive/Obenseuer-Issues/files/13702042/Crash_2023-12-17_161711196.zip)

**Comment by Nextej** [comment]
Managed to repeat one of the issues related to this on new character, after loading a player-made save, player-placed furniture was doubled. Seems to happen on every reload, duplication issue. Place furniture/items using building mode -> reload the level -> see two furnitures/items stacked

**Comment by Oskutin** [comment]
Does this still happen?

**Comment by Nextej** [comment]
No, seems to be fixed.
