### ISSUE TITLE
Playtesting - Cleaning mode notifications are tripled when triggered.

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#1484]

**Comment by Nextej** [comment]
Seems to happen only for the first time the playerment is loaded? Surely after restarting the game and loading a saved slot on playerment, it doesn't happen.

**Comment by Zuntti** [comment]
I think this happens because some of them gives multiple items?

**Comment by Zuntti** [comment]
Changed notification to show "Item name (amount)" instead of multiple notifications

**Comment by Nextej** [comment]
> I think this happens because some of them gives multiple items?

it's from taking loose items, like empty bottles, etc. the notification is shown three times, for furniture that gives multiple amounts, the total is also tripled
