### ISSUE TITLE
Playtesting - Some misplaced plywood in apartment 5 of playerment, adjust the position,

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#1486]
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/e54b1571-6038-48b6-b35a-9268b61690c4)

**Comment by Oskutin** [comment]
Umm, there is no plywood spawn at all.

**Comment by Nextej** [comment]
umm, I thought it was added to help new players craft the first wooden chest easier, perhaps there's some item that's get replaced by plywood then? I'll try to see if it is recreatable

**Comment by Oskutin** [comment]
Is it possible that inventory was full and dropped plywood there?

**Comment by Nextej** [comment]
did not perform any crafting, not sure if anything in the area of picked up furniture, yields plywood when cleaned

**Comment by Nextej** [comment]
invalid
