### ISSUE TITLE
Playtesting - selecting laptop as a furniture makes it fly towards you to collide and push you.

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#1489]
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/10b7c6d0-ad1c-4158-b5c1-0fce12473436)
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/2d4c8513-6427-45a8-8687-e603aa5cb1bb)

**Comment by Oskutin** [comment]
Fixed
