### ISSUE TITLE
Playtesting - Cleaning the apartment before starting renovation should be needed (only furniture, not loose items) besides examination.

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#1494]
- Perhaps add written with red marker check sign on the blueprint?
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/caa11f32-d2e8-4333-aae5-d46da8f90874)
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/057a80c3-6f04-4be4-9239-200fe740fc6e)

- perhaps have a certain percentange of cleaned apartment (95% of a total number of all furniture in the apartment) to exclude borderline cases  where player missed some paper sheet in a dark corner, that allows get cleaning state checked off.

**Comment by Zuntti** [comment]
Added
