### ISSUE TITLE
Invisible wall blocks basement staircase access

### ISSUE THREAD

**Issue by N-G-Neer** [loiste-interactive/Obenseuer-Issues#1496]
Following the "tenement-wide cleaning mode" update, I'm not longer able to walk downstairs to my basement, or upstairs from it.
Invisible wall from the basement
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/15633807/0524e5c5-d8c9-4ca3-8dbc-3cabbc37e4f9)
Invisible wall from upstairs has you floating on an invisible incline.
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/15633807/5c0a33ec-df66-4bb3-a343-5b7c1611a71e)

**Comment by Zuntti** [comment]
Fixed
