### ISSUE TITLE
0.3.23 Low Priority Bug - Collision box for shopping cart on Kolhola floor 3 throws player back on first time approach.

### ISSUE THREAD

**Issue by sashort** [loiste-interactive/Obenseuer-Issues#1506]
If the player approaches the shopping cart head on, they will quickly be thrown back. This has only happened the first time approaching it. The bug can be reproduced if you leave the building and come back in.

NOTE: I may have had sprit engaged by pressing SHIFT before each instance of the bug. This may or may not be a contributing factor.

**Comment by Oskutin** [comment]
fixed
