### ISSUE TITLE
0.3.23 Visual/Environment Bug - Looking at opened dentist's door displays as closed/locked door.

### ISSUE THREAD

**Issue by sashort** [loiste-interactive/Obenseuer-Issues#1508]
1. Lock pick the door between the dentist's office and their apartment (in between the 2 rooms.)
2. Look at the door.
<img width="963" alt="Bug Dentist Lockpick Open Door" src="https://github.com/loiste-interactive/Obenseuer-Issues/assets/95879519/74873f0f-e6e8-4eb8-8e10-d7bd272a4d82">

**Comment by uranimegf** [comment]
Here to add on to this, the first door seems to display as opened or locked depending on where you look at it, regardless of that second apartment door. I also lockpicked the door from the outside a second time and the same issue occured. 

https://github.com/loiste-interactive/Obenseuer-Issues/assets/131580872/de5c8a2f-6f37-464e-bd55-eef7c68bad7f

**Comment by Nextej** [comment]
Regarding second issue, similar thing happens to the padlocked doors to the penthouse in deekula C

**Comment by Oskutin** [comment]
> Regarding second issue, similar thing happens to the padlocked doors to the penthouse in deekula C

what doors exactly?

**Comment by Oskutin** [comment]
fixed
