### ISSUE TITLE
0.3.23 Visual/Environment Bug - Shelf on 1st floor of player Tenement clips through duct

### ISSUE THREAD

**Issue by sashort** [loiste-interactive/Obenseuer-Issues#1509]
Somewhere in the process of making upgrades to my tenement, a vertical duct appears in the corner of the 1st floor. It clips through the shelf beside it.
<img width="962" alt="Bug Shelf clipped through" src="https://github.com/loiste-interactive/Obenseuer-Issues/assets/95879519/47b4e071-88b6-429c-a7da-73cedfafe194">

Here's the current state of my tenement. I've encircled what I believe factors contributing to the bug in red.
<img width="961" alt="TenementState" src="https://github.com/loiste-interactive/Obenseuer-Issues/assets/95879519/50467cf1-6a91-4a51-bb75-b98990aa7e54">
2 important questions for debug:

1. When does the shelf get added (I think it appeared after the upgrade to Stairwell II)
2. When does the duct get added (I don't remember seeing it before my Water III upgrade, maybe Water II)

**Comment by Zuntti** [comment]
Fixed
