### ISSUE TITLE
0.3.23 Game mechanic bug - Arrest causes you to sleep before entering cell. Leads to moldy food that covers other items on inmate tray.

### ISSUE THREAD

**Issue by sashort** [loiste-interactive/Obenseuer-Issues#1513]
I've been arrested numerous times. Each time in 0.3.23 I sleep before waking up in the cell. Every time at least one of the perishable foods has turned into mold. I feel like this fails a regression test. I think everything in 0.3.22 related to imprisonment worked fine.

While mentioning being incarcerated: Is there/can a waste bin be placed in the prison? I usually am arrested with a full inventory, and I'd like to keep the items the nice policeman has provided for me. I can discard some useless stuff I collected earlier. It doesn't feel right tossing my garbage in the locker and walking off. Maybe I've missed a trash can or something?

**Comment by Oskutin** [comment]
fixed
