### ISSUE TITLE
Arrest While Entering Building 03.23

### ISSUE THREAD

**Issue by million-town** [loiste-interactive/Obenseuer-Issues#1515]
If you are arrested the same time you enter a building, you load into the new map thinking you are arrested. Your health almost immediately drops to nothing and you die from starvation or thirst. You cannot eat or drink enough to survive as the health drops within a couple seconds. No way around it as if you load the autosave, the save state is the same and you just die. You have to load an older save. Has happened to me at least twice.

Reloading the autosave, the time is incredibly accelerated like you were sleeping in the jail when first arrested, but you're in the building you entered.

**Comment by Oskutin** [comment]
fixed
