### ISSUE TITLE
0.3.23 Minor Bug - Liouba Bennet called Fenella Hunt when interacting with her

### ISSUE THREAD

**Issue by uranimegf** [loiste-interactive/Obenseuer-Issues#1518]
Such a trivial issue but I don't think anyone else has noticed yet: when speaking to Liouba Bennet in the Telemarketing Company Office in Kolhola, her name displays as Fenella Hunt:

![20231219182712_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/131580872/5d09adf8-866d-4432-8287-7ad9a4770a8b)
![20231219182719_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/131580872/39b418e0-de2c-4148-b354-91e8102ee629)

**Comment by Zuntti** [comment]
Fixed
