### ISSUE TITLE
Playtesting - Furniture vendors are broken

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#1522]
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/a77e7956-0c9b-45f7-a434-6957538d731a)

**Comment by Nextej** [comment]
Other furniture vendors are broken as well.

**Comment by Oskutin** [comment]
Them being dark or something else?

**Comment by Nextej** [comment]
broken furniture list, can't switch categories, placeholder name and image and price
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/117bc0a8-ee58-4019-8f39-be07abdbd23b)

**Comment by Zuntti** [comment]
Fixed
