### ISSUE TITLE
Tenants are back on the street (again).

### ISSUE THREAD

**Issue by Ludvig11** [loiste-interactive/Obenseuer-Issues#1526]
![20231219205256_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/31344357/ea3ce677-32a5-4774-90b6-10997da7492c)
![20231219204704_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/31344357/c42774d9-443a-477c-b21f-702b02769a82)
![20231219204638_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/31344357/b9dba327-014f-4fcc-9200-62752520e2ea)
![20231219204620_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/31344357/5b502447-5012-4a1a-a48a-76e126469e73)
[Speakeasy, Tenants_Lumi_Pakkanen.zip](https://github.com/loiste-interactive/Obenseuer-Issues/files/13720027/Speakeasy.Tenants_Lumi_Pakkanen.zip)

**Comment by Zuntti** [comment]
Fixed Speakeasy
