### ISSUE TITLE
Playtesting - ATM booth uses Mailbox icon on a map, also when suggesting it, I rather thought that roadmap icons would fit mail and phone more as a public utilities.

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#1528]
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/70d49288-042e-4f77-96b0-345ccff7820c)
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/a93988d3-e224-41f2-ba79-6adeb380f62e)
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/2bdd5ab8-1f41-4759-9284-8f5cf69dff6c)
perhaps hostel should get similar one too

**Comment by Zuntti** [comment]
Changed
