### ISSUE TITLE
Few minor intro interview issues

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#153]
1. One of the options of seeing "Black hallusinations" should've spell hallucinations.
2. After ending the interview, the monitor noise can still be heard.

**Comment by Zuntti** [comment]
Fixed hallucinations spell mistake. Noise sound comes from the radio

**Comment by KETALss** [comment]
once interview is almost done, pressing [E] instead of [continue] will result in a chat loop
