### ISSUE TITLE
Inconsistencies in Task Descriptions

### ISSUE THREAD

**Issue by uranimegf** [loiste-interactive/Obenseuer-Issues#1530]
Completely trivial submission, but I've noticed that the task descriptions swap between using 'you' and 'I/me' when describing the player. I just thought I'd make this known, as I personally think that the tasks section could feel more 'polished' if it was more consistent. But yeah! Not very important haha

![20231220204707_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/131580872/0320dbd0-3f4f-4108-b7c2-0efcc9a4c9fa)
![20231220204705_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/131580872/71efa16b-166b-420c-aac5-362e30d8b568)

**Comment by Zuntti** [comment]
Fixed
