### ISSUE TITLE
Saving and loading a game if you have taken doctor's ticket doesn't allow you to enter doctors place.

### ISSUE THREAD

**Issue by Oskutin** [loiste-interactive/Obenseuer-Issues#1531]
![kuva](https://github.com/loiste-interactive/Obenseuer-Issues/assets/5402150/2db585d8-326d-4b2a-a5f6-2117955ff5d0)

**Comment by Zuntti** [comment]
Doesn't seem to happen for me

**Comment by Zuntti** [comment]
Fixed
