### ISSUE TITLE
Playtesting - loading a save with playerment (also for map transitions), tends to crash more often

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#1533]
[Crash_2023-12-20_122910982.zip](https://github.com/loiste-interactive/Obenseuer-Issues/files/13727326/Crash_2023-12-20_122910982.zip)

Could be even that loading playerment for the second time in a game session (not per slot), crashes it

**Comment by Zuntti** [comment]
Fixed
