### ISSUE TITLE
Playtesting - Stats during telemarketing job should be satisfied to a degree

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#1536]
1. Bowel and Bladder satisfied on their own, office has a toilet
2. If player has any food, it should be eaten above certain percentage (perhaps show how exhausting the job is in nutrients?)
3. same for water
4. addiction needs should be satisfied if player both has any of the drugs in the inventory and the need went already over 100%

**Comment by Nextej** [comment]
Player should also get a notification (top left) and an associated sound when respective item (food, water, drug) is consumed, perhaps also show it on a summary screen #1731

**Comment by Oskutin** [comment]
Now toilet and thirst are satisfied
