### ISSUE TITLE
0.3.23 - I broke into Pizza Guy's house and he doesn't want to talk to me so I sat on him

### ISSUE THREAD

**Issue by uranimegf** [loiste-interactive/Obenseuer-Issues#1537]
I lockpicked my way into Sam Morton's house and when I tried interacting with him my screen would just centre onto him with no dialogue appearing. I was also able to sit on his chair with him still in it.
I haven't delivered him a pizza through the door yet so I'm not sure if that has something to do with it or not.
I remember someone else mentioning a similar issue of being able to sit in an occupied chair but I can't remember details, so I apologise if this has already been brought up.

![20231220235128_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/131580872/47a5577f-4811-4e0d-b707-3de63737b594)
![20231220235131_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/131580872/07f50195-37a0-4abb-94b6-c1fcf00de3c3)
![20231220235137_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/131580872/2ee85c1a-8c8a-461c-b5ce-f2fe65ba4455)

**Comment by Oskutin** [comment]
Already fixed
