### ISSUE TITLE
GUI change request - Tenement Heat and Water upgrades

### ISSUE THREAD

**Issue by sashort** [loiste-interactive/Obenseuer-Issues#1538]
### Make all the upgrades that are for an individual apartment lowercase Roman numerals. ###
I've noticed that after doing many upgrades, attempting to move Kiara Hääbus in from Hostel Warehom, I've misinterpreted the symbols for Tenement and Apartment Heating/Water. I know the tool tips tell you what they are, maybe I'm just stupid.

I realize, after stopping and thinking about it, the tooltip spells out what each requirement is.
Requirements for tenement upgrades have a red background too.
Despite these, I still managed to screw up.
I feel I won't be the only person to make this mistake.

**Comment by Oskutin** [comment]
There are already UI changes in the upcoming

**Comment by sashort** [comment]
Awesome, how can I access the most recent betas. I hate posting bug reports for things that have already been fixed.
