### ISSUE TITLE
0.3.23 - Minor Bug - Jörge Af Guldskjöld called Fenella Hunt during interaction with him

### ISSUE THREAD

**Issue by uranimegf** [loiste-interactive/Obenseuer-Issues#1539]
![20231221152302_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/131580872/64539e1b-48d7-42e8-b185-5dd05176a78c)
![20231221152309_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/131580872/cf0243b8-640b-4ff5-9189-9f0af560fdb3)

**Comment by Zuntti** [comment]
Fixed
