### ISSUE TITLE
Playtesting - all furnitures are broken, taking a furniture up, reloading and trying to place it down show that the furniture is not present on building mode list

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#1540]
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/83f9c50e-4ae1-4ca6-becd-6046c46eb278)
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/235b83b2-9444-4a8e-a8a6-93f173570c2f)
only two furnitures

new character

**Comment by Zuntti** [comment]
Fixed
