### ISSUE TITLE
Playtesting - Lighting issues at Deekula A floor level

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#1542]
before entering Samuel's
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/2991f14b-ebd4-4150-be86-ccb7005ce19c)
after
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/fc6ebc32-fc15-444d-ae19-84f9b9985d87)

**Comment by Zuntti** [comment]
Fixed
