### ISSUE TITLE
Playtesting - Morning sun is now supernova

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#1548]
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/4397e8b1-fd50-4d10-a985-2c87980f0175)

**Comment by sashort** [comment]
In addition, and related to this bug, it appears there is a halo layer around the sun.

The halo effect appears through any objects that are between you and the sun.
Look at your tenement before the sun rises over it, you can see the haze in front of the building.

**Comment by Zuntti** [comment]
Fixed
