### ISSUE TITLE
Playtesting - requirement to clean apartments before renovations is broken

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#1556]
At first it's not even there, both on save from 0.3.26.v2 and on new character from 0.3.26.v3, then after a while, randomly one of the apartments gotten checked as uncleared, only this one
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/e6ae2dc7-e15c-409e-b0c4-0af988b80c4b)

**Comment by Zuntti** [comment]
It seems to work for me

**Comment by Zuntti** [comment]
Can I get a save where this happens? I tried to get this with a new character but it seemed to work always

**Comment by Nextej** [comment]
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/99bedc9c-b332-4409-9061-38463ad2ff0b)
newly created character, apartment 8 is ready for renovation after examination without cleaning, load autosave or slot 1 (after examination)
[Alex_Malmberg.zip](https://github.com/loiste-interactive/Obenseuer-Issues/files/13750877/Alex_Malmberg.zip)

**Comment by Zuntti** [comment]
Weird. It worked with this character for me. Slot1 is before entering the tenement and slot2 is with examined apartments
[Osmo_Thunstrom.zip](https://github.com/loiste-interactive/Obenseuer-Issues/files/13750925/Osmo_Thunstrom.zip)

**Comment by Zuntti** [comment]
And also Alex is working if you load save twice

**Comment by Nextej** [comment]
On Osmo Thunstrom it worked only if I first loaded slot2 and then slot1, if I first loaded slot1 and did the examination, it's not requiring cleaning

**Comment by Zuntti** [comment]
Yeah I think it can happen again only if you restart the game?

**Comment by Nextej** [comment]
Seems to happen only the first time you load the save

**Comment by Zuntti** [comment]
Fixed
