### ISSUE TITLE
Playtest - 0.3.26 V3 shabby bed uncraftable

### ISSUE THREAD

**Issue by pinkamedic** [loiste-interactive/Obenseuer-Issues#1558]
![Screenshot 2023-12-21 152243](https://github.com/loiste-interactive/Obenseuer-Issues/assets/151697489/3766c8dc-5d8e-46b5-a563-ef4abceceae5)
it also shows that i need 2 mattresses for some reason

**Comment by Oskutin** [comment]
what makes it uncraftable?

**Comment by Oskutin** [comment]
Fixed the recipe
