### ISSUE TITLE
Hacker's Den pad

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#156]
Spamming random key after pressing the last button to confirm the combination doesn't close the window. The doors get unlocked and you close the windows with ESC anyway.
https://user-images.githubusercontent.com/44178400/235455659-120a341e-07fb-479b-a2ca-3b836b02a967.mp4

"#" and "*" do nothing, not sure why they are even there, but it would be nice to have a reset button for if we type a wrong combination before confirming it. Also I guess it would make sense that if 3 wrong combinations in a row would cause an alarm.

Additionally the Doors have a slight gap on its right side.
![image](https://user-images.githubusercontent.com/44178400/235455640-d00249f4-f558-4599-a3ec-041a1f554f67.png)

**Comment by Oskutin** [comment]
Doesn't seem to happen anymore
