### ISSUE TITLE
Playtest - 0.3.26 V3 two versions of bathtub with soil and supports

### ISSUE THREAD

**Issue by pinkamedic** [loiste-interactive/Obenseuer-Issues#1560]
![Screenshot 2023-12-21 183702](https://github.com/loiste-interactive/Obenseuer-Issues/assets/151697489/befe11cd-0122-47f6-a174-5b24ae0e908e)
![Screenshot 2023-12-21 183708](https://github.com/loiste-interactive/Obenseuer-Issues/assets/151697489/fb76b039-3f31-44cf-82b9-af67f117e07d)
from what i can tell one is ment to be the normal bathtub with soil rather then the one with supports

**Comment by Zuntti** [comment]
Fixed
