### ISSUE TITLE
0.3.23 Bug - Sitting on Fidan Tanner's chair when he is already on it

### ISSUE THREAD

**Issue by uranimegf** [loiste-interactive/Obenseuer-Issues#1562]
I'm also stuck here now as his character interaction is taking up my whole screen.
![20231222174727_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/131580872/e0f076e1-9770-4d9c-800e-633fc8e40800)

**Comment by uranimegf** [comment]
Just thought I should mention - reloading my last autosave made me unable to sit on chairs entirely, even outside of that house Fidan is in, however closing the game and opening the save again fixed it.
![20231222175052_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/131580872/8b5e552c-4a2a-4bed-9a60-409985d95485)

**Comment by Zuntti** [comment]
Already fixed
