### ISSUE TITLE
Opening area loading doors while sitting locks you in a permanent sitting state 

### ISSUE THREAD

**Issue by ImNotThatBrave** [loiste-interactive/Obenseuer-Issues#1564]
encountered mainly in sauna, might be possible elsewhere?

tldr: sitting on the bench within the sauna then activating the level load door to the outside (while seated) locks you in a sitting state that (seems to?) effect other saves of that character.

The effect on other saves is to make your character permanently considered "sitting" as seen here
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/40413120/438eb6a9-4ee1-45d7-ad60-8be47169df6e)

Debug chatter filled with null references
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/40413120/1c4f1a79-c32d-4b9f-8911-bcca79bb3199)

**Comment by ImNotThatBrave** [comment]
I should add that this specific instance was a slightly different variation (I simply loaded a save after sitting in the sauna) and triggered the save state seated status weirdness

**Comment by Oskutin** [comment]
Already fixed in upcoming
