### ISSUE TITLE
Fish Breeding and Mushroom Farming issues

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#157]
Taking a fully grown fish from the aquarium doesn't add it to our inventory, instead it disappears, neither does at any state. How are you even supposed to bread more fish? Additionally I think it should return you something that can start the breeding from the start and do only that, instead of always loosing the item that was breading when it's not grown.

To start farming shrooms, they all need a Moist modifier which neither of the available farms has, they however have a Sun modifier, in a closed dark compartment.
![image](https://user-images.githubusercontent.com/44178400/235457505-a42e2c22-8b51-4ea7-90f2-dc8532d23c07.png)
Again the problem of loosing any progress when the shrooms are taken accidentally too early as above, there should be an item given that starts the growth process from the start.
After reloading a save the farm's UI was not useable and did not show any information about the status of the shrooms, possibly fixed by other Savefile fixes.
When gathering the shrooms, we can do it only "in-the-world" and can't so from the UI, additionally it seems that a grown state has different visual sizes, while it doesn't correspond anyhow to the amount of shrooms we're actually getting from the harvest (seems like we can get 1-2 shrooms at random); visually smaller shrooms should be the ones giving a smaller number and visually bigger should be the ones giving larger number.
![image](https://user-images.githubusercontent.com/44178400/235459026-11d39b6c-c259-49a4-bfcd-d7f44726bec6.png)
Lastly when previewing the recipe for farming, the game only states it is a 1:1 exchange from bags of shrooms to just shrooms, while in reality there's a change of several shrooms to get from it, it should be made clearer. Also the shroom hurt area seems to be a bit too big, leading to a much of an unnecessary health loss.

**Comment by Oskutin** [comment]
Changed correct modifiers to the boxes

**Comment by Oskutin** [comment]
Fish multiply now.

**Comment by Oskutin** [comment]
Now fish gives yield
