### ISSUE TITLE
broken/stuffed chemlab  1/1 queue

### ISSUE THREAD

**Issue by greensalt99** [loiste-interactive/Obenseuer-Issues#1570]
Deekula A Chemlab (Chemstation) . i was crafting clean water, lots of it. used stack of plastic bottles with water.
i was clicking craft item, maybe to fast.
 at one point there was -2empty_placstic_bottles. i have dropped 2 empty bottles on those -2 and it disappeared. 
station showed that in that empty square of current crafting item was something blue, like water i guess.
i have left room, reloaded. now station says that crafting_queue is 1/1 full. cant craft anymore :'(

**Comment by greensalt99** [comment]
[Slot7.zip](https://github.com/loiste-interactive/Obenseuer-Issues/files/13753956/Slot7.zip)
i have noticed new version dropped. checked on new version, same issue.

**Comment by Oskutin** [comment]
Fixed
