### ISSUE TITLE
Building System Bugs

### ISSUE THREAD

**Issue by sashort** [loiste-interactive/Obenseuer-Issues#1573]
As of the most recent update (12 Dec 2023, 4:30 EST) I've found the following bugs, some of which have already ben mentioned:

1. Building menu ~~does not engage~~ cannot be engaged when you enter the tenement from outside (basement or lobby door.) Appears to engage correctly in all other cases (moving to different room/stairwell, loading into occupied/unoccupied apartment). Have not tested on evicting and canceling/moving in new tenet.
This streamer found the bug and didn't realize it. The time markers are from 9:10 - 9:57
https://youtu.be/O_x577Xe7kc?si=m3BLCDJrgl2kzKRJ

The only way to enable the build menu from this invalid state is to walk into your apartment, the basement (that already had build functionality, and possibly cleaned apartments [cleaning is still buggy...hard to test if this is true].)

3. Key binding of E is used in both build menu and as interact. E should be interact when build menu is engaged and you are looking at a door. I was walking around and had to go through tarps/doors. I had to disengage the build menu, open the door, then reengage build mode (in the basement.) More generically, interact should override any build menu key binding if they key bindings are the same.

4. Noise for engaging build mode should be removed when:
- player has build mode engaged
- player is moving to another apartment/stairwell
- destination apartment/stairwell allows build mode

5.  In Apartment 14,  you cannot remove the firewood basket, nor the wooden crate. 
**After reloading save, I managed to clear the apt and reach 100%. These items are still present in the apartment**

6. Cleaning progress mechanic is broken. ~~I've only been able to test on apartment 14. Progress went up to 25% after everything was cleared. After saving and reloading, progress was at 0%.~~ It appears cleaning progress is not retained if you leave the tenement, or if you save and reload that save.

**Comment by Orphiex** [comment]
Minor update: The "Cleanliness" state of the actual apartment is retained in the game; however, the "Tenement" menu shows "0% cleaned" after leaving the apartment, irrespective of the actual condition. A fully cleaned apartment can be renovated even if the menu shows "0% Cleaned".

**Comment by Zuntti** [comment]
Fixed 1, 5 and 6
