### ISSUE TITLE
Incomplete Tenement Basement Utility Glyph Update: Some circles on construction tab should be the [new] octagons

### ISSUE THREAD

**Issue by sashort** [loiste-interactive/Obenseuer-Issues#1576]
A picture is worth a thousand words.
Here are the glyphs that need to be converted to octagons in the construction tab.

I pasted screenshots into Paint. Ignore the other screenshot hidden underneath at the top of each image.

<img width="1281" alt="IncompleteGlyphMigration1" src="https://github.com/loiste-interactive/Obenseuer-Issues/assets/95879519/bda0427b-7d3f-4ac8-a99e-cb1bbc0882a9">

<img width="1281" alt="IncompleteGlyphMigration2" src="https://github.com/loiste-interactive/Obenseuer-Issues/assets/95879519/258eef3e-f99e-402c-85ee-63aee3c655af">

<img width="1280" alt="IncompleteGlyphMigration3" src="https://github.com/loiste-interactive/Obenseuer-Issues/assets/95879519/86dc49ed-3ada-4709-825c-5fea8bf81420">

**Comment by Zuntti** [comment]
Fixed
