### ISSUE TITLE
Version 0.3.27 - o-mart matches and glue not being sold as full

### ISSUE THREAD

**Issue by pinkamedic** [loiste-interactive/Obenseuer-Issues#1580]
![Screenshot 2023-12-23 071005](https://github.com/loiste-interactive/Obenseuer-Issues/assets/151697489/cbd635cf-a754-4119-bc9d-48fda3392ed8)
![Screenshot 2023-12-23 071016](https://github.com/loiste-interactive/Obenseuer-Issues/assets/151697489/d198d3dc-8a02-4e9d-aa5e-f1a0886af3fb)
i saw the fix of cigs not being full then i noticed this

**Comment by pinkamedic** [comment]
to add onto this the cleaning spray is also not full

**Comment by Zuntti** [comment]
Fixed
