### ISSUE TITLE
Shop Money still not replenishing on 0.3.27

### ISSUE THREAD

**Issue by million-town** [loiste-interactive/Obenseuer-Issues#1583]
Shops (hardware, OSS) for me are still not replenishing their money daily on 0.3.27. They only get OC if I buy something. been at least two weeks in-game.

**Comment by CVariable** [comment]
It works for me. Is that on a migrated save?

**Comment by Zuntti** [comment]
Can I get a save where this happens?

**Comment by million-town** [comment]
It is a migrated save. It's not really holding me back right now, I'm going to keep playing this save as long as I can then maybe start a new one with later updates. 
[John_Lindgren.zip](https://github.com/loiste-interactive/Obenseuer-Issues/files/13791020/John_Lindgren.zip)

**Comment by Zuntti** [comment]
Fixed
