### ISSUE TITLE
Steam Achievement Issues

### ISSUE THREAD

**Issue by sashort** [loiste-interactive/Obenseuer-Issues#1587]
### Lively Tenement Achievement ###
I managed to move in all tenants (unless there is a place you can rent on the roof.)
I've been working towards this goal for the past week in December, hoping to be one of the first to get this goal.
I did not receive the achievement.
I'm not sure if: this is a bug, I don't understand the achievement, or the achievement hasn't been developed yet. 
Is it because we can't access the other ground floor apartment yet?
- I haven't made a single upgrade to my own apartment. Don't even have a tarp on my stairwell door.
- Final tenant moved in while I was sleeping.
- I had to play using version 3.23. The cleaning mechanic hasn't been fully debugged and may have prevented me from moving in any further tenants. 3.24+ would've have only added about another 2 hours of gameplay if I were playing with most recent (only had to clear the top floor, and cleaning an apartment doesn't take long, especially when you have tons of cleaning supplies at hand.)
- I have not explored the roof.
[Slot10.zip](https://github.com/loiste-interactive/Obenseuer-Issues/files/13763016/Slot10.zip)

### All Works Achievement ### 
- I upgraded directly to Water/Heat/Electricity 3, or at least skipped level 1 for everything.
- Unlike other achievements, there is only `All Works`
- It felt awkward completing my final utility at level 3 and receiving `All Works` when I completely bypassed all level 1 and 2 utilities.

Solution:
- Add an achievement for Upgrading all utilities to level 2 and 3. This would match `Shabby Apartments` and `Fine Apartments`
- OR Reword `All Works` description to "Upgrade all `tenement/basement` utilities to `at least` level 1

**Comment by Zuntti** [comment]
Fixed
