### ISSUE TITLE
Move-In Bugs in Tenement Tab

### ISSUE THREAD

**Issue by sashort** [loiste-interactive/Obenseuer-Issues#1589]
If you have the tenement tab open < 1hr before new resident is moving in, the Evict button incorrectly shows "Moving: `0s`"
<img width="1278" alt="MoveBug01" src="https://github.com/loiste-interactive/Obenseuer-Issues/assets/95879519/7827277b-dc1d-4c05-a031-1da560d4415d">

If a resident moves in while the tenement tab is open, the Income fields do not update and remain at 0 OC and 0 RM
<img width="1282" alt="MoveBug02" src="https://github.com/loiste-interactive/Obenseuer-Issues/assets/95879519/48be57b8-bab7-40ab-af35-15eb30a83af1">

**Comment by Zuntti** [comment]
Fixed
