### ISSUE TITLE
Public - reloading seems to cause cleanining state to lock to 0% of apartments, even cleaned ones.

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#1592]

**Comment by Nextej** [comment]
[Player.zip](https://github.com/loiste-interactive/Obenseuer-Issues/files/13766138/Player.zip)

**Comment by Zuntti** [comment]
Looks like the counter resets to 0 when you go out

**Comment by Zuntti** [comment]
Fixed

**Comment by Zuntti** [comment]
It should not happen if apartment is 100% cleaned but if there's still something left it resets it back to 0%
