### ISSUE TITLE
Bug - Manufacturing Equipment polymorphism problems

### ISSUE THREAD

**Issue by sashort** [loiste-interactive/Obenseuer-Issues#1596]
It appears as if all the manufacturing equipment has a shared super class. That makes sense.

Bug 1: list of craftable items in manufacturing equipment will disappear under the following conditions:
1. You are interacting with any piece of manufacturing equipment
2. You have a crafting recipe selected
3. Any manufacturing equipment finishes crafting (different or same type, equipment you are interacting with or another piece of equip)

Example: I am interacting with the `Gas Furnace` and have a `Steel Bar` crafting recipe selected.
This list of craftable items for the `Gas Furnace` disappears, while I am still interacting with it, when my `Lathe` has finished crafting `Mechanical Parts`. The recipe for `Steel Bar` persists on the `Gas Furnace` interact dialog.

I have experienced this bug with other combinations of manufacturing equipment with the same bug.

Bug 2: Invalid visual on/off state interacting with equipment:
repeatable test (sometimes) with `Gas Furnace` and `Band Saw`
`Gas Furnace` and `Lathe`
(other combinations might exist)

PRECONDITION: reproduce bug 1. Do not reload the game.
1. Interact with either. 
2. Interact with the other piece of equipment.)
Bug: The on/off state visually matches the state of the first piece of equipment you interact with.

WORKAROUND: Interact with a piece of equipment twice (press `E` 3 times)

![20231226125917_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/95879519/933e235b-8bfd-4f78-be7c-8b2473fc533a)
Interacted with Lathe that was crafting mechanical parts first.
Note: Bug 1: List of craftable items has disappeared, but recipe for Steel bar is still visible.
Bug 2: Visually appears as `ON` in dialog (orange flame icon,) but there is no orange background light.

**Comment by Zuntti** [comment]
Fixed
