### ISSUE TITLE
0.3.27 - Police Tape at Deekula B3 (Radio Bathtub Apartment) does not despawn

### ISSUE THREAD

**Issue by CVariable** [loiste-interactive/Obenseuer-Issues#1598]
After more than 1 week in game, the tape has still not disappeared from the door.
This save was made in 0.3.27, so it is not migrated.
![grafik](https://github.com/loiste-interactive/Obenseuer-Issues/assets/45665371/c4cf3a2e-d7dd-4caf-ab47-d9080aab0940)

**Comment by Zuntti** [comment]
Fixed
