### ISSUE TITLE
All my tenement's storage chests etc ended up empty

### ISSUE THREAD

**Issue by Ludvig11** [loiste-interactive/Obenseuer-Issues#1599]
[Storage-chests_empty_ Lumi_Pakkanen.zip](https://github.com/loiste-interactive/Obenseuer-Issues/files/13773417/Storage-chests_empty_.Lumi_Pakkanen.zip)
![20231226012829_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/31344357/08a7dd8b-10dd-4858-8e6c-fbd6967b57e4)
![20231226193513_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/31344357/d2a3330c-bcfc-46a4-8cae-7e1139e8bcc0)

Possibly happened after spending time in jail, where the police had a ludicrously high bounty on me after stealing some abandoned pea soup(?):
![20231222224958_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/31344357/f3ba5374-825a-4217-a187-f579b521a83d)

**Comment by Oskutin** [comment]
Migrated save?
