### ISSUE TITLE
Green borderline seen on upgrade preview (that indicates the upgrade is installed) might be confusing (from my own experience) whether it's installed or available to renovate

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#1601]
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/742c76c9-431c-4179-9f84-10376aed590a)
potential ideas:

1. Make the outline a different color, neutral to green-red indication, golden perhaps could work
2. Add a label "Current"/"Currently Installed"/"Current Upgrade"/"Current Level" to the top left side of the borderline
3. When player attemps to upgrade to a currently installed level, display pop-up prompt "Already instealled" or something along the line.

**Comment by sashort** [comment]
To make it visually intuitive, why not make the background of the upgrade header have a light grey background to indicate the current upgrade.... For this demo image, I used #464646 as the background. I'm not sure about accessibility, but it looks like good contra
<img width="1280" alt="Suggestion" src="https://github.com/loiste-interactive/Obenseuer-Issues/assets/95879519/cef86851-f5bd-4f5f-b6b0-eab0d85b47fe">
st.

**Comment by Nextej** [comment]
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/41d54618-755e-457d-86e2-91f45d9755ce)
alternatively something like that, with added labels

**Comment by Zuntti** [comment]
Changed color and added status labels
