### ISSUE TITLE
Jompe Kurahaara wont buy  Cabbage 

### ISSUE THREAD

**Issue by greensalt99** [loiste-interactive/Obenseuer-Issues#1602]
Jompe Kurahaara  does not buy/take/pay for Cabbage. He gives seeds of Cabbage (Chest behind him). Might be forgotten to add into Jompe buy/take/pay for list. Cabbage grows supper long, i guess farming is not balanced and plants will be reworked in later builds.

**Comment by Zuntti** [comment]
Already fixed
