### ISSUE TITLE
Playtesting - player has to collect literally everything in the apartment to get it cleaned

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#1604]
Apartment is fully cleaned but this one last object to pick up
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/210be244-021b-4e15-b023-db781e72a593)
yet it shows it's only 80% cleaned, meaning that this one object takes 20% of the cleaning state
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/3c1fe58c-3144-4953-8edf-923deae3b125)
additionally it doesn't allow for user-end error of borderline cases of one missed can or paper sheet in a dark corner, aka, the 90% threshold doesn't work

**Comment by Nextej** [comment]
oh wait, actually no, I cleared everything and I'm stuck at 81%
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/e999b51f-835c-4157-8b61-f556a8069136)

**Comment by Nextej** [comment]
Seems to concern apartment 3 so far

**Comment by Zuntti** [comment]
It seems that some trash in apartment 4 are marked as apartment 3 trash

**Comment by Zuntti** [comment]
Fixed
