### ISSUE TITLE
Inventory sorting duplicates liquids

### ISSUE THREAD

**Issue by virusek20** [loiste-interactive/Obenseuer-Issues#1613]
## Description
Sorting liquid containers in the inventory can create invalid items that duplicate liquids on stack merge.

## Current behaviour
Sorting multiple stacks of filled / empty containers creates "filled" containers with 0l of liquid.

## Expected behaviour
Sorting liquid containers merges only those with same liquid + container type.

## Video
https://virusek20.kuub.io/2023-12/Obenseuer_2023-12-29_02-04-20.mp4

## Repro steps
These steps are the same as in the video
1) Aquire the following items: 1 stack + 1 empty containers, 1 container filled with liquid (all of the same container type)
2) Sort inventory
3) Merge original container with liquid with a newly created "empty" container with liquid

**Comment by Oskutin** [comment]
Seems to only happen with mason jars

**Comment by Oskutin** [comment]
seems to work now
