### ISSUE TITLE
Not sure if an issue or a feature?

### ISSUE THREAD

**Issue by TiaLinna** [loiste-interactive/Obenseuer-Issues#1616]
![20231229015627_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/130680276/227d7295-df6d-44b0-8d38-6f625f2a67b4)
![20231229021404_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/130680276/38dcb549-d11d-4df0-a736-4a5582ab558f)
So I spotted a Fridge and a drawer in the sky? I had to noclip to get a closer look and there it was. Could be a placeholer or something? No clue

**Comment by Zuntti** [comment]
Fixed
