### ISSUE TITLE
Version 0.3.28 - Mash making went into negatives on processing

### ISSUE THREAD

**Issue by pinkamedic** [loiste-interactive/Obenseuer-Issues#1622]
![Screenshot 2023-12-29 184723](https://github.com/loiste-interactive/Obenseuer-Issues/assets/151697489/37dba312-d3b5-403a-af55-04f8c2a3ad0e)
im not exactly sure how this happend but it did

**Comment by Oskutin** [comment]
You got save?

**Comment by pinkamedic** [comment]
i do not as the game crashed shortly after taking the picture and the lastest save was before i made the mash.
