### ISSUE TITLE
New Bug: Möblemann Furnitures store stays closed (door locked)

### ISSUE THREAD

**Issue by sashort** [loiste-interactive/Obenseuer-Issues#1624]
Möblemann Furnitures is currently inaccesible. I've checked 2 days in a row between the posted hours (8-18)
Both times the door has been closed and locked. Note: My save has been migrated from several game versions.
<img width="1280" alt="LockedOut" src="https://github.com/loiste-interactive/Obenseuer-Issues/assets/95879519/832baa46-01c0-42ab-abcb-9292c6a2e30b">

[Mark_Smith.zip](https://github.com/loiste-interactive/Obenseuer-Issues/files/13799905/Mark_Smith.zip)

**Comment by greensalt99** [comment]
dec 22 savefile  - furniture guy worked on time. havent checked all hours.
dec 29 update, using dec 22 savefile - furniture guy will not open on 8, 9, 10, 11 h Wednesday.
Working table times issue? (was open on Thursday, not sure when)
[Slot7.zip](https://github.com/loiste-interactive/Obenseuer-Issues/files/.13798163/Slot7.zip)

**Comment by greensalt99** [comment]
Thursday 12:55 furniture shop it is closed. Saved game, reloaded from Main Menu - furniture shop is open. 
not sure why it works, maybe it wont work correctly when you go into Dekula C.

**Comment by sashort** [comment]
I started a new game and entered Deekula C. I realized the door to the furniture store was the only one open when you enter for the first time.

With this knowledge:
I was able to pinpoint the GUID for the door.
I opened `Interior Tenement Deekula C.tnmt` on my migrated save and changed the key/pairs for GUID `0aef7805-2dd6-4962-b8de-aef81cc7a844`
`Key` `Value`
`"State"` `"Open"`
`"lockWhenClosed"` `false`

This allows me to get into the furniture store, but the store hours are not enforced. I have access 24/7.

After being able to enter, I noticed Hank was once again too far from the table, and is locker was locked.

Hope this info helps with debug.

**Comment by greensalt99** [comment]
sashort, have you tried 
Condition:
1. old save file
2. going to furniture shop working hours.
3. finding locked door.
4. saving near locked door, new save file.
5. reloading that save file. (Main meniu/ Runing game/ restarted game)
 after reload from Main meniu Furniture shop started working correctly, not sure if all hours work.

**Comment by sashort** [comment]
Yes, I followed the steps you provided. The workaround did not fix problem.
I tried it on both a new game and an older migrated save.

This solution did however fix my problems with the One Stop Shop a few days ago.

**Comment by greensalt99** [comment]
bug hunt continues ;D

**Comment by Oskutin** [comment]
seems to work now
