### ISSUE TITLE
Phantom turnip wine on item sort

### ISSUE THREAD

**Issue by DavidGraff** [loiste-interactive/Obenseuer-Issues#1627]
In my inventory I have a stack of 3 turnip wine jars, and a single empty jar. When I sort my inventory, the empty jar turns in to turnip wine with a volume of 0/1L.

![20231229230316_1_cropped](https://github.com/loiste-interactive/Obenseuer-Issues/assets/153752812/a53dced6-9681-4a16-a5d3-d522f68dcfb0)

**Comment by sashort** [comment]
I think you're experiencing the same bug as #1613
