### ISSUE TITLE
Reloading a savefile and/or traveling between maps seems to make some of the UIs of appliance unusable, might be already fixed by other savefile fixes.

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#163]
![image](https://user-images.githubusercontent.com/44178400/235698409-b323988b-834e-42e9-813d-5d1d7378ce6f.png)
![image](https://user-images.githubusercontent.com/44178400/235698447-adf548e0-f6c7-421b-aa0f-5d33c898a54e.png)
slots grayed out, similar thing happened once with shroom farms, storage units (including Fridge/Freezer and Fuse Socket) seem to work fine.

**Comment by Oskutin** [comment]
This should already be fixed
