### ISSUE TITLE
low priority. Pearl Ear Ring Jewelry - hitbox

### ISSUE THREAD

**Issue by greensalt99** [loiste-interactive/Obenseuer-Issues#1632]
Not sure how that jewelry is called. once you drop it, can not pick it up again. Either hitbox is supper small, or there is no hitbox. 
PearlEarRing.
Adding savefile. looking at it. 
[Slot6.zip](https://github.com/loiste-interactive/Obenseuer-Issues/files/13798141/Slot6.zip)

same issue on older and newest dec 29 version

**Comment by Oskutin** [comment]
Fixed
