### ISSUE TITLE
Enhancement - There should be some sort of fence / water gate Infront the bridge in the canal

### ISSUE THREAD

**Issue by pinkamedic** [loiste-interactive/Obenseuer-Issues#1636]
![Screenshot 2023-12-30 150638](https://github.com/loiste-interactive/Obenseuer-Issues/assets/151697489/710f5a33-15e3-46ec-864d-2f77a9cd52b2)
![Screenshot 2023-12-30 150651](https://github.com/loiste-interactive/Obenseuer-Issues/assets/151697489/61c4ae28-70cf-4431-af52-47ec15a5d59e)
with the area being a detention center theres a big flaw with the canal as theres just a straight shot out of it if someone takes a boat and goes under that bridge, maybe put a fence up like in the second picture Infront of the bridge

**Comment by Oskutin** [comment]
The quarantine zone has fences everywhere. that is just bridge in the main canal
