### ISSUE TITLE
Appliance modifiers need a better explanation in the UI.

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#164]
1. It's unknown what type of modifier it is (what aspect it affects), for instance, Sinks can have a modifier of Dirty and Clean, but the game in no way indicates it's the water quality, Clean modifier is found on Ovens and Kitchens and so on, surely it can't mean the Water is clean there too?
![image](https://user-images.githubusercontent.com/44178400/235700892-aa2402ef-7b57-436d-940a-691cce66c0bb.png)
2. Additional visual indication would be welcome, currently it has those question marks inside a star, after examining it for the first time, it would be nice if every modifier had its unique icon, for example a Clean (water) modifier has a blue star with a drop of water, Dirty (water) as same, but with brown color of the star, etc.

Any additional information is welcome, I for one am not sure what the hell does Crude modifier means on a Microwave Oven, a type of the modifier would already be helpful.

**Comment by Oskutin** [comment]
Planned for future already, hence closing this
