### ISSUE TITLE
Chemical lab should use terrarium, not aquarium, for the crafting recipe.

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#1645]

**Comment by Nextej** [comment]
It's confusing since you clearly see grown mushrooms in crafter lab

**Comment by Oskutin** [comment]
Oh sorry, misinterpreted the title

**Comment by Zuntti** [comment]
I think there should be a group that accepts several different furniture like barrels have their own group

**Comment by Zuntti** [comment]
Fixed
