### ISSUE TITLE
UI Bug - Missing Info on Upgrade Tooltip

### ISSUE THREAD

**Issue by sashort** [loiste-interactive/Obenseuer-Issues#1650]
Tooltip for upgrade in construction tab omits next update (in red)
word `Upgrade` should be lowercase
### Proposed Change ###
<img width="734" alt="MissingInfo" src="https://github.com/loiste-interactive/Obenseuer-Issues/assets/95879519/fe8943a8-2290-46e5-8ee5-2586c154eab2">

### Current ###
<img width="735" alt="Current" src="https://github.com/loiste-interactive/Obenseuer-Issues/assets/95879519/b4b5374a-a076-4b4c-99fc-dd822429fd64">

**Comment by Nextej** [comment]
You could just add a enhancement flair to it, oskutin, something like "In progress: <upgrade name>" would be welcome
