### ISSUE TITLE
0.3.28 - Steam Achievements Not Triggering ▒ ① Shabby Apartments | ② Decent Apartments | ③ Fine Apartments

### ISSUE THREAD

**Issue by sashort** [loiste-interactive/Obenseuer-Issues#1652]
- I've upgraded all my apartments to Level IV.
- Skipped Level I, Level II, and Level III
- Received `Makeshift Apartments`

- Did not receive `Shabby Apartments`
- Did not receive `Decent Apartments`
- Did not receive `Fine Apartments`

Note: The description of these achievements should be reworded as follows:
Makeshift Apartments - Upgrade all apartments to `at least` level 1
Shabby Apartments - Upgrade all apartments to `at least` level 2
Decent Apartments - Upgrade all apartments to `at least` level 3
Fine Apartments - Upgrade all apartments to `at least` level 4
Reason: Players might skip levels like I did.

~~Fine Apartments description is ok since there are no upgrades above it.~~
I forgot about Level V : Luxurious

Debugging save:
[Mark_Smith.zip](https://github.com/loiste-interactive/Obenseuer-Issues/files/13806296/Mark_Smith.zip)
You are standing in front of Jonasson and only need to purchase the last upgrade in this save.

**Comment by Zuntti** [comment]
Fixed
