### ISSUE TITLE
Furniture Disappearing

### ISSUE THREAD

**Issue by sewer-dweller** [loiste-interactive/Obenseuer-Issues#1653]
Current version of the game - two different saves. One was an angle grinder sitting on a wooden pallet bench, and this time is a small wooden shelf. I checked my building/furniture mode to make sure I didn't accidentally pick it up - it was gone. 

[obenseuer save 1-1-24.zip](https://github.com/loiste-interactive/Obenseuer-Issues/files/13807116/obenseuer.save.1-1-24.zip)

**Comment by Zuntti** [comment]
Related to https://github.com/loiste-interactive/Obenseuer-Issues/issues/1658
