### ISSUE TITLE
Issue #1624 incorrectly labeled as a migration issue. Should be bug.

### ISSUE THREAD

**Issue by sashort** [loiste-interactive/Obenseuer-Issues#1655]
I've done some further testing related to issue #1624.
This is the new, unmigrated save:
[John_Doe.zip](https://github.com/loiste-interactive/Obenseuer-Issues/files/13811868/John_Doe.zip)

It appears, even with a new game in current version, door state (locked/unlocked) does not change.
If it's a new game, the door is open.
For previous saves, it remains in the state you lasted walked out of Deekula C.

This YouTuber spotted the bug at 17:09 in this video:
https://www.youtube.com/watch?v=XEx5nqfZaYw&t=3013s
In his case, the door is still open after hours

**Comment by Oskutin** [comment]
seems to work now
