### ISSUE TITLE
Moving around a brown fridge (gathered from Ap 4), while it has items inside seems to cause old issues, the fridge got duplicated, while some other furniture started disappearing.

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#1658]
[Player.zip](https://github.com/loiste-interactive/Obenseuer-Issues/files/13813403/Player.zip)
[Miko_Mortley.zip](https://github.com/loiste-interactive/Obenseuer-Issues/files/13813411/Miko_Mortley.zip)
Autosave has pre-bug state, slot 9 has post-bug state. You can find a flying lantern where previously was a shelf as well as duped (stacked) fridges in smaller room.

**Comment by Zuntti** [comment]
I can't reproduce this

**Comment by Zuntti** [comment]
I couldn't reproduce this but I made some changes but I made some changes that might help with this

**Comment by Zuntti** [comment]
There are changes in the latest version that might help with this. Open a new issue if furniture are still disappearing or duplicating
