### ISSUE TITLE
0.3.28 Bug - Cleaning Mode Triggers walking out of roof greenhouse door after 1st upgrade.

### ISSUE THREAD

**Issue by sashort** [loiste-interactive/Obenseuer-Issues#1663]
https://youtu.be/OVrqRtTyCws

[Mark_Smith.zip](https://github.com/loiste-interactive/Obenseuer-Issues/files/13813991/Mark_Smith.zip)
<sub>Inital <code>Cleaning Mode</code> with <code>L</code> button does not automatically appear if build menu is activated by player before exiting greenhouse (either in stairwell or greenhouse.)
Cleaning mode will still engage by pressing <code>L</code> in stairwell after entering greenhouse.</sub>

Notes:
Migrated save
Just made final payment on Shabby Rooftop Greenhouse. This is the first time entering the greenhouse.
Biohazard bags still present on 1st floor landing.

**Comment by sashort** [comment]
Follow-up after removing biohazard bags. I'm pretty sure the stairwell has been cleaned 100%.
https://youtu.be/GR7DZD8KAEs
Video is only 0:52.

**Comment by Zuntti** [comment]
Fixed

**Comment by Zuntti** [comment]
That 24 pack has 23 bottles of Osmo Beer. Added text to show what items it has if the inventory is full
