### ISSUE TITLE
0.3.28 Bug - Cannot pick up items in basement

### ISSUE THREAD

**Issue by sashort** [loiste-interactive/Obenseuer-Issues#1669]
I feel like this bug has been present since build mode was added to basement.

Frequent problem.
Fixed by reload but will occur again.
Unsure what triggers bug.

Examples of items that can't be picked up:
• Items on shelves
• Items dropped on top of cabinets
• Items dropped on floor 

<hr>

How I triggered the bug:
<sub>NOTE: I did the following 2x. Bug did not occur on 2nd runthrough!<br>See video showing bug</sub>
[Mark_Smith.zip](https://github.com/loiste-interactive/Obenseuer-Issues/files/13835192/Mark_Smith.zip)
Note: Migrated save. Unsure if it's a bug propagated to 0.3.28 or if it's a migration issue.
• Go to a drawer and interact with it
• Break all of the glass into glass shards in your inventory
• Transfer all glass shards into the drawer

Here's a video of me loading this save and performing the steps above.
https://youtu.be/F5rYwYpqd6w
<sub>Length: 2:49</sub>

**Comment by Zuntti** [comment]
Fixed
