### ISSUE TITLE
0.3.28 - Plywood crafted from sawdust finishes instantly

### ISSUE THREAD

**Issue by CVariable** [loiste-interactive/Obenseuer-Issues#1673]
Crafting from planks takes 12 minutes, but crafting from sawdust happens instantly.
![grafik](https://github.com/loiste-interactive/Obenseuer-Issues/assets/45665371/b1f3c9af-f77f-4648-9789-f1fe89e64ae8)

**Comment by Nextej** [comment]
I think this is intentional, you're just glueing the dust so there's not woodworking, unlike in the planks recipe where you need to cut the planks first to glue them.

**Comment by CVariable** [comment]
I feel like it would make sense for that to still take time, especially as compressing isn't technically possible at all using a saw. But if the devs agree with you, they will just close the issue hopefully

**Comment by Oskutin** [comment]
Fixed
