### ISSUE TITLE
Player can start a crafting processes requiring liquid in a row even if they don't have enough liquid.

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#1680]
This one is, peculiar, let's say we have 40L of ruined mash in two plastic containers (20L each) and we want to craft some fertile soil that costs 15L each, if we place just 40L of ruined mash into a composter, starting 3 processes in a row (a total of 45L of needed ruined mash) will be allowed.

before
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/7e530043-636a-42ec-ae9a-30a92f5327ec)

after
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/9f38a09b-b951-4364-aa84-11ebd28edf81)

**Comment by Zuntti** [comment]
Fixed
