### ISSUE TITLE
Crafting Biogas using ruined mash (20L + empty bottle) cannot be started in biogas reactor.

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#1681]
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/394d8923-7562-4409-8919-29f0001a8f10)
Recipe is not shown

**Comment by Oskutin** [comment]
caused by this: https://github.com/loiste-interactive/Obenseuer-Issues/issues/1680 ?
