### ISSUE TITLE
Crop harvesting quality varies greatly between in-world and UI

### ISSUE THREAD

**Issue by Chiesef** [loiste-interactive/Obenseuer-Issues#1682]
Version: 0.3.28
Harvesting carrots from a growing box gives different quality output depending on how they're harvested. Harvesting them from the growing box's UI (by clicking on them) gives higher-quality plants, while harvesting them in-world by pressing "E" on the growing plants gives generally lower-quality crops. Farming skill was the same (10) between both plots, which were both growing boxes with lights.
I'm guessing the Efficiency modifier's only applied on the UI and not the world.

This image has an example of the differences.
![OSPlanterHarvesting](https://github.com/loiste-interactive/Obenseuer-Issues/assets/137258363/bac428dc-2b43-46eb-a676-5fb9d84c6854)

**Comment by Zuntti** [comment]
Fixed
