### ISSUE TITLE
Exhausted tree debris cause collisition as if trees were still there

### ISSUE THREAD

**Issue by ClementFoucher** [loiste-interactive/Obenseuer-Issues#1684]
1) Locate tree debris
![20240105115914_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/113233219/ca1ec7db-0244-4ed2-9c3e-b4b894a2b0cf)
2) Chop it fully
![20240105120051_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/113233219/d95ae345-664b-4485-9491-84305144f8b3)
3) Leave the area (e.g. by entering the nearby shop) and come back: phantom exhausted tree are spawned, causing collision as if tree debris was still there:
![20240105120218_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/113233219/e4eed111-1b2f-4268-ae60-c4246061fdc2)

**Comment by sashort** [comment]
I've noticed this too. The hit box doesn't change to match the visual state of the tree debris.

**Comment by Zuntti** [comment]
Fixed
