### ISSUE TITLE
Requested commands

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#169]
1. A command(s) that add recipes and blueprints in the fashion of add_item.
2. A command that shows IDs and Names of all the items in the game.
3. A command that modifies/sets current Health, neither of the two available Health commands seems to work like that, nor work at all in anyway.
4. A command that shows the current player stats.

**Comment by Oskutin** [comment]
Added health command

**Comment by Oskutin** [comment]
Added get stats command

**Comment by Oskutin** [comment]
Added find command for items
