### ISSUE TITLE
Negative progression % on mashing tun process.

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#1691]
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/c96971be-bfc9-4503-9267-3569e92f5057)
[Miko_Mortley.zip](https://github.com/loiste-interactive/Obenseuer-Issues/files/13845537/Miko_Mortley.zip)
[Player.zip](https://github.com/loiste-interactive/Obenseuer-Issues/files/13845538/Player.zip)
slot 2 is the latest

**Comment by Oskutin** [comment]
Fixed
