### ISSUE TITLE
0.3.28 Bug - Steam Achievement LOCKPICKING OUTCAST not unlocking

### ISSUE THREAD

**Issue by sashort** [loiste-interactive/Obenseuer-Issues#1694]
I just reached level 10 for lockpicking.
Lockpicking outcast wasn't unlocked.

Do you need me to submit a save right before hitting level 10?

**Comment by Oskutin** [comment]
How old is your save? This was fixed a while back ago.

**Comment by Oskutin** [comment]
People are getting the achivement:
![kuva](https://github.com/loiste-interactive/Obenseuer-Issues/assets/5402150/8fe67e45-0153-4652-b630-59006a43b00d)
