### ISSUE TITLE
In apartment A20, curtains disappear depending on the viewing angle

### ISSUE THREAD

**Issue by ClementFoucher** [loiste-interactive/Obenseuer-Issues#1697]
![20240106093524_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/113233219/6239113b-6e3f-405c-a51b-dc5ba115320e)
![20240106093504_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/113233219/f95354a9-47ee-4400-98b5-bad4e148a32b)
![20240106093501_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/113233219/45c97b1e-3fc2-4f6f-ade2-7537e0e5b688)
![20240106093455_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/113233219/4e579ac0-f1bf-4cf5-8de4-75a11a7398b2)
![20240106093454_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/113233219/34d6c3a1-c3e0-428f-8784-12e3dc7fa01d)

**Comment by Zuntti** [comment]
Fixed
