### ISSUE TITLE
In apartment A3, sitting on the bench at the left of the entrance make facing wall

### ISSUE THREAD

**Issue by ClementFoucher** [loiste-interactive/Obenseuer-Issues#1698]
![20240106095729_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/113233219/ab713724-df32-47c1-9cf0-74e109249c33)
![20240106095717_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/113233219/85cb4c29-1844-4965-846d-31891558895c)
Sitting:
![20240106095723_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/113233219/53eef3f7-9b04-4fc1-9970-3926e15486c4)

**Comment by Zuntti** [comment]
Fixed
