### ISSUE TITLE
Log storage inconsistent visual state

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#170]
On example of the one found in B4 apartment, when visiting it for the first time, it seems to always have full state, when opening it, it changes it's look to a smaller amount of logs present.
https://user-images.githubusercontent.com/44178400/235739677-a2a51019-47b0-4a9c-a073-34b836b7d594.mp4

After taking all the wood from it and placing it back, the visual stack of the logs is even smaller, probably because the storage takes amount of taken slots as a representation, not the actual total values of all the stacks present in the storage.
https://user-images.githubusercontent.com/44178400/235739815-2c5865ee-55b2-4a61-b1a0-9935873b2804.mp4

https://user-images.githubusercontent.com/44178400/235740052-cf4423b9-2b96-48b2-9a10-a54f7060cbff.mp4

**Comment by Oskutin** [comment]
Fixed
