### ISSUE TITLE
After some time, placed items using building mode will become unpickable.

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#1700]
[Miko_Mortley.zip](https://github.com/loiste-interactive/Obenseuer-Issues/files/13850625/Miko_Mortley.zip)
On that character on slot 4, there are several moldy waste items placed in a corner of the basement, that cannot be picked up.

Placing another item of the same kind, and reloading the level, will make those items pickable again.

**Comment by sashort** [comment]
I think this is the same bug I reported in #1669

**Comment by Zuntti** [comment]
Fixed
