### ISSUE TITLE
Furniture store was closed when it should be open (save/load fixes it)

### ISSUE THREAD

**Issue by Tritiumisotope** [loiste-interactive/Obenseuer-Issues#1702]
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/67477899/da2351ca-51ba-40f7-b0cc-9ab467d19c6e)

As it says on the tin. Noon on a weds, in case this doesn't load, deekula C.

**Comment by Oskutin** [comment]
already fixed in upcoming
