### ISSUE TITLE
Large fancy wooden desk has its function as its name

### ISSUE THREAD

**Issue by Tritiumisotope** [loiste-interactive/Obenseuer-Issues#1703]
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/67477899/ad24a569-85df-40d4-a994-d03cc7782e50)

counterexample:

![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/67477899/30a855d1-c12c-4755-941e-0fd35ea50a2e)

First should be more like second. I think some other items also do this.

**Comment by Zuntti** [comment]
Fixed
