### ISSUE TITLE
0.3.28 Bug - [Balcony|Water|Heat] Initial Apt Resource Reqs  should be blank

### ISSUE THREAD

**Issue by sashort** [loiste-interactive/Obenseuer-Issues#1704]
Initial Upgrades
`Balcony` `Bare`
`Water` `Off`
`Heat` `None`  
for an apartment show the same required resources.
No resources should be listed.

<img width="1280" alt="Water" src="https://github.com/loiste-interactive/Obenseuer-Issues/assets/95879519/4416f35c-d780-45e3-b7ce-3ba2723cb548">

**Comment by Zuntti** [comment]
Fixed
