### ISSUE TITLE
Craft bug in chemical lab > furniture disappears after trying to move or take the lab.

### ISSUE THREAD

**Issue by iam-n0x** [loiste-interactive/Obenseuer-Issues#1706]
- Crafting at the chemical lab is bugged and it doesn't leave the bottom as it should.
- Once finished you are not able to make any new recipe.
- If you try to move or pick up the table and save/reload, a piece of furniture will disappear.
- In Slot 2, crafting is in progress.
- In Slot 1, the worktable placed behind the character has disappeared. (after trying to move the chemical lab) 
- Autosave contains the bucket with the water bottom used for crafting.
- Migrated save from v0.3.27 to v0.3.28
[Bob_Sponge.zip](https://github.com/loiste-interactive/Obenseuer-Issues/files/13855243/Bob_Sponge.zip)

**Comment by Zuntti** [comment]
The chemical lab seems to be fixed already. I can't get the worktable removal bug in Slot 2

**Comment by iam-n0x** [comment]
Weird, I've downloaded and reused the saves and I can't reproduce the bug with the disappearing furniture..
The inability to craft again remains on the chemical lab until save/reload (it says "Crafting full 1/1).
Also, any idea where the bucket with the water bottom is?

**Comment by Zuntti** [comment]
Fixed disappearing bucket
