### ISSUE TITLE
The drill produces lockpicks faster than the lathe, even if the stats display indicates otherwise.

### ISSUE THREAD

**Issue by iam-n0x** [loiste-interactive/Obenseuer-Issues#1709]
https://www.youtube.com/watch?v=_opyNKNLhH4

Save migrated from v0.3.27 to v0.3.28

**Comment by Oskutin** [comment]
This is intentional, as drill requires player while lathe is automatic.

**Comment by iam-n0x** [comment]
What I mean is that the information is wrong.
The information displayed on the drill is 17 minutes, whereas on the lathe it's 12 (max machining skill).
