### ISSUE TITLE
Playtesting - Overlapping textures on makeshift basement

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#1711]
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/f46e09f7-ae5c-4430-9f10-8b4c4f50ade4)
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/628bcbde-72dd-4b87-ae6c-02f6f638f411)
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/16a0cf15-89c6-42d4-954a-0743dbbbad5f)

**Comment by Zuntti** [comment]
Fixed
