### ISSUE TITLE
Playtesting - Windows inside playerment don't have the same intesity

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#1714]
West side 
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/89ec5011-166c-4000-88ff-a89fdc8e4c4a)
East side
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/950d4cac-36e4-4571-851b-6b9d298e2536)

**Comment by Oskutin** [comment]
can't seem to be able to repro this
