### ISSUE TITLE
Playtesting - no "Biogas" recipe is revealed in biogas reactor

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#1718]
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/6ff32754-6884-4024-bc4b-5bdaf26b2283)

**Comment by Oskutin** [comment]
What is the item you're trying to use?

**Comment by Nextej** [comment]
Ruined Glowing Mash

**Comment by Oskutin** [comment]
Fixed
