### ISSUE TITLE
Public - sometimes it may happen that storage containers are completely grayed out (don't render any storage slots), at any point in the game.

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#1719]
Example 1: https://steamcommunity.com/app/951240/discussions/0/6689600878688860651/
Example 2: https://www.youtube.com/live/D6NDrvO0W1s?feature=shared&t=1114

Storages from the very start, on every map, don't render any slots

**Comment by Oskutin** [comment]
This needs save files

**Comment by Oskutin** [comment]
Savefile: https://steamcommunity.com/linkfilter/?u=https%3A%2F%2Fdrive.google.com%2Fdrive%2Ffolders%2F164Lzl1hMBudJej-XPCPFKoeH1XP6uhKH%3Fusp%3Dsharing

**Comment by Zuntti** [comment]
Maybe related to https://github.com/loiste-interactive/Obenseuer-Issues/issues/1124?

**Comment by Oskutin** [comment]
Yes it was that
