### ISSUE TITLE
Planting our seeds in an owned farms makes the harvest marked as stolen.

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#172]
![image](https://user-images.githubusercontent.com/44178400/235745920-ec4f61fd-c1b7-45ab-a54e-e0deabd504fe.png)
If that's intentional, there should be an option to ask to use a farm, and if such situation happens elsewhere where property is owned, but no owner to be found, it should not be marked as stolen either.

**Comment by Oskutin** [comment]
Permisison feature already exists
