### ISSUE TITLE
Playtesting - Watching TV makes you incredibly depressed

### ISSUE THREAD

**Issue by PestoVerde322** [loiste-interactive/Obenseuer-Issues#1724]
As the title suggest, watching Tv for 2 hours will send your mental health to 0%, not sure to why that's the case.

![immagine](https://github.com/loiste-interactive/Obenseuer-Issues/assets/75247747/f4dc4eee-b179-4a30-83d0-22b688de4471)

**Comment by Oskutin** [comment]
already fixed
