### ISSUE TITLE
Playtesting - The tenement is gone when you're doing a facade rennovation

### ISSUE THREAD

**Issue by PestoVerde322** [loiste-interactive/Obenseuer-Issues#1725]
As the title suggest, the tenement just disappear, leaving an hollow shell when its just rennovating the facade, leading to hilarious results:

![20240115165750_1 1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/75247747/f58c8ad0-ff71-4748-ae73-5e4817e81ed2)

![image 1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/75247747/ca87af6a-2b53-48f8-bb11-0bd624f9a3db)dfc19131f168&

**Comment by Zuntti** [comment]
Fixed
