### ISSUE TITLE
Crash/freeze on version 0.3.29

### ISSUE THREAD

**Issue by macend** [loiste-interactive/Obenseuer-Issues#1729]
[Player.log](https://github.com/loiste-interactive/Obenseuer-Issues/files/13953889/Player.log)
[Player-prev.log](https://github.com/loiste-interactive/Obenseuer-Issues/files/13953892/Player-prev.log)
As the title says. Game just crashed first time in 36hrs. The save is not a clean one, started the game in 0.3.27 then .28 and then rolled into the playtest version. Doesn't remember what I did at the moment of the crash, but 100%sure wasn't anything that was introduced with version 0.3.29.

**Comment by Zuntti** [comment]
There doesn't seem to be any crash in the player log. Maybe the game froze? I'm closing this because there is no information why this happened
