### ISSUE TITLE
Kolhola A15 Lockpicking bug.

### ISSUE THREAD

**Issue by Gnarynhar** [loiste-interactive/Obenseuer-Issues#1734]
When trying to lockpick the door for A15 in the Kolhola building, the lockpicking interface disappears after a short amount of time, often before the arrow gets to the target area. To keep the interface open to pick the door you have to click immediately and sacrifice a lockpick. The interface then stays open and works as normal.

**Comment by Oskutin** [comment]
Can't reproduce
