### ISSUE TITLE
Invisible Wall In OS Telemarketing Office Bug

### ISSUE THREAD

**Issue by Gnarynhar** [loiste-interactive/Obenseuer-Issues#1735]
In the public version's latest update in the telemarketing office I can't just walk into the back area. There's an invisible wall starting at the pot plant blocking off the rest of the room, except for a small corridor along the wall. Walking to the end and crouching allows me to jump up onto the carrels, and then walk along the to and gather cans/bottles/etc and even jump down to access the rest of the room. but I have to jump back up onto the carrels to get back out.

**Comment by Zuntti** [comment]
Already fixed
