### ISSUE TITLE
At a shop vendor, if player double clicks to buy a liquid in a container, after purchase the liqui will disappear in seemingly random amounts

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#1736]
before purchase
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/14df642c-61d1-44d0-854b-c6ae64be309e)
after 
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/24a2725e-03c4-4b61-ac6d-e88cc92fc58b)
got reduced from 0,6L to 0,2L

**Comment by Zuntti** [comment]
Fixed
