### ISSUE TITLE
New Game tutorial - Button - Text Box?

### ISSUE THREAD

**Issue by greensalt99** [loiste-interactive/Obenseuer-Issues#1738]
![Newgame - buttons](https://github.com/loiste-interactive/Obenseuer-Issues/assets/154023649/dc872c2a-c87f-41fd-ae0e-b3cec4effeee)

This Button message to a player should be adjusted into more readable form. 
Button names does not fit into text box.
I am using Arrow Keys to move.  Left Arrow, Right Arrow, Up, Down.

**Comment by Zuntti** [comment]
Fixed
