### ISSUE TITLE
Missing backside barriers during workshop upgrade

### ISSUE THREAD

**Issue by N-G-Neer** [loiste-interactive/Obenseuer-Issues#1739]
When upgrading the workshop (level 1), the construction barriers are missing on the basement entrance side (the one near OSS)
Player can walk into the area and become stuck if they fall to the lower basement floor.

![20240117214758_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/15633807/6085c735-bf54-44de-a4f4-2e277c4d7453)
![20240117214801_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/15633807/52becbdd-7bcb-4f22-9107-151fba51baf8)

**Comment by Oskutin** [comment]
Atleast the missing stairs are now fixed.
Need to confirm the other thing

**Comment by Zuntti** [comment]
Fixed
