### ISSUE TITLE
Plant Matter Quallity and Spoling

### ISSUE THREAD

**Issue by greensalt99** [loiste-interactive/Obenseuer-Issues#1742]
0.3.29
Is it now supposed to be that some Plants make "Plant matter" with Quality and Spoilage indicators. 
Some Plants still acts like old normal, without above mentioned indicators.

[Slot8.zip](https://github.com/loiste-interactive/Obenseuer-Issues/files/13980218/Slot8.zip)

**Comment by Oskutin** [comment]
Which plants?
Also plant matter is waste item without quality&spoilage values.

**Comment by greensalt99** [comment]
you giving me lot of work :P ok ill try to make a list.

1. List of Spoillage&Quality values plants:
    Onions, Sugar beet, Turnip, Carrot, Potato, Cabbage,
   1.2 Water melons plant matter have Spoilage level but no Quality.

2. List of Plants that give plant matter without Spoillage&Quality. Standart Old Plant matter:
    Rye, Wheat, Snakeplant, Monsteraplant , Heracleumplant, Dracaenaplant, Cactus, Soleiroliaplant

3. Did not provide "plant matter" : 
    Leek, Lettuce, Hops, Peas, Cucumbers, Tomatoes, Bell Pepper, 

4. Hops, Tomatoes provide seeds.

5. Jompee Kurahaara farm does not buy Water Melons and Hops, not sure if it supposed. (hops is not vegie so it is logical) Not sure if you get seeds(water melons,hops) from seed box. SO i guess it is supposed to be this way.

6. SnakePlant and Monstera Plant spoil(super fast), so as decorative plants they fail their function 

7. Why some flower names have conjunction with word Plant while others separated? Like SnakePlant and Monstera Plant.

8. Peas/Cucumbers growd 1 harvest and continue to growing -1 .... till died, growing after harvest should be named spoiling. cause there were no more harvesting. Bell Peppers after last fruit harvested continues -1 to grow to 0% health.

**Comment by greensalt99** [comment]
Spoiling levels is sort of annoying.  if i buy food and go to sleep, i get lot of spoiled food. The whole system should be looked, or just make growing plants min 1day, spoil like 2days.
