### ISSUE TITLE
Crafting Full error on Metal Lathe after crafting can opener

### ISSUE THREAD

**Issue by N-G-Neer** [loiste-interactive/Obenseuer-Issues#1743]
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/15633807/9b058aab-7708-4ae2-a34d-1763ee43047a)

**Comment by Oskutin** [comment]
Got save file?

**Comment by N-G-Neer** [comment]
> Got save file?

Sure ! Where are they located again ?

**Comment by Gnarynhar** [comment]
I've had the same bug
[Slot1.zip](https://github.com/loiste-interactive/Obenseuer-Issues/files/13987192/Slot1.zip)

N-G-Neer. save files are in the your users folder- AppData\ocalLow\Loiste Interactive..

**Comment by N-G-Neer** [comment]
If another file is needed, here's mine. 
[Slot10.zip](https://github.com/loiste-interactive/Obenseuer-Issues/files/13991500/Slot10.zip)

**Comment by Oskutin** [comment]
Fixed
