### ISSUE TITLE
Player can jump on the greenhouse roof and over the kurahaara's house to see edge of the map, a barrier preventing that would be needed

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#1746]
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/26e8ee92-277d-4f37-968a-4487b201abf6)

**Comment by Nextej** [comment]
Player can also get stuck here
![Uploading image.png…]()

**Comment by Oskutin** [comment]
Fixed
