### ISSUE TITLE
super small bug - can and some bottles spawned near this tent is not always pick able or have messed hitbox.

### ISSUE THREAD

**Issue by greensalt99** [loiste-interactive/Obenseuer-Issues#1748]
[Slot10.zip](https://github.com/loiste-interactive/Obenseuer-Issues/files/13992927/Slot10.zip)

**Comment by Oskutin** [comment]
Picture of the location?

**Comment by greensalt99** [comment]
this can has no hitbox, but if other item spawns, like plastic bottle, it will have hitbox way to the left side. sometimes there nothing spawns. i have seen this bug in youtube videos too, sorry dont remember what video. like i said small bug.
![unpickalble](https://github.com/loiste-interactive/Obenseuer-Issues/assets/154023649/1e01998a-9e2e-4039-846f-8cf6769b2aa8)

second pick for better positional view.
![unpickalble bigger picture](https://github.com/loiste-interactive/Obenseuer-Issues/assets/154023649/4298ecf4-75d0-44dc-87d2-62c6b0811bab)

 PS: Oskutin i have answered your question about plants
https://github.com/loiste-interactive/Obenseuer-Issues/issues/1742#issuecomment-1902583486
