### ISSUE TITLE
Bergman tunnel locked Mike briefcase changes difficulty?

### ISSUE THREAD

**Issue by greensalt99** [loiste-interactive/Obenseuer-Issues#1750]
https://www.youtube.com/watch?v=1qiyEoK-sQU&list=WL&index=102&t=133s
youtube video of letsplay
Obenseuer Gameplay part 33 - Bergmann Tunnel Exploration (Open Sewer AKA Obenseuer Overhaul Update)

22:40 lock Easy, 23:06 Lock changes to moderate O_O bug?
i had 20:09 gate to change difficulty for me too, came once it was easy. 
came on other save file it was challenging. went out and came after a day or so and it became effortless. 
december save files. sorry dont have more info.
magic locks?

**Comment by Zuntti** [comment]
Beer affects lockpicking difficulty and also lockpicking skill
