### ISSUE TITLE
Suggestion important - trigger zone is to small

### ISSUE THREAD

**Issue by greensalt99** [loiste-interactive/Obenseuer-Issues#1751]
Bergman tunnels. Check video in youtube
Obenseuer Gameplay part 33 - Bergmann Tunnel Exploration (Open Sewer AKA Obenseuer Overhaul Update)
28:00
player comes to a ladder, sees Bank "Blocked" and gets confused. Trigger zone is way to small to notify player that he have found way to the bank and that quest part is done. So if someone will move from that moment out of Tunnels his quest wont progress forward.
 
I suggest to either not display early "Blocked" message, or expand trigger zone.
same issue might happen in other quests. please keep in mind this when making other triggers. thank you.

**Comment by Zuntti** [comment]
Fixed
