### ISSUE TITLE
Buyable festive lights that can be either attached to the ceiling or hanged on the wall.

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#1752]
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/ce443ea2-d35b-4eef-998e-3fc7cc149a99)

**Comment by greensalt99** [comment]
more decorations would be nice overall . Different people like different stuff. Decorating world the way you want it, would be definitely big game benefit :) 
Hype Hype !!!

**Comment by Nextej** [comment]
Already implemented
