### ISSUE TITLE
Typo in bank customer service dialogue.

### ISSUE THREAD

**Issue by TheRealLogiti2** [loiste-interactive/Obenseuer-Issues#1754]
When contacting the bank about a new card the word please has been misspelled and is instead written as pleace. (quite minor but still changes games completeness feel)

![Screenshot 2024-01-21 014444](https://github.com/loiste-interactive/Obenseuer-Issues/assets/106812831/d5da2924-c37a-4046-9d01-93fcda91c645)

**Comment by Zuntti** [comment]
Fixed
