### ISSUE TITLE
Talking with Bar keeper, mash, Pentti Steals, speak easy

### ISSUE THREAD

**Issue by greensalt99** [loiste-interactive/Obenseuer-Issues#1756]
There is mess with mash. Using December save updated to 0.3.29

1. Speak Easy Barkeeper (Pentti Pentila) when you talk with him and say i want to sell mash.
 He takes your mash automatically and does not pay. (stealing!!) 
 1.2 I have reloaded many times. Tried same stuff and sometimes you see those canisters in his inventory, 
       sometimes not. (Extra bug)
[Slot10 mash thief.zip](https://github.com/loiste-interactive/Obenseuer-Issues/files/14000667/Slot10.mash.thief.zip)

2. noticed that if barkeep has odd prices for mash canisters. (Stole Mash, he left canisters empty to me)
    20L 1.2RM but 5L 1.1RM , so selling combined would cost 0.10RM for 15L?? 

![odd mash cost](https://github.com/loiste-interactive/Obenseuer-Issues/assets/154023649/b34e5521-467a-4f36-9a15-fcfd69807b21)

I don't know what happened, but i am sure he did not stole my canisters before and i could sell him 5L/20L canisters without glitch. 

Brought to him 3 separate canisters with 5L/20L Mash. He stole it and combined in his inventory into 
15L priced 1.1RM

**Comment by Zuntti** [comment]
Fixed
