### ISSUE TITLE
The shadow object next to b2 door in the basement acts very strange when you move around and can even start covering the door itself

### ISSUE THREAD

**Issue by Crlangley** [loiste-interactive/Obenseuer-Issues#176]
![20230426211414_1](https://user-images.githubusercontent.com/65619937/236727692-b4ab5a6d-741b-428b-b533-deb7035f7b3c.jpg)
![20230426211445_1](https://user-images.githubusercontent.com/65619937/236727694-1dcbec68-3193-43f1-be8d-0f4ce7025af2.jpg)

Might not be an issue and intended,  it just looked a bit off to me when i started noticing how it was interacting with the environment. It kind of grows and moves with your character. Light from an flashlight kind of interacts with it strangely as well. Doesn't really affect it as much as you might expect.

**Comment by Oskutin** [comment]
Already fixed
