### ISSUE TITLE
0.3.29 graphical issue at yard first upgrade

### ISSUE THREAD

**Issue by macend** [loiste-interactive/Obenseuer-Issues#1760]
In version 0.3.29 after I upgraded the yard to the first tier, if I go the place where the porta-potty was before, every object vanishes and I only see some light blue background. As I turn around objects pop up and go. When I move from that spot everything is ok.
![20240121183856_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/156837031/51d5ef97-0d62-444e-b779-ec8662c22cf4)

**Comment by Zuntti** [comment]
Fixed
