### ISSUE TITLE
0.3.29 Misplaced door in kolhola a22

### ISSUE THREAD

**Issue by iam-n0x** [loiste-interactive/Obenseuer-Issues#1761]
![a22](https://github.com/loiste-interactive/Obenseuer-Issues/assets/90686125/59fcb217-e95d-4aab-80a1-346e8e7a56c4)
[Quack_Killer.zip](https://github.com/loiste-interactive/Obenseuer-Issues/files/14001721/Quack_Killer.zip)

**Comment by Oskutin** [comment]
Fixed
