### ISSUE TITLE
0.3.29 Black Icon Mushroom need and NaN need addiction value

### ISSUE THREAD

**Issue by iam-n0x** [loiste-interactive/Obenseuer-Issues#1764]
After spending a few days eating shit/sleeping pills/painkillers and drinking dirty water/methanol, this black shroom icon appeared after eating or drinking (tested with shit/dirty water/painkiller/osmo olut).

https://github.com/loiste-interactive/Obenseuer-Issues/assets/90686125/d31e6110-1910-4e54-a927-e5a4f9bed6b1

[Quack_Killer.zip](https://github.com/loiste-interactive/Obenseuer-Issues/files/14009202/Quack_Killer.zip)

**Comment by Zuntti** [comment]
Fixed
