### ISSUE TITLE
Passmore has no space when selling

### ISSUE THREAD

**Issue by rpc1234** [loiste-interactive/Obenseuer-Issues#1770]
(Filename: E:/Loiste/Open Sewer/Assets/Scripts/Utility/TakeScreenshot.cs Line: 50)
![20240124163017_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/157072430/ae9c081f-97f8-4ce1-acec-51ca11cf073b)

(Filename: E:/Loiste/Open Sewer/Assets/Scripts/ItemSystem/Slot.cs Line: 97)

Trade slot debug: SetSlotController
UnityEngine.StackTraceUtility:ExtractStackTrace ()
UnityEngine.DebugLogHandler:LogFormat (UnityEngine.LogType,UnityEngine.Object,string,object[])
UnityEngine.Logger:Log (UnityEngine.LogType,object)
UnityEngine.Debug:Log (object)
Slot:SetSlotController (SlotController) (at E:/Loiste/Open Sewer/Assets/Scripts/ItemSystem/Slot.cs:227)
SlotController:CaptureSlot (UnityEngine.Transform) (at E:/Loiste/Open Sewer/Assets/Scripts/ItemSystem/SlotController.cs:778)
Storage:GetStorage () (at E:/Loiste/Open Sewer/Assets/Scripts/Storage/Storage.cs:566)
Storage:EnterExternally (bool) (at E:/Loiste/Open Sewer/Assets/Scripts/Storage/Storage.cs:670)
Trade:StartTrade () (at E:/Loiste/Open Sewer/Assets/Scripts/Crafting/Trade.cs:330)
UnityEngine.Events.InvokableCall:Invoke ()
UnityEngine.Events.UnityEvent:Invoke ()
Outputs.output:onEventInvoke () (at E:/Loiste/Open Sewer/Assets/Scripts/Utility/Outputs.cs:112)
RelayDialogue:onEventInvoke (Outputs.output) (at E:/Loiste/Open Sewer/Assets/Scripts/Utility/LogicEntities/RelayDialogue.cs:84)
RelayDialogue:triggerOutputs () (at E:/Loiste/Open Sewer/Assets/Scripts/Utility/LogicEntities/RelayDialogue.cs:26)
System.Reflection.MonoMethod:Invoke (object,System.Reflection.BindingFlags,System.Reflection.Binder,object[],System.Globalization.CultureInfo)
System.Reflection.MethodBase:Invoke (object,object[])
Language.Lua.LuaMethodFunction:InvokeMethod (Language.Lua.LuaValue[]) (at E:/Loiste/Open Sewer/Assets/Plugins/Pixel Crushers/Dialogue System/Scripts/Lua/Lua Interpreter/LuaValue/LuaMethodFunction.cs:35)
Language.Lua.FunctionCall:Evaluate (Language.Lua.LuaValue,Language.Lua.LuaTable) (at E:/Loiste/Open Sewer/Assets/Plugins/Pixel Crushers/Dialogue System/Scripts/Lua/Lua Interpreter/Expr/FunctionCall.cs:41)
Language.Lua.PrimaryExpr:Evaluate (Language.Lua.LuaTable) (at E:/Loiste/Open Sewer/Assets/Plugins/Pixel Crushers/Dialogue System/Scripts/Lua/Lua Interpreter/Expr/PrimaryExpr.cs:15)
Language.Lua.ExprStmt:Execute (Language.Lua.LuaTable,bool&) (at E:/Loiste/Open Sewer/Assets/Plugins/Pixel Crushers/Dialogue System/Scripts/Lua/Lua Interpreter/Chunk/ExprStmt.cs:11)
Language.Lua.Chunk:Execute (bool&) (at E:/Loiste/Open Sewer/Assets/Plugins/Pixel Crushers/Dialogue System/Scripts/Lua/Lua Interpreter/Chunk/Chunk.cs:42)
Language.Lua.Chunk:Execute () (at E:/Loiste/Open Sewer/Assets/Plugins/Pixel Crushers/Dialogue System/Scripts/Lua/Lua Interpreter/Chunk/Chunk.cs:15)
Language.Lua.LuaInterpreter:Interpreter (string,Language.Lua.LuaTable) (at E:/Loiste/Open Sewer/Assets/Plugins/Pixel Crushers/Dialogue System/Scripts/Lua/Lua Interpreter/LuaInterpreter.cs:38)
PixelCrushers.DialogueSystem.Lua:RunRaw (string,bool,bool) (at E:/Loiste/Open Sewer/Assets/Plugins/Pixel Crushers/Dialogue System/Scripts/Lua/Lua Wrapper/Lua Interpreter/Lua.cs:223)
PixelCrushers.DialogueSystem.Lua:Run (string,bool,bool) (at E:/Loiste/Open Sewer/Assets/Plugins/Pixel Crushers/Dialogue System/Scripts/Lua/Lua Wrapper/Lua Interpreter/Lua.cs:129)
PixelCrushers.DialogueSystem.ConversationModel:GetState (PixelCrushers.DialogueSystem.DialogueEntry,bool,bool,bool) (at E:/Loiste/Open Sewer/Assets/Plugins/Pixel Crushers/Dialogue System/Scripts/MVC/Model/Logic/Model/ConversationModel.cs:234)
PixelCrushers.DialogueSystem.ConversationModel:GetState (PixelCrushers.DialogueSystem.DialogueEntry) (at E:/Loiste/Open Sewer/Assets/Plugins/Pixel Crushers/Dialogue System/Scripts/MVC/Model/Logic/Model/ConversationModel.cs:304)
PixelCrushers.DialogueSystem.ConversationController:OnSelectedResponse (object,PixelCrushers.DialogueSystem.SelectedResponseEventArgs) (at E:/Loiste/Open Sewer/Assets/Plugins/Pixel Crushers/Dialogue System/Scripts/MVC/Controller/ConversationController.cs:304)
PixelCrushers.DialogueSystem.ConversationView:SelectResponse (PixelCrushers.DialogueSystem.SelectedResponseEventArgs) (at E:/Loiste/Open Sewer/Assets/Plugins/Pixel Crushers/Dialogue System/Scripts/MVC/View/View/ConversationView.cs:504)
PixelCrushers.DialogueSystem.ConversationView:OnSelectedResponse (object,PixelCrushers.DialogueSystem.SelectedResponseEventArgs) (at E:/Loiste/Open Sewer/Assets/Plugins/Pixel Crushers/Dialogue System/Scripts/MVC/View/View/ConversationView.cs:497)
PixelCrushers.DialogueSystem.AbstractDialogueUI:OnClick (object) (at E:/Loiste/Open Sewer/Assets/Plugins/Pixel Crushers/Dialogue System/Scripts/UI/Abstract/Dialogue/AbstractDialogueUI.cs:346)
PixelCrushers.DialogueSystem.StandardDialogueUI:OnClick (object) (at E:/Loiste/Open Sewer/Assets/Plugins/Pixel Crushers/Dialogue System/Scripts/UI/Standard/Dialogue/StandardDialogueUI.cs:352)
PixelCrushers.DialogueSystem.StandardUIResponseButton:OnClick () (at E:/Loiste/Open Sewer/Assets/Plugins/Pixel Crushers/Dialogue System/Scripts/UI/Standard/Dialogue/StandardUIResponseButton.cs:132)
UnityEngine.Events.InvokableCall:Invoke ()
UnityEngine.Events.UnityEvent:Invoke ()
UnityEngine.UI.Button:Press () (at E:/Loiste/Open Sewer/Library/PackageCache/com.unity.ugui@1.0.0/Runtime/UI/Core/Button.cs:68)
UnityEngine.UI.Button:OnPointerClick (UnityEngine.EventSystems.PointerEventData) (at E:/Loiste/Open Sewer/Library/PackageCache/com.unity.ugui@1.0.0/Runtime/UI/Core/Button.cs:110)
UnityEngine.EventSystems.ExecuteEvents:Execute (UnityEngine.EventSystems.IPointerClickHandler,UnityEngine.EventSystems.BaseEventData) (at E:/Loiste/Open Sewer/Library/PackageCache/com.unity.ugui@1.0.0/Runtime/EventSystem/ExecuteEvents.cs:50)
UnityEngine.EventSystems.ExecuteEvents:Execute<UnityEngine.EventSystems.IPointerClickHandler> (UnityEngine.GameObject,UnityEngine.EventSystems.BaseEventData,UnityEngine.EventSystems.ExecuteEvents/EventFunction`1<UnityEngine.EventSystems.IPointerClickHandler>) (at E:/Loiste/Open Sewer/Library/PackageCache/com.unity.ugui@1.0.0/Runtime/EventSystem/ExecuteEvents.cs:261)
UnityEngine.EventSystems.StandaloneInputModule:ReleaseMouse (UnityEngine.EventSystems.PointerEventData,UnityEngine.GameObject) (at E:/Loiste/Open Sewer/Library/PackageCache/com.unity.ugui@1.0.0/Runtime/EventSystem/InputModules/StandaloneInputModule.cs:195)
UnityEngine.EventSystems.StandaloneInputModule:ProcessMousePress (UnityEngine.EventSystems.PointerInputModule/MouseButtonEventData) (at E:/Loiste/Open Sewer/Library/PackageCache/com.unity.ugui@1.0.0/Runtime/EventSystem/InputModules/StandaloneInputModule.cs:645)
UnityEngine.EventSystems.StandaloneInputModule:ProcessMouseEvent (int) (at E:/Loiste/Open Sewer/Library/PackageCache/com.unity.ugui@1.0.0/Runtime/EventSystem/InputModules/StandaloneInputModule.cs:553)
UnityEngine.EventSystems.StandaloneInputModule:ProcessMouseEvent () (at E:/Loiste/Open Sewer/Library/PackageCache/com.unity.ugui@1.0.0/Runtime/EventSystem/InputModules/StandaloneInputModule.cs:533)
UnityEngine.EventSystems.StandaloneInputModule:Process () (at E:/Loiste/Open Sewer/Library/PackageCache/com.unity.ugui@1.0.0/Runtime/EventSystem/InputModules/StandaloneInputModule.cs:289)
UnityEngine.EventSystems.EventSystem:Update () (at E:/Loiste/Open Sewer/Library/PackageCache/com.unity.ugui@1.0.0/Runtime/EventSystem/EventSystem.cs:377)
 
(Filename: E:/Loiste/Open Sewer/Assets/Scripts/ItemSystem/Slot.cs Line: 227)

about to send file over playerconnection C:/Program Files (x86)/Steam/steamapps/common/Obenseuer/Obenseuer_Data/Screenshots/Interior Tenement B_01_24_2024_1.png  with length 1568906
Failed to store screen shot (C:/Program Files (x86)/Steam/steamapps/common/Obenseuer/Obenseuer_Data/Screenshots/Interior Tenement B_01_24_2024_1.png) 
(Filename: C:\buildslave\unity\build\Modules/ScreenCapture/CaptureScreenshot.cpp Line: 86)

Saved screenshot as: Screenshots/Interior Tenement B_01_24_2024_1.png
UnityEngine.StackTraceUtility:ExtractStackTrace ()
UnityEngine.DebugLogHandler:LogFormat (UnityEngine.LogType,UnityEngine.Object,string,object[])
UnityEngine.Logger:Log (UnityEngine.LogType,object)
UnityEngine.Debug:Log (object)
TakeScreenshot/<ScreenshotNoUICO>d__2:MoveNext () (at E:/Loiste/Open Sewer/Assets/Scripts/Utility/TakeScreenshot.cs:50)
UnityEngine.SetupCoroutine:InvokeMoveNext (System.Collections.IEnumerator,intptr)

**Comment by Zuntti** [comment]
Fixed
