### ISSUE TITLE
Inventory bug 0.3.30 (not developer version)

### ISSUE THREAD

**Issue by macend** [loiste-interactive/Obenseuer-Issues#1772]
![20240124213446_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/156837031/575ed064-c9b6-461d-85b6-7b0d8d3173ec)
The two upmost rows are my backpack, Pedro's inventory below. 1 interaction earlier with him was fine.

**Comment by Zuntti** [comment]
Already fixed in upcoming
