### ISSUE TITLE
Passmore still has space issue with certain items

### ISSUE THREAD

**Issue by rpc1234** [loiste-interactive/Obenseuer-Issues#1773]
![20240125132428_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/157072430/92f293cd-e13a-4fa2-a36a-c4581219f983)
![20240125132443_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/157072430/a4128112-1f20-45e2-bc1b-45d6811e50c7)
![20240125132445_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/157072430/48bf182e-d046-435b-a985-348afb24baa0)

**Comment by rpc1234** [comment]
Out of Space  where sell button is

**Comment by Zuntti** [comment]
Already fixed in upcoming
