### ISSUE TITLE
Cannot move after working for OS Marketing company

### ISSUE THREAD

**Issue by N-G-Neer** [loiste-interactive/Obenseuer-Issues#1778]
![20240126182549_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/15633807/9c6dc799-b49a-4155-949a-ffb461f88d3c)
Not sure what's happening here, whether I'm being spawned inside the table or something else. I have 98% tiredness and hunger in this screenshot. I'm using the desk closest to the entrance. I tried doing this right after the new save migration process, also.

**Comment by greensalt99** [comment]
i have used this table today and it worked for me. maybe your position is issue?

**Comment by greensalt99** [comment]
so it is fixed?, i have found if you tired more like 90% you get locked. if 77% you can move
