### ISSUE TITLE
In 0.3.30 V2 Basement mushroom farm makeshift level renovation never finishes

### ISSUE THREAD

**Issue by macend** [loiste-interactive/Obenseuer-Issues#1780]
In 0.3.30 V2 Basement mushroom farm makeshift level renovation never finishes. I can pay the final payment indefinitely over and over again. Under task I receive the message that renovation is done, but in the basement is still under construction.

**Comment by Zuntti** [comment]
Same as https://github.com/loiste-interactive/Obenseuer-Issues/issues/1786 and also fixed
