### ISSUE TITLE
Cleaning of player tenement resets after entering building

### ISSUE THREAD

**Issue by wolfnuke** [loiste-interactive/Obenseuer-Issues#1781]
[playtesting version 0.3.30 v2] 
The tenements in the player's building resets to the initial dirty state upon exiting and reentering the building. If I clean various rooms and exit, the tenement menu screen and the upgrade screen show that the rooms are clean and available to upgrade, but after reentering the building all of the dirt/trash/graffiti reappears. The furniture that has been removed is still removed, but the other trash items like bags and paper on the floor return.
[Player.log](https://github.com/loiste-interactive/Obenseuer-Issues/files/14070726/Player.log)

**Comment by Zuntti** [comment]
Can I get a save?

**Comment by wolfnuke** [comment]
Here is a new save I created that has the issue and little else completed.

[Slot1.zip](https://github.com/loiste-interactive/Obenseuer-Issues/files/14087842/Slot1.zip)

**Comment by Zuntti** [comment]
Fixed
