### ISSUE TITLE
Inventory and Storage issues

### ISSUE THREAD

**Issue by rpc1234** [loiste-interactive/Obenseuer-Issues#1782]
A lot of my storage furniture is resetting and my items are disappearing. additionally when i try to move furniture, sometimes it duplicates the furniture. As well sometime when opening storage containers it shows your backpack inventory instead.

**Comment by greensalt99** [comment]
Hello rpc1234, can you give more details on how is this happening. You have multiple issues.
Game Dev can then duplicate those issues and fix them.

**Comment by rpc1234** [comment]
![20240128133139_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/157072430/9fc0afb2-6c8a-4a31-9be2-55fef093617d)
Here is one example where i have gone to move a kitchen cabinet and it has duplicated the item instead. 
All my kitchen cabinets had their internal inventories wiped when i moved the, same with bedside tables. 
Additionally when opening some storage units your inventory is displayed where the containers contents should be

**Comment by Zuntti** [comment]
Fixed
