### ISSUE TITLE
[Playtesting, migrated save, V.0.3.30] Somehow can pay Jonasson the basement workshop 4 times, or infinitely.

### ISSUE THREAD

**Issue by Ludvig11** [loiste-interactive/Obenseuer-Issues#1786]
[Workshop-Lumi_Pakkanen.zip](https://github.com/loiste-interactive/Obenseuer-Issues/files/14074460/Workshop-Lumi_Pakkanen.zip)

https://github.com/loiste-interactive/Obenseuer-Issues/assets/31344357/7ce3bf74-cfdc-40fe-a599-6e9667c815ee

**Comment by Zuntti** [comment]
Fixed
