### ISSUE TITLE
Renovating Balconies

### ISSUE THREAD

**Issue by rpc1234** [loiste-interactive/Obenseuer-Issues#1787]
I already had my frnot balcony at level 2 and decided to renovate my back balcony to level one. However the construction tarp has been placed over the wrong one. 
![20240128133128_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/157072430/1bbe5ea5-550c-4d7b-a23b-c22a7f645768)
![20240128133131_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/157072430/bea542ee-8532-4c6a-8754-cc2dbd6a95d8)

**Comment by rpc1234** [comment]
And as you can see the back balcony is just a void as it it being built where my front balcony is now only accessible from the external door.

**Comment by Zuntti** [comment]
Fixed
