### ISSUE TITLE
From older saves, police officers tended to get stuck near level transitions and would always respawn in a new place, there should be a call for them to respawn in their original positions.

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#1788]

**Comment by greensalt99** [comment]
suggestion. after every time police loose suspect in "level transition" and gets back to its original patrol.
next time police will run faster after suspect. every time increasing in speed until suspect is caught. 
if suspect lost police run speed =+1

**Comment by Zuntti** [comment]
Added
