### ISSUE TITLE
0.3.30 V3 backpack is is still bugged

### ISSUE THREAD

**Issue by macend** [loiste-interactive/Obenseuer-Issues#1789]
![Tenement materials and backpack](https://github.com/loiste-interactive/Obenseuer-Issues/assets/156837031/8cfcd5b8-be8b-4c3a-bbfe-02e8d2460de4)
![Backpack plus 3 row](https://github.com/loiste-interactive/Obenseuer-Issues/assets/156837031/215ac224-9a3f-4d5e-8698-b0a8a40e4243)
1. 1st pic: I opened the tenement box next to Johanssen(?) with a backpack and the UI couldn't handle it
2. 2nd pic: every storage in my apartment and my backpack has plus 3 rows on the top.
3. I am not able to open my backpack more than once. I have to unequip it and equip again.
4. Sort button doesn't work in backpack

Q: Should I seperate this as 4 different issues or is it ok like this?

**Comment by DFliyerz** [comment]
Yeah, I ran into this too. It seems like as soon as you load into an area it opens the backpack with a bunch of empty slots then those empty slots persist in all inventories.

**Comment by Zuntti** [comment]
Fixed the new issue that caused this when changing the scene. Can you send a save if it's still happening after upcoming update?
