### ISSUE TITLE
Tenement resources chest and backpack inv combined

### ISSUE THREAD

**Issue by greensalt99** [loiste-interactive/Obenseuer-Issues#1791]
steps (this is not suggestion, i am trying to describe bug? )
1. open Tenement resources chest by Samuel Jonasson. 
2 open backpak while you are in Tenement resources chest.
3 close inventory (not backpack)
4 open Tenement resources chest and you will see combined Backpack inv and Tenement Inv.

i am sure it is a bug, but you can call it feature ;)
![inv combined bug](https://github.com/loiste-interactive/Obenseuer-Issues/assets/154023649/c5df249d-95b7-457f-8bd4-6b7b9f02cd61)

**Comment by Oskutin** [comment]
Playtest/new build?

**Comment by Zuntti** [comment]
Fixed
