### ISSUE TITLE
Duplications when moving items

### ISSUE THREAD

**Issue by rpc1234** [loiste-interactive/Obenseuer-Issues#1793]
The item duplication error still happens at less random intervals than previous when moving objects. 
![20240201110520_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/157072430/902587f7-8519-40c6-92ee-880bd09db553)

**Comment by Zuntti** [comment]
Probably related to this https://github.com/loiste-interactive/Obenseuer-Issues/issues/1792 or maybe that furniture was duplicated before the update? Open a new issue if it persists after the upcoming hotfix

**Comment by rpc1234** [comment]
No it happens in my apartment too so untelated to #1792

Sincerely
Robert Clohesy
________________________________
