### ISSUE TITLE
Biogas reactor

### ISSUE THREAD

**Issue by rpc1234** [loiste-interactive/Obenseuer-Issues#1800]
This item appears to be broken. It does not produce any gas, it just creates Mould.
I have tried many times over the last several updates to work it, but every time it fails.

**Comment by Oskutin** [comment]
Did you put the gas bottle in the compressor?

**Comment by rpc1234** [comment]
Yes, and it disappeared. The biogas gauge always reads zero as well.

Sincerely
Robert Clohesy
________________________________

**Comment by rpc1234** [comment]
Couldn't create a Convex Mesh from source mesh "compressor" within the maximum polygons limit (256). The partial hull will be used. Consider simplifying your mesh. 
(Filename:  Line: 91)

Couldn't create a Convex Mesh from source mesh "Cylinder" within the maximum polygons limit (256). The partial hull will be used. Consider simplifying your mesh. 
(Filename:  Line: 91)

**Comment by rpc1234** [comment]
I believe this is still a bug. The canister disappears from the bioreactor, it never fills. Will try using it in the apartment as an alternative but expect similar results

**Comment by riktoi** [comment]
Running into the same issue where no biogas is produced. The byproduct of moldy waste is created just fine.
Tried both in the basement area and in the apartment and the results are the same. Tried with the gas bottle in the compressor, not in the compressor, with the compressor running and with the compressor not running.

**Comment by rpc1234** [comment]
I believe this is still a bug. The canister disappears from the bioreactor, it never fills. We are all using it right

**Comment by TonyFromRomania** [comment]
in my case from 4 biogas reactors only one was fully opeational and filling my gas cans the others been duds

**Comment by Oskutin** [comment]
Is the working one new, and the others previously placed/old ones?

**Comment by TonyFromRomania** [comment]
the working one is the first one bought in the save (witch i started when the migration mechanic was added) the other ones i kinda forgot witch one was bough or just a cloned instance from the furniture duping glitch 
eventually sold them and kept the working one

**Comment by Oskutin** [comment]
Okay, I guess newly bought ones will work.

**Comment by Bdan720** [comment]
Mine is new. Bought from Tenement Contract Work on a v0.3.33 save. No migration.

**Comment by TonyFromRomania** [comment]
my case is that due to my pre migration save took to long to do the migration i started a new  gameplay witch got plagued by more bugs then the original one, beside furniture dupe glitch, my character stopped needing water(from v0.3.31 until even the beta v0.3.34), bio gas reactor still not having working pressure gauge (it keeps saying is 0% but i continue to fill up my cans and barely made any gas in the past week), frankly i should make a list when i find any new glitches
