### ISSUE TITLE
0.3.30 - Player items are locked in a locker in the prison if they get re-arrested in the prison

### ISSUE THREAD

**Issue by CVariable** [loiste-interactive/Obenseuer-Issues#1803]
Players keep reporting that they get locked out of their items if they get thrown back in jail before taking them, e.g. by lockpicking in front of the guard or by turning off the tv. Then, they only have access to the other locker, while their items are still in the first one.
I'm not sure if this behavior is intentional, but some players seem frustrated by it.
Reports of it on discord:
"Long story and unsure if intentional, but I lockpicked into  the tunnels from the jail while serving time and by the time I got back to the cell I'd been released, which entering the cell (or maybe he saw me walk past Cell 2 by mistake?) counted as me breaking intojail and needing to serve more time.  When I got released the second time, only my OG jail inventory was returned to me. I think my real inventory was in the other locker, but that would have meant having to distract the guard etc" -akio
"occurred to me, I thought I had lost the inventory and it is impossible to lockpick in one of the lockers without the guard seeing, so I ended up getting arrested a few times and when I went to the first cell I had been arrested I waited for the sentence to end and my items were in the locker." - guilherme99gc

**Comment by Oskutin** [comment]
I think this issue is duplicate

**Comment by N-G-Neer** [comment]
I think I got a double-whammy on this one. Got arrested while sleeping at home, the guard opened the gate and told me I was free, I get caught for trespassing the moment I get out of the cell and get thrown in the other, but when I get out, not only are both lockers empty, but all my items are scattered on the floor, some out of bounds and a large chunk of them missing (including the Super Flashlight, RIP)

Don't steal, kids !

**Comment by Oskutin** [comment]
fixed
