### ISSUE TITLE
Pentii doesn't pay for mash (Workaround drag and drop)

### ISSUE THREAD

**Issue by Shadowfire117** [loiste-interactive/Obenseuer-Issues#1804]
When talking to Pentii, sometimes the mash has disappeared, havent had it happen yet in this attempt, might have been fixed but just bringing it up.

The current big bug is that whenever one attempts to sell mash to Pentii, the item disappears, no matter if one doubleclicks, press the sell button.

The current workaround is to drag and drop the mash into his trading inventory in order for the sale to happen with sound and everything.

**Comment by Zuntti** [comment]
Fixed
