### ISSUE TITLE
Kolhola Lift  first floor call button status problems

### ISSUE THREAD

**Issue by greensalt99** [loiste-interactive/Obenseuer-Issues#1811]
[Slot3.zip](https://github.com/loiste-interactive/Obenseuer-Issues/files/14151468/Slot3.zip)
this might be for all lifts.

go with lift to 2 or other level. go stairs down. call lift but fastly leave building. if you came back, lift will be coming down.
However lift call button will be locked in "Calling-Yellow" status. you wont be able to use that button again. 

added save, but you might not need it, it is easy to reproduce, going up to maybe 3 or 4 level, cause lowering from second might not be enough time to leave Kolhola. 

I have feeling leaving buildings might bug out more stuff this way. no fail-save to save status of stuff that it is not completed when you leave building. you know your code better.  i am not trying to insult or something, just my thoughts :)

**Comment by Oskutin** [comment]
Fixed
