### ISSUE TITLE
Turnip Man's LV 1 Balcony is a void

### ISSUE THREAD

**Issue by rpc1234** [loiste-interactive/Obenseuer-Issues#1814]
![20240204161700_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/157072430/f4caa699-dabb-42e3-a5fe-0fb38fc996f7)

**Comment by greensalt99** [comment]
Hey rpc1234. i have noticed when upgrading walls and it is not finished, walls get void texture. is this upgrade finished?

**Comment by rpc1234** [comment]
Yeah the upgrade is fully complete has has been for several ingame weeks

**Comment by greensalt99** [comment]
i have now upgraded straight his balcony to L2  and it looks fine. haven't done any L1 balcony upgrades :/

**Comment by Zuntti** [comment]
Fixed
