### ISSUE TITLE
Item shortcuts in inventory don't work/display until after hitting the use button once

### ISSUE THREAD

**Issue by N-G-Neer** [loiste-interactive/Obenseuer-Issues#1818]
Example : A plastic container with drinkable water inside.
Normally I would just select it and press X to drink, but currently the list of shortcut and the shortcut itself doesn't display/work until after I clicked the Drink button once.

It seems to happen and random, not necessarily on save load or map change. Could be related to the grayed out fuel slot on stoves ?

**Comment by N-G-Neer** [comment]
Found the cause. When pressing TAB, if the first tab to open is the map/tasks/not the inventory, the list of shortcuts won't display below and the shortcuts will not work in the inventory until you press the use button on an item once.

**Comment by Zuntti** [comment]
Fixed
