### ISSUE TITLE
Overlapping items in Malones room - v0.3.33

### ISSUE THREAD

**Issue by Bdan720** [loiste-interactive/Obenseuer-Issues#1820]
In Malone's apartment, his loos items, like bottles and jars, seems to respawn but overlap multiple times every day. You know, like the Russian Matryoshka doll effect? I can pick up one empty bottle, but there is another one over it. I picked up 36 + bottles.

This only happens in Malone's room.

v0.3.33 - Fresh save

**Comment by Zuntti** [comment]
Fixed
