### ISSUE TITLE
[0.3.33] Apartment 7 - Infinitely Respawning Items

### ISSUE THREAD

**Issue by Issueseuer** [loiste-interactive/Obenseuer-Issues#1822]
Apartment 7 has some items that infinitely respawn. I think they do every time you enter the tenement, but I'm unsure.

![issue_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/159054294/5abf986b-2e00-45f9-8bda-c422a4053db1)

**Comment by greensalt99** [comment]
hello Issueseuer.   isnt this Turnip man place? :)
