### ISSUE TITLE
[0.3.33] Apartment 6 - Phantom Body-/Sleeping Bag

### ISSUE THREAD

**Issue by Issueseuer** [loiste-interactive/Obenseuer-Issues#1823]
When you are in the hallway you can see the removed body bag having reappeared after removal, but it disappears when you enter the apartment.

![issue_2](https://github.com/loiste-interactive/Obenseuer-Issues/assets/159054294/f69a4107-af86-4064-baff-d611a4f1ffcf)

**Comment by Zuntti** [comment]
Fixed
