### ISSUE TITLE
[Visuals][0.3.33] Item name doesn't match the style of the rest items.

### ISSUE THREAD

**Issue by l-HealthAngel-l** [loiste-interactive/Obenseuer-Issues#1828]
While making a full list of items I noticed that one item name doesn't have capitalized other words in the name.
This item is by ID: 26011, and the current name is "Glowing chicken meat". It should be "Glowing Chicken Meat" since the following item by ID: 26016 has the name "Glowing Chicken Steak".
![26011](https://github.com/loiste-interactive/Obenseuer-Issues/assets/76599402/60d26f6b-9cca-4c19-92ff-fb9ec118787a)
![26016](https://github.com/loiste-interactive/Obenseuer-Issues/assets/76599402/0a727971-b09e-4326-b5ea-4180f1131211)

**Comment by Zuntti** [comment]
Fixed
