### ISSUE TITLE
[0.3.33] Fermenting Bucket Duplication

### ISSUE THREAD

**Issue by Issueseuer** [loiste-interactive/Obenseuer-Issues#1834]
The fermenting bucket allows for duplicating bottles and liquids.

**Replication Steps**
1. Ferment something in the fermenting bucket.
2. Place a stack of 8 empty bottles (the 0.3 liter ones) in the bucket's inventory.
3. Click "Fill".
4. Right-click drag one of the now filled stack's bottles to the inventory slot next to it.
5. Drag the seperated bottle onto the original stack.
6. **[Subissue 1]** The bottle empties into the stack and becomes a bugged 0 liter item.
7. Drag the bugged bottle into the original stack once more.
8. The fill button becomes available again. Click it as much as you want.

**Screenshots**
<details>
<summary>Click for Screenshots</summary>

![issue_5](https://github.com/loiste-interactive/Obenseuer-Issues/assets/159054294/3ef55638-00f3-4580-9c2b-b75972467f73)

![issue_4](https://github.com/loiste-interactive/Obenseuer-Issues/assets/159054294/198d3090-7c11-4d5f-b80c-30d63def42dc)
</details>

**Comment by Zuntti** [comment]
Fixed
