### ISSUE TITLE
Playtesting - SMV issues

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#1835]
- When the SMV progression reaches 100%, it loops back to 0% to start rising again
- When player finally travels to Other Side by a mushroom consumption when the SMV is high, they get immediately kicked back to normal world within few seconds.

**Comment by Zuntti** [comment]
It seems to go back to 0% if god mode is on

**Comment by Zuntti** [comment]
Fixed
