### ISSUE TITLE
v0.3.33 - Refual slots blocked for Ball Grillers and Barrel stoves over time.

### ISSUE THREAD

**Issue by Bdan720** [loiste-interactive/Obenseuer-Issues#1838]
This is an odd bug. This happens inside the tenement building and outside.

After spending time in player apartment building, somewhere between 4 to 6 minutes or more, the fuel slots on Ball Grills and Barrel stoves gets blacked out. **I'm unable to refuel the stoves unless I exit and enter the building again.**

This also happens outside the O Market - Barrel Stove fuel slot gets disabled.

v0.3.33

In apartment and outside. Perhaps elsewhere too.

![Screenshot 2024-02-07 160252](https://github.com/loiste-interactive/Obenseuer-Issues/assets/50018197/c2581f70-9756-432b-84c9-1c7e6b52cca3)
![Screenshot 2024-02-07 160411](https://github.com/loiste-interactive/Obenseuer-Issues/assets/50018197/b8bec1c4-5954-46e0-a882-a01264b73df4)

**Comment by TonyFromRomania** [comment]
yea the bug is old and it repeats numeorus times (also the bug is stopping you to get ash from burning things as fuel) repeats as in appears then return to normal and repeat
