### ISSUE TITLE
Possibly in relation to issue #78: Light Switch animation is still broken, it restarts immediately after turning it on.

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#184]
https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/da3b6448-8de8-4558-8fb4-c562437b4401

**Comment by Oskutin** [comment]
Seems to be savegame issue

**Comment by Nextej** [comment]
well, it happened before I had a chance to make and reload a savefile

**Comment by Oskutin** [comment]
Map transitions do save and load, hence savegame issue.

**Comment by Oskutin** [comment]
Seems to be fixed?
