### ISSUE TITLE
Unable to upgrade Basement Heating system.

### ISSUE THREAD

**Issue by Bdan720** [loiste-interactive/Obenseuer-Issues#1840]
I have all the requirements for the Tenement Building Basement Heating but the game will not budge when clicking to go ahead.

This happens also with other rooms. I have one upgrade heating in player's room.

![Screenshot 2024-02-07 172126](https://github.com/loiste-interactive/Obenseuer-Issues/assets/50018197/f301659d-48f9-4d14-9050-1def5de71f05)

[Pirkko_Hansley.zip](https://github.com/loiste-interactive/Obenseuer-Issues/files/14195820/Pirkko_Hansley.zip)

**Comment by TonyFromRomania** [comment]
dud are you trying to upgrade to lvl2 or you are not noticing you already have lvl1 upgrade done ?

**Comment by Bdan720** [comment]
Oh...I realized there are 2 heating upgrades. Heating per room and heating in the basement.
I'm confused.

**Comment by Bdan720** [comment]
Delete this issue post if im wrong.
Sorry.

**Comment by TonyFromRomania** [comment]
be careful next time and you can use the help and issues chat from discord for consusions like this
