### ISSUE TITLE
yard lvl 3 corner near gazibo not having the fundation wall the way in the corner

### ISSUE THREAD

**Issue by TonyFromRomania** [loiste-interactive/Obenseuer-Issues#1841]
![20240207193601_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/157300727/3bcf0525-0f2d-4b64-8269-87341fe223a4)
![20240207193617_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/157300727/104d283d-d155-44a9-b9e9-25699f12b872)
![20240207193622_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/157300727/ee1a37eb-1b85-475a-a3e6-e03da4de0d8a)

**Comment by Zuntti** [comment]
Fixed
