### ISSUE TITLE
Window bug 

### ISSUE THREAD

**Issue by TonyFromRomania** [loiste-interactive/Obenseuer-Issues#1844]
![20240209163141_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/157300727/cfaebf98-8843-49ec-8e66-1aeb04c9ef7e)
i see the window been shifted to the left bug is still exiting

**Comment by Zuntti** [comment]
Same as https://github.com/loiste-interactive/Obenseuer-Issues/issues/1862
