### ISSUE TITLE
bugging shop inventory into void

### ISSUE THREAD

**Issue by greensalt99** [loiste-interactive/Obenseuer-Issues#1845]
I think this bug works for all shops. Tried on Tools and Firewood shop.
this is not important bug or damaging. at least for now. dangerous if you brake some supper important quest items in future, haven't seen such quest yet.

Steps:

1. In shop inventory with mouse take 1 item from stack.
2. drop that item in black row. look at pic  (it is not so easy to do)
![stack](https://github.com/loiste-interactive/Obenseuer-Issues/assets/154023649/5f7326f5-2742-450f-93c2-a4406af27080)
3. stack spot will get 1 item and rest of stack will disappear.

after some time it will reappear. not sure if it is time issue or talking with npc.
it wont reappear if  other mat changes spot with that 1 item. if you shuffle them.

**Comment by TonyFromRomania** [comment]
this almost similar with the bug i had when v0.3.29 dropped and the hardware vendor inventory was so full i got away with 5-6 stacks of wood ,3 of cement and at least one of paint and pipes

**Comment by greensalt99** [comment]
well in my case i get nothing out of this bug. it not game braking, but odd.
version 0.3.33

**Comment by TonyFromRomania** [comment]
IK  it just reminded me of that one "free stuff" moment

**Comment by Zuntti** [comment]
Fixed
