### ISSUE TITLE
graphical issue - upgrading Heating in cellar

### ISSUE THREAD

**Issue by greensalt99** [loiste-interactive/Obenseuer-Issues#1846]
while upgrading heating you can see through fence that room is empty, but other side is tarped. so this side should be tarped too. 

![fence](https://github.com/loiste-interactive/Obenseuer-Issues/assets/154023649/1c251d1c-ca3e-4f7b-a1d6-dcd5788801f3)

**Comment by Zuntti** [comment]
Fixed
