### ISSUE TITLE
[0.3.33] Apartment 14 - Multiple Issues

### ISSUE THREAD

**Issue by Issueseuer** [loiste-interactive/Obenseuer-Issues#1847]
~~**Issue 1:** The apartment can't be fully cleared. Maybe the destroyable (and unremovable) boxes count towards the percentage?~~ Never mind. Missed some bricks hidden in the doorway brick piles.
**Issue 2:** Phantom fireplace after removal. Visible from living room/kitchen and disappears when entering the bedroom.
**Issue 3:** The body on the bed gives a unusable and non-standard green mushroom item.

**Screenshots**
Screenshots are in the same order as the issues.
<details>
<summary>Click for Screenshots</summary>

![issue_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/159054294/114b5960-d322-4cfe-91cf-fef0565e5637)

![issue_2](https://github.com/loiste-interactive/Obenseuer-Issues/assets/159054294/9b29bb72-0a36-4bb6-a14c-e21c6631923f)

![issue_3](https://github.com/loiste-interactive/Obenseuer-Issues/assets/159054294/b6dc6217-47ec-4d5d-ba52-ae1451855d53)
</details>

**Comment by greensalt99** [comment]
0.3.33 Apartment 14 
1. is cleared for me. havent done upgrade to walls yet.
2. Fireplace ghost is at my place too. 
3. i got that too. and if you place that item it will make you cough.
![ghostly fireplace](https://github.com/loiste-interactive/Obenseuer-Issues/assets/154023649/cad37880-94aa-49b6-a3b1-9d256d2dc29d)

**Comment by Zuntti** [comment]
Fixed
