### ISSUE TITLE
Passage between storages B4 and B3 still seem to cause troubles with player getting stuck, it didn't seem like the issue was present on a ver 0.3.01, perhaps maybe it depends on the wood chunks?

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#185]
https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/344eb4a3-04ca-4c22-b5bd-ecb965532c0d

**Comment by Nextej** [comment]
Seems to be caused by the planks chunks, happens in other places too
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/70594044-313b-45f9-9c58-32cc5861c4bd)

https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/82edf685-7a32-4b2f-b7d3-3c9514a2dc75

**Comment by Oskutin** [comment]
Yeah this is fixed
