### ISSUE TITLE
[0.33.3] [suggestion] Rename "basic income" -> "base income"

### ISSUE THREAD

**Issue by goc9000** [loiste-interactive/Obenseuer-Issues#1853]
In the game, the term "basic income" appears when you're offering someone an apartment (in the preview box).

I don't know about Finland, but in English-speaking countries "basic income" almost always means a specific political/economic scheme whereby all people are given a minimum sum of money by the state each month, kind of like unemployment, except even if you have a job, no matter what.

Whether you think this is good or bad, I don't think this is what the devs meant in context. The term "base income" is more appropriate.

**Comment by Zuntti** [comment]
Changed
