### ISSUE TITLE
backpack issues 

### ISSUE THREAD

**Issue by Asireldreemurr213** [loiste-interactive/Obenseuer-Issues#1858]
i went inside the redemption militia building and i went into my backpack and it had double the space then when i left it went back to normal and all the items in it was gone

**Comment by greensalt99** [comment]
i guess you are using test build. 
0.3.33 my backpack had no issues.

**Comment by Asireldreemurr213** [comment]
if thats the latest one then yes

**Comment by greensalt99** [comment]
can you replicate and leave save file here :) 
lately there lot of random inv issues happening

**Comment by Asireldreemurr213** [comment]
[Slot10.zip](https://github.com/loiste-interactive/Obenseuer-Issues/files/14313012/Slot10.zip)

**Comment by Zuntti** [comment]
I can't replicate this
