### ISSUE TITLE
Forgot to sown this issue. windows on lvl2 large apartments have a chance to have the entire window been shifted

### ISSUE THREAD

**Issue by TonyFromRomania** [loiste-interactive/Obenseuer-Issues#1862]
![20240227150949_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/157300727/256b9292-d31c-4536-901a-3c5ee79633fb)
 bug is in this save visible at the second floor window, in my previous playthrough save the  first and 3 floor window was bugged , in a similar way

**Comment by Zuntti** [comment]
Fixed
