### ISSUE TITLE
Infinite glass shards loop

### ISSUE THREAD

**Issue by Rafasimon** [loiste-interactive/Obenseuer-Issues#1863]
Version 0.3.33

Broken bottles reappear in inventory if the last one is dropped.

Steps:
Start with a stack with >1 bottles;
Break them until only 1 is left;
Drop the remaining bottle;
Broken bottles reappear;
Pick up the dropped bottle to return to original stack size;
Repeat to get infinite glass shards.

Example:
Start with 4 bottles
Break 3 so 1 is left
Drop the bottle
3 bottles appear in the inventory
Pick up bottle to go back to 4

**Comment by Zuntti** [comment]
Fixed
