### ISSUE TITLE
Playtesting - console command doesn't return outputs of the commands, it's empty

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#1864]

**Comment by Oskutin** [comment]
Pic?

**Comment by Nextej** [comment]
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/3557829e-4361-4650-a199-2642161c04b2)
It seems like there's some massive lag whenever console is opened, and only giving mysefl a dosimeter fixed it

**Comment by Orphiex** [comment]
Having the same bug; the console seems to be functional (using the `add_item` trick spawned the correct item), but the text is either invisible, lagging, or just not generating. In my case, using `add_item code` didn't cause the text to generate, but using `player_stats get` worked; all of the text appeared, including the text for the previous entries

**Comment by Zuntti** [comment]
Seems to be fixed now
