### ISSUE TITLE
Playtesting - Malone's apartment by default lacks his unique furniture, malone is standing and a wooden planks come out of the ceiling

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#1869]
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/a2ae268b-a3d9-4d58-94d5-9fbf00c3a3f1)
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/562e0628-b3ac-4d11-ab90-c258997681c0)

**Comment by Zuntti** [comment]
Seems to be fixed now
