### ISSUE TITLE
Amanda's animation had resetted during a playthrough

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#187]
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/76912213-3d57-4586-9c77-76dede08c3a0)
Seems like other characters met the same fate.
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/113b6149-020c-4094-a784-9a07e259bb99)
Possibly an otherside encounter (with Priest) did cause it.
Changing maps back and forth seems to fix it.
[Player.log](https://github.com/loiste-interactive/Obenseuer-Issues/files/11470033/Player.log)

**Comment by Oskutin** [comment]
Seems to work
