### ISSUE TITLE
Playtesting - migration from .33 to .35 issues

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#1870]
- Default trash returned in the cleaned apartments
- Player placed furniture is gone
- When previewing the upgrade menu at Samuel's, all upgrades state that they are upgraded to max level, regardless of their state pre-migration, they will retain their state as they had, but will display that it's a max level, prevent player from starting more renovations

**Comment by Z-O-M-B-I-E** [comment]
Furniture disappears even if you start a new game.
All icons on the map and inventory become white squares.

**Comment by Zuntti** [comment]
Related to https://github.com/loiste-interactive/Obenseuer-Issues/issues/1866
