### ISSUE TITLE
Rebalancing of renovation costs

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#1871]
I'm proposing a new set of prices for respective renovations from Makeshift-Shabby levels to make the game progression smooth and not feeling grindy, taking into consideration the current means of making money (farming, bottle collecting, telemarketing, looting, money stealing) as well as the recent decrease of the rent income.

There however remains one problem with my proposal that leaves the things unbalanced as it stands out now, player can make quite an amount of money by cleaning whole tenement and selling the furnitures, which makes gathering money for early trivial, unless player decides to keep the furniture for themselves, which renders gathering money annoying. To combat this, I've already proposed #1190 with making an use of furniture quality (which is already in the game), make most (if not all) of the furniture player can gather from cleaning (at least on the first 3 floors) to be the shitties quality possible, rendering the least of possible profits.

Here's the list of my proposed changes to renovation costs
https://steamcommunity.com/app/951240/discussions/0/4040358019730215643/

**Comment by greensalt99** [comment]
lowest quality stuff looks bad, has debufs. best quality looks new and works good. yeah this could be extra layer to replace with better stuff. but upgrading your room sort of stands in the way. why would you replace when you just renovate. 

on cost think, game needs way more stuff to do. if you have lots of missions and stuff to explore, you will not notice grinding. however some prices are super expensive. this is why i suggested:
https://github.com/loiste-interactive/Obenseuer-Issues/issues/1666

**Comment by Nextej** [comment]
By quality I meant just a trait that defines value, like it is now for crops (the look is the same regardless of quality), so if player decides to keep them for themselves, they remain virtually unchanged as it is now, but if they were to sell it all, they wouldn't get suddenly a massive cash boost.

I think that generally there's enough to do in the game right now in relation to what levels of renovations you should have, Makeshift and Shabby for stuff in Residential, Decent and Fine in Bazaar, Luxurious in Central. Only thing I would add is a daily randomly generated jobs that would rely on player producing certain goods (boosting skills in various crafts) and delivering them for money in return. #1153 This should also help the alcohol brewing, cooking, machining (other than crafting lockpicks and watches) and farming to be performed more often, since there is stuff to do, just not very profitable right now.

**Comment by greensalt99** [comment]
how do you do farming in beginning? community farms stuff is marked as stealing.  so you cant grow it for random quests.
growing at home? i always got bad stuff. not sure how to improve farmed vegies.
i like daily random, but it will be boring fast, like in some mmo's. 

if item has bad quality why not add some dirt/spotty/split/crack texture on it. this way you will be reminded about having junk at home. :)

**Comment by Zuntti** [comment]
Changed
