### ISSUE TITLE
Playtesting - NPCs with broken hats

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#1877]
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/e8bbdc1f-f97b-4e7d-bc97-8902ef7607c4)
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/f6ef57d0-2c9a-4100-b137-ff6844021d5b)

**Comment by Nextej** [comment]
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/ea42be11-c112-4f26-8e0d-13121eb04747)

**Comment by Zuntti** [comment]
They're not broken. The colors have just changed
