### ISSUE TITLE
Buggy Behaviors with water bottle filling

### ISSUE THREAD

**Issue by snortico** [loiste-interactive/Obenseuer-Issues#1882]
Have one stack of 5 big bottles to fill with water. Trying to merge the stack together after filling, or drinking from the recently filled stack seems to empty water entirely. Can't pin down exactly how exactly it is broken, but filling and merging doesn't seem to want to work right.
[Slot2.zip](https://github.com/loiste-interactive/Obenseuer-Issues/files/14520558/Slot2.zip)

**Comment by snortico** [comment]
Seems to clear up when all bottles are emptied and then refilled, so something to do with merging non-full bottles with full bottles. For example, merging 4x1liter water bottles with a 1x0.9 liter bottle empties all the 4x1 liter bottles entirely.

**Comment by Zuntti** [comment]
Was the dishwasher used for other bottle? It seems to still have stolen data

**Comment by Zuntti** [comment]
Fixed
