### ISSUE TITLE
[Playtest] Broken Dishwasher

### ISSUE THREAD

**Issue by Z-O-M-B-I-E** [loiste-interactive/Obenseuer-Issues#1883]
For some unknown reason, one of their two dishwashers broke down. Maybe there was a sledgehammer inside

![20240308062022_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/46783282/16777947-3f52-4eaf-b65f-bbcc35f5e431)

[Slot3.zip](https://github.com/loiste-interactive/Obenseuer-Issues/files/14532804/Slot3.zip)

**Comment by Z-O-M-B-I-E** [comment]
A strange duplication of the stolen large lantern was also noticed. How can this be fixed?

**Comment by Z-O-M-B-I-E** [comment]
After the update, the dishwasher worked, but the duplication of the big flashlight remained

**Comment by Z-O-M-B-I-E** [comment]
There is an error when interacting with the dishwasher in the console
`Exception: NullReferenceException: The object reference is not set for the object instance`

**Comment by Oskutin** [comment]
Got updated savefile?

**Comment by Z-O-M-B-I-E** [comment]
> Got updated savefile?
[Slot1.zip](https://github.com/loiste-interactive/Obenseuer-Issues/files/14549819/Slot1.zip)

**Comment by Zuntti** [comment]
Fixed
