### ISSUE TITLE
Stacked soaps use one charge from every bottle in the stack.

### ISSUE THREAD

**Issue by snortico** [loiste-interactive/Obenseuer-Issues#1884]
Have 4 stacked 10/10 soaps, used the stack. Separating them later, I now have 4x 9/10 soaps.

**Comment by snortico** [comment]
Additionally, these stacks bug out? Not sure if this is a separate bug or related. Try to use the slot below the cigarettes in the inventory.
[Slot3.zip](https://github.com/loiste-interactive/Obenseuer-Issues/files/14547740/Slot3.zip)

**Comment by TonyFromRomania** [comment]
this bug is quite old  and happens with other items that are stackable and have multiple uses (coffee, 3D printer filament to name a few)

**Comment by Oskutin** [comment]
Fixed
