### ISSUE TITLE
Delete character - usability issue 

### ISSUE THREAD

**Issue by robmurg** [loiste-interactive/Obenseuer-Issues#1885]
It is too easy to unintentionally delete your entire character.

I was trying to delete a single save slot for housekeeping. I highlighted the slot and clicked on the waste bin icon. It asked me to confirm that I wanted to delete this character. I assumed that referred to the highlighted slot. When I replied 'yes' it deleted all the saved slots and as far as I can see there is no way to recover them. (I don't back up the AppData folder, they are not in the Recycle Bin). That is about 160 hours of gameplay gone which is rather disappointing.

**Comment by greensalt99** [comment]
yeah, agree on that, i have deleted my char too :/ and i was trying to delete save file.

**Comment by Zuntti** [comment]
Changed it to ask if you want to remove the slot if slot is highlighted and also changed the delete character text to tell that it removes all slots
