### ISSUE TITLE
[Playtest] The interaction interface is broken

### ISSUE THREAD

**Issue by Z-O-M-B-I-E** [loiste-interactive/Obenseuer-Issues#1888]
But it works on the dishwasher :D

![20240312230138_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/46783282/338a465c-28b5-4a86-b871-573e6f82f2f1)
![20240312230137_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/46783282/ca12134c-5f68-471b-a1a9-4a545bccf54e)
![20240312231520_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/46783282/9dd9246e-91ae-4010-ad5b-046a4a5b8b44)

**Comment by Oskutin** [comment]
save?

**Comment by Z-O-M-B-I-E** [comment]
> save?

[Slot3.zip](https://github.com/loiste-interactive/Obenseuer-Issues/files/14578870/Slot3.zip)

**Comment by Z-O-M-B-I-E** [comment]
> Fixed

It doesn't work with the latest update
![20240314203659_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/46783282/1cfc04e4-1abb-425e-a297-3b5eea06fae1)

[Autosave2.zip](https://github.com/loiste-interactive/Obenseuer-Issues/files/14606066/Autosave2.zip)
