### ISSUE TITLE
[Playtest] The problem with washing some items

### ISSUE THREAD

**Issue by Z-O-M-B-I-E** [loiste-interactive/Obenseuer-Issues#1889]
Washing of wines and other drinks, which are counted in liters, happens strangely (see pic).

![20240312233804_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/46783282/5c3d38e0-45e7-450d-ad6d-20708b9f4d58)
![20240312233814_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/46783282/d89defcd-699d-433d-93a9-80efa3ac1be7)

Washing of flashlight is also broken. A flashlight with a 41% charge is duplicated and 1% is taken away. We get an old stolen flashlight with a 40% charge and a new one not stolen from 41%

![20240312233043_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/46783282/2cc4fa26-c108-4059-810a-7f7069bc9b8f)
![20240312233053_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/46783282/0fbef4fb-d074-464a-b8ef-da315f0ecc8e)
![20240312233108_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/46783282/75c2d7a9-83c4-4020-a26d-ff72e1b2f86d)

Washing of tablets does the same thing as with a flashlight, only it takes away not a percentage, but the amount

Gold and silver cannot be washing, the chance of failure is 100% (or is it intended?)

**Comment by Oskutin** [comment]
Fixed
