### ISSUE TITLE
[Playtesting, migrated save, V. 0.3.35 V8] All my Tenants have vanished, and so has the kitchen.

### ISSUE THREAD

**Issue by Ludvig11** [loiste-interactive/Obenseuer-Issues#1890]
![20240313185804_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/31344357/dcf5c7b2-1667-42d0-aff2-83e458425da5)
![20240313185843_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/31344357/baaf9679-6cce-4453-9d1d-0eb72d465001)
![20240313185847_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/31344357/9d5e6231-1d8e-45ba-8085-0fe6dd3d203a)
![20240313185641_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/31344357/87b247ac-b407-41c3-b4d3-590a3c6ac342)
[Tenants-Gone_Lumi_Pakkanen.zip](https://github.com/loiste-interactive/Obenseuer-Issues/files/14591844/Tenants-Gone_Lumi_Pakkanen.zip)

**Comment by Z-O-M-B-I-E** [comment]
I have the same

**Comment by Zuntti** [comment]
Fixed
