### ISSUE TITLE
Playtesting - [0.3.35] Liquids duplication/Containers exceeding max capacity

### ISSUE THREAD

**Issue by gaberenest** [loiste-interactive/Obenseuer-Issues#1891]
Empty liquid containers will always be filled to their maximum capacity through swapping liquid containers in the inventory. This can also result in containers exceeding their capacity limit. 
![20240313135714_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/32476007/bae825b0-34d1-4b93-8c42-5f94aed8d945)

Bottom row of the chest inventory has plastic canisters exceeding 20 liters.

**Comment by Zuntti** [comment]
Fixed
