### ISSUE TITLE
Playtesting - tollgate fence clipping into pathway

### ISSUE THREAD

**Issue by pinkamedic** [loiste-interactive/Obenseuer-Issues#1894]
![Screenshot 2024-03-13 070713](https://github.com/loiste-interactive/Obenseuer-Issues/assets/151697489/5931fbac-bbbf-47ec-a7a6-84a7b6f220d0)
![Screenshot 2024-03-13 070721](https://github.com/loiste-interactive/Obenseuer-Issues/assets/151697489/1e069998-f471-4893-a4f2-1228cfac0ed9)

**Comment by Zuntti** [comment]
Fixed
