### ISSUE TITLE
Furniture Previews cluttered by Bottles

### ISSUE THREAD

**Issue by snortico** [loiste-interactive/Obenseuer-Issues#1896]
See screenshot. I wonder if this might be related to a migrating playtest save, but this is just speculation. Has persisted through game restarts and loads.
[Slot10.zip](https://github.com/loiste-interactive/Obenseuer-Issues/files/14605874/Slot10.zip)
![Screenshot (164)](https://github.com/loiste-interactive/Obenseuer-Issues/assets/112534082/934d89af-ed6d-40be-bcda-00b372fbd398)

**Comment by Zuntti** [comment]
Fixed the reason that causes it (except that the bottles remain in that save if they are not collected or destroyed by console command)
