### ISSUE TITLE
Some recipes not in inventory, crafting stations

### ISSUE THREAD

**Issue by snortico** [loiste-interactive/Obenseuer-Issues#1899]
Not sure the total list of affected recipes. I know I received a pontikka recipe in the mail and it does not show on any of the crafting stations nor in my inventory, so I would only know how to make it via experimentation. 

I have very many recipes, so not sure if this is specific to "certain recipes do not show up" or of it is potentially "recipe list is 'full'"
[Slot10.zip](https://github.com/loiste-interactive/Obenseuer-Issues/files/14606654/Slot10.zip)

**Comment by snortico** [comment]
I might be confused. Is Pontikka = Moonshine?

**Comment by Zuntti** [comment]
Fixed
