### ISSUE TITLE
When dropping an item, the icon stays on the screen

### ISSUE THREAD

**Issue by TiaLinna** [loiste-interactive/Obenseuer-Issues#19]
![20230413180611_1](https://user-images.githubusercontent.com/130680276/231803507-9a640ed5-a038-4c77-8115-45e893874681.jpg)

and it claims that inventory is full (if dropping from full inventory)

**Comment by Oskutin** [comment]
Can't reproduce this

**Comment by Oskutin** [comment]
Duplicate of this: https://github.com/loiste-interactive/Obenseuer-Issues/issues/134
