### ISSUE TITLE
Getting Hanss's keys, moving to another map (Deekula B) before unlocking the transition doors, and then coming back to the Mines Entrance, prevents player from unlocking the doors.

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#190]
https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/0b088c0a-89e2-4929-9152-2ef333a4ade7

Reloading the game seems to cause it too.

**Comment by Oskutin** [comment]
Seems to affect all unlockable doors.

**Comment by Oskutin** [comment]
Fixed
