### ISSUE TITLE
Drawers, cupboards losing contents.

### ISSUE THREAD

**Issue by robmurg** [loiste-interactive/Obenseuer-Issues#1900]
Sometimes on returning to the apartment items previously placed in cupboards or drawers have vanished.

I can recreate this as follows:
Place a cupboard (tested with a bathroom cabinet) that was cleaned from one of the apartments while still containing items.
Add more items from your inventory.
Save the game. Reload the save.
The cupboard is now empty.

If you do the same but first empty the cupboard of all previous items it seems to be OK and keeps your items as expected.

**Comment by Zuntti** [comment]
Not sure if it's the same bug but I managed to recreate it when I save the game while the bathroom cabinet is in the inventory. I fixed that

**Comment by Zuntti** [comment]
Can I get a save where you can recreate it as you described?

**Comment by robmurg** [comment]
This is the save I was working from. 
There's another quirk where you sometimes have to leave and re-enter the apartment (just walk through the door and return) to get the 'L' menu to work but maybe unrelated, just in case that affects anything.
[Slot3.zip](https://github.com/loiste-interactive/Obenseuer-Issues/files/14613427/Slot3.zip)

**Comment by Zuntti** [comment]
Seems to be the same bug
