### ISSUE TITLE
Suggestion-Make Penti pay more for mash

### ISSUE THREAD

**Issue by Taco-Cat1** [loiste-interactive/Obenseuer-Issues#1905]
I don't know if this was a bug but I had an 8 liter bucket of beer mash and Penti only bought it for 1.80 RM, kind of like a scam.

**Comment by Oskutin** [comment]
It was already increased. And the reason for low price was probably quality of the mash

**Comment by Taco-Cat1** [comment]
Thanks for letting me know

**Comment by Taco-Cat1** [comment]
Oh by the way I feel like he should give back the container, he kind of just took it.
