### ISSUE TITLE
[Bug] Clipping through staircase.

### ISSUE THREAD

**Issue by Taco-Cat1** [loiste-interactive/Obenseuer-Issues#1909]
Some staircases are easier to clip through then others. The easiest one is in the Bergman Tunnels where all you need to do is un crouch under them. Also if you save your game while crouched, you will be un crouched when you load it again which poses an issue in vents and crawl spaces. I not sure if you can clip through every staircase and this is a minor glitch but it is still weird.

**Comment by Oskutin** [comment]
fixed
