### ISSUE TITLE
Deekula A, missing models and icons of blueprinted items in workshop.

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#191]
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/02f3584d-7f36-4b80-b112-34782e4df381)
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/9f24fcd1-fa75-4be4-ac4b-28c3019ebd82)

**Comment by Oskutin** [comment]
Propably a save issue

**Comment by Zuntti** [comment]
Fixed
