### ISSUE TITLE
[Bug] Wrong indicator

### ISSUE THREAD

**Issue by Taco-Cat1** [loiste-interactive/Obenseuer-Issues#1911]
Maybe the title isn’t so helpful so here is the breakdown. Let’s say you use a microwave and then you enter a new loading area (eg. Deeluka B to Playerment) and interact with say… a sink. It will display the power icon where you can “turn on” the sink even if it’s makeshift. Exiting and re using it seems to fix the issue though. A similar issue also occurs with Mr.Bag. If you talk to him and he says he’s closed, talking to him the next day he will start by saying he’s closed. Talking to Jim’s seems to fix the issue

**Comment by Zuntti** [comment]
Can I get save where this happens?

**Comment by Taco-Cat1** [comment]
As far as I can tell, it works in all saves and might of gotten worse as the power icon appears in rat cages and inflatable pools, I don't know how to give you a my save (if that's even possible) so you might just need to find it yourself. Also, it's been a while since I've been to Mr. Bag so I don't know if it's been patches. Sorry for replying late, my github was broken for a while.

**Comment by TonyFromRomania** [comment]
to give the devs the save you firstly need to .zip it then post it (on the discord server was for me tho)

**Comment by TonyFromRomania** [comment]
Compress a file or folder: Control-click it, then choose Compress from the shortcut menu. If you compress a single item, the compressed file has the name of the original item with the .zip extension.

**Comment by TonyFromRomania** [comment]
but also having winrar could work too

**Comment by Taco-Cat1** [comment]
Where would I find the files. As I said I'm new to windows (Sorry)

**Comment by TonyFromRomania** [comment]
go into "This Pc/Disk C/Users/'your pc profile name here'/AppData/LocalKow/Loiste Ineractive/Obenseuer/Saves

**Comment by TonyFromRomania** [comment]
for more i info you can contact me on the Game's Server (i am the Broke electrician guy)

**Comment by Taco-Cat1** [comment]
I think I found you are you Broke Electrician or do you have guy at the end of your display name

**Comment by Taco-Cat1** [comment]
Here is a screen shot of this happening
![20240411132416_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/163670936/80fd29a5-6786-45ba-8bad-7d22aedb7127)
