### ISSUE TITLE
Powered crafting stations no longer showing appropriate state 

### ISSUE THREAD

**Issue by snortico** [loiste-interactive/Obenseuer-Issues#1913]
Powered crafting stations (Lathe, gas furnace, microwave) no longer show lights or play sounds that they are powered on. The state changes in the UI, it just does not reflect on the model.

This is on a migrated save from playtests, have not tried to recreate it yet on a new save.

**Comment by snortico** [comment]
The state does change - it seems like if something is left in a state, exiting and leaving the playerment might refresh the state?

**Comment by Zuntti** [comment]
Fixed
