### ISSUE TITLE
Backpack is still usable even after having been taken during sleep

### ISSUE THREAD

**Issue by arsentical** [loiste-interactive/Obenseuer-Issues#1917]
Or as I like to call it, Schrodinger's backpack.

I had a backpack full of stuff. Upon going to sleep, it appears my backpack was robbed from me, but I can still "open" it and access the items inside anyhow. This remains true, no matter how many times I open my inventory, until I reload the save file (at which point the ghost backpack is gone). The bed I slept in was an "Aching, Unsafe" bed (Shabby Bed Frame + Mattress) in my apartment.

![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/57933332/deb485cb-f68c-47ce-bec9-5ca4ab4308b0)
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/57933332/345cb7c4-5539-4e7c-b9d3-9281542049dd)

Presumably, steps to recreate are:
1. Get a backpack and equip it
2. Place items in it?
3. Sleep in an unsafe bed
4. Have your backpack stolen during the night
5. Open your inventory

(This log file also contains stuff from the hour or two of otherwise normal gameplay before I experienced the bug)
[Player.log](https://github.com/loiste-interactive/Obenseuer-Issues/files/14687088/Player.log)

v0.3.37

**Comment by Zuntti** [comment]
Fixed
