### ISSUE TITLE
found that tis candle stais lit even when i turn it off

### ISSUE THREAD

**Issue by TonyFromRomania** [loiste-interactive/Obenseuer-Issues#1918]
![20240321232019_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/157300727/12e22320-da95-4495-a2a8-c356dab3fce3)
![20240321232014_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/157300727/ff680756-d601-4cb3-bdb4-ad912cdc59ac)

**Comment by Zuntti** [comment]
Fixed
