### ISSUE TITLE
When unlocking a transition doors (from Mines Entrance in this example), when going to the next map (Deekula A), the doors behind us are still locked and need to be unlocked.

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#192]

**Comment by Nextej** [comment]
Get Hanss' keys
Go to unlock Deekula A doors
Transit to Deekula A map
Turn around to see the doors are locked, while they logically supposed to be unlocked.

**Comment by Oskutin** [comment]
Could be intentional, as many doors backlock themselves upon closing

**Comment by Nextej** [comment]
It seems very illogical, inconsistent and misleading and it rather seems like there's no logic that tells the other map that the other side of those doors supposed to match the state from the previous map.

**Comment by Oskutin** [comment]
So it's says it's unlocked when you go back to the other map?

**Comment by Nextej** [comment]
It says locked, while it should say unlocked, because, well, you've just unlocked them, passed through them, while why they suddenly be locked again since no other doors so far do this. What I meant that it seems what when unlocking a door on Mine Entr, the game doesn't tell the Deekula A map that it should also change state of doors from locked to unlocked to match the state of the same doors on Mine Entr.

**Comment by Nextej** [comment]
Here, so we're clear onto what's going on
https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/84956782-cc06-4dc4-9930-9a063c8a204b
It's not even the question on whether the door always lock up behind us, it's the issue of that they never unlock by themselves in the first place, after the unlocking them from the other side, they stay that way

**Comment by Zuntti** [comment]
Fixed
