### ISSUE TITLE
Playtesting - [0.3.38] Fenella Hunt redundant dialogue

### ISSUE THREAD

**Issue by gaberenest** [loiste-interactive/Obenseuer-Issues#1920]
After Fenella moves into the tenement building and is spoken to, you can attempt to rent her an apartment again. 
![20240322010354_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/32476007/c9ae4223-6eb2-40b2-8768-36e2b1ebb52c)

**Comment by Zuntti** [comment]
Fixed
