### ISSUE TITLE
Playtesting - [0.3.38] Hall Kääbus reappeared in hostel

### ISSUE THREAD

**Issue by gaberenest** [loiste-interactive/Obenseuer-Issues#1922]
After Kirka and Hall Kääbus finish moving into the tenement, a second Hall appears in his place at the hostel. 
![20240322020121_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/32476007/dd006721-65b7-450f-ad64-0d950bb668a0)
(Hall 2 pictured on right)

**Comment by Zuntti** [comment]
Fixed
