### ISSUE TITLE
Playtesting - [0.3.38] Dishwasher cleaning issues 

### ISSUE THREAD

**Issue by gaberenest** [loiste-interactive/Obenseuer-Issues#1923]
There are some items; to list a few: sugar, acetylene tanks, or cheese that cannot be cleaned in a dishwasher. 
Furthermore, stolen pill bottles on their last use will not be used in the cleaning process, effectively duplicating the item.  
Lastly, the grid size is inconsistent for the 2 dishwashers in my basement. One is a 1x3 grid, the other is 3x3. 

![20240321204830_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/32476007/7b6e5e56-bb4f-4332-b35b-59c055e7f688)

**Comment by Zuntti** [comment]
It seems that food and liquid are not allowed to be washed in the dishwasher. Not sure about the gas bottle.

Slot amount was changed, so the old dishwashers still have a 1x3 grid.

**Comment by Oskutin** [comment]
Food and liquids are intentionally prohibited.
