### ISSUE TITLE
issue found back in 0.3.33 but forgot about it and though someone else also found it after 0.3.35

### ISSUE THREAD

**Issue by TonyFromRomania** [loiste-interactive/Obenseuer-Issues#1924]
![20240322192451_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/157300727/a82aa4b5-650c-4538-afe9-21a2b82f895e)
![20240322192455_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/157300727/924c64c3-96bb-4b9e-b96e-c37fa90e2ab4)
![20240322192553_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/157300727/b03018fe-03e6-421a-af8c-a751b2e10aa4)
save file was given a while back but if you want the save again i can provide it again

**Comment by Zuntti** [comment]
Fixed
