### ISSUE TITLE
[Bug] Health stuck at 65%

### ISSUE THREAD

**Issue by PRS93** [loiste-interactive/Obenseuer-Issues#1925]
Seems no matter what you do, health will be stuck at 65%, this happened out of nowhere, I was not hurt by anything, didn't eat something bad etc, was just exchanging OC for RM at the machine when the health icon showed up.
I've tried painkillers, perscription painkillers, band aids, bandages, went to the doctor and tried all options available
Even tried using commands to fix this, but nothing works, if I use the command to set amount to regenerate back to 0 and then health back to 100, it goes back to 65%

**Comment by Oskutin** [comment]
caused by SMV
