### ISSUE TITLE
Icon for Milk Carton and Empty Milk Carton are confusingly similar

### ISSUE THREAD

**Issue by TheSofox** [loiste-interactive/Obenseuer-Issues#1927]
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/3089525/a708bf6c-3adb-4f3f-befe-53e7353aaa63)

Perhaps tilting the empty milk carton, like done for other empty bottles, would help people more easily determine whether a carton is full or not.

**Comment by Zuntti** [comment]
Fixed
