### ISSUE TITLE
Decent Stairwell has broken directory placement

### ISSUE THREAD

**Issue by snortico** [loiste-interactive/Obenseuer-Issues#1928]
The directory is correctly spawned/placed and updated in the shabby stairwell upgrade, but upon upgrading to the decent stairwell, it moves to an incorrect position in the floor of apartment 3 (Floor 2 medium). See screenshots.

![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/112534082/f35824cb-0173-4d1b-a616-394d43999850)
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/112534082/f1ed3b3e-5b62-46bd-9415-315b5c635961)

**Comment by Zuntti** [comment]
Fixed
