### ISSUE TITLE
Stolland clock clipping placement issue

### ISSUE THREAD

**Issue by snortico** [loiste-interactive/Obenseuer-Issues#1929]
Placing the Stolland clock on the wall is very difficult: It appears like there is some edge on the back of the clock that clips with walls. If placed with the left edge of the clock hanging off the edge of a wall, it has no collision issues. Trying to place it on the center of a wall is prevented in most spots. This was attempted with Decent apartment walls.

**Comment by greensalt99** [comment]
https://github.com/loiste-interactive/Obenseuer-Issues/issues/1924
