### ISSUE TITLE
[0.3.38 -> 0.3.39 Playtesting] Subtitle shows Mirjam Freighter instead of Eliana Passmore 

### ISSUE THREAD

**Issue by binbows** [loiste-interactive/Obenseuer-Issues#1939]
![20240423180311_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/87271815/7398510f-f9f6-4d40-96e3-1cb63fe5b0a5)

Minor detail.
This happened after you visit the City Gates and tell Eliana what you found. It also occurs on the following subtitles.
This was done on a save that was migrated from version [0.3.38] to the new playtesting version [0.3.39]

**Comment by Zuntti** [comment]
Fixed
