### ISSUE TITLE
playtest - brick furnace not using fuel from gas bottles after leaving and returning 

### ISSUE THREAD

**Issue by pinkamedic** [loiste-interactive/Obenseuer-Issues#1950]
if you start the brick furnace it will use fuel at the start but if you leave the building and then return the brick fuance will keep running but not use any fuel from the gas bottles

**Comment by pinkamedic** [comment]
same goes for the gas furnace

**Comment by Oskutin** [comment]
Effectively same as: https://github.com/loiste-interactive/Obenseuer-Issues/issues/1954
