### ISSUE TITLE
[Playtest] Lonkka does not buy vegetables

### ISSUE THREAD

**Issue by Z-O-M-B-I-E** [loiste-interactive/Obenseuer-Issues#1956]
But he buys building materials

![20240429194143_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/46783282/b3445985-db86-42b6-90a8-8a5ca647e77d)
![20240429194149_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/46783282/41e14633-9be7-4fe5-8af4-009bf01c6c29)

**Comment by pinkamedic** [comment]
this isint a bug he does not buy veggies but the lady in the stall does

**Comment by Z-O-M-B-I-E** [comment]
> this isint a bug he does not buy veggies but the lady in the stall does

She has very little money. Therefore, she has practically nothing to sell

**Comment by Zuntti** [comment]
Fixed
