### ISSUE TITLE
[Playtest] Deekula C bug

### ISSUE THREAD

**Issue by Z-O-M-B-I-E** [loiste-interactive/Obenseuer-Issues#1957]
![20240428185324_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/46783282/98edee33-ee54-442a-99f8-7fe725c36ecb)
![20240428185333_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/46783282/a574a0e2-6910-4c1c-bdbd-99c6920f5080)

**Comment by Oskutin** [comment]
This requires savegame

**Comment by Z-O-M-B-I-E** [comment]
> This requires savegame

[Slot1.zip](https://github.com/loiste-interactive/Obenseuer-Issues/files/15179295/Slot1.zip)

**Comment by Zuntti** [comment]
Fixed
