### ISSUE TITLE
Playtest - Mashing Kettle Capacity is shown incorrectly

### ISSUE THREAD

**Issue by CVariable** [loiste-interactive/Obenseuer-Issues#1959]
![grafik](https://github.com/loiste-interactive/Obenseuer-Issues/assets/45665371/500f823b-2b86-460f-b7d0-2825a338b51c)
The mashing kettle claims to only have 1L of space. The fermentation container shows 50L, which is correct.

**Comment by Zuntti** [comment]
Fixed
