### ISSUE TITLE
Staircase lights turn off if the b1 door is closed

### ISSUE THREAD

**Issue by ontrigger** [loiste-interactive/Obenseuer-Issues#196]
https://github.com/loiste-interactive/Obenseuer-Issues/assets/8556074/c7e22d2e-2205-4552-acb4-dcaf9ff6e62d

**Comment by Oskutin** [comment]
Can't reproduce

**Comment by ontrigger** [comment]
https://github.com/loiste-interactive/Obenseuer-Issues/assets/8556074/8dfeec4c-2486-4375-85bf-147346ff6fb7

**Comment by Oskutin** [comment]
Fixed
