### ISSUE TITLE
Playtest - Prison / Police deletes non-stolen Backpack and content

### ISSUE THREAD

**Issue by CVariable** [loiste-interactive/Obenseuer-Issues#1960]
I turned myself in to the police, wearing my backpack and having some stuff in the inventory. After being released, the normal inventory stuff was in the prison locker, but the backpack and its contents were neither in the locker nor dropped at the spot where i was arrested.

Save before turning myself in:
[Slot1.zip](https://github.com/loiste-interactive/Obenseuer-Issues/files/15170640/Slot1.zip)

Save right after prison time ended:
[Slot8.zip](https://github.com/loiste-interactive/Obenseuer-Issues/files/15170647/Slot8.zip)

**Comment by Zuntti** [comment]
Fixed
