### ISSUE TITLE
Playtest / Bug: Level 2 & 3 Greenhouses cannot plant seeds

### ISSUE THREAD

**Issue by jmnavamuel** [loiste-interactive/Obenseuer-Issues#1966]
Running playtest version 0.3.39.

After the update, cannnot get seeds planted (in any kind of pot), 'cause the sun indicator is not showing, as they weren't getting sunlight. The humidy indicator is properly showing.
![Greenhouse Lvl2 - No Sun Bug](https://github.com/loiste-interactive/Obenseuer-Issues/assets/15030538/6a090ff0-e4f6-4b7a-9cf7-2de9b06b0296)
![Greenhouse Lvl3 - No Sun Bug](https://github.com/loiste-interactive/Obenseuer-Issues/assets/15030538/fd2c8a80-f9df-429a-97ba-b7d8770b9860)

**Comment by Zuntti** [comment]
Related to https://github.com/loiste-interactive/Obenseuer-Issues/issues/2123
