### ISSUE TITLE
[Bug] Dr. Pena MD no longer asks for your turn slip

### ISSUE THREAD

**Issue by Taco-Cat1** [loiste-interactive/Obenseuer-Issues#1969]
While you still do need to take a turn slip in order for the door to unlock, Dr, Peena MD no longer asks for it to treat you. Instead, the I still need something promt comes up.

**Comment by DragonZephyr** [comment]
This seems to be only after you did the dialogue with him for the first time for the slip. On a new game in *.*.38 Peena asks for the slip once then never again. If intentional its confusing that it still makes you draw a new number later

**Comment by Taco-Cat1** [comment]
Yeah, I failed to mention that but seeing as this was never mentioned in the changes makes me think that its a bug
