### ISSUE TITLE
Adam is borked again

### ISSUE THREAD

**Issue by ontrigger** [loiste-interactive/Obenseuer-Issues#197]
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/8556074/6200790e-e24c-4966-b5a5-4b191783cbf3)

**Comment by ontrigger** [comment]
[Player.log](https://github.com/loiste-interactive/Obenseuer-Issues/files/11470222/Player.log)

**Comment by Oskutin** [comment]
Oh great

**Comment by Oskutin** [comment]
Dupe of https://github.com/loiste-interactive/Obenseuer-Issues/issues/187 ,which also explains the reason better
