### ISSUE TITLE
B3 lights get culled too early

### ISSUE THREAD

**Issue by ontrigger** [loiste-interactive/Obenseuer-Issues#198]
https://github.com/loiste-interactive/Obenseuer-Issues/assets/8556074/7216586c-0076-47c1-9903-faa3dccb687d

**Comment by ontrigger** [comment]
This stopped happening after I talked with Jakob and turned on the oil lamp, but now there are some errors in console
[Player.log](https://github.com/loiste-interactive/Obenseuer-Issues/files/11470230/Player.log)

**Comment by Oskutin** [comment]
Video is blank

**Comment by ontrigger** [comment]
Works on my machine
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/8556074/8268ed4e-4ee8-4f02-aef9-535fec23cc35)

**Comment by Oskutin** [comment]
Fixed
