### ISSUE TITLE
[Bug?] Apartment A13 in Kohola has a door that wont open

### ISSUE THREAD

**Issue by Taco-Cat1** [loiste-interactive/Obenseuer-Issues#1987]
Maybe this feature just hasn't been implemented yet, but in Kohola Apartment A13, there is a door that can't be opened, it's the door where the sand, concrete, absteos etc spawn. The door says it's unlocked, but interacting with it, while it does change the subtitles by saying open/close, the visual state of the door does not change.

![20240512095330_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/163670936/5920f624-5b23-415d-b18c-512909087d1a)
![20240512095321_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/163670936/6910f6e0-417d-4441-934d-ddee6cef11ac)

As you can see, the open/close prompt changes, but the door doesn't move.

**Comment by Oskutin** [comment]
Fixed
