### ISSUE TITLE
[Bug?] Liquids other than beer increase drinking skill

### ISSUE THREAD

**Issue by Taco-Cat1** [loiste-interactive/Obenseuer-Issues#1989]
This is most likely intentional and is a good feature for people who don't want to get drunk to increase their drinking skill, but liquids such as milk and water also increase the drinking skill. I hope this isn't a bug, but better safe than sorry

**Comment by Oskutin** [comment]
Can you confirm non-alcoholic drinks raising skill?

**Comment by Taco-Cat1** [comment]
I only got to drinking level three. I got to level when when drinking water, and level three when drinking milk. The water one was a few versions ago and the milk was this version. I'm now at drinking level 10 (using beer) so I can't test this anymore.
