### ISSUE TITLE
In relation to issue #141: More problems

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#199]
Now skipping an interaction with Priest by accessing B2 apartment does in-fact check off "Investigate the Priest's Apartment" as it would do while trying to interact with Priest, but now no new objective appears, normally we would have optional finding out what exactly happened or mandatory reporting back to Eliana.
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/e6a92887-ca89-425a-a08b-1dbee5a1a8ae)

**Comment by Oskutin** [comment]
@Zuntti could you check this one?

**Comment by Zuntti** [comment]
Fixed
