### ISSUE TITLE
[Minor] 0.3.38 Kohola A10 Sink only object not considered stealing from. 

### ISSUE THREAD

**Issue by DragonZephyr** [loiste-interactive/Obenseuer-Issues#1994]
![grafik](https://github.com/loiste-interactive/Obenseuer-Issues/assets/65025239/bb3cc42f-a139-49de-9382-9c66adc6be94)
Stands out like a sore thumb but could be intentional. I was wondering if during a burglarly any storage should ever be considered not theft or if its within design that some are just okay to take from. In most instances it is a trash bucket but this apartment does not have one so it is why i am unsure if its intentional.

**Comment by Oskutin** [comment]
Seems to work
