### ISSUE TITLE
[Minor] Kohola A7 Demon Summoning Appartment which was bricked up has object Adhesive bandage count as stolen. Wardrobe also counts as stealing.

### ISSUE THREAD

**Issue by DragonZephyr** [loiste-interactive/Obenseuer-Issues#1995]
![grafik](https://github.com/loiste-interactive/Obenseuer-Issues/assets/65025239/ac12710f-7748-4cbe-9a27-eb19c8da6b15)
Bandage might have been placed with wrong tag. Would look less out of place if the other drugs right next to it would also be marked as theft if intentional.
![grafik](https://github.com/loiste-interactive/Obenseuer-Issues/assets/65025239/3d098243-59ae-483b-9716-c24d935505f3)
Wardrobe in question which given the adhesive bandage might also have been placed with wrong tag but could be easily argued to be intentional.

**Comment by Oskutin** [comment]
Fixed
