### ISSUE TITLE
Fixed issues from before the update

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#200]
#81 is not applied
#83 is not applied
#170 visual state still counts the amount of taken slots instead of total amount of singular items in all stacks combined
#35 console doesn't remember commands from previous maps/savefile sessions; also as suggested by deseven, keep the typing window active after entering a command so you can immediately type another command

**Comment by Oskutin** [comment]
Pressing up key in console remembers the previous

**Comment by Oskutin** [comment]
170, it's new feature, the visual state bug has been fixed

**Comment by Nextej** [comment]
> Pressing up key in console remembers the previous

but only within the same map, if I've typed few commands on Deekula A and then moved to Mines Entrance, I won't be able to call the commands I've typed on Deekula A, same for all the commands typed before reloading a savefile
