### ISSUE TITLE
[Bug][Enhancement?] 0.3.38 Rats only attempt escape from player in certain levels while players can drop rats in any level.

### ISSUE THREAD

**Issue by DragonZephyr** [loiste-interactive/Obenseuer-Issues#2002]
Rats placed by Player
![grafik](https://github.com/loiste-interactive/Obenseuer-Issues/assets/65025239/c1cd8bb8-af3a-43a2-8250-27f1b56dbab3)
Rat part of level spawning
![grafik](https://github.com/loiste-interactive/Obenseuer-Issues/assets/65025239/70300894-b048-4baa-bba8-3ce64909eb79)

Bug:
Placing a rat by dropping it allows players to put rats into every level in the game, in certain areas however it seems that rats do not attempt to run away. In one instance in the Container Shack there is even a rat spawn next to the cage that places a rat there with no AI.
Either the nav map/nav mesh isnt there for AI in these levels yet or the AI for the rat is just missing. I saw there will be more animals in a future update so this might affect them too.

Suggestion/Enhancement:
For the Tenement i thought it was interesting that the rats do not move as you are likely to farm them there and might wanna keep a pet however they despawn upon level exit which shows this isnt intended.
It is also strange feeling that neither the Kohola rules forbid infesting with vermin nor that the Pharmacy does not comment they will report you to the police for dropping rats into their workplace especially since its a pharmacy. People might be used to rats in Obenseuer 
otherwise even the o-market has the occasional rat im sure.

Locations:
I tried walking to every level and meticulously checked if a rat would attempt to run away, these are the ones i have found with no Rat AI:
Container Shack, Wooden Shack, Tennement, Makeshift Sauna Room, Makeshift House (Wall to the Bazaar) and Skeida Pharmacy

**Comment by Oskutin** [comment]
added nav data to pharmacy

**Comment by Oskutin** [comment]
Added to canal saunas

**Comment by Oskutin** [comment]
Others seem to already have
