### ISSUE TITLE
[Typo] 0.3.38 uprooting a spoiled orange mushroom says plan instead of plant in interact description

### ISSUE THREAD

**Issue by DragonZephyr** [loiste-interactive/Obenseuer-Issues#2004]
![grafik](https://github.com/loiste-interactive/Obenseuer-Issues/assets/65025239/f22bf71b-c5a1-4dd4-b912-5c764eaf18a9)

Will check later if this is true for other _plans_

**Comment by DragonZephyr** [comment]
From my minor testing this seems to be only case i have found with a typo

**Comment by Zuntti** [comment]
Fixed
