### ISSUE TITLE
[Minor] 0.3.38 Reverse-Prison Escape/Prison Escape clip

### ISSUE THREAD

**Issue by DragonZephyr** [loiste-interactive/Obenseuer-Issues#2005]
Nearly identical to #644 and #573 
Pressing crouch sets player to uncrouch when they can which results in player uncrouching in unfortunate situation
![grafik](https://github.com/loiste-interactive/Obenseuer-Issues/assets/65025239/31154ac5-0749-4067-91ed-da12acc05d92)
Despite my best effort i only managed to clip very shortly and was teleported to the transition door for the area. Issue here is that its automatic with the uncrouching in this spot. Whatever decides that you get to uncrouch fails here

**Comment by Oskutin** [comment]
fixced
