### ISSUE TITLE
Playtesting - Interaction hitbox on some of the furniture should be adjusted

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#2014]
For instance here in the Bank's office, you can "open" the filling cabinet and the desk from the "wrong"/costumers side, I'm sure many cupboards/cabinets that clearly are being opened from one side only should be adjusted.
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/2c6e464a-2e8b-4269-9e9b-1c4b292f4378)
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/68295338-3125-4a2b-849a-d9b6d8fe4386)

**Comment by Taco-Cat1** [comment]
You can also open the cupboard in the hostel waroom from the wrong side

**Comment by Zuntti** [comment]
Fixed
