### ISSUE TITLE
[Typo] Achievements

### ISSUE THREAD

**Issue by Taco-Cat1** [loiste-interactive/Obenseuer-Issues#2019]
Some achievements on steam have typos. The first one is "Welcome to Obenseur" and its description is "Enter the Obenseur" The description has a typo, to fix this it should instead be changed to "Enter Obenseur" The other achievements with typos are the ones of Burglar points where their description is "Get a {low, medium, high} burglar points" to fix this typo remove the "a" after "Get". The last achievement I could find with a typo was the "Eternal November" achievement where its description is "Survive an year in Obenseur" to fix this typo "an" should be changed to "a"

**Comment by Zuntti** [comment]
Fixed
