### ISSUE TITLE
[Suggestion] Rename tin cans to steel cans

### ISSUE THREAD

**Issue by Taco-Cat1** [loiste-interactive/Obenseuer-Issues#2022]
Tin cans are a great item but considering that they can be used to make a steel bar is slightly confusing seeing as they aren’t the same metal. Renaming them to steel cans which where used in the past could help with the player experience.
Thanks :D

**Comment by Nextej** [comment]
I think it would be better to add a description of sorts of "Contrary to the popular name, these cans are not made out of tin"

**Comment by Taco-Cat1** [comment]
Maybe change that to Contrary to the popular name, these cans are made out of steel

**Comment by Zuntti** [comment]
Added description
