### ISSUE TITLE
Mash Duplication

### ISSUE THREAD

**Issue by MikeGO2611** [loiste-interactive/Obenseuer-Issues#2035]
Using a Mashing Kettle that is already filled, putting a "Turnip Mash in a plastic bottle" that is already filled in the slot, and pressing the fill button makes the bottle stack to reach a "weird" number.

![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/9802509/3600d79c-beaf-41d6-a35b-301c5ca658cc)

**Comment by MikeGO2611** [comment]
Also, the amount of mash in the kettle increases.

**Comment by Zuntti** [comment]
Already fixed
