### ISSUE TITLE
Finished task "Who lives in the basement" duplicating itself

### ISSUE THREAD

**Issue by KETALss** [loiste-interactive/Obenseuer-Issues#204]
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/81901907/5b863ae7-1ad6-46ca-ab1e-19ef88c2605e)
after finishing this task it duplicates itself by some amount in finished tasks tab

**Comment by Oskutin** [comment]
Did this happen at once, or after changing level?

**Comment by KETALss** [comment]
haven't noticed when it appeared
[Globals.txt](https://github.com/loiste-interactive/Obenseuer-Issues/files/11473904/Globals.txt)
not sure if this is right save file (converted to .txt because github doesn't accepts og filename)

**Comment by Nextej** [comment]
It seems to happen every time with level change, the same applies to tenement contracts tasks (other tasks don't seem to be affected), the amount is so high it freezes the game even up to a minute after switching to Task tab, not to mention previewing one of the tasks (not necessary the duplicates).

**Comment by Zuntti** [comment]
Fixed
