### ISSUE TITLE
Playtesting | O-Market Hot Dog Stacking Glitch

### ISSUE THREAD

**Issue by Orphiex** [loiste-interactive/Obenseuer-Issues#2060]
Basically, when in the O-Market, opening up the fridge labeled "Refrigerator (Weiners) and pressing the "Sort" button causes all of the Hot Dog Weiner packs to be ejected from the fridge and scattered around the O-Market.

This seems to be the same problem as mentioned in [issue #1252](https://github.com/loiste-interactive/Obenseuer-Issues/issues/1252), but I've tested all of the fridges and unlike that issue, it only seems to happen to the Hot Dog Weiner Packs. This is a repeatable glitch, occurring in both prior and current versions (ver. 0.3.39 and V2).

**Comment by Oskutin** [comment]
Fixed
