### ISSUE TITLE
Playtesting - When a held flashlight is turned on and its battery reaches 0%, reloading the flashlight makes it turned on while retaining indefinate 100% of the battery.

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#2065]
How to recreate:
1. Equip and turn on flashlight
2. Let it deplete its battery to 0% while the light is still on
3. Reload (and don't press anything else, let the animation finish so the flashlight turns itself on)
4. Battery is indefinate until player turns the flashlight off and on

**Comment by Oskutin** [comment]
fixed
