### ISSUE TITLE
Playtesting - Intro issues

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#2073]
1. Fade-ins, Fade-outs take too long
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/da1ec3fd-a1d5-49d6-a549-9dd861096aa5)
2. "Open Sewer" title does not disappear
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/c9036e29-a221-4968-9277-723a389260c5)

**Comment by Zuntti** [comment]
Fixed
