### ISSUE TITLE
Playtesting - Player can order Open Sewer and Swamp magizines before even knowing the address (before acquiring the tenement blueprint)

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#2075]
Either make the only dialogue option being something like "I don't know yet" until player gets the Tenement Blueprint and/or add 2-3 fake addresses to guess like with the passwords, so the player actually has to check the Tenement Blueprint and memorise the password, if you'll go with the latter, perhaps you should be able to ask malone where to find an address of this place.

**Comment by Zuntti** [comment]
Added
