### ISSUE TITLE
Playtesting - Placing cats with the building menu is broken

### ISSUE THREAD

**Issue by mattiskung** [loiste-interactive/Obenseuer-Issues#2077]
When bring up Your Cat in the build menu it falls straight to the map and into the void. Placing it brings it back up again.
![20240531165543_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/77937586/e60bc3e6-5b6b-42d7-892f-a20b42829b2f)
![20240531165555_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/77937586/881f840c-5455-4ad6-a62a-9cfcc3473fef)

Edit: The issue below doesn't appear as cat was spawned in
Regular cats don't have this issue but they have another problem. When placing regular cats they turn 90 degrees and become a wee bit bigger. You can't pick them back up so they are stuck there forever. They don't either have any animations
![20240531164542_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/77937586/48340f9a-7fef-4abf-ae77-1aceabdcdf22)
![20240531165412_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/77937586/c2afb788-10f0-481c-ab88-5c060f95732f)

v0.3.39 V2

**Comment by Nextej** [comment]
Same applies to rats with the first issue, for the regular cats, mattiskung most likely spawned themselves a cat category item instead of an actual cat, the cat category item is motionless and has no behaviour like regular or owned cats.

**Comment by mattiskung** [comment]
> Same applies to rats with the first issue, for the regular cats, mattiskung most likely spawned themselves a cat category item instead of an actual cat, the cat category item is motionless and has no behaviour like regular or owned cats.

Ah ok then, well sorry for reporting a issue which didnt really exist

**Comment by Zuntti** [comment]
Fixed
