### ISSUE TITLE
Tenement upgrade UI suggestions

### ISSUE THREAD

**Issue by ontrigger** [loiste-interactive/Obenseuer-Issues#208]
1. Show how much of a resource you have in the upgrade UI.
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/8556074/d0ddf032-2550-4ca2-afad-32c9eb16b9d0)
2. Allow clicking on the building schematics to quickly (and visually) select the part of the building you'd like to upgrade
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/8556074/7e298bba-9d80-4292-ad00-04dad7e0db63)

**Comment by Zuntti** [comment]
Added the building schematics buttons.
