### ISSUE TITLE
Playtest - Tenement A Apartment A6 upper floor, bathroom collision between bathtub and opening door

### ISSUE THREAD

**Issue by CVariable** [loiste-interactive/Obenseuer-Issues#2096]
![grafik](https://github.com/loiste-interactive/Obenseuer-Issues/assets/45665371/40d915be-8ebf-440e-bcf6-2055ba3bc379)
The door opens into the tub in the upper bathroom of A6.

**Comment by Zuntti** [comment]
Fixed
