### ISSUE TITLE
Playtesting - Bank of Bazaar, when giving Passmore the gathered loot from the bank, Passmore gives you only 1 OC, instead of giving the promised half of all stolen items' value

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#2100]
Before the talk:
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/e37cfd47-fb16-4093-9f8e-059a3b60795a)
After:
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/461c2320-7249-4ee8-8b75-7e933e76bdf2)
(remaining stolen items were not marked as owned by Bazaar Bank)

**Comment by Zuntti** [comment]
Fixed
