### ISSUE TITLE
Tunnel detailing abruptly stops in the northern and southern tunnels in Bergmann's

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#2104]
North:
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/7572b847-2779-4eab-8f9c-398cc689d0a1)
South:
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/44c54444-98c6-4360-a8ac-dcced15315ab)
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/7f6ffb9d-9459-4d8c-8727-471e7c437dcd)

**Comment by Oskutin** [comment]
Fixed
