### ISSUE TITLE
Playtesting - When wielding a dosimeter in hand, you cannot interact with various objects around eye-level.

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#2110]
The area marked below cannot be interacted with to open the door, only above or below that area I can interact, same applies to buttons, storages, etc.
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/fbe47e63-0731-4e7e-bc4b-ec60a75ebc6a)

**Comment by Zuntti** [comment]
Fixed
