### ISSUE TITLE
new machinery got the owned tag after doing renovation of the apartment wall

### ISSUE THREAD

**Issue by TonyFromRomania** [loiste-interactive/Obenseuer-Issues#2113]
![20240601142157_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/157300727/a892410a-98bd-40b0-b610-7717f6ad309f)
![20240601142153_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/157300727/3e2a3ad5-1663-4785-8798-4dc27d62aafe)

**Comment by Zuntti** [comment]
Fixed
