### ISSUE TITLE
Playtesting - It's weird that the Tenement A has technically two separate basements that are not connected at all, I think it would be neat if you could access Speakeasy bar from the Tenement A service area.

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#2114]
I think this could be a good spot to add transition doors to Speakeasy, perhaps the 'Tenement B keys' you get from the office could unlock those gated doors at the Speakeasy level
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/602def60-0deb-4ed6-bbc3-1a003937a701)
I also think it may be beneficial to have a shortcut from Tenement A to Speakeasy directly, without one additional loading screen.

**Comment by ProfRadis** [comment]
![20240601192900_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/167462213/3eeecb98-9121-478f-b73e-07ba8d326591)

**Comment by ProfRadis** [comment]
this metal door in center is to the basement

**Comment by Nextej** [comment]
It is not, it's a secret location that gives you freezer-backpack and a chicken

**Comment by Zuntti** [comment]
Added
