### ISSUE TITLE
Playtesting - Working at shroomlight factory should have a chance of giving a small amount of SMV per hour

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#2115]
I would expect someone who does a manual labor around shrooms without any protection to development an SMV within several weeks.

So I'm thinking that per hour of each hours the player is working, there should be a random chance of get a set, small amount of SMV. I think that after a one or two whole days of work, the SMV on average should be enough to keep on growing if player is not taking care of themselves with countermeasures.

**Comment by Zuntti** [comment]
Added
