### ISSUE TITLE
Playtesting - Would be nice if the arrow meter was illuminated (perhaps stick some reflective tape to it) in the dark, otherwise it's hard to look for the otherside signal.

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#2118]
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/58e8e501-e69d-4bc9-853e-f24f69ac41e5)
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/38db9f37-51e8-496e-89ee-9958733c1cd4)

**Comment by Zuntti** [comment]
Added
