### ISSUE TITLE
Deekula A Storage: you can get behind the boxes without breaking them down.

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#212]
https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/ef9a5351-a987-4ce9-b8ce-064902c8d689

**Comment by Nextej** [comment]
I dunno yet

**Comment by Oskutin** [comment]
If yes, then this issue can be closed.

**Comment by Nextej** [comment]
If you try hard enough, you'll finally get out, but nonetheless, the whole area makes an impression that you should not be able to get in without axle/hammer to get to the goods inside.

**Comment by ontrigger** [comment]
You can get out, but yeah, it feels kind of unintended. Maybe make getting out a bit easier?

**Comment by Oskutin** [comment]
Fixed
