### ISSUE TITLE
Playtesting | Bug(?) | Greenhouse planters stuck with "Modifier: Moist"

### ISSUE THREAD

**Issue by Orphiex** [loiste-interactive/Obenseuer-Issues#2123]
My tenement has the level 3 greenhouse built, and in previous builds, planters placed there received the "Sun" modifier, as opposed to the "Moist" modifier from placing them indoors. However, since some point, planters in the greenhouse now only receive the "Moist" modifier, even if the time of day is around noon.

![20240602033510_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/16548338/45a35e22-ee2b-4873-9a3b-288e537abcd6)

Not sure if this is a bug, or simply a change in how the greenhouse works, but either way, thought I'd post it here.

**Comment by Zuntti** [comment]
Fixed
