### ISSUE TITLE
Missing rent dialogue with NPC's

### ISSUE THREAD

**Issue by Machvia** [loiste-interactive/Obenseuer-Issues#2124]
Tested on both an existing and new playtest file, NPCs no longer have the dialogue option to ask them to rent an apartment

**Comment by TonyFromRomania** [comment]
yea i got that bug as well reported it a day ago but the main dev that deals with checking in here is probably taking a break

**Comment by Orphiex** [comment]
Thirded; I evicted two tenants to rearrange the renting order, and now I can't fill those apartments anymore.

**Comment by Zuntti** [comment]
Fixed
