### ISSUE TITLE
Playtesting | Bug | Respawning money box

### ISSUE THREAD

**Issue by Orphiex** [loiste-interactive/Obenseuer-Issues#2125]
In the new version, I returned to my tenement flat to find a Plastic Storage Crate inside the door, containing 99 RM.

![20240602034401_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/16548338/248411f4-8c4f-4893-b2a6-129e284fb10f)

I assumed that this was a gift from the devs, so I cleared it out, took the Crate into my inventory, and moved on. The thing is, I then proceeded to save and reload the game without having left the tenement... and when I returned to the flat, the crate had respawned, complete with 99 RM, even though the first Plastic Storage Crate was in my inventory.

Checking the console after picking up the Crate showed the following error:
`Error: Furniture info was null!`

![20240602034907_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/16548338/7f381267-55f4-424c-9bfb-c409c67f0bad)

I've tested this in several configurations, and it appears that the Crate doesn't respawn if I remove the money but leave the crate; it only occurs when the crate is picked up. The respawn happens both when loading the game, and when leaving & re-entering the building. While I enjoy the idea of infinite free RM, I think this ought to be fixed.

**Comment by Taco-Cat1** [comment]
I have the same issue and while I don't want to cheat, I don't want to just leave it there
