### ISSUE TITLE
Moving between maps (and possibly reloading a savefile) causes some map objects to respawn like recipes or blue prints, possibly some predetermined pickable objects too.

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#213]

**Comment by Oskutin** [comment]
An you list the objects what do respawn?

**Comment by Nextej** [comment]
If you need an example to test, there's a recipe in storage B5 (the one right off the Deekula Basement exit) that should respawn each time you pick it up.

**Comment by Oskutin** [comment]
Seems to work on first load, but on second and that on it always spawns a new item.

**Comment by Oskutin** [comment]
Works now. It was a race condition on save load.
