### ISSUE TITLE
Playtesting - Tenement A: general level issues (listed per room)

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#2131]
I suggest just going chronologically from top to bottom, fixing things room-by-room

<h2>Basement: Utility areas</h2>

* In the same room as Lathe, behind a water tank there's a Sand Bag that's not marked as 'stealing'

![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/1a44ce9e-abd9-414d-a05a-0abb1e7fdd55)
* These 3 planks are not marked as 'stealing'

![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/a323b156-4628-4677-bc6b-137351351eee)
* This blueprint on the way to Tenement B is not marked as 'stealing'

![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/b170932e-a820-43d5-b498-2a10033490e4)
* These 3 planks on the way to Tenement B are not marked as 'stealing'

![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/611ffbda-3741-4e08-b0b5-5975cc160bd6)
* This barrel changes model to an entirely different skin on distance

![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/eb8eae18-8de1-490a-934a-daab1e6d06b1)
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/53085e49-cfd3-47fb-bddd-71de7d947b19)

* This key in the bathroom is not marked as 'stealing'

![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/4f92f58b-7ea6-4463-a318-50d4c46d2d2d)
* On this desk inside the control room, the Industrial Fuse and this recipe are not marked as 'stealing'

![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/717ad88c-8d07-44f8-a36a-7aeff7afc751)
* On the same desk, this fan cannot be turned on

![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/244a5b36-b5f3-4f17-adf3-88cc24703f3b)
* This key is not marked as 'stealing'

![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/8569b07b-d0ef-44e1-8401-15cdbce53015)
* Hitboxes of the large green machinery make it hard to pick up the dwarf plush

![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/7faf5e4e-c4ab-4f98-8f8e-9d01eafce789)
* The dwarf plush itself is not marked as 'stealing'

![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/08a00cb8-c0ff-4d64-8f94-84252648358c)
* In this room the blueprint, the cable and the toolbox are not marked as 'stealing'/'owned' respectively

![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/7c04e9fa-9bc3-41b3-8448-f58d2598260e)
* Looking through the vent doesn't render light behind it

![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/e90553cb-6de1-4276-bf49-3939b052cf4a)

<h2>Basement: Storage area</h2>

* There's a massive gap going all the way around the doors in the door frame between main hall and the storage area

![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/6e2061db-5c53-4bb7-b409-c08ea6a344f8)
* You can get stuck between Tool Cart and a wooden pallet in the far corner inside storage A4

![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/bf69dfb2-e844-4a98-83d2-98c6bb18e558)
* You can get stuck in a corner behind a bed frame in storage A6

![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/f09c6ff8-d0f7-4a40-865c-82f882192151)
* Issues with picking up 3 planks in storage A9 (hard to get "pick up" interaction to show up)

![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/12a86586-e9bb-4810-9ef7-91cf50e1f8cd)
<h2>Apartment A1</h2>

* When opening main entrance door, the light inside the apartment is not rendered until player steps in

![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/20d1cd0e-f6c2-45fe-8b70-d03f0d317ce2)
* Unpickable cleaning spray in the closet

![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/9a97ca7a-25f9-4a31-8986-ea8c73c5840d)
* In the bedroom, this alarmclock is not marked as 'stealing'

![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/bd512cb2-4ade-403f-b458-d0c6aea5836c)
* In the bedroom closet, this teddybear is not marked as 'stealing'

![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/8e32722f-5a7d-405d-bd42-f08fb44c76b7)
* In the hallway between the bedrooms, being at its end and looking into the livingroom doesn't render some of the livingroom's lights

![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/9ca2526d-712f-4de3-9895-894580e681d7)
* The bathroom door opens towards you, not away from you, regardless of the side

![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/4b8df935-3456-4ebb-a949-3f9216b07e27)
<h2>Apartment A2</h2>

* At the electronics station, this Laundry Detergent is not marked as 'stealing'

![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/a25f400c-2485-4ca5-8ef9-2090ce14dcdb)
* At the same table this oil lamp cannot be turned on

![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/723dfd0b-da80-4774-906b-6de53f76bc39)
* The electronics station is not marked as 'owned'

![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/4863b2ca-55f3-4f83-8545-5700ca1f0d64)
* These blueprints are not marked as 'stealing'

![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/723dfd0b-da80-4774-906b-6de53f76bc39)
* On the table in the middle all those bottles and cans are marked as 'stealing' despite the trash most of the time (and others in this room) is not marked as 'stealing'

![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/6d709364-4c01-41c0-8a1c-725467ad9aee)
* These cardboard boxes block movement (player hits the lamp with their head)

![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/d1f418d1-f834-40ca-9cb8-58c4849ea183)
* In the kitchen, despite a carrot being visible in 3d world, the carrot is not present in the planter's UI

![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/79db1126-9806-470a-bec6-453d804e4395)
* Bathroom door clips with a basked under the sink

![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/f3d61858-6a23-4c50-959b-b1e7be3f2da5)
* Sauna is not working, you can turn it on but neither the water splashes, nor thermometer raises, nor effects are present

![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/ff712d53-854f-48fd-a331-dd22297e29a3)
* Washing room, Laundry Detergent is not marked as 'stealing'

![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/db907f5a-4db0-43b3-84ab-be8bf3eaf804)
* Bedroom's closet, mirror has a wrong cubemap

![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/81fc43ec-4244-49a2-b766-5c4136d20514)
<h2>Apartment A3</h2>

* On this shelf there's a bunch of items that should be marked as 'stealing'

![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/d9da5fb1-ee10-4720-b683-9e02c06b21a4)
* This sack behind the shelf is not marked as 'stealing'

![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/f7091569-79b0-49f8-a65f-7c17952efb34)
* This plywood is not marked as 'stealing'

![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/29e19160-892a-4b58-a8ea-9cd8cdddf351)
* Sitting on this bench (all spots) snaps camera hard to the right

![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/a7bfb5d8-b5b7-47c2-9d1d-9756c9a772d1)
* In the kitchen, this recipe and this macaroni are not marked as 'stealing'

![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/f61aae5e-c300-485e-9f6b-d86aa8541cc2)
* When crossing this doorframe, facing this way, some lights in the first bedroom are not being rendered 

![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/2f2de06d-deba-47e2-a98a-5c00b119dbc5)
* Matchboxes in the second bedroom on a table are not marked as 'stealing'

![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/b98f2cdb-007c-4790-8eca-0d8c7a731a04)
* Recipe on top of this bed is not marked as 'stealing'

![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/577aac34-09fe-49ef-92bc-efedcdfd703f)
* In the bathroom, when sitting on this toilet the camera snaps hard to the right

![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/108a18d6-8924-4370-9a6a-a6b13f3f1b8c)
* Firewood under the sink is not marked as 'stealing'

![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/86ee02da-5698-451c-9107-38ce6a8e6b53)
* Sauna doors clip with the stool when opening 

![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/ae4b1953-4433-41f1-8e94-31c65441915e)
* Sauna is not working

![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/856b714c-e2fd-40e0-b2f9-7ffceff3e0b3)
* Bathroom next to the entrance door, Laundry Detergent is not marked as 'stealing'

![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/6ef99c22-887a-4a47-9932-25ead72a15b0)
* Bathroom door clip with the sink and the beercrate

![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/3e1826ae-0c27-48c9-baa6-cd0cd8f37030)
<h2>Apartment A4</h2>

* Standing in the marked red area makes the light in the hallway to not render 

![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/393ba02c-5358-49e3-9004-f9663153b4d9)
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/d61c2d45-8ec6-4eac-938f-f4134a5f92ba)
* This cage next to a ladder is not marked as 'owned'

![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/49d54090-cc2e-4cb7-bd1a-3ff85abbe41c)
* The canned cucumbers on the table are not marked as 'stealing'

![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/02cdab8f-1807-4642-bfce-ab7c4562fb75)
* This recipe on the kitchen counter is not marked as 'stealing'

![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/ed9f4bc5-95a9-4962-bdb4-8102e96ede57)
* There's a random plastic bottle with clean water in the middle of the bathroom

![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/a13e8e5a-ec00-4167-9c6f-1860a7651d60)
* The space between bathtub and the top rail is just slightly too small to fit underneath when standing

![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/840374d4-bfbf-419c-9704-545e1bf4f572)
* In the bedroom, sitting on this bench (all spots) snaps the camera hard to the right

![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/2d496a88-6a5a-4e44-b5f4-8a58c22a34ed)
<h2>Apartment A5</h2>

* The two large shroom growing cabinets have all of the shrooms spoiled from the start

![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/59360d68-c3db-4296-b8dd-8852ac757b83)
* The animated fan has wrong rotation

![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/6f4a5cf0-f09e-4fe5-b228-1c3c74ce4066)
* This bucket of paint is not marked as 'stealing'

![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/f49f0bac-3f01-4e56-bc1e-c5a1457cb9ca)
* This coffemaker doesn't have power, coffeemakers in kitchens like that usually have power despite their visual model always looking unpluged

![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/ebcccb9a-3e54-4840-914d-c8996b7bdce8)
* The injection machine has a little bit too large hitbox, making it harder to reach a toolbox on top of it

![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/1e59574c-d620-4613-b45a-ec6250010a7b)
* This pendrive on top of the Toolbox is not marked as 'stealing'

![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/962a88a3-73ec-4c49-9c7e-40cecba7c676)
* This beercrate of glass bottles is not interactable

![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/85be3196-6f1c-4e8c-8691-7dcea34e61e4)
* In the women's bathroom you can get stuck in the corner between toilet and the sink

![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/9e979f96-f05a-4648-a103-c835ddf8c51c)
<h2>Apartment A6</h2>

* A cup is stuck in the doorframe to the first room

![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/8ff06e4a-4d13-4815-8ec5-81957358e7e1)
* You can sit on the chair occupied by Johannesen, making you get stuck

![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/32a3deb1-6010-4db8-9602-8c98dc5bfc61)
* In the second room, these matches on a shelf cannot be picked up

![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/6c5132f8-1ffd-480c-b123-224aaa78ad12)
* In the same room, this clean water is not marked as 'stealing'

![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/e3c44206-4a94-4c83-ba6c-deae703340cb)
* This blueprint next to the third room is not marked as 'stealing'

![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/4789706f-2a9b-4ba0-9a5c-c4f0f3544efe)
* In the third room, this Clean water and the key are not marked as 'stealing'

![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/d6154a48-3240-4ba1-83cd-13bc5e942537)
* Underneath the staircase, you got to jump to get on to the matress instead of smooth transition

![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/3f60c187-b99f-4962-8b76-80eb7783e185)
* The sauna is not working (same as previous saunas)

![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/6cd25c20-9aad-48ee-83e5-53658a7b62f5)
* In the upstairs bathroom the door collide with the bathtub, it is also impossible to access the toilet there because of the doors

![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/3126a917-2a47-46f1-8560-e5674ffbb37e)
* This disinfectant in the upstairs bathrooms is not marked as 'stealing'

![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/13df5c52-4183-4a08-90a7-f4c817b63bff)
* Standing along this wall disables light rendering

![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/e9aeea88-8431-4957-9c8b-7ca983effe24)
* The space between the tub and the top rail is slightly too small to fit player standing

![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/ebd13e48-900c-4f82-bee2-ebc76c1553de)
* Sitting on this toilet snaps camera hard to the right

![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/4ec90a29-d75f-4c63-a215-c11bdba4dc79)
* Shelf collisions make it hard to pick up fertile soil

![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/95f4b81e-e33b-44ec-aadd-2573f753f6b1)
* This blueprint on top of the shelf is not marked as 'stealing'

![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/8a21eb2a-4c53-4596-83c6-9553b097d9fe)
* This plastic bucket is not marked as 'stealing'

![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/b21f77b5-a0a7-4c20-ba57-084e06692f02)
* Being on the stairs makes some of the lights not render

![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/49469492-b7cb-4724-803b-c9dbe5f20968)
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/d9da689d-b3fa-48b6-ace1-2f399d57f79d)
<h2>Apartment A7</h2>
* Some interior lights are not rendered from stairwell

![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/e94b720b-d531-4a81-a67b-1e8415ef906c)
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/dcba8413-c856-414b-9b6c-135abc83d33e)
* This plant in living room is rotated sideways

![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/f7a64591-d5d9-44b6-b355-e89509787601)
* This plastic container cannot be picked up from this angle

![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/4a0b9790-ef7e-4464-8a71-003fe17ebc3a)
* Sauna is not working (same as before)

![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/25557452-f7b5-4e32-9bc9-94466eb3ab2a)
* This recipe in the kitchen is not marked as 'stealing'

![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/d1dba40a-ce12-4943-b2a1-cafab95c9dec)
* You can get stuck in this corner of the kitchen

![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/7e16a8aa-b552-4236-a29a-9ccf2a942fa9)
* While being in a corner of the first cage, these two lights don't render at the same time

![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/0985401f-11d1-4c8f-a3d9-b0cf7078b071)
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/e51a1a97-a49e-4230-956f-b9c87e751479)
<h2>Apartment A8</h2>

* These 3 planks are not marked as 'stealing'

![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/e0cc72ec-63b9-4e7f-84e1-d9c8f14e8de3)
* These shrooms should probably cause coughing in close proximity

![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/0e8b8c5f-cb76-43d2-92d9-c433b85f46be)

<h2>Apartment A10</h2>

* Unpickable cleaning spray

![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/7023f08a-0c9d-4217-9d1f-2608d67d56ba)
* You can get stuck behind water sample machine

![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/aee1d529-1e1d-49f7-b37b-616707a4f665)
* The top cabinet does not spawn any items

![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/d91c44ba-c313-4bdf-8709-dbc80ad73b7d)
* In bathroom, a Hand Soap is not marked as 'stealing'

![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/9936aee2-0bd0-456a-bfda-316725ddbb04)
* In the lab, this recipe is not marked as 'stealing'

![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/5d8b4b74-8837-4445-9ddf-67e50dd7150d)
* This disinfectant is not pickable

![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/0025605e-a83d-4e04-9898-b2742c193f53)
* In the quest room, this Chem Lab is not marked as 'owned'

![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/8685cec9-c442-4dc4-b5fc-790498e18179)
<h2>Apartment A9</h2>

* This Cabinet does not spawn any items

![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/d7912a28-5499-4a9a-8bef-280bb4ae5090)
* The space between bathtub and the top rail is slightly too small to fit player standing

![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/40ff9087-72fc-4e36-93ff-74c1e037c99c)
* Player has to jump to get on top of the mattress, it should be smooth transition

![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/33c59555-4f5f-42c6-b0c5-2f316f592f71)
* Shrooms here are not harvestable

![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/bb645555-a1bc-42cb-a341-a95bbdfec312)
<h2>Apartment A11</h2>

* Interior lights are not rendered inside the apartment and vice versa

![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/e92dda4c-662d-4acc-8f14-01b271b462cb)
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/08830766-9208-4dc3-afe2-9649b8e7566a)
* Body in the first room has weird collisions (you can get around its collisions and inside the body)

![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/23058122-0d5a-47ae-95aa-e73c74b900ba)
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/6dc75eea-a668-4541-a7b3-3cab3be91858)
* Jumping and pushing onwards towards the hand pushes player back (a need for collision simplification?)

![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/aa878387-82ce-4539-9155-32de3484c213)
* Similarly as above, collision with these pushes player back

![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/91cdfdec-37b1-416d-8f42-4d787bd06dfb)
<h2>Apartment A13</h2>

* Toilet is not useable

![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/d10cf35c-10d1-439c-90d6-57db79cca995)
* First room (to the left), you can get stuck in a corner on the body

![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/ccd8d9f0-a064-4d71-8237-61a5e15287c5)
<h2>Apartment A14</h2>

* Toilet cannot be used

![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/49e7538b-c7c8-401a-822f-778aad66e677)

<h2>Stairwell</h2>

* Standing in this spot on a half-floor between floors 3 and 4 makes the light not render

![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/5a07d3a6-d724-4eb5-a704-82d3a42a39c6)
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/5c02238f-5f81-423a-b1ce-d8d49fc9f0c6)
* Going onto 6th floor while looking at the stairwell renders lights disabled

![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/e24d08a4-cbb7-47c7-9ea3-8d14647e80c5)
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/6b60420e-5fcf-4d97-a8c9-e36b837270cf)
* Going onto 7th floor while looking at the stairwell renders lights disabled

![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/c08e80a6-f4b7-4cf5-8755-24fc3abcef14)
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/71f2d1f1-9856-4d9f-b0e5-cb17988faa17)
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/202dca1b-82d1-4f88-b888-2eb381b85e50)
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/3035412f-9554-4b6c-b064-ce168ed7c57b)
* Standing on the steps to the 7th floor renders the mid-floor lights disabled

![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/8a1efefd-8b0d-428f-acd4-e623061c4cf0)
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/203da2a3-550b-4d69-a9a5-8e8b6516cd97)
* Going throught the blocked doors renders some lights from the contained area disabled

![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/69303920-fe65-4b46-b191-3e27455d2eb7)
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/57278c07-8c50-43d0-b22a-0262b5583370)
* Opening A13 doors renders additional lights (on the right) from not apparent source

![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/bd2eef55-ef98-4912-aea7-658b6c44567c)
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/8290ba9c-ccb0-4fb9-bdb4-145a4d84c176)
* Opened A13 doors cannot be closed manually as they are not selectable

![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/194cc42e-a915-453c-8e57-795d5b6d5811)
* Jonne Reis bed can be used, should be marked as 'owned' instead

![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/548eb601-a482-49f0-b50b-c03a536d1fb5)

**Comment by Zuntti** [comment]
Fixed
