### ISSUE TITLE
Rats do not get saved

### ISSUE THREAD

**Issue by ontrigger** [loiste-interactive/Obenseuer-Issues#214]
Infinite rat generator

https://github.com/loiste-interactive/Obenseuer-Issues/assets/8556074/5080a155-0745-4110-8bfb-4b249c08ba66

**Comment by Oskutin** [comment]
Possibly same cause than with this: https://github.com/loiste-interactive/Obenseuer-Issues/issues/213

**Comment by Oskutin** [comment]
Btw, dropping a ton of live rats from inventory is fun.

**Comment by Oskutin** [comment]
Fixed
