### ISSUE TITLE
Harvesting rats from cage convert them into coins

### ISSUE THREAD

**Issue by ontrigger** [loiste-interactive/Obenseuer-Issues#215]
I'm not sure if this a bug or not, but clicking on a rat inside the cage slots will yield a stolen coin?
https://github.com/loiste-interactive/Obenseuer-Issues/assets/8556074/cdfcac0a-c79c-4e9c-94bc-89f585621aef
The UI itself is also extremely convoluted, I don't understand why you can't just drag the rat into the cage slots

**Comment by ontrigger** [comment]
The cage itself is owned, just weird that you get a stolen coin out of it

**Comment by Oskutin** [comment]
Oh that rat turning into coin is a bug

**Comment by Oskutin** [comment]
Fixed rats becoming coins

**Comment by Oskutin** [comment]
The UI may get updated later.
