### ISSUE TITLE
Apartment A8 keys do not show up in inventory after picking them up

### ISSUE THREAD

**Issue by ontrigger** [loiste-interactive/Obenseuer-Issues#216]
They also do not work on the actual door they're supposed to open
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/8556074/2881e005-8035-4c7f-ab0d-1c87e2fd0a82)

**Comment by Oskutin** [comment]
Can you do that again (that it's the last action) and post a log?

**Comment by ontrigger** [comment]
[Player.log](https://github.com/loiste-interactive/Obenseuer-Issues/files/11472953/Player.log)

**Comment by Zuntti** [comment]
Fixed
