### ISSUE TITLE
Playtesting - When item has both 'amount' and 'perishable' attributes, information is lost on its icon

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#2169]
I propose one of the two solutions
1. If both these atributes are present, push perishable % to the top left corner (possible issues if there was an item with 'quality' attribute too)
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/cb2ac06b-a11b-4990-939c-b0bd0612bb87)

2. If 'amount' attribute is present, the 'stack' attribute is redundant, so perhaps move the 'amount' to the bottom right corner and then place perishable % in the bottom left corner
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/0b68f78d-b7b2-48d8-87db-e95cfc563cc3)

**Comment by Zuntti** [comment]
Changed
