### ISSUE TITLE
Playtesting - Tenement A resident list names are not properly rendered when viewed from smaller angles

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#2170]
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/beb21c96-ed39-45a2-9345-223f6cc1caf7)

![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/079b150e-4b26-4045-b964-2550161d8382)

**Comment by Zuntti** [comment]
Fixed
