### ISSUE TITLE
If we're having full inventory and character is giving us an item, that item won't be naturally added to our inventory and is lost forever.

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#218]
Samuel Jonasson in one of the dialogue options gives us coffee, normally it gets added, but if the inventory is full, it won't be, no notification is shown too, but I think I've once gotten the notification despite having full inventory.
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/78e09e78-f26b-4355-98d0-7ab144555fd4)
perhaps it would be good to spawn the item on the ground.

**Comment by Oskutin** [comment]
Doesn't it already spawn to the ground?

**Comment by Nextej** [comment]
Nope, well, at least its not visible nor pickable, can't reassure it doesn't spawn below the floor or something like that.

**Comment by Oskutin** [comment]
Looking at the code it should drop the item if adding it to inventory failed. It could have spawned in ground or some weird place?

**Comment by Oskutin** [comment]
Ah, actually no.

**Comment by Oskutin** [comment]
Fixed
