### ISSUE TITLE
[playtest] the chest with 99RM is now yielding 594RM and keeps reappearing in my appartment.

### ISSUE THREAD

**Issue by PestoVerde322** [loiste-interactive/Obenseuer-Issues#2180]
As title say, in the latest version (0.3.39 V4) that crate keeps respawning whenever i collect the cash, pocket the container, leave my appartment, and then re-enter it. Alongside that, the amount of cash also increased.

**Comment by Oskutin** [comment]
Does this happen on new saves?

**Comment by PestoVerde322** [comment]
> Does this happen on new saves?

Unsure, will have to test that

**Comment by TonyFromRomania** [comment]
welp in my last test on my old save, after getting the package i see the bug (curently didnt gone to far in the storyline to see if it happens on my new save, but i am not far from the point)

**Comment by PestoVerde322** [comment]
Can confirm, it happens on a new save aswell.

**Comment by Zuntti** [comment]
Fixed
