### ISSUE TITLE
Playtesting - The Fume Cabinets at shroomlight factory still by default is full of spoiled mushrooms

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#2186]
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/48036a54-329d-4c88-857a-239383d70bce)

**Comment by Nextej** [comment]
The fan is also not fixed
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/ee8c2f0a-2bb9-44a6-b764-8a0dae2048c0)

**Comment by Zuntti** [comment]
Fixed
