### ISSUE TITLE
Playtesting - Few new lighting issues at Tenement A

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#2190]
1. Crouching at the bottom of the elevator shaft disabled lights
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/63d4b8bf-6580-46e4-998f-4e4a4275b025)
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/c31aa671-6c2e-44f2-8a09-011cfbc9fd96)
2. Third floor, standing in this area on the elevator doorway disabled stairwell lights
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/2e2ba368-20b7-4df6-a95d-da2c770d07f9)
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/9636b2f1-ce56-4631-ab17-13c969147529)
3. When the sprite glow stops being rendered (it fades-out), when it needs to start being rendered it just plops up momentally (easiest way to test it is to go into apartment A6 to make it stop render and then return, the same happens when going down or up from the stairwell)
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/8871f1f0-395f-430a-8ca9-928c0e3021d4)
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/4d942501-bf7d-4b70-b5dc-9e42ce811948)
4. Elevator light is not rendered on the 7th floor
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/a36662d9-4307-4e97-b883-f15b21ef3516)
5. Opening A13 doors still weirdly and abruptly illuminates the hall to the right
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/9aa4e281-9970-4f8d-9396-b297dd43bed3)
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/4f66d418-c091-45d1-833f-a865752f7b31)
6. Stepping onto 7th floor from the bottom stairs makes some additional, very subtle, light to disappear
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/707494c8-a630-4696-9619-bacaeb57772c)
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/e30f7e41-c380-4951-b535-8815f004a492)
7. The whole maintainance area was actually pretty well optimized, so it is a shame a little that the vent was instead sealed off
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/e2130a4d-c707-4d31-a2b9-05acc5e0e04d)

**Comment by Zuntti** [comment]
Fixed
