### ISSUE TITLE
playtest - lockpick recipe paper does not add lockpick recipe 

### ISSUE THREAD

**Issue by pinkamedic** [loiste-interactive/Obenseuer-Issues#2195]
currently picking up the lockpick recipe paper does not add the recipe to your recipe inv

**Comment by pinkamedic** [comment]
seems like some of the new recipe papers do not add the recipe to the inv, as i picked up a recipe for a gold bar and didint get any recipe for it

**Comment by Zuntti** [comment]
Does this only happen when there is already a recipe with the same name in inventory?

**Comment by Zuntti** [comment]
Can I get save where this happens?

**Comment by pinkamedic** [comment]
[Kyle_Pinkmin.zip](https://github.com/user-attachments/files/16600816/Kyle_Pinkmin.zip)

**Comment by Zuntti** [comment]
Fixed
