### ISSUE TITLE
When having "maxed out" Mental Health, we can go above 100% with using sleeping pills.

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#220]
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/218a3491-53ba-4693-877c-de4df28c21e4)
On a sidenote, shouldn't intuitively the 0% of Mental Health be the worst state and 100% being the best one? At last for player's information in the UI, as it would the state of Mental Health be "dropping" down.

**Comment by Oskutin** [comment]
Should change "Mental health" -> "Depression".

You're on god mode right?

**Comment by Nextej** [comment]
Yeah, god mode is on.
