### ISSUE TITLE
[Playtesting] Kolhola A13 apartment still has a broken balcony door.

### ISSUE THREAD

**Issue by Taco-Cat1** [loiste-interactive/Obenseuer-Issues#2205]
I reported this a while ago and it was said to be fixed, I don't think it was because I still have the same issue on play testing. I assume the door is meant to be locked like all the other balcony doors but the issue persists.
![20240605171409_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/163670936/3be9f7da-d0ff-4b6f-a26c-aa16753d4f0b)
![20240605171415_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/163670936/8dced9ac-2b48-485d-8495-f8b7cba38345)
![20240605171421_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/163670936/f1edbc34-e93c-44a0-9da6-e8612a7e4d4f)

**Comment by Oskutin** [comment]
Is this old save?

**Comment by Taco-Cat1** [comment]
It's the same one that I reported the issue on. I'll check tomorrow on a new save if the bug is still there. Please keep the issue open
