### ISSUE TITLE
[Playtesting] My own kitchen that I upgraded to decent now counts as steeling for some reason.

### ISSUE THREAD

**Issue by Taco-Cat1** [loiste-interactive/Obenseuer-Issues#2206]
I upgraded my kitchen by Samual to decent and when I went to see what it looked like, it said that looking in the cabinets was theft. Also for some reason they had loot in them.
![20240603145448_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/163670936/de87f23d-7e97-4e03-ae9b-bf7abe82b98c)

**Comment by Zuntti** [comment]
Fixed
