### ISSUE TITLE
[Bug] Apartment in Deeluka B3 has an un-usable toilet.

### ISSUE THREAD

**Issue by Taco-Cat1** [loiste-interactive/Obenseuer-Issues#2208]
I imagine it just wasn't added the functional to be used but I know it's meant to be usable because you can lift the lid. Also when first using interacting with the lid it doesn't have and animation.

![20240525082333_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/163670936/df278929-2ee9-4ab7-9f44-399bca257923)

**Comment by Nextej** [comment]
Hmm, it was originally cloggled with body waste, looks like the model is missing

**Comment by Zuntti** [comment]
Fixed
