### ISSUE TITLE
Suggestion for container drop behavior

### ISSUE THREAD

**Issue by ontrigger** [loiste-interactive/Obenseuer-Issues#221]
Right now, dropping an item outside of a slot will cancel the drop action, i.e, dropping it in the space between slots.
I think it would be better if dropping items in the gutter would just pick the closest slot to the mouse position and drop it there.
The current behavior is really annoying when dropping junk into the tenement chest - I just want to quickly drag items without a care where it will end up, only for the drop to be canceled because I didn't hover my cursor exactly over a slot

**Comment by Zuntti** [comment]
Already implemented
