### ISSUE TITLE
[Typo] Both sides of the steel cabinet say that they are the left side

### ISSUE THREAD

**Issue by Taco-Cat1** [loiste-interactive/Obenseuer-Issues#2218]
![20240606164152_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/163670936/ae442f96-40a4-40aa-b553-c3598b689d29)
Actual left side
![20240606164156_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/163670936/57c7596b-7e9a-4865-8c14-745796ae5030)
Supposed to be right side

**Comment by Zuntti** [comment]
Fixed
