### ISSUE TITLE
[Playtesting] Some more Tenement A issues

### ISSUE THREAD

**Issue by Taco-Cat1** [loiste-interactive/Obenseuer-Issues#2223]
![20240607161306_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/163670936/7a3351b9-de75-4fd7-b26c-efc07e2b4594)
Door to apartment A9 opens inwards and clips through the wall
![20240607161706_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/163670936/19c7567c-61d2-4c21-ad2e-ee4d04289937)
Despite the radio being off I still hear music
You can still get stuck behind the tool cart in the basement with the help of the boot next to it

**Comment by Zuntti** [comment]
Fixed
