### ISSUE TITLE
Moonshine distillery should require barrels not barrel planters 

### ISSUE THREAD

**Issue by TonyFromRomania** [loiste-interactive/Obenseuer-Issues#2229]
![20240608005645_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/157300727/d732fce7-dd30-42e2-b1dd-008ffe4d7b06)
distilery has a requirement of barrel planters in the place of normal barrels *edit* minor image fuckup from my side

**Comment by pinkamedic** [comment]
that dont look like a distillery

**Comment by Zuntti** [comment]
Fixed
