### ISSUE TITLE
[PLAYTEST as of 6/7] Eliana Passmores aptmnt has item pop in/out issues

### ISSUE THREAD

**Issue by Tritiumisotope** [loiste-interactive/Obenseuer-Issues#2230]
![Untitled](https://github.com/loiste-interactive/Obenseuer-Issues/assets/67477899/d39b7f3c-ceca-4d4b-8d63-049001b4a63b)
Light switch, rug, dustpan will pop in and out if you move around in this orientation.

**Comment by Zuntti** [comment]
Fixed
