### ISSUE TITLE
[PLAYTEST as of 6/7] Player apartment (1) furniture can't be picked up/placed after level 4 upgrade -  or during other upgrades, unsure.

### ISSUE THREAD

**Issue by Tritiumisotope** [loiste-interactive/Obenseuer-Issues#2231]
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/67477899/bb66ed44-dc82-410d-a5e7-8329fe19e06a)
 
Will update if the finished kitchen and bathroom fixes it, but still ideally not a thing that happens. Also may be because I entered one of the expansion wings when the apartment itself was upgrading and also could not place anything.

**Comment by Tritiumisotope** [comment]
Strange update, I saved, exited, rebooted the PC since yesterday, loaded it today... and it's fine. It still HAPPENED but this is now a bit of a transient issue to make note that it IS transient so efforts to see why it happens might be difficult.

**Comment by Zuntti** [comment]
Did you pick up that black plastic storage with money? It might cause this bug

**Comment by Zuntti** [comment]
Probably related to black plastic storage
