### ISSUE TITLE
Playtesting - accidential potential for an interesting puzzle to solve the safe code

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#2253]
In the Fredrik's lab there's a safe and a board with written organic compound structure
![20240531132451_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/034031ff-a950-48a0-9b64-d99b3a25b78e)
Decoding the chemical formula almost (almost since it has 5 elements, not 4) gives 4-digit sequence that would be viable to the safe (which it is not in any form a clue to the actual safe code in the room, especially given that part of the structure is covered by some notes and I had to check texture file to be sure, but maybe I'm stupid and missing something and it already was meant to be a code clue)
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/ee3408b9-963c-40de-9405-ecc8e1c9b1e3)

I think this idea could be reused to have more engaging puzzle that requires some external from the game, basic chemistry knowledge (or a 15 minute google search), and I think this would be a way way more realistic code hint, that I could believe if some chemist wanted to keep tabs on some long code combination he keeps forgeting, he would come up with an imaginary compound structure, so he can decode it in a moment

**Comment by Zuntti** [comment]
Added
