### ISSUE TITLE
Playtest - can craft some furniture without full material's needed

### ISSUE THREAD

**Issue by pinkamedic** [loiste-interactive/Obenseuer-Issues#2258]
the veggie crate can be made without any planks and i was able to make a half pallet with only half planks needed, assumingly this can work with most furniture
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/151697489/0be71f40-9561-40d4-a29f-7168bd1068b9)
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/151697489/e1b83c84-74fb-43f4-bc1b-94d825db1b63)

**Comment by Zuntti** [comment]
Fixed
