### ISSUE TITLE
enhancement - there should be a vent above the basement exit

### ISSUE THREAD

**Issue by pinkamedic** [loiste-interactive/Obenseuer-Issues#2259]
if ya look here youll see a vent leading towards the outside to assumingly keep air flowing though the basement
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/151697489/cdf5d0b7-b469-44ff-a9a4-69651c95fc17)
yet when you step outside
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/151697489/68d97935-b5f7-4838-8e4d-1d9235292841)
no vent!

**Comment by Zuntti** [comment]
Added
