### ISSUE TITLE
Playtesting - Pet seller NPC in Tenement A overlaps with T-posing model

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#2276]

**Comment by Nextej** [comment]
+ ringing the doorbell does not say anything like "Open, please enter", just it silentely unlocks

**Comment by Nextej** [comment]
The issue applies to most "overhauled" NPC models, in other levels too.

**Comment by Taco-Cat1** [comment]
I got some screenshots of where this T-Posing model appaers
![20240622154713_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/163670936/369a49da-ff04-4370-96f3-2920d7a8e4d0)
With Pia
In Tenament A apartment A6
At the cat trader
With the elevator guy at the top of Tenement A

Note: This might not be all the locations

**Comment by Zuntti** [comment]
Fixed
