### ISSUE TITLE
Playtesting - "Disappearance of Alice" quest, you can trigger "Pia is dead" dialogue option out of order

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#2277]
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/e6b1a699-a1a8-46d1-8c2c-26d58051b9c3)
This dialogue option can be chosen, despite Pia being alive, the option leads to player saying where the body of alice is, before player even investigates it.

**Comment by Zuntti** [comment]
Fixed
