### ISSUE TITLE
Playtesting - Outside level keeps returning "Object reference is not set to an instance of an object"

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#2281]
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/de43cef7-8800-431f-a905-4bb3cab0def5)

**Comment by Oskutin** [comment]
Can you get the the log, it's more detailed there

**Comment by Nextej** [comment]
[Player.log](https://github.com/user-attachments/files/15917900/Player.log)

**Comment by Oskutin** [comment]
NullReferenceException: Object reference not set to an instance of an object
  at MaterialWindEffect.WeatherUpdated () [0x0002c] in <ffafb927e1b64bc1b038ed7141ec5837>:0 
  at MaterialWindEffect.Start () [0x0000b] in <ffafb927e1b64bc1b038ed7141ec5837>:0

**Comment by Zuntti** [comment]
Fixed
