### ISSUE TITLE
Feedback - Firewood piles should not respawn and firewood price/worth should be increased

### ISSUE THREAD

**Issue by pinkamedic** [loiste-interactive/Obenseuer-Issues#2284]
firewood is more or less everywhere when its supposedly hard to get in obenseuer to the point that a merchet gets it from outside of the  city, you can get up to 3-5 days worth of fuel from a single firewood pile that respawns on the daily. right now its not the biggest deal but when more mechanics are added such as heat management and needing to refuel the furnace in the greenhouse it will become a bigger deal but will become trivialized by the large piles constantly respawning. also the firewood merchant is useless firewood is worthless to sell and its everywhere so why bother buying any

**Comment by Taco-Cat1** [comment]
I also think that fuel slots should have a limit on how many hours of fuel they can have and reducing how much time fire wood gives you would make it more challenging

**Comment by pinkamedic** [comment]
that is a good idea as its silly that you can load up to 100 hours of fuel into a single burn barrel, not to mention the ash that explodes out of it when it runs out of fuel

**Comment by Oskutin** [comment]
Are you talking about tenement firewood piles respawning?

**Comment by pinkamedic** [comment]
just firewood piles in general, the one in the greenhouse the one next to to the outside player sauna all of em
