### ISSUE TITLE
Playtesting - at the Fredrik's lab, these two notes obstruct the needed information to solve the code puzzle

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#2289]
Whole chem structure needs to be visible for player to deduct it's name
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/1380ee0a-1e9c-4c9e-9edc-2fc330ea3237)

**Comment by Oskutin** [comment]
Fixed
