### ISSUE TITLE
Playtesting - I think that all adjecent rooms in Tenement A7 apartment should be considered tresspassing upon entering

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#2291]
Since we're entering the private property to buy pets upon permission, entering anywhere besides the "invited" space should add tresspansing points, with NPC reacting to that
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/460caca5-8d9f-4c2b-8d10-0a685535884d)
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/8fd648ff-95da-4b87-8e79-d8aba9dc0af7)

Also I think that realistically these cat cages would be locked, requiring lockpicking 
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/4b0d89cc-11f4-41eb-90f0-6f7d780c8ead)

**Comment by Oskutin** [comment]
Added tresspassing zones. Toilet is still allowed
