### ISSUE TITLE
Playtesting - You should be able to report Hietala's and Alice's bodies to the militiamen/112

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#2293]
After finding the body in Tenement A1 apartment, player should be able to report the body, same with the body of Alice found in the small storage.

Additionally, once police clears out Pia's and Hietala's bodies, the items/machines in their apartments should not longer be considered owned (in according to the rule that abandoned apartments are not considered stealing).

**Comment by Nextej** [comment]
Well actually, there should be a dialogue line of sorts "I have multiple bodies to report..." if player found all 3 bodies before attemping to report them separately (separate option should of course exist too if player decided to report after finding only one body).

**Comment by Nextej** [comment]
Actually you can report Hietala's body, unless you enter the Small Storage, after that the ability to do so is taken away. Ability to report Alice's body is not given in return either.

**Comment by Zuntti** [comment]
Fixed
