### ISSUE TITLE
Playtesting - minor level design continuity error around Tenement A, the pipe in the interior goes outside, however the continuation of this pipe is not seen on the outside

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#2295]
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/17c51fcc-0632-4362-b44e-1de13c99e615)
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/5cb1cd34-e959-47da-9872-3d7c6f1fe151)

**Comment by Zuntti** [comment]
Fixed
