### ISSUE TITLE
Playtesting - "The Disappearance of Alice" quest, typo when asking Louis Green about Alice

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#2298]
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/f52fc0e4-701b-4059-8436-384da1b5e11e)
should be "her"

**Comment by Nextej** [comment]
Asking Fredrik about Alice, her name is not capitalized
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/551b7ab5-acbc-4da6-a3e2-3bfde4cec468)

**Comment by Zuntti** [comment]
Fixed
