### ISSUE TITLE
Loading games not working

### ISSUE THREAD

**Issue by apterous123** [loiste-interactive/Obenseuer-Issues#23]
unable to load saves. clicking on slot1 plays sound. clicking on character name does nothing.

**Comment by Oskutin** [comment]
From main menu?

**Comment by apterous123** [comment]
yes

**Comment by Zuntti** [comment]
Did the character have any special letters? Can you give the character folder? It should be in Users\Username\AppData\LocalLow\Loiste Interactive\Obenseuer\Saves

**Comment by Zuntti** [comment]
Fixed
