### ISSUE TITLE
Playtesting - "Disappearance of Alice" quest: spam in the log in Pia's house after finding Alice's body

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#2303]
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/93e1fc75-99bd-4543-8c21-f283ac2b4577)

**Comment by Nextej** [comment]
[Player.log](https://github.com/user-attachments/files/15945310/Player.log)

**Comment by Zuntti** [comment]
Save? It seems to be related to the equipped flashlight

**Comment by Nextej** [comment]
[Mines_Update.zip](https://github.com/user-attachments/files/15954263/Mines_Update.zip)
Slot 1 should be good
