### ISSUE TITLE
Playtesting - "The Disappearance of Alice" quest: when Friedrik is questioned about Alice, he says he doesn't know anyone associated with her in the Tenement A, but after the quest when he's told she's dead, he says he recalls Alice's friend named Hietala

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#2305]

**Comment by Nextej** [comment]
He even adds that he saw them both in the stairwell together despite saying before he never seen Alice with anyone

**Comment by Zuntti** [comment]
He never actually says that. Only that Alice has been at Fredrik's place alone (not Tenement A) and also Pia mentions that Fredrik seems to be absent-minded

**Comment by Zuntti** [comment]
I made a few changes to the dialogue
