### ISSUE TITLE
[PLAYTEST as of 6/23] When renovating the player aptmnt and using the extensions, weird things happen

### ISSUE THREAD

**Issue by Tritiumisotope** [loiste-interactive/Obenseuer-Issues#2308]
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/67477899/5a163ebf-f401-4110-b4d5-513493eeda37)
This particular type of cabinet starts randomly changing contents as if it belonged to an NPC, and the furniture becomes temporarily impossible to pick up and put down.

**Comment by Oskutin** [comment]
Got savefile?

**Comment by Tritiumisotope** [comment]
[PT_Cruiser.zip](https://github.com/user-attachments/files/15946678/PT_Cruiser.zip)
Couldn't put whole folder of saves for another bug but just this one alone I can. 76 megs seems really big! wonder why it's so much for all of them. Anyway, Save 3 should be the one, also there may be a bug where if you go to save, it shows no saves saved for this character. It's weird.
