### ISSUE TITLE
Playtesting - Safe unlocking feedback

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#2311]
Issue
- People with shitty/mediocare earphones will hardly hear a difference between regular clicks and the right clicks (especially since regular clicks sounds get cut off sometimes)
- People with good earphones that provide clean sound and don't cut the sounds will hear the difference really clearily and will have no problem of getting it at the first try (effectively for someone who is aware of this mechanic, it makes safe opening faster that way than looking for a code)

Possible ideas
- Have each click for each 4 digits different from each other, so player has harder time to 'just recognise the one click that's sligthly quieter', so pitch on first correct digit is different from pitch on second correct digit and so on.
- Have the pitch diviation of regular clicks and pitch diviation of the correct clicks slightly randomized, in a way that ranges of extreme of low pitch of regular clicks and extreme of high pitch of correct clicks overlap. That way correct clicks have a slight chance of sounding very similar to regular clicks, forcing player to do several rotations to be totally sure it's the right position
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/d840067d-ca39-4bb8-b39a-62cf97f9692b)

**Comment by Oskutin** [comment]
Implemented
