### ISSUE TITLE
[Playtesting] Player can grab the full milk cartons from the O-Market fridge and recycle them for money

### ISSUE THREAD

**Issue by Taco-Cat1** [loiste-interactive/Obenseuer-Issues#2315]
If the player were to grab all the owned milk cartons at the back of the store they can put them into the bottle recycling machine and make some easy money. A way to fix this would be to not let the machine accept milk cartons with liquid in them

**Comment by Nextej** [comment]
Or not accept "owned" items.

**Comment by Taco-Cat1** [comment]
True but putting liquid into an electrical machine might not be the safest thing to do

**Comment by Zuntti** [comment]
Fixed
