### ISSUE TITLE
[Playtesting] I magically knew the password to Passmore

### ISSUE THREAD

**Issue by Taco-Cat1** [loiste-interactive/Obenseuer-Issues#2316]
![20240626010342_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/163670936/76ee7bbd-55a2-4a60-bda3-5a76103c7325)
Ignoring my shroom high as well as being drunk you can see that I get the quest and jump to the objective of telling the correct password. I deleted my save after this but you might be able to recreate it.

**Comment by ProfRadis** [comment]
i recreated it and how to do it is firstly go to deecula basement door and ring it after ringing and saying passed to her she will say go to tenement B and talk to him (passmore), at passmore he will entirely skip "passed" and go to "passless".
This is before 5 upgrades task

**Comment by Taco-Cat1** [comment]
I just started a new save and I just knew it

**Comment by Tritiumisotope** [comment]
Also randomly talked to him in a new save and knew it, latest playtest as of 8/4

**Comment by Zuntti** [comment]
Fixed
