### ISSUE TITLE
Enhancement - sulfuric acid should only be stored in metal or glass containers

### ISSUE THREAD

**Issue by pinkamedic** [loiste-interactive/Obenseuer-Issues#2320]
sulfuric acid would outright eat though a plastic container espicly a cheaply made one made for drink's, acid should only be able to be stored in glass such as the glass bottles or wine bottles, could even add metal liquid containers like a bucket

**Comment by Oskutin** [comment]
![SULPHURIC-ACID-33-AC593-5L-1-2606689013](https://github.com/loiste-interactive/Obenseuer-Issues/assets/5402150/f81783a2-36bd-4f8f-b154-a1f8dd631bdc)

Usually hazardous chemicals are used in plastics, while metal in general is being avoided.
