### ISSUE TITLE
Falling asleep while opening a door that triggers a loading screen softlocks the game

### ISSUE THREAD

**Issue by duckymomo360** [loiste-interactive/Obenseuer-Issues#2328]
My clipping software didnt record it, but I'm pretty sure that's exactly what happened.

Fell asleep while the door open animation was playing, clock went by, woke up still at the door but unable to move, interact, or open any menus.
[Player.log](https://github.com/user-attachments/files/16047713/Player.log)
Version: 0.3.38

**Comment by Zuntti** [comment]
Fixed
