### ISSUE TITLE
Bug - moist modifier for planters sometimes is replaced with sun modifier despite being in the conditions for moist

### ISSUE THREAD

**Issue by pinkamedic** [loiste-interactive/Obenseuer-Issues#2331]
the issue is solved if you pick up the planter and put it back down (before and after photos) seems like it is replaced with the sun modifier when you leave and enter the tenement
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/151697489/62f89701-e04c-4a8c-a1bf-8a6df08c8b3f)
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/151697489/9a8dbbb5-cfa8-4733-986b-94c47547d326)

**Comment by Zuntti** [comment]
Maybe fixed and related to https://github.com/loiste-interactive/Obenseuer-Issues/issues/2123
