### ISSUE TITLE
Crafting a Chemistry Station using stolen mechanical components causes crash

### ISSUE THREAD

**Issue by Wretched-K** [loiste-interactive/Obenseuer-Issues#2342]
Running Obenseuer v.0.3.38

As stated.
Specifically, I have 2 stolen components in my inventory and 2 non-stolen.
When I just pull one stolen one from my bag, the craft executes fine, however using a stack of 2 (or presumably more) causes the game to instantly crash to desktop.
I have tried in both the tenement contract workbench and an in-tenement workbench, both seem to have this issue.
[Link to a clip of the bug](https://drive.google.com/file/d/10HU8ujQAPlDXMhBC3I9FdB6b7P8xelTn/view?usp=drive_link)

**Comment by Oskutin** [comment]
Got logfile and dumpdile?

**Comment by Wretched-K** [comment]
I'm sorry I don't
I thought I had created a backup of it to share, but I can't seem to find it

**Comment by Zuntti** [comment]
It seems that it crashes when the selected category is something other than "All" and the selected category becomes empty

**Comment by Zuntti** [comment]
Fixed
