### ISSUE TITLE
Failing to wash stolen over-the-counter drugs duplicates them

### ISSUE THREAD

**Issue by Wretched-K** [loiste-interactive/Obenseuer-Issues#2344]
Running v0.3.38

As stated.
When washing over-the-counter drugs such as antidepressants, if the first washing fails, it will return a stolen box of antidepressants with 0/6 uses, this box can then be washed again without the item being consumed; causing the 0/6 box to be duplicated.
This may also work on stolen prescription drugs, although I have not been able to confirm that. 
[[Clip]](https://drive.google.com/file/d/1MJvISoCZfT1Ld6Hv34K1IkBlMrnWp_OF/view?usp=sharing)

**Comment by Zuntti** [comment]
Seems to be fixed already in 0.3.39
