### ISSUE TITLE
Deekula A basement entrance locked after loading autosave

### ISSUE THREAD

**Issue by gehube** [loiste-interactive/Obenseuer-Issues#235]
![20230517172223_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/130682887/23ef6ef7-1e61-4430-89af-b8dd83e02973)

**Comment by Oskutin** [comment]
Can you be more precise on what happened?

**Comment by gehube** [comment]
I loaded an autosave which was in Deekula A, I was trying to go back into the basement but the door was locked, even though I had it unlocked prior to this.

**Comment by Oskutin** [comment]
And you're unable to unlock it again?

**Comment by Oskutin** [comment]
Did you also check the door that it's unlocked from the same level as you're now?

**Comment by gehube** [comment]
It seems like you have to unlock the door again when you enter Deekula A. Loading the save seems to get rid of the ability to unlock it.

**Comment by Oskutin** [comment]
Duplicate of this https://github.com/loiste-interactive/Obenseuer-Issues/issues/190 , as it seems to affect all keys.
