### ISSUE TITLE
Enhancement - changes to wooden piler

### ISSUE THREAD

**Issue by pinkamedic** [loiste-interactive/Obenseuer-Issues#2356]
with how the wooden piler is now its alittle hard to make decent pallet walls so it needs some changes to make it better.

1 double the size, id say around 1.5x taller then it is right now or yetleast the height of the tarpwalls,
2 let other pallets snap onto it, right now you cannot snap the half or quarter pallets to the wall
3 more snap locations, with the increased size there should be yetleast 4 snap locations per side so you can snap 2 full sized pallets ontop of each other and 4 half pallets ontop of each other

**Comment by Zuntti** [comment]
Added Half Wooden Pillar and more snap locations
