### ISSUE TITLE
Bug - purifying water at distillery will always give 0.2 ltrs of water despite saying it will give more

### ISSUE THREAD

**Issue by pinkamedic** [loiste-interactive/Obenseuer-Issues#2362]

**Comment by Zuntti** [comment]
Seems to work for me. Can I get a save where this happens?

**Comment by pinkamedic** [comment]
this should be correct
[Slot1.zip](https://github.com/user-attachments/files/16281929/Slot1.zip)

**Comment by Zuntti** [comment]
Seems to be fixed already. Related to https://github.com/loiste-interactive/Obenseuer-Issues/issues/2285
