### ISSUE TITLE
Playtest - new walking noises overlap

### ISSUE THREAD

**Issue by pinkamedic** [loiste-interactive/Obenseuer-Issues#2369]
seems to rapidly overlap the sounds when on soft surfaces ( carpets for example)

**Comment by Zuntti** [comment]
Doesn't seem to happen to me

**Comment by pinkamedic** [comment]
it might have been because of the area i was in ( walking backwards in the inspection booth )

**Comment by Zuntti** [comment]
Does this still happen?

**Comment by pinkamedic** [comment]
i havint noticed it in the new version so no
