### ISSUE TITLE
playtest - omart is having some lighting issuies

### ISSUE THREAD

**Issue by pinkamedic** [loiste-interactive/Obenseuer-Issues#2370]
the low watt bulbs arnt working to well
![image](https://github.com/user-attachments/assets/8444a916-a048-4dff-9924-53c4aecd4270)

**Comment by pinkamedic** [comment]
![image](https://github.com/user-attachments/assets/e4afe45b-ed1e-4e51-91d2-6dcfc7ba0c2f)
seems to be happening in deekula A aswell

**Comment by Taco-Cat1** [comment]
I don't have it in deekula A but I do have it at the gatehouse

**Comment by Zuntti** [comment]
Fixed
