### ISSUE TITLE
Playtesting - While in furniture preview menu, every several seconds the whole scene flashes for a moment, as if in fullbright

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#2375]

**Comment by Zuntti** [comment]
Doesn't seem to happen to me

**Comment by Nextej** [comment]
yeah, doesn't seem to happen anymore since yesterday's update

**Comment by Nextej** [comment]
Seems like the same issue is happening now on Player's Tenement level (globally, not just in the furniture preview)
