### ISSUE TITLE
Playtesting - some vendor npcs start walking around and get stuck on things / wont return to their spot

### ISSUE THREAD

**Issue by pinkamedic** [loiste-interactive/Obenseuer-Issues#2376]
hes been stuck there for awhile, idk if this is a bug that they start moving around or a new feature, another vendor that started moving around was the canned goods lady
![image](https://github.com/user-attachments/assets/cb3d76a8-556a-4c56-b314-11b6b5bf4739)

**Comment by pinkamedic** [comment]
seems like npc movement is messed up in general as the cops are messed up (more then usual) to the point they wont start a chase even if they give dialogue to start a chase

**Comment by Zuntti** [comment]
Fixed
