### ISSUE TITLE
A certain issue with hint for device reloading with batteries.

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#238]
When we're out of energy for either of the flashlights or the OSRAT, we're getting a tutorial hint about reloading, however if player doesn't have any batteries to reload them, the hint is lost and player might be confused on how to properly reload them once they find a batteries. My proposed solution is that if the hint appears and player is out of batteries, a notification that they need batteries should appear and the hint then should disappear, only to reappear once player finally acquires proper batteries.

On a related note, OSRAT item should mention what type of batteries are used in its description.

**Comment by Zuntti** [comment]
Fixed.
