### ISSUE TITLE
Playtesting - Given how large the fluid containers are, I think the filling time should be 2x faster

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#2393]

**Comment by Zuntti** [comment]
Which of them? Liquid containers have different filling and unfilling times

**Comment by Nextej** [comment]
Can they all be increased 2x times respectively for their own time? I think it's the most notable issue when filling to/from Canister on IBCs or regular house sinks

**Comment by Zuntti** [comment]
Increased
