### ISSUE TITLE
Playtesting - You can't move liquid from one container to a one that's in item state (like empty bottles)

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#2395]
![image](https://github.com/user-attachments/assets/8cc4d607-4d02-4811-85ff-566f2356904d)

**Comment by Nextej** [comment]
"Moving liquids" mechanic is also not consistent, it takes right click + move to move liquid from canister to canister, but it takes left click + move to move from bottles to canisters

**Comment by Zuntti** [comment]
Fixed
