### ISSUE TITLE
dyanmite sound effect does not exist or does not play

### ISSUE THREAD

**Issue by VaughnRoper** [loiste-interactive/Obenseuer-Issues#2403]
![image](https://github.com/user-attachments/assets/475624c1-e237-4520-9246-510b9c06529f)
 when detonating the dynamite holes found here, no SFX plays when the detonation occurs, at least not if the player runs back a bit into the passage before doing so. lack of sound feedback makes it unclear if the detonation worked

**Comment by Zuntti** [comment]
Fixed
