### ISSUE TITLE
cannot interact or open menus after showing photos to pia

### ISSUE THREAD

**Issue by VaughnRoper** [loiste-interactive/Obenseuer-Issues#2407]
after showing the photo to pia, keys for interacting with environment or opening menus ceased to function. only arrow keys and spacebar continued to respond for movement. could not leave building or open pause menu to load a save

**Comment by VaughnRoper** [comment]
issue persists after re-loading and giving the letter again. upon interacting with pia, the console begins to flood with a ' " is not a valid command...' message, as though i were entering " into the console over and over. after ending the conversation with pia, having given the letter and told her id deliver the letter right away, the console floods with this message

![image](https://github.com/user-attachments/assets/f60f017f-ad83-4c78-9734-5ee18c375736)

**Comment by Zuntti** [comment]
Fixed
