### ISSUE TITLE
Playtesting - changes to the recipes do not get updated in the UI retroactively on older saves

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#2409]
the recipe logic is updated, it requires the new set of ingredients to be put in to start crafting, but the UI is still displaying the old set of ingredients, so player has no right to know what they really need

In example the Glass Pane recipe was updated with the addition of Limestone, but the recipe still shows only Sand and Glass Shards
![image](https://github.com/user-attachments/assets/0c24ec67-210c-4076-944a-e1a5692f6894)

**Comment by Zuntti** [comment]
Fixed
