### ISSUE TITLE
Playtest Bug - Failed to load apartment

### ISSUE THREAD

**Issue by ProfRadis** [loiste-interactive/Obenseuer-Issues#2429]

**Comment by ProfRadis** [comment]
![20240723155316_1](https://github.com/user-attachments/assets/135b4c57-9651-4d7f-bf6d-47a9f8ad48b9)

**Comment by ProfRadis** [comment]
When everything is max out in apartment

Here are the files: [https://wetransfer.com/downloads/b07d34b320190444a302f264450643ee20240723125949/5025c9851c4efe8d82af8edcd7b9bab120240723130007/c09cd6](https://wetransfer.com/downloads/b07d34b320190444a302f264450643ee20240723125949/5025c9851c4efe8d82af8edcd7b9bab120240723130007/c09cd6?trk=TRN_TDL_01&utm_campaign=TRN_TDL_01&utm_medium=email&utm_source=sendgrid)

**Comment by Zuntti** [comment]
Fixed
