### ISSUE TITLE
Playtesting - Missing dekula b sink

### ISSUE THREAD

**Issue by pinkamedic** [loiste-interactive/Obenseuer-Issues#2430]
honestly i think this should be a cartable makeshift sink with the IBC
![image](https://github.com/user-attachments/assets/bcaf361e-1fea-47c5-b590-5c96d81633ce)
![image](https://github.com/user-attachments/assets/b47fc9b3-6e1d-4beb-a628-fab2aeb69cde)

**Comment by Oskutin** [comment]
Fixed
