### ISSUE TITLE
Playtesting - On older saves, new skills are not getting added to player's character, player won't see them in console, player will not be able to level them up or increase it with command

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#2433]
![image](https://github.com/user-attachments/assets/220ef2f4-f1c4-45bb-b975-4c1877d43d3e)

**Comment by Oskutin** [comment]
![kuva](https://github.com/user-attachments/assets/1b4ab87c-4dee-4c97-80d4-567cd5c77779)
works for me

**Comment by Nextej** [comment]
![image](https://github.com/user-attachments/assets/4085bf33-d1f0-4cd9-8dba-533c9fc31fe7)
from today's update, could be a save migration issue?

**Comment by Nextej** [comment]
Seems like it might be the cause of the alleged issues with getting Cleaning skill when using dishwasher, all these people could've been using saves that were predating the addition of that skill

**Comment by Zuntti** [comment]
Fixed
