### ISSUE TITLE
Playtest - Bug Doesn't let make glass pane

### ISSUE THREAD

**Issue by ProfRadis** [loiste-interactive/Obenseuer-Issues#2435]
![20240724183808_1](https://github.com/user-attachments/assets/d0501496-d40f-4e90-a509-928e1ef89291)
![20240724183811_1](https://github.com/user-attachments/assets/4ba54c20-02c3-416e-9aaf-67ece6848987)

**Comment by ProfRadis** [comment]
And typo

**Comment by Nextej** [comment]
The recipe has changed #2409 it now requires also limestone
