### ISSUE TITLE
Playtest - null spam is worse and is happening on every scene 

### ISSUE THREAD

**Issue by pinkamedic** [loiste-interactive/Obenseuer-Issues#2438]
![image](https://github.com/user-attachments/assets/a11481c0-857b-4084-af09-60f42a562562)

**Comment by Oskutin** [comment]
Logfile

**Comment by pinkamedic** [comment]
[Player.zip](https://github.com/user-attachments/files/16365302/Player.zip)

**Comment by Oskutin** [comment]
`NullReferenceException
  at (wrapper managed-to-native) UnityEngine.Component.get_gameObject(UnityEngine.Component)
  at InteractableItemGiver.DeltaSeconds (System.Int32 sec) [0x00000] in <493b5892c6574326a4d150cfe7d01698>:0 
UnityEngine.DebugLogHandler:Internal_LogException(Exception, Object)
UnityEngine.DebugLogHandler:LogException(Exception, Object)
UnityEngine.Logger:LogException(Exception, Object)
UnityEngine.Debug:LogException(Exception)
InteractableItemGiver:DeltaSeconds(Int32)
TimeOfDayAzure:UpdateCurrentTimeAndDay()
TimeOfDayAzure:CalculateDeltaTime()
TimeOfDayAzure:Update()
 
(Filename: <493b5892c6574326a4d150cfe7d01698> Line: 0)

NullReferenceException
  at (wrapper managed-to-native) UnityEngine.Component.get_gameObject(UnityEngine.Component)
  at InteractableItemGiver.DeltaSeconds (System.Int32 sec) [0x00000] in <493b5892c6574326a4d150cfe7d01698>:0 
UnityEngine.DebugLogHandler:Internal_LogException(Exception, Object)
UnityEngine.DebugLogHandler:LogException(Exception, Object)
UnityEngine.Logger:LogException(Exception, Object)
UnityEngine.Debug:LogException(Exception)
InteractableItemGiver:DeltaSeconds(Int32)
TimeOfDayAzure:UpdateCurrentTimeAndDay()
TimeOfDayAzure:CalculateDeltaTime()
TimeOfDayAzure:Update()`
