### ISSUE TITLE
Playtesting- Can't Interact with any sink after doing Bank of Bazaar quest.

### ISSUE THREAD

**Issue by thedoctorpl898** [loiste-interactive/Obenseuer-Issues#2443]
Atleast I'm sure it's this quest as it's possible to interact with the sink in the bank's upper apartment. but upon leaving the bank and speaking with Passmore not only does the player's bathroom sink become "owned" It also removes your ability to interact with any other sink.

v. 0.3.39
![image](https://github.com/user-attachments/assets/dcfe7114-aaf1-42d6-942d-e896d49ac42b)
![image](https://github.com/user-attachments/assets/e9a31b6a-8ce1-458b-8743-0618e8445e1a)

**Comment by Zuntti** [comment]
Can I get a save where this happens?

**Comment by Zuntti** [comment]
Fixed

**Comment by thedoctorpl898** [comment]
> Can I get a save where this happens?

I take it now that it's fixed you don't need the save? I can still provide one regardless.
