### ISSUE TITLE
Unusual game behavior after loading an autosave from character that had no actual saveslots saved.

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#245]
To various testings I just go ahead and create a new character, they all have at least autosave on them so this time I've booted up the latest used character. The two main things I've noticed, any visual drug effects are not applied, drinking, smoking and shoorms; player stats can go as high as they can and player has no consequence out of it.
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/875214fc-f2bd-4867-8251-b5de3f9eeb1c)
[Player.log](https://github.com/loiste-interactive/Obenseuer-Issues/files/11522951/Player.log)

**Comment by Nextej** [comment]
Seems like the issue is caused by skipping the interview because of the "testing door", so I guess it's not an issue.

**Comment by Oskutin** [comment]
Yeah, because stats are disabled before the interview. Eating and drinking increases toilet need, even though it won't have any effect until stats are enabled, or "applied" on game load.
