### ISSUE TITLE
Playtesting - crazy neighbor not showing up in player tenement 

### ISSUE THREAD

**Issue by pinkamedic** [loiste-interactive/Obenseuer-Issues#2450]
there are multilabel accounts from new and old saves that that he does not spawn in the player tenement despite having the correct life options to spawn him

**Comment by Oskutin** [comment]
Old or new save?

**Comment by pinkamedic** [comment]
ive gotten accounts from old saves and for me new saves

**Comment by Zuntti** [comment]
Fixed
