### ISSUE TITLE
[Suggestion] Being around glowing rats should give the player S.M.V

### ISSUE THREAD

**Issue by Taco-Cat1** [loiste-interactive/Obenseuer-Issues#2452]
This would encourage the player not to use glowing rats a food as they can give S.M.V and will instead promote farming them. It also makes it more realistic

**Comment by Nextej** [comment]
would be better if the rats left behind a trail of spores, the more the dense the trail is in one place, it starts to cause caughing

**Comment by Taco-Cat1** [comment]
I think that would be nice exept how would clear
