### ISSUE TITLE
Wrong launch location 

### ISSUE THREAD

**Issue by Eyes1977** [loiste-interactive/Obenseuer-Issues#2464]
I started a new character n game n was launched at the sauna by the tenement. 
![17220070194337602925950020067214](https://github.com/user-attachments/assets/b9ecf5f8-f970-42cf-8ece-07488c14dadb)

**Comment by TiaLinna** [comment]
To add to this issue which I experienced:
I left Deekula A and ended up at the same location as in this issue
Upon entering the back to the Sauna, there's only void, no way in or out.

**Comment by Nextej** [comment]
Entering any transition door on the outside level spawns you at the Canal Sauna scene, in the void.
