### ISSUE TITLE
playtest - 10L water bottle should cost more

### ISSUE THREAD

**Issue by pinkamedic** [loiste-interactive/Obenseuer-Issues#2465]
10L is alot of water but 16 OC is really cheap for that amount espicly when mineral water only costs 6, id say increase the price around 60-100OC or so, also mineral water should have the price increased aswell mostly cus its fancy mineral water

**Comment by Nextej** [comment]
going with the rule of selling more for less, the price of 10L bottle should not be more than 10x 1L bottles

**Comment by Zuntti** [comment]
changed
