### ISSUE TITLE
Playtesting - Inconsistencies with in-world display of 10L bottles

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#2466]
![image](https://github.com/user-attachments/assets/2c7e8015-a8eb-40d2-9538-af574b0ade85)
Additional notes:
- Having water in the bottle should still be slightly transparent, unlike it is seen on the shelf
- It kinda looks weird without any branding tape around the bottle, perhaps it could be made to match brand design of spring water bottle (without making the bottle fully white tho)

Edit: issue appears only if the Clean Water is in the container, other liquids so far appear to be displayed correctly.

**Comment by Zuntti** [comment]
Fixed
