### ISSUE TITLE
Drinking effects.

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#247]
Right now, the drinking effects are too strong, they seem to be as strong after one beer as after a whole series of them. It makes keeping up with the alcohol addiction rather annoying (in the very bad meaning of gameplay perspective) where you're practically out of the game, waiting in place for the effects to end, even after the light alcohols as beer.

My proposed changes would be having the effects as not as strong after one beer to the game remains pretty playable, with at last the center part of the screen clean and in-focus. Additionally the more advanced the addiction, the effects should be way lighter for a regular drinker on smaller amounts, for example: character with an addiction would have lighter effects after 3 beers than the character without the addiction.

**Comment by Oskutin** [comment]
I think the effect strength curve should be adjusted.

**Comment by Oskutin** [comment]
Added threshold of 15%
