### ISSUE TITLE
Playtesting - Banker's Lamp is doubled as two separate furnitures in the Mobelmann's stock

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#2470]
![image](https://github.com/user-attachments/assets/028ded23-fb23-4936-bdfe-4a5c8f58ecc7)

**Comment by pinkamedic** [comment]
this happens with alot of furniture not just this one

**Comment by Nextej** [comment]
Every instance should be reported

**Comment by pinkamedic** [comment]
i think its an issue with how objects are stored rather then the object themselves, ive had it happen with pallets, sleeping bags, deviders

**Comment by Zuntti** [comment]
Fixed
