### ISSUE TITLE
Playtesting - issues with signs

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#2481]
1. Pressing Down arrow adds new lines, infinitely it seems
![image](https://github.com/user-attachments/assets/809fe63f-4bee-4907-8bd8-c828dd0ca642)
2. While having multiple lines and pressing Down arrow, it does not move one line by line, instead it skips multiple of them
3. Adding new lines doesn't properly scale the text window, making it float outside of the sign
![image](https://github.com/user-attachments/assets/7050ef4a-87cd-47d3-ad42-84511466598f)
4. Editing a written sign automatically Selects All, making an addition of new text automatically replace what was there previously, it would be better if instead the text editor simply placed the text cursor after the last character and let player add or remove characters from there; The whole text should not be automatically selected (unless it's an empty sign).
5. Spaces are automatically treated as a new line separator in relation to the scale of the text, making it sometimes annoying to write what the player wants, it would be better if new lines were exclusively created when pressing Enter/Enter+LShift.
![image](https://github.com/user-attachments/assets/0e164cba-f1d7-4ed8-b1b8-01dd516a07ea)
6. Not having Enter as a text confrimation is counterintuitive, I suggest making Enter as the definite confirmation of the edited text, while assigning new line to Enter+LShift
   - If the sign was initially empty before editing (and only in this case), pressing ESC should save whatever player had written, as some people may intuitively press it after changing the sign's clean slate; in any other situation than this exception ESC should cancel text edition to what previously was written on the sign by the player.
7. Numericals and special characters are not having an appropriate font to match the text on the A-Board sign
![image](https://github.com/user-attachments/assets/91274dee-79ef-4e03-85e1-a8320abbfc9e)

   
The best way to recreate majority of the issue is to attempt a creation of a simple numerical list and use UP/DOWN arrows to move between the lines

**Comment by Nextej** [comment]
8. Small Label and Industrial Sign have problems of being placed on certain flat or angled surfaces of the other furniture (which is especially critical on chests and other storage)
![image](https://github.com/user-attachments/assets/576826f4-4853-487a-b877-d10c50f8580d)
![image](https://github.com/user-attachments/assets/84329b7e-adea-4860-a538-8dc8be66cbb5)
![image](https://github.com/user-attachments/assets/c9306601-8e2a-453b-bbb7-33e37529dcd3)
![image](https://github.com/user-attachments/assets/80717848-a30f-4e71-84a1-473bf49df22a)

**Comment by Oskutin** [comment]
Fixed pressing down key adding new lines
