### ISSUE TITLE
playtest - plank bed and shabby bed share same icon and model

### ISSUE THREAD

**Issue by pinkamedic** [loiste-interactive/Obenseuer-Issues#2498]
and for some reason shabby bed requires a terrarium/aquarium to make
![image](https://github.com/user-attachments/assets/6aaa70fa-4c6b-40de-ac20-1466c4ed53cd)
![image](https://github.com/user-attachments/assets/6420fc53-c023-42d0-b5e7-a5bbe12f1fe2)

**Comment by Zuntti** [comment]
Fixed
