### ISSUE TITLE
custom key issues in tutorial prompts

### ISSUE THREAD

**Issue by apterous123** [loiste-interactive/Obenseuer-Issues#25]
if you set custom keys for any of the buttons that tutorial teaches you, the tutorial wont update the custom keybinds and will show the default prompts.

**Comment by Oskutin** [comment]
You mean changing the keybindings when the tutorial dialog is visible?

**Comment by apterous123** [comment]
i change use keybind from e to f. tutorial still tells me to press e instead of the new custom bind, which is f.

**Comment by Oskutin** [comment]
Was the tutorial already visible when you changed the binding?

**Comment by apterous123** [comment]
it was new game after i changed the binds in previous one.

**Comment by Zuntti** [comment]
Seems to work for me? Changed e to f in main menu
