### ISSUE TITLE
playtest - not getting lockpick recipe from any source

### ISSUE THREAD

**Issue by pinkamedic** [loiste-interactive/Obenseuer-Issues#2503]
ive gotten the recipe in the mail but it only said i got it, when i went to go make some it said i didint have the recipe, i found a random recipe paper for lockpicking and the same thing it said i got the recipe but i didint actually have the recipe

**Comment by Zuntti** [comment]
Same as https://github.com/loiste-interactive/Obenseuer-Issues/issues/2195
