### ISSUE TITLE
Playtest - you can get two of pias head with the crazy neighbor

### ISSUE THREAD

**Issue by pinkamedic** [loiste-interactive/Obenseuer-Issues#2506]
when doing the part where you find the crazy neighbor with pias head you can get one from him (also you wont continu the questline when you get the head form him) you can then talk to the corpse to get another head (despite lacking a head already, doing this will also continue the questline) 
![image](https://github.com/user-attachments/assets/9dda14d3-5358-4af4-9231-53bdc7bc8730)

**Comment by Zuntti** [comment]
Fixed
