### ISSUE TITLE
Toilet blocks Apartment 16

### ISSUE THREAD

**Issue by ProProcastrinator** [loiste-interactive/Obenseuer-Issues#2507]
![20240803144023_1](https://github.com/user-attachments/assets/759d4cae-55ae-4a10-a24c-dffa229d9fe3)
![20240803144309_1](https://github.com/user-attachments/assets/7f8ea2ec-bcab-45be-baa7-3138e0a87fc7)

A "ghost" Toilet blocks Apartment 16, it can't be removed in cleaning mode.

Game Version 0.3.38

**Comment by ProProcastrinator** [comment]
[Slot1.rar.webm](https://github.com/user-attachments/assets/fff750fc-89d1-4ee1-a49c-06b83e9c5e1f)
i added a savefile. because github is stupid, i had to make add webm to upload the Slot Folder.

**Comment by ProProcastrinator** [comment]
https://github.com/user-attachments/assets/cd4f6376-e7b9-43d3-954c-1f53cb065b4c
toilet also derenders (?) at certain distance.

**Comment by ProProcastrinator** [comment]
i went in again and tried removing the spraypaint and after that the game registerd as normal.
i heard no sound when clicking the toilet.
the apartment now, shows up as cleard (?) i think.

**Comment by Zuntti** [comment]
Fixed
