### ISSUE TITLE
Player has to get a new number if exiting doctor's dialogue

### ISSUE THREAD

**Issue by gehube** [loiste-interactive/Obenseuer-Issues#251]
It would be better if the number stays valid when you are in the room.
I gave the doctor my number, I had to close the dialogue box so I could type in the console. You have to go outside the office to grab another number and wait to talk to him again.

**Comment by CBS-S** [comment]
Related: Spamming the number-taking machine and getting a whole bunch of tickets still only lets you in once, and if you actually need to get back in a second time you have to get yet another ticket. It would be funny - not necessarily good, but funny - if the door opened for 10 seconds every time you took a ticket and then closed automatically, then repeated itself if you took a bunch of tickets.

**Comment by Zuntti** [comment]
Fixed
