### ISSUE TITLE
[Playtest as of 8/4] Non-stolen detergent does not decrement charges on use

### ISSUE THREAD

**Issue by Tritiumisotope** [loiste-interactive/Obenseuer-Issues#2510]
before

![image](https://github.com/user-attachments/assets/a076015a-7d13-4b5a-a9db-babd93f145f9)

cleaning

![image](https://github.com/user-attachments/assets/e7112d41-6a1e-488d-b5ff-4bcfeba8df03)

after

![image](https://github.com/user-attachments/assets/f1a356a4-efce-4e8b-9207-65b949b1dd0e)

**Comment by Tritiumisotope** [comment]
Similar oddities may be occurring with matches per a conversation

**Comment by mojitopop** [comment]
I think the same thing also happens with disinfectant as long as you have one in the inventory you can get rid of an infinite amount of trash bags

**Comment by Zuntti** [comment]
Fixed
