### ISSUE TITLE
[Playtest as of 8/4] Not enough slots to display all the requisite materials for district heating

### ISSUE THREAD

**Issue by Tritiumisotope** [loiste-interactive/Obenseuer-Issues#2511]
As seen here, was not able to upgrade, some requirements per @Oskutin not being shown. Should readjust icon size when required material varieties exceed 12, or something.

![image](https://github.com/user-attachments/assets/ae7db5fc-5bac-4f65-ae3e-97f7521a15ab)

**Comment by Zuntti** [comment]
Fixed
