### ISSUE TITLE
[Playtesting] Pete Rantanen at the market square sits the wrong way when exiting the pharmacy

### ISSUE THREAD

**Issue by Taco-Cat1** [loiste-interactive/Obenseuer-Issues#2513]
https://github.com/user-attachments/assets/244530e0-3496-45e3-a847-e779725486ae

Skip to last three seconds. For whatever reason he tries to sit the wrong way before quickly snaping back to how he should sit

**Comment by mojitopop** [comment]
the same thing happens with the people eating at the pea soup place when you exit building A

**Comment by Taco-Cat1** [comment]
Actually it seems all sitting NPC's start the wrong way

**Comment by mojitopop** [comment]
it kinda seems like when the scene start that they are all "walking" a few centimers in a seated position toward their seat

**Comment by Zuntti** [comment]
Fixed
