### ISSUE TITLE
Crafting Fermenting barrels bug (Blue plastic barrel not being used)

### ISSUE THREAD

**Issue by THRACAZARD** [loiste-interactive/Obenseuer-Issues#2514]
when crafting the Fermenting barrel no blue plastic barrels are used. should be 1/1 not 1/0

![Fermenting barrel](https://github.com/user-attachments/assets/57a93c18-3409-42e3-afff-9232d74e2847)

**Comment by THRACAZARD** [comment]
Created a GitHub account to report this hope I did it right.
love the game keep it up.

**Comment by Zuntti** [comment]
Same as https://github.com/loiste-interactive/Obenseuer-Issues/issues/2358
