### ISSUE TITLE
[Playtest as of 8/6] Double Eliana glitch and more Eliana apartment furniture bugging.

### ISSUE THREAD

**Issue by Tritiumisotope** [loiste-interactive/Obenseuer-Issues#2519]
Missed these on my first Eliana test pass somehow, but found after trying to steal from her more on subsequent visits.

Double Eliana

![image](https://github.com/user-attachments/assets/381dfa09-892a-4631-9b94-de2ea2ee5a52)

Disappearing fixtures and furniture (LOD?)

![image](https://github.com/user-attachments/assets/0713f0d0-eb31-4bfa-9be6-c5d2c88cdb55)

**Comment by Zuntti** [comment]
Fixed
