### ISSUE TITLE
[0.3.39]- Issues with White and Green Rug 

### ISSUE THREAD

**Issue by Regal0** [loiste-interactive/Obenseuer-Issues#2524]
The rug uses the wrong icon in the furniture selection menu, and when picked up, turns into the old rug.
![Screenshot from 2024-08-08 13-19-01](https://github.com/user-attachments/assets/b59765f4-a7a8-4841-904b-d0116cffe419)

https://github.com/user-attachments/assets/ba9fde22-e929-4f36-8e41-84cb9dedb884

**Comment by Zuntti** [comment]
Fixed
