### ISSUE TITLE
Nightstand I placed in my apartment causes my game to crash when i look at it in build mode while using the move or take tool

### ISSUE THREAD

**Issue by UnfortunateBlooper** [loiste-interactive/Obenseuer-Issues#2525]
![20240808093721_1](https://github.com/user-attachments/assets/bf289f0f-970d-488c-99d2-2e6393176661)
this nightstand right here causes my game to crash whenever i try to pick it up or move it, if i even just hover my cursor over when in move or pick up mode it will instantly crash my game, this doesnt happen with any other furniture item i have in my apartment, just this one, there are no items in it or anything, i can even interact with it just fine while not in build mode, i can put items in it and take them out

Here is my save [Briggs_Rahtilaiva.zip](https://github.com/user-attachments/files/16549742/Briggs_Rahtilaiva.zip)
Here are logs [Player-prev.log](https://github.com/user-attachments/files/16549896/Player-prev.log) [Player.log](https://github.com/user-attachments/files/16549902/Player.log)

The version im in is 0.3.38

To reproduce it just turn on build mode and look at the nightstand while using the move or take tool 

I've had this nightstand there since the beginning of the game, i started my save before a lot of the more recent updates came up so that could possibly be it?? but none of my other containers i placed before those updates have this problem, it's ONLY this nightstand

**Comment by Zuntti** [comment]
Somehow, the night stand has the same night stand as a child furniture which causes an infinite loop. I fixed it so it can no longer crash the game. Here is also [Slot1.zip](https://github.com/user-attachments/files/16558078/Slot1.zip) where it's fixed. You can also fix it from some other save if you search 75e83047-b2e2-44b7-b2c2-82e94300a2ba7 from Interior Player Tenement.tnmt file and remove it from childFurnitureGUIDs list.

**Comment by UnfortunateBlooper** [comment]
> Somehow, the night stand has the same night stand as a child furniture which causes an infinite loop. I fixed it so it can no longer crash the game. Here is also [Slot1.zip](https://github.com/user-attachments/files/16558078/Slot1.zip) where it's fixed. You can also fix it from some other save if you search 75e83047-b2e2-44b7-b2c2-82e94300a2ba7 from Interior Player Tenement.tnmt file and remove it from childFurnitureGUIDs list.

thank you so much!! i've played a bit after, so i'll go in and fix it myself
