### ISSUE TITLE
[Playtesting] Escaping prison from the font door gives an absurd amount of crime points

### ISSUE THREAD

**Issue by Taco-Cat1** [loiste-interactive/Obenseuer-Issues#2526]
![20240805161158_1](https://github.com/user-attachments/assets/d842dcc8-75f1-4a25-b536-2ae0c9f173b3)
It could be intentional that the player gets a lot of crime points but I don't see a reason it should give 14 million crime points

**Comment by mojitopop** [comment]
I've tried to escape three times in a row and my bounty went up so high i had to pay a negative amount of RM lol

**Comment by Oskutin** [comment]
Fixed
