### ISSUE TITLE
[Playtesting] Npcs can gives coins to the player for playing the guitar from an unrealistic distance

### ISSUE THREAD

**Issue by Taco-Cat1** [loiste-interactive/Obenseuer-Issues#2527]
![20240808180254_1](https://github.com/user-attachments/assets/7321da7f-292f-48c8-8bf3-1648d1ae847a)

Note: I did not move after he gave me the coin. It seems unrealistic that he can just hand the player a coin from like 15 meters away. This can happen with any NPC

**Comment by Zuntti** [comment]
Fixed
