### ISSUE TITLE
{Playtest} - Best Plumbing Upgrade bug/issue

### ISSUE THREAD

**Issue by Defence-Cannon** [loiste-interactive/Obenseuer-Issues#2536]
When the upgrade finished I went to try to pay it off but for some reason it didn't want to proceed/Show the finish payment UI,
I have enough money for it.

Save and video attached for reference

[DaVey_McMulch.zip](https://github.com/user-attachments/files/16591658/DaVey_McMulch.zip)

https://www.youtube.com/watch?v=IvK7qODkuiw

**Comment by Oskutin** [comment]
https://github.com/loiste-interactive/Obenseuer-Issues/issues/2511 possibly related to this?

**Comment by Defence-Cannon** [comment]
I had no issues upgrading, 
I was able to upgrade and wait the specified time, then it didn't want to let me pay the RM amount. So my plumbing upgrade can't finalise on the tenement.

**Comment by Zuntti** [comment]
Fixed
