### ISSUE TITLE
[PLAYTESTING] can't speak to 2 vendors at the start of the game. v 3.40

### ISSUE THREAD

**Issue by LeLastpak** [loiste-interactive/Obenseuer-Issues#2542]
![image](https://github.com/user-attachments/assets/00616573-4c3e-4cf7-a802-2448f8b9b07f)
![image](https://github.com/user-attachments/assets/fc140682-20cc-401f-aff1-55b2c7dcebec)

I cant spreak to Henning Torskaevr and Lonkka Kurahaara. Other vendors I tried work fine so far.

**Comment by mojitopop** [comment]
If this is of any help? I can talk to them but I've migrated my save from 3.39 instead of making a new 3.4

**Comment by Zuntti** [comment]
Fixed
