### ISSUE TITLE
[PLAYTEST] Yeast in o-mart has gone moldy v 3.40

### ISSUE THREAD

**Issue by LeLastpak** [loiste-interactive/Obenseuer-Issues#2543]
![image](https://github.com/user-attachments/assets/c0a8dcbd-978a-4d42-81b9-d4f1a45837b9)

**Comment by LeLastpak** [comment]
![image](https://github.com/user-attachments/assets/51f961c2-b1e3-4df7-974e-e0af67f44cad)
other things too

**Comment by Zuntti** [comment]
Can I get a save where this happens?

**Comment by LeLastpak** [comment]
> Can I get a save where this happens?

**Comment by LeLastpak** [comment]
> Can I get a save where this happens?
[Slot5.zip](https://github.com/user-attachments/files/16634544/Slot5.zip)

**Comment by Zuntti** [comment]
Seems to to get fixed after waiting a day

**Comment by LeLastpak** [comment]
> Seems to to get fixed after waiting a day

i think the problem is that everything is getting spoiled in the refrigerator.

**Comment by Zuntti** [comment]
Fixed
