### ISSUE TITLE
[PLAYTESTING] Empty liquid containers disappear when i try it to fill it with mash. v 3.40

### ISSUE THREAD

**Issue by LeLastpak** [loiste-interactive/Obenseuer-Issues#2544]
![image](https://github.com/user-attachments/assets/95d07c9f-ca3b-440c-be7b-97434e206e78)

**Comment by LeLastpak** [comment]
Mash amount in the kettle stays the same. Its just the containers that disappear.

**Comment by LeLastpak** [comment]
![image](https://github.com/user-attachments/assets/00c697a2-6c22-4e7d-b2c6-ee51dec8a1e2)

Also it says that the max capacity is 10l, even though you can do a lot more than 10l.

**Comment by Zuntti** [comment]
Fixed
