### ISSUE TITLE
playtest - crazyneighbor doesn't kill you if you break into his apartment

### ISSUE THREAD

**Issue by pinkamedic** [loiste-interactive/Obenseuer-Issues#2545]
im asuming if you keep bothering him when you break into his apartment hes ment to kill you as you hear axe swinging noises but after the screen went black i just appeared outside his apartment completely fine, idk if this is how its ment to be or if he is ment to kill you

**Comment by Taco-Cat1** [comment]
He does deal damage to you though so after enough hits you will die
