### ISSUE TITLE
3.40 unpickable industrial shelves keep appartment 4 stuck at 99% cleared

### ISSUE THREAD

**Issue by mojitopop** [loiste-interactive/Obenseuer-Issues#2555]

**Comment by Zuntti** [comment]
Industrial shelves?

**Comment by mojitopop** [comment]
I meant Plywood Shelve sand uh- i just reloaded the save today and i managed to pick it up so idk if it's a bug or just a random quirk

**Comment by LeLastpak** [comment]
> I meant Plywood Shelve sand uh- i just reloaded the save today and i managed to pick it up so idk if it's a bug or just a random quirk

I had the same thing. I needed to reload the save to pick up/clean stuff again. Don't know how to replicate the bug.

**Comment by mojitopop** [comment]
i had the exact same issue again but on the floor upstair in the large appartment in the same exact spot except with a large wooden crate so idk if it has to do with items that are against the wall in that specific z axis level or what

**Comment by Zuntti** [comment]
Can I get Player.log?
