### ISSUE TITLE
 [Playtesting] Using an old save and having a tenant in apartment four (The Crazy Neighbors apartment) causes the tenant to be deleted

### ISSUE THREAD

**Issue by UnfortunateBlooper** [loiste-interactive/Obenseuer-Issues#2556]
I had Pate Rantanen living in apartment four while in version 0.3.38, when I updated to the current playtesting version, the neighbor took over, but when I look for Pate he was nowhere to be found. He does not reappear in his original spot 
![20240815142434_1](https://github.com/user-attachments/assets/a00dfbff-791b-4fa4-8c48-570c80f8384f)
 The Crazy Neighbor works fine so far on my old save, minus him deleting the old tenant.

**Comment by Zuntti** [comment]
Fixed, but you have to use a save before the crazy neighbor takes over the apartment to get it work
