### ISSUE TITLE
[PLAYTESTING] When you plant something, leave the area(go outside) and come back again. Plants are gone. 

### ISSUE THREAD

**Issue by LeLastpak** [loiste-interactive/Obenseuer-Issues#2557]
Before going outside:
![image](https://github.com/user-attachments/assets/4545365b-1a84-4f3d-a1ab-b097e9e51cfc)

After going outside:
![image](https://github.com/user-attachments/assets/cd370db2-d30c-4ce3-a99f-024dbf566b0a)
![image](https://github.com/user-attachments/assets/a5873513-26f2-42e0-b1ff-de4b1827e4cb)

**Comment by Zuntti** [comment]
Fixed
