### ISSUE TITLE
Got stuck between Anya's desk and Hanss's room

### ISSUE THREAD

**Issue by eetnaviation** [loiste-interactive/Obenseuer-Issues#256]
https://steamcommunity.com/profiles/76561198353613512/home/

Look at those two pictures

**Comment by Oskutin** [comment]
Link doesn't work

**Comment by eetnaviation** [comment]
https://steamuserimages-a.akamaihd.net/ugc/2022724735496063379/0D5C2EDF233F2CD14F371F6892C7289EB8F01463/?imw=1024&imh=575&ima=fit&impolicy=Letterbox&imcolor=%23000000&letterbox=true
https://steamuserimages-a.akamaihd.net/ugc/2022724735496062740/DC971238336D61C2CA7B9E6B14C8E6B7F0CE0944/?imw=1024&imh=575&ima=fit&impolicy=Letterbox&imcolor=%23000000&letterbox=true

Fixed images

**Comment by Oskutin** [comment]
Fixed
