### ISSUE TITLE
[PLAYTESTING] Can't move/take items or clean appartment.

### ISSUE THREAD

**Issue by LeLastpak** [loiste-interactive/Obenseuer-Issues#2560]
When i move objects in my main appartement. I'm unable to clean/move objects in the other apartments.

Before:
![image](https://github.com/user-attachments/assets/2f4e246b-e76d-4d05-a3d6-ce0392e7b994)

After I have moved some stuff in my personal appartement:
![image](https://github.com/user-attachments/assets/01675761-9cec-4f6a-a966-27bf58c082ea)

I can debug it by going outside first.

**Comment by Zuntti** [comment]
Same as https://github.com/loiste-interactive/Obenseuer-Issues/issues/2555
