### ISSUE TITLE
[PLAYTESTING] Can't remove an item or clean in Apartment 0.3.40 V2

### ISSUE THREAD

**Issue by LeLastpak** [loiste-interactive/Obenseuer-Issues#2562]
Same issue as in https://github.com/loiste-interactive/Obenseuer-Issues/issues/2560

But this time its with the shroomstuff on the ground that you clean with bleach and a random crate. the other items were removable.

**Comment by Zuntti** [comment]
I can't replicate this

**Comment by Zuntti** [comment]
Seems to happen when a item is taken from the top of the furniture without the build menu

**Comment by Zuntti** [comment]
Fixed
