### ISSUE TITLE
No foundation/flooring under the door into the Fine Apartment 1 extensions

### ISSUE THREAD

**Issue by UnfortunateBlooper** [loiste-interactive/Obenseuer-Issues#2565]
![20240816111009_1](https://github.com/user-attachments/assets/3453b217-fcfb-48d7-87bb-5d5c1ec1bc19)
![20240816111251_1](https://github.com/user-attachments/assets/4c11c079-c89c-476f-9867-efa0fc8671e3)
There's a really noticeable hole under the door. 
This is in version 0.3.38

**Comment by Zuntti** [comment]
Fixed
