### ISSUE TITLE
[Playtesting] Melee Weapon script is null!

### ISSUE THREAD

**Issue by N-G-Neer** [loiste-interactive/Obenseuer-Issues#2567]
I am unable to equip either my axe or my sledgehammer. I can drag them into the slot, the integrity bar shows up, but the 3D held model doesn't, and trying to left click doesn't do anything but produce the console message : "Melee Weapon script is null!"

Version : 0.3.40

**Comment by LeLastpak** [comment]
Update your game. a new version of 0.3.40 has been released with that bug fixed.

**Comment by N-G-Neer** [comment]
Yep, confirmed that it works now. Thanks !
