### ISSUE TITLE
[PLAYTESTING] When I sort my inventory in O-Mart while looking at goods, I get theft points. 0.3.40 V2 

### ISSUE THREAD

**Issue by LeLastpak** [loiste-interactive/Obenseuer-Issues#2578]
![image](https://github.com/user-attachments/assets/d747aa7e-a8e0-4c10-a95c-c590f41e6573)

The issue is prob happening because I have stolen items in my inventory. When I autosort without stolen items, nothing bad is happens.

When I put stolen Items in the green garbage container and take it back, I get theft points again.
![image](https://github.com/user-attachments/assets/cd7de9d8-64c8-42be-b2e5-33a60f3f04c4)

**Comment by Zuntti** [comment]
Fixed
