### ISSUE TITLE
Suggestion - Shortkey for filling liquid containers

### ISSUE THREAD

**Issue by LeLastpak** [loiste-interactive/Obenseuer-Issues#2579]
I suggest that the F-key could be a shortkey to fill the selected container if its empty.
![image](https://github.com/user-attachments/assets/b078e90a-5ccc-4c39-a8cd-b70087d60a71)

**Comment by Nextej** [comment]
Additionally being able to hold LMB and move cursor around the inventory to select containers for queue

**Comment by Zuntti** [comment]
Added
