### ISSUE TITLE
Playtesting - Preplaced fluid barrels in the playerment are marked as owned by default

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#2584]
I'd also make that barrels found on the stairwell/other apartments are not interactable until player picks them up and replaces in their own apartment/basement

**Comment by Oskutin** [comment]
Is this suggestion, or a bug?

**Comment by Nextej** [comment]
uh, both, most importantly a bug

**Comment by Zuntti** [comment]
Fixed
