### ISSUE TITLE
[PLAYTESTING] Found the lockpick recipe but didn't got the recipe. lockpicks still uncraftable

### ISSUE THREAD

**Issue by LeLastpak** [loiste-interactive/Obenseuer-Issues#2588]
![image](https://github.com/user-attachments/assets/1d209831-25c1-44ba-9600-ea56265a861e)
![image](https://github.com/user-attachments/assets/a6157dc1-f1a9-4f80-9167-b2e8cd332c73)
![image](https://github.com/user-attachments/assets/20d9d8c7-6573-4fe0-8268-674127ce6ce2)

**Comment by Zuntti** [comment]
Fixed
