### ISSUE TITLE
Movement occasionally jitters

### ISSUE THREAD

**Issue by Oskutin** [loiste-interactive/Obenseuer-Issues#259]
https://github.com/loiste-interactive/Obenseuer-Issues/issues/257
https://github.com/loiste-interactive/Obenseuer-Issues/issues/255
https://github.com/loiste-interactive/Obenseuer-Issues/issues/38
https://github.com/loiste-interactive/Obenseuer-Issues/issues/173

**Comment by Oskutin** [comment]
Related: https://github.com/loiste-interactive/Obenseuer-Issues/issues/242 ?

**Comment by Nextej** [comment]
The issue appears to be global in all places of a specific maps, those are `Interior Start, Interior Tenement Deekula A` and `Interior Tenement Deekula Mine Enterance` and seems to only happen when player is moving backwards and or sideways, but not when straight forward.

**Comment by CBS-S** [comment]
I can second that this is also my experience. Backwards seems to be the worst.

**Comment by CBS-S** [comment]
It also seems to be lighting-dependent; areas with more light sources seem to jitter more than ones with only a few.

**Comment by Zuntti** [comment]
Fixed
