### ISSUE TITLE
[Typo] The personal storage loading tip has some words that should be changed

### ISSUE THREAD

**Issue by Taco-Cat1** [loiste-interactive/Obenseuer-Issues#2593]
![20240818202330_1](https://github.com/user-attachments/assets/8206d058-48d3-4686-9ba4-f6cc9540de71)
The "To" towards the end should be changed to "For" so the final sentence looks like this. "You can buy or craft your personal storages for your apartment"

**Comment by Zuntti** [comment]
Fixed
