### ISSUE TITLE
Sugar beet juice not being made

### ISSUE THREAD

**Issue by enigmabread** [loiste-interactive/Obenseuer-Issues#2596]
on .3.38 have the buckets a few dozen sugar beets and the recipe for normal sugar is not showing up tried a few new games and same result 

![20240816000509_1](https://github.com/user-attachments/assets/3436c031-541f-4f7f-84c6-8a6c36c98853)
![20240816000525_1](https://github.com/user-attachments/assets/68131a81-2915-4243-8d28-4198e5d65f8e)

**Comment by Zuntti** [comment]
Already fixed
