### ISSUE TITLE
[playtesting] Police arresting you when you dont have a bounty

### ISSUE THREAD

**Issue by LeLastpak** [loiste-interactive/Obenseuer-Issues#2606]
Sometimes the police will chase you for only having stolen items in your inventory. This can happen during sleeping, even in a safe place like the hostel. The police will also keep chasing you after you got rid of the stolen items. The problem is that it is impossible to prevent jail because you don't have a bounty, so its also not possible to pay a fine. The player is always forced to go to jail. When you go to jail with 0 bounty, the jaildoor remains open causing the game to bug. This bug has been reported already.

**Comment by Oskutin** [comment]
fixed
