### ISSUE TITLE
[playtesting] People can spot you doing crimes behind doors 0.3.40 v3

### ISSUE THREAD

**Issue by LeLastpak** [loiste-interactive/Obenseuer-Issues#2617]
![image](https://github.com/user-attachments/assets/f91059cc-398b-4933-a0e9-f945b64a3151)

Meri Haka can spot men even though she is on her bed behind a closed door. NPC's have xray vision superpowers.

**Comment by Orphiex** [comment]
Had the same thing happen in Kolhola bldg on the 8th floor, except for me it wasn't Meri Haka but Sam Norton.

**Comment by Zuntti** [comment]
Fixed
