### ISSUE TITLE
[playtesting] Found a 1L mason jar. 0.3.40V3

### ISSUE THREAD

**Issue by LeLastpak** [loiste-interactive/Obenseuer-Issues#2618]
![image](https://github.com/user-attachments/assets/d3810627-0cb2-480d-ae94-1006351ed15a)

Shouldn't they be 2L now?

**Comment by LeLastpak** [comment]
![image](https://github.com/user-attachments/assets/1a416bf5-771b-45ad-8f08-a51b0d8bd860)

Okay its 2L it just doesn't tell you

**Comment by Oskutin** [comment]
fixed
