### ISSUE TITLE
Points of confusion

### ISSUE THREAD

**Issue by CBS-S** [loiste-interactive/Obenseuer-Issues#263]
-Question: Why does the game give you a hard time about using people's owned sinks but not their toilets or showers?
-Things that might be inconsistent but might just be cultural differences I as an American am not used to:
 -Why are the paint buckets so wide? I've never seen a paint bucket that was wider than it was tall.
 -Why do people own washing machines but not dryers?
-Weird: Turning off the oil lamp makes a sound like a light switch
-Bug?: Was dying of thirst, filled up a bottle with dirty water from the sink in A3 and immediately died. The notification was "died of suicide." What?

**Comment by Oskutin** [comment]
Some sinks (and others) may have mis-assigned owner.
Toilets and showers don't have inventory, hence not being ownable.

Others are cultural & regional things.
