### ISSUE TITLE
[playtesting] There is a bug when you buy 4 desinfects at the pharma and you checkout, 1 of the desinfects stays in you inventory and you cant buy it.

### ISSUE THREAD

**Issue by LeLastpak** [loiste-interactive/Obenseuer-Issues#2634]

**Comment by Oskutin** [comment]
Does this still happen?

**Comment by LeLastpak** [comment]
> Does this still happen?

i just tried it and its even more wacky
![image](https://github.com/user-attachments/assets/fd39d5d2-fef6-4f5c-9cb1-f33a640916a0)

i picked up 4 bottles. 5 showed on the table and one of them is still on the table
![image](https://github.com/user-attachments/assets/bad05325-2897-4b30-8e29-aced824d1e23)

![image](https://github.com/user-attachments/assets/3412091f-7cf3-4025-b39b-6d5c5bb49267)

**Comment by LeLastpak** [comment]
When i pick it up i cant buy it. I can run away with it tho. FREE DESINFECTANT!!!
![image](https://github.com/user-attachments/assets/08338e5e-b508-455a-b321-696bb8d6975c)

**Comment by LeLastpak** [comment]
I reloaded the autosave and noticed the extra bottle was always there. So its prob the old bottle i could never buy. I think everything is fine now. Needs more testing on a new save game i think to be sure.
