### ISSUE TITLE
[playtesting] The hose in the shabby basement sauna gives dirty water instead of clean water.

### ISSUE THREAD

**Issue by LeLastpak** [loiste-interactive/Obenseuer-Issues#2637]
![image](https://github.com/user-attachments/assets/8f474460-5765-4924-ba34-97a2ac09ca66)

The shower in the basement is in clean water. And so is my bathroom.

**Comment by LeLastpak** [comment]
My plumbinglevel is only dirty. But it allows the player to upgrade the bathroom to cleanwater.

**Comment by Oskutin** [comment]
Save?
