### ISSUE TITLE
Tripod Camera cannot be placed anywhere, collides with terrain.

### ISSUE THREAD

**Issue by Kyo21943** [loiste-interactive/Obenseuer-Issues#2641]
Happens on any location within the tenement.
Tested in v. 0.3.38
![20240825225256_1](https://github.com/user-attachments/assets/33334776-2cc4-4a5e-94b6-e936e4014fba)

**Comment by pinkamedic** [comment]
a few other objects have this issue too, the chainsaw for one

**Comment by Zuntti** [comment]
Fixed
