### ISSUE TITLE
[Typo] Typos in character dialogue

### ISSUE THREAD

**Issue by Taco-Cat1** [loiste-interactive/Obenseuer-Issues#2647]
![20240820212255_1](https://github.com/user-attachments/assets/7e5f9fba-99cc-4116-b4d4-a3e5db2e1807)
(Typo found after the word you)
som ething should be changed to something

![20240820213041_1](https://github.com/user-attachments/assets/0730a085-c942-4919-a15d-ad39536c5323)
(Typo found at the very end)
to day should be changed to today

![20240824010335_1](https://github.com/user-attachments/assets/a761d28d-aa14-4763-863f-5fd48c38e651)
Not a typo but "us" should be changed to "me"

**Comment by Zuntti** [comment]
Fixed
