### ISSUE TITLE
[Playtesting] Even after drinking everything in a small glass bottle the stats act as if the bottle still had a liquid

### ISSUE THREAD

**Issue by Taco-Cat1** [loiste-interactive/Obenseuer-Issues#2650]
![20240820195934_1](https://github.com/user-attachments/assets/2c9fe96f-a303-496e-a468-97597105ffc3)
I believe there was urea solution in this one. The stats stay the same even after closing the inventory, clicking on something else and even entering a new loading zone. It will only change after you fill it with something else

**Comment by Oskutin** [comment]
fixed
