### ISSUE TITLE
[Playtesting] Traveling to another are of the game except the outside causses all renovation times to skip foward

### ISSUE THREAD

**Issue by Taco-Cat1** [loiste-interactive/Obenseuer-Issues#2664]
I know this was reported and fixed a few weeks ago but at least for me it still happens whenever I enter a new area of the game. It also feels like cheating

**Comment by pinkamedic** [comment]
can confirm that this is happening

**Comment by Oskutin** [comment]
On a new saved?

**Comment by Taco-Cat1** [comment]
Yes even on old saves

**Comment by Zuntti** [comment]
Fixed
