### ISSUE TITLE
[playtesting] Mushroom coffee might be bugged

### ISSUE THREAD

**Issue by LeLastpak** [loiste-interactive/Obenseuer-Issues#2665]
![image](https://github.com/user-attachments/assets/940d0ea0-22f3-4457-b92f-4b9842da8627)

I found some quality mushroom coffee but my character doesn't like it. Normal coffee seems to be better. Also on a different character, i dont have mushroom addiction and the mushroom coffee is a lot more tasty. Is it possible that there is a mistake?

Right now magic addicts dont like mushroom coffee and non-magic addicts do like mushroom coffee. I believe it was suppose to to be the other way around?

**Comment by Oskutin** [comment]
Fixed shroom coffee not having shroom in it
