### ISSUE TITLE
[Playtesting] Even after renting a room in the Barrack Hotel the bed is still marked as owned

### ISSUE THREAD

**Issue by Taco-Cat1** [loiste-interactive/Obenseuer-Issues#2674]
![20240830184836_1](https://github.com/user-attachments/assets/f99a1563-ac77-4629-bb1a-e0db600a13bb)
I will say that this is an older save from 0.3.40 but I don't think that should affect it.

Might be related to
 #2673

**Comment by Oskutin** [comment]
Fixed
