### ISSUE TITLE
[Playtesting] Sometimes the colour of a renovation icon is wrong

### ISSUE THREAD

**Issue by Taco-Cat1** [loiste-interactive/Obenseuer-Issues#2676]
![20240830165849_1](https://github.com/user-attachments/assets/d7a9d818-e53f-4298-af40-5760ebfe17fa)
According to the colour of the icon I should have enough resources to upgrade the stairwell however clicking on the icond shows a different story
![20240830165856_1](https://github.com/user-attachments/assets/dc99827b-268b-40db-bd7c-d19b91f09b2b)
Exiting the Tenement tab and going back in does fix the issue but it's still pretty annoying not knowing if the icon is lying or not

**Comment by Zuntti** [comment]
They don't seem to update when starting the upgrade

**Comment by Zuntti** [comment]
Fixed
