### ISSUE TITLE
[Minor] Teuvo Skogman in the market square is labeled as ??? when talking to him

### ISSUE THREAD

**Issue by Taco-Cat1** [loiste-interactive/Obenseuer-Issues#2677]
![20240824010907_1](https://github.com/user-attachments/assets/12a6f534-353d-4fa8-bcbb-28b2c231724c)

![20240824010915_1](https://github.com/user-attachments/assets/6c808b03-ebbc-4db6-ada7-e360917c0024)
Just a small inconsistency

**Comment by Oskutin** [comment]
Fixed
