### ISSUE TITLE
[playtesting] bug with rightclick dragging liquidcontainers

### ISSUE THREAD

**Issue by LeLastpak** [loiste-interactive/Obenseuer-Issues#2680]
![image](https://github.com/user-attachments/assets/fa5b4dcd-458f-483f-a106-0705d14b1e9f)

if you rightclick drag the left jar towards the right jar

![image](https://github.com/user-attachments/assets/10df3207-85ce-4658-8dd7-c3a87184388c)

only the liquid of 1 jar gets transporterd to the right jar.

**Comment by LeLastpak** [comment]
![image](https://github.com/user-attachments/assets/e345403b-3c23-4ba4-9803-c5623c86e80c)
its the same with doing it from a closet/chest. when you hold rightclick to take a jars.
![image](https://github.com/user-attachments/assets/4e207018-2277-47ca-a166-ebc3188fe75e)
it leaves 3 empty jars, only 2 liter in a jar in you personal inventory and an empty jar.

**Comment by Oskutin** [comment]
Might be duplicate issue, but i'll keep this open, as the dupe is ancient
