### ISSUE TITLE
[Typo] Typo in a note name

### ISSUE THREAD

**Issue by Taco-Cat1** [loiste-interactive/Obenseuer-Issues#2681]
![20240901142142_1](https://github.com/user-attachments/assets/6ed8a49e-b168-4bb5-9ac8-3342f4a99cbf)
 
hanas should have a capital "H" and also the note titles are very inconsistent with capitalization as in some capitalize the first letter of all the words, some only do the first letter

**Comment by Oskutin** [comment]
Fixed
