### ISSUE TITLE
[Playtesting] Facemasks causing hygiene drop while still clean

### ISSUE THREAD

**Issue by Orphiex** [loiste-interactive/Obenseuer-Issues#2686]
When equipping a new, 100% facemask, the hygiene decay rate stays normal. However, at around 85% condition, wearing a facemask causes your hygiene to start dropping at an alarmingly fast rate; this hygiene drop stops when the facemask is unequipped, and restarts when the mask is re-equipped. This issue is repeatable.

Now, if hygiene started dropping when the facemask reaches 0%, that would make sense. So I'm assuming that this effect is deliberate, and is just triggering early for whatever reason. If there's some external factor that causes the mask to be unhygienic - say, having just walked through a spore cloud - then it would be helpful if the now-contaminated facemask could have an icon added to its Inventory window showing its now-useless state.

**Comment by Oskutin** [comment]
Possibly fixed it now.
