### ISSUE TITLE
[Playtesting] Super Flashlight battery drains when entering buildings

### ISSUE THREAD

**Issue by Orphiex** [loiste-interactive/Obenseuer-Issues#2687]
When entering a location from the main map, while holding and using the Super Flashlight, the battery life drops by a variable amount (approx. 70-80%). Has been tested while entering Deekula A, B and C. Does not cause battery drain if holding, but not using, the Super Flashlight. Does not cause battery drain when leaving the buildings to the main map. Repeatable.

**Comment by Zuntti** [comment]
Related to this https://github.com/loiste-interactive/Obenseuer-Issues/issues/2705 I think
