### ISSUE TITLE
[Playtesting] The cabinet under the sink in Deekula B is marked as stealing

### ISSUE THREAD

**Issue by Taco-Cat1** [loiste-interactive/Obenseuer-Issues#2689]
I don't remember the exact apartment number but it's the one with two floors and with the eviction notice on the door. The person on the couch says you can take anything except what's behind the TV but he's lying.
![20240820205127_1](https://github.com/user-attachments/assets/0f9ce8e3-d5b1-4353-a0de-887e8f87d749)
Only the sink counts has theft.
![20240820205131_1](https://github.com/user-attachments/assets/a4d0cb2f-1985-4ce7-927b-2629f99bdacf)
Nothing else does.

**Comment by Oskutin** [comment]
Fixed
