### ISSUE TITLE
Deekula A basement door auto-locked

### ISSUE THREAD

**Issue by CBS-S** [loiste-interactive/Obenseuer-Issues#269]
Not sure when this happened, but the Deekula basement door locked me into Deekula A. I had to use the console to unlock it, but it stayed unlocked after that when I reloaded the save. I think this is a dupe of #190 but I'm resubmitting it because that one was marked fixed and it happened to me again just now, even though Steam said the game updated today.

**Comment by Oskutin** [comment]
Update is not pushed yet
