### ISSUE TITLE
Playtesting - Empty mason jars duplicating homemade booze when moved to inventory

### ISSUE THREAD

**Issue by CocoaMuggins** [loiste-interactive/Obenseuer-Issues#2692]
I was fermenting different kinds of booze and I put a bucket and a stack of mason jars in a fermenting barrel with 10L of booze and pressed 'Fill'. It filled the bucket and one mason jar with 9L of the booze. I pressed 'Fill' again to fill a second mason jar with the remaining 1L of booze. I ctrl-clicked the booze to my inventory then I ctrl-clicked the empty mason jars to inventory. The empty jars were moved to the slot with the 2 filled mason jars and it duplicated the booze into the remaining empty jars. This left me with 1 bucket filled and 8 mason jars filled when I should've only had 1 bucket filled and 2 mason jars filled. I re-created this exact dupe bug in the fermenting bucket as well. 
I was playing in the main branch, not experimental/beta. I'm unsure if this has been fixed since but thought I'd mention it

**Comment by Oskutin** [comment]
https://github.com/loiste-interactive/Obenseuer-Issues/issues/2680 likely related
