### ISSUE TITLE
Feedback - Prices in vending machines (softdrinks and osmo olut) should be higher than in O-Market for the same products

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#2698]
Currently it is the other way around, the prices in vending machines should be higher, as they are much more easier and quicker to access than the O-Market. Player should be incentivized to buy from O-Market in the early game more often than from the vendings.

I propose switching around O-Market prices with vending ones, if not making vending ones much higher.

**Comment by Zuntti** [comment]
Changed
