### ISSUE TITLE
[Playtest] 'Timeskip' issue

### ISSUE THREAD

**Issue by Bonskee** [loiste-interactive/Obenseuer-Issues#2705]
I've seen some mentions of this bug already, but I decided to see if anything else was affected.
This 'timeskip' bug appears to happen when entering any interior or when a previous save is loaded.
I have not tested whether this occurs with all ingame interiors, however, every interior tested seems to be affected.
This is tested on a new save _(as well as an old save updated to the new playtest version)_ and is easily replicated.
So far I have found that these are affected:

- Tenement Construction Time (discussed in #2664 and #2628)
- Mushroom high stat/Alcohol in blood stat
- Hygiene while wearing a mask

Firstly, is the tenement construction time: 

Re-loading a save with an active construction timer regularly 'skips' the time required for the completion of the construction forward by 11hr30m.

![pre load 1](https://github.com/user-attachments/assets/3f388f4a-13a1-4716-85c1-4c2489483d2a)
![post load 1](https://github.com/user-attachments/assets/6529efba-4776-4240-9c51-8c4daf88a618)
![post load 2](https://github.com/user-attachments/assets/7b473322-d21b-4a99-a7b7-aad535906aff)
![post load 3](https://github.com/user-attachments/assets/7ee00b5d-9ab9-418c-9408-683ccf27f866)
![post load 4](https://github.com/user-attachments/assets/903a44a9-5352-43c3-b678-eb27e7d609b1)

The above pictures are with repeated saves and reloads and as seen 'skip' the time forward.

Interestingly, the amount of time that is 'skipped' is inconsistent when loading into interiors, with 'timeskips' ranging from 2hr to 8hr.

Secondly, is the Mushroom high stat/Alcohol in blood stat:

![pre load affects](https://github.com/user-attachments/assets/31913790-71b5-4260-9155-0205b53460c3)
![post load affects](https://github.com/user-attachments/assets/17d93a61-6680-4db3-8511-14c793ae0d31)

I can't say to the degree of 'timeskip' that occurs in these instances, but I believe that it would be associated with the above.

Finally, is hygiene while wearing a mask:

![hygiene pre interior](https://github.com/user-attachments/assets/7a083729-e5f4-481c-bc6a-2d2e88036f55)
![hygiene post interior](https://github.com/user-attachments/assets/07040cec-942f-43d8-af18-571ff34596cb)

The amount that the hygiene stat is affected depends on the percentage of the mask (i.e. low percentage masks lead to a larger drop in hygiene)

Edit: Time taken for a new tenant to move into an apartment (as well as evicting a tenant) is also affected.

**Comment by Bonskee** [comment]
Time taken for a tenant to move into a new apartment is also affected

**Comment by Zuntti** [comment]
Fixed
