### ISSUE TITLE
Sauna damage timer runs even while in main menu

### ISSUE THREAD

**Issue by MasterBismuth** [loiste-interactive/Obenseuer-Issues#2714]
When using the pier sauna, if the player presses escape to open the main menu and pause the game once the sauna stove has been lit, the timer to begin the sauna damaging/killing the player seems to continue accumulating even though the game is theoretically paused. If one stays on the main menu for a long enough amount of time, one can enter the damage or death state near instantaneously upon unpausing, even if the sauna temperature hasn't risen high enough for the stove rocks to make steam yet.

The issue seems to be repeatable.

Game version is V. 0.3.38

**Comment by Oskutin** [comment]
already fixed in new
