### ISSUE TITLE
Greyed-out dishwasher inventory

### ISSUE THREAD

**Issue by OstinFas** [loiste-interactive/Obenseuer-Issues#2723]
This happens on v.0.3.38.
![dishwasher greyed out](https://github.com/user-attachments/assets/019035ff-6379-4ba5-b7d7-4171277fdff5)

I have a dishwasher in my flat that works fine the first time I open it after loading in from outside or the load menu, but on the second time onwards its inventory shows grey tiles I can't interact with. It currently contains washing powder, a 20L jug, and computer parts, all stolen, the latter being cleaned.
The washing sound still plays while in that state, and I confirmed by saving/loading that cleaning still progresses.
Powering it off breaks it further as it can't be turned back on even after quickloading (I can still access inventory once as described above).
Picking it up and placing it down doesn't fix it, though the game remembers it has items left inside.

[Player.log](https://github.com/user-attachments/files/17319943/Player.log)
[Player-prev.log](https://github.com/user-attachments/files/17319944/Player-prev.log)

Thanks for your time, and good luck.

**Comment by Zuntti** [comment]
Fixed in playtest
