### ISSUE TITLE
[Feedback/Playtesting] Player should not be able to sit on the bench with the cat

### ISSUE THREAD

**Issue by Taco-Cat1** [loiste-interactive/Obenseuer-Issues#2726]
![20241009163939_1](https://github.com/user-attachments/assets/235ca8e0-18cc-4efc-a8ec-3a6e08f46cd0)
Right now it looks like the player is sitting on the cat

**Comment by pinkamedic** [comment]
nah make it into an event, where if you sit on the cat you end up killing it and everyone in the room beats you up killing you

**Comment by Taco-Cat1** [comment]
That would be very funny

**Comment by Zuntti** [comment]
Fixed
