### ISSUE TITLE
Player oofs himself - without approval

### ISSUE THREAD

**Issue by SaladSauce** [loiste-interactive/Obenseuer-Issues#2729]
I'm not trying to be funny, dont know if github has censuring for "certain topics" so I had to meme it

in short I entered the tenant and every need starts going into overdrive
heres a vid

https://github.com/user-attachments/assets/94e93a79-3292-463a-bc4b-8bf8f016296e

and safe file
[SelfEnding.zip](https://github.com/user-attachments/files/17356009/SelfEnding.zip)

its not a major issue, I came back later in the day and it was fine

**Comment by SaladSauce** [comment]
forgot to add that I was in the middle of installing power to my home

**Comment by Zuntti** [comment]
Have you changed in game time scale from the console? It seems to be 150 in your save. Default is 1

**Comment by SaladSauce** [comment]
> Have you changed in game time scale from the console? It seems to be 150 in your save. Default is 1

I have no idea how to even open the console
I just came into the tenant and my char. when into a need spiral but if that's what happen, then something in the game changed it

**Comment by Zuntti** [comment]
The source of the bug is outside. Backyard police tried to arrest you when you changed the map. This may have been fixed in the playtest
