### ISSUE TITLE
Can't fuel Machine "Spirits"

### ISSUE THREAD

**Issue by SaladSauce** [loiste-interactive/Obenseuer-Issues#2730]
Mash Tun and machines where any kind fuel is required is blacked out and NOT interactable
![Capture](https://github.com/user-attachments/assets/3aea0356-89c1-4a36-8a50-c96da47980c1)

There's a workaround https://steamcommunity.com/app/951240/discussions/0/4513254014351719404
but its a real pain to do this twice every game day

**Comment by Zuntti** [comment]
Fixed in playtest
