### ISSUE TITLE
Mashing Tun never finishes

### ISSUE THREAD

**Issue by Jacket80** [loiste-interactive/Obenseuer-Issues#2731]
![image_2024-10-14_151755249](https://github.com/user-attachments/assets/d8803331-59e6-4bff-b6f7-25e8f90e1ec4)

Its at 100% but it dont count as finish, you need to abort to be able to finish the process, ruining your mash
(srry bad entglish)

**Comment by SaladSauce** [comment]
I had this same issue too

**Comment by Zuntti** [comment]
This may have been fixed in the playtest version. Can you send a save where this happens?
