### ISSUE TITLE
Playtest: The guy in Tenement A A6 doesn't have any dialogue option related to "The disappearance of Alice" quest

### ISSUE THREAD

**Issue by KabanFriends** [loiste-interactive/Obenseuer-Issues#2735]
![image](https://github.com/user-attachments/assets/3c3a0671-2677-4860-bd38-dbc4797ea27b)
https://discord.com/channels/478514341176672267/510482630278512640/1295797649869639820
According to the conversation around this in Discord this NPC is supposed to give me options to progress the quest, but that's not happening to me

Save: [Slot1.zip](https://github.com/user-attachments/files/17382298/Slot1.zip)

**Comment by Zuntti** [comment]
Fixed
