### ISSUE TITLE
Error with save system

### ISSUE THREAD

**Issue by Jacket80** [loiste-interactive/Obenseuer-Issues#2736]
https://github.com/user-attachments/assets/9deeb551-040c-4885-a06f-d3053dc5c737

I use slots 1, 2, 3, 9 and 10 to save my games, for some reason my saves in slot 1 and 2 have disappeared, and now I'm unable to even make a save in those slots, all of the other slots are completely fine, i don't know what cause the lost of my files and the inability to use them, as i just close the game and when i started it and entered to play this was what happened

**Comment by Zuntti** [comment]
Can you send the save files from "\Users\ [username] \AppData\LocalLow\Loiste Interactive\Obenseuer"?

**Comment by Zuntti** [comment]
For some reason the Info.tnmt files are empty, but other files are fine

**Comment by Zuntti** [comment]
Fixed not being able to select corrupted slots

**Comment by Zuntti** [comment]
Maybe Steam Cloud is causing this?
