### ISSUE TITLE
[Playtest Ver 0.3.41] "Your Cat" De-spawns if you enter the unfinished basement from the outside entrance

### ISSUE THREAD

**Issue by Tshepha** [loiste-interactive/Obenseuer-Issues#2738]
The "Your Cat" you get from picking the starting cat perk during the interview seems to consistantly de-spawn for me whenever I enter the basement from the outside entrance for the first time. Im unsure if its falling into the void but ive been able to reproduce this bug several times by doing the following:

1. Start new game
2. During the interview pick the perk that gives you a starting cat
3. Head to the apartment complex once you are out of the starting room
4. Go inside the apartment complex and check that "Your cat" has spawned
5. Head back outside
6. Enter the basement through the outside entrance
7. Leave the basement through the same entrance
8. Enter apartment complex
9. Your cat no longer seems to exist

Some other things i noticed that might help locate the problem: 
Sometimes picking the cat up and placing it back down or dropping it stops it from dis-appearing but its not consistant. 
Going into the basement first without entering the apartment first also seems to make "your cat" despawn. 
Ive tried spawning "your cat"s from the console and the ones spawned from the console dont seem to disappear only the original that was recieved from the interview question perk seems to. 
The pathfinding of the original "your cat" without being picked up and placed/dropped has it regularly walking into the stairwell on my saves, maybe this is causing the cat to fall into the void when the unfinished basement is loaded?  Picture below
![image](https://github.com/user-attachments/assets/5550710c-20a8-48e3-a1bc-ca7131b72e2c)

Ive not tested if fixing the basement before entering it from the outside entrance stops the cat from despawning.

**Comment by Zuntti** [comment]
Fixed
