### ISSUE TITLE
Old Bathtub With Soil and Support dismantles into 0 Old Bathtubs

### ISSUE THREAD

**Issue by MayBloon** [loiste-interactive/Obenseuer-Issues#2739]
When you dismantle Old Bathtub With Soil and Support you get back 0 Old Bathtubs and it adds an Old bathtub slot in owned furniture for it with an amount of 0.
![no old bathtub](https://github.com/user-attachments/assets/d16aaead-9521-4ce1-ba54-24bac2a658c9)

**Comment by Zuntti** [comment]
Fixed
