### ISSUE TITLE
Liquids disappear from containers placed in the world

### ISSUE THREAD

**Issue by vulpes133** [loiste-interactive/Obenseuer-Issues#2740]
I have noticed that certain containers, when placed in the world and having the area reload, either by leaving the area and returning to it, or by saving and loading within the area.
The containers that I've noted to be affected by this bug are as follows.
•Plastic Bottle
•Large Plastic Bottle
•Glass Bottle
•Cup
•Plastic Bucket
![image](https://github.com/user-attachments/assets/9fdc82d3-162b-41be-9d91-e9ab0884a16c)
![image](https://github.com/user-attachments/assets/859794a6-b6c9-47d0-9807-f86093764a3a)

**Comment by TonyFromRomania** [comment]
this is probably the oldest bug i know when comes with this  game, started seen it as early as when i first started playing

**Comment by Zuntti** [comment]
Fixed
