### ISSUE TITLE
Minor visual bug, Hostel Warehom

### ISSUE THREAD

**Issue by Thomathnan** [loiste-interactive/Obenseuer-Issues#2743]
![image](https://github.com/user-attachments/assets/8969fb3f-f25f-495d-aa0a-eb222cb9ce33)
In the Kolhola box hotel, a purple square can be seen through a doors window into what I assume is the managers office. The bug seems to appear only when past the table without a person sitting at it, and can be seen anywhere beyond that point. If you walk on the table, you can see that it disappears when you get too close to the edge. Issue has persisted through saving and quitting, as well as reloading saves. I have not tested if it persists through a restart. Version 0.3.38

**Comment by Zuntti** [comment]
Fixed
