### ISSUE TITLE
Playtesting / suggestion - Orange Heaven outcome enhancement 

### ISSUE THREAD

**Issue by pinkamedic** [loiste-interactive/Obenseuer-Issues#2745]
after getting malone killed you should get his chair as a reminder of what you have done, the chair should also be covered in blood and you shouldint be able to sell it to anyone as its permanent reminder of what the player has done, you can never get rid of it but you can place it. also it needs a grim description to further guilt the player

**Comment by Zuntti** [comment]
Added
