### ISSUE TITLE
Playtesting - minor typo in Malone's Orange Heaven dialogue "She" --> "He"

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#2746]
![image](https://github.com/user-attachments/assets/110b0bb7-2c4e-4153-8620-3032d3cd4c76)

**Comment by Nextej** [comment]
![image](https://github.com/user-attachments/assets/bd58d1bc-da61-4041-83e0-d43ace1db0a9)

lack of space between "I'm" and "NOT"

**Comment by Zuntti** [comment]
Fixed
