### ISSUE TITLE
Playtest 0.3.42 Coffee maker deletes items

### ISSUE THREAD

**Issue by Leiaviathan** [loiste-interactive/Obenseuer-Issues#2748]
Referring to the higher quality machine, not tested with the cheaper one as I currently don't have one.
Placed an empty cup into coffee maker and it instantly disappeared.
Tried with an empty mason jar, was able to start making coffee, but after it was finished the jar with its content vanished as well.

**Comment by Pangaron** [comment]
Can confirm with a basic one as well. Easy to reproduce by adding several cups inside. After closing and reopening UI, some of them (usually 2) disappear with each repeated action. Tested with both an old (upgraded from prepatch) and a newly bought coffee machine. The chemistry station possibly suffering also some similar issues, will check later and create a separate if necessary, but item loss (or duplication) possibly affects more production stations.

**Comment by TonyFromRomania** [comment]
i used the chem station while making yeast from found dough, no issues there beside the usual low skill yeast making fails

**Comment by Zuntti** [comment]
Fixed
