### ISSUE TITLE
Playtesting - Mobelmann's furniture store ui is broken, cannot buy anything.

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#2751]
![image](https://github.com/user-attachments/assets/0c228ec9-5efe-464f-a151-a164b5aaff19)

**Comment by TonyFromRomania** [comment]
ah yes it happened to me too but it reverted son after i unloaded ad reloaded the deekula C map

**Comment by Pangaron** [comment]
Same issue, clean new game, first day, cannot get the UI work properly. Save and reload does not help, exiting and re-entering building does not help either, but completely closing the game and loading fixed the issue for now.

**Comment by Zuntti** [comment]
Fixed
