### ISSUE TITLE
Playtesting 0.3.42 Cat cage is broken

### ISSUE THREAD

**Issue by Leiaviathan** [loiste-interactive/Obenseuer-Issues#2752]
This cat cage was placed with cats inside of it before the recent update. 
Cats are still visible from the outside, but no longer accessible when opening the cage inventory.

![Screenshot (787)](https://github.com/user-attachments/assets/aeabb432-70db-4401-a5bb-8c51f7d0fe80)
![Screenshot (786)](https://github.com/user-attachments/assets/9f6ebe6c-c50e-4a5b-8505-67688761f13e)

**Comment by TonyFromRomania** [comment]
yea an you cant add new cats to the cage ether, plus the planting UI bug is almost similar with that but you cant plant the seed or even see them after exiting and reentering, wont be surpirsed if almost all stations have this UI bug

**Comment by Pangaron** [comment]
For me, this applies to chicken coop too, as well as any planting spot - no recipe to add appears and when closing UI and reopening it, the area is greyed out, no items are visible there, but they are still there as when storing the coop or planter, warning is displayed on the item that it contains item and cannot be sold. It blocks production completely.

**Comment by TonyFromRomania** [comment]
and i have a suspicion that the aquarium and terrarium may also have this bug witch is a huge stop for any alcohol production

**Comment by Pangaron** [comment]
Yes, can confirm for aquarium, terrarium and rat cages too, so basically all biological production. Have not tested the furnace and bio yet (need gas), but I presume those will work.
Got Object reference when opening any of the concerned UI's 
![image](https://github.com/user-attachments/assets/aa976d4c-c950-46b7-a9b8-d7d49dfa2ab0)
Although the save file I am playing currently was updated from previous versions, I have purchased new production items, so this is not related only to old facilities not being upgraded properly. Will try on a completely fresh save too, but will take some time.

**Comment by TonyFromRomania** [comment]
bio reactor works fine didnt tested the furnace ether been that i never got one yet of my curent update made save

**Comment by Oskutin** [comment]
Can I have the logfile and save?

**Comment by Pangaron** [comment]
[Slot9.zip](https://github.com/user-attachments/files/17498880/Slot9.zip)
[Player - Copy.log](https://github.com/user-attachments/files/17498886/Player.-.Copy.log)
This one is from a clean save, first day, freshly bought small rat cage, placed, added two rats, no recipe, closed UI, reopened and UI broke.

**Comment by Leiaviathan** [comment]
Can confirm terrarium is not working. Was able to harvest crops that had been planted prior to update, but the UI looks like the chicken coop. 
[Slot1.zip](https://github.com/user-attachments/files/17498917/Slot1.zip)
Not sure if my log file is useful, as I did some further testing (regarding Stuck furniture issue #2755) since that last save, so I'll be uploading it there asap

**Comment by Zuntti** [comment]
Fixed
