### ISSUE TITLE
Playtesting 0.3.42 Furniture in tenement is stuck (move/take not working)

### ISSUE THREAD

**Issue by Leiaviathan** [loiste-interactive/Obenseuer-Issues#2755]
### All of the furniture that I placed prior to the update is stuck in place:

- Objects are highlighted green as usual, but can't be moved/taken 
- Small items that go into players inventory can be collected just fine
- Trying to move/take furniture with small items placed on it results in the small items being collected into player inventory
- Issue affects players apartment, hallway, basement and roof

<details>
  <summary>SPOILER for Orange Heaven task, but related to furniture (click) </summary>
After Malone was killed and taken out of the apartment, I was able to gather his personal belongings.
There is one bug though: The radio keeps playing after being taken. I tried leaving/entering the building, tried saving and reloading, tried loading the previous save file to make sure to manually collect the radio rather than the shelf it was on. The music keeps playing. I also couldn't turn it off before taking it.
</details>

**Comment by Pangaron** [comment]
Same, affecting any furniture/workstation item placed prior to update, throws a reference error in console. If you leave the map after the error is thrown and return, the item that was clicked (no matter if for moving or picking up) is gone/removed (not anywhere in the inventory or in the area).

**Comment by Oskutin** [comment]
Can you paste the logfile?

**Comment by Pangaron** [comment]
[Player - Copy.log](https://github.com/user-attachments/files/17498844/Player.-.Copy.log)
I tried her to pick up, then move repeatedly an item existing before the update. Applies to both player-placed items before the update as well as items generated by the game (like default barrels in the hallway).

**Comment by Leiaviathan** [comment]
Tested and can confirm what @Pangaron said. 
Tried to remove objects but they remained in place. Exit and enter building and they are gone. Not in my inventory, just seemingly no longer existing.
[Slot2.zip](https://github.com/user-attachments/files/17498971/Slot2.zip)

[Player.log](https://github.com/user-attachments/files/17498972/Player.log)

**Comment by Zuntti** [comment]
Fixed
