### ISSUE TITLE
Cannot remove mash from Mashing tun (possibly affecting other mashing/fermenting/distilling)

### ISSUE THREAD

**Issue by Pangaron** [loiste-interactive/Obenseuer-Issues#2759]
Cannot remove mash from Mashing tun (possibly affecting other mashing/fermenting/distilling).
Steps:
Mashing completes, ready to output.
Insert empty containers to fill the mash into.
Click fill

> Containers are not filled and the mashing tun is not emptied. Instead, the containers return in a negative value amount and the mash amount in the mashing tun increases. This goes exponentially with each attempt

Have not tested others, but possibly affects fermenting, and distilling as well.

[Player - Copy.log](https://github.com/user-attachments/files/17510686/Player.-.Copy.log)
[Slot9.zip](https://github.com/user-attachments/files/17510688/Slot9.zip)

![image](https://github.com/user-attachments/assets/66f88911-2ed2-43db-8c2c-c45d6cf5ec3c)

**Comment by Zuntti** [comment]
Fixed
