### ISSUE TITLE
Crash on loading autosave

### ISSUE THREAD

**Issue by CBS-S** [loiste-interactive/Obenseuer-Issues#276]
Crash on load from autosave after inexplicably dying of suicide (maybe the food I ate was bad?). The autosave point was the toilet in the hacker apartment. When I restarted the game it was able to reload from the autosave point fine.

**Comment by Oskutin** [comment]
Can you post lof and crash dump?

**Comment by CBS-S** [comment]
Where would the dump be located?

**Comment by Oskutin** [comment]
#687
