### ISSUE TITLE
Playtesting - When the game begins data migration, change automatically the game to work "in-the-background"

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#2761]
If you had not previously set the game to "run in the background", you will have to sit through the migration process screen, as opposed to minimizing and doing something else while it runs.

You can also perhaps add a hint on the information panel stating something like "You can minimize the game, while the save data migration processes in the background."

And if possible, perhaps also temporalily change the process name in task menager to display something like "Migrating old save data..."

**Comment by Zuntti** [comment]
Changed
