### ISSUE TITLE
Coffee maker dupes non-stackable containers instead of making coffee

### ISSUE THREAD

**Issue by Pangaron** [loiste-interactive/Obenseuer-Issues#2762]
Using a non-stackable container, such as a bucket or 20L can in a coffee maker (tested with the better variant) for output does not pour coffee into it, instead it dupes the container - even overflowing them outside of the output area and on the floor.
Seems to work with stackable containers (tested jars).

![image](https://github.com/user-attachments/assets/e071e8cf-cee1-43bb-947d-b38f7610ff4d)

[Slot9.zip](https://github.com/user-attachments/files/17510822/Slot9.zip)

[Player - Copy.log](https://github.com/user-attachments/files/17510826/Player.-.Copy.log)

**Comment by Zuntti** [comment]
Fixed
