### ISSUE TITLE
Playtesting - It seems that the "eating habit" loading screen hint conveys incorrect information

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#2763]
![image](https://github.com/user-attachments/assets/8eb89b9a-982a-4937-9248-74e76925b633)
I'm fairly certain it should be "Progressing fungal disease changes eating habits", unless having very high addiction also affects the player's taste, either way even if true, I think information about fungal disease causing it is more important.

**Comment by Zuntti** [comment]
Changed
