### ISSUE TITLE
Playtest: All apartment upgrades and tenants have vanished

### ISSUE THREAD

**Issue by Leiaviathan** [loiste-interactive/Obenseuer-Issues#2764]
Testing the latest update: 
all of the apartments inside the tenements are back to their original state (minus the furniture, clutter and graffiti we'd have to clean up), and the tenants are missing. 
In the tenement overview the apartments are still listed as fully upgraded and rented out.
Tried this on multiple save files both from yesterday's update, as well as an older save file from October 10th. Same issue in all save files.
Loading the save files from yesterday did not give me the migration loading screen, the older one did.
Outside, roof, hallway and basement seem unaffected by this, it's just the apartments and tenants.

![Malones apartment](https://github.com/user-attachments/assets/b7b1a4d6-b1db-40c7-921e-765c218e9a9d)
![This one even still got the bricks in the door, others are blocked too](https://github.com/user-attachments/assets/085c01ad-93f5-4595-9d0f-88fb2a230d79)
![This is where the door to the balcony should be](https://github.com/user-attachments/assets/16a9ba74-6a48-45cc-b5b0-ef5167ed3c79)
![Outside](https://github.com/user-attachments/assets/d7d6a382-d1e3-4bcb-bd3c-9c95b4137220)
![On paper](https://github.com/user-attachments/assets/2c261698-cd86-4fca-960b-e3e0290b3bdd)
Two of my save files are still here #2752 #2755

**Comment by Zuntti** [comment]
Fixed
