### ISSUE TITLE
Playtest 0.3.24 V2 - Player Cat spawns every time the player enters the tenement

### ISSUE THREAD

**Issue by CVariable** [loiste-interactive/Obenseuer-Issues#2769]
On a new game in the latest version, the player cat spawns again every time you pick it up from your tenement as soon as you leave and enter the tenement.
![grafik](https://github.com/user-attachments/assets/9998aeae-1e0f-43ad-931a-8ae1e922acb6)

**Comment by CVariable** [comment]
Also, the slaughter text should maybe be removed. Poor kitty

**Comment by Zuntti** [comment]
Fixed
