### ISSUE TITLE
Headless Max Masher

### ISSUE THREAD

**Issue by CBS-S** [loiste-interactive/Obenseuer-Issues#277]
If you're inside Max Masher's apartment and walking back toward the door while facing the door directly, Max's head disappears when you get close to him. The rest of his body remains. The head comes back if you look over but disappears again when you look back at the door.

I think this is my favorite bug so far.

**Comment by Zuntti** [comment]
Related to https://github.com/loiste-interactive/Obenseuer-Issues/issues/21
