### ISSUE TITLE
Playtesting - Making tea spawns multiple new containers inside and around the cooking appliance

### ISSUE THREAD

**Issue by generolas121** [loiste-interactive/Obenseuer-Issues#2772]
Whenever making tea is finished it dumps a stack of about 20 containers, if it does not fit inside the appliance then it throws it outside.
![tea container bug](https://github.com/user-attachments/assets/15593f53-d2d7-47df-8f9a-6d1cb6cac277)

v. 0.3.0.42

**Comment by Zuntti** [comment]
Same as https://github.com/loiste-interactive/Obenseuer-Issues/issues/2762
