### ISSUE TITLE
[Typo] Various typos in the B2 note

### ISSUE THREAD

**Issue by Taco-Cat1** [loiste-interactive/Obenseuer-Issues#2774]
![20241025115307_1](https://github.com/user-attachments/assets/f66a40d4-052e-44ed-8057-bf35e75aa3b4)

atleast  --> at least

Maybe I --> Maybe I'll

is not --> isn't   (optional)

door password ---> door code   (optional)

**Comment by Zuntti** [comment]
Fixed
