### ISSUE TITLE
Playtest 0.3.24 - Mines Canteen counts all items as buyable

### ISSUE THREAD

**Issue by CVariable** [loiste-interactive/Obenseuer-Issues#2780]
Taking, paying for and eating the meatballs worked fine, but then i decided to steal a silver bar from a sack behind Anna. Upon leaving she told me i had to pay, so i went to pay and now i have to pay for the stolen silver bar...
![grafik](https://github.com/user-attachments/assets/4effc5f5-e658-411f-aefd-e98820430210)

**Comment by Zuntti** [comment]
Fixed
