### ISSUE TITLE
playtesting - large wooden chest should be more expensive

### ISSUE THREAD

**Issue by pinkamedic** [loiste-interactive/Obenseuer-Issues#2782]
this price seems really low for the amount of space that it has, maybe around 3540 OC
![image](https://github.com/user-attachments/assets/da7a1df3-2860-49a4-b035-80380debdbd7)

**Comment by CVariable** [comment]
I think the price is fair given the small wooden chest has 3 rows for 157oc. This is just a box of plywood and planks, it can't cost that much to make. Certainly not more than fridges at 2k oc

**Comment by Nextej** [comment]
I'm personally in favor of the change for higher price, it is a huge upgrade over regular chests and it shouldn't be something player aims to get in early game, but rather in mid-late game. Comparing it to other fancier machines/furniture, it would sit at around 354 RM, which I feel is in line with the other prices on that stage.

**Comment by Pangaron** [comment]
I think the price is fair, as previously noted, it is just a big box of planks and nails. What should be targeted is to make the large wooden crated balanced in case it is craftable. It should allow players to earn more than by selling the resources needed for it alone (thus encouring crafting), but not to a point of grinding them solely. Of course having prices fluctuate base on some simplified (or complex, where there is time for it) supply/demand. Let's imagine there are 8 of such crates in stock to sell, the price reflect that and increase with each sold crate. As opposite, selling such crate to the vendor should decrease with each additional crate and slowly revert back in the following days as the demand/supply balances.

**Comment by Oskutin** [comment]
Bumped up the price
