### ISSUE TITLE
[0.3.42] - Kilju uses the prototype icon

### ISSUE THREAD

**Issue by Regal0** [loiste-interactive/Obenseuer-Issues#2783]
The inventory icon for kilju recipe uses an icon that dates back all the way to the prototype, there may be other recipes that also have old icons.
![Screenshot From 2024-10-26 00-31-44](https://github.com/user-attachments/assets/88b97c9b-3adf-4ed2-8571-9e3ad0c1668c)

**Comment by Nextej** [comment]
No gonna lie, the prototype icon does look more interesting than the other generic recipe icons, perhaps simple color adjustment to make the paper texture more in line and the ink color a bit more grayed out. So it fits with the style of other recipes.
![image](https://github.com/user-attachments/assets/376adaf6-23b6-4a70-85c6-5d8173269185)

**Comment by Regal0** [comment]
The pixelation makes it seem out of place, even with a change in colour

**Comment by Regal0** [comment]
Perhaps make a higher resolution "remaster" of the icon for a small homage?

**Comment by Zuntti** [comment]
Changed
