### ISSUE TITLE
Playtest 0.3.42 V3 - Prepared foods in O-Market fridge expire and overlay

### ISSUE THREAD

**Issue by CVariable** [loiste-interactive/Obenseuer-Issues#2789]
![grafik](https://github.com/user-attachments/assets/ed3cfeb5-8834-45ce-9aef-4cc32f2743da)
![grafik](https://github.com/user-attachments/assets/0b40da44-8f6c-4216-8a6b-24af144ce723)
Pressing sort then makes everything disappear:
![grafik](https://github.com/user-attachments/assets/a5ed3e0f-6d4b-4c0f-9093-8f3548dcbe5d)
This seems to be an issue exclusively with the prepared foods.

**Comment by Oskutin** [comment]
Old Save?

**Comment by CVariable** [comment]
No, the save was made on 0.3.42* V2, so it was only migrated to V3

**Comment by Oskutin** [comment]
I need save file of this
