### ISSUE TITLE
(Playtest) Floating Coffee + too many milk cartons spawning infront of Deekula

### ISSUE THREAD

**Issue by Leiaviathan** [loiste-interactive/Obenseuer-Issues#2793]
There is this spot in front of the Deekula building that I assume used to be on top of a surface. It keeps spawning floating coffee.
Next to it on the ground there's a spot that spawns overlapping empty milk cartons.

![Screenshot (812)](https://github.com/user-attachments/assets/a0fc855a-c68b-4b44-a789-63b5cd69955e)
![Screenshot (813)](https://github.com/user-attachments/assets/7f0aac42-e1c0-4690-ab5a-15712544feb5)

**Comment by Zuntti** [comment]
Can I get a save where this happens?

**Comment by Zuntti** [comment]
Fixed
