### ISSUE TITLE
Playtest 0.3.24 V3 - Floating Boxes in Deekula B Attic (Top Floor)

### ISSUE THREAD

**Issue by CVariable** [loiste-interactive/Obenseuer-Issues#2794]
![grafik](https://github.com/user-attachments/assets/93db4f46-332c-48fa-b3a4-23462d021fb6)

**Comment by TonyFromRomania** [comment]
is not a floating box case, is  case of the armchair be sunken into the ground (see the small red line under the boxes)

**Comment by Oskutin** [comment]
fixed
