### ISSUE TITLE
(Playtest) Maxing skills didn't unlock Steam achievement

### ISSUE THREAD

**Issue by Leiaviathan** [loiste-interactive/Obenseuer-Issues#2798]
I've reached level 10 Engineering Skill today, but it hasn't unlocked the achievement on Steam. According to Steam 0,0% of players have unlocked this achievement, and it's the same for a few other skill related achievements, so perhaps those are bugged as well.

The achievement for level 10 distilling hasn't unlocked for me either. I'm not 100% sure, but I believe I've maxed this skill before I started the play test version.
![Screenshot (823)](https://github.com/user-attachments/assets/aac90897-d329-45a9-9796-bf91ce28e200)

**Comment by Oskutin** [comment]
Fixed
