### ISSUE TITLE
[Typo] Typo in some item descriptions

### ISSUE THREAD

**Issue by Taco-Cat1** [loiste-interactive/Obenseuer-Issues#2804]
![20241027094436_1](https://github.com/user-attachments/assets/63a4017f-f0e2-4707-a22f-088b526d36c4)
Should be: It's an expensive sheet of metal

![20241027094632_1](https://github.com/user-attachments/assets/1cc585ff-c1bb-466e-853d-5b3bb7550feb)
Should be: Dead fish from the sewer

![20241027094652_1](https://github.com/user-attachments/assets/fb26886c-eaa1-4d56-acf9-4149434671c3)
Should be: It's a useful piece of metal

**Comment by Oskutin** [comment]
fixed
