### ISSUE TITLE
[Playtesting/Minor] Some bugs with Tenement contract work

### ISSUE THREAD

**Issue by Taco-Cat1** [loiste-interactive/Obenseuer-Issues#2805]
![20241027121327_1](https://github.com/user-attachments/assets/0ae00350-0c9f-4d74-b3d1-f41a4bd8b4cc)
![20241027121341_1](https://github.com/user-attachments/assets/48fc793f-1a75-4467-b1b0-5da7091fc0cf)
The desil does not count as stealing

![20241027131250_1](https://github.com/user-attachments/assets/280e6be6-1265-4e97-a48e-2381e95f7b79)
Not really a big deal but I think the broken brown refrigerator should be standing upright like the normal fridges instead of hanging on the wall like that

**Comment by Zuntti** [comment]
Fixed
