### ISSUE TITLE
[Playtesting] Pea soup recipe icon broken

### ISSUE THREAD

**Issue by Taco-Cat1** [loiste-interactive/Obenseuer-Issues#2806]
![20241027080653_1](https://github.com/user-attachments/assets/974c52fb-d188-4c7e-bc79-7729434cbfc9)

**Comment by Nextej** [comment]
So is OsRat recipe (on migrated save at least)

**Comment by Taco-Cat1** [comment]
This is not migrated save though and have not tested on osrat
