### ISSUE TITLE
[Bug] Mail box counts wieldable items as mail

### ISSUE THREAD

**Issue by Taco-Cat1** [loiste-interactive/Obenseuer-Issues#2807]
V.0.3.38

https://steamcommunity.com/app/951240/discussions/2/4844273853945399654/

**Comment by Taco-Cat1** [comment]
[Slot10.zip](https://github.com/user-attachments/files/17535475/Slot10.zip)

**Comment by Zuntti** [comment]
Doesn't seem to happen in playtest?
