### ISSUE TITLE
Playtest 0.3.42 V3 - Double Eliana is back

### ISSUE THREAD

**Issue by CVariable** [loiste-interactive/Obenseuer-Issues#2808]
Issue #2519 is apparently still or again present in the current version: Eliana exists twice at the end of her Questline.
Apparently this appears as soon as the Kolhola Map is reentered according to Broke Electrician on Discord.
![20241020224306_1](https://github.com/user-attachments/assets/b5a2e4bb-92ac-4282-9b37-ff726444cb76)

**Comment by Zuntti** [comment]
Fixed
