### ISSUE TITLE
character model culling happens too early

### ISSUE THREAD

**Issue by KETALss** [loiste-interactive/Obenseuer-Issues#281]
![1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/81901907/4012eae4-5891-49df-a5f9-52a834fee71c)
![2](https://github.com/loiste-interactive/Obenseuer-Issues/assets/81901907/b5900b99-9558-48e2-a5d7-58fadc351d52)

in max masher apartment, head culls too early on right side of screen

**Comment by Oskutin** [comment]
https://github.com/loiste-interactive/Obenseuer-Issues/issues/21
