### ISSUE TITLE
Playtest 0.3.42 V3 - Potato mushroom mash does not consume mushrooms for the recipe. 

### ISSUE THREAD

**Issue by Pangaron** [loiste-interactive/Obenseuer-Issues#2815]
Potato mushroom mash does not consume mushrooms for the recipe. Sugar beet recipe was fine, so it probably affects only some of the recipes or potato one only. Also the water taken seems to be off, taking 6 more units - possibly the cause where it takes 6 additional units of water instead of 6 shrooms?

![image](https://github.com/user-attachments/assets/8d79d7da-48fc-45a2-93f1-bbaf235f06d6)

![image](https://github.com/user-attachments/assets/e853968b-a389-4b38-93f6-c7e729b707a4)

[Slot6.zip](https://github.com/user-attachments/files/17545421/Slot6.zip)
[Player - Copy.log](https://github.com/user-attachments/files/17545425/Player.-.Copy.log)

**Comment by Pangaron** [comment]
Confirmed for Glowing carrot mash as well (and possibly others not yet tested)

**Comment by Zuntti** [comment]
Fixed
