### ISSUE TITLE
(Playtest) Mashing kettle no longer interactable

### ISSUE THREAD

**Issue by Leiaviathan** [loiste-interactive/Obenseuer-Issues#2818]
At first it was just one of my mashing kettles, then two, now after rearranging them, non of them can be interacted with. 
It also happened with my distilling machine (forgot the name of it, the big one), but I went back to my last auto save to fix it. 

I've saved right in front of multiple broken mashing kettles in this save file:
[Slot7.zip](https://github.com/user-attachments/files/17549656/Slot7.zip)

**Comment by Pangaron** [comment]
Possibly connected to https://github.com/loiste-interactive/Obenseuer-Issues/issues/2781#issuecomment-2440491600 ?
