### ISSUE TITLE
Playtest Enhancement - Bloody chair desc should be different

### ISSUE THREAD

**Issue by pinkamedic** [loiste-interactive/Obenseuer-Issues#2820]
with how it is right now the line of '' there is something very wrong with this chair '' kinda misses the ball it should be hitting, the desc should really guilt the player. something more fitting would be '' his favorite chair.. '' or '' yetleast his bones contaminated bones didint kill him '' or '' you got him to leave, but this will always remain '' these are just examples

**Comment by Pangaron** [comment]
What about, if you do not place it somewhere in your apartment, you get something like "disturbed sleep", where you would wake up, all sweaty (in need for a shower), until you place it? The description could be something like "He is gone... or is he?"
Also possibly, you would be able to see his silhouette sitting in when drunk/on shrooms, perhaps hearing his voice in distance. The thing here would be that it would not be explained whether it is actual "ghost" thing and his imprint on the chair, or just you mind and guilt playing tricks on you. Possibily might be clarified as the story progresses, perhaps even having an option to make peace with him/yourself later.

**Comment by Nextej** [comment]
Another proposals:
"The blood remembers"
"Just like him... You let that happen"

Additional idea about how the description is previewed:
- Every time the player inspects the furniture (or every time players opens the inventory/every new day), a new description is randomized from a list, delivering various unsettling comments towards the player.
- Alternatively, change the final description of the furniture depending on player's dialogue choices in the confrontation. For example if player will be selfish and persistent choosing an option of "I want him gone", the description will be more aggressive ("You got what you wanted"), but if player chooses options that try to deescalate the situation, but he still gets shot and killed, the description will be more pityful instead (see above proposals).

**Comment by Zuntti** [comment]
Changed
