### ISSUE TITLE
Playtest 0.3.42 V3 - Stalburg Bank account inflates to absurd amounts of RM, adding more every few seconds.

### ISSUE THREAD

**Issue by Pangaron** [loiste-interactive/Obenseuer-Issues#2821]
Stalburg Bank account inflates to absurd amounts of RMs, adding more every few seconds.

![image](https://github.com/user-attachments/assets/45f40aa0-428a-4ef7-85ed-9352e1fd392c)

This save was upgraded from the prod version, but the same seems to apply to a new save. If I edit the save to reset the RM on account to 0, it gets inflated very soon afterwards. Due to this, it is impossible to test any bank account-related features (like weekly gains, scam invoices and so on).

[Slot6.zip](https://github.com/user-attachments/files/17562934/Slot6.zip)

[Player - Copy.log](https://github.com/user-attachments/files/17562938/Player.-.Copy.log)

**Comment by Oskutin** [comment]
Fixed
