### ISSUE TITLE
[Typo] Some typos in diolouge

### ISSUE THREAD

**Issue by Taco-Cat1** [loiste-interactive/Obenseuer-Issues#2827]
![20241029164723_1](https://github.com/user-attachments/assets/ff405a76-abcf-4197-8711-b52db1fee451)
Should be: My own apartment would be so much better than this... bus.

![20241029174453_1](https://github.com/user-attachments/assets/3d24c490-a29a-4aba-b37a-785a3190bf88)
(Bottom dialogue choice) Should be: I'll think about it

![20241029181538_1](https://github.com/user-attachments/assets/f6f5c924-571c-4233-9243-7514de6f3c94)
(Last few words) Should be: try to follow them.

![20241030161035_1](https://github.com/user-attachments/assets/781e7f36-050a-43f0-b549-5fff7ac3854b)
(Excuse the drunk effect) Should be: He wants to heal a certain person

![20241030170313_1](https://github.com/user-attachments/assets/a2e24682-e3c4-4725-956a-129c1415049b)
(First sentence) Should be: Me? I don't even know what is happening.

![20241101080102_1](https://github.com/user-attachments/assets/0b0384e2-d151-4fdf-bcc0-1b3c5d2483d4)
Not a typo but the text is off centre

**Comment by Zuntti** [comment]
Fixed
