### ISSUE TITLE
Playtesting - the "restrooms" sign at the portapotty next to the Ten A is on the wrong side of the geometry

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#2851]
![image](https://github.com/user-attachments/assets/86fc6337-2b00-4327-9ba1-3afbdf0314f7)
It should be moved slightly to be visible from the outside instead
![image](https://github.com/user-attachments/assets/cd8e4eef-03e1-4ea3-b70e-c6c5f411d624)

**Comment by Oskutin** [comment]
fixed
