### ISSUE TITLE
(Bug) Kolhola A infinite bottle respawning

### ISSUE THREAD

**Issue by Thomathnan** [loiste-interactive/Obenseuer-Issues#2854]
This is in V 0.3.38. If you drop a bunch of glass bottles in the sort of foyer area of Kolhola A, break them into glass shards, then leave and reenter, the glass bottles will respawn in the same area you dropped them. You can repeat this ad infinitum for infinite glass shards. 
![image](https://github.com/user-attachments/assets/a8dc1e79-c40e-4773-b4e6-7953dde63541)
Respawned glass bottles, on top of glass shards where previous bottles have been broken.

**Comment by Zuntti** [comment]
Fixed
