### ISSUE TITLE
Upon entering the Other Side using OSRAT, an attempt to talk to anyone (Jacob or Tobias) will immediately exit the Other Side 

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#286]
This also allows to have the same conversation multiple times.

https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/2c7ec26f-39eb-4a32-9014-b5eb8d61c936

**Comment by Zuntti** [comment]
Fixed
