### ISSUE TITLE
Feedback - facade 1 should be less expensive 

### ISSUE THREAD

**Issue by pinkamedic** [loiste-interactive/Obenseuer-Issues#2873]
with facade one its super expensive for how little samuuel does, 7000OC and 500RM for samuuel to clean up some graffiti and remove scaffoldings, it should be around 2000 OC and 150 RM and maybe it should require some cleaner for removing the graffiti.

**Comment by Nextej** [comment]
I think the RM cost for facade should no be higher than 50 RM. Facade doesn't really do much for the gameplay, so players might be very discouraged to "waste" their crucial early money for such an expensive renovation, putting even the lowest tier level for a late-game.

On the topic of adjusting resource costs, the Tenement Electricity 1 should only require 1 electronic parts and 1 wiring components, as by the time player will need or want to get this upgrade, getting at least 1 of both will be a matter done within a day, maybe two. I do not think the drop yield for these two items should be increased.

**Comment by Zuntti** [comment]
Changed
