### ISSUE TITLE
When unlocking transition doors, at first they will be unlocked on the other side, but going to another map and returning will make the doors locked again.

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#288]
In relation to https://github.com/loiste-interactive/Obenseuer-Issues/issues/192
How to recreate:
get Luka's Hideout keys -> unlock and enter Deekula A -> see that the doors behind you are unlocked -> go to another map from there (General Store for example) -> return to Deekula A -> see that the doors to Basement are now locked

**Comment by Zuntti** [comment]
Fixed
