### ISSUE TITLE
[playtesting] players cat cloned

### ISSUE THREAD

**Issue by Garrowni** [loiste-interactive/Obenseuer-Issues#2891]
![20241107140820_1](https://github.com/user-attachments/assets/86e727a1-04e0-4d2b-9f0b-05438f1f20b9)
Owned cat clone. Not sure what triggered it, I walked in and there they both were.

**Comment by efadfa3** [comment]
Mine cloned as well. Twice by now, I now own 3 cats

**Comment by Garrowni** [comment]
I started a new game and got it to happen again. First few days there was no cat. I went in on the Wednesday and the cat was there. I picked it up and put it back down.  I then cleaned and slept. I went out the Thursday morning, and when I came back there was 2 cats again.

**Comment by Garrowni** [comment]
ok so i picked up my cats, put them both down again, left. and at some point a 3rd appeared

**Comment by Garrowni** [comment]
I have 5 cats now. I can confirm if I pick them all up and put them all down, then go do my adventuring... when I come home theres an extra one.
