### ISSUE TITLE
Playtesting - greenhouse furnace initial state issue

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#2895]
When player visits the greenhouse level for the first time, the furnace will be on automatically and be lit indefinitely without any wood inside. However once player reloads the level (after the first visit), the furnace will be properly off, letting the plants to die.

I propose either making the furnace off by default, or have an actual initial value of added wood (like say 3,7 hours). I think the latter will be better to bring the player's attention to where the furnace is located.

**Comment by Zuntti** [comment]
Fixed
