### ISSUE TITLE
some questlines progressing on their own

### ISSUE THREAD

**Issue by apterous123** [loiste-interactive/Obenseuer-Issues#29]
![6fba22fb1bbbad6f1c8d66c1e367580c](https://user-images.githubusercontent.com/67603259/231841191-b32385b6-8f2e-46ec-b3b5-611ee752f6d7.png)
priests debt and me mash quests appeared when i opened a door nearby after talking to amanda korhonen. i dont think this is supposed to happen.

**Comment by gehube** [comment]
are you sure you didn't accidentally press the test button?

**Comment by apterous123** [comment]
yeah i did, what does the test button do? :D

**Comment by gehube** [comment]
give the objectives
