### ISSUE TITLE
[Playtesting] Bug with mines canteen checkout

### ISSUE THREAD

**Issue by Taco-Cat1** [loiste-interactive/Obenseuer-Issues#2902]
![20241109130616_1](https://github.com/user-attachments/assets/c59258c3-835e-42fb-af76-d1ab67096dec)
The player can steal the bag without paying, which is inconsistent with O-Market or Skeida. Even if it is meant to be intentional for the player to be able to steal, only sandwiches and pies will be considered stealing and everything else once in the inventory with be marked as owned.

**Comment by Nextej** [comment]
I think it would be solved better if
1) all items sold there had an appropriate ownership
2) the moment you leave the map, they retain the specific ownership, while they change from "owned" to "stolen", and vice versa if the player returns.
3) the vendor would not serve the player anymore until they pay off recompensation, perhaps by making it unable to pick up any more items from the stock.

**Comment by Zuntti** [comment]
Fixed
