### ISSUE TITLE
Playtesting - "Moderate" wealth indicator is too long to show up properly

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#2906]
![image](https://github.com/user-attachments/assets/d680f68a-8fbf-48e3-92b1-25af0f9dcb3f)
Same with "Generous"
![image](https://github.com/user-attachments/assets/4dc9747f-90c4-443c-afe3-cfac4eaf536d)

**Comment by Zuntti** [comment]
Fixed
