### ISSUE TITLE
Liquid Duplication with stackable containers

### ISSUE THREAD

**Issue by vulpes133** [loiste-interactive/Obenseuer-Issues#2907]
I found a glitch when using Pint Glasses and Mason Jars that infinitely duplicates the liquids stored inside of them.

Steps to reproduce this glitch.
1: Gather either 3 Pints or Mason Jars. (Will use Mason Jars for this example)
2: Split the items into two stacks. 1 stack with 2 Mason Jars and 1 stack with 1 Mason Jar.
3: Completely fill the 2 Mason Jar stack with any liquid.
4: Right click on the 2 Mason Jar stack, while holding RMB drag and drop the Mason Jars over the single Jar stack. This will fill the 1 Jar stack with the same liquid as in the 2 Mason Jar stack.
5: Empty the now filled 1 Mason Jar, either by using the liquid or transferring it to another container.
6: Repeat steps 4 & 5 to infinitely duplicate the liquid.

![duplication](https://github.com/user-attachments/assets/d3ada1f0-5631-4cf0-8d61-89be7e1abd3b)

This appears to work with all liquids I've tested. Though it can be noted that the containers don't need to be in just a stack of 2. The filled containers seem to work in any size of stack of 2 or greater, just as long as the entire stack is completely filled with the liquid.
![image](https://github.com/user-attachments/assets/204c43c2-29ef-49fc-883f-3e33db6c154a)

**Comment by Oskutin** [comment]
https://github.com/loiste-interactive/Obenseuer-Issues/issues/2680 linked

**Comment by Oskutin** [comment]
Fixed
