### ISSUE TITLE
Fermenting Barrel crafting recipe doesn't consume Blue Plastic Barrels

### ISSUE THREAD

**Issue by Fatboye206** [loiste-interactive/Obenseuer-Issues#2909]
[v.0.3.38]
The worktable recipe for Fermenting Barrels shows a requirement for 0 Blue Plastic Barrels and does not consume them on craft. I'm not able to produce Fermenting Barrels without blue barrels in my inventory, but having only one means that I can infinitely produce them. Other crafting components are consumed as normal.
![Obenseuer 11_10_2024 10_31_25 PM](https://github.com/user-attachments/assets/e5059102-e6af-4bcc-912d-1990f1454b56)

**Comment by Zuntti** [comment]
Already fixed in playtest
