### ISSUE TITLE
DoublePot wins seem to override the amount of cash inserted to the machine, not sure if intentional, doesn't seem so.

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#291]
For example: insert 13 coins -> put 1 as a stake, 12 remain in cashout -> win 2x -> cashout now states 2 coins (shouldn't it be logically 14?)

After doing double or nothing, the cashout shows the remaining value, seems like the interface needs a little tweaks, like for example the cashout button should say "( Cash Out: {state before Play} Won: {state of the reward} )", before it gets merged together once double or nothing is done.

**Comment by Oskutin** [comment]
Actually it's not a bug, you can redeem your winnings, and after you do that, you can also cash out the money you have inserted.

**Comment by Nextej** [comment]
I know you can, knew eventually, but the interface is still misleading and needs tweaking, the button should state clearly how many coins were inserted to the machine and what's the amount of winning, separately.
