### ISSUE TITLE
0.3.38 - Lockpicking when you dont see the door lock

### ISSUE THREAD

**Issue by CapraPoligonail** [loiste-interactive/Obenseuer-Issues#2915]
If you don't see the door lock lockpicking is interrupted, but if you break the lockpick before then the lockpicking is no longer interrupted.
![951240_14](https://github.com/user-attachments/assets/cddbcfd1-8249-41b3-bc4a-db415eab41b7)

**Comment by Oskutin** [comment]
fixed in upcoming
