### ISSUE TITLE
Crash on OSRAT

### ISSUE THREAD

**Issue by rojok23** [loiste-interactive/Obenseuer-Issues#292]
When using the OSRAT in the priest's room the game crashed.
[Player.log](https://github.com/loiste-interactive/Obenseuer-Issues/files/11919947/Player.log)

**Comment by rojok23** [comment]
Loading an autosave after put me on a toilet with inventory empty; flashlight still shows up on hud despite not being in inventory
![20230630124036_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/17996199/e5ec5b6a-b4e5-42d8-8a41-822517783b66)

**Comment by rojok23** [comment]
![20230630124036_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/17996199/04d43576-fa10-44ab-9246-9893c5ae6b5e)
After reloading autosave inventory emptied despite flashlight remaining on hud(Hit wrong comment button, oops)

**Comment by Oskutin** [comment]
#687
