### ISSUE TITLE
[Playtest] Sara Claine in the bus is clipping through the shelf

### ISSUE THREAD

**Issue by efadfa3** [loiste-interactive/Obenseuer-Issues#2923]
![20241113024114_1](https://github.com/user-attachments/assets/48ecda95-97d3-430a-b1c6-163385f2055d)

**Comment by Oskutin** [comment]
I don't see her clipping

**Comment by efadfa3** [comment]
![20241116031755_1](https://github.com/user-attachments/assets/7d0aa069-f0dd-421d-8a39-8285c0e0f3fc)

![20241116031803_1](https://github.com/user-attachments/assets/252b83ff-67af-48a9-8201-0a011d466569)

![20241116031811_1](https://github.com/user-attachments/assets/726b3f10-8154-4bde-8a54-dc41f325b068)
 Definitely clipping.
