### ISSUE TITLE
Playtest - recipes for the loom / sewing machine need to be added to random recipe paper pool

### ISSUE THREAD

**Issue by pinkamedic** [loiste-interactive/Obenseuer-Issues#2925]
right now you cannot get recipes for the sowing machine or loom from random recipe papers or the pekka life mag, when you should be getting them

**Comment by Oskutin** [comment]
Hmm, some loom recipes are already in Lifehack-Pekka

**Comment by pinkamedic** [comment]
honestly i think more mags should be added, recipes i mostly get from pekka are just food recipes / booze recipes, would be nice to have mags that tend towards different kinds of things like sewing / metalwork with pekka being more of a general thing

**Comment by Oskutin** [comment]
new magazines basically covers these
