### ISSUE TITLE
Playtest - head regrows after cop call

### ISSUE THREAD

**Issue by pinkamedic** [loiste-interactive/Obenseuer-Issues#2929]
pias head will grow back if you cut it off then call the cops about the body

**Comment by Oskutin** [comment]
still happens`?

**Comment by Oskutin** [comment]
This needs save game (and confirmation that this still happens)

**Comment by pinkamedic** [comment]
[Head_Chopper.zip](https://github.com/user-attachments/files/18241283/Head_Chopper.zip)
slot 1 is before it happens, but her head seems to regrow when you leave and reenter the building no matter if you can call the cops or not and for some reason i couldint call the cops to report the body but it might be due to it being a test save that i forced the quests

**Comment by Zuntti** [comment]
Fixed
