### ISSUE TITLE
Cannot sleep in the own bed in the own apartment because the bed is marked as owned.

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#293]
The first apartment on the first floor should be player's (that's where the building mode is active), right? I does says the bed is owned and cannot be slept in 
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/567df982-79e1-4fb3-a5c3-ac226b0251e0)

**Comment by Oskutin** [comment]
Fixed
