### ISSUE TITLE
It is possible to get on top of the elevator

### ISSUE THREAD

**Issue by Moomoobeef** [loiste-interactive/Obenseuer-Issues#2933]
# About
when the elevator is moving down they can crouch jump onto the bar at the back, then the sign, then finally the elevator buttons. If they uncrouch while on top of the elevator buttons while the elevator is still moving and then jump, they will glitch through the elevator and end up on top of it. Below is a video I took of the bug.

### Media
https://youtu.be/JucZ_JbMSrk?si=NS3kej5rFC3Zb2Bk&t=22

# Reproduction
1. go down in the elevator
2. while going down, crouch jump onto the bar at the back
3. crouch jump onto the sign
4. strafe onto the buttons
5. uncrouch and jump repeatedly
6. you are now trapped on top of the elevator, congratulations.

### My system
I am running Obenseuer in Manjaro Linux with the following specs
```
CPU: AMD Ryzen 9 5900X (24) @ 3.700GHz
GPU: 2x NVIDIA TITAN X (Pascal)
RAM: 32Gb
Kernel: 6.6.47-1-MANJARO
```

**Comment by Oskutin** [comment]
fixed
