### ISSUE TITLE
Playtest - Hitting hot steel bars into plates counts as theft

### ISSUE THREAD

**Issue by AllayTheWolf** [loiste-interactive/Obenseuer-Issues#2936]
![20241116200907_1](https://github.com/user-attachments/assets/c6875bed-995d-4b18-a78b-94bbc937f985)
![20241116200910_1](https://github.com/user-attachments/assets/f13d4258-83a9-4e61-909f-5e9e4069c9c2)

Unfortunately my video software wasn't working, hopefully these screenshots will do.

So, I heat up some iron bars, slammed them with a sledge, picked up the plates - and boom, theft bounty. Not sure how this is happening. My crafting stations are in the basement of the tenement, if that helps. Game version is V.0.3.43

Not sure what else to say about this really.

**Comment by Oskutin** [comment]
fixed
