### ISSUE TITLE
playtest - distilling gives to much XP

### ISSUE THREAD

**Issue by pinkamedic** [loiste-interactive/Obenseuer-Issues#2938]
whenever i distill anything in a medium distillery it gives a level, no matter how much of a liquid or what liquid it will always give a lvl in distilling when finished

**Comment by Oskutin** [comment]
Got a save file?

**Comment by pinkamedic** [comment]
[Kyle_Pinkmin.zip](https://github.com/user-attachments/files/18256162/Kyle_Pinkmin.zip)
Slot 2, the barrel next to it is filled with water for testing, if you distill 20 ltrs of water it will jump you to lvl 2

**Comment by Oskutin** [comment]
Need to test with higher levels

**Comment by pinkamedic** [comment]
[Kyle_Pinkmin.zip](https://github.com/user-attachments/files/18256219/Kyle_Pinkmin.zip)
distilled about 7 20L of water and got to lvl 6

**Comment by Oskutin** [comment]
Okay, there's indeed then something to fix

**Comment by Oskutin** [comment]
Reduced XP gain on (large) distilleries
