### ISSUE TITLE
[Playtest] Lighting bug for trash on deekula rooftop

### ISSUE THREAD

**Issue by AllayTheWolf** [loiste-interactive/Obenseuer-Issues#2939]
![20241114182627_1](https://github.com/user-attachments/assets/6b0a131f-e57c-4e0f-8bd3-18a94b14b0c9)

Game version V.0.3.43

Not really much else to say about this, although the issue may only be present in foggy conditions - not too sure on that.

**Comment by Oskutin** [comment]
fixed
