### ISSUE TITLE
Building mode buttons feedback

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#294]
1. Would be nice to have a buttons that rotate the objects by a fixed degree, Z and C seems to be free to do so (ideally, from relation to the world's axis, not the current position, so you can always align everything, no matter the RMB offset). Probably a button to switch between that fixed degree could be also a good idea, X for instance, to switch between 5°/10°/15°/30°/45°. A general alternative to RMB is welcome, since rotating that way might be tiring for the hand, so it could be a solution to it.
2. Pressing TAB to exit also opens up the TAB menu immediately, which it shouldn't.

**Comment by Zuntti** [comment]
Added and fixed
