### ISSUE TITLE
[Playtesting] After eating ice cream, the paper trash has stats as if it's food

### ISSUE THREAD

**Issue by Taco-Cat1** [loiste-interactive/Obenseuer-Issues#2940]
I have not experienced this bug but I did find this screenshot on discord

https://cdn.discordapp.com/attachments/510482630278512640/1307772973050101810/image.png?ex=673b85fe&is=673a347e&hm=7771bb0d49a82a4f5a87dca9a0a7a6131a425062113044d4955022e8e3ae3f84&

**Comment by lomberd2** [comment]
Discord Links will expire after a few days. Here is the screenshot uploaded on git:
![image](https://github.com/user-attachments/assets/724a3010-ecb0-433e-909c-fef9181a9772)

(Screenshot was from me)

Repro Steps:
1. Open freezer
2. Eat ice cream inside freezer

Game Version:
v. 0.3.43

**Comment by Oskutin** [comment]
Migrated save?

**Comment by lomberd2** [comment]
It might be from 0.3.42. Can I check somehow?

**Comment by lomberd2** [comment]
![grafik](https://github.com/user-attachments/assets/45ff745e-47cf-4ea2-a96c-dd22c1cbb3b9)

**Comment by lomberd2** [comment]
Well I just tested it with a fresh safe. Still there.
![grafik](https://github.com/user-attachments/assets/7b11422e-8ccf-4ea3-aa3c-fb11de92caaa)

**Comment by Oskutin** [comment]
For some reason it inherits starts from the ice cream

**Comment by Oskutin** [comment]
fixed
