### ISSUE TITLE
suggestion - new skill music / busking improvements 

### ISSUE THREAD

**Issue by pinkamedic** [loiste-interactive/Obenseuer-Issues#2952]
this new skill would relate to the playable guitar that the player can find and would effect any other musical instruments (if added).

right now all you can do with the guitar is walk around playing music for maybe some money but what if there was a skill to go with it, simply walking around playing music will increase the skill, with higher levels the higher chance of ppl giving you money and the higher chance of them giving you larger amounts of money, this would give a simple change to busking and would make it more impactful but with this skill and change a new job is opened up.
you would be able to play guitar at the speakeasy to earn some money and tips, but in order to do this job you need some sheet music, with the new skill youll be able to make your own sheet music with their own quality the better quality of sheet music the more money youll make in tips, you would be able to make sheet music at a writing mat / typewriter and would go off of your music skill. the main appeal of this job would be the tips as you dont get paid alot (tips would depend off of the sheet music quality while the flat pay depends on your skill, you would also get a free beer at the end of your shift)

**Comment by Oskutin** [comment]
Added music skill
