### ISSUE TITLE
Collecting rubble in your apartment should give you "material" items that can you use later to sell or craft

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#296]
Like those cables here, would be nice to get some "Cable sections" from cleaning this up
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/2055fef7-5e5e-46d1-a8c6-a8197ee7e929)
Some "Cardboard"
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/5253a1f2-178c-4642-ab8a-658c623b3bbe)
or "Rubble pieces"
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/a257cfcc-772f-4890-b775-2a578dbdf81f)

**Comment by Oskutin** [comment]
does already
