### ISSUE TITLE
[Playtesting] Certian itme at SKeida count as stealing rather than owned

### ISSUE THREAD

**Issue by Taco-Cat1** [loiste-interactive/Obenseuer-Issues#2964]
![20241125173937_1](https://github.com/user-attachments/assets/64a844f2-78f1-4f20-9536-337cbde3b223)

![20241125173946_1](https://github.com/user-attachments/assets/2b574d95-973b-4fe7-acf0-8e7d1e2c6d73)

![20241125173957_1](https://github.com/user-attachments/assets/b90f9201-d86e-4337-a2e6-fcdb3c8e3a37)

The items you are seeing are the only ones on that shelf that count as stealing and all the other ones are labelled as owned.

**Comment by Oskutin** [comment]
Fixed
