### ISSUE TITLE
[Playtest] [Bug] Liquid containers delete their liquids when unstacking

### ISSUE THREAD

**Issue by AllayTheWolf** [loiste-interactive/Obenseuer-Issues#2974]
https://github.com/user-attachments/assets/7a4deb34-c837-4d72-8edb-a1d583148f79

Game version V.0.3.43

I can't confirm if this affects other containers or just bottles, however as seen in the video - I was unstacking some bottles full of fresh moonshine, when suddenly the stack reverted into an empty bottle stack and just straight up deleted all the moonshine inside.

Was in a VC at the time, forgive background chatter from callers.

**Comment by Oskutin** [comment]
https://github.com/loiste-interactive/Obenseuer-Issues/issues/2680 related

**Comment by Oskutin** [comment]
Fixed
