### ISSUE TITLE
0.03.38 - Repeatable crash when crafting the Sawbuck with Chainsaw

### ISSUE THREAD

**Issue by owlsten** [loiste-interactive/Obenseuer-Issues#2975]
Tested at the workshop next to Samuel Jonasson with all crafting materials in inventory/the chainsaw being in the furniture inventory. Crafting materials are not stolen, inventory has 1 open space left.

When attempting to craft the Sawbuck with Chainsaw the game crashes.

The bug is consistently repeatable.

**Comment by owlsten** [comment]
The bug did not occur with other craft-able items.

After leaving the building and returning the bug stopped happening. This was also true when returning to a previous save in which the bug previously appeared every time.

**Comment by Oskutin** [comment]
Likely fixed in upcoming
