### ISSUE TITLE
playtest / bug - new model npcs stay when useing osrat

### ISSUE THREAD

**Issue by pinkamedic** [loiste-interactive/Obenseuer-Issues#2979]
when using the osrat npcs disappear but all npcs with updated models stay (only one that should stay is the omart lady as working retail can make you soulless)

**Comment by Oskutin** [comment]
This needs full list of NPCs where this happens

**Comment by Nextej** [comment]
all NPCs in the mines, all NPCs in Ten A, Malone P., Tatyana G., H. Mobelmann, Amanda K., Sara C., Vivi B. and Patrik A, Mirjam, Dr. Pena

don't remember if crazy neighbour was already fixed or not

**Comment by Oskutin** [comment]
nvm, managed to fix without
