### ISSUE TITLE
Pre-placed storage furniture in your apartment reset their position upon map transition

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#298]
In example: Briefcase was to be found in the apartment as one of the default furniture, picking it up and moving elsewhere resets to its original location when the Player's Tenement map is left and revisited again.

https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/ff24f17b-3a7f-42e2-815f-653fe052684c

**Comment by Nextej** [comment]
There seems to be more issues, firstly a loading up an autosave (and changing maps) disappeared one of the storages I've placed (which did not the previous time the autosave loading was used), then after that a second (older) storage disappeared, again with loading an autosave, that stayed there for much longer time and wasn't affect by map transition.

**Comment by Nextej** [comment]
The autosave issues and the map transition issue seem to be two separate cases.

Trying to pick up the briefcase, not placing it down, saving and reloading, causes all items in the picked briefcase to disappear, the original is returned to its position (so we got additional briefcase duplicated) and the original one also remains empty.

Worth to add that once the briefcase normally changes its position back to normal, no items are being lost.

**Comment by Nextej** [comment]
Emptying the briefcase and then moving it seemed to help to change its position, but that caused another storage (place by myself) to disappear upon reloading saves
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/9d7cd74e-afc0-42bb-abdd-ab3684d98047)

**Comment by Nextej** [comment]
I dunno how I forgot to mention this, the bug seems to happen only if we place any our items into the pre-placed briefcase first. If we take the briefcase and move it, and then start storing items in there, it won't respawn its position.

**Comment by Zuntti** [comment]
Fixed
