### ISSUE TITLE
Playtesting - at Erikson's Claim sometimes you get stuck/slowed down at the entrance to the toilet

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#2988]
![image](https://github.com/user-attachments/assets/baa91f00-a761-4949-87c2-f297f6d80ae7)

**Comment by Nextej** [comment]
Also, all of the urinal spots at the same toilet have wrong camera direction when interacted
![image](https://github.com/user-attachments/assets/d410c968-6de4-4600-a382-ee3054b853a9)

**Comment by Oskutin** [comment]
Fixed
