### ISSUE TITLE
[Playtesting] In the elevator control room, the player has to jump up the stairs instead of the normal behavior of walking up them

### ISSUE THREAD

**Issue by Taco-Cat1** [loiste-interactive/Obenseuer-Issues#2989]

**Comment by Oskutin** [comment]
Screenshot of the location?

**Comment by Taco-Cat1** [comment]
Unable to get a screenshot for now but the map name is "Interior Mines Elevator Control Room" and the staircase in there is the one you have to jump up

**Comment by Taco-Cat1** [comment]
Okay got the screen shot
![20241213114601_1](https://github.com/user-attachments/assets/6f066190-0bcf-4646-a515-4b3af0987cc5)
The staircase is in that buiding

**Comment by Oskutin** [comment]
Fixed
