### ISSUE TITLE
Playtesting - talking to the fuel station guy about seeing his stock still crashes the game

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#2990]

**Comment by l-HealthAngel-l** [comment]
![20241214101236_1](https://github.com/user-attachments/assets/52a5eb88-fcb8-4762-bcdd-c26362c097c8)
Based on options:
1. Choosing this it will lock in interactive state as it happened to @Nextej 
2. Choosing this one, says one line about diesel pricing and returns back to these four options. Working as intended.
3. When you choose this, it completely crashes down the game. Feels like there is not defined store screen.
4. Leaves NPC interaction. Working as intended.

**Comment by Orphiex** [comment]
Can confirm all of the above. Choosing option 1 softlocks the game, choosing option 3 crashes it.

**Comment by Moomoobeef** [comment]
this happens to me as well

**Comment by Zuntti** [comment]
Fixed seeing his stock crashing the game

**Comment by Oskutin** [comment]
the crash is fixed, but can't seem to be able to pay

**Comment by Oskutin** [comment]
Oh, it is just missing dialogue for no. money.

**Comment by Oskutin** [comment]
Implemented
