### ISSUE TITLE
[Playtesting] Asking the person at the desil pump what they are selling crashes the game

### ISSUE THREAD

**Issue by Taco-Cat1** [loiste-interactive/Obenseuer-Issues#2992]

**Comment by TonyFromRomania** [comment]
is less crashing and more softlocking, or at leas that happened  to me

**Comment by Oskutin** [comment]
Nextej reported this less than hour ago

**Comment by Taco-Cat1** [comment]
No not that you want to buy desil. You ask what they are selling (the thrid dialogue option)
