### ISSUE TITLE
Playtesting - the Control Room at the service area have a stairs that act like a ramp, preventing player from climbing it up

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#2999]
![image](https://github.com/user-attachments/assets/89a16111-8691-40d7-baf9-1ce0756e0c4c)

**Comment by Oskutin** [comment]
dupe https://github.com/loiste-interactive/Obenseuer-Issues/issues/2989 ?

**Comment by Nextej** [comment]
exiting the Control Room via door spawns you near the elevator shaft instead of actual door
![image](https://github.com/user-attachments/assets/454fb193-86ba-4c63-b340-da75e2969b20)

**Comment by Oskutin** [comment]
or is this the different hut?
