### ISSUE TITLE
Minitrains - behind canteen, if the train enters the aux track, it cannot leave it, as it hits walls whenever approaching either of the switches

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#3002]
![image](https://github.com/user-attachments/assets/357f18de-e276-4b6f-a3fb-dbf62418b6ff)
![image](https://github.com/user-attachments/assets/d7566763-232c-4472-9256-109fcc99155f)

**Comment by Oskutin** [comment]
is fixed
