### ISSUE TITLE
Minitrains - behind Monitoring Room, a part of the tracks between switches causes the train to reverse around for a moment

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#3003]
![image](https://github.com/user-attachments/assets/8edca3db-1ed4-4c88-bb05-70a2ac0bec1a)

**Comment by Oskutin** [comment]
This is weird, as that excact piece of tracks works for me

**Comment by Nextej** [comment]
[Player-prev.log](https://github.com/user-attachments/files/18129943/Player-prev.log)

the crashes eventually in that spot, but no crash logs are produced

**Comment by Oskutin** [comment]
hmm, not even saving and loading breaks it for me. There has to be something different in build

**Comment by Oskutin** [comment]
track change 4B (Doesn't exists?)Backward speed: 1,589999 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Train cannot switch track segment correctly! Backward, reverse dir: True 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

track change 4B (Doesn't exists?)Backward speed: 1,589999 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Train cannot switch track segment correctly! Backward, reverse dir: True 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

track change 4B (Doesn't exists?)Backward speed: 1,589999 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Train cannot switch track segment correctly! Backward, reverse dir: True 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

track change 4B (Doesn't exists?)Backward speed: 1,589999 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Train cannot switch track segment correctly! Backward, reverse dir: True 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

track change 4B (Doesn't exists?)Backward speed: 1,589999 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Train cannot switch track segment correctly! Backward, reverse dir: True 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

track change 4B (Doesn't exists?)Backward speed: 1,589999 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Train cannot switch track segment correctly! Backward, reverse dir: True 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

track change 4B (Doesn't exists?)Backward speed: 1,589999 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Train cannot switch track segment correctly! Backward, reverse dir: True 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

track change 4B (Doesn't exists?)Backward speed: 1,589999 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Train cannot switch track segment correctly! Backward, reverse dir: True 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

track change 4B (Doesn't exists?)Backward speed: 1,589999 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Train cannot switch track segment correctly! Backward, reverse dir: True 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

track change 4B (Doesn't exists?)Backward speed: 1,589999 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Train cannot switch track segment correctly! Backward, reverse dir: True 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

**Comment by Oskutin** [comment]
Can't reproduce any issues on that spot, no matter what i do

**Comment by Nextej** [comment]
The same issue happens at the part between switches connecting the ore dropoff at the service area with the tunnel from Erikson's Claim
![image](https://github.com/user-attachments/assets/2e1c455d-0002-41a5-b65c-db0d188dd448)

**Comment by Nextej** [comment]
[Player.log](https://github.com/user-attachments/files/18130205/Player.log)

**Comment by Oskutin** [comment]
Can't neither reproduce that one. There has to be some weird build-editor difference, race condition or something weird

**Comment by Oskutin** [comment]
track change 4B (Doesn't exists?)Backward speed: 1,859999 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Train cannot switch track segment correctly! Backward, reverse dir: True 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Train changed track segment 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

track change 4B (Doesn't exists?)Backward speed: 1,859999 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Train cannot switch track segment correctly! Backward, reverse dir: True 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Again the segmentswitch 4B

**Comment by Oskutin** [comment]
Fixed "track change 4B"
