### ISSUE TITLE
Minitrains - when coming from SOMC tunnel towards to the service area, there's a one way invisible walls that stops the trains

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#3005]
![image](https://github.com/user-attachments/assets/30bef455-d227-4339-a602-09c362e8ff1b)

**Comment by Oskutin** [comment]
what does log say?

**Comment by Nextej** [comment]
[Player.log](https://github.com/user-attachments/files/18130181/Player.log)

**Comment by Oskutin** [comment]
track change 4B (Doesn't exists?)Backward speed: 1,859999 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Train cannot switch track segment correctly! Backward, reverse dir: True 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Train changed track segment 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

track change 4B (Doesn't exists?)Backward speed: 1,859999 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Train cannot switch track segment correctly! Backward, reverse dir: True 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Train crashed at speed of 1,859999 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)


again 4B

**Comment by Oskutin** [comment]
this is fixed
