### ISSUE TITLE
[Playtesting] Exiting the electrical room (1) from the downstairs exit will shove the player into a rock

### ISSUE THREAD

**Issue by Taco-Cat1** [loiste-interactive/Obenseuer-Issues#3006]
The player is not softlocked because they can still enter the door but this effectively means that there are two entrances and only one exit

**Comment by Oskutin** [comment]
The generator hall or other place?

**Comment by Taco-Cat1** [comment]
The other place

**Comment by Oskutin** [comment]
Fixed
