### ISSUE TITLE
Minitrains - stuck spot after passing by the first radioactive waste gate to the right

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#3009]
![image](https://github.com/user-attachments/assets/eedec8f6-dfbe-4432-bda7-b59f7f954311)
locomotive does not move, carts do when operated with the lever, they still connected in the pic

**Comment by Oskutin** [comment]
logfile?

**Comment by Nextej** [comment]
[Player.log](https://github.com/user-attachments/files/18131322/Player.log)

**Comment by Oskutin** [comment]
Fixed. Track wasn't properly connected there
