### ISSUE TITLE
Minitrains - coming up to the Service Area from western side on the right track has a stuck spot

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#3010]
![image](https://github.com/user-attachments/assets/47dcc8eb-99a8-4f80-abc8-7a2bbfe34fb7)

**Comment by Nextej** [comment]
Coming from the left track crashes the game
![image](https://github.com/user-attachments/assets/b5d19d4c-748c-41d7-984e-d7cece08e56b)

**Comment by Nextej** [comment]
[Player.log](https://github.com/user-attachments/files/18131652/Player.log)
[crash.dmp](https://github.com/user-attachments/files/18131654/crash.dmp)
[Player.log](https://github.com/user-attachments/files/18131655/Player.log)

**Comment by Oskutin** [comment]
this necessiates a log file

**Comment by Oskutin** [comment]
Seems to be rednering based crash

**Comment by Oskutin** [comment]
Stuckpoint is fixed, switch is still weird

**Comment by Oskutin** [comment]
Fixed

**Comment by Oskutin** [comment]
Won't likely apply retroactively to old save, though.
