### ISSUE TITLE
Minitrains - Invisible wall in the upper Tenement Access tunnel

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#3016]
![image](https://github.com/user-attachments/assets/ca59a879-4619-4dc0-bf89-842852ae02ab)

**Comment by Oskutin** [comment]
Does it happen you drive up with only a locomotive

**Comment by Nextej** [comment]
[Player.log](https://github.com/user-attachments/files/18131994/Player.log)

later in that tunnel it also crashed game randomly, no further logs, no crash log

**Comment by Nextej** [comment]
![image](https://github.com/user-attachments/assets/99669cfd-bccd-45a8-8db3-48a0ccf955d9)
another spot in the same area, towards Service Area

didn't happen before when there was only 4 carts total (including a locomotive)

**Comment by Nextej** [comment]
I think this is consistent with test map, where long train sets started to hitting stop at random moments where otherwise shorter trains were doing fine

**Comment by Oskutin** [comment]
seems that train is colliding with itself

**Comment by Oskutin** [comment]
i think you should close this (and the other invis walls with long  trains) and make new issue about long trains self colliding

**Comment by Oskutin** [comment]
im prob going to need save for debugging anyway

**Comment by Nextej** [comment]
> i think you should close this (and the other invis walls with long trains) and make new issue about long trains self colliding

not all invisible walls are caused by long trains

**Comment by Nextej** [comment]
> im prob going to need save for debugging anyway
[Uploading Mines_Update.zip…]()
slot 3

**Comment by Oskutin** [comment]
This doesn't happen anymore
