### ISSUE TITLE
[Playtesting] Pea Soup recipe doesnt have item texture

### ISSUE THREAD

**Issue by l-HealthAngel-l** [loiste-interactive/Obenseuer-Issues#3019]
After visiting the Redemption Militia's Field Kitchen you get stove recipe for Pea Soup, but it is missing the usual note texture in inventory.
![Screenshot 2024-12-13 235426](https://github.com/user-attachments/assets/2df2e019-148d-4ce6-b99d-35f1c9d6c70f)

**Comment by Oskutin** [comment]
Does this still happen (on new saves)?

**Comment by l-HealthAngel-l** [comment]
> Does this still happen (on new saves)?

Let me test with completely fresh start.

**Comment by l-HealthAngel-l** [comment]
Okay after investigation I found out that, when first time come to Redemption Militia Field Kitchen you get recipe with applied texture, but once you change scenes the texture disappears.
![20241229145329_1](https://github.com/user-attachments/assets/9e082b66-e598-4d4d-9a04-a914965520b4)
![20241229145427_1](https://github.com/user-attachments/assets/60aa3778-5ae7-4fec-a40e-3aea8047cdd7)

**Comment by TonyFromRomania** [comment]
also it happens to the  shroom extract too
![20241229145731_1](https://github.com/user-attachments/assets/28b34908-4484-4a1a-b068-8eb7a5891bf2)

**Comment by Oskutin** [comment]
What does logfile say?

**Comment by Oskutin** [comment]
I also need save

**Comment by TonyFromRomania** [comment]
okay give me a second

**Comment by l-HealthAngel-l** [comment]
> I also need save

Seems it removes some sort duplicates:
![image](https://github.com/user-attachments/assets/bc61a88b-0ac7-439b-8d1c-d9291a0e18f3)

**Comment by TonyFromRomania** [comment]
because on my own save the bug for the pea soup recipe isnt apearing, soo i think is a bit of an individualized bug

**Comment by l-HealthAngel-l** [comment]
> I also need save

Here is the save, but I just spent like 15 min in there to have this issue.
[David_Lund.zip](https://github.com/user-attachments/files/18269675/David_Lund.zip)

**Comment by TonyFromRomania** [comment]
[Slot3.zip](https://github.com/user-attachments/files/18269680/Slot3.zip)
here is mine for the shroom extract

**Comment by Nextej** [comment]
#2806 probably related

**Comment by Oskutin** [comment]
Fixed
