### ISSUE TITLE
[Playtesting] Mug on floor at Dr.Pena's office, picked up changes model skin

### ISSUE THREAD

**Issue by l-HealthAngel-l** [loiste-interactive/Obenseuer-Issues#3021]
First time visiting Dr.Pena I found violet mug on floor with sewage water. Once it is picked it changed skin into white with teddy bear picture.
![Screenshot 2024-12-14 003032](https://github.com/user-attachments/assets/94bbc73b-cdad-413e-af04-e26bde5255b0)
![Screenshot 2024-12-14 003247](https://github.com/user-attachments/assets/04483064-c172-4faf-8b8e-74ed493e0e35)

**Comment by Oskutin** [comment]
removed
