### ISSUE TITLE
Playtest - Vendor Categories no longer work

### ISSUE THREAD

**Issue by CVariable** [loiste-interactive/Obenseuer-Issues#3022]
![grafik](https://github.com/user-attachments/assets/7a0eed90-b83a-4975-aed9-2374336272c6)
For at least Möbelmann and Samuel, but probably all Vendors, you can no longer sort their offerings by category. After selling them something, e.g. a bucket, you can sort to the category that the item belonged to, e.g. "clutter" or "all" instead of just "all".

**Comment by Zuntti** [comment]
Fixed
