### ISSUE TITLE
[Playtesting] Impossible to pick up copy machine droped items

### ISSUE THREAD

**Issue by l-HealthAngel-l** [loiste-interactive/Obenseuer-Issues#3029]
Copy machine is known to have 24 slots for paperwork crafting and 9 inventory slots. But if you load all 9 inventory slots with items and start craft paperwork, machine drops paperwork under machine and it is impossible to pick them up.
![Screenshot 2024-12-14 035619](https://github.com/user-attachments/assets/ef0e562c-9cfb-44da-9515-768f3d3fa622)

**Comment by Oskutin** [comment]
seems to be fixed now
