### ISSUE TITLE
Minitrains - at the end of the tunnel going off from the Baths sauna, the train stopper does not collide with the trains, allowing them to phase through

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#3030]
![image](https://github.com/user-attachments/assets/8116dfdd-4fc9-496f-b3f7-2a5a251e9d17)
![image](https://github.com/user-attachments/assets/545b90dd-bdd4-40cf-92e4-3adabbedf0f9)

**Comment by Oskutin** [comment]
fixed
