### ISSUE TITLE
[Playtesting] Scam Invoice description missing spacing between words

### ISSUE THREAD

**Issue by l-HealthAngel-l** [loiste-interactive/Obenseuer-Issues#3031]
Mouse hover on item or mouse hover on mailing icon gives description "Mail ScamInvoice ready to be sent"
![Screenshot 2024-12-14 040847](https://github.com/user-attachments/assets/2ad18f30-aa31-48ca-af33-4752ce2ccdfe)
![Screenshot 2024-12-14 041110](https://github.com/user-attachments/assets/15b39e5b-f105-4d48-822d-130410b331b7)

**Comment by Oskutin** [comment]
Not a bug, its IDtag
