### ISSUE TITLE
[0.3.38 & Playtesting] Kolhola A17 floating cash box

### ISSUE THREAD

**Issue by l-HealthAngel-l** [loiste-interactive/Obenseuer-Issues#3032]
In Kolhola A17 apartment aka Money Exchange there is shelf with security keypad and on it is Cash Box ... floating.
![Screenshot 2024-12-14 052307](https://github.com/user-attachments/assets/ff45ea00-b28f-4c63-b04f-a636ab69a9ac)

**Comment by Oskutin** [comment]
fixed
