### ISSUE TITLE
[Playtesting] Kolhola A20 Broken mirror has ceramic tile texture

### ISSUE THREAD

**Issue by l-HealthAngel-l** [loiste-interactive/Obenseuer-Issues#3033]
Inside Kolhola A20 there is leaning broken mirror with ceramic tile texture applied.
![Screenshot 2024-12-14 053121](https://github.com/user-attachments/assets/04e63f80-e63d-440e-8a5c-4c6d9ed0dfe4)

**Comment by Oskutin** [comment]
Fixed
