### ISSUE TITLE
[Playtesting] Laura Markkanen interaction locks the player in NPC interaction state

### ISSUE THREAD

**Issue by l-HealthAngel-l** [loiste-interactive/Obenseuer-Issues#3044]
After choosing the dialogue option "Do you know where Ines Hietala is?" it locks player in NPC interaction state.
![20241214121015_1](https://github.com/user-attachments/assets/dbc94c1d-8bb1-4179-a1c6-ba556cd2df4b)

**Comment by Oskutin** [comment]
@Zuntti is this fixed already, or dupe?

**Comment by Zuntti** [comment]
Fixed
