### ISSUE TITLE
[Playtesting] Bad quest trigger in Mines Canteen - "The Disappearance of Alice"

### ISSUE THREAD

**Issue by Orphiex** [loiste-interactive/Obenseuer-Issues#3045]
When talking to Anna Markkanen in the Mines Canteen, it is possible to select the "You have blonde hair!" conversation option without ever having visited Pia, received the task "The Disappearance of Alice" or having found the body of Joel Hietala. Selecting this conversation option counts as the "New Task" trigger for "The Disappearance of Alice" and generates the objective "Ask Laura about Ines" without generating any of the previous objectives.

ADDENDUM: If you trigger this conversation with Anna before talking to Pia and getting the quest officially, you will not be able to ask Tatyana or Axel about Alice even though the task objectives show as unfulfilled in the task log.

**Comment by Zuntti** [comment]
Fixed
