### ISSUE TITLE
Playtesting - Train Depo makeshift level, there's no interaction to enter the tenement from the depo

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#3047]
![image](https://github.com/user-attachments/assets/2a33c3cc-200e-49b3-b3f2-ec2e41953b73)

The ladder also has no collisions

**Comment by ProfRadis** [comment]
Same with tenement depo shaby and it doesnt update the players tenement map just leaves the same door that you can't open before having tenement depo.

**Comment by ProfRadis** [comment]
tenement depo shaby's ladder has also no collision.

**Comment by Oskutin** [comment]
This seems to be already fixed
