### ISSUE TITLE
Playtesting - after clearing out Tenement tunnel, there are still active blasting caps spots player can insert dynamite into

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#3048]
![image](https://github.com/user-attachments/assets/535a700b-1e57-44e4-bf3c-ec065054f6c7)
![image](https://github.com/user-attachments/assets/9ea140df-e7f3-49ec-8b0b-07c9532f06e2)

**Comment by Oskutin** [comment]
just these 2?

**Comment by Nextej** [comment]
It's the same one from different perspectives, was hard to aim towards that one, didn't find more, don't know if there are more

**Comment by Oskutin** [comment]
can't reproduce this

**Comment by Oskutin** [comment]
Actually... Fixed
