### ISSUE TITLE
O-Market pricing issue and items don't unstack when going out of inventory

### ISSUE THREAD

**Issue by eetnaviation** [loiste-interactive/Obenseuer-Issues#305]
Items:
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/117541874/0959e84c-cf53-409a-b6c9-40ca1217a2b0)
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/117541874/ba62d194-e4fd-48f2-a2f0-cda97b57546d)

Card terminal price:
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/117541874/314e1b04-27ba-4e9d-b7af-5b7654e56f42)

Value of one sugar bag: 8OC
I am buying: 10 sugar bags
Price should be 80OC but is 16OC

Also it only shows 2 items on the conveyor (Items don't unstack when going out of inventory)

**Comment by Oskutin** [comment]
Price is now correct
