### ISSUE TITLE
[Playtesting] Jonne Reis apartment assignment doesn't show profile data

### ISSUE THREAD

**Issue by l-HealthAngel-l** [loiste-interactive/Obenseuer-Issues#3051]
Usually in one of these four squares there is NPC's profile, and on mouse hover shows name, age and occupation, but for him it doesnt happen.
![image](https://github.com/user-attachments/assets/0fe1ab9d-e1c5-4b28-a68d-4fc8ae23d8b2)

**Comment by Zuntti** [comment]
Fixed
