### ISSUE TITLE
Playtesting - when tasked to clear the tunnel by Ken, Ken should tell the player where the tunnel is located to avoid confusion

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#3052]
Currently player has no clue where the tunnel is located, there is one supposed access from Service Area, but that's not the right place, the correct tunnel is located above at the Erikson's Claim

**Comment by Nextej** [comment]
also, it is weird that Tenement tunnels have fancy signs put to them, perhaps would be better if those signs looked more makeshift at first, and that they would not appear until player starts the quest, with the guy telling the player they've marked the tunnel prior to their arrival

**Comment by Oskutin** [comment]
I also think that the second sign should only appear when the player mine is level 3

**Comment by Nextej** [comment]
Yes

**Comment by Oskutin** [comment]
Moved the sign
