### ISSUE TITLE
[0.3.38 & Playtesting] Broken Brown Refrigerator still considered as wall decoration

### ISSUE THREAD

**Issue by l-HealthAngel-l** [loiste-interactive/Obenseuer-Issues#3054]
![Screenshot 2024-12-14 191938](https://github.com/user-attachments/assets/b8f721bd-3949-40de-8a28-5ea1864d60b4)

**Comment by Oskutin** [comment]
Version 0.3.43 is the latest...

**Comment by l-HealthAngel-l** [comment]
> Version 0.3.43 is the latest...

I meant the recent version, but all my recent bugs were reporting using playtesting version, I just know that same problem goes and for official release
