### ISSUE TITLE
playtest - Shop vendors funds get reset everytime you leave and re-enter the scene 

### ISSUE THREAD

**Issue by pinkamedic** [loiste-interactive/Obenseuer-Issues#3061]
currently this is happening with mr bags but ill check to see if its happening with other vendors

**Comment by pinkamedic** [comment]
seems like its all vendors

**Comment by Oskutin** [comment]
increase or reset?

**Comment by pinkamedic** [comment]
yeah it seems to just reset rather then increase as it wont go past a point

**Comment by Zuntti** [comment]
Fixed
