### ISSUE TITLE
Train-Train violence causes a crash if re-entered

### ISSUE THREAD

**Issue by Tritiumisotope** [loiste-interactive/Obenseuer-Issues#3063]
![image](https://github.com/user-attachments/assets/8a1f94e4-b51a-497d-8572-2fcbf3fe5af0)

Getting on the train in back crashes the game. Autosave Attached 

[Autosave2.zip](https://github.com/user-attachments/files/18137950/Autosave2.zip)

**Comment by Oskutin** [comment]
I need log and crash dump

**Comment by Tritiumisotope** [comment]
apparently they were coupled btw

**Comment by Tritiumisotope** [comment]
where is the crashlog dir?

**Comment by Oskutin** [comment]
fixed
