### ISSUE TITLE
Playtesting (0.3.43 v2) - Tenement map doesn't update the door in basement to Tenement Depo when you have makeshift or above

### ISSUE THREAD

**Issue by ProfRadis** [loiste-interactive/Obenseuer-Issues#3064]

**Comment by ProfRadis** [comment]
![20241215003541_1](https://github.com/user-attachments/assets/0a7ae62b-429e-4a81-a072-57d75b0d41da)
![20241215003537_1](https://github.com/user-attachments/assets/390f6ff9-ae17-4d1e-8353-601145bcf981)

**Comment by Zuntti** [comment]
Fixed
