### ISSUE TITLE
Playtesting (0.3.43 v2) - Furniture sink into later tenement depot upgrades

### ISSUE THREAD

**Issue by ProfRadis** [loiste-interactive/Obenseuer-Issues#3068]
this one is decent upgrade
![20241215010244_1](https://github.com/user-attachments/assets/78ddf5b5-9070-49c9-9a91-8ae0c26a550e)

**Comment by Oskutin** [comment]
uh?

**Comment by ProfRadis** [comment]
but on makeshift entire floor is lowered that in building mode furniture is sunken in to floor.

**Comment by ProfRadis** [comment]
but now i dont have that upgrade

**Comment by ProfRadis** [comment]
![20241214020003_1](https://github.com/user-attachments/assets/fa3835d9-8d5a-41f9-bf0c-67f92b6f33b2)
here is the only thing i have

**Comment by ProfRadis** [comment]
that furniture on platform are sunken like its on the ground below it is attached

**Comment by Oskutin** [comment]
Okay, as train depo has a lot of changing geometry, the furniture there should return to the inventory
