### ISSUE TITLE
Playtesting - Lockpicks go into the negative

### ISSUE THREAD

**Issue by CVariable** [loiste-interactive/Obenseuer-Issues#3069]
![grafik](https://github.com/user-attachments/assets/1e68cf72-61a1-4ea3-9540-d2f4e8dcb1a1)
After lockpicking the first toolbox we see in the mines, my 12 lockpicks turned into -1 lockpick.
Adding the 12 i found in the toolbox turned it to 11.
In the same savefile, when i used a lockpick earlier, and failed the lockpicking, it just disappeared like it should.

**Comment by Oskutin** [comment]
How reproductible this is?

**Comment by CVariable** [comment]
it seems quite reproducable, i will upload a savefile right in front of the toolbox;
When you use the lockpicks and fail a few times, the amount you failed will turn into the negative lockpicks in your inventory, and the amount of lockpicks you had before will be in the toolbox you unlocked.
Also, the toolbox has a red border and wiggles when you unlock it, i'm unsure if that is intended.
Failing 5 times when having 12 picks results in this:
![grafik](https://github.com/user-attachments/assets/5f0fe8c1-f003-4013-b46d-8461d5bc0508)
Savefile: 
[Slot5.zip](https://github.com/user-attachments/files/18138233/Slot5.zip)

**Comment by CVariable** [comment]
This used to happen every time, but after migrating the save to the latest version, it no longer happens. Something must have fixed it between versions.
