### ISSUE TITLE
Playtest - Loose items will not stack atop each others

### ISSUE THREAD

**Issue by Blake81** [loiste-interactive/Obenseuer-Issues#3074]
I tried to stack some food cans (sour herring, canned meat, canned pineapple) atop each others on the Plywood Shelf and it would not work. The cans would just clip into each others and not stack. Tried this with all sorts of items, and they all clip through each others. Only happens to loose items, not furnuture.

![20241214211123_1](https://github.com/user-attachments/assets/2b10dfd0-616b-4240-aff3-2e44b5f95ef1)
![20241214211129_1](https://github.com/user-attachments/assets/8d48ece4-d659-4e89-92b3-f8f2577abbe3)
![20241214213823_1](https://github.com/user-attachments/assets/9d6f0cbe-17e6-4e4c-8e1a-37e32d586a2c)

I can say this was not happening on the Stable version.

**Comment by Zuntti** [comment]
Fixed
