### ISSUE TITLE
Playtesting - Upgrading the Tenement Mine access interferes/disables with other tenement upgrades

### ISSUE THREAD

**Issue by BoulderCabin** [loiste-interactive/Obenseuer-Issues#3077]
After upgrading the Mine to Level 2 / Shabby, it appears to do something to the other tenement upgrades. in my instance it disabled the Walls and upgrades reliant on those walls (kitchen, bathroom, balcony) in multiple apartments. 

![20241214204109_1](https://github.com/user-attachments/assets/3cff3d12-0890-4fb4-8a47-953b809959d3)

![20241214204123_1](https://github.com/user-attachments/assets/897a73ff-e299-4fa2-a1df-a8ef78f7b55e)

![20241214230200_1](https://github.com/user-attachments/assets/eafbe4fe-e67d-4d14-b1b8-165ffea3e047)

**Comment by BoulderCabin** [comment]
[Slot2.zip](https://github.com/user-attachments/files/18138982/Slot2.zip)

Attaching my save for this.

**Comment by Zuntti** [comment]
Fixed
