### ISSUE TITLE
[Playtesting] Minitrains stuck near Tenement Depo in both access tunnels

### ISSUE THREAD

**Issue by l-HealthAngel-l** [loiste-interactive/Obenseuer-Issues#3078]
West side tunnel stops the minitrain, but able to move further into tunnels just not into depo (Was riding backwards):
![20241215072517_1](https://github.com/user-attachments/assets/9f01f398-c3fc-402c-b8e9-cbbca94d8fcf)

East side tunnel stops minitrain and makes it stuck, you can't go forward or backwards like minitrain would be derailed, because wheels are spinning but staying in place:
![20241215072650_1](https://github.com/user-attachments/assets/d2746a85-c3e6-45b1-9c10-a98e28f405d8)

**Comment by Oskutin** [comment]
Upgrades are still missing functional tracks.

**Comment by Oskutin** [comment]
Fixed
