### ISSUE TITLE
[Playtesting] Unable to place anywhere Fancy leather Chair!

### ISSUE THREAD

**Issue by l-HealthAngel-l** [loiste-interactive/Obenseuer-Issues#3079]
By trying to place "Fancy leather Chair" (I think word 'leather' should be capitalized as well) registers as the chair is inside the object.
![20241215143847_1](https://github.com/user-attachments/assets/3e4ccdd8-68ce-4595-855c-a7cdf0828585)

**Comment by Oskutin** [comment]
Fixed
