### ISSUE TITLE
[Playtesting] Hospital Table has model anomalies

### ISSUE THREAD

**Issue by l-HealthAngel-l** [loiste-interactive/Obenseuer-Issues#3082]
While hospital table is selected, before placement two floating orbs can be visible, after placing them they disappear.
1. Invalid Placement.
2. Valid Placement.
3. Placed Furniture
![Hospital Bed my Beloved](https://github.com/user-attachments/assets/71cb5e93-a1cb-4879-a2e5-b7835bd4f922)

**Comment by Oskutin** [comment]
fixed
