### ISSUE TITLE
Playtesting - "I Yearn for the Mines" achievement is not triggered on older saves

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#3084]

**Comment by Oskutin** [comment]
I need save for testing pursposes

**Comment by Nextej** [comment]
oh yeah, forgot about that, try slot 7
[Mines_Update.zip](https://github.com/user-attachments/files/18203547/Mines_Update.zip)

**Comment by Oskutin** [comment]
fixed

**Comment by Oskutin** [comment]
fixed
