### ISSUE TITLE
[Playtest] - Saving and reloading refreshes rock pile in Erikson's claim.

### ISSUE THREAD

**Issue by berryberrynaisu** [loiste-interactive/Obenseuer-Issues#3085]
https://github.com/user-attachments/assets/6ed7600d-a16a-4960-8595-e74af39a1dc4

**Comment by berryberrynaisu** [comment]
On testing further it seems this is the case with all rock piles not just the one in Erikson's claim.

**Comment by Oskutin** [comment]
Does this apply ores too?

**Comment by berryberrynaisu** [comment]
From what I've seen it only affects rocks. Tried to replicate it with ore and they did not refresh.

**Comment by Oskutin** [comment]
fixed
