### ISSUE TITLE
Save slot menu feedback

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#309]
1. In the main menu "Load Game" should present the latest used character, additional, next to each characters name, a last date of the latest save it was played on, should be displayed, so it's easier to find recent characters, or characters played before, without blind guess by names
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/e2816a86-dfbc-49d1-9b89-0186ef0c4e96)
2. Both in the main menu and the esc menu, the latest saveslot (except for autosave) should be highlighted, so it's easier to let player know on which slot did the end up last time and or which slot is next in order to save the progress to.
Any sorts of indication which slot was the latest will be useful
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/9fa84a15-31a2-4f02-9a18-8d1bc966c069)

**Comment by Zuntti** [comment]
Changed the pause menu to look like this https://github.com/loiste-interactive/Obenseuer-Issues/issues/112
