### ISSUE TITLE
Playtest - Dating Tanja freezes the game

### ISSUE THREAD

**Issue by CVariable** [loiste-interactive/Obenseuer-Issues#3096]
Agreeing to a date after giving her the form gives a black screen, coffee sound effect, and then locks the player into this screen:
![grafik](https://github.com/user-attachments/assets/f904d26e-cc3d-4144-8499-3202906e33ae)
Bug is reproducable every time on non-migrated savefile: 
[Slot2.zip](https://github.com/user-attachments/files/18142507/Slot2.zip)

**Comment by Zuntti** [comment]
Fixed
