### ISSUE TITLE
Playtesting - Minitrain glitching and game crashing when leaving service area

### ISSUE THREAD

**Issue by CVariable** [loiste-interactive/Obenseuer-Issues#3097]
When driving the minitrain in the provided save forward, it will glitch out for a second and then crash the game, reproducable every time.
![grafik](https://github.com/user-attachments/assets/817709ab-fd53-4681-82e6-9ba258c382c0)

[Slot3.zip](https://github.com/user-attachments/files/18142591/Slot3.zip)

**Comment by Oskutin** [comment]
already fixed

**Comment by Oskutin** [comment]
Nextej has already scouted pretty much every piece of track
