### ISSUE TITLE
Playtesting - Well is unwell (missing image)

### ISSUE THREAD

**Issue by CVariable** [loiste-interactive/Obenseuer-Issues#3098]
![grafik](https://github.com/user-attachments/assets/0423db81-7af4-489a-aaa1-97d6071dcb1b)
![grafik](https://github.com/user-attachments/assets/2971c382-b00e-4e87-ba13-79f77924aaa4)

**Comment by Oskutin** [comment]
Need to change it to the new water source thing

**Comment by Zuntti** [comment]
Fixed
