### ISSUE TITLE
Playtest - Kurahaara greenhouse oven doesn't heat the crops after leaving

### ISSUE THREAD

**Issue by MissCassidy06** [loiste-interactive/Obenseuer-Issues#3102]
Title says it all: The oven in the kurahaara greenhouse stops heating the crops when you leave the area. When reentering you can watch the thermometer drop despite the oven being on.

**Comment by Zuntti** [comment]
The value appears to be too high and it drops to the correct value

**Comment by Zuntti** [comment]
Fixed
