### ISSUE TITLE
Playtesting - data migration on some maps is too brutal on some level

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#3103]
![image](https://github.com/user-attachments/assets/0aa79e09-e626-4130-b530-847139c1d571)

Kolhola in example takes around 30-40 minutes to migrate

any chances to optimize the process?

**Comment by Oskutin** [comment]
i can take a look at one point.

**Comment by Oskutin** [comment]
Optimized the process at one point
