### ISSUE TITLE
Drawer that shouldn't be marked as owned

### ISSUE THREAD

**Issue by MissCassidy06** [loiste-interactive/Obenseuer-Issues#3105]
This specific drawer in Dekula B3 is marked as owned, even though everything else in the apartment isn't.
![grafik](https://github.com/user-attachments/assets/999d0665-4b5e-4313-96cc-400945f1a62a)

**Comment by Oskutin** [comment]
Playtest version?

**Comment by Oskutin** [comment]
Actually it should be the other way around, ad that apartment is still lived

**Comment by MissCassidy06** [comment]
Yes, it's playtest.

**Comment by Zuntti** [comment]
Fixed
