### ISSUE TITLE
Floor bed blueprint requires coin instead of pillow

### ISSUE THREAD

**Issue by PoyanBD** [loiste-interactive/Obenseuer-Issues#3109]
Describe:
In the inventory tab the blueprints for floor bed is showing wrong item

Reproduce:
Open the inventory tab and look through blueprints and find the one for floor bed displayed require items are "Mattress - Cloth roll - Open Sewer Coin".
![image](https://github.com/user-attachments/assets/1a54c132-a40d-45f1-b602-bbf97f704323)

Expected behavior:
Displayed require items should be "Mattress - Cloth roll - Pillow"

V 0.3.43
Playtesting

**Comment by Zuntti** [comment]
Fixed

**Comment by PoyanBD** [comment]
![image](https://github.com/user-attachments/assets/092d6828-8997-4453-bf9f-fcd0f73f33b6)

@Zuntti Barrel planter has the same issue

**Comment by TonyFromRomania** [comment]
that is more of a visual bug then anything

**Comment by PoyanBD** [comment]
Oh yea when crafting requirements are as it should be just the blue prints displayed requirement is wrong.

**Comment by l-HealthAngel-l** [comment]
That happens only when you examine the blueprints in your inventory, at worktable looks fine
![Screenshot 2024-12-16 215316](https://github.com/user-attachments/assets/636e7321-56b9-4023-9d5c-41106a0ae267)

**Comment by TonyFromRomania** [comment]
i think most of those that have that bug are furniture that for crafting requires a buyable furniture piece, like beds need you to buy the pillow they need , because the recipe of it is considered as an esential quest item for some reason

**Comment by l-HealthAngel-l** [comment]
@Zuntti
