### ISSUE TITLE
Tenement tunnel closing

### ISSUE THREAD

**Issue by TheGungeonologist** [loiste-interactive/Obenseuer-Issues#3113]
Cleared the tenement tunnel, came back a long while later, and it's closed again
![Screenshot 2024-12-16 123440](https://github.com/user-attachments/assets/d76185a7-743f-4a63-999b-14efbbd71e38)
![image](https://github.com/user-attachments/assets/18adb4b6-aa09-46bc-a793-aac6f4489962)

**Comment by Oskutin** [comment]
Need your savegame to check this

**Comment by Oskutin** [comment]
no details provided
