### ISSUE TITLE
playtest 0.3.43: Duct in Emil Kauha's mine has no collision

### ISSUE THREAD

**Issue by Akmeddeadterrorist** [loiste-interactive/Obenseuer-Issues#3115]
As per the title the duct in Emil Kauha's mine has no collision.

![duct in mines](https://github.com/user-attachments/assets/31094178-a923-4361-972f-d39216ec68e3)
![clipping through duct in mines](https://github.com/user-attachments/assets/5a48498a-39ff-4807-b383-ea2b8b0c2932)

**Comment by Oskutin** [comment]
added
