### ISSUE TITLE
[Playtesting] On blueprint exam some blueprints require sewer coins, but on worktable is fine

### ISSUE THREAD

**Issue by l-HealthAngel-l** [loiste-interactive/Obenseuer-Issues#3116]
From the currently closed issue: https://github.com/loiste-interactive/Obenseuer-Issues/issues/3109 I am reposting my comment as new issue by Oskutin's suggestion.

There is more blueprints which are asking for sewer coins by examining blueprint, so I mention all of them including these two already mentioned on previous issue ticket:
- Barrel Planter Blueprint.
- Plank Bed Blueprint.
- Moonshine Distillery Blueprint.
- Chemical Lab Blueprint.
- Floor Bed Blueprint.
- Makeshift IBC Sink Blueprint.
- Mashing Barrel Blueprint.
- Shabby Bed Blueprint.

![Toss a coin to your witcher](https://github.com/user-attachments/assets/189b3c98-c9f3-4f31-acf7-f2fad3ad8a32)

**Comment by TonyFromRomania** [comment]
soo aparently from a quick scan this show that pillow , barrel and the aguarium/terratium are causing this bug all of them are most of the part only purchase-able items
