### ISSUE TITLE
Playtesting - Disappearance of Alice Quest broken and unfinishable

### ISSUE THREAD

**Issue by CVariable** [loiste-interactive/Obenseuer-Issues#3118]
After finding alice in small storage, using the osrat and taking the picture from her hand, the dialogue options with pia have not updated despite the quest telling me to tell pia what i found.
Quest status:
![grafik](https://github.com/user-attachments/assets/edae1a17-dfb3-4d94-a186-bfbb5802fe89)

Possible dialogue with pia:
![grafik](https://github.com/user-attachments/assets/7e9fedc3-1dba-4274-aa86-e439d5693fed)
None of the dialogue options allow me to inform her about anything i found.

**Comment by CVariable** [comment]
I wonder if it has something to do with the fact that i talked to the girl in the sauna/pool combo in the mines. 
Additionally, i tried to talk to Axel Norberg about it, but he has no dialogue options regarding the quest, despite pia telling us to "ask axel who is in the guardhouse usually"

**Comment by Zuntti** [comment]
Can I get a save where this happens?

**Comment by CVariable** [comment]
[Slot5.zip](https://github.com/user-attachments/files/18188867/Slot5.zip)
Here is the save where it happens, it is a new, non migrated save on the latest playtest version

**Comment by Zuntti** [comment]
It merged with another task which had the wrong name

**Comment by Zuntti** [comment]
Fixed
