### ISSUE TITLE
Playtest 0.3.43 - Sand and Fertile Soil bags have no collision

### ISSUE THREAD

**Issue by Moomoobeef** [loiste-interactive/Obenseuer-Issues#3119]
# About
Sand and Fertile Soil bags no longer have collision and objects cannot be placed on top of them.

### Media
https://www.youtube.com/watch?v=yWd_s_Bei1I
Here you can see a save I had migrated where previously I had stacked up bags of resources. After migration, the affected items will have no collision, and can no longer have items placed on top. (not pictured is that new bags placed will have the same problems.)

# Reproduction
1. Place bags of sand/fertile soil (there might be other objects affected by this but these are the two I noticed)
2. Attempt to walk/place items on top of them
3. Failure

### My system
I am running Obenseuer in Manjaro Linux with the following specs
```
CPU: AMD Ryzen 9 5900X (24) @ 3.700GHz
GPU: 2x NVIDIA TITAN X (Pascal)
RAM: 32Gb
Kernel: 6.6.63-1-MANJARO
```

**Comment by Zuntti** [comment]
Already fixed in upcoming

**Comment by Moomoobeef** [comment]
![image](https://github.com/user-attachments/assets/9e4962f6-6393-43c0-b90d-916cc8177c11)
This problem is only half solved. The offending items no longer have no collision to objects in build mode, but you can still walk right through them.
