### ISSUE TITLE
[Playtesting] Dosimeter doesn't turn off when battery runs out

### ISSUE THREAD

**Issue by l-HealthAngel-l** [loiste-interactive/Obenseuer-Issues#3122]
Once dosimeter is equipped and turned on, it uses battery in order to show background radiation, but when battery is depleted, the dosimeter doesn't shuts off and allows battery level go in negative percentage.
![Screenshot 2024-12-17 004750](https://github.com/user-attachments/assets/5c7a9f94-91d9-4fb7-adf0-fd18cde9dec4)

**Comment by Oskutin** [comment]
Likely related: https://github.com/loiste-interactive/Obenseuer-Issues/issues/3138

**Comment by Oskutin** [comment]
Fixed
