### ISSUE TITLE
[Playtesting] Puuhari magazines doesn't change time on reading

### ISSUE THREAD

**Issue by l-HealthAngel-l** [loiste-interactive/Obenseuer-Issues#3123]
Puuhari magazines are defined to have 1.17h reading time, but once it is used to read, it doesn't give the clock screen as you would sleep, watch TV or read Open Sewer or ARG magazine.

https://github.com/user-attachments/assets/8f75efe5-a074-4940-90bf-ef20ffda6e70

**Comment by Oskutin** [comment]
effectively dupe of https://github.com/loiste-interactive/Obenseuer-Issues/issues/3138
