### ISSUE TITLE
Playtest 0.3.43 - Autosaves created by moving around on the minitrain do not save skills, thus erasing them.

### ISSUE THREAD

**Issue by Moomoobeef** [loiste-interactive/Obenseuer-Issues#3128]
# About
When driving the minitrain through an auto-save zone, the resulting autosave will have all skills reset.

# Reproduction
1. Drive minitrain through an auto-save point
2. load autosave
3. look at your skills
4. cry

### My system
I am running Obenseuer in Manjaro Linux with the following specs
```
CPU: AMD Ryzen 9 5900X (24) @ 3.700GHz
GPU: 2x NVIDIA TITAN X (Pascal)
RAM: 32Gb
Kernel: 6.6.63-1-MANJARO
```

**Comment by Zuntti** [comment]
Can't reproduce. Can I get a save where this happens?

**Comment by Moomoobeef** [comment]
Here's the save file, both a save immediately before the bug, and an autosave where the bug has happened.
[Saves.zip](https://github.com/user-attachments/files/18190503/Saves.zip)

Here's a video demonstrating the problem
https://youtu.be/quZSIT6h_w0?si=ucuqKf-B6wNugpCx&t=16

**Comment by Oskutin** [comment]
Fixed
