### ISSUE TITLE
[Playtest] Significant performance drop after recent update inside player tenement

### ISSUE THREAD

**Issue by AllayTheWolf** [loiste-interactive/Obenseuer-Issues#3130]
Version 0.3.43

After the recent update, performance inside the player tenement has taken a massive drop (relative to me at least, who already didn't have good performance as I cannot afford the best modern hardware).

Previously, my own apartment would average around 23-26 frames, which was manageable. The basement + lower basement workshop would boost to 30 or slightly above, likely because the rest of the tenement building wasn't loaded.

Now however, the entire building averages around 12-15 frames, including the previously "safe" basement. This is on a max-occupied tenement with minimum level 3 walls for everyone, a few with better, and overall I'd say 65~ish% upgrades for everyone.

https://github.com/user-attachments/assets/bf1e4e95-9627-41a8-aea4-b821f506407c

**Comment by Zuntti** [comment]
Can I get a save where this happens?

**Comment by AllayTheWolf** [comment]
Here, hopefully it'll work for ya.


[Slot1.zip](https://github.com/user-attachments/files/18166223/Slot1.zip)

**Comment by Oskutin** [comment]
In the save the entire building (-player room) is bare

**Comment by Oskutin** [comment]
I think i got it atleast a bit better now

**Comment by Oskutin** [comment]
Btw, those mushroom terrariums cause a lot of lag when they have glowing shrooms in them

**Comment by AllayTheWolf** [comment]
Thank you so much Oskutin! I'll keep that in mind too, thank you.
