### ISSUE TITLE
Playtesting - Tenement A maintenance room, Ten A basement key and a pendrive do not have "stolen" tag

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#3133]
![image](https://github.com/user-attachments/assets/f10fe9e3-68fa-41f0-89f0-cb7da79d9362)
![image](https://github.com/user-attachments/assets/ba67bf4a-d833-4393-b56c-251fe189d5af)

**Comment by Oskutin** [comment]
should they?

**Comment by Nextej** [comment]
everything else in the maintenance area, including that room has 'stolen' tag

**Comment by Oskutin** [comment]
Now they do
