### ISSUE TITLE
[Playtesting] Now ARG magazine doesn't change time on read

### ISSUE THREAD

**Issue by l-HealthAngel-l** [loiste-interactive/Obenseuer-Issues#3138]
Previously I reported Puuhari magazines weren't adding defined 1.17 hours https://github.com/loiste-interactive/Obenseuer-Issues/issues/3123 , this time ARG magazine doesn't add 2 hours.

https://github.com/user-attachments/assets/3db8ae20-016f-42b7-82e0-7b88a5d83d74

**Comment by Oskutin** [comment]
Works for me. I can i have a save where this happens.

**Comment by l-HealthAngel-l** [comment]
> Works for me. I can i have a save where this happens.

Sure thing, just don't be alarmed with so much things in inventory 😄  , also save is allocated in slot 9
[John_Sewer.zip](https://github.com/user-attachments/files/18172130/John_Sewer.zip)

**Comment by Oskutin** [comment]
Can't reproduce, works even on your save
