### ISSUE TITLE
cant remove metal sheet on the 4th floor of player tenaments 

### ISSUE THREAD

**Issue by Asireldreemurr213** [loiste-interactive/Obenseuer-Issues#3139]
when i click to remove it only rotates and does not remove it
![Screenshot_140](https://github.com/user-attachments/assets/c432a605-a57e-4615-9265-0ed2f6b898bf)

**Comment by l-HealthAngel-l** [comment]
I didn't had issue with this corrugated metal sheet, it gets stored as piece of furniture.

**Comment by Oskutin** [comment]
Save is needed to check this

**Comment by Asireldreemurr213** [comment]
[Jeff_Aarhus.zip](https://github.com/user-attachments/files/18171824/Jeff_Aarhus.zip)

**Comment by Asireldreemurr213** [comment]
there u go sorry it took so long to upload

**Comment by Zuntti** [comment]
Fixed
