### ISSUE TITLE
Tenement System: Picking up a storage with an items will cause the items to disappear after the reload and the storage to respawn

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#314]
How to recreate:
- place a storage
- put items
- pick up the storage
- reload the level
- storage will respawn, empty
- storage you had in your inventory will be empty
- placing it will replace the respawned (see above) storage

in short, stored items are not saved between reloads.

**Comment by Zuntti** [comment]
Fixed
