### ISSUE TITLE
[Playtesting] Paper towel playing magic tricks

### ISSUE THREAD

**Issue by l-HealthAngel-l** [loiste-interactive/Obenseuer-Issues#3140]
At Player Tenement, floor 6 medium apartment in unclean apartment in very same corner there was a table with some random things and this paper towel roll on it. To make cleaning efforts faster, I in cleaning mode picked up the table, what was on table it was picked up automatically except this towel roll. Currently I can't either approach the roll, or pick it up using cleaning mode.

https://github.com/user-attachments/assets/83047446-ada1-4185-b1fb-786c38227459

**Comment by Oskutin** [comment]
fixed
