### ISSUE TITLE
[Playtest] Jail time being incredibly short

### ISSUE THREAD

**Issue by MissCassidy06** [loiste-interactive/Obenseuer-Issues#3142]
Even though the option with the cop to go to jail said I would be in for 2 days, I was released immediately.

**Comment by Oskutin** [comment]
Need savegame to investigate

**Comment by pinkamedic** [comment]
this might be part of my issue of the bounty system being broke / cops not giving chase, as when i got arrested i was released right away

**Comment by MissCassidy06** [comment]
Yea, the police didn't chase me either.

**Comment by Oskutin** [comment]
Also, save is necessary to investigate
