### ISSUE TITLE
[Playtesting] Bicycle can't be wall mounted

### ISSUE THREAD

**Issue by l-HealthAngel-l** [loiste-interactive/Obenseuer-Issues#3146]
According whereabouts of Bicycle, it supposed to be wall mounted furniture piece, in reality seems it can't be mounted.. only can be placed on the ground.
![Screenshot 2024-12-18 170808](https://github.com/user-attachments/assets/bf3ff23d-cc11-4b66-89d9-070346e4096f)

**Comment by Zuntti** [comment]
You can change it to wall mounted version by pressing c
