### ISSUE TITLE
Wall Gap in Lab

### ISSUE THREAD

**Issue by jkeller098** [loiste-interactive/Obenseuer-Issues#3148]
![20241218105249_1](https://github.com/user-attachments/assets/ab39955d-6a65-4606-8d7c-275e94375363)
![20241218110305_1](https://github.com/user-attachments/assets/1b8dc4fc-a665-4bf1-8d11-1e4055c8bc9b)
![20241218110654_1](https://github.com/user-attachments/assets/26432641-3a79-4202-82e4-43943dc81148)

In tennement A Frederics lab by the enterance too the lab / apartment.

**Comment by jkeller098** [comment]
![20241218110654_1](https://github.com/user-attachments/assets/9fe59ce0-538f-49df-aa62-17ebbdfe68b7)
a better upclose view

**Comment by Oskutin** [comment]
Fixed
