### ISSUE TITLE
[Playtesting] When Bare Facade and Decent Courtyard colide

### ISSUE THREAD

**Issue by l-HealthAngel-l** [loiste-interactive/Obenseuer-Issues#3150]
I made courtyard renovations to decent, but never upgraded the facade, so main entrance has these Facade decals colliding with courtyard's pavement.

https://github.com/user-attachments/assets/d42451d3-c88c-4521-8de8-6b45c0d0e7f5

**Comment by Oskutin** [comment]
fixed
