### ISSUE TITLE
Playtesting - few dialogue suggestions for 'that gate guard guy, you know who, in the mines'

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#3154]
- Important: When he's about to power the gate for you to open it, he should tell you at what dose of absorbed radiation you should get the hell out of there as fast as possible
- After player progresses the "Glowstick Trail" to be tasked to return to Anya, if player decides to talk to the guy, have a unique conversation started of him commenting of your successful survival
- When he tells you the door combination, add a dialogue option from the player in lines of "are you serious?"/"really, that's the code?'

**Comment by Oskutin** [comment]
Added the first
