### ISSUE TITLE
[v0.3.38] Breaking into the jail effectively clears bounty

### ISSUE THREAD

**Issue by spdx-github** [loiste-interactive/Obenseuer-Issues#3157]
hey! first bug report. encountered this one after robbing the exchange.

i wanted to turn myself in, but didn't want to get tackled by the police, so i broke into the jail to hand myself over in person. when i asked the guard, he said i'd be in for 2 days, so i passed some time in cell 2 for a bit. after only four hours or so, the door was open, and when i buzzed the guard he said i was now free.

i later asked a police officer for the time as if nothing had happened. my 10,000+ bounty cleared, and i hadn't spent the 2 days in prison i was meant to!

i know there's some existing issues with the prison system in playtest, so i hope this doesn't lump too much pressure on. cheers :]

**Comment by Oskutin** [comment]
need a save file where this happens

**Comment by spdx-github** [comment]
[Slot7.zip](https://github.com/user-attachments/files/18220460/Slot7.zip)
about to break into the exchange; i've done it before, but a while ago ingame

[Slot8.zip](https://github.com/user-attachments/files/18220461/Slot8.zip)
just did the crime and now have a 5,000+ bounty

[Slot9.zip](https://github.com/user-attachments/files/18220462/Slot9.zip)
entered the jail via lockpicking and was arrested; now in cell. i asked the guard, he says 24 hours

[Slot10.zip](https://github.com/user-attachments/files/18220463/Slot10.zip)
free after ~4 hours of playing on the gameboy

hope this helps!

**Comment by Oskutin** [comment]
fixed
