### ISSUE TITLE
Clipping cup in Kolhola

### ISSUE THREAD

**Issue by SolidRz** [loiste-interactive/Obenseuer-Issues#3159]
Sometimes _**at random**_ a cup in Kolhola will spawn clipping through the wall next to the telephone on the second floor. It's also for some reason a cup that can be stolen, but you'll get caught by the security camera.

Game version 0.3.43

![image](https://github.com/user-attachments/assets/8bd690b1-34c9-4caa-aa9f-ca294d1fec1c)

**Comment by pinkamedic** [comment]
this has been fixed
