### ISSUE TITLE
For furniture placement, a MOVE button would be nice.

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#316]
Instead of always having to Remove the object and then look it up from the list and reselect it to place it, have a button that allows to remove an object and have kept it selected to immediately place in new spot.

**Comment by Nextej** [comment]
Additionally, any objects placed on to of the furniture that is being moved, could remain their position in relation to that moved furniture once it's placed in a new spot (unless walls or other furniture obstruct those additional objects, in that case they should be removed back to inventory).

**Comment by Zuntti** [comment]
Added
