### ISSUE TITLE
[Playtesting] Helm clock doesn't show 12 o'clock in building mode

### ISSUE THREAD

**Issue by l-HealthAngel-l** [loiste-interactive/Obenseuer-Issues#3160]
All clocks besides Helm Clock shows 12 o'clock to make easier for player to know which side is correct on placement, but Helm Clock shows real time in building mode.

Helm Clock in Building Mode:
![20241220115029_1](https://github.com/user-attachments/assets/c481e160-a770-4a18-b2e8-5c831219d2c0)

Wall Clock in Building Mode for reference:
![20241220115904_1](https://github.com/user-attachments/assets/ac720253-2778-48e6-8f3c-8f088a210b56)

**Comment by Oskutin** [comment]
fixed
