### ISSUE TITLE
[Playtesting] Wine Rack bottle generator

### ISSUE THREAD

**Issue by l-HealthAngel-l** [loiste-interactive/Obenseuer-Issues#3162]
Any wine rack (I don't know how about small ones, didn't had opportunity to buy one) generates bottles once it is placed and player changed scenes (Going out and in back to tenement) generates bottles not in furniture's inventory but into map itself. Player can take this advantage to generate easy Obenseuer Coins just by delivering bottles to O-Market.

1. Placed Wine Racks.
2. Wine Racks with bottles once player is back to tenement.
3. Bottles when furniture is removed by building mode.

![Sewer Coin Generator](https://github.com/user-attachments/assets/44e5df35-4ef5-4f98-8d05-c84013506d93)

**Comment by Oskutin** [comment]
Fixed
