### ISSUE TITLE
Playtesting - fuel counter at the station distributor should have the decimal comma more visible (possibly make it as bright as the numbers)

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#3171]
![image](https://github.com/user-attachments/assets/04b25dfc-f1f5-400a-b6b7-697efc850419)

or even make its appearance bigger
![image](https://github.com/user-attachments/assets/d0f30870-dfbf-4f5f-95fa-968c65867e7c)

**Comment by Oskutin** [comment]
fixed
