### ISSUE TITLE
playtest Version 0.3.44 bug? - some npcs have been moved from sitting to standing

### ISSUE THREAD

**Issue by pinkamedic** [loiste-interactive/Obenseuer-Issues#3173]
im unsure if this is a bug or not, but it does seem strange with the vendors
![image](https://github.com/user-attachments/assets/e8976a07-a512-4588-b710-9ea54b8c7585)
![image](https://github.com/user-attachments/assets/2ea84b21-5334-4883-b002-27b00da4e111)
![image](https://github.com/user-attachments/assets/51b12063-1d00-4d5e-bbbb-8cb52f5eaaa8)
![image](https://github.com/user-attachments/assets/9c1fc24b-fe7f-4f5c-9514-31c9a8533e29)

**Comment by pinkamedic** [comment]
gamebreaking
![image](https://github.com/user-attachments/assets/f98777b6-1710-4b41-ada6-2a20f8f6e1ec)

**Comment by Oskutin** [comment]
Fixed
