### ISSUE TITLE
Playtesting (0.3.44 v.) - Tenement mines roof is to low 

### ISSUE THREAD

**Issue by ProfRadis** [loiste-interactive/Obenseuer-Issues#3174]

**Comment by ProfRadis** [comment]
![20241220195225_1](https://github.com/user-attachments/assets/80b7ca03-e999-4ab7-aa08-12f21cabd794)
that you fall 1 floor

**Comment by TheJusa** [comment]
fixed, tenement is now accessible from the bottom of the stairs.
