### ISSUE TITLE
Playtesting .44 - all 'track change 4B' and the crash trigger in the Service Zone are still present

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#3175]
any other instances outside service zone seems to be fixed as far as I've seen

**Comment by Nextej** [comment]
[Player-prev.log](https://github.com/user-attachments/files/18214581/Player-prev.log)
[Mines_Update.zip](https://github.com/user-attachments/files/18214583/Mines_Update.zip)
(slot 4, it's the same save as in other related tickets)

**Comment by Oskutin** [comment]
Can you try with new save, so that there is no broken data from old save?

**Comment by Nextej** [comment]
still happens on a fully fresh save, you want the files for that too?

**Comment by Oskutin** [comment]
yes

**Comment by Nextej** [comment]
[Esko_Virtanen.zip](https://github.com/user-attachments/files/18215536/Esko_Virtanen.zip)
[Player.log](https://github.com/user-attachments/files/18215538/Player.log)

**Comment by Oskutin** [comment]
flippoint1 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

track recursive back wheel loop happened! Trackdir: Forward, entrydir: Forward. Trace: 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

flippoint1 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

track recursive front wheel loop happened! Trackdir: Forward. Trace: 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

flippoint1 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

track recursive front wheel loop happened! Trackdir: Backward. Trace: 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

flippoint1 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

**Comment by Oskutin** [comment]
And fuck, can't reproduce, other than that the X-switch is sitll acting weird...

**Comment by Oskutin** [comment]
Do things fuck up in the train test map?

**Comment by Nextej** [comment]
is there a specific spot where the direction is reversed? although, the wye next to the sauna works flawlessly

**Comment by Oskutin** [comment]
theres multiple points, but one specific one is the one at front of the gas station

**Comment by Oskutin** [comment]
Does that track work: 
![kuva](https://github.com/user-attachments/assets/09f60077-2082-4185-986c-4ede9bbbf9a0)

**Comment by Nextej** [comment]
yes, both ways

**Comment by Oskutin** [comment]
This is getting weirder then

**Comment by Nextej** [comment]
the one behind station fully works (have no idea how to get the train onto the one infront)
![image](https://github.com/user-attachments/assets/2885fffa-90cf-408f-983e-ebd24ed62f73)

**Comment by Oskutin** [comment]
![kuva](https://github.com/user-attachments/assets/477cbdf8-98ee-462d-8f42-ddd5005806ff)
what about that track with those stripes?

**Comment by Nextej** [comment]
the hazard ones going through the station? works all fine both direction all the way

**Comment by Nextej** [comment]
the one infront kills the train completely in that spot (no freaking out like on the main map, just halts to stop entirely, cannot be operated anymore)
![image](https://github.com/user-attachments/assets/b36a6677-615f-4b2a-aa88-92d35f7e3776)

**Comment by Nextej** [comment]
![image](https://github.com/user-attachments/assets/7aa5cbcc-425c-488e-abb8-0fadfe29e843)

**Comment by Oskutin** [comment]
Umm, that also works for me

**Comment by Oskutin** [comment]
Altough did you reverse there?

**Comment by Nextej** [comment]
"reverse" in what sense?

**Comment by Oskutin** [comment]
![kuva](https://github.com/user-attachments/assets/112790a5-3b8d-42cd-9217-6153c73d1fe7)

**Comment by Nextej** [comment]
checked both sides, either way the train gets struck
[Player.log](https://github.com/user-attachments/files/18215876/Player.log)

**Comment by Oskutin** [comment]
you can also give me save of that

**Comment by Nextej** [comment]
[Esko_Virtanen.zip](https://github.com/user-attachments/files/18215911/Esko_Virtanen.zip)

**Comment by Oskutin** [comment]
works for me. I get dead of terminal velocity as the train launches with max speed from there :D

**Comment by Oskutin** [comment]
managed to reproduce it in build, now to figure out why unity decides to do things differently on it....

**Comment by Oskutin** [comment]
Hmm, the failure track was missing one setting. Building the game to see if applying that fixes it

**Comment by Oskutin** [comment]
didn't fix in build :(

**Comment by Oskutin** [comment]
Or wait, looks like it startup up the steam version...

**Comment by Oskutin** [comment]
Oh hey, it fixed it (but still fucked in your save)
