### ISSUE TITLE
Playtesting - issues with decoupling long trains that have flatbed carts

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#3178]
When a train has multiple flatbed carts in it, decoupling some of them doesn't really decouple them, sometimes even out of order, keeping them parented to the locomotive

besides infuriating wasted time on trying to separate the wagons, it also leads to the wagons to phase through one to another 
![image](https://github.com/user-attachments/assets/222b47db-6054-44b3-baee-ff20b8dd98b3)

it's an issue hard to explain, so it has an attached save 4 which has the middle locomotive detached from the chest-wagon, but still somehow attached to the crate-wagon
[Mines_Update.zip](https://github.com/user-attachments/files/18214397/Mines_Update.zip)
[Player.log](https://github.com/user-attachments/files/18214399/Player.log)

**Comment by Oskutin** [comment]
Just happens with flatbeds?

**Comment by Nextej** [comment]
I think the same issue would happen with passanger carts and fuel caskets, tippers are safe

**Comment by Oskutin** [comment]
Okay, so the coupler positions are likely inverted on those. Front-coupler is actually back-coupler and vice versa.

**Comment by Oskutin** [comment]
Actually it's save related

**Comment by Oskutin** [comment]
Altough i can't reproduce this issue, other than that after loading a save it requires to decouple from both couplers.

**Comment by Oskutin** [comment]
Fixed (but it doesn't apply to old saves, as part of the bug was in the saving process)
