### ISSUE TITLE
[Playtesting] Jail is still broken

### ISSUE THREAD

**Issue by MissCassidy06** [loiste-interactive/Obenseuer-Issues#3183]
The jail is still broken, although this time instead of being released instantly, you instead get arrested for leaving your cell (after being told you are free to go) or even pushing the buzzer.
Enclosed is a save where you will get arrested for leaving the cell after being told that you were free to go.
[Save for Github.zip](https://github.com/user-attachments/files/18215436/Save.for.Github.zip)

**Comment by Oskutin** [comment]
new or old save?

**Comment by MissCassidy06** [comment]
Old save.

**Comment by Oskutin** [comment]
can you test again with new one.

**Comment by MissCassidy06** [comment]
Sure, but it'll take a moment.

**Comment by MissCassidy06** [comment]
I seem to be unable to recreate the bug on a new save.

**Comment by MissCassidy06** [comment]
Just in: Apparently in my old save, where I encoutnered this bug, the polcie are no longer looking for me (I didn't have the option to turn myself in).
