### ISSUE TITLE
[Playtest] - When loading a save in the mines after migrating a save Erikson's dialogue triggers around that saved area only.

### ISSUE THREAD

**Issue by berryberrynaisu** [loiste-interactive/Obenseuer-Issues#3184]
![image](https://github.com/user-attachments/assets/d27b3a9e-4924-40ae-894a-092afdb8a016)

This save is from when I walked out of the canteen. Whenever I  walk around or near this area his dialogue plays but not when I get close to him.

**Comment by berryberrynaisu** [comment]
When approaching him in person he makes sounds like he is speaking but no subtitles appear.

**Comment by Oskutin** [comment]
save file?

**Comment by berryberrynaisu** [comment]
I just saw this after reinstalling windows I am so sorry.

**Comment by Oskutin** [comment]
Well, got this myseld too

**Comment by Oskutin** [comment]
Fixed
