### ISSUE TITLE
playtest - disinfectant not being used when cleaning

### ISSUE THREAD

**Issue by pinkamedic** [loiste-interactive/Obenseuer-Issues#3187]

**Comment by Oskutin** [comment]
Save?

**Comment by pinkamedic** [comment]
would be the same one from the apartment examination issue

**Comment by pinkamedic** [comment]
https://github.com/loiste-interactive/Obenseuer-Issues/issues/3189#issuecomment-2557906796

**Comment by lSwitchbladel** [comment]
just to add to this, it only happen with stolen disinfectant, non stolen had its uses reduce as per usual at least for me, new save

**Comment by Oskutin** [comment]
fixed
