### ISSUE TITLE
Joran of "The Pickaxe Motel" will not rent a room even after using up all nights.

### ISSUE THREAD

**Issue by berryberrynaisu** [loiste-interactive/Obenseuer-Issues#3188]
![image](https://github.com/user-attachments/assets/a0aa984c-dceb-4a28-858a-dbded1111211)
![image](https://github.com/user-attachments/assets/943277d3-a386-469b-a869-9191ef0f79ae)
![image](https://github.com/user-attachments/assets/79bc88af-f02d-410f-8fe6-e821df718584)
![image](https://github.com/user-attachments/assets/a868a53a-6c33-42ec-8ff5-39386ba757b1)

**Comment by Oskutin** [comment]
Old save?

**Comment by berryberrynaisu** [comment]
old save

**Comment by Oskutin** [comment]
can you test with new one

**Comment by berryberrynaisu** [comment]
Was a problem with the old save couldnt replicate.
