### ISSUE TITLE
Playtest, bug report. Mine stairs

### ISSUE THREAD

**Issue by Stony1776** [loiste-interactive/Obenseuer-Issues#3190]
The stairs that connect the basement to the mine are not fully real. several sections of it are just visual and you will fall through it, this includes the top, and the bottom, but most of the middle is solid. You can also get into the mines through the basement, but not get back into the basement through that same door.

**Comment by Oskutin** [comment]
What level? Fine? Decent?

**Comment by Stony1776** [comment]
3 and 4.

**Comment by Oskutin** [comment]
Fixed
