### ISSUE TITLE
playtest - guard and Lönkkäs schedule is broken

### ISSUE THREAD

**Issue by pinkamedic** [loiste-interactive/Obenseuer-Issues#3193]
the guard never sleeps and Lönkkäs only sometimes works (from what i can tell hes always inside of his home when you inside no matter the time of if hes at another area)

**Comment by Oskutin** [comment]
Related:
https://github.com/loiste-interactive/Obenseuer-Issues/issues/1661
https://github.com/loiste-interactive/Obenseuer-Issues/issues/1458

**Comment by Oskutin** [comment]
fixed guard

**Comment by Oskutin** [comment]
restored lönkkä schedule
