### ISSUE TITLE
Playtest - Won't stop offering me a job

### ISSUE THREAD

**Issue by Chippperz** [loiste-interactive/Obenseuer-Issues#3194]
When I entered the mines I didn't accept the job from Antero Erikson immediately and he'd keep repeating his dialogue every so often, and always when I reentered the main mine interior.

[Player.log](https://github.com/user-attachments/files/18217760/Player.log)
[Slot5.zip](https://github.com/user-attachments/files/18217761/Slot5.zip)

**Comment by Orphiex** [comment]
I did accept the job, but I also keep getting the same message every time I enter the mines. No matter how far away from Antero Erikson I happen to be.
