### ISSUE TITLE
Greeting the VOID again

### ISSUE THREAD

**Issue by Orphiex** [loiste-interactive/Obenseuer-Issues#3196]
In 0.343 V2, Tritiumisotope reported Issue #3073 - when building the Makeshift Mine upgrade, the completed version failed to load and all that was left was a void. I tried building the Makeshift Mine upgrade in that version; the map loaded for me, but I was experiencing Issue #3047, so I loaded a fresh save from before building the upgrade and did other stuff while I was waiting.

When the 0.344 update dropped, I built the Makeshift Mine upgrade from scratch - opening the tunnel, commissioning the upgrade, and making final payment.

Now I'M the one greeting the void.

![20241221170555_1](https://github.com/user-attachments/assets/05aeffa8-2579-43a2-bc05-28588d5a7dbc)

The map elements are theoretically loading; the ladder is functional and can get me straight to the basement in this version, as long as I noclip my way over to the landing point.

![20241221172322_1](https://github.com/user-attachments/assets/029ccc98-f3bd-41b7-b414-cf036aaaa06a)

Unfortunately, this also means that if I use the basement door to go down to the Mines, I experience almost immediate Death by Fall. I can catch myself with more noclipping if I'm fast enough, but...

Here's the console logs when entering into the mines from the basement.

![20241221172444_1](https://github.com/user-attachments/assets/f863a3cd-1b56-4e7b-9313-202ecd2d9ed3)

**Comment by Oskutin** [comment]
based on the previous playtesting version save?

**Comment by Oskutin** [comment]
could also give the save

**Comment by Orphiex** [comment]
> could also give the save

My bad, attaching save file here

[Slot10.zip](https://github.com/user-attachments/files/18229386/Slot10.zip)

**Comment by Zuntti** [comment]
Seems to been fixed already
