### ISSUE TITLE
Anna & Laura are now dead-ends for the Hietala hunt

### ISSUE THREAD

**Issue by Orphiex** [loiste-interactive/Obenseuer-Issues#3197]
In the previous game build, talking to Anna Markkanen about her blond hair before completing the Disappearance of Alice broke the quest chain (Issue #3045). I ran into this in 0.343 V2, so in preparation for the next version, I loaded an older save from before entering the new mines and completed the Disappearance of Alice quest chain, including the "Task Complete" when telling Fredrik about what happened.

Now, in 0.344, conversation with Anna Markkanen doesn't bring up the blond hair conversation topic at all.

![20241221173404_1](https://github.com/user-attachments/assets/eff08329-734b-448e-83af-05fa55156b50)

Laura Markkanen also has no conversation topics available, including her normal explanation about the sauna and the club that uses it, even though I've never spoken to her before in this save.

![20241221173741_1](https://github.com/user-attachments/assets/ffa8bdef-a808-4565-80ee-ab2cc5304a25)

Is there a new trigger for these conversation topics that I'm missing, or is this a bug?

Also, a suggestion: would it be easier to separate these interactions into a separate quest chain? Say, a task called "Hunting Hietala" that triggers when completing "The Disappearance of Alice" and uses the new quest flag as a marker rather than using any of the Disappearance flags.

**Comment by Zuntti** [comment]
Fredrik should have given you a new task. Can I get a save before Fredrik send you to the mines?

**Comment by Nextej** [comment]
[Mines_Update.zip](https://github.com/user-attachments/files/18230283/Mines_Update.zip)
I've had the task activated (slot 4 or 5), althought I don't remember whether it was given by Fredrik or whether it was given after talking to one of the miners.

regardless of the activated quest, when approacing Laura with a proper dialogue option, she does not give a response

**Comment by Zuntti** [comment]
Fixed
