### ISSUE TITLE
Playtesting - the first of Red Danger experiment instructions is out of order

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#3198]
instead of telling you to insert the shrooms to the extractor, it says "what are you doing"

**Comment by Oskutin** [comment]
Does this happen any more (if it does, provide a save)?

**Comment by Nextej** [comment]
still happens
![image](https://github.com/user-attachments/assets/40553721-d2a8-4dd6-a58d-bd69f22c31b2)

**Comment by Nextej** [comment]
uh, it doesn't happen on entirely new save, but needs checking if it happens on migrated saves from public

**Comment by Nextej** [comment]
I think it's fine
