### ISSUE TITLE
Loading autosave causes player to get stuck on the toilet

### ISSUE THREAD

**Issue by gehube** [loiste-interactive/Obenseuer-Issues#32]
sitting on it and standing back up causes the player to ricochet out of bounds

**Comment by gehube** [comment]
https://user-images.githubusercontent.com/130682887/232024639-6288fccf-3704-4f2a-b823-6e76f05570f0.mp4

also weird lighting glitch in the video

**Comment by Zuntti** [comment]
Fixed
