### ISSUE TITLE
Playtesting - Pia: choosing either of the two top options, when looped back to the choice again, won't ever display the third option

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#3200]
![image](https://github.com/user-attachments/assets/b3da8632-220f-4b29-99ef-a9529a45c37a)
![image](https://github.com/user-attachments/assets/eb4a36c1-dbbc-4b76-9322-77a7dca1399d)
![image](https://github.com/user-attachments/assets/2d288923-e857-4dc6-b9e2-3f8df6b2b58d)

**Comment by Zuntti** [comment]
Fixed
