### ISSUE TITLE
Playtesting - after completing the fredrik's experiment, reloading the level causes the dialogue to reapper

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#3202]
![image](https://github.com/user-attachments/assets/f343398d-805a-41b1-99ad-9fb28fc75f93)
not sure if was fixed by #3184

**Comment by Nextej** [comment]
same after meeting eskola
![image](https://github.com/user-attachments/assets/43eb4360-203b-44bd-9761-bafac81f4a16)

**Comment by Oskutin** [comment]
Already fixed
