### ISSUE TITLE
[Playtesting] All sink furniture contains items despite being empty

### ISSUE THREAD

**Issue by l-HealthAngel-l** [loiste-interactive/Obenseuer-Issues#3210]
When you purchase any sink furniture (Makeshift Barrel Sink, Makeshift IBC Sink or Commercial Kitchen Table with Sink) is empty by default and when you place in tenement and pick up again it says that contains items, place again and there is no any items or fluids poured in tanks.

**Comment by Zuntti** [comment]
Fixed
