### ISSUE TITLE
[Playertesting] Unable place Copper Moonshine Still

### ISSUE THREAD

**Issue by l-HealthAngel-l** [loiste-interactive/Obenseuer-Issues#3215]
Registers as being inside an object either on floor or table.
![20241221181003_1](https://github.com/user-attachments/assets/d762b9bb-27c8-4113-92a1-7f0cfe0fa4ed)
![20241221181138_1](https://github.com/user-attachments/assets/15589a2d-b1c2-47a5-a7f6-971775d38a39)

**Comment by Stony1776** [comment]
Known and already fixed.

**Comment by l-HealthAngel-l** [comment]
> Known and already fixed.

If that fix is that I need make whole still on desk near falling edge, it is still bizarre to have expensive still on edge of the desk.

**Comment by Stony1776** [comment]
Fixed, not in current version.
