### ISSUE TITLE
(Unlock) action perhaps should be highlighted in another color to indicate a new available interaction

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#322]
As opposed to (Locked) Red and (Open) Gray, (Unlock) should also be highlighted uniquely to indicate to the player more clearer the doors are now to be unlocked, so it's more distinct from standard (Open) action
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/3fb81e93-6528-4467-a771-af03a3462a7d)

**Comment by Zuntti** [comment]
Added
