### ISSUE TITLE
[Playtesting] Leather Scrap and Rag Rugs using Old Rug icon

### ISSUE THREAD

**Issue by l-HealthAngel-l** [loiste-interactive/Obenseuer-Issues#3221]
![20241221213524_1](https://github.com/user-attachments/assets/6a92ebde-e780-47a7-897f-20ef519f0a6e)
![20241221212324_1](https://github.com/user-attachments/assets/591c93fc-4c66-4b07-91a8-5dd307cb0110)

**Comment by Zuntti** [comment]
Fixed
