### ISSUE TITLE
Canteen hole

### ISSUE THREAD

**Issue by SolidRz** [loiste-interactive/Obenseuer-Issues#3222]
There's a hole in the canteen behind where Veiko is sitting, I don't know whether the hole is for the outside (which it doesn't look like because can see the floor boards on the other side), or if it's a rat hole. Decided to report it because on the other side the hole isn't visible if it should be.

Version 0.3.44
![image](https://github.com/user-attachments/assets/a0a014d6-fd29-4c3d-9607-4e127e9b42de)

**Comment by Oskutin** [comment]
intentional, thats where the rats live
