### ISSUE TITLE
Playtesting Bug report. Can't report bodies. (Pia quests)

### ISSUE THREAD

**Issue by Stony1776** [loiste-interactive/Obenseuer-Issues#3224]
I am unsure if it's intended, but I can't report the murdered bodies aside from Pia herself.

**Comment by Zuntti** [comment]
Can I get a save where this happens?

**Comment by Stony1776** [comment]
[Dick_Fuck.zip](https://github.com/user-attachments/files/18231542/Dick_Fuck.zip)
Here you go.

**Comment by TonyFromRomania** [comment]
buddy what is with that folder naming

**Comment by Stony1776** [comment]
My character's name.

**Comment by Zuntti** [comment]
Fixed
