### ISSUE TITLE
>Multigrain dough recipe gives out 2 rye doughs

### ISSUE THREAD

**Issue by Leichensack84** [loiste-interactive/Obenseuer-Issues#3229]
![dough](https://github.com/user-attachments/assets/c4e0989b-d918-43c1-a24c-fb2ab2cb050e)

**Comment by Oskutin** [comment]
fixed

**Comment by Nextej** [comment]
@Oskutin isn't that intentional since you're giving 2 times the ingredients?

**Comment by Leichensack84** [comment]
Its not because of the amount. Its the kind of dough u get.

**Comment by Oskutin** [comment]
> @Oskutin isn't that intentional since you're giving 2 times the ingredients?

Amount is intentional because it requires 2x flour
