### ISSUE TITLE
[Playtesting] Smooth Wooden and Half variant Pillars doesn't have object snap option 

### ISSUE THREAD

**Issue by l-HealthAngel-l** [loiste-interactive/Obenseuer-Issues#3230]
By placing one of the variants of smooth wooden pillars ( Full or Half ), doesn't give option for second pillar to snap on the pillar, despite the fact simple Wooden Pillars have this option.

Smooth Wooden Pillars:
![20241222095254_1](https://github.com/user-attachments/assets/98975d22-190c-498a-a29a-a0ca8033c5e9)

Standard Wooden Pillars with snapping:
![20241222095332_1](https://github.com/user-attachments/assets/d5ea059d-5ead-475e-a9e3-f7d1a8632d98)

**Comment by Zuntti** [comment]
Fixed
