### ISSUE TITLE
Playtesting - IC Magazine has ARG Magazine recipe types instead of having engineering-related ones

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#3232]
![image](https://github.com/user-attachments/assets/02e2b176-55b5-4078-815d-4896d91e0d7d)

**Comment by Nextej** [comment]
Also OS Magazine still has Sludgetank recipes for whatever reason, despite there no longer existing any recipes in that category
![image](https://github.com/user-attachments/assets/50850bfd-6ce4-47d7-b656-1534b8e38017)

**Comment by Oskutin** [comment]
Fixed
