### ISSUE TITLE
Playtest - Even in the new playtest the tier 1 mine access does not appear when built

### ISSUE THREAD

**Issue by Chippperz** [loiste-interactive/Obenseuer-Issues#3234]
My save file is one that has been imported from the pre-playtest build. The attached save file I 
believe is from before I paid to finish the upgrade.
[Player.log](https://github.com/user-attachments/files/18221879/Player.log)
[Slot5.zip](https://github.com/user-attachments/files/18221884/Slot5.zip)
[Player-prev.log](https://github.com/user-attachments/files/18221902/Player-prev.log)

**Comment by Zuntti** [comment]
Seems to be fixed already
