### ISSUE TITLE
Q-Market: items lack any clear indication on how much they actually cost before we go to the checkout

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#324]
Items are only shown with estimated value (of 5 in the case of sugar), but the actual price here is 8.
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/0442bb0c-e38d-4247-a6e9-86d734db778a)
all the items should have a price highlight the same way as it is shown in the General Store (but just informational here)
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/c4daaacb-8d2c-4042-ac8d-3bd9f25b32c2)

**Comment by Nextej** [comment]
I think it's crucial, watching some videos of other people playing, players get confused when the "estimated value" next to the description doesn't match the actual prices in O-Market.

**Comment by Zuntti** [comment]
I think it's broken in build or does it show the price here?
![price](https://github.com/loiste-interactive/Obenseuer-Issues/assets/5405170/48a42e2c-8d2f-4fd3-99ea-be2398ad5579)

**Comment by Nextej** [comment]
Oh, yes it does, would be also better however if it also did here 
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/8b242395-641b-4c66-a561-7d385dcbfa24)

**Comment by Zuntti** [comment]
Changed
