### ISSUE TITLE
Playtesting - Tier 2 mine depo does not have any collisions with placed furniture

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#3243]
![image](https://github.com/user-attachments/assets/694305d7-04c9-42c5-bb99-0fc466cd39ea)

**Comment by ProfRadis** [comment]
same a little bit https://github.com/loiste-interactive/Obenseuer-Issues/issues/3068
the main point but i didn't have pics

**Comment by Oskutin** [comment]
Fixed
