### ISSUE TITLE
Playtesting - Contract work finishing bug

### ISSUE THREAD

**Issue by Leichensack84** [loiste-interactive/Obenseuer-Issues#3247]
Scenario is the following: started workshop upgrade with Samuel while in stable branch. after switch to playtesting branch, already started contract work can't be finished neither by samuel nor that japanese guy in the mines. save file attached.
[playtestmines.zip](https://github.com/user-attachments/files/18223291/playtestmines.zip)

**Comment by TonyFromRomania** [comment]
yea that is a case of a huge diference in versions , and the renovations gone through many changes

**Comment by Zuntti** [comment]
Fixed
