### ISSUE TITLE
[Playtesting] Unable to craft Saline

### ISSUE THREAD

**Issue by l-HealthAngel-l** [loiste-interactive/Obenseuer-Issues#3250]
To craft saline, has modifier requirement "Clean". There is no such lab bench which has this modifier.
![Screenshot 2024-12-23 125434](https://github.com/user-attachments/assets/f9f17893-3c37-4625-8a39-851ad9528773)

**Comment by Nextej** [comment]
might be the issue of a slight rework of Fume cabin when it was split from the sink, I think it could've had clean modifier before

**Comment by Oskutin** [comment]
Fixed
