### ISSUE TITLE
[Playtesting] Dishwasher duplicating items

### ISSUE THREAD

**Issue by l-HealthAngel-l** [loiste-interactive/Obenseuer-Issues#3251]
Have seen similar problem and in official release, mostly happens when item has capacity like gas cans or uses like pills and other items. Currently I found the problem with this gas canisters, but I will comment bellow if I find more

https://github.com/user-attachments/assets/17537427-48e5-4751-87b3-412e8b462af0

**Comment by Oskutin** [comment]
fixed
