### ISSUE TITLE
Playtesting - Ore chutes don't fill up the wagons

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#3253]
the set up below despite triggering the animation, does not fill up the cart
![image](https://github.com/user-attachments/assets/0dfbd92a-a2bb-46b2-b469-7e904e2aad05)

**Comment by Oskutin** [comment]
save?

**Comment by Nextej** [comment]
use either of the autosaves or slot 7
[Mines_Update.zip](https://github.com/user-attachments/files/18234337/Mines_Update.zip)

**Comment by Oskutin** [comment]
Slot 7 was ancient

**Comment by Oskutin** [comment]
Fixed
