### ISSUE TITLE
OS mining services culling issue

### ISSUE THREAD

**Issue by SolidRz** [loiste-interactive/Obenseuer-Issues#3260]
Title
Band Saw, gas furnace, band saw, drill, electronics station, bucket, all of the lanterns, most chairs, the biohazard and editable signs, cardboard box, small wooden crate, red and white barrel. These are the current store items that I found that had glitched and/or missing images when looking at them in the NPC inventory. It happens even when you re-enter the trade window. Happens constantly even on save reload.

V 0.3.45
![image](https://github.com/user-attachments/assets/14a46b0a-fb8b-425a-909b-eb4f7d88fa54)
![image](https://github.com/user-attachments/assets/2ceab58a-691e-430a-9277-cf5a5dd80c51)
![image](https://github.com/user-attachments/assets/4fda9f85-c4d3-485c-942d-a951022ac55d)

**Comment by SolidRz** [comment]
Forgot to mention. Some of the items in the store will either be partially or fully visible for a few seconds while being displayed

**Comment by Oskutin** [comment]
Fixed
