### ISSUE TITLE
Eija's grill never restocks

### ISSUE THREAD

**Issue by efadfa3** [loiste-interactive/Obenseuer-Issues#3261]
I bought out all the non-mushroom stuff on like day 7 of the game.  It's been over a month and she still hasn't restocked.

**Comment by Nextej** [comment]
I think it might be an issue also occuring on all "vending machine"-like vendors, since they all use the same system

**Comment by Oskutin** [comment]
save?

**Comment by Oskutin** [comment]
Fixed
