### ISSUE TITLE
[Playtesting] Sleeping bag name and icon problems in inventory view

### ISSUE THREAD

**Issue by l-HealthAngel-l** [loiste-interactive/Obenseuer-Issues#3262]
In the inventory, where you can examine all recipes and blueprints, sleeping bag has same tittle problem two words not being separated and first letters capitalized, and now it doesn't contain any icon.
![20241224002121_1](https://github.com/user-attachments/assets/c56d3077-5954-4361-be9b-55a9895c43b3)

**Comment by Oskutin** [comment]
already fixed
