### ISSUE TITLE
playtest - cops give chase even at zero bounty

### ISSUE THREAD

**Issue by pinkamedic** [loiste-interactive/Obenseuer-Issues#3264]
cops seem to be sick of my shit and want me to rot in jail even if i havint done anything 
[Kyle_Pinkmin.zip](https://github.com/user-attachments/files/18234643/Kyle_Pinkmin.zip)

**Comment by Oskutin** [comment]
Stolen goods in inventory?

**Comment by pinkamedic** [comment]
in that save yes, but a few times i did not and they still gave chase nor have ive accumulated any bounty

**Comment by Oskutin** [comment]
i need a log file and save when that happens without any stolen items or bounty

**Comment by pinkamedic** [comment]
[Kyle_Pinkmin.zip](https://github.com/user-attachments/files/18234743/Kyle_Pinkmin.zip)
[Player.log](https://github.com/user-attachments/files/18234744/Player.log)
Slot 2

**Comment by Oskutin** [comment]
did the police chase you when you had stolen goods, then dumped those goods somewhere and returned to the map and the police started to chase you again?

**Comment by pinkamedic** [comment]
im starting to think thats the case, after doing more testing it seems like i just had stolen goods on me and didint know they chased you if you did
