### ISSUE TITLE
playtest - malone grew a second chair 

### ISSUE THREAD

**Issue by pinkamedic** [loiste-interactive/Obenseuer-Issues#3266]
![image](https://github.com/user-attachments/assets/b23e725e-2c2c-4f5e-acb4-548a725e46e8)

**Comment by Oskutin** [comment]
saveeeee

**Comment by pinkamedic** [comment]
[Kyle_Pinkmin.zip](https://github.com/user-attachments/files/18235245/Kyle_Pinkmin.zip)
slot 1/2 was before i found him like that slot 3 is right infront of him

**Comment by pinkamedic** [comment]
![image](https://github.com/user-attachments/assets/dff5d430-22f6-48a3-9e9a-d1313691637f)
 seems like the bug is that its spawning the bloody chair before the correct events

**Comment by Zuntti** [comment]
Fixed
