### ISSUE TITLE
[Playtesting][Feedback] Change max level skill flags into Flags category

### ISSUE THREAD

**Issue by l-HealthAngel-l** [loiste-interactive/Obenseuer-Issues#3267]
Currently max level skill flags are under Decorations category, I recommend to move them to the Flags category, since this category exists and it has only 3 furniture pieces (flags) under this category, this way no longer would need go through all decoration furniture pieces just to find hard earned flag.
![20241224120331_1](https://github.com/user-attachments/assets/820c8eb5-51b2-436e-9dcc-6290eaad2e51)

**Comment by TonyFromRomania** [comment]
i would also say have the small flag the player can find in the tenement in that category too

**Comment by l-HealthAngel-l** [comment]
> i would also say have the small flag the player can find in the tenement in that category too

It is already in flag category
![Screenshot 2024-12-24 125501](https://github.com/user-attachments/assets/b301df55-662e-47fa-83ea-ff286845c6e6)

**Comment by TonyFromRomania** [comment]
ah my bad

**Comment by Oskutin** [comment]
changed
