### ISSUE TITLE
Possible keypad UI bug (Tennement B for now, not tested on other keypards)

### ISSUE THREAD

**Issue by SolidRz** [loiste-interactive/Obenseuer-Issues#3269]
When inputting the code with the keyboard in Tennement B, the numbers 5,6,7,8,9 and 0 don't appear with a '*' on it. This could be a developer choice because you only need to input the correct code anyway, but 0 doesn't appear as well for some reason. Happens if you place the code manually or with keyboard.

Version 0.3.45

![image](https://github.com/user-attachments/assets/55de25f1-b16c-4b5d-b9be-2e14dc558223)

**Comment by l-HealthAngel-l** [comment]
Duplicate https://github.com/loiste-interactive/Obenseuer-Issues/issues/3038
