### ISSUE TITLE
Sleep events been triggered while using the TV to skip time 

### ISSUE THREAD

**Issue by TonyFromRomania** [loiste-interactive/Obenseuer-Issues#3270]
like the title says, sleep event are triggered when watching TV witch in the way is set it does not causes sleep to go down , so i proposed the sleep events while watching TV should ether be changed or made to not trigger at all

**Comment by Oskutin** [comment]
Did your character fall a sleep while watching tv?

**Comment by TonyFromRomania** [comment]
no the sleep meter was in the early stages of turning orange, the thing is i noticed this problem apearing  long before this version

**Comment by Oskutin** [comment]
fixed
