### ISSUE TITLE
the shop gui freeze wile the game is still playable

### ISSUE THREAD

**Issue by thygoose** [loiste-interactive/Obenseuer-Issues#3272]
https://github.com/user-attachments/assets/16515419-d9de-427b-99ea-3a8ad7892aae

**Comment by thygoose** [comment]
this is the worng clip

**Comment by thygoose** [comment]
Uploading Untitled video - Made with Clipchamp (19).mp4…

**Comment by thygoose** [comment]
https://github.com/user-attachments/assets/16515419-d9de-427b-99ea-3a8ad7892aae
this is the right one

**Comment by thygoose** [comment]
i think this might becuse i ues a low display and thats why no one else has incounted this bug

**Comment by thygoose** [comment]
it was not cused by the display is happons becuse of post px

**Comment by Oskutin** [comment]
Integrated GPU
