### ISSUE TITLE
Receipt Machine doesn't work

### ISSUE THREAD

**Issue by MarkusxD19** [loiste-interactive/Obenseuer-Issues#3273]
The Receipt machine at the drop off resets back to 0rm after you use it but doesnt give you your realmoney and receipt. 
![Receipt Machine](https://github.com/user-attachments/assets/9272bcdc-37bb-4544-814e-82fea8098096)

![receipt machine after](https://github.com/user-attachments/assets/54a54ff1-4c5e-4a12-81a8-7886946ed827)

**Comment by Oskutin** [comment]
got a savegame?

**Comment by MarkusxD19** [comment]
> got a savegame?

[Marki_Neulo.zip](https://github.com/user-attachments/files/18245358/Marki_Neulo.zip)

**Comment by Oskutin** [comment]
Fixed
