### ISSUE TITLE
[PLAY TESTING!!| my cat cannot kill rats

### ISSUE THREAD

**Issue by thygoose** [loiste-interactive/Obenseuer-Issues#3276]
these rats are the ones in the cafe in the mimes

https://github.com/user-attachments/assets/768704d8-ee6d-4924-865f-43724edf2249

**Comment by l-HealthAngel-l** [comment]
I think the rats are specially scripted for the quest

**Comment by thygoose** [comment]
aw so im not aloud to sit back and relax wile my cat does the work

**Comment by Oskutin** [comment]
need your save

**Comment by thygoose** [comment]
[Oskar_Schulz.zip](https://github.com/user-attachments/files/18274806/Oskar_Schulz.zip)

**Comment by Oskutin** [comment]
works for me

**Comment by Oskutin** [comment]
Seems to be fixed

**Comment by l-HealthAngel-l** [comment]
Maybe it was bench collisions

**Comment by thygoose** [comment]
ah

ok
