### ISSUE TITLE
Basement accessible from mines while being upgraded.

### ISSUE THREAD

**Issue by Tritiumisotope** [loiste-interactive/Obenseuer-Issues#3277]
![image](https://github.com/user-attachments/assets/2e24daef-a172-439d-a36c-36c3b6865d45)
![image](https://github.com/user-attachments/assets/e8e0603a-ca15-44e4-94e1-07679ea1e551)
Really silly but you can use the mine entrance into the tenement to access the basement when you shouldn't be able to.

**Comment by Oskutin** [comment]
fixed
