### ISSUE TITLE
B2 Mines Gate 'No power'

### ISSUE THREAD

**Issue by SolidRz** [loiste-interactive/Obenseuer-Issues#3278]
Quest 'Glowstick trail' cannot be progressed further despite having completed requirements. B2 gate is locked and says it has no power so it is impossible to enter the code for it. No idea how the problem appeared. Reloading an earlier save or autosave didn't seem to fix the issue.

Version 0.3.45

![image](https://github.com/user-attachments/assets/093025c9-abc4-4396-86fc-e1de83491884)
![image](https://github.com/user-attachments/assets/4a304df7-52b9-490d-8857-21210b86970d)
![image](https://github.com/user-attachments/assets/373e5fec-c4ff-4c92-96c1-c1c29a075e5d)
![image](https://github.com/user-attachments/assets/17c20062-3473-440e-8a0f-91081baebf70)

**Comment by Oskutin** [comment]
Did you ask Heska to open it?

**Comment by SolidRz** [comment]
Yes. I have no more dialogue options with him. I went back and talked to Eliana to see if skipping parts of a quest could be what has caused it, but it's still locked.

![image](https://github.com/user-attachments/assets/52511f3c-defd-4cde-a5da-cf8197b1df66)

**Comment by Oskutin** [comment]
In that case need yout save file

**Comment by SolidRz** [comment]
Heres the latest save file

[Slot10.zip](https://github.com/user-attachments/files/18252880/Slot10.zip)

**Comment by Oskutin** [comment]
Hmm, did you save after heska allowed you to open the gate and then continue later?

**Comment by Oskutin** [comment]
Looks like the keypad doesn't retain it's powered state on saves.

**Comment by Oskutin** [comment]
In that case it should be fixed now (but doesn't apply to older saves)

**Comment by SolidRz** [comment]
This save was made 30 minutes after talking to Heska to open the gate

**Comment by Oskutin** [comment]
Fixed (but doesn't affect old saves)
