### ISSUE TITLE
Traders should prioritize providing crafting-used furniture over the decorative-only furniture

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#328]
Currently you rather have to have some luck to find any furniture used in crafting (Plastic Chair, Blue Plastic Barrels, Vegetable Crate, Gas Bottle, etc.), traders should provide such crafting furniture more often, or even, based on unlocked recipes, prioritize those that we can actually use. Jonasson currently seems to provide only built-ready machines, with a rather narrow amount of furniture to sell total, perhaps he specifically could get to sell more of those crafting-used furnitures.

**Comment by Oskutin** [comment]
Adjusted
