### ISSUE TITLE
playtest / feedback - you can make a ton of machining XP with a grinder and mousetraps

### ISSUE THREAD

**Issue by pinkamedic** [loiste-interactive/Obenseuer-Issues#3280]
withmouse traps only being made with 1 scrap and 1 junk wood it makes it a very simple craft and with how fast its made even at a grinder you can make them very fast, add onto the grinders high failrate you can make a ton of XP by making mousetraps, you also get the scrap back when it fails so you just need a bunch of junkwood

**Comment by Oskutin** [comment]
fixed
