### ISSUE TITLE
[Playtest] Scrap Metal from different containers not stacking

### ISSUE THREAD

**Issue by berryberrynaisu** [loiste-interactive/Obenseuer-Issues#3281]
While on a new save gathering cans and materials I noticed that these particular scrap pieces would not stack with each other. After some advice from the issues channel I was able to figure out that putting them in the tenement chest made them stackable again. I cannot provide a save from when they were unstackable as both autosaves were done after this happened but I will attach the latest one in hopes you can gleam something from it.
![image](https://github.com/user-attachments/assets/e6822bdc-3055-444c-b640-f6dd80144150)
I tried 3 separate new saves to replicate this the issue but I couldn't reproduce the same result.
[Slot2.zip](https://github.com/user-attachments/files/18256329/Slot2.zip)

**Comment by Oskutin** [comment]
Can't reproduce
