### ISSUE TITLE
Playtesting - when player exits the starting border control for the first time, they should see the bus already parked at the busstop

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#3285]

**Comment by Oskutin** [comment]
Player has waited the processing for hours, so the bus has already left a long time ago

**Comment by Nextej** [comment]
@Oskutin If it was hours of processing, then there are really high chances the bus would be at the busstop again, so it's not out of the question the coincidences would align there. I think it might be helpful to further establish the player, how did they arrived there, and so on, as it would give an immediate continuity
