### ISSUE TITLE
[Playtesting] Malone's Chair Typo

### ISSUE THREAD

**Issue by l-HealthAngel-l** [loiste-interactive/Obenseuer-Issues#3286]
Malone's chair is called "Malones's Plastic Chair", which suppose to be "Malone's Plastic Chair". Despite the fact description of this furniture piece is written correctly.

<details>
  <summary>Graphic Image Warning</summary>

![Snake Sounds](https://github.com/user-attachments/assets/e27f5fc3-03bf-40f0-b3e7-4a2487203f96)

</details>

**Comment by Oskutin** [comment]
fixed
