### ISSUE TITLE
[Playtesting] Liquid storage container categories

### ISSUE THREAD

**Issue by l-HealthAngel-l** [loiste-interactive/Obenseuer-Issues#3287]
Lately as community can recall that I am working on furniture pieces and all. One thing now kept me thinking... now all barrels (Blue plastic barrel, Red barrel and Rusty barrel) can store 250 L of liquid. These barrels are considered in Clutter category, BUT... IBC Container which stores 1000 L of liquid is categorized as Storage.

So does these barrels should be moved to Storage category?
![20241228022442_1](https://github.com/user-attachments/assets/153f6c0b-0a97-41fc-b61f-35dce4b0119d)

**Comment by Oskutin** [comment]
Added new category for liquid storages
