### ISSUE TITLE
post px can freeze players low end laptops/pc 

### ISSUE THREAD

**Issue by thygoose** [loiste-interactive/Obenseuer-Issues#3289]
it just freezes the screen but the game still plays
you can move and hear the sounds
but the screen will show what there was last
before this only happoned to the shops
but when i messed with the setings and turned up px it just does it without a shop menu

https://github.com/user-attachments/assets/6faf0efa-d7f2-4e5d-b21b-953254b55000

the video might be too fast i had to speed it up to post it onto github

**Comment by Oskutin** [comment]
Based on discord, this is running on integrated GPU, which is very very low tier and likely doesn't support many required features https://gpu.userbenchmark.com/SpeedTest/153579/IntelR-HD-Graphics-620
