### ISSUE TITLE
Playtesting - a tipper next to SNW elevator shaft has wrong spawning position

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#3290]
![image](https://github.com/user-attachments/assets/c3ed0f48-8bce-4d93-90e3-b5c535d2cc23)

**Comment by Nextej** [comment]
same applies to one of the boogies of the first casket wagon you find
![image](https://github.com/user-attachments/assets/f59f42fe-7080-476b-bd3c-5ae7673a6edc)

**Comment by Oskutin** [comment]
fixed
