### ISSUE TITLE
Apartment 4 going from tier 0 to tier 4 kitchen, the construction area has no collision [latest playtest 12/28/2024]

### ISSUE THREAD

**Issue by Tritiumisotope** [loiste-interactive/Obenseuer-Issues#3292]

**Comment by Oskutin** [comment]
fixed

**Comment by Tritiumisotope** [comment]
![image](https://github.com/user-attachments/assets/11a14cc5-9dad-4198-9636-40c656f23041)
![image](https://github.com/user-attachments/assets/f1f5e8b3-d8b7-4caa-998d-f3fe6ad79913)

**Comment by Tritiumisotope** [comment]
oh ok sorry
