### ISSUE TITLE
Playtesting - On this animated model in Monitoring room, 3 out of 4 gauges do not have pixelized texture at all

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#3296]
![image](https://github.com/user-attachments/assets/47287e46-363e-4622-b789-c7cecd04ba04)
![image](https://github.com/user-attachments/assets/e61b46c2-6bd2-4bc0-b2b1-9cd5316a698a)

**Comment by Oskutin** [comment]
fixed
