### ISSUE TITLE
Swimming in the Lake cave doesnt work

### ISSUE THREAD

**Issue by TonyFromRomania** [loiste-interactive/Obenseuer-Issues#3299]
[Slot3.zip](https://github.com/user-attachments/files/18276245/Slot3.zip)

 _**also pls check the tenement tunnel bug if you at, thank you**_ 
![20241228123632_1](https://github.com/user-attachments/assets/16118d53-e14f-497a-bf68-7bf4e0f88604)
![20241228123636_1](https://github.com/user-attachments/assets/0bb0923a-6cda-4596-a88c-782efa40cc0a)

**Comment by efadfa3** [comment]
I'm experiencing this issue as well, here's my save. 
[Slot4.zip](https://github.com/user-attachments/files/18276317/Slot4.zip)

**Comment by Oskutin** [comment]
Hmm, works for me in the saves

**Comment by TonyFromRomania** [comment]
weird...

**Comment by Zuntti** [comment]
Fixed
