### ISSUE TITLE
Prepared steak is stuck in barrel stove

### ISSUE THREAD

**Issue by oleg-v-ladygin** [loiste-interactive/Obenseuer-Issues#3300]
I have walked away from barrel stove (a shared one on Market Square) while my meal was being prepared, and returned later.
Now i see the steak in "Process 100%", but i cannot do anything with it, can't take it, can't move it into main 3x3 area of the stove - nothing. And I cannot cook on this barrel anymore - it says "Crafting Full 1/1". Save/reload or in-game sleep does not help - the meal is still stuck.
Is it possible to clean it, to remove this meal?
Photos attached.

(I remember i once have seen something like a frying pan on the top of the barrel with some meat on it, about the same time when this bug happens. But is's probably unrelated.)

![2024-12-30_21-50-57](https://github.com/user-attachments/assets/e29b9096-9699-4189-983f-c88a0ff10965)
![2024-12-30_21-50-28](https://github.com/user-attachments/assets/3821f6c0-ba59-443a-b03b-0a3f1c4ba559)
![2024-12-30_21-49-29](https://github.com/user-attachments/assets/f988fee4-d92f-49f4-9132-99c03fb31194)

**Comment by Oskutin** [comment]
This is fixed in the upcoming version

**Comment by oleg-v-ladygin** [comment]
Thank you very much!
