### ISSUE TITLE
[Bug]/[Suggestion] Dumpster you can steal from

### ISSUE THREAD

**Issue by SolidRz** [loiste-interactive/Obenseuer-Issues#3302]
Most of the dumpsters in Obenseuer can be opened and you don't get any burglary of thievery points from it, but I noticed that this dumpster on the way to the Sauna Club had the 'Steal' prompt under it. Was wondering if it was left intentionally?

Randomly found
Version 0.3.45

![Dumpster](https://github.com/user-attachments/assets/e26f9ae0-6884-475a-961e-1a4211f6997b)

**Comment by Oskutin** [comment]
This one is intentional as it actually has a valuable trash
