### ISSUE TITLE
[Playtesting] Bathroom Cup and Glass dismantling result balance

### ISSUE THREAD

**Issue by l-HealthAngel-l** [loiste-interactive/Obenseuer-Issues#3303]
By checking Bathroom Cup and Glass dismantle output items, appears Bathroom Glass gives 5x Plastic Trash, but Bathroom Cup gives 1x Plastic Trash.
![Maybe Extra Toothpaste](https://github.com/user-attachments/assets/3de9f460-6260-43e9-b747-ce8841711c16)

**Comment by Oskutin** [comment]
fixed
