### ISSUE TITLE
[Playtesting] Blue Plastic Barrel Sink on dismantle gives "zero" quantity of plastic barrels

### ISSUE THREAD

**Issue by l-HealthAngel-l** [loiste-interactive/Obenseuer-Issues#3304]
Dismantling Blue Plastic Barrel Sink gives "zero" quantity of plastic barrels, which later you need place gained barrel to refresh the quantity to "One".
![Screenshot 2024-12-31 120057](https://github.com/user-attachments/assets/ff766022-a920-40a5-836b-6d417f99eca0)

**Comment by Oskutin** [comment]
fixed
