### ISSUE TITLE
[Playtesting] Makeshift Barrel Sink crafting and dismantling

### ISSUE THREAD

**Issue by l-HealthAngel-l** [loiste-interactive/Obenseuer-Issues#3305]
Between crafting and dismantling the Makeshift Barrel Sink, is strange requirements or results.
- On dismantle you get full Pallet, but for crafting you need half pallet.
- For crafting needs two canisters, I understand that one is used for drainage collection but other one?
- For crafting needs two beer crates, again I got it that one is used as platform leg but other one?
![Full Pallet for Extra Canister](https://github.com/user-attachments/assets/dd945d1e-16ae-4df7-8d7c-8c3d4259e2a3)

**Comment by Oskutin** [comment]
fixed

**Comment by l-HealthAngel-l** [comment]
> fixed

I was about to mention, about Beer Crate requirement which requires blue variant specifically, maybe it could be any variant? Since with update we get other color variants (red and yellow).
