### ISSUE TITLE
[Playtesting][Suggestion] Makeshift Toilet dismantling

### ISSUE THREAD

**Issue by l-HealthAngel-l** [loiste-interactive/Obenseuer-Issues#3306]
By dismantling toilet you get various used crates and shopping basket as well some items. I suggest to add metal bucket as output furniture to the list as well.
![Screenshot 2024-12-31 124320](https://github.com/user-attachments/assets/c90c86ff-5003-462c-98f6-da3d84a8657e)

**Comment by Oskutin** [comment]
done
