### ISSUE TITLE
[0.3.46 Playtesting] Orange Mushroom Lantern crafting is imposible

### ISSUE THREAD

**Issue by l-HealthAngel-l** [loiste-interactive/Obenseuer-Issues#3319]
This blueprint you get from Orange trail quest if Malone is alive, but blueprint asks player use wrong Orange Mushrooms, since we only can have mushrooms in bag, this asks "Planted" ones.
![Screenshot 2025-01-01 003504](https://github.com/user-attachments/assets/450593a1-91d2-4db3-8147-bf6496f388ac)

**Comment by Oskutin** [comment]
fixed
