### ISSUE TITLE
O-Market bottle recycle still buggy

### ISSUE THREAD

**Issue by gehube** [loiste-interactive/Obenseuer-Issues#332]
https://github.com/loiste-interactive/Obenseuer-Issues/assets/130682887/37fa9b67-fd9c-4bb1-b552-e0e4e60e01bb

When putting bottles individually, the entire stack disappears. Sometimes putting a stack in only gives you the money for one of the bottles.
Bottle respawning still seems to happen.

**Comment by Oskutin** [comment]
Itemdata / PutItem system in general seems to be broken.

**Comment by Oskutin** [comment]
Fixed
