### ISSUE TITLE
Sometimes during in the interview room, when the Inventory Tab tutorial pops up, the game tells us to press "I", instead of the binded key

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#340]
Additionally the binded key doesn't work and the "I" is the only one that does, after doing so, the binded key continuous to work properly.

**Comment by Nextej** [comment]
Seems to happen always, for a time being of the intro level, the inventory key is rebinded to I, exiting the level or pressing ESC makes the actual binded key to start to work properly.

**Comment by Zuntti** [comment]
Fixed
