### ISSUE TITLE
Planted plants disappear after loading a save in tenement

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#341]
1. Minor, visually the plants keep changing their positions between the slots, they don't match the UI slots position and with each reload they are different. UI slots remain always the same.
2. With reload, plants tend to disappear, it seems as if the farm doesn't allow more plants than it has slots to, for instance, Bag of Soil always keep 3 plants maximum, while it has 6 slots, having various plants mixed, it seems to be chosen at random, which of the plants to remove.
[Player.log](https://github.com/loiste-interactive/Obenseuer-Issues/files/11938146/Player.log)

**Comment by Oskutin** [comment]
I assume this is the custom placed ones?

**Comment by Nextej** [comment]
Yes, they are, but I haven't tested the large 3-slot one nor the ones found in the world

**Comment by Oskutin** [comment]
Ah, this seems to be issue only with furniture growing boxed.
What i discovered:

1. Sometimes growth stage resets to zero on reload.
2. Had 4 different growing boxes, but upon reload all of them loaded the state of one of them

**Comment by Oskutin** [comment]
Partially fixed now

**Comment by Oskutin** [comment]
Fully fixed
