### ISSUE TITLE
When player is trying to put furniture in the apartment before clearing up the rubbish, perhaps an additional notification should be shown.

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#342]
New players might be confused as to why they can't immediately put their furniture in the apartment, not realizing the rubbish is what blocks it, so perhaps if an furniture we're trying to place is colliding with one of the "rubbish" objects, additional notification should appear like "Furniture is blocked by the rubbish, clear the apartment first" to make extra clear what's happening
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/3c76f6a2-3bbf-4142-8ecf-beb00c3e1f11)
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/6b4cd2bb-7bcb-4f30-9fdc-4dc5e519a31d)

**Comment by Zuntti** [comment]
Added message that explains why the furniture cannot be placed
