### ISSUE TITLE
empty cans in the recycling machine

### ISSUE THREAD

**Issue by Asireldreemurr213** [loiste-interactive/Obenseuer-Issues#343]
if you put empty food cans into the recycling machine it turns it into another item 
![Screenshot_27](https://github.com/loiste-interactive/Obenseuer-Issues/assets/138607022/350d5c99-87a5-412b-8999-c140f89f4060)
![Screenshot_28](https://github.com/loiste-interactive/Obenseuer-Issues/assets/138607022/cd8416bc-990b-4874-b7ba-ad722bc87a21)

**Comment by Oskutin** [comment]
This is already fixed

**Comment by Oskutin** [comment]
https://github.com/loiste-interactive/Obenseuer-Issues/issues/332
