### ISSUE TITLE
graphical glitch when looking out of building A apartment A2

### ISSUE THREAD

**Issue by Asireldreemurr213** [loiste-interactive/Obenseuer-Issues#344]
when looking out of the door of the apartment A2 the lighting breaks outside looking into the doctors office while inside of the apartment
![Screenshot_31](https://github.com/loiste-interactive/Obenseuer-Issues/assets/138607022/1b1a70f2-c3ad-4c1f-8b8d-ba13b6cef0e5)

**Comment by Oskutin** [comment]
Can you post comparision pic to normal?

**Comment by Asireldreemurr213** [comment]
![Screenshot_32](https://github.com/loiste-interactive/Obenseuer-Issues/assets/138607022/f466c9ce-d448-41f2-bc61-eb67cf100cf0)
here you go

**Comment by Oskutin** [comment]
Related to lighting, closing this as there has been lighting changes in that map, so this may not be relevant anymore
