### ISSUE TITLE
game crash when standing in doorway when door tries to close 

### ISSUE THREAD

**Issue by Asireldreemurr213** [loiste-interactive/Obenseuer-Issues#345]
when i was standing in the doorway takeing screenshots for another issue the game crashed twice when the door tried to close
[Crash_2023-07-06_195957080.zip](https://github.com/loiste-interactive/Obenseuer-Issues/files/11972002/Crash_2023-07-06_195957080.zip)
theres one of the crashlogs also its in apartment A2

**Comment by Oskutin** [comment]
#687
