### ISSUE TITLE
Buying more of the same furniture that we bought in another store is not possible

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#346]
Attempt to buy more of the furniture at General Store that some I've already bought at Hank Möbelmann's doesn't make the item purchased, but the money is still being drawn.

https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/4b25d938-77fa-4a10-88fd-396958983f95

Buying any other furniture that I didn't own beforehand from Hank's, works.

**Comment by Oskutin** [comment]
It's save issue, only starts to happen after save&load

**Comment by Oskutin** [comment]
Fixed
