### ISSUE TITLE
Building Menu should show machine modifiers, or at least show those that are environment dependent.

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#349]
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/16e99f92-545f-4586-925a-1c7cc65c99ab)
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/5aa65d73-527c-40f3-bbfc-39c0dea47c4c)
Currently it's mostly affecting the placement for the farms.

**Comment by Zuntti** [comment]
Added
