### ISSUE TITLE
Console commands

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#35]
"add_item" command doesn't work with items that IDs are over 30000 (probably over 32767 as it returns error of invalid int16 value).
![image](https://user-images.githubusercontent.com/44178400/232106288-9b8c43ab-c923-4e82-ace4-7e07b66f3c92.png)

"noclip" command in one very peculiar case of unknown conditions did not disable collisions with the world, nor player's affection by the gravity when the game is unpaused. At the same time if a console is brought up, player can freely use noclip properly and both above items are disabled, closing up the console causes them to enable again. (It also might be related to abuse "change_scene" command, happened to me twice but I couldn't replicate it either way to find a cause)

After using command "change_scene" command and incorrectly typing "Interior Deekula Tenement B" instead of "Interior Tenement Deekula B" while also being in "noclip" mode with the bugged state mentioned above the game crashed.
![image](https://user-images.githubusercontent.com/44178400/232103406-e0523314-dc15-4ca8-924f-b4eb7af9f5f1.png)
[Player.log](https://github.com/loiste-interactive/Obenseuer-Issues/files/11235060/Player.log)

Suggestion: Allow bringing back the previously used command(s) with an Up and Down arrow keys as seen in most console interfaces. Also a TAB usage for filling up the rest of the command and arguments of the command would be appreciated, especially for "change_scene" command.

**Comment by deseven** [comment]
Also the input field shouldn't lose the focus so you won't need to press on it every time you want to input another command.

**Comment by Nextej** [comment]
Command "player_stats tiredness set" changes thirst instead of tiredness, seems to work exactly as same as "player_stats thirst set".

**Comment by Oskutin** [comment]
'Próbowano uzyskać dostęp do nieprawidłowego adresu.'  What is this in english?

**Comment by Oskutin** [comment]
Console now remember old commands
