### ISSUE TITLE
Furniture like Large Wooden Wine Rack and Small Wooden Cupboard should be mountable on the wall, currently can be placed only on the ground.

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#352]
https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/29f3a9b2-4972-416c-ba62-1fc6b0551507

**Comment by Nextej** [comment]
Perhaps the game could detect whether we're aiming at a wall or at a floor and according change orientation of those furnitures, so it can be placed both on the floor and hanged on the wall.

**Comment by SaladSauce** [comment]
I should have built a chest
03.21 same issue
