### ISSUE TITLE
The way items are being sorted out in the Building Mode needs to be redone.

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#353]
Currently it's rather annoying that a recently removed item is being placed at the very end of the furniture list.

https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/3d7f34d1-c366-4c56-9cda-5c4ba18a733a

I'd propose either sorting it alphabetically (or category wise), so the order is always the same or have the recently removed/acquired placed in the front, always.

**Comment by Zuntti** [comment]
Added alphabetical sorting
