### ISSUE TITLE
Issues with save files

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#36]
When saving, the items held (equiped) in hand won't be save and upon loading back to that saveslot, they will be gone entirely. It surely applies to Sledgehammer, OSRAT and flashlights, if not all the items that can be equiped.

When having a character that's name is made out of none-letter characters (numbers and special symbols), the Load Game menu will always show the firstly created character (assuming we're having more than one) instead of the one we're playing currently, additionally the Save Game menu will show that all the saveslots for our character are empty, despite some of them being written.
![image](https://user-images.githubusercontent.com/44178400/232110446-db8b23c4-2f08-4f45-8191-98fc506c0535.png)
![image](https://user-images.githubusercontent.com/44178400/232110492-8e62ae5c-ee5a-4890-b410-751ad256ead9.png)

Also I'll just throw it here, you can create a character with name made out of none-letter characters.

**Comment by Zuntti** [comment]
Fixed
