### ISSUE TITLE
Upgrades inside player's apartment (and possibly other apartments) get stuck at 0 seconds left after paying the final payment

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#363]
Doing so makes the game state that the final payment still needs to be paid.

https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/7cc7853a-0518-4c93-86c6-795817264c60

**Comment by Nextej** [comment]
changing the maps made the upgrade task to appear multiple times
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/e5616890-0846-42f2-8869-09af2326b03f)

**Comment by Nextej** [comment]
Reloading the map caused the icons to change, yet they cannot be interacted

https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/4ff3a894-ab99-4bb0-81c6-65a6a75678b4

**Comment by Nextej** [comment]
[Player.log](https://github.com/loiste-interactive/Obenseuer-Issues/files/11991301/Player.log)

**Comment by Oskutin** [comment]
Did you pay the final payment to the contractor NPC?

**Comment by Oskutin** [comment]
I mean talking to the NPC itself?

**Comment by Nextej** [comment]
Either I'm missing something or there's no dialogue option for that, only to open the renovation menu by talking to him, which leads to the message above.

**Comment by Oskutin** [comment]
Ah
