### ISSUE TITLE
After trying out to make several tenement upgrades and unlocking basement, the game began to lag horribly whenever console is opened.

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#365]
[Player.log](https://github.com/loiste-interactive/Obenseuer-Issues/files/11991298/Player.log)

**Comment by Nextej** [comment]
Seems to be triggered by broken upgrade completion from #416 and applies to every map (tested Deekula B, Player's Tenement and Deekula Mine Entrance) to have a performance issues with console open.
[Player.log](https://github.com/loiste-interactive/Obenseuer-Issues/files/12267404/Player.log)

**Comment by Oskutin** [comment]
I think this is fixed or irrelevant due changes into the system
