### ISSUE TITLE
missing items in shop

### ISSUE THREAD

**Issue by Asireldreemurr213** [loiste-interactive/Obenseuer-Issues#366]
i have no idea what these are suppposed to be but here
![Screenshot_38](https://github.com/loiste-interactive/Obenseuer-Issues/assets/138607022/9ed0e351-2d3e-42d0-8da4-1f29be488476)

**Comment by Oskutin** [comment]
Didn't @nextej already report this?

**Comment by Oskutin** [comment]
Ah this was the "missing icons causes models to not render" -bug what has been fixed
