### ISSUE TITLE
Game crashes when leaving bathroom in hacker room; after loading autosave leaving the toilet makes me drift out of map

### ISSUE THREAD

**Issue by CarlieBendix** [loiste-interactive/Obenseuer-Issues#367]
Game crashes when leaving bathroom behind the Osrat room; after restarting and loading the last autosave, getting up from the toilet in the same bathroom makes me drift out of the map. Can't find the crashlog tho (sorry, new to this)

**Comment by Oskutin** [comment]
Fixed
