### ISSUE TITLE
Rats disappearing from Rat Cage upon closing the UI and/or reloading the level.

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#368]
Got two different cases of this issue
1. Started game normally, loaded few maps before reaching Deekula A and then putting rats into the cage and closing the UI made them disappear.
2. Relaunched the whole game and loaded the autosave (so I spawned in the Deekula A straight away) and the rats put into the cage disappeared only after reloading a savefile.

https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/731f8e21-30d6-4ee8-9cc6-97ea227d9ab7

Additionally, unlike the Aquarium, you don't really "plant" rats to grow, but rather the mere presence of rats over time makes more rats, the UI should be improved to and not mislead into "planting".

**Comment by Nextej** [comment]
Aquarium on the Deekula B map seems to work as intended without any problems, or at least couldn't reproduce the same effects as with the rat cage.

**Comment by Oskutin** [comment]
https://github.com/loiste-interactive/Obenseuer-Issues/issues/341 the issue seems to be somewhat same as this

**Comment by Oskutin** [comment]
Can't reproduce in editor, either it is fixed, or it only happens on build.

**Comment by Oskutin** [comment]
Ahaha, you opened the cage below in the video. And you can see the glow of the rats in the cage after you loaded the game.
