### ISSUE TITLE
Doors closing on distance detection

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#37]
The doors appear to work in a manner of a distance between the player and itself, causing it to close when player is beyond that defined distance, however player can position themself as such as they can interact with doors to open, yet still be far enough to cause them to close immediately. This alone is not hard to recreate by accident and may cause annoyance.

https://user-images.githubusercontent.com/44178400/232111690-d107b2af-749f-428d-8505-ae22f936daca.mp4

**Comment by Zuntti** [comment]
Fixed
