### ISSUE TITLE
Intro sequence: looped sentence and lighting issues

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#370]
The line "As researchers are still trying to find a cure." is repeated 4 times in the later part of the intro.

https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/68b38099-a271-424d-a59f-8f9d52cba643

The green lighting has hard edges inside the sewer pipe (4th scene with city panorama)
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/321c524e-ff7f-4143-b1f2-cc1e01af8fb3)

**Comment by Zuntti** [comment]
Fixed
