### ISSUE TITLE
Dropping a "stack of rats" and picking it up gives you back only one item.

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#371]
https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/fcd5fcaa-9d1b-4ab6-a3f0-65744ca4291c

**Comment by Oskutin** [comment]
Hmm, weird, as rats shouldn't be stackable in the first place

**Comment by Oskutin** [comment]
How you got it?

**Comment by Oskutin** [comment]
Seems that that map is missing navmesh as the rat stays on the spot

**Comment by Nextej** [comment]
Eh dammit, it could've been from console, I don't recall.
