### ISSUE TITLE
Deekula A large Rat Cage storage has a unintuitive visual design

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#374]
A structure made of several (seven!) rat cages, even of two different types, that's located in the attic of Deekula A is not very clear on the fact it is not a one large structure, but several separate cages.
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/e39f6f39-ce04-4ba5-97f9-26cb51a9310b)
A better distinction is needed, I'd propose first - adding a separate number label model to each cage (just in this location, not to the cage model itself) and/or placing something along the lines of high contrast, dark wood planes inbetween the cages, a sort of a shelf to make it clear where one cage ends and starts another. Even renaming the large variant to "Large Rat Cage" (instead of having small and large named the same) should slightly help.

**Comment by ontrigger** [comment]
+1
