### ISSUE TITLE
Tenement System: Furniture still disappears from save reloading, although this time it might be caused by Move function, haven't tested the Remove one yet.

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#377]
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/9a04ed67-1270-4292-9e85-add980fd2522)
[Player.zip](https://github.com/loiste-interactive/Obenseuer-Issues/files/12253798/Player.zip)

**Comment by Nextej** [comment]
Issue is happening for both Move and Take functions 
[Player.log](https://github.com/loiste-interactive/Obenseuer-Issues/files/12253927/Player.log)

**Comment by Zuntti** [comment]
Fixed
