### ISSUE TITLE
Issue #287 is not fixed, TVs still don't properly light up the room like they used to and don't show visual noise.

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#378]

**Comment by Nextej** [comment]
This is how it should look
https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/e795ac98-9c7d-4a30-acf1-da1e8931925c

This is how it looks at Priest's and Jacob's

https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/160391c3-85fe-41df-8256-040a30fc6ee1


https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/fad297d7-47cd-4c12-9db1-4e6f0c1e21dc

It seems like it sometimes work properly on a first try, but turning it off and on makes it break down, sometimes it is that way from the start.

**Comment by Zuntti** [comment]
This seems to be fixed in the current update
