### ISSUE TITLE
Vibrating/Tearing effect from player's perspective when moving sideways along the corridor in the intro waiting room

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#38]
As per spot in the video, the effect might not be observed well here because of the compression, but in this particular spot facing along the wall I've managed to get this, no other place in game behaves like this so far
https://user-images.githubusercontent.com/44178400/232141928-361dc7d5-aad8-407c-a427-8f72bc4f520f.mp4

**Comment by Nextej** [comment]
Tried to rerecord the issue, on the video it appears more as a lag or a jump-cut movement, so it's better to see for yourself, it also seems to occur not only when moving sideways, but also backwards; moving forward seemed fine.

https://user-images.githubusercontent.com/44178400/232316814-04deb809-0354-4471-a2ed-9bc5fa58271e.mp4

**Comment by Nextej** [comment]
Same happens in the Mine Entrance map in a lot of places, none to be found in Deekula B2 itself.

**Comment by Nextej** [comment]
Video showing an example of mines, however does not seem to be a Performance Issues as it was labeled, game runs smoothly, it seems to be an issue with camera itself.
https://user-images.githubusercontent.com/44178400/233662519-c85b1d72-4285-48bc-a831-8aa37e24face.mp4

**Comment by Oskutin** [comment]
Possibly related to: https://github.com/loiste-interactive/Obenseuer-Issues/issues/242

**Comment by Oskutin** [comment]
Merged all "jittering movement" stuffs together.
