### ISSUE TITLE
Spawned blueprints/recipes/mail tend to disappear after reloading. Not sure if with each reload, their chances to spawn are reset.

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#381]

**Comment by Nextej** [comment]
Same seems to apply to cooking recipes.

**Comment by Nextej** [comment]
Same applies to mail, after receiving a mail and reloading the map/save, the mail is gone.

**Comment by Nextej** [comment]
Also it seems that recipes still have chance to respawn if we visit the map freshly the other day, but blueprints never do respawn.

**Comment by Oskutin** [comment]
Mail is working now

**Comment by Zuntti** [comment]
Fixed
