### ISSUE TITLE
Wielded sledge hammer firstly disappeared, then after replacing it in a slot, was out of position.

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#387]
https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/0b7db1f5-1574-4609-9312-7bd6cfb8b698

[Player.log](https://github.com/loiste-interactive/Obenseuer-Issues/files/12255473/Player.log)

**Comment by Oskutin** [comment]
https://github.com/loiste-interactive/Obenseuer-Issues/issues/392 seems to explain it better
