### ISSUE TITLE
OSRAT beeping when not equipped in hand

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#39]
I assume it is not an intended behaviour as it seems to be misleading as to what this sound may indicate, or where to be coming from when a player is not having OSRAT in hand.
https://user-images.githubusercontent.com/44178400/232143949-6ceacb82-2fa2-4547-b9b8-110f938fb448.mp4

**Comment by Oskutin** [comment]
This may be intentional behaviour, unless the device is without batteries.

**Comment by Nextej** [comment]
The device was reloaded with batteries, if it's intended then it should have an additional visual indication, possibly in the inventory, to indicate the OSRAT is working. Because again, it might be very confusing for a player to hear beeping of some kind if they are not particularly looking for the spots to activate it.

**Comment by Zuntti** [comment]
Changed it to only work when it's in hand and visible
