### ISSUE TITLE
Mr. Duck's blue duck rescue task is not present on the list of tasks, despite not being finished yet. (is it even given in the first place?)

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#390]
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/ff53a0d6-2551-4238-bd1d-990587a28309)

**Comment by Nextej** [comment]
I just noticed the objective was added to the "Priest's Debt" task, instead of being its own thing.
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/173af2e3-78f9-493b-a708-5e514c41b839)

**Comment by Zuntti** [comment]
Fixed
