### ISSUE TITLE
Upon loading the savefile and equipping the hammer

### ISSUE THREAD

**Issue by TiaLinna** [loiste-interactive/Obenseuer-Issues#392]
![20230804101754_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/130680276/0cdf8a57-8f46-4c57-82ed-6ea27f82e7b4)
![20230804101758_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/130680276/fbca7966-b966-4125-8ac6-6df9b234aec0)
![20230804101800_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/130680276/1b2a57ee-6231-4df9-bf10-b60c8a3d3358)

This happens, unequipping it and re-equipping it fixes it, but just a heads up!

**Comment by Zuntti** [comment]
Fixed
