### ISSUE TITLE
Negative Alcohol need is still happening, likely on the course of getting rid of the addiction.

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#399]
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/6aa1b734-20a1-4246-9215-082f4320af72)
Additionally, if the case is getting rid of the addiction, then currently it is too easy to do so, and within one day you can be free of it (despite setting the alcohol addiction the most advanced in the introduction).

**Comment by Oskutin** [comment]
Halved addiction reduction rate

**Comment by Oskutin** [comment]
Can't reproduce this. Has this happened recently?

**Comment by Nextej** [comment]
Haven't tested.
