### ISSUE TITLE
Sitting and standing up takes too long between near-end of the animation and player getting back control

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#40]
As you can see in the video, there's a noticeable delay before the player can move the camera and is seemingly already standing or sitting, 1 or 2 seconds sooner seems like would've been better.
https://user-images.githubusercontent.com/44178400/232198889-1467f934-c2e8-4ac6-ad8f-4c799ac474de.mp4

**Comment by Oskutin** [comment]
Duplicate of #14
