### ISSUE TITLE
General Store cannot take more items to sell, likely because it's out of space and it doesn't seem to reset from day to day.

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#404]
https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/c98bdbac-2a8b-4e89-a85a-aa7d0d59fcfd

**Comment by Nextej** [comment]
Likely clicking "Sort" button caused the store to break down, upon second interaction.
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/7bae48cd-467d-422a-ae18-f73ee2a73c5b)

**Comment by Zuntti** [comment]
Fixed and added out of space message
