### ISSUE TITLE
Pentti gives 1 RM per every item that contains a mash, not per quantity of liquid, so for example 5L Bucket of Mash is worth the same as 0,5L Bottle of Mash.

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#406]
Additionally we're loosing the container and the whole process puts some doubt whether it's worth it, currently it is 35 OC + 10 OC worth of plastic bottles (assuming it should be 1RM per 0,5L) to produce the Mash once and sell it, which gives us 40 OC from the old 1:4 ratio, if we use glass bottles, then it's 35 OC + 34 OC worth of glass bottles, which delivered in 17 bottles, gives us 68 OC, we're still loosing.
Also on the contrary, in the current version it's not a good way of making OCs since all you're getting are RMs and OCs are more important on the early stages.

So assuming the selling process will not be consuming our containers and there will be a constant value per Liters, I think it should be about at least double the amount we need to spend on production (perhaps 1,5x but no less), so we're still left with some profit, with a selling price of 12-16 OC per Liter, you would make profit of 25-45 OC per one recipe, seems more reasonable.

**Comment by Oskutin** [comment]
@Zuntti Looks like that the general trade.cs doesn't account item meta values at all

**Comment by Oskutin** [comment]
Price calculation of liquids works on Mr. Bag.

**Comment by Oskutin** [comment]
Hmm, could be rounding error.
What stuff do you sell him, and how much?
What is the estimated value of it in your inventory (before talking with Pentti)?

**Comment by Nextej** [comment]
I've been selling Beer Mash in metal bucket (5L), plastic bottles (0,5L) and glass bottles (0,3L), everytime I got exactly 1 RM, and I also could buy it back for exactly 1 RM.

**Comment by Oskutin** [comment]
It's 35OC per liter = 1.75RM per 0.5L, and considering that Pentti doen't pay that full price, it could round down to 1RM

**Comment by Nextej** [comment]
Why does it give you RM then instead of OC? But also it doesn't make sense if you sell an 8L Bucket with 5L of Mash inside, it should you give 8RM then, but you're still getting only 1.

**Comment by Nextej** [comment]
https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/a2cac349-5b89-435b-a5e6-aa438638cff8

https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/231ff791-7197-4c77-8023-a4ea77ef6643

Also found another rounding error, in the first video, having 5L of mash, it should cover 16 0,3L bottles + 1 bottle with 0,2/0,3L, but all 17 bottles get fully filled to 0,3L each, having made a total of 5,1L of mash.

Another bug in the second video, it seems like one stack of mash in the bottles after being sold changed a texture to a little darker, and after rebuying it turned into normal bottle.

**Comment by Nextej** [comment]
I was going to go with a video of 8L Bucket of 5L Mash, but the game froze sooo...
[Player.log](https://github.com/loiste-interactive/Obenseuer-Issues/files/12270888/Player.log)

**Comment by Oskutin** [comment]
> Why does it give you RM then instead of OC? But also it doesn't make sense if you sell an 8L Bucket with 5L of Mash inside, it should you give 17RM then, but you're still getting only 1.

10 OC = 1 RM

**Comment by Nextej** [comment]
> 10 OC = 1 RM

Yeah, figured out, so if 1L is 35 OC, then you should have 175 OC from a single-item 5L sell, so rounded down to 17 RM.

**Comment by Nextej** [comment]
Oh I see how it might be misleading since 0,3L bottle fit's perfectly into the supposedly correct ratio...

Here's the bucket and plastic bottles, in both cases from the same amount of Mash I've made this time either 1RM or 10RM

https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/424886af-0a52-4599-8daf-ce06f2117f9e


https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/8a7ad93f-79e7-4dc7-8015-f759905efc31

[Player.log](https://github.com/loiste-interactive/Obenseuer-Issues/files/12270932/Player.log)

**Comment by Oskutin** [comment]
Works now, this was fixed by the other price calculation rounding bug.
