### ISSUE TITLE
Mail doesn't seem to be spawned daily if player is not present on the map, it did for me for the first time on the third day.

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#409]

**Comment by Oskutin** [comment]
Was one of the days sunday?

**Comment by Nextej** [comment]
No, it was Monday and Tuesday, first mail came during the Wednesday evening (been sleeping) and the next one about similar time the next day (also been sleeping), however it was doubled the next day (two recipes)

**Comment by Nextej** [comment]
My testing over two in-game weeks
(On map) Monday 13:00 slept to Tuesday 21:00: 2 mails received
(On map) slept to Thursday 16:00: 3 mails received
(On map) slept to Friday 19:00: 1 mail received
(On map) slept to Sunday 3:00: none mail received
(On map) slept to Monday 11:00: 4 mails received
(Outside the map) slept to Tuesday 17:00, then to Thursday 6:00 and visited the tenement: none mail received
(Outside the map) slept to Friday 20:00, then to Sunday 1:00, then to Monday 10:00 and visited the tenement: none mail received
(On map) slept to Sunday 9:00, the fuck...: 8 mails received

So, in the first week I got 10 mails, in the second, I got none, then somehow after sleeping a little over 24 hours I got found myself on Sunday...
[Player.log](https://github.com/loiste-interactive/Obenseuer-Issues/files/12267299/Player.log)
Second part, since the system crashed in the meantime:
[Player.log](https://github.com/loiste-interactive/Obenseuer-Issues/files/12267209/Player.log)

**Comment by Oskutin** [comment]
Ah, the mail system itself is working, but the model is not updating

**Comment by Oskutin** [comment]
Fixed
