### ISSUE TITLE
O-Market and General Store never resupply, no matter whether player is present on the map or not.

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#412]
Oskutin also said that various storages should have their content rerandomized with each day, this doesn't happen either, perhaps for the same reasons?

On a sidenote, furniture sellers do work properly and their content is resupplied properly with every day.

**Comment by Oskutin** [comment]
![kuva](https://github.com/loiste-interactive/Obenseuer-Issues/assets/5402150/f03be2c5-c482-4e93-8d25-4274adba727b)
lol

**Comment by Nextej** [comment]
Who the hell designed this... There's no gameplay in that if you have to wait 8 days for a fucking sugar to resupply... Would've been better if those "proper" stores had their reset everyday (maybe except sundays). For O-Market, I'd even argue that twice a day would be idea...

**Comment by Oskutin** [comment]
You missed the point: the tickbox "respawn enabled" is not checked.
Fixed
