### ISSUE TITLE
"Kurahaara Farmer" task issues.

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#414]
1. Having the turnips grown, there's not way to give them to Kurahaara, neither collected ones count nor just the grown turnips sitting in the bags.
2. Intuitively, it seems like we're allowed to plant and grow turnips in the given Bags of Soil, but upon trying to collect the turnips for the mission, it is considered a crime.

**Comment by Zuntti** [comment]
He only accepts plants grown in his greenhouse. Added a mention of it to the dialogue. Fixed crime bug
