### ISSUE TITLE
Noclip is bugged, player seems to constantly fall.

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#415]

**Comment by Oskutin** [comment]
Please elaborate

**Comment by Nextej** [comment]
When in noclip, the character acts like it's constantly falling (as if the would do normally from height), but with noclip they go immediately through the floor, it seems like multiple floors of a level may block the falling through sometimes.

**Comment by Nextej** [comment]
https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/06561fc1-de74-42bb-8d14-fcf74885756d

**Comment by Zuntti** [comment]
Fixed
