### ISSUE TITLE
Issues with furniture indication inside Inventory.

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#418]
1. Furniture placed in the apartment or used in crafting is still shown inside the inventory, but now with missing icon.
2. Having A LOT of furniture seems to break the display, as seen in the video below, most of them are displayed in one item in the inventory while in reality I have multiple of them, also the sleeping bag has a surprise amount of itself despite having only 1 piece.

https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/ab062b36-5bd4-418e-859e-e66df02ff538

**Comment by Zuntti** [comment]
Fixed
