### ISSUE TITLE
OSRAT doesn't seem to work for the first time we load Interior Tenement Deekula B map

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#42]
Device is reloaded with batteries and Amulet is present in inventory
![image](https://user-images.githubusercontent.com/44178400/232200468-4ad7a1b7-27b9-444f-8884-8ce671874ab9.png)
To be precise, map was loaded by starting a new game, skipping or not the intro and going thru the tutorial normally without using a console. Reloading the game from a savefile does not seem to fix it.

**Comment by Nextej** [comment]
It seems that OSRAT doesn't work only if the map is loaded normally via menu, throughout Intro and tutorial level with whatever settings there are set, while it works properly only if the map was loaded via change_scene. There are few more differences between loading Interior Tenement Deekula B "by menu" and via change_scene, like the fact that some blueprints or recipe never spawn when using the latter.

**Comment by Zuntti** [comment]
Fixed
