### ISSUE TITLE
Suggestion: An option to disable hud (crosshair, money, needs) for taking screenshots.

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#426]
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/0507c193-390c-4996-809e-73236da2f236)

**Comment by Zuntti** [comment]
It already exists but is missing from the key bindings menu. Pressing P should hide it

**Comment by Zuntti** [comment]
Needs to be added to the key bindings menu

**Comment by Zuntti** [comment]
Added to the key bindings menu
