### ISSUE TITLE
Sittable objects can still be used even when occupied (which doesn't happen on normal levels).

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#428]
https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/ef0aa0c8-ba5f-4e06-8cfa-5f3c2a0bc2c0

It also caused my character to bug out and cannot move after standing out, seems like the game still thinks I'm sitting, but I can't even move the camera around
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/aa3d16c4-a912-4369-96b8-ddd2e1ad8134)

**Comment by Nextej** [comment]
[Player.log](https://github.com/loiste-interactive/Obenseuer-Issues/files/12267751/Player.log)

**Comment by Oskutin** [comment]
Fixed
