### ISSUE TITLE
There are some situations, notably in the basement, where the furniture is too tall to be placed, and an appropriate message should be displayed.

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#429]
Some shelfs or cupboards are one examples of tall furniture, if it collides with ceiling, it should say something like "Furniture collides with ceiling" or "Furniture is too tall to be placed here", especially since when placing furniture, we're looking down at a floor, so the cause might not be clear to us.

**Comment by Zuntti** [comment]
Added message that explains why the furniture cannot be placed
