### ISSUE TITLE
Loading up a saved game appears to drastically increase the rate of player's needs.

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#43]
It causes player to quickly loose health from thirst and hunger and it unables to continue without turning on the god_mode.
https://user-images.githubusercontent.com/44178400/232200800-13ef34a3-75f7-4c28-a896-4440b2624417.mp4

**Comment by Nextej** [comment]
It seems that it's not the rate that's increased, but the time between each statistic gets increased got shortened, the rate stays the same as it was. The issue also only happens if the map was loaded normally via menu, past intro and past tutorial level, using change_scene and saving and loading there does not result in the same issues.

**Comment by Oskutin** [comment]
The liquid issue is fixed

**Comment by Oskutin** [comment]
Fixed
