### ISSUE TITLE
Gas Furnace's and Brick Furnace's state of gas bottle slots is resetted with each reload, to always show present gas bottles even when the slots are empty.

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#430]
https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/7d73f693-1bc4-4168-92c5-68fca7686847

**Comment by Oskutin** [comment]
Same as this: https://github.com/loiste-interactive/Obenseuer-Issues/issues/383
