### ISSUE TITLE
Levitating items after upgrading Electricity I

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#432]
https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/25a15cde-34f1-4008-bdc9-22c532d24398

**Comment by Oskutin** [comment]
Seems that the plate from "bare" didn't get removed

**Comment by Oskutin** [comment]
Neither the other stuff

**Comment by Oskutin** [comment]
Fixed
