### ISSUE TITLE
After confirming a tenement contract work, and immediately switching out of the Tab menu and back to inventory, the inventory appears disappeared, reopen again brings it back.

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#434]
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/55d3afc1-086a-4fdc-8531-0d1a9d111d27)

**Comment by Nextej** [comment]
Seems to be more random for simple interaction with Jonasson, perhaps for not opening the inventory after loading onto the map, but going straight to the contractor?

**Comment by Zuntti** [comment]
Fixed
