### ISSUE TITLE
Mushroom Farm seems to be an upgrade that should be locked by its previous version, because with each time, it's ever slightly enlarged.

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#438]
It shouldn't be possible that we skip all the way up to the largest version.
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/710f88c8-013f-438c-b98c-1e5d2fb15263)

**Comment by Zuntti** [comment]
Fixed
