### ISSUE TITLE
Player's Tenement: a lot of areas of basement (utility rooms, sauna, southern corridor) are full of "owned" storages and items.

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#446]
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/09e6ac62-95a6-4c96-9279-8abe37f0a10e)
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/f757f837-016f-4fe5-9e68-9a38254e4833)
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/10904f62-c58b-4c0a-af49-93820d42fba7)

**Comment by Zuntti** [comment]
Fixed
