### ISSUE TITLE
Sometimes when exiting the basement's swimming pool, wet footsteps sound doesn't stop and continues on.

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#447]
https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/2a3d5fa0-c306-423f-8a17-6e5d054be0c5

**Comment by Nextej** [comment]
[Player.log](https://github.com/loiste-interactive/Obenseuer-Issues/files/12282153/Player.log)

**Comment by Oskutin** [comment]
Fixed
