### ISSUE TITLE
Bathroom radio body scene issues

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#45]
It's too easy to position yourself in a way you're being hurt by the shrooms when trying to talk, perhaps the damage should be disabled when being on the otherside
https://user-images.githubusercontent.com/44178400/232202828-6ec8b78e-427e-42ad-a1f4-bb36b71f75f2.mp4

When reaching a certain point in a conversation with the body, the possible dialogue options are repeated and there's no way to proceed the scene, nor to leave it in any way
https://user-images.githubusercontent.com/44178400/232202871-734b7823-55c1-4ff9-88a7-30f6b484a1df.mp4

Also when dying during a conversation, it can be continued when the death screen with menu is present.
https://user-images.githubusercontent.com/44178400/232202937-42c9c782-6432-4629-b50b-843eb7b2996b.mp4

**Comment by Zuntti** [comment]
Fixed
