### ISSUE TITLE
For Wooden Pallets furniture, add an ability to switch between horizontal and vertical orientation of placement, so player can put a pallet vertically without additional support.

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#453]
Since the game doesn't have any chain fence/wall to separate space, Wooden Pallets could work just fine.
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/fb0ecb98-4da3-404e-99c7-5acfb6ad3114)

With the Wooden Half-Pallets being added too, would be nice if snapping was added too, both vertical and horizontal to put pallets evenly if possible.

**Comment by Oskutin** [comment]
Already kinda implemented with the snap system
