### ISSUE TITLE
On the start of the game, player should be able to find a blue print for a Wooden Chest in an accessible location at the Player's Tenement.

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#455]
Certainly at the beginning, player will be collecting a lot of junk (useful or not) and they'll rather quickly ran out of space to store them, being able for sure to create any kind of storage early in the game might help with this, and additionally will set one of the first goals for the player - find items to craft a storage - so they are not completely lost on what to do.

It should be always an Wooden Chest item, plain clear on what is it.
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/ecf65636-59d9-4e25-870a-df04b6b8fe0c)

**Comment by ontrigger** [comment]
+1

**Comment by Oskutin** [comment]
Done
