### ISSUE TITLE
Regarding auto-sorting by categories, a Water in a (plastic/glass/wine) Bottle is not considered a consumable and lands with other bottles/cans.

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#458]
Additionally, it seems that rearranging the items position, makes the Water being considered as a consumable and auto-sort button whenever clicked the other time, shuffles between two different sorted configurations.

https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/257ff6bb-2735-4a1c-a324-a4aeb7826a5e

**Comment by Oskutin** [comment]
Now liquids in containers get sorted separately from containers
