### ISSUE TITLE
O-Market restocking is broken, it seems like with each day there's less items, on the fifth day, the store is almost empty

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#462]
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/db34674d-bf8d-47cd-870b-e1dd632acb1d)
_those are not broken visual stages of storages, they are all empty_

A day before there were a minimum of items

https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/4c938667-28a1-4b77-8266-008fac9a2480

**Comment by Oskutin** [comment]
Fixed
