### ISSUE TITLE
In relation to ##412: Restocking of General Store (item section) is not fixed.

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#463]
Friday:
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/e173a9e9-5c87-4c38-b261-5cdff89e900e)

Monday:
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/e999bafa-4083-4fc3-85a6-13618e350e50)

**Comment by Oskutin** [comment]
Fixed
