### ISSUE TITLE
Mashing Tun: reloading the map while the recipe is going makes the crafting corrupted, there's no longer a way to abort it and the progression had stopped.

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#468]
https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/6298ff3d-c722-4dfe-bac5-0a9771d3cbe3

**Comment by Oskutin** [comment]
log?

**Comment by Nextej** [comment]
[Player.log](https://github.com/loiste-interactive/Obenseuer-Issues/files/12316971/Player.log)

**Comment by Oskutin** [comment]
Is this player placed mashing tun, or one found elsewhere?

**Comment by Nextej** [comment]
Player placed, did not test the ones found in the world.

**Comment by Zuntti** [comment]
Fixed
