### ISSUE TITLE
Player's Apartment: Seems like a Suitcase originally found in the apartment and re-placed in a new location at first doesn't render items if the map is reloaded, this doesn't seem to happen to other storages.

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#469]
https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/e546c75d-b0dc-4904-a4b7-7dcee0f53825

**Comment by Nextej** [comment]
[Player.log](https://github.com/loiste-interactive/Obenseuer-Issues/files/12315339/Player.log)

**Comment by Zuntti** [comment]
Fixed I think
