### ISSUE TITLE
Dragging money found in storages using double click and CTRL

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#47]
When trying to take money from a storage via double mouse click while holding CTRL takes only half (in not even, rounded up to player's favor) of the amount, for instance trying that on a stack of 75 OC adds only 38 OC to your account. 

Using just a double click adds the amount normally as expected.

https://user-images.githubusercontent.com/44178400/232209973-28a02795-0f2f-4035-8e0c-fbcb399e4737.mp4

**Comment by Oskutin** [comment]
Fixed
