### ISSUE TITLE
In relation #406: it's not fixed...

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#473]
8L of Mash sold to Pentti gives you only 2 RM while according to Oskutin with the ratio of 1L = 3,5 RM, I should get 28 RM per bucket. So from total of 32L of Mash I got only 4 RMs

https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/4df38c6f-fbc4-4551-9808-9a0a8ad0b8f7

**Comment by Oskutin** [comment]
Quality of the mash affects the price.

**Comment by Oskutin** [comment]
And you're selling very low quality mash.

**Comment by Nextej** [comment]
The problem still exists, I can just put all the Mash to glass bottles and from 5L make 17 RM in compare to 8L of Mash in a bucket that makes 2 RM...

https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/0b5f3f87-e659-4c94-94b7-00caa07f716a
