### ISSUE TITLE
Player's Apartment is not being checked off as an examined.

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#480]
This might be a singular, rare case, but right now there's nothing I can do to make upgrades to my apartment, I can still go around and examine other apartments and they do count normally.
[Player.log](https://github.com/loiste-interactive/Obenseuer-Issues/files/12316004/Player.log)
[Game_Tester.zip](https://github.com/loiste-interactive/Obenseuer-Issues/files/12316007/Game_Tester.zip)
Game Tester is the save file for the character.

**Comment by Zuntti** [comment]
Fixed
