### ISSUE TITLE
Thoughts and concerns about Player's Tenement placement in relation to the rest of the points of interest on the map.

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#481]
I like the current layout of the map made for playtesting purposes, mainly the fact that Player's Tenement is directly connect to them, if we look at how the map looks right now, we'll see that the Tenement is always near the player's reach.
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/c6ba98e5-b9d6-4db7-8147-af1e5110e6d0)
Whenever player is moving between the most important points of interest, there are high chances they will pass by Tenement, usually stepping by to take some equipment, food and leave unnecessary for now items to free up inventory, but also unlocking/buying new furniture/blueprints is an another reason to step by and preview the new stuff we just got.
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/d0db02c5-5be4-4ff0-9c90-23bee477ed72)
My point being that there's plenty of situations player is able and may want to step into the Tenement (and now how interactive it is in this version, there are good reasons to do so), including just item storage.

But if we look at what it's meant to be for the final version, Tenement is clogged somewhere in the dark edge of the map noone ever goes because there's no reason to, Tenement is far away from any points of interest.
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/0c1266e8-cd3e-4647-952c-31c1a1ec5740)
While ideally it should be in the middle between all the points of interest, so the Tenement works as hub the player has many reasons and chances to step by. I'd even say in the current playtesting layout, it would've been even better if the Tenement was in the middle.
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/f107ee8f-6073-4ea5-b33e-ebec47579130)
But let's get back to the final version, I'm afraid players won't be just spending much time there, nor want to upgrade their apartment, they can sleep, relief, eat and to some degree process items in a better place, more "closer to civilization" where everything is near, the only thing they cannot do is store items, so I can already imagine unnecessary trips across whole map just to leave out some items.

One thing I'm thinking of would be to have a rentable storages either near the Market or at the Deekula, so it works a s "hub" for the player and the player still has that "own" space, somewhere they can keep something to themselves, perhaps such rentable small spaces could be featured in every district. _Alternatively you could just remade the whole outside map to, I dunno, swap Deekulas with Tenement, but I doubt you'd do it at this stage._

**Comment by Oskutin** [comment]
I'd say that this is pretty much irrelevant as the exterior map is coming soon.
