### ISSUE TITLE
Easily accessible blueprints (for the early game) needs to have a limited selection of items.

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#482]
When version 0.3.03 originally was released, there wasn't much craftable furniture, yet the ones that were, were rather valuable to the player, stuff like storages, bucket toilet, basic decorative structures like crates, pallets or crates. However version 0.3.05 added tons of decorative or much more advanced machinery player won't really want or need at their early stages. So for the player's sake, blueprints that are at the accessible locations (like the workshop at Deekula B, attic at Deekula A) should provide those more basic, limited recipes, if they are respawnable, they should provide better stuff once player gathered all the basic ones.

**Comment by Oskutin** [comment]
Done
