### ISSUE TITLE
Player's Apartment Makeshift Toilet shouldn't have Bucket Toilet preplaced, it makes the Bucket Toilet furniture (and a blueprint you must find for!) obsolete.

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#483]
At this point, player will sooner have this upgrade completed than they find a blueprint to be able to craft this furniture, which puts the existence of this furniture in question... Since it is acquirable (unlike the Sink that's also placed automatically in Makeshift toilet), player should earn the Bucket Toilet themselves, not get it with the toilet upgrade.

**Comment by Zuntti** [comment]
Removed the bucket toilet

**Comment by Zuntti** [comment]
Actually no. The sink also furniture that is probably going to have a blueprint

**Comment by Nextej** [comment]
So finally, is player getting them both "for free" pre-placed or had both been removed for player to craft?

**Comment by Zuntti** [comment]
They come with the upgrade for now so that it is similar to other apartments upgrades. Those are the only things how the upgrade differs from lvl 0
