### ISSUE TITLE
Translation potential of the game

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#487]
Would be nice to look into possibilities of making the game translatable before the release:
- Certainly most European (and not only I imagine) languages will need a separation for male and female character dialogue lines, ideally would be nice to have a separate string lines for each per language, so the game loads the needed one based on player character's gender.
- Additionally all the item/UI names and descriptions would need to be moved into their own string file with proper internal names.
- Would be also nice to have some specific posters/infoboards/graffiti/_whatever with readable text_ to be swappable depending on the selected language.

If translations would be something to come, I'd be willing to get it up done in Polish, I'd be even willing to start in advance if I could only get notes/dialogues/item descriptions sooner.

**Comment by Oskutin** [comment]
Implemented (to some degree)
