### ISSUE TITLE
Issue #417 also applies to Bandsaw

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#497]
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/19773d1f-57be-4341-bca4-1759db3fb240)

**Comment by Oskutin** [comment]
Can you merge and list these issues into a single (new) issue

**Comment by Nextej** [comment]
So far it's the only one I found, I'll update it if I find more, the older ones are fixed.

**Comment by Zuntti** [comment]
Fixed
