### ISSUE TITLE
Various gameplay inconsistencies

### ISSUE THREAD

**Issue by deseven** [loiste-interactive/Obenseuer-Issues#50]
1. In some rooms light switches can be triggered, in others they are just a part of the scenery. Maybe make them all interactable, but in rooms where you don't want lighting just make them do nothing?

2. Some boxes could be broken with a sledgehammer, but others couldn't. Same with the planks that block door frames. Also, since you give us a sledgehammer it would be nice if it can break some other stuff, like bottles and TVs. Otherwise maybe just make it a quest item that can be used in needed places (kinda like a boltcutter in Infra)? As of now having it equipped feels pretty useless in most cases.

3. Maybe I missed it, but there is no clue anywhere that you have to call 112 to reach the police. This number might be unknown for many.

**Comment by Nextej** [comment]
In relation to this report, near the entrance to the attic you can find an guitar that despite being exactly the same model as an actual useable one, it cannot be picked up.
![image](https://user-images.githubusercontent.com/44178400/232310071-d563ffa0-79bb-47dd-b554-9fbc116143c1.png)

Similarly you can find an electric stove in one of the storages in the basement that cannot be used, despite looking the same way as any other useable stove in the building, nor be stolen to be used on our own advantage in our own tenement.
![image](https://user-images.githubusercontent.com/44178400/232310333-98851898-825d-49ad-8401-bbbbd29efd23.png)

**Comment by Oskutin** [comment]
The latter part is fixed

**Comment by Oskutin** [comment]
Instruction to call 112 is implemented in the next update. Closing this for now.
