### ISSUE TITLE
After selling mash to Pentti, make him return the container within an hour or so after selling (in a separate window below selling slots) with an appropriate dialogue from him after closing the selling window.

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#500]
Currently loosing a container in the process is painful, mostly since the container itself is more valuable than the sold mash...

**Comment by Oskutin** [comment]
insta return would be the best & easiest

**Comment by Oskutin** [comment]
Or adding a generic free container spawner to his bar

**Comment by Oskutin** [comment]
Pentti now sells canisters at discount, also the canisters in his backroom respawn
