### ISSUE TITLE
Locker placed in apartment won't open anymore

### ISSUE THREAD

**Issue by CarlieBendix** [loiste-interactive/Obenseuer-Issues#507]
I bought a locker and placed it in my apartment, now it won't open anymore. The door opens only a crack (see below) and the items menu does not appear. Keeps happening if the locker is removed and placed again.
Also I can't sleep in the bed I placed there. The (sleep) prompt does appear, but pressing E doesn't do anything except play a sound.
Loading save fixes both issues

![Screenshot (2)](https://github.com/loiste-interactive/Obenseuer-Issues/assets/139687446/4d610bda-086e-4434-a8a6-b047c6987463)

**Comment by Oskutin** [comment]
Logfile?
