### ISSUE TITLE
You can put flashlight into primary slot, the item doesn't seem to work tho.

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#511]
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/36ebb4af-cdf7-48d3-b639-86577060e50f)

**Comment by Zuntti** [comment]
How did you do it?

**Comment by Nextej** [comment]
Simple drag&drop
https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/d23a39c4-4483-4f49-b458-29948e3deefb
Weird, last time I've tried I couldn't place anything in the flashlight spot except for flashlights...

**Comment by Nextej** [comment]
Turns out you can place anything into those slots.

**Comment by Zuntti** [comment]
Can I get save where this is possible?

**Comment by Zuntti** [comment]
Fixed
