### ISSUE TITLE
Kurahaara farm task, giving out turnips for the quests counts the quest condition up, but does not take the turnips from our inventory.

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#512]
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/41fd6d4d-35fa-45d0-ae78-a0fd16d6ed9a)
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/79d823a4-9f80-48de-bbbb-5713c1a638fc)

**Comment by Nextej** [comment]
It only happens if you given him not a full amount, items get properly taken away when the stage of the task is completed (giving him the remaining 3 turnips finished the task and took them away).

**Comment by Zuntti** [comment]
Seems to work for me

**Comment by Nextej** [comment]
Gonna create a new save and redo it later.

**Comment by Nextej** [comment]
Also cannot recreate anymore.
