### ISSUE TITLE
Moving around a storage with items in it, at first causes those items to disappear (likely during a reload) and attempt to remove that storage causes it to duplicated, one copy has our items.

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#513]
[Player.log](https://github.com/loiste-interactive/Obenseuer-Issues/files/12457406/Player.log)

**Comment by Oskutin** [comment]
Is this just limited to the suitcase already present in the map?

**Comment by Nextej** [comment]
I've tested so far it only on the suitcase.

**Comment by Oskutin** [comment]
Which is already known to be bugged

**Comment by Nextej** [comment]
Happens to all storages when Moved or Taken while having items inside. Allows for easy duplication.

**Comment by Zuntti** [comment]
1. Put any storage with items on any originally found object (cardboard, dirt etc)
2. Save and load
3. Take the storage
4. Take the object where it was
5. Now you have duplicated storage

**Comment by Zuntti** [comment]
Fixed
