### ISSUE TITLE
Leave Buckets of Paint loosely on the apartment's floor causes two of them to disappear over time.

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#514]
[Player.log](https://github.com/loiste-interactive/Obenseuer-Issues/files/12457416/Player.log)
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/1d5e3f85-5954-4fad-ac47-93e0c923c6e8)

**Comment by Zuntti** [comment]
Can I get a save where this happens?

**Comment by Nextej** [comment]
[Miko_Mortley.zip](https://github.com/loiste-interactive/Obenseuer-Issues/files/12587800/Miko_Mortley.zip)

**Comment by Zuntti** [comment]
Fixed
