### ISSUE TITLE
Cheese refrigerator at O-Market gets corrupted seemingly after the product gets spoiled.

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#517]
https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/78070481-7f12-443a-b8a2-8135761710ae

[Player.log](https://github.com/loiste-interactive/Obenseuer-Issues/files/12459284/Player.log)

**Comment by Oskutin** [comment]
Fixed
