### ISSUE TITLE
Suddenly levels got reset to their original state at every aspect.

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#525]
[Player.log](https://github.com/loiste-interactive/Obenseuer-Issues/files/12468043/Player.log)

**Comment by Oskutin** [comment]
This happened after a crash?

**Comment by Nextej** [comment]
No, during a playthrough, but I think it might be on me given a thought, since autosave folder was corrupted I decided to remove it to avoid any more progression loss, and I think that the lack of the autosave folder caused them to reset as apparently it seems the game first creates an autosave when transiting and then loads it up immediately after.

**Comment by Oskutin** [comment]
Yeah it was that
