### ISSUE TITLE
"Getting Started" task, the stage with having to complete 5 renovations should account those that are already started (and possibly completed) except for the very first one.

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#526]
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/281628ca-e207-4937-87ca-4306817f3781)
I've started two renovations about in the same time, now that I started the first renovation gotten a next stage, the second renovation I have going on won't be accounted in the stage.
I personally even forgot about this guy to report to him back, so I assume a lot of people may do as well, starting more renovations before even getting that "0/5 renovations" stage.

**Comment by Zuntti** [comment]
Fixed
