### ISSUE TITLE
When loading an Autosave, it puts you on a toilet...

### ISSUE THREAD

**Issue by TiaLinna** [loiste-interactive/Obenseuer-Issues#53]
![20230415194730_1](https://user-images.githubusercontent.com/130680276/232238907-b4901e67-f3b2-4fb2-9765-4a7bf0c0a487.jpg)
![20230415194749_1](https://user-images.githubusercontent.com/130680276/232238909-a9085183-2ce5-47b7-b099-ceb17f701700.jpg)

and if you noclip out, it teleports you back to the bathroom and locks you in 1x1 square spot, which you can't move out from

**Comment by TiaLinna** [comment]
And the needs keeps rapidly going lower (has been Issued before)
And I used two different Autosaves, getting stuck AND needs going low happens on both cases

**Comment by gehube** [comment]
same as issue #32
