### ISSUE TITLE
After update 0.3.08, Mashing Tun can process only 5 L of mash at the time, despite having ingredients for much more.

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#533]
In the example below, I should be able to produce at least 40 L of mash.

https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/2853c120-9a12-4f12-a83f-001e087a99a4

Additionality, the recipe doesn't include minutes for the actual process time.
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/85f5f7ec-43cd-4861-a118-6687a58cb6f8)
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/568a3b87-29f5-471b-956c-064fede19493)

**Comment by Oskutin** [comment]
Seems to work correctly for me

**Comment by Oskutin** [comment]
Hmm, I think it would be that it doesn't count multiples correctly if one of the input is item group.

**Comment by Oskutin** [comment]
Yeah, that was it. Fixed
