### ISSUE TITLE
General Store sometimes is closed during working hours during the week, reloading level fixes it, however it tends to be open on sundays too (without reloading).

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#534]

**Comment by Oskutin** [comment]
Sunday opening is intentional

**Comment by Oskutin** [comment]
https://github.com/loiste-interactive/Obenseuer-Issues/issues/535 Seems to be same cause than with this - time breaking entirely (whay is potentially fixed aleady).
