### ISSUE TITLE
Somewhen after a one in-game week, the mail had stopped coming.

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#535]

**Comment by Oskutin** [comment]
You said you placed some furniture on the doorway?

**Comment by Nextej** [comment]
Near the doorway, that way it visually would not block the mail. It was removed since but the mail still hadn't come.

**Comment by Nextej** [comment]
I had this moment when all stats were suddenly broken and nothing had progressed since until a restart #522 could it be related?

**Comment by Nextej** [comment]
It was looking like that
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/e3b01709-c057-4f9c-a87a-700bc84908eb)

**Comment by Oskutin** [comment]
> ressed sin

Most likely, as it seems that the entire time system broke for you.

**Comment by Oskutin** [comment]
logfile?

**Comment by Nextej** [comment]
What do I do, just spend a week in game skipping time?

**Comment by Nextej** [comment]
This time that I've launched the game and with console commands went to sleep, I gotten a mail soon after, which wasn't happening previously in my actual session (where I was on the map for hours and been sleeping a lot).
[Player.log](https://github.com/loiste-interactive/Obenseuer-Issues/files/12566502/Player.log)
