### ISSUE TITLE
Carl Fatler chocolate turns into dirty water

### ISSUE THREAD

**Issue by Gnarynhar** [loiste-interactive/Obenseuer-Issues#537]
I tried buying some Carl Fatler Chocolate Bars at the OS Mart. After paying and picking them up they became dirty water when I opened my inventory

![ose1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/55886367/44cadbf5-46fa-48e9-8ee0-4e83e7d3f879)

Initially I brought 3, combined into one stack. I reloaded to the earlier autosave and tried again. Dirty water. 
I've also tried leaving them as 3 separate units, they turned into dirty water.
I tried buying just one. I turned into dirty water.

**Comment by Zuntti** [comment]
Fixed
