### ISSUE TITLE
Item stuck at drag'n'drop, then disappear after saveload

### ISSUE THREAD

**Issue by Kastuk** [loiste-interactive/Obenseuer-Issues#539]
I have glitching mouse: sometimes left mouse button hold is interrupting, so dragged icons may drop in the middle of dragging.
When I drag items in game, items may drop between cells or in non-interactive areas of inventory UI.
They will hang there after inventory is closed untill I save and load the game, then item will disappear to nowhere.
Theres savegame and log at game start, when I dragged the stack of planks and they stuck. There's also screenshot of it and other one, when empty bottle did stuck in the sink.
[Kastuk save drag item stuck and disappear.zip](https://github.com/loiste-interactive/Obenseuer-Issues/files/12659068/Kastuk.save.drag.item.stuck.and.disappear.zip)

[Player Wood stuck and disappear while dragndrop.log](https://github.com/loiste-interactive/Obenseuer-Issues/files/12659069/Player.Wood.stuck.and.disappear.while.dragndrop.log)
![20230918013920_1 item drag stuck](https://github.com/loiste-interactive/Obenseuer-Issues/assets/36314945/bf22e975-3ff1-4fe1-8bf6-2c0734c1b2de)
![20230919133024_1 item drag stuck](https://github.com/loiste-interactive/Obenseuer-Issues/assets/36314945/67f0b0bb-03fd-44c4-8ce7-22333476aa45)

**Comment by Oskutin** [comment]
Old and known issue
