### ISSUE TITLE
All cucumbers is spoiling at young stage

### ISSUE THREAD

**Issue by Kastuk** [loiste-interactive/Obenseuer-Issues#542]
So I cannot complete second farming order.

**Comment by Oskutin** [comment]
This is not a bug, it's related to farming skill.

**Comment by Oskutin** [comment]
It is fixed already

**Comment by Oskutin** [comment]
![kuva](https://github.com/loiste-interactive/Obenseuer-Issues/assets/5402150/263c5c57-ce0f-4763-97c2-b549ab9bca7a)
