### ISSUE TITLE
Rye is not growing from grain

### ISSUE THREAD

**Issue by Kastuk** [loiste-interactive/Obenseuer-Issues#543]
Rye is not growing from sowed grain, which is harvested from rye stalk which did grow from seeds.

Also grain is not stackable and overfilling inventory at harvesting, drop and hang in the air.
![20230919162428_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/36314945/f3f9c518-4336-4af8-a5b6-a8938cc71961)

**Comment by Oskutin** [comment]
Can you elaborate, what you mean with rye is not groing?

**Comment by Kastuk** [comment]
I mean there's no growing progress of Rye stalk which sowed from harvested grain.

**Comment by Oskutin** [comment]
Okay, so the rye grows, but it doesn't show up the model?

**Comment by Oskutin** [comment]
Rye and wheat are now stackable

**Comment by Oskutin** [comment]
Works for me 
![kuva](https://github.com/loiste-interactive/Obenseuer-Issues/assets/5402150/6d284da1-f60a-4177-86fd-50ceda239582)

And that 0 growth progress is the filed planting related to farming skill
