### ISSUE TITLE
Cheese shelf in Market only has 99 "Open Sewer Coin"

### ISSUE THREAD

**Issue by binbows** [loiste-interactive/Obenseuer-Issues#544]
The Cheese shelf in the market only contained what seems to be a bugged out version of the Open Sewer Coin item.
With each opening of the Container menu, the space inside would increase by one.

No idea on how to replicate, **however** I should note this was in a save with cheated in money with the add_item command.

https://www.youtube.com/watch?v=6JyZyPISKzE
(video of bug)

**Comment by Kastuk** [comment]
Also, Cheese, Yeast and Mammi shelves is not let return their type items back. That bug can start right at this shelves.
Then all freezer shelves may become affected, include milk, meat and sausages, but not fish and peas.

**Comment by Oskutin** [comment]
Already fixed
