### ISSUE TITLE
Package is not returned after consumption or failed cooking

### ISSUE THREAD

**Issue by Kastuk** [loiste-interactive/Obenseuer-Issues#548]
90030 Bowl 
  is not returned when these recipes is failed:
10210 Macaroni casserole
10211 Macaroni casserole 
10212 Mushroom macaroni casserole
10386 Boiled Rice

Also
10690 Empty Milk Carton
  is not returned after consumption of:
20210 Milk

**Comment by Oskutin** [comment]
Fixed
