### ISSUE TITLE
Pause menu settings: brightness slider

### ISSUE THREAD

**Issue by Kastuk** [loiste-interactive/Obenseuer-Issues#551]
Brightness slider is clone of FOV one in Display settings on Pause menu.

**Comment by Oskutin** [comment]
So it modifies FOV?

**Comment by Kastuk** [comment]
![20230929225525_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/36314945/642d0be9-fa97-4c8f-be33-e00a3d381909)
![20230929225508_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/36314945/50259f5f-3d2f-4b1f-a1e2-ef9218022b6d)
Seems like that

**Comment by Crlangley** [comment]
![20230930015723_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/65619937/8d7ae739-a018-49c5-b44a-eccc2693d6c3)
![20230930015711_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/65619937/b8c97a83-2ecc-4073-8b3a-46cb2ae13db9)

the FOV can get to some rather extreme views with brightness

**Comment by Crlangley** [comment]
![20230930020146_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/65619937/0ddd142d-8d23-4f80-a896-55b6e5e0ef2b)
![20230930020158_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/65619937/498bfb70-2a1c-45de-ae10-388938d71d47)
Can also use brightness to lower FOV below 60 down to 1 and up to 200

**Comment by Zuntti** [comment]
Fixed
