### ISSUE TITLE
Sink with beer

### ISSUE THREAD

**Issue by Kastuk** [loiste-interactive/Obenseuer-Issues#552]
Sink in Hanes hideout in basement got recipes not just for clean water, but also for dirty one and beer too. 
No modifiers to make them.

I not reached bar in this save yet, other sinks have just both water recipes sometimes.

**Comment by Oskutin** [comment]
Picture?

**Comment by Kastuk** [comment]
![20230929230044_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/36314945/a50cf863-a279-4e12-b48e-778c501f57a9)

**Comment by Oskutin** [comment]
And they're craftable?

**Comment by Kastuk** [comment]
Nope, lack of special modifiers, only Clean can be produced there.

**Comment by Oskutin** [comment]
Not necessarily a bug, but something that could be improved.

**Comment by Oskutin** [comment]
This is likely already fixed. Atleast I haven't seen this recently
