### ISSUE TITLE
Lighting artifacts in Samual Jonasson's workshop(Graphical)

### ISSUE THREAD

**Issue by KoolHoven11** [loiste-interactive/Obenseuer-Issues#553]
![951240_20230929235842_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/146493678/7204baf1-f854-4bdb-b40b-0bc614f03789)
![951240_20230929235852_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/146493678/0d8e4ad5-32bb-458b-9599-8fd7dcd8eecd)
Lighting around Samual Jonasson's workshop seems to be a lot brighter after last patch compared to other locations making it hard to see
Location: Deekula A
Reproduction: Happens from launch
Seems to persist as I havent notice the brightness change at all
Version: V. 0.3.09

**Comment by Oskutin** [comment]
Also, theres a overlit (red) plastic chair in the back.

**Comment by Kastuk** [comment]
Huh, I was think he is such shiny delighted man...

**Comment by Oskutin** [comment]
Fixed
