### ISSUE TITLE
Bright red chair in Deekula A (Graphical)

### ISSUE THREAD

**Issue by KoolHoven11** [loiste-interactive/Obenseuer-Issues#554]
![951240_20230929235914_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/146493678/117486f6-b085-4212-9a61-e165a8d4dd0c)
![951240_20230929235944_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/146493678/ed9f97d9-05ce-4e6a-b1af-127060a5f2de)
Issue: Plastic chair just outside of Samuel Jonasson's Workshop has an unnaturally bright red reflection from the red service light opposite it compared to other objects
Location: After exiting Deekula Basement into Deekula A, and going up the stairs and under the boards, its on the left (behind Samuel Jonasson)
Reproduction: Seems to be there from game launch (new saves too)
Issue does persist
Version: V. 0.3.09

**Comment by Oskutin** [comment]
#553 Same lighting artifacts
