### ISSUE TITLE
Nameless furniture without model and sprite at furniture seller.

### ISSUE THREAD

**Issue by Kastuk** [loiste-interactive/Obenseuer-Issues#557]
It's like that at the very start, after update of the shop next day too.
![20230930021859_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/36314945/4f861b18-7e2e-4358-bbe5-f24ab39ff579)
Savegame:
[empty  furniture positions in shop.zip](https://github.com/loiste-interactive/Obenseuer-Issues/files/12772741/empty.furniture.positions.in.shop.zip)
If you buy it and try to place in your apartments, it will show just name.

**Comment by Oskutin** [comment]
Logfile?

**Comment by Kastuk** [comment]
[Player.log](https://github.com/loiste-interactive/Obenseuer-Issues/files/12772758/Player.log)
Same one as in #555

**Comment by Oskutin** [comment]
Can you list what furniture cause issues?

**Comment by Kastuk** [comment]
Will try to fill the list.
First ones from the log with that exception:

UnityEngine.AddressableAssets.InvalidKeyException: Exception of type 'UnityEngine.AddressableAssets.InvalidKeyException' was thrown. No Location found

- Storage/Small Wooden Night Stand.asset
Lights/Wall Light.asset
Lights/Plank Ceiling Light.asset
Decoration/Red Shroomekko Wall Cloth.asset
Chairs/Small Wooden Step Stool.asset
Chairs/Tuffet.asset
Shelves/Plank Shelf Blueprint.asset

**Comment by Kastuk** [comment]
Also:

- Shelves/Shelf Large Plank.asset 
- Decoration/Shroom Bottle Wall Cloth.asset 
- Decoration/Green Shroomekko Wall Cloth.asset  <-- this one appear fine in store but not in building menu
- Lights/Plank Ceiling Light.asset  <-- same

- Blueprints/Chairs/Plank Stool Blueprint.asset <-- is blank in Manufacturing screen

**Comment by Oskutin** [comment]
Fixed
