### ISSUE TITLE
Prison: waiting by book reading freezes game

### ISSUE THREAD

**Issue by Crlangley** [loiste-interactive/Obenseuer-Issues#559]
Used the book inside the prison cell at the gatehouse, it froze my game, though after about a minute it seemed to further glitch out and finished the prison sentence by fast forwarding another 17 hours  more than it should and freeing the game again after the guard says you can leave.

**Comment by Crlangley** [comment]
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/65619937/5011c5db-a79e-42f3-92fb-6319144f8f7c)
 
Game is still active i'm just stuck here and unable to do anything, slowly dying now

**Comment by Crlangley** [comment]
update: dying does seem to fix it to the point it lets you get to the menu

**Comment by Oskutin** [comment]
got logfile of the frozen game?
