### ISSUE TITLE
Rendering issues in one of the corners at the entrance to the attic in Deekula B.

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#56]
https://user-images.githubusercontent.com/44178400/232308898-833d47e0-286e-4bdc-8170-bdd9bbea95ae.mp4

**Comment by Nextej** [comment]
Another such issue appears in apartment B3 in the room with woman in bed while standing on a table.

https://user-images.githubusercontent.com/44178400/232322858-67809bea-b85a-407b-91cc-2fd98b069aaa.mp4

**Comment by Zuntti** [comment]
Fixed
