### ISSUE TITLE
I get thrown back into jail everytime the jailer frees me, opens the door and sees me leaving

### ISSUE THREAD

**Issue by Crlangley** [loiste-interactive/Obenseuer-Issues#560]
![20230930014723_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/65619937/3e936547-1550-47ce-8b57-e465adf7527c)

Has happened twice after originally getting caught opening the door with the lockpicks if that might be causing it.

**Comment by Zuntti** [comment]
Fixed
