### ISSUE TITLE
Store door spawn direction 

### ISSUE THREAD

**Issue by Crlangley** [loiste-interactive/Obenseuer-Issues#561]
entering and leaving the camera guy shop spawns the player facing 90 degrees to the right going in and 90 degrees to the left

**Comment by Crlangley** [comment]
![20230930100812_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/65619937/c6b8e873-2249-4f39-87bc-259e6ee13f38)

**Comment by Oskutin** [comment]
Not a bug as only applies to playtesting versions
