### ISSUE TITLE
Two wall cloths in Mr.Bags shop 

### ISSUE THREAD

**Issue by Crlangley** [loiste-interactive/Obenseuer-Issues#564]
Both wall cloth items are laying on the ground in the preview and can clip through the walls and décor in the back 

![20230930105212_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/65619937/1cc3a4e6-7146-4e9a-bc4d-570775b97997)
![20230930105258_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/65619937/32945e50-cffa-4e03-85e7-a4eb4d2bc7ac)

**Comment by Oskutin** [comment]
Fixed
