### ISSUE TITLE
3 NPC foreheads glitching out 

### ISSUE THREAD

**Issue by Crlangley** [loiste-interactive/Obenseuer-Issues#565]
Just the upper part of the head on these 3 below will being rapidly going up and down 

![20230930020158_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/65619937/1c9a758b-72a0-44be-98eb-e6d26a6312d5)

**Comment by Crlangley** [comment]
![20230930143530_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/65619937/7ad5fc6f-0338-45c3-9e24-a1128db9f10a)
![20230930143801_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/65619937/e11b3703-e901-4a0f-ba62-c4bff0f374da)

**Comment by Crlangley** [comment]
I think ive seen others do this, but when going through the game checking them all it was only these 3 I could find with this issue

**Comment by CBS-S** [comment]
The Market Square Police bald guy's head also did this for me

**Comment by CBS-S** [comment]
Fidan Tanner also does this for me

**Comment by Kastuk** [comment]
Arvid Vinter, who also is naked owner of hostel Warehom

**Comment by CBS-S** [comment]
Also Johan Wider

**Comment by Oskutin** [comment]
is there some characters this never happens?

**Comment by Oskutin** [comment]
Potentially fixed

**Comment by Z-O-M-B-I-E** [comment]
> is there some characters this never happens?

jomppe Kurahaara - normally
Eija Lurppu - not normally
Arvid Vinter - not normally

The problems are mainly with sellers
