### ISSUE TITLE
Drill moving texture

### ISSUE THREAD

**Issue by Crlangley** [loiste-interactive/Obenseuer-Issues#566]
![20230930152857_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/65619937/b57c844c-323b-4cdf-9254-a4353e0ec43d)

**Comment by Oskutin** [comment]
How you got this to happen?

**Comment by Crlangley** [comment]
left an incomplete lockpicks being made and left for awhile. might have caused it as i came back to them finished and the machine doing this

**Comment by Oskutin** [comment]
Fixed
