### ISSUE TITLE
Trash texture behind Samuel Jonasson is floating above the ground by about an inch

### ISSUE THREAD

**Issue by Crlangley** [loiste-interactive/Obenseuer-Issues#568]
![20230930232130_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/65619937/a18422ae-9d7a-4167-9228-7a9bea0f42ea)

**Comment by Crlangley** [comment]
![20230930234738_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/65619937/cd8342e0-0fa6-4dad-84ab-f1212405cf25)
these boxes under the desk near the trash are floating too

**Comment by Oskutin** [comment]
Fixed
