### ISSUE TITLE
Vine plant harvest is broken

### ISSUE THREAD

**Issue by Crlangley** [loiste-interactive/Obenseuer-Issues#569]
![20231001000645_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/65619937/e8391821-83bf-4a4c-bdc7-0e2bffc1abf0)
After picking tomatoes they create seeds for each pick that land on the ground. When i pick them up they don't seem to go into the inventory

**Comment by Oskutin** [comment]
Do tomatoes appear to your inventory at all?

**Comment by Crlangley** [comment]
![20231001000700_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/65619937/684e8ae6-9727-4f2b-9cb2-3e9f9549c660)
Yes but Jomppe won't buy these after picking them.

**Comment by Crlangley** [comment]
![20231001000717_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/65619937/457d7dea-3ce4-4e4e-acdb-df5089095f75)
was able to get cucumbers earlier today, though that plant seemed broken as it got to spoiling much faster than these  and only gave after plant got to 100% spoiled which might be the system here im unsure, but can't tell if these are actually growing or aren't.

**Comment by Oskutin** [comment]
Fixed the buyback issue

**Comment by Crlangley** [comment]
Cabbages also aren't selling to Jomppe

**Comment by Zuntti** [comment]
Fixed
