### ISSUE TITLE
NPC name issue in bar Simppa is called Jomppe in dialog 

### ISSUE THREAD

**Issue by Crlangley** [loiste-interactive/Obenseuer-Issues#571]
![20231001113914_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/65619937/cb8a479e-cc3d-47aa-858f-c3647816fd3a)
![20231001113915_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/65619937/5caf1457-a7c9-444e-8443-e4fb69e1076f)

**Comment by Zuntti** [comment]
Fixed

**Comment by gurka** [comment]
@Zuntti I'll just comment here instead of creating a new ticket - talking to Ulrik Takala shows the name Agnes Takala in the dialog. She is sitting next to him, so maybe this is somehow intended
