### ISSUE TITLE
Prison escape: standup in tight place clip me into ceiling

### ISSUE THREAD

**Issue by Kastuk** [loiste-interactive/Obenseuer-Issues#573]
When you crouching from prison cell into caves, in this particular place with broken wall I can stand and clip out the level.

![20231001150754_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/36314945/5e170123-dbbf-4958-ba60-39156d88aae2)
![20231001150832_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/36314945/41aa742b-1319-4d0e-a7b2-996a60f4bef3)

I will stand automatically, if I tried to jump while crouching before.

**Comment by Zuntti** [comment]
Fixed
