### ISSUE TITLE
Max Masher mushroom farm: respawning shrooms at saveloading

### ISSUE THREAD

**Issue by Kastuk** [loiste-interactive/Obenseuer-Issues#574]
In the shroom farm of Max Masher, green shrooms respawning under any other shrooms.
Initially there's several shrooms planted one under another with different potency.
![20231001233144_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/36314945/45fd4132-6cd0-4f60-aa5a-459d7ae767f6)
I did harvest all green shrooms there. Then i did plant orange shrooms there. then save game, do something with mashers, load game, return to farm and seen fresh spawned green shrooms, several already mature and harvestable.

**Comment by Zuntti** [comment]
Fixed
