### ISSUE TITLE
Not cookable recipes

### ISSUE THREAD

**Issue by Kastuk** [loiste-interactive/Obenseuer-Issues#575]
Cannot be cooked after all ingedients is placed into stove/oven:

Cabbage soup
Glowing onion soup (no shrooms here) 
Meat pie 

Suggestion: mark detected ingredients of recipe, so it will be simple to find what is missed.

**Comment by Oskutin** [comment]
Do you have the cabbage soup recipe collected?

**Comment by Kastuk** [comment]
Yes, all three is presented in inventory and in cooking interface.

**Comment by Zuntti** [comment]
Fixed
