### ISSUE TITLE
Homemade moonshine not return the bottle after drink

### ISSUE THREAD

**Issue by Kastuk** [loiste-interactive/Obenseuer-Issues#576]
Drinking of this consuming the bottle too:
_Carrot moonshine
Brandy
and other moonshines_

I suppose, caused by
**"DestroyAfterUse": true**

This will return the bottle:
Methanol
and wines, which have
**"DestroyAfterUse": false**

**Comment by Oskutin** [comment]
Fixed

**Comment by Kastuk** [comment]
+
Carrot mushroom moonshine
Fecal moonshine
Fecal mushroom moonshine
Whiskey
Rich whiskey
Mushroom whiskey
Mushroom rich whiskey
Mushroom brandy
Applejack
Mushroom applejack
Sahti
Mushroom sahti

**Comment by Oskutin** [comment]
Fixed those also already
