### ISSUE TITLE
Sauna stove lost fuel slot

### ISSUE THREAD

**Issue by Kastuk** [loiste-interactive/Obenseuer-Issues#577]
Bug similar to old ones
#336 
#317 

Sauna in apartments on floor 3 of Dekula A
![20231002210002_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/36314945/f9a06d3e-758c-449e-980d-7db103fd2801)

But there is different error text:

```
System.NullReferenceException
  at (wrapper managed-to-native) UnityEngine.GameObject.SetActive(UnityEngine.GameObject,bool)
  at Slot.HideTradeUI () [0x0000a] in <d170424fcc574ff49611ebc315636dd7>:0  
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

System.NullReferenceException
  at (wrapper managed-to-native) UnityEngine.Component.get_gameObject(UnityEngine.Component)
  at SlotController.CaptureSlot () [0x0001c] in <d170424fcc574ff49611ebc315636dd7>:0 
  at CraftingBase.Enter () [0x00032] in <d170424fcc574ff49611ebc315636dd7>:0  
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)
```

[Sauna lost fuel slot.log](https://github.com/loiste-interactive/Obenseuer-Issues/files/12785201/Sauna.lost.fuel.slot.log)
[sauna miss fuel slot.zip](https://github.com/loiste-interactive/Obenseuer-Issues/files/12785206/sauna.miss.fuel.slot.zip)
(sorry for methanol intoxication blindness)

Got similar bug with mashers, save reload from main menu can fix it, but it cannot fix sauna.

**Comment by Oskutin** [comment]
How to reproduce?

**Comment by Kastuk** [comment]
Random appear, on mashing barrels too.

**Comment by Kastuk** [comment]
Saveload near sauna stove will break the fuel slot.

**Comment by Kastuk** [comment]
Barrel stove of Player tenement makeshift heating have broken fuel slot from very start.

**Comment by Oskutin** [comment]
Does full game reboot help with that (but load the save)?

**Comment by Kastuk** [comment]
Not catched it in new version yet.

**Comment by Oskutin** [comment]
Umm, I'll mark it closed then.
Feel free to re-report if it appears again
