### ISSUE TITLE
Some default settings are off from what was settled before.

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#579]
FOV by default is again 60 instead of the 90
Brigthness is set to low instead of being in the middle
Default inventory tab key is I again instead of Q (which works better gameplay-wise and Q was used only in now-legacy feature).

**Comment by Oskutin** [comment]
Does the issue persist?

**Comment by Kastuk** [comment]
Default brightness is really low for sure.

**Comment by Nextej** [comment]
It only happens on update/fresh game install.

**Comment by Zuntti** [comment]
Fixed
