### ISSUE TITLE
Secondary wielding issues

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#58]
In the Key Binding settings, buttons for Primary and Secondary reloads are reversed, R is for Primary.
![image](https://user-images.githubusercontent.com/44178400/232310984-5b7eb4a0-ac7e-414c-83ea-b068ac0f4e8c.png)

For the secondary wielding, the reload button does not work, neither trying to use the primary assigned one, nor trying to rebind them does fix it, making flashlight currently a single use.

**Comment by Zuntti** [comment]
already fixed
