### ISSUE TITLE
Minor immersive improvement to level transition - closing and opening door sounds + fading out music.

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#582]
For when **after** a loading screen begins, player should immediately hear opening sound, and **once** player loads onto the level, they should hear closing sound. From my long plays, level transition still feels a bit off instead of continous movement, I feel like this would be a neat improvement. Of course some doors would need special sounds, like the transition to and from O-Market or Skeida with them having the sliding doors.

Another thing are the level that have a music on, you're transitioning away from. Upon loading start, the music is still heard but after few seconds fades immediately. Would be better if it faded out gradually after playing the door opening sound (well, that goes for all the sounds from that level the player can hear when leaving the level).

**Comment by Kastuk** [comment]
Door sound will be nice to hear to mark that location is loaded.

**Comment by Oskutin** [comment]
Implemented
