### ISSUE TITLE
Player placed radio sound radius has too sudden fade out.

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#583]
There's actually two problem:
1. Horizontally the radio is heard well until the sound drops drastically at the edge of the radius instead of being more gradual.
2. Vertically, radio is heard too well, so being one floor or even two above player's tenement feels off hearing the music well, would be better if vertical range was smaller or the fade was quicker to sound muffled.

**Comment by Zuntti** [comment]
Adjusted radius and volume. Also now sound is added to the soundscape
