### ISSUE TITLE
Jail - taken (player's) inventory is not being stored in the lockers, instead a random owned items spawn in them.

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#584]

**Comment by Kastuk** [comment]
At least, after I been catched two times at escape attempts (exit the opened cell at the end of timer, unlock the cell while guard is awake), third time I did crawl around sleeping guard and unlick all storages, did not find any my items.

**Comment by Zuntti** [comment]
It's a bit confusing that there are two white lockers next to them
![lockers](https://github.com/loiste-interactive/Obenseuer-Issues/assets/5405170/2d5e6d79-dfdf-47bd-b71c-ff75e5942e20)

**Comment by Zuntti** [comment]
Now it clears the storage only when you have left from the exit door. Also changed two white lockers to something else and made it more visible where the cell stuff is
