### ISSUE TITLE
Sorting Deletes Player Inventory

### ISSUE THREAD

**Issue by steven-fontaine** [loiste-interactive/Obenseuer-Issues#585]
#Sorting Deletes Player Inventory

##Issue Location: Player Tenement
##Game version: Playtest 0.3.09
##Video of issue: https://youtu.be/yxxVUqlKzsk

##Issue Description:

After opening a freezer, selecting  "Take All" in the freezer menu, and then sorting the player inventory, all items were deleted from the player inventory

[Uploading Player.log…]()

**Comment by Oskutin** [comment]
Already fixed
