### ISSUE TITLE
Suggestion: harder safecodes

### ISSUE THREAD

**Issue by Kastuk** [loiste-interactive/Obenseuer-Issues#586]
For now several safes in playtesting version is too easy to unlock, as code is written cleanly right nearby. So it feels like cheat to obtain valuable items inside such easily.

My proposals to make it more interesting challenge.
Separate code by parts:
- one part to place randomly in one of locked containers. So it need enough skill.
- one part to be placed high on top of furniture. So it need sharp eyes, furniture climbing and flashlight.
- one part to be written on wall just like now.
Optionable: this hint will be visible only when you got high enough colourful sight by mushrooms. So it need to use shroom consumables and not just ignore any glowing food.

Some hardcore codes can be ciphered as normal signs on devices just like INFRA ARG messages.

All to make it not easy to got all treasures at very first visit until you explore it fully.

**Comment by Oskutin** [comment]
I guess this counts as implemented now, as new safes are with much harder codes
