### ISSUE TITLE
Several minor suggestions

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#59]
1. Default settings: I feel like the default setting of FOV and mouse sensitivity should be changed. It seems like somewhere within 80-90 fits the best for other people, I personally use 90 and it made the game way more comfortable to me than using default 60. As to mouse sensitivity, while others seemed to be fine with default setup, I had it turned up to 14,00 and it's one of the rare examples of games I actually had changed mouse sensitivity, because it almost always was perfect to me, would probably require more feedback from others and finetuning to find the most appropriate default value, if any other than the current one is.
2. Defecation sound effect: I'd personally would like it having toned down and not be that "aggressive", maybe as an overall change, maybe as some setting to choose from, or maybe depending on the % of Bowel and Bladder the sound would change.
3. Bring back the old Open Sewer theme, possibly in a form of available radio music, or maybe as an acoustic version that can be played on a guitar as one of the songs, or maybe both. But I'd really appreciate having it to accompany the tone of the game.

**Comment by Oskutin** [comment]
3 is done.

**Comment by Zuntti** [comment]
Adjusted defecation sound effect
