### ISSUE TITLE
Some map change doors 'vanish' for a second when using

### ISSUE THREAD

**Issue by Oskutin** [loiste-interactive/Obenseuer-Issues#594]
![kuva](https://github.com/loiste-interactive/Obenseuer-Issues/assets/5402150/ffe9359c-eeb4-4719-8e2a-e4125af54685)

Actually, it's still there but rotated 180
![kuva](https://github.com/loiste-interactive/Obenseuer-Issues/assets/5402150/555d24f2-fefc-4d6c-9291-cf08a531dcd5)

**Comment by Oskutin** [comment]
Some are fixed, but there may still be other doors like this

**Comment by Kastuk** [comment]
Door from Redemption Militia scene.

**Comment by Nextej** [comment]
Applies to the Interior General Store exit doors.

**Comment by Oskutin** [comment]
General Store and Greenhouse is fixed

**Comment by Oskutin** [comment]
Fixed
