### ISSUE TITLE
Lockpicking needs some reworking.

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#595]
This is my list of thing I feel should change about lockpicking, both the lockpicks are too easy to get in larger quantities and the whole level too easy to quickly pick the whole thing is almost obsolete on a second day.
1. Crafting requires having a recipe, the one crafted from scrap can be found randomly in mail, the one crafted from sheets requires finding it in obscure location or doing a dedicated quest
2. Successful pick has high chances of breaking the lockpick anyway, the better the lockpicking skills, the less chances of it breaking during, and only, a successful pick, a failure always breaks the lockpick, no matter the level
3. Certain locked objects should have some "importance" value, within few days a broken lock will be replaced by a new harder one, depending on the importance, some objects won't have replaced lockers at all (suitcases or lockers that spawn crappy items), some objects will take within a week of being replaced to the same difficulty of lock (basement storages) and some objects will get locks replaced within 1-3 days to a higher level of difficulty (apartments)
- this is notable on the outdoors level, where you can quite easily access an alternative route to your tenement by crafting a lot of lockpicks and surprisingly easily beat the high difficulty of locks, bypassing the toll booth, having that relocked within 3 days seems reasonable.
4. Lockpick crafting failchance should be increased for each recipe, perhaps so it is increased by 100% or 150% on no machining crafting skills of the current values on that level.

**Comment by Oskutin** [comment]
4 = done
5 = done

**Comment by Oskutin** [comment]
Auto locking doors with increasing difficulty is implemented
