### ISSUE TITLE
Changed the displayed name of Open Sewer Tenement level to "Outdoors" or "Outside" to indicate clearer when the doors from one map lead to the outside, displayed "Open Sewer" or "Obensuer" might be confusing.

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#597]

**Comment by Nextej** [comment]
Actually, when being in any of the Deekulas, it would be nice to have the exit doors display something like "Outdoors (West)"/"Outdoors (western exit)" and "Outdoors (East)"/"Outdoors (eastern exit)"

**Comment by ontrigger** [comment]
+1

**Comment by Oskutin** [comment]
Doing this would get even more confusing once bazaar is out
