### ISSUE TITLE
Controls: Can't select phone call or clear buttons

### ISSUE THREAD

**Issue by Zuntti** [loiste-interactive/Obenseuer-Issues#6]
![Phone](https://user-images.githubusercontent.com/5405170/229507895-321bf7bd-b45b-4884-9f21-83bb1fa53bef.png)

Maybe add own buttons for gamepad and keyboard too

**Comment by Oskutin** [comment]
> Pressing X at the phone types the number 1
> Pressing P at the phone closes the phone menu and makes the screen go fuzzy
