### ISSUE TITLE
Caravan messes up player movement

### ISSUE THREAD

**Issue by gehube** [loiste-interactive/Obenseuer-Issues#603]
I went inside the caravan outside deekula a and it spawned me through the ceiling, now the player gets stuck on the slightest imperfections on the ground and can even go through certain things
![20231020183035_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/130682887/a6cbe54d-6c1a-43ab-a3f0-140dc8ded5dd)

**Comment by Oskutin** [comment]
Also this is already fixed
