### ISSUE TITLE
Whoever nerfed Cupboard storage to be 2x(8x2), for the love of god, please revert it back to the 2x(8x3)

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#604]
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/84273ff0-c228-420b-80d2-f0e7b873b32e)
...

**Comment by Zuntti** [comment]
Changed bottom to 8x3

**Comment by Nextej** [comment]
You're not making me happier enough Zuntti...
