### ISSUE TITLE
Incompleted food stats

### ISSUE THREAD

**Issue by Kastuk** [loiste-interactive/Obenseuer-Issues#605]
Have Material null and Type None, not give nutrition:
11070 Sawdust White Bread 
11080 Glowing Sawdust White Bread
10660 Glowing Multigrain Bread
11090 Sawdust Multigrain Bread
11100 Glowing Sawdust Multigrain Bread

Not spawn a bowl by consumption:
11150 Glowing Onion Soup
11160 Vegetable Soup

Have empty "Meta": [] at end, so not spoilable:
14210 Boiled Rice
10640 Pea Soup
11150 Glowing Onion Soup
11160 Vegetable Soup

Have wrong Meta, not spoilable too:
26870 Sausage Soup
26871 Glowing Sausage Soup

**Comment by Oskutin** [comment]
Fixed
