### ISSUE TITLE
Kinda broken market stalls

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#606]
- When player is on the map and the time passes (sleeping), during the day a random amount of stalls will be open for business, but not all i seems, they all normally close for the night
- Map transition/reloading causes all stalls to close
- Sleeping outside the Tenement Open Sewer map and then entering it seems to almost always only open Kurahaara's stall, regardless of the time of the day
[Player.log](https://github.com/loiste-interactive/Obenseuer-Issues/files/13060686/Player.log)

**Comment by Nextej** [comment]
It actually doesn't seem to be the case entirely, first of all it affects market stalls, general store and mail system (potentially Deekula A blueprints too). I've managed to get it to work on my main save by sleeping in one location for 36 (which cheats), then for a moment on another try on the same save after sleeping just 8 hours to wake up around 12:00 midday, it started to work at one point after visiting and exiting Deekula A, further reloading attempts didn't copy the effects.
[Player.log](https://github.com/loiste-interactive/Obenseuer-Issues/files/13060964/Player.log)

**Comment by Kastuk** [comment]
At my savegame is only Alcohol stall is working in next day, nothing in first day.
There's two game sessions from start.
[Kastuk day 1.log](https://github.com/loiste-interactive/Obenseuer-Issues/files/13061443/Kastuk.day.1.log)
[Kastuk day 2-3-4.log](https://github.com/loiste-interactive/Obenseuer-Issues/files/13061442/Kastuk.day.2-3-4.log)
And two saves, one at begin, where stalls is closed (slot 3) and one somewhere later, when stall is opened (slot 7).
[Outin_Looker.zip](https://github.com/loiste-interactive/Obenseuer-Issues/files/13061455/Outin_Looker.zip)

**Comment by Oskutin** [comment]
```
System.NullReferenceException
  at (wrapper managed-to-native) UnityEngine.GameObject.SetActive(UnityEngine.GameObject,bool)
  at Slot.HideTradeUI () [0x0000a] in <9c895edcd8024e5db8ac2c419b005719>:0  
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)
```
Oh yes, the mystery null ref

**Comment by Oskutin** [comment]
Managed to reproduce

**Comment by Oskutin** [comment]
Fixed
