### ISSUE TITLE
Backpack slot amount nerf

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#607]
Currently it seems like the backpack is a bit too overpowered, it has basically an amount of 2 regular chests, 2x(8x3), while useful it feels way too much, I think it could be reduced to just 8x3 or even 8x2, actually I'd try out 8x2 first and see how it plays in the playtest and if needed, increase it to 8x3. Also I think it's a little to easy to find a backpack in early game, I've found two owned ones and one available to buy at General Store, feels like it should be more exclusive or harder to find, more expensive even.

**Comment by Oskutin** [comment]
Nerfed
