### ISSUE TITLE
Player tenement - new starting blueprints positions

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#608]
I'd like to rearange several of the starting blueprints found in the player tenement.

- Wooden Chest should be found in Apartment 5's small room, here:
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/95d8c50e-a5a7-4332-b8be-13c9ba2950a0)

- Wooden Pallet should be either replaced with Wooden Cupboard storage, also in the Apartment 5, here:
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/981d1a31-4dd8-48bf-9f46-5f41bba1cf94)

- Wooden Half Pallet should be replaced with Wooden Pallet, in the Apartment 3, here:
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/119a4592-865f-4623-9302-4f5147891eb5)

- Wooden Chest should be replaced with Wooden Pallet in the Apartment 6, here:
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/bbe98aee-d4c1-4caa-b639-f4e5a137f86d)

- Out of notable starter items, a bucket toilet might be usuful to add, I'm also thinking of either of the farms, but I think the chances of having a farm to buy should be just higher.

**Comment by Kastuk** [comment]
I has been sure that blueprints content is randomised.
Also, this makeshift toilet need a days of renovation.

**Comment by Oskutin** [comment]
Reduced bathroom construction time for early stuff
