### ISSUE TITLE
Cooking and its practical uses

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#61]
Currently trying to cook anything rarely gives you any output other than ash, which leads to massive waste of food, in this exampled run only 6% of all the food I've gather was cooked properly, rest turned to ashes, however it seems that on all of them, a fail chance was only 17% (unless that's not what it means).

The word "chance" (if that's it) is also misspelled as "change"
![image](https://user-images.githubusercontent.com/44178400/232335805-8e4259aa-33c9-4f4b-9bb1-2eedc7a01e4c.png)

Anyway, it makes cooking pretty much useless at this point. It would be nice if besides getting just ash, player was just getting lower quality of food, like a burned steak, that's on its own should be at last better to not give player poisoning (if such even is in this game, I dunno really what are the consequence of eating untreated or rotten food). At early stages player should get any-to-zero benefits from trying to cook food, but currently it is pretty much a waste every time, making it not worth the effort in the first place, while it should be worth anything.

**Comment by Zuntti** [comment]
Fixed
