### ISSUE TITLE
Entering the caravan causes the players walk cycle to be messed up

### ISSUE THREAD

**Issue by TiaLinna** [loiste-interactive/Obenseuer-Issues#611]
As I entered the Caravan, outside O-Mart, I spawned into a wall, and after I got myself unstuck, it felt like my character was constantly walking crouched down, and when I stood up, my character would walk like.. few meters normally, and then crouch again, until I entered another building. And then the walking cycle would return to normal.

**Comment by Oskutin** [comment]
Already fixed
