### ISSUE TITLE
Items that need higher chances to get (not necessary to find, but perhaps to buy)

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#613]
- Nails, even with General Store and Hardware stall working, the limited amount of nails you can buy is annoying in compare to how useful and required they are in crafting and renovation, I think a 50%-100% increase in the amount you can see at a store would be good start.
- Gas bottles, extremely rare to find, not common to see in the store, I think the chances should increase about 25%-50% for them to be available to buy, alternatively the chances and the amount of them being available to buy could be modified by the amount of furnaces the player has.

**Comment by Kastuk** [comment]
May be nice to refill gasbottles by homemade biogas from fermented feces and other compostables.

**Comment by Oskutin** [comment]
Gasbottles and nails are more common in the stall
