### ISSUE TITLE
Doctor have blank page at physical health measurement

### ISSUE THREAD

**Issue by Kastuk** [loiste-interactive/Obenseuer-Issues#614]

**Comment by CBS-S** [comment]
![20231026223114_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/86502239/f9a8eac9-cf72-478a-8118-663c48652af8)

I was going to file my own report and saw this was already here. Nothing on the pop-up menu here is clickable, aside from other exam options.

**Comment by Zuntti** [comment]
Fixed
