### ISSUE TITLE
Glowing food give intoxication

### ISSUE THREAD

**Issue by Kastuk** [loiste-interactive/Obenseuer-Issues#616]
Most of glowing food give alcohol intoxication instead of mushrooms high:

14001 Glowing sausage
20311 Cup of mushroom coffee
24101 Glowing rye bread
24106
26021
26026
26031
26036
26041
26046
26051
26056
26715
26716
26725
26726
26735
26736
26745
26746
26755
26756
26765
26766
26775
26776
26785
26786
26811
26821
26826
26831
26836
26851
27111
27116
27121
27126
27131
27136
27141
27146
27151
27156
27161
27166
27171
27176
11630
11640
11670
11680
11710
11720
11750
11760
11790
11800
11830
11840
11870
11880
11910
11920
11950
11960
11990
12000
12030
12040
12070
12080
12110
12120
12150
12160
13620

May be okay, but these mostly have none effects (deep heating?):
26871 Glowing sausage soup (no effects, except depression-)
13650 (same)
10870 (no effects)
11180
13581
13600
13660
13730
13750
But vegetable and onion soups have normal glowing effects.

Two without effects, except huge infection:
11030 Glowing Pea Soup (+5% of SMV!)
13670 (same)

Glowing breads has no difference with normal ones:
11060
11080
10660
11100

**Comment by Oskutin** [comment]
Fixed
