### ISSUE TITLE
Tablesalt consumed as whole bottle per recipe, not charges

### ISSUE THREAD

**Issue by Kastuk** [loiste-interactive/Obenseuer-Issues#617]

**Comment by Oskutin** [comment]
What recipes?

**Comment by Kastuk** [comment]
Wheat dough
Snashed potatoes
Steak with fries
...

**Comment by Oskutin** [comment]
Uh, not sure if I fixed them already, as in recipe editor they look correct.

**Comment by Oskutin** [comment]
Or that the entire system for using charge as input is broken

**Comment by Oskutin** [comment]
Fixed
