### ISSUE TITLE
Two bugged toilets

### ISSUE THREAD

**Issue by Kastuk** [loiste-interactive/Obenseuer-Issues#621]
Outside - toiled behind Player Tenement.
If you sit, you will stuck inside and cannot stand up. Loading a game - you cannot sit anywhere, only Stand Up action is shown.

Container shack interior - wooden toilet inside not give relief by sitting.

**Comment by Oskutin** [comment]
Outside is fixed

**Comment by Oskutin** [comment]
Fixed
