### ISSUE TITLE
Repeating error at exit the Market

### ISSUE THREAD

**Issue by Kastuk** [loiste-interactive/Obenseuer-Issues#622]
After exit the Market fps got drop down and repeating error about stopped coroutine of npc sit action is appear in console.
After some actions (maybe talking with sitting npc) error did stop reappear and fps normalized.
![repeating_error__toilet_stuck.zip](https://github.com/loiste-interactive/Obenseuer-Issues/files/13120172/repeating_error__toilet_stuck.zip)

Theres also toilet stuck error which already fixed.

**Comment by Oskutin** [comment]
#620 The error seems to be the same
