### ISSUE TITLE
Vivi Bondar softlock

### ISSUE THREAD

**Issue by CBS-S** [loiste-interactive/Obenseuer-Issues#625]
It's possible to jump up the side of the tent behind Vivi Bondar and then fall down the other side, where you can move around but then softlock the game by falling into a spot you can't move from.

![20231025004711_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/86502239/15806f46-454a-48da-96bf-82c0a3d3fdb4)

**Comment by Oskutin** [comment]
What is the spot specifically?

**Comment by Oskutin** [comment]
Fixd
