### ISSUE TITLE
Radio Signal task, Amanda dialogue issues

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#63]
After finding a body and reporting back to Amanda, we can decided whether to inform a police, choosing no to still allows to report the body when calling 112, but when asked for the address, there's not other dialogue option on our part but to end the call.
![image](https://user-images.githubusercontent.com/44178400/232483009-d0c08347-b50b-4f1a-bf2d-ecf63834ac82.png)
https://user-images.githubusercontent.com/44178400/232483032-17ef5988-8e6d-4c99-a1f0-77e0d3c16f56.mp4

Additionally we can say that we think it's a man two times, before and after deciding to not report to the police. And after a second time, the conversation either ends or we have a chance to tell Amanda about woman in bed if we haven't yet, which doesn't makes sense given the context of "what are we going to do now?"
https://user-images.githubusercontent.com/44178400/232483867-8c1b4f71-35d5-44f1-b424-33c1a16f5a60.mp4

**Comment by Nextej** [comment]
Turns out you can report a dead body anytime to the police, even outside the quest, resulting in the same outcome as above.

**Comment by Zuntti** [comment]
Fixed
