### ISSUE TITLE
Fidan Tanner keeps changing

### ISSUE THREAD

**Issue by CBS-S** [loiste-interactive/Obenseuer-Issues#630]
Every time you walk into the Redemption Militia, Fidan's appearance changes. If this is deliberate then it's very funny, but if not then it's a bug you should know about.

![20231025234140_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/86502239/84449ab7-1495-4258-abbf-c13e390b7a62)

**Comment by CBS-S** [comment]
![20231025234211_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/86502239/ffbf4e07-861e-4a66-9a40-33f8ed89a358)

**Comment by CBS-S** [comment]
Actually Kaisa Wirta on the second floor does this too, it's just not as obvious because he's not the first thing you see each time you enter the building.

**Comment by Oskutin** [comment]
this is already fixed
