### ISSUE TITLE
No sound while walking sideways at barrier fence

### ISSUE THREAD

**Issue by CBS-S** [loiste-interactive/Obenseuer-Issues#634]
![20231025235718_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/86502239/7c95984b-d82e-4923-8e1f-8f21af292f24)

Footsteps play normally if you walk back and forth here, but if you slide along the fence - using the strafe keys either alone or with forward/backwards - there's no walking sound.

**Comment by Zuntti** [comment]
Fixed
