### ISSUE TITLE
Can't use crumpled paper for food

### ISSUE THREAD

**Issue by CBS-S** [loiste-interactive/Obenseuer-Issues#635]
Honestly I might just be misunderstanding something here, but it *seems* like I should be able to use this paper to cook this rat, but I can't.

![20231026000644_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/86502239/59f98881-41b9-4fee-b6d5-e123a9c96765)

**Comment by CBS-S** [comment]
This is at the campfire right outside Deekula B. I got the paper out of the trash cans next to the door.

**Comment by Kastuk** [comment]
Just havent fuel slot.

**Comment by Oskutin** [comment]
https://github.com/loiste-interactive/Obenseuer-Issues/issues/577
