### ISSUE TITLE
Deekula B Hammock

### ISSUE THREAD

**Issue by CBS-S** [loiste-interactive/Obenseuer-Issues#636]
The hammock outside the door to Deekula B has no collision. It would also be nice if you could use it for sleeping, but that's a request, not a bug.

![20231026001445_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/86502239/d2503133-4c30-4a03-9a77-6670f017fe30)

**Comment by Oskutin** [comment]
Fixed
