### ISSUE TITLE
Mold at Militia

### ISSUE THREAD

**Issue by Kastuk** [loiste-interactive/Obenseuer-Issues#638]
Theres mold placed on table where bowl of peasoup has been.
Also red man at table is eating mold now.
![20231026205254_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/36314945/fbe68666-5a3e-4c41-86f8-3388dd031340)

**Comment by CBS-S** [comment]
I think the guy eating mold is funny but I would like having that free bowl of soup back too.

**Comment by Oskutin** [comment]
fixed
