### ISSUE TITLE
Player still gets hurt from the body bathtub after gathering all the mushrooms, seemingly leaving no physical harm.

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#64]

**Comment by Nextej** [comment]
I thought of this too, but for the sake of a game, it seems unintuitive, especially since in other instance, picking up mushrooms (like Max Masher's plant) removes the harming space. 

I'd suggest then having maybe particles to float around or have some smaller unpickable shrooms in the corners of the bathtub, I'd also make the whole hurt zone a bit smaller, since it seems to be kinda to big if you were to try to talk (I'm aware the harm effect was disabled in other side and you can talk only there, but it's again about intuition of that you should not get closer to it at all).

**Comment by Zuntti** [comment]
Fixed
