### ISSUE TITLE
Weird issues with new fog

### ISSUE THREAD

**Issue by CBS-S** [loiste-interactive/Obenseuer-Issues#641]
![20231026220219_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/86502239/bcfc4308-1db7-4409-b3db-d86de9e1094c)

I think there's something wrong with the Z buffer? You can see dark spots, like the Lada headlights and the far wall, where the fog doesn't render.

**Comment by CBS-S** [comment]
This mostly seems to happen with glass, but there are also places where it's drawing stuff that I think is supposed to be invisible. This cube disappears as you get closer, for instance.

![20231026220945_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/86502239/c205bf3b-815d-4219-a157-27a42fc026d3)

**Comment by Oskutin** [comment]
Already fixed
