### ISSUE TITLE
"Excuse me, lady."

### ISSUE THREAD

**Issue by CBS-S** [loiste-interactive/Obenseuer-Issues#642]
![20231026220425_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/86502239/8f4b32b7-f4a8-43c3-a20d-919d905135e4)

I set the character gender to male (at least I think I did) but she addresses me as "lady."

**Comment by Kastuk** [comment]
Also drunk guy sitting near market.

**Comment by Zuntti** [comment]
Fixed
