### ISSUE TITLE
General graphics feedback

### ISSUE THREAD

**Issue by CBS-S** [loiste-interactive/Obenseuer-Issues#643]
Putting this here in the off chance any of these are bugs, although I think it's more likely they're personal preference issues.

- I think the new fog is too strong. I'd lighten it up unless you plan to use it to help with draw distance, since I'll admit I'm not pulling a steady 60FPS when I look around outside.
- I also think the bloom when you look around is too strong. I find it distracting rather than immersive.
- The fuzzy effect that plays when you've drunk booze toggles on and off rather than fading smoothly in and out.

**Comment by Oskutin** [comment]
Fog is randomized weather.

**Comment by Oskutin** [comment]
Reduced fog intensity
