### ISSUE TITLE
Prison Escape, clip into ceil at standup in tunnel

### ISSUE THREAD

**Issue by Kastuk** [loiste-interactive/Obenseuer-Issues#644]
Same as #573 
Got similar stumbling almost in same place but slightly deeper.
You need try to standup or jump while crouching on the way here in any direction.
May stumble on something and become pushed cross the wall.
![20231027011015_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/36314945/f1e66a02-c79f-47eb-b7c6-441b2a9394cc)
![20231027011042_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/36314945/f34ba670-a397-45c3-9b2b-0ba759fd3970)
![20231027011047_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/36314945/07fa80f9-734e-473f-81ec-4d063ce6f3b0)
![20231027013958_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/36314945/899bbda1-eee2-41fc-8d37-be0cef01bc91)

**Comment by Kastuk** [comment]
I suppose it may trigger if you're switch to sprint mode when crouching and start run immediatelly when stand up in tunnel.
Can also be pushed into wall and drop under floor in same place.
![20231027013913_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/36314945/9f588b8a-698d-40c1-b47d-a0f29bb8ff96)

**Comment by Oskutin** [comment]
fixd
