### ISSUE TITLE
Can't legally buy painkillers

### ISSUE THREAD

**Issue by CBS-S** [loiste-interactive/Obenseuer-Issues#646]
I stepped in a bear trap and went to the pharmacy. I took two boxes of "Ibuats" to the counter, the clerk rang them up, and they passed to the other side. But no money was deducted from my funds (which were sufficient) and the door alarm went off when I tried to leave. I ran through this several more times and got the same result.

**Comment by CBS-S** [comment]
Update: I went back with two packs of sleeping pills and for some reason that completed the *prior* transaction, making the painkillers mine. I do not own the sleeping pills, however.

**Comment by Oskutin** [comment]
Did you took the pills straight from counter or pressed the cash register to pay them?

**Comment by CBS-S** [comment]
Having tried it again, I think it was my mistake not realizing that I had to press the register after the scan.
