### ISSUE TITLE
Autosave not working

### ISSUE THREAD

**Issue by CBS-S** [loiste-interactive/Obenseuer-Issues#648]
I spun up a new character for the latest build and ended up dying without saving. I tried to load an autosave and discovered there weren't any. I had played for about an hour and completed at least the pea soup quest.

**Comment by Oskutin** [comment]
This is likely caused by the character name having '-' character

**Comment by Kastuk** [comment]
Wrong named characters still create folder and savegames, just autoselection in Load menu will select first default character instead and you must switch chars to find your one.

**Comment by Oskutin** [comment]
Yeah, its just a UI bug

**Comment by Oskutin** [comment]
Fixed
