### ISSUE TITLE
Steal +0 not rated crimes

### ISSUE THREAD

**Issue by Kastuk** [loiste-interactive/Obenseuer-Issues#649]
Can drink or steal all bottles in Alcohol stall behind owner. He cannot see most of containers behind his back, but when he can, it's just +0 level crimes.

Same at hacker room, you can steal under his nose and it's just +0 rated crime.

**Comment by Kastuk** [comment]
Same at the cash register of Kalpana the Canner

**Comment by Oskutin** [comment]
Fixed
