### ISSUE TITLE
Controls freeze after talking to Jonasson

### ISSUE THREAD

**Issue by SpewkyGoast** [loiste-interactive/Obenseuer-Issues#651]
When talking to Jonasson for the first time after Malone tells you to speak to him; the controls get stuck in dialogue mode after the objective registers as complete. Can't even open the pause menu, happens every time I finish the conversation with him.
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/149126180/38c22ece-a526-48f3-b55e-dbca8fea631a)

**Comment by Zuntti** [comment]
Doesn't seem to happen to me. Can you give a save file where this happens?

**Comment by SpewkyGoast** [comment]
Just the autosave-
[Into_Perkele.zip](https://github.com/loiste-interactive/Obenseuer-Issues/files/13189209/Into_Perkele.zip)

**Comment by Kastuk** [comment]
I wonder what is in console there.
If you didnt run game more, try to bring player.log from 
DocumentsOrWhatever/Name/AppData/LocalLow/LoisteInteractive/Obenseuer

**Comment by Zuntti** [comment]
The task panel causes it. Opening task panel before talking to Jonasson fixes it

**Comment by Zuntti** [comment]
Fixed
