### ISSUE TITLE
White void screen in sauna door

### ISSUE THREAD

**Issue by Kastuk** [loiste-interactive/Obenseuer-Issues#655]
I got explored Kolholla with unlocking doors around and in apartment A11 gonna jump around sauna and when I touched glass door,  screen did turned to white fast but smoothly.
I did have several moderate needs and critical alco-need and god_mode activated.

Before
![20231027132641_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/36314945/73d15e31-e6cf-4d12-b0b8-cdd338f79843)
After bug
![20231027132844_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/36314945/bd3bd874-88cd-4042-8d55-7f6a1e84c19a)
[white void in sauna door.zip](https://github.com/loiste-interactive/Obenseuer-Issues/files/13188504/white.void.in.sauna.door.zip)

Cannot reproduce it just by coming there and jumping around, even if sauna is turned on. Maybe related to simultaneous screen effects of needs.

**Comment by Oskutin** [comment]
Can't reperoduce it neighter. Fromt the log it just seems that the camera has just exploded
