### ISSUE TITLE
Conflicting liquid volume info in Teuvo's

### ISSUE THREAD

**Issue by CBS-S** [loiste-interactive/Obenseuer-Issues#659]
The thumbnail images and tooltip info for the various products Teuvo sells often conflict with each other. For instance, "ale in a plastic bottle" has a thumbnail that says 0.5L, and the tooltip text says that it's a bottle that contains 0.5L but also that you're getting 1.5L.

If I have to guess, this is because the vessel and its contents have different descriptions, so a 0.5L bottle is what you'd be left with if you bought and drank it, but it's still confusing.

**Comment by Oskutin** [comment]
Did you get 3 bottles?

**Comment by Kastuk** [comment]
May it be 3 bottles of 0.5 is stacked?

**Comment by CBS-S** [comment]
I'll check next time I boot the game.
