### ISSUE TITLE
Getting stuck in the elevator pit 

### ISSUE THREAD

**Issue by TiaLinna** [loiste-interactive/Obenseuer-Issues#664]
![20231028193530_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/130680276/d7ffb6ae-0a87-4da2-b9fd-ab47b54954ba)
![20231028193531_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/130680276/65766b30-2f31-4e05-86ca-f017a5bf0197)

The elevator is broken, called it from 1st floor to 3rd floor, it went all the way up to 5th/6th floor, the door to the elevator was open in the 1st floor and I jumped in and got stuck, no way to get back up expect loading the save

**Comment by Oskutin** [comment]
Did you first go to some floor with elevator, and then go to another map or save/load?

**Comment by TiaLinna** [comment]
Nope, I just called the elevator, it went past me. I tried it again by exiting the building and going back in, and same thing happened

**Comment by Oskutin** [comment]
On what floor did you call it?

**Comment by TiaLinna** [comment]
From 1st floor to 3rd floor

**Comment by Oskutin** [comment]
Fixed
