### ISSUE TITLE
Standing up under a staircase

### ISSUE THREAD

**Issue by TiaLinna** [loiste-interactive/Obenseuer-Issues#665]
![20231028193400_2](https://github.com/loiste-interactive/Obenseuer-Issues/assets/130680276/f595e7d3-ff3f-46dc-ab5e-eb15d06c5c88)
![20231028193402_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/130680276/c1c5155b-fbaa-4880-91a0-5ad70a436699)

I managed to stand up under a staircase and my screen started to go spaz out completely, until I crouched back down

**Comment by Oskutin** [comment]
Seems to be save load thing?
