### ISSUE TITLE
Inconsistant weather on loading from save

### ISSUE THREAD

**Issue by CBS-S** [loiste-interactive/Obenseuer-Issues#666]
I saved at in-game sundown last night and came back today. When I reloaded the save, it was raining, which it hadn't been before. When I reloaded it again (without restarting the game) it went back to being clear, and stayed that way through many subsequent deaths (in a separate issue I'll file as a separate ticket). I closed the game, reopened it and it was raining again. Reloaded the level and it was clear again. Quit and restarted a third time, it was raining, jumped off a building and died. When I reloaded it was clear again. So it always rains when I boot the game from this save and then it's always clear when I load the save a second time.

**Comment by CBS-S** [comment]
Just thought to try it from the main menu. Weirdly, that also starts me with rain.

**Comment by Oskutin** [comment]
Looks like weather state is not saved at all

**Comment by CBS-S** [comment]
Huh. Why is it always rain or clear, then? I only ever got those two conditions, never fog.

**Comment by CBS-S** [comment]
I stand corrected, I did it again and got clouds this time. Huh.

**Comment by Oskutin** [comment]
I think I got it fixed
