### ISSUE TITLE
Rooftop access

### ISSUE THREAD

**Issue by CBS-S** [loiste-interactive/Obenseuer-Issues#667]
I can't tell whether this is a bug or not, but I have some feedback.

On the roof of the unnamed tenement there's a section of chain-link fence that's been pulled away, which allows you access to the ledge.

![20231029023131_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/86502239/85c30409-3002-499e-af11-e0379b347b2b)

This access lets you drop down in three separate places you otherwise can't reach, as far as I know. The roofs of the plaza stalls, the top of the timber-frame building next to the militia soup kitchen, and the roof of Eija's Grill. The first two don't really matter because they're essentially islands in the middle of Obenseuer and you can drop back to street level without getting stuck or needing to die (as long as you're careful). Eija's is different.

![20231029022218_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/86502239/49b67f28-3b8f-4d56-b78f-dd351679f493)

From the roof of Eija's (thank you for the vodka and teddy bear, by the way) you can do four things that, as far as I know, you can't otherwise do:

1. Drop down to the porch that overhangs the canal, which is a softlock
2. Drop behind the green tarp building to where the wheelbarrow is, which is also a softlock
3. Drop into the canal, which is death by drowning, which I love
4. Walk the razorwire, sustaining injury and laceration but not dying immediately

Following the razorwire and testing where the player clip walls are lets you actually get to the other side of the closed road and drop down there, which is another softlock, or the canal walls, same deal (although at least you can jump into the canal to die).

The easiest way to fix this would be to just close off the ledge by making the fence continuous. That would fix everything. **BUT!** I really hope you don't do that, because I've realized that coming up here is my favorite part of the game. I've done 15 hours of playtesting and coming up here, to watch over Obenseuer like I'm crap Scandanavian Batman, is by far my favorite part. It's peaceful. It's beautiful.

![20231029025241_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/86502239/44f748f2-5a4f-4b2f-a052-bfe8d778cc87)

I'm reporting this because I've found what are arguably bugs, but truthfully I hope you leave things exactly like they are. There is a certain kind of player, myself included, who likes trying to boundary break. It's added value to them, and I haven't found anything here that's game-breaking. You'd just have to reload from a save. I feel like the sort of person who feels the need to try this will be smart enough to save before they try jumping over razorwire into a canal.

If you feel the need to fix this, you could just put something on the ledge to stop the player from jumping to Eija's. I'd be sad I couldn't have the teddy bear and the vodka, but I'd still be able to go up there and brood, which is like 80% of the experience.

**Comment by Oskutin** [comment]
Not a bug, you can even access some easter eggs from there.

**Comment by CBS-S** [comment]
Huh, I didn't know you could get out when the stall opens, I was doing this at night and never waited for daytime. I'm glad you don't see this as a bug either.

**Comment by Oskutin** [comment]
Fixed the OOB

**Comment by Kastuk** [comment]
I like climbing to unusual places in any games, it will be nice to got some rewards ther except just observation point.
Like reach second floor in Deekula A from that outer door, which is not easy to reach from the ground.
Also I hope for opening of roof access from Dekula B. Its been my favorite place in old version.
