### ISSUE TITLE
Bugged door in Kolhola A9

### ISSUE THREAD

**Issue by CBS-S** [loiste-interactive/Obenseuer-Issues#670]
This door in the A9 suite on the Kolhola fifth floor changes from "open" to "closed" in the prompt when you interact with it, but doesn't do anything else, even make the stuck door sound that unopenable doors usually do.

![20231029033200_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/86502239/c3215645-ef53-43eb-bfc4-6e773e624d0d)

**Comment by Oskutin** [comment]
Fixed
