### ISSUE TITLE
Duck Hater achievement earned after creating a new character

### ISSUE THREAD

**Issue by GreyGoldFish** [loiste-interactive/Obenseuer-Issues#671]
- Describe the issue as accurately as possible, like where and when does it happen

You can get the Duck Hater achievement by getting addicted to ducks and then creating a new character.

- Describe how to reproduce the issue

1. Get addicted to ducks.
2. Create a new character.
3. Possibly also load a previous save file when you weren't addicted to ducks.

- Please also include the version of the game into the report (can be seen in the bottom of pausemenu)

v. 0.3.11

**Comment by Oskutin** [comment]
Fixed
