### ISSUE TITLE
Stuck in well near Harmacy

### ISSUE THREAD

**Issue by GreyGoldFish** [loiste-interactive/Obenseuer-Issues#672]
The title is self evident. I've attached a picture below. I think that the collision should be adjusted so that you either can't fall in or you can get out if you do.
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/55509085/7b05c831-74c2-4c70-9f52-796f80b7c37e)

**Comment by Oskutin** [comment]
Already fixed
