### ISSUE TITLE
Have to crouch to enter shroom outhouse

### ISSUE THREAD

**Issue by CBS-S** [loiste-interactive/Obenseuer-Issues#675]
You don't have to crouch to enter the portable toilet in the starting area, but the shroom-filled one near the contaminated building. I think this is a player clip bug because there's no obvious reason you should have to.

![20231030172147_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/86502239/dd230278-9fc2-4656-a98b-15ee247cfd46)

**Comment by Zuntti** [comment]
Fixed
