### ISSUE TITLE
Infinite diesel can

### ISSUE THREAD

**Issue by CBS-S** [loiste-interactive/Obenseuer-Issues#676]
![20231030173034_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/86502239/d3a16b14-ed24-4bb5-9e08-cce5de1d9381)

Trying to pick this up plays the grab sound effect but doesn't add the item to your inventory.

**Comment by CBS-S** [comment]
Where would I find it?

**Comment by Oskutin** [comment]
https://github.com/loiste-interactive/Obenseuer-Issues/issues/618

**Comment by Oskutin** [comment]
#683

**Comment by CBS-S** [comment]
I don't think this is the same bug. This diesel can isn't in a crate, it's in the environment, and the quantity there doesn't change. The bug is that you can pick it up repeatedly, adding more and more diesel cans to your inventory.
