### ISSUE TITLE
Invisible wall at yellow cabin

### ISSUE THREAD

**Issue by CBS-S** [loiste-interactive/Obenseuer-Issues#681]
There's an incomplete invisible wall here that can be walked around. It doesn't match up to any of the map geometry.

![20231030181758_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/86502239/d819d1ac-1dac-4687-b112-c13e18c5b3e1)

**Comment by CBS-S** [comment]
Also another one here on the roof, which again can be walked around

![20231030182141_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/86502239/8f00eeeb-156f-4c06-aaa8-62049f0a4415)

**Comment by Oskutin** [comment]
Mind if I post the second screenshot, it looks cool?

**Comment by Oskutin** [comment]
Fixed
