### ISSUE TITLE
Bad framerate in this area during rain

### ISSUE THREAD

**Issue by CBS-S** [loiste-interactive/Obenseuer-Issues#684]
![20231030183529_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/86502239/89d5cb25-2c09-44be-9a26-3fd731261079)

Performs fine in good weather. Haven't experienced it yet with snow.

**Comment by Oskutin** [comment]
Can confirm, it's the rain collision doing something funky there

**Comment by Oskutin** [comment]
Rain shouldn't cause that much lag anymore
