### ISSUE TITLE
Crash while stealing from first tenant (tutorial guy)

### ISSUE THREAD

**Issue by GreyGoldFish** [loiste-interactive/Obenseuer-Issues#685]
I was in the tutorial guy's apartment, stealing, when I turned the camera to leave, and before I opened the door, I crashed.

I'm not sure how to recreate the issue, but I've attached my player log.

v. 0.3.11

[Player-prev.log](https://github.com/loiste-interactive/Obenseuer-Issues/files/13208833/Player-prev.log)

**Comment by Oskutin** [comment]
Seem to be random crash originating from rendering/lighting

**Comment by Oskutin** [comment]
#687
