### ISSUE TITLE
Seating NPC got limbs lost at particular angle

### ISSUE THREAD

**Issue by Kastuk** [loiste-interactive/Obenseuer-Issues#688]
Several sitting NPCs lossing foots or hairs\eyes\heads when I look at them at the edge of screen when crouching.
![20231030222401_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/36314945/59f794ce-5f04-45b9-bd6f-6d8f5aecc8a4)
![20231030222426_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/36314945/098309bd-18ad-470b-8dc9-c99b713b9735)
![20231030222752_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/36314945/a0af35af-ada7-4428-b91a-ffd896301973)
![20231030222507_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/36314945/dbcbc677-a870-42bd-9aa4-3b2667f12089)
![20231030222554_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/36314945/aff9fd9e-eb49-4f6b-9503-908e97224a50)

**Comment by Oskutin** [comment]
Fixed
