### ISSUE TITLE
Cannot put candies back on market shelf

### ISSUE THREAD

**Issue by Kastuk** [loiste-interactive/Obenseuer-Issues#689]
Kitties, Mattox, Pluto bars cannot be placed back on shelf.
Simple way to test it is to Sort every market shelf, so all things be stacked.
Things which not available to be put back, will disappear at sorting and got dropped on the floor.
![20231030230952_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/36314945/4e86ca3d-72fa-4cc5-a8de-6f009c09ffcb)
![20231030230948_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/36314945/350a705d-dea3-4644-a3e2-86ad3a740860)

**Comment by Oskutin** [comment]
Fixed
