### ISSUE TITLE
Task Items duplicating (with a blank sprite) each time game is saved and loaded

### ISSUE THREAD

**Issue by Oskutin** [loiste-interactive/Obenseuer-Issues#69]
![kuva](https://user-images.githubusercontent.com/5402150/232532859-02ebe30b-f937-4626-b132-e7b9ff9bcf0b.png)
After save & load:
![kuva](https://user-images.githubusercontent.com/5402150/232532945-1a3e74d3-c512-4df3-9db7-d2e8cef44f03.png)

**Comment by Zuntti** [comment]
Fixed
