### ISSUE TITLE
Broken stats after location load

### ISSUE THREAD

**Issue by Kastuk** [loiste-interactive/Obenseuer-Issues#691]
Similar to old #522 
I got this error again after some intensive farming in greenhouse, after exit to outside (in this game session I did cheat for fast renovations testing).
![20231030235815_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/36314945/2f72df7f-e63a-4e50-8e7d-7519b2dd9109)
No stats and addiction showing, console is empty and when I enter _**player_stats get**_, I got repeating error.
[Player.log](https://github.com/loiste-interactive/Obenseuer-Issues/files/13209906/Player.log)

Autosave at exit from greenhouse and saveslot after error spam.
[no stats error spam.zip](https://github.com/loiste-interactive/Obenseuer-Issues/files/13209914/no.stats.error.spam.zip)

**Comment by Oskutin** [comment]
Same error than in #619 , but keeping this as this has logs and savefile

**Comment by Oskutin** [comment]
Theres try catch in that method now, so it doesn't break stats anymore, but this error may cause other issues
