### ISSUE TITLE
Hostel pods is disowned after saveload

### ISSUE THREAD

**Issue by Kastuk** [loiste-interactive/Obenseuer-Issues#692]
I did rent pod 4 for several nights but after saveload it got locked and I must rent another pod.
Theres first save when I have pod and second at same place when I not have pod after load.
[Pod 4 is my here.zip](https://github.com/loiste-interactive/Obenseuer-Issues/files/13210173/Pod.4.is.my.here.zip)
[Player.log](https://github.com/loiste-interactive/Obenseuer-Issues/files/13210175/Player.log)

Before got same problem at pod 2, so I rent pod 4, but number of free pods is already reduced down to 2 pods.
![20231031004610_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/36314945/52520084-40c5-420e-abfa-4b539c006f7f)

**Comment by Oskutin** [comment]
Fixed
