### ISSUE TITLE
Teuvo's alcohol stall: buy alcohol to randomly get empty bottles

### ISSUE THREAD

**Issue by Kastuk** [loiste-interactive/Obenseuer-Issues#693]
When you buy alcohol at Marketplace there, filled bottle may become empty bottle after buy.
Alcohol bottles or jars become empty quite randomly, it may not disappear at first untill you buy-sell-buy again.

When trading inventory menu is opened: try to sell single bottle of alcohol, another of same kind in you inventory will become empty just under cursor, or by single click, or by drag to another slot, or by separating stack of alco bottles.

[Player.log](https://github.com/loiste-interactive/Obenseuer-Issues/files/13215024/Player.log)
[Slot5.zip](https://github.com/loiste-interactive/Obenseuer-Issues/files/13215033/Slot5.zip)

**Comment by Kastuk** [comment]
That problems appear when you buy/sell by double click. No problems if you drag n drop bottles to buy/sell.

**Comment by Oskutin** [comment]
Fixed
