### ISSUE TITLE
Crash after long play when look at wood stove

### ISSUE THREAD

**Issue by Kastuk** [loiste-interactive/Obenseuer-Issues#696]
Deekula A, srcond floor, briked room.

Got a crash when look at wood stove for second time. Already got spammed console error before that and sudden wave of depression when tried to consume too much of antidepressants before sleep.

[Player.zip](https://github.com/loiste-interactive/Obenseuer-Issues/files/13217651/Player.zip)
[Obenseuer.exe.14192.dmp](https://github.com/loiste-interactive/Obenseuer-Issues/files/13217658/Obenseuer.exe.14192.dmp)
[Autosave.zip](https://github.com/loiste-interactive/Obenseuer-Issues/files/13217806/Autosave.zip)

**Comment by Oskutin** [comment]
Seems to belong to the same category of random crashes
#687
