### ISSUE TITLE
Renovation of Yard - Makeshift: hiding elements at various view angle

### ISSUE THREAD

**Issue by Kastuk** [loiste-interactive/Obenseuer-Issues#697]
When I walking around renovated yard, elements like planks and whole terrain may disappear at particular positions and view angle.
![20231031162704_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/36314945/042690de-c6c2-4366-8917-912e3aab0b9d)
![20231031162652_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/36314945/47422650-1cfb-4254-ab31-a26e16ea808f)
![20231031162655_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/36314945/c16fcbac-8f23-47ff-a190-13ed78eb93f4)

**Comment by Oskutin** [comment]
Already fixed
