### ISSUE TITLE
Durability for Can Opener and Watches

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#698]
Currently finding one can opener sets the player for having unlimited ability to use canned food and you don't need any more, any additional can opener will always go to sale for additional money. Seems logical it would be such item that would have a % durability, being able to open about 15-30 cans before running out of usage.

As for the watches, getting the cheapest one will serve player enough, while any more expensive one will always go for sale. I think that low quality/cheap watches should have a chance of permanently breaking down (the time counter should suddenly stop so it depends on player's perception to notice the issue, the name of the item should also change to "Broken ... Watch"). More expensive ones should never break (same goes for the alarm clock). Overall they shouldn't have a "durability" but the cheap ones shouldn't be permanent.

**Comment by ontrigger** [comment]
+1

**Comment by Kastuk** [comment]
Also, alarm clock may lost battery charge after time and theres may be rich watches with alarm included.

**Comment by Nextej** [comment]
I wanted to avoid mentioning Alarm Clock due to hope of #402

**Comment by Kastuk** [comment]
Also, common alarm clock may lost battery charge after time. That thing is even more useful than watches.

Also, classic mechanical alarm clock, which give depression by irritating ringing at every wakeup. At high enough depression will accidently break on next wakeup.
