### ISSUE TITLE
Missing crafting icons

### ISSUE THREAD

**Issue by Zuntti** [loiste-interactive/Obenseuer-Issues#7]
- [ ] Copy machine
- [ ] Drill
- [ ] Bandsaw
- [ ] Lathe
- [ ] Table saw
- [ ] Printing press
- [ ] Fireplace (fireplace_004)
- [ ] Fireplace (fireplace_006)

**Comment by Oskutin** [comment]
There should be some default icon?

**Comment by Oskutin** [comment]
Added
