### ISSUE TITLE
"Good goddess, Amanda, what did they do to you!?"

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#70]
That's being said, I feel like in some aspects, the new character models are a downgrade from the previous Open Sewer version, especially on a faces (especially Amanda's face) which seemed more natural (and even realistic that went surprisingly well with the pixel-arty style), but torso for example doesn't look any better than it was before too.
![image](https://user-images.githubusercontent.com/44178400/232830165-3882e46f-a9a8-41a5-9b28-373680ca98bc.png)![image](https://user-images.githubusercontent.com/44178400/232830148-fbe90424-6601-4b8e-9384-16f9bf9af541.png)
so I find it as an issue!

**Comment by Oskutin** [comment]
Characters will be refined later
