### ISSUE TITLE
Sun flare draws above everything

### ISSUE THREAD

**Issue by ontrigger** [loiste-interactive/Obenseuer-Issues#700]
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/8556074/bb181020-6db9-4d3a-b195-e6355b1cad12)
This is right outside the starting area

**Comment by CBS-S** [comment]
The moon also does this, although the effect is more subtle

![20231031220829_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/86502239/7f69402d-69e6-41c2-9c50-320afea80679)

**Comment by Zuntti** [comment]
Fixed
