### ISSUE TITLE
Weather is still not saved correctly

### ISSUE THREAD

**Issue by ontrigger** [loiste-interactive/Obenseuer-Issues#701]
Entering and exiting apartments will completely change the weather
Before entering Kolhola A
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/8556074/1c388515-5030-47e2-8cb5-e4c0dfd837ed)
After entering and immediately exiting
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/8556074/4e3a28c1-7ee3-418c-b299-4f9830ccb3cb)
After reentering once more
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/8556074/f7d6a0c8-5b2a-4a42-8b58-5a133396f1e3)

**Comment by Zuntti** [comment]
Fixed
