### ISSUE TITLE
VSync turns off after each loading screen.

### ISSUE THREAD

**Issue by JBalazs01** [loiste-interactive/Obenseuer-Issues#702]
Setting the ingame vsync doesn't work after a single load screen, this implies to loading a save from the main menu as well. Setting Radeon Chill to 'Min FPS -->  60; Max FPS --> 60' seems to solve the issue externally, but the game still turns vsync off after every load screen.

**Comment by CBS-S** [comment]
Can confirm I'm also experiencing this.

**Comment by CBS-S** [comment]
This also happens while loading a save after death.

**Comment by Zuntti** [comment]
Fixed
