### ISSUE TITLE
Elevator location in Kolhola A does not get saved

### ISSUE THREAD

**Issue by ontrigger** [loiste-interactive/Obenseuer-Issues#703]
Saving/loading in Kolhola A will reset the elevator location to the first floor. Tried save/loading inside the elevator on the 8th floor and ended up plunging down the shaft

**Comment by Kastuk** [comment]
Opened doors status is saved, so elevator may at bottom with doors into shaft opened at high floor.

**Comment by Oskutin** [comment]
Does the elevator save/load proprly if you save in a moving elevator?

**Comment by ontrigger** [comment]
> Does the elevator save/load work properly if you save in a moving elevator?

It's a bit hard to tell, but it seems like the elevator will spawn below you and then teleport to some location after a few seconds. Idk what's going on there

**Comment by Oskutin** [comment]
Fixed
