### ISSUE TITLE
Crash after loading a save made during an extremely weird bug

### ISSUE THREAD

**Issue by ontrigger** [loiste-interactive/Obenseuer-Issues#704]
This extremely weird bug occurred shortly after talking to the doctor
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/8556074/b6c05569-cb7f-41cc-8453-b39ae485fcfd)
I made a save during this which consistently crashes the game 
[Slot3.zip](https://github.com/loiste-interactive/Obenseuer-Issues/files/13220416/Slot3.zip)
[Player-prev.log](https://github.com/loiste-interactive/Obenseuer-Issues/files/13220420/Player-prev.log)

**Comment by Oskutin** [comment]
Hmm, this is not random crash if it happens consistently:

`Infinity or NaN floating point numbers appear when calculating the transform matrix for a Collider. Scene hierarchy path "Player/Player Camera Base/Player Camera" `

**Comment by Oskutin** [comment]
Seems to be the same as this:
https://github.com/loiste-interactive/Obenseuer-Issues/issues/655

**Comment by Oskutin** [comment]
This is now fixed
