### ISSUE TITLE
Cannot entered windowed mode, game is stuck in full-screen resolution

### ISSUE THREAD

**Issue by CubeOfIce** [loiste-interactive/Obenseuer-Issues#706]
Game Ver: 0.3.13, bug was present upon first public release of overhaul as well

Hello all,
Upon first playing the game before and after the hotfix, I cannot enter windowed mode through the options upon starting the game. I have also started a new game, and tried to change the screen mode through the pause-menu options as well, but the game still remains in full-screen.  In addition, the black bars present in the screenshots are present on my screen. I have an ultra-wide curved monitor, with a resolution of 3840x1080. I am trying to run the game in a bordered windowed mode, but I can't get the game to go into a window at all. If I go back and forth between changing the resolutions and screen modes, the issue still persists, and the game remains in fullscreen.
![20231031161635_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/10001740/57a43ec1-cedd-4046-a59d-c124dd53648f)
![20231031162246_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/10001740/1a598120-34ea-47d7-b5b5-0bf456cfa6d5)

**Comment by Zuntti** [comment]
Fixed
