### ISSUE TITLE
Key for Deekula C Storage 8 does not work

### ISSUE THREAD

**Issue by ontrigger** [loiste-interactive/Obenseuer-Issues#707]
Cannot open the storage unit if I have the key. Most likely a save issue as I exited and entered C before trying to open it
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/8556074/d3d4143f-c9dd-4e22-8bdd-6b91a3d05d0c)
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/8556074/cb1f03f8-f16f-4a89-b6cd-8951b827552c)

**Comment by Oskutin** [comment]
Fixed
