### ISSUE TITLE
Short draw pop-in at bazaar shipping container

### ISSUE THREAD

**Issue by CBS-S** [loiste-interactive/Obenseuer-Issues#711]
![20231031221045_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/86502239/cbe421ad-3d28-4e17-8486-1d3818ac0bab)
![20231031221046_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/86502239/5ece0d35-44d6-4bb7-9aeb-fbb4327c902c)

Maybe this is the default draw distance but it felt surprisingly close to me.

**Comment by Oskutin** [comment]
Fixed
