### ISSUE TITLE
You can give Jomppe your held items and he will pay for it

### ISSUE THREAD

**Issue by ontrigger** [loiste-interactive/Obenseuer-Issues#713]
I wanted to give Jomppe back my harvest, but he somehow took my hammer and the flashlight along with it, and paid for them too.
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/8556074/d116f0b9-9755-4b4e-925b-f0fbb87911a2)

Steps to repro:
1. Open this save
[Slot4.zip](https://github.com/loiste-interactive/Obenseuer-Issues/files/13221791/Slot4.zip)
2. Give Jomppe the items
3. Both the veggies and the held items disappear but you will have the hammer in your hands
4. Leave the greenhouse or saveload and the items will actually disappear

**Comment by GreyGoldFish** [comment]
This might've happened to my axe too, it vanished but I didn't notice until I left the greenhouse.

**Comment by Zuntti** [comment]
Fixed
