### ISSUE TITLE
The "Start editing the apartment" task does not work

### ISSUE THREAD

**Issue by ontrigger** [loiste-interactive/Obenseuer-Issues#715]
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/8556074/b6d25e1d-44c3-49dd-acb6-c3179581785d)
[Autosave.zip](https://github.com/loiste-interactive/Obenseuer-Issues/files/13221879/Autosave.zip)

**Comment by Oskutin** [comment]
Also there's a typo.

**Comment by Oskutin** [comment]
Seems to work now
