### ISSUE TITLE
Missing items in pharmacy

### ISSUE THREAD

**Issue by CBS-S** [loiste-interactive/Obenseuer-Issues#717]
This might be the same as #490 but it's not something I ran into before the current build, and I'm not seeing the same console errors reported there.

![20231031231648_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/86502239/5729a9e4-6bb1-422a-a8c9-50059f678bfd)

**Comment by Oskutin** [comment]
Seems to be still happening

**Comment by Zuntti** [comment]
Fixed
