### ISSUE TITLE
Evil candy bags are way too evil

### ISSUE THREAD

**Issue by ontrigger** [loiste-interactive/Obenseuer-Issues#719]
Just ate 2 bags, it raised my bladder from 47% to 100 in 10 seconds, which forced me to take a shit, otherwise I would take a 30% health penalty
After taking a shit it AGAIN raised my bladder to 78%

**Comment by CBS-S** [comment]
I wait until I'm near a toilet and then eat them there. It's okay if you know it's coming.

**Comment by Kastuk** [comment]
Perfect aid for fertilizer and mash production.
