### ISSUE TITLE
Containers near Sauna respawn items too fast, bottles doubled

### ISSUE THREAD

**Issue by snortico** [loiste-interactive/Obenseuer-Issues#720]
Both the locker and the can/bottle storage at the sauna respawn new items very fast if you enter/leave the sauna. In addition, the can/bottle container has both a container and a 'dummy' container that spawns cans in the overworld that can be taken. (Think this was similar to a bug with the can container in the tenement stairwell/hall.)

**Comment by Oskutin** [comment]
Is this the player interior or canal sauna?

**Comment by snortico** [comment]
Canal sauna, no upgrades.

**Comment by Oskutin** [comment]
Should be fixed
