### ISSUE TITLE
Door clips through box behind Decorative Items vendor

### ISSUE THREAD

**Issue by CubeOfIce** [loiste-interactive/Obenseuer-Issues#722]
Opening the chain-link door behind the Decorative Items vendor across from the O-Market, the door clips through the cardboard boxes lying on the floor. Screenshot taken while the door was opening for demonstration purposes.
![20231101105326_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/10001740/72bd03f9-3162-4b77-900d-d4626a90847b)

**Comment by Oskutin** [comment]
Fixed
