### ISSUE TITLE
KIrka the miner, hard lock

### ISSUE THREAD

**Issue by Kastuk** [loiste-interactive/Obenseuer-Issues#723]
Hostel, npc near vending machine, Kirka.
I did sleep in the pod and gonna talk to npc nearby.
When I talk to her and ask about appartment, tenement map appear when dialog is not closed.
![20231101202024_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/36314945/d20a625d-326b-45e3-b20c-0d71472850bd)
So I cannot end it after tenement map is closed.
![20231101202044_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/36314945/55d13ad7-f1c8-4000-a989-0ad6db745bcc)
Pause menu is not available.
Console is not available, as any text in it is sended immediately.
So, only hard exit available.

**Comment by Oskutin** [comment]
Hm, The same issue propably also affects other potential residents of the Kolhola

**Comment by Oskutin** [comment]
Hmm, bank call also frozes according to some reports

**Comment by Zuntti** [comment]
Fixed
