### ISSUE TITLE
Getting flashbanged when entering Hostel check-in area

### ISSUE THREAD

**Issue by GreyGoldFish** [loiste-interactive/Obenseuer-Issues#725]
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/55509085/882cb7ec-3fd0-48bb-8d6d-bf5d00a66131)

This is what I saw after opening the door the check-in area at the hostel. I've attached my player logs below.

[Player-prev.log](https://github.com/loiste-interactive/Obenseuer-Issues/files/13230509/Player-prev.log)
[Player.log](https://github.com/loiste-interactive/Obenseuer-Issues/files/13230510/Player.log)

**Comment by Oskutin** [comment]
```
Screen position out of view frustum (screen pos 909.000000, 518.000000) (Camera rect 0 0 1920 1080) 
(Filename:  Line: 3484)

Shadow strength -nan(ind) was clamped to 0..1 range. 
(Filename:  Line: 26)
```

#704

**Comment by GreyGoldFish** [comment]
This happens consistently in Kolhola. It happened again near the pods.
