### ISSUE TITLE
Upon entering the B2 tunnel, the game freezes

### ISSUE THREAD

**Issue by TiaLinna** [loiste-interactive/Obenseuer-Issues#73]
Sometimes the loading screen appears and loads me outside the tunnell, the time goes on, but I can't do anything

**Comment by Oskutin** [comment]
Ah, this is just content missing from the playtesting, will work once B2 is included.

**Comment by Oskutin** [comment]
Should modify the doorscript that it doesn't get stuck if requested scene is missing

**Comment by Oskutin** [comment]
Now doors that lead to non-existing levels don't let player through.
