### ISSUE TITLE
Spacebar opens virtual keyboard on main menu

### ISSUE THREAD

**Issue by CubeOfIce** [loiste-interactive/Obenseuer-Issues#731]
When starting the game, press the spacebar twice, once to move past the "Press any key to continue screen", and the next to open the New Game prompt. Press the spacebar again, and a virtual keyboard will open, which can be closed by pressing Escape, or clicking outside of the virtual keyboard. The keyboard can also be opened by pressing escape to go back to the main menu, then pressing spacebar again.
![20231101152745_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/10001740/e85c2a1b-3106-41e2-aeb0-b11f52def6e5)

**Comment by Oskutin** [comment]
Oh yes, it does.

**Comment by Oskutin** [comment]
Fixed
