### ISSUE TITLE
Flashlight can sometimes drain battery when turned off after reloading batteries

### ISSUE THREAD

**Issue by CubeOfIce** [loiste-interactive/Obenseuer-Issues#732]
When reloading the flashlight, I pressed F to turn off the flashlight after reloading it's batteries. The flashlight turns off, but drains battery despite it being "turned off". Turning it back on and then off again does not fix the issue. The only way to stop the drainage is to go through a loading zone, such as a door.

**Comment by Zuntti** [comment]
Fixed
