### ISSUE TITLE
Sledgehammer's tooltip listed as perishable

### ISSUE THREAD

**Issue by GreyGoldFish** [loiste-interactive/Obenseuer-Issues#733]
In the One Stop Shop:

![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/55509085/9ba0299c-e1ab-476c-bcdb-80e9a277f2a3)

**Comment by Oskutin** [comment]
Minor UI enchantment

**Comment by Zuntti** [comment]
Fixed
