### ISSUE TITLE
game breaks randomly when upgradeing or waiting for things to be done upgradeing 

### ISSUE THREAD

**Issue by Asireldreemurr213** [loiste-interactive/Obenseuer-Issues#735]
the tittle says it all i have no clue what causes it

**Comment by Oskutin** [comment]
Can you upload savefile and logs when it breaks

**Comment by Asireldreemurr213** [comment]
when it does again i will

**Comment by Oskutin** [comment]
I'll close this, in case the original happened in old version. Feel free to make a new issue when it appears
