### ISSUE TITLE
Collision issue with doorway scraps

### ISSUE THREAD

**Issue by CBS-S** [loiste-interactive/Obenseuer-Issues#736]
![20231102014125_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/86502239/a8e6b6b5-a345-41c0-82f0-2f3ba6ae656b)

A problem I've run into both in Deekula and the player tenement is that, when you break down boards to get into a closed room, the board scraps have collision. I don't know if this is randomized or not but sometimes I only have to push a little extra and sometimes I can only get past them by crouching and jumping over.

**Comment by Oskutin** [comment]
Fixed
