### ISSUE TITLE
Dragging items directly from equip to the drop margin sticks them to the HUD

### ISSUE THREAD

**Issue by CBS-S** [loiste-interactive/Obenseuer-Issues#738]
Behold:
![20231102021556_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/86502239/7b286a75-a8c1-43f7-8bec-58da71506c99)
![20231102021558_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/86502239/b563a66a-efc2-4518-9b21-d81f63fd268e)
If you save after doing this and reload it fixes the HUD but you don't get the items back

**Comment by Oskutin** [comment]
Logfile?

**Comment by CBS-S** [comment]
![20231102022104_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/86502239/a1df1982-fac3-4b88-a214-995ed122e7eb)

**Comment by Oskutin** [comment]
Fixed
