### ISSUE TITLE
Crash after trying to load a saveslot, moments after saving it.

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#74]
[Player.log](https://github.com/loiste-interactive/Obenseuer-Issues/files/11288698/Player.log)

**Comment by Nextej** [comment]
Another crash in the same situation if that's worth anything
[Player.log](https://github.com/loiste-interactive/Obenseuer-Issues/files/11288905/Player.log)

**Comment by Oskutin** [comment]
Can you get me this:
A crash has been intercepted by the crash handler. For call stack and other details, see the latest crash report generated in:
 * C:/Users/kacper/AppData/Local/Temp/Loiste Interactive/Obenseuer/Crashes

**Comment by Nextej** [comment]
[OS_crashes.zip](https://github.com/loiste-interactive/Obenseuer-Issues/files/11303402/OS_crashes.zip)
