### ISSUE TITLE
Kolhola cleaning items owned after pickup

### ISSUE THREAD

**Issue by snortico** [loiste-interactive/Obenseuer-Issues#740]
Not sure if related: https://github.com/loiste-interactive/Obenseuer-Issues/issues/727

While investigating that one, I noticed weird behavior with other items in Kolhola. The disinfectant at the entrance and the cart with cleaning supplies all show no ownership and let you pick up items that are 'free' - but when in your inventory show that they're owned and are a crime. After dropping the items again it shows them as owned.

**Comment by Oskutin** [comment]
I think that #727 fix also fixed this
