### ISSUE TITLE
Trying to load a saved game from the pause menu or death screen doesn't work

### ISSUE THREAD

**Issue by CubeOfIce** [loiste-interactive/Obenseuer-Issues#743]
Just as the title says, clicking Load 1, 2, etc or even autosave to load a save does nothing. The only way to load a save is to quit to the menu, then load from there. Video demonstration included:

https://github.com/loiste-interactive/Obenseuer-Issues/assets/10001740/be9d8007-0a40-4f82-b713-ecc163cb4518

**Comment by CubeOfIce** [comment]
I should also add, I died once and tried to load a save from there, but the issue was also present. I had to quit to menu, then load save.

**Comment by Kastuk** [comment]
Cause of death?

**Comment by CubeOfIce** [comment]
Any cause of death. The only way to load a save is through the main menu.

**Comment by Oskutin** [comment]
Got logfile?
I can't reproduce this bug.

**Comment by CubeOfIce** [comment]
> Got logfile? I can't reproduce this bug.
I started a new game and tried to reproduce it, yet the save/load system works now. It's probably related to just the save itself.
