### ISSUE TITLE
Mushroom lamps haven't glass untill moved

### ISSUE THREAD

**Issue by Kastuk** [loiste-interactive/Obenseuer-Issues#744]
All that pretty green lamps across Obenseuer lost the ornamental glass. Can fix it only in our appartment by relocation.
![20231101172016_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/36314945/4aff90a3-58f4-45ad-bc06-acd9c548ae19)

**Comment by Oskutin** [comment]
Fixed
