### ISSUE TITLE
Certain blueprints appear as white squares, cannot be built

### ISSUE THREAD

**Issue by CubeOfIce** [loiste-interactive/Obenseuer-Issues#745]
When viewing the player's inventory for blueprints, a few come up as just white squares with a number in their lower right or upper left corner. When attempting to build the blueprinted items at a worktable, the items do not appear at all and have no hover-over description, except when viewed in the inventory.

![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/10001740/e1c5a70c-e685-42cb-bdbb-febc2ff5e644)
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/10001740/4f7a6bbf-303e-4626-a73f-a97dd1fe038d)
![20231102122030_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/10001740/d9140932-bdad-4ce4-b5ed-05f5f6db2ace)

**Comment by Oskutin** [comment]
Already fixed
