### ISSUE TITLE
light problem in the doc office

### ISSUE THREAD

**Issue by Asireldreemurr213** [loiste-interactive/Obenseuer-Issues#746]
if you stand inside the offfice and look out the lighting messes up ![Uploading Screenshot_27.png…]()

**Comment by Asireldreemurr213** [comment]
![Uploading Screenshot_27.png…]()
oops it diddent work sry

**Comment by Oskutin** [comment]
Image didn't upload

**Comment by Oskutin** [comment]
And the lights turn normal when you walk thru that door?

**Comment by Oskutin** [comment]
Fixed
