### ISSUE TITLE
Visual bugs with level 4 facade.

### ISSUE THREAD

**Issue by JBalazs01** [loiste-interactive/Obenseuer-Issues#748]
![os1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/121858945/6ddb3cce-c6bb-4bea-b420-4c608ae7c6f0)
![os2](https://github.com/loiste-interactive/Obenseuer-Issues/assets/121858945/9c044f34-9e20-4b69-aa0a-ac2b8499d8ca)
![os3](https://github.com/loiste-interactive/Obenseuer-Issues/assets/121858945/4dd0bd06-a5d7-4b97-b4e4-cd0ae73fb484)
![os4](https://github.com/loiste-interactive/Obenseuer-Issues/assets/121858945/67a38610-1a5a-4103-af3f-258f1ffc2126)

You can see through the building at several palces, including the main entrance, at the middle of the floor 1 extensions and at some windows where apartment 2 is.

**Comment by JBalazs01** [comment]
![os5](https://github.com/loiste-interactive/Obenseuer-Issues/assets/121858945/f545334b-562e-4821-ac62-f24a9ed3a4fb)

If you enter the player apartment and go to the right extension it also has a missing wall texture.

**Comment by Zuntti** [comment]
Fixed
