### ISSUE TITLE
Clipping issues with level 4 courtyard.

### ISSUE THREAD

**Issue by JBalazs01** [loiste-interactive/Obenseuer-Issues#749]
![os6](https://github.com/loiste-interactive/Obenseuer-Issues/assets/121858945/777dbb4b-ba0d-4bfa-98a8-fea5b3fe4129)
![os7](https://github.com/loiste-interactive/Obenseuer-Issues/assets/121858945/46908fe4-afba-40e7-ab60-ad6a1e5eb462)

When coming from the toll bridge the two stairs on the right have clipping issues. The one that is closer to the bridge is missing clipping entirely and the on on the right most side has some minor issues.

**Comment by Oskutin** [comment]
Does the lower level upgrades work?

**Comment by JBalazs01** [comment]
![os8](https://github.com/loiste-interactive/Obenseuer-Issues/assets/121858945/f7e34063-5756-4758-8091-76a7a6ff5a7b)

And the gazebo too.

**Comment by JBalazs01** [comment]
> Does the lower level upgrades work?

I'll make a new character and try.

**Comment by Zuntti** [comment]
Fixed
