### ISSUE TITLE
Modular shelves can only be placed on floor

### ISSUE THREAD

**Issue by JBalazs01** [loiste-interactive/Obenseuer-Issues#750]
![os9](https://github.com/loiste-interactive/Obenseuer-Issues/assets/121858945/1b634c47-c400-4d20-87a1-edbd33ae90f1)
![os10](https://github.com/loiste-interactive/Obenseuer-Issues/assets/121858945/c764860d-5a34-4cfc-b7e5-1d39c8a5698a)

Modular Shelf and Modular Shelf Rec snap to the wall incorrectly.

**Comment by Oskutin** [comment]
well, they're red so needs to be placed on floor.
Not a bug, but a something what could be improved, tho

**Comment by JBalazs01** [comment]
Oh sorry, I didn't know those could only be put on the ground as of now.
