### ISSUE TITLE
Rats get culled, even when they shold be visible

### ISSUE THREAD

**Issue by CBS-S** [loiste-interactive/Obenseuer-Issues#753]
![20231102234019_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/86502239/2e67165e-6eae-4d85-8feb-254bd49b1c4b)

Was visible, then vanished but could still be followed by the green glow. Was grabbable while invisible but I chose not to pick it up, and it reappeared a few seconds later.

**Comment by Oskutin** [comment]
Seems to be fixed
