### ISSUE TITLE
Misc. item description typos

### ISSUE THREAD

**Issue by CBS-S** [loiste-interactive/Obenseuer-Issues#755]
![20231103001332_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/86502239/c2f875cc-4419-49d1-97ff-9675d9730253)
If Fail is the brand name then it should be capitalized the second time too

![20231103001346_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/86502239/ee58924f-6b09-4a90-bf2b-25a8fabfccad)
Slauhgter -> slaughter

![20231103001537_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/86502239/3a1c71b8-c6cc-4e1d-b90d-9c2fab39a489)
The first word in the sentence should be capitalized

**Comment by Zuntti** [comment]
Fixed
