### ISSUE TITLE
Enhancement request: Make it possible to break up item stacks

### ISSUE THREAD

**Issue by CBS-S** [loiste-interactive/Obenseuer-Issues#756]
Sometimes I want to keep part of a stack, and as far as I can tell items can't be unstacked. Could you do it with ctrl + click or something like that?

**Comment by Oskutin** [comment]
Items can be unstacked, by dragging and then dropping one by one with left click. Theres also slider for that.

**Comment by Kastuk** [comment]
Right mouse click to take one of many.
