### ISSUE TITLE
Baked-in shadows on O-Mart bulletin board

### ISSUE THREAD

**Issue by CBS-S** [loiste-interactive/Obenseuer-Issues#757]
![20231103002341_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/86502239/fb4291f3-54e4-4a38-8b80-033e9521cf7e)

I remember the conspiracy theory bulletin board in INFRA had these shadows, and that had a separate prop that acted as an overlay. Is there supposed to be something like that here?

**Comment by Kastuk** [comment]
Theres baked shadows at various pickable items everywhere, like cans in Kolhola basement. Must be hunt down specifically.

**Comment by snortico** [comment]
This is still true in .16, noticed in Kolhola basement/1st floor, not sure if elsewhere.

**Comment by Zuntti** [comment]
Already fixed
