### ISSUE TITLE
Water purifying bug - Plastic Liquid Containers

### ISSUE THREAD

**Issue by Orphiex** [loiste-interactive/Obenseuer-Issues#759]
Found an issue when using the Chemical Lab to separate a Plastic Liquid Containers of Dirty Water into Clean Water and Sewage.

(1 L Dirty Water -> 0.7 L Clean Water + 0.3 L Sewage)

Upon the first success (i.e. when one Container contains Clean Water and one contains Sewage), further processing of the Dirty Water is blocked until the Container holding Clean Water is emptied.

Note: since early levels of the Chemistry skill have a success rate around 40%, repeated failed processing of the Dirty Water generates Sewage, but no Clean Water. In this case, the Purify action can be repeated continuously until the first successful generation of Clean Water, at which time the Purify action is grayed out.

Possible cause is that Purify action can only increase Clean Water content of an empty fluid-container object?

EDIT: Same issue appears when creating other Chem Lab products, e.g. Mushroom Extract.

**Comment by Oskutin** [comment]
https://github.com/loiste-interactive/Obenseuer-Issues/issues/718
