### ISSUE TITLE
Map transition issues with tasks

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#76]
When changing the maps, all tasks gets removed, getting back to the map they were active does not resolve it. Additionally when entering a map, we're getting all the prompts (like a map item got added to our inventor or a certain task is active) with each time again, which makes a clutter and is confusing whether player gotten something new while entering or not.
![image](https://user-images.githubusercontent.com/44178400/233446651-4135ee37-6021-4212-8854-c110234fec63.png)

**Comment by Oskutin** [comment]
Does this still happen?

**Comment by Nextej** [comment]
It seems to work alright now.
