### ISSUE TITLE
Passport task issues, cannot find passport salesman in Deekula C or Passmore's password

### ISSUE THREAD

**Issue by CubeOfIce** [loiste-interactive/Obenseuer-Issues#768]
With the task "Getting a passport", I cannot find neither the passport salesman in Deekula C, nor the password required for Passmore.  I've went up and down Deekula C multiple times, and could not find a passport salesman.

I have however found the password via the moonshine salesman under Deekula B (Passed), yet when I go back to Passmore in Tenement B, I cannot give him this password. I also believe the "Find someone who sells passports" subtask is too vague in it's description.

EDIT: Mistakenly said Tenement A instead of B, which is Passmore's location.

**Comment by Oskutin** [comment]
Did you talk with Möbelmann? He knows who sells them.

**Comment by CubeOfIce** [comment]
Yeah, I did, I found that out later but forgot to close the ticket.
