### ISSUE TITLE
Passmore's task broken, cannot continue

### ISSUE THREAD

**Issue by CubeOfIce** [loiste-interactive/Obenseuer-Issues#771]
When completing one of the two tasks for Passmore, I cannot continue after finding the entrance to the bazaar bank. I find the entrance, go back to his apartment door, and he asks me if I want to buy something. No prompt is given for any next task or even an inquiry into the bank tunnel entrance.
![20231103180629_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/10001740/499ce061-2fba-45cf-b1ff-44f452ad6188)
![20231103180641_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/10001740/2d459b46-eb89-4546-9880-36523a072e76)
![20231103180643_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/10001740/a1d2a7ef-d0f2-46bc-b161-73efe0507574)

**Comment by Oskutin** [comment]
Is it this: https://github.com/loiste-interactive/Obenseuer-Issues/issues/769

**Comment by CubeOfIce** [comment]
Duplicate issue, see #769
