### ISSUE TITLE
Conversation dialog softlock

### ISSUE THREAD

**Issue by Orphiex** [loiste-interactive/Obenseuer-Issues#775]
I've found a few conversations where ending the conversation doesn't trigger the closure of the conversation dialog; with the conversation dialog still open but all interactions with the environment blocked, this causes a softlock that necessitates a restart of the game.

I've found it on these conversation topics:
- Kirka Kaabus (Hostel): upon asking her if she's still looking for an apartment (bringing up the Tenement menu)
- Stalburg Bank (Payphone): in the Debit Card conversation line (Trigger: I'm currently living abroad, so I can't...)

**Comment by Oskutin** [comment]
This is already fixed
