### ISSUE TITLE
Unable to pass tenement bridge while walking

### ISSUE THREAD

**Issue by snortico** [loiste-interactive/Obenseuer-Issues#776]
The pay bridge in the direction of the tenement to the town center cannot be crossed while walking. Either have to sprint or jump. See attached.
![Screenshot 2023-11-04 020954](https://github.com/loiste-interactive/Obenseuer-Issues/assets/112534082/e81cc3ab-85cb-454a-82b8-991a498d6c5d)

**Comment by Orphiex** [comment]
Same here, but I find that the bridge can be walked onto without jumping from certain angles. Might be just a misaligned hitbox.

**Comment by Oskutin** [comment]
fixed
