### ISSUE TITLE
Suitcase in Apartment 6 is owned

### ISSUE THREAD

**Issue by snortico** [loiste-interactive/Obenseuer-Issues#777]
![Screenshot 2023-11-04 022534](https://github.com/loiste-interactive/Obenseuer-Issues/assets/112534082/ae767aef-312a-4598-ac7f-71e2fccffb8e)
Upon first exploration of Apartment 6, in the 'kitchen,' the suitcase under the bed is still marked as owned despite nothing else being marked as such.

**Comment by Oskutin** [comment]
Fixed
