### ISSUE TITLE
Prepared food inedible, unable to purchase

### ISSUE THREAD

**Issue by snortico** [loiste-interactive/Obenseuer-Issues#778]
Prepared foods cannot be purchased (unable to place on belt in OS Market.) Also cannot be eaten (at least when 'stolen' before purchase.)

Maybe related to: https://github.com/loiste-interactive/Obenseuer-Issues/issues/549

**Comment by snortico** [comment]
tested in new playtest build

**Comment by Oskutin** [comment]
Fixed
