### ISSUE TITLE
Aggressive visual culling: Pea Soup Militia Fence and Tenement B Light

### ISSUE THREAD

**Issue by snortico** [loiste-interactive/Obenseuer-Issues#779]
Found two instances of visual culling that are slightly too aggressive and are easy to see unintentionally. Fence by the pea soup folks and the light box above tenement B. Hard to tell from pictures, but the difference is a very slight difference in viewing angle. Graphic settings all set highest, if relevant. See attached.

![Screenshot 2023-11-04 023556](https://github.com/loiste-interactive/Obenseuer-Issues/assets/112534082/a5f56a67-3746-4f3f-9c84-7e208d058726)
![Screenshot 2023-11-04 023518](https://github.com/loiste-interactive/Obenseuer-Issues/assets/112534082/a8cd8df9-cb47-4c64-9f2e-a6dfc6139bef)
![Screenshot 2023-11-04 023523](https://github.com/loiste-interactive/Obenseuer-Issues/assets/112534082/0e46ae93-bff8-4fb9-9f56-465fa8840445)
![Screenshot 2023-11-04 023548](https://github.com/loiste-interactive/Obenseuer-Issues/assets/112534082/3b77683d-598b-4ce4-89e7-734f950657ab)

**Comment by Oskutin** [comment]
Already fixed
