### ISSUE TITLE
Grain crops that fail don't show 'dead' and uproot, just 0% progress toward growth 

### ISSUE THREAD

**Issue by snortico** [loiste-interactive/Obenseuer-Issues#780]
Other crops show the 'uproot dead crop' message, rye and wheat instead show 0% progress. Picture taken planted with 10 farming. Not sure if it is specific to the fields in the greenhouse above OS Market or not.
![Screenshot 2023-11-04 025508](https://github.com/loiste-interactive/Obenseuer-Issues/assets/112534082/5f76fb23-34f9-4cad-bdd8-029d884d405e)

**Comment by Oskutin** [comment]
Fixed
