### ISSUE TITLE
Playtesting - game froze unrespondingly at Deekula B while quickly opening and closing storage UI

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#786]
[Player.zip](https://github.com/loiste-interactive/Obenseuer-Issues/files/13257073/Player.zip)

**Comment by Oskutin** [comment]
Is this random or consistent?

**Comment by Nextej** [comment]
Happened only once, didn't test further.

**Comment by Nextej** [comment]
Another instance at Deekula A, also happened when attempting to close an inventory.
[Player.zip](https://github.com/loiste-interactive/Obenseuer-Issues/files/13310894/Player.zip)
