### ISSUE TITLE
Police arrest behavior only works once per game session

### ISSUE THREAD

**Issue by ontrigger** [loiste-interactive/Obenseuer-Issues#788]
Police will only try to arrest you on the first load after a game start. Reloading any save will stop them from trying to arrest you

Steps to reproduce:
1) DL this save [Slot3.zip](https://github.com/loiste-interactive/Obenseuer-Issues/files/13257087/Slot3.zip)
2) Restart the game
3) Load the save, you should get arrested immediately
4) Reload the same save, arresting no longer works

**Comment by Oskutin** [comment]
You mean: "if police is chasing you, you can stop the chase by save load"?

**Comment by Oskutin** [comment]
Yeah, it seems to break just like you described

**Comment by Oskutin** [comment]
Fixed
