### ISSUE TITLE
Task "Tell Pentti you will make mash yourself" doesn't work

### ISSUE THREAD

**Issue by ontrigger** [loiste-interactive/Obenseuer-Issues#789]
[Slot4.zip](https://github.com/loiste-interactive/Obenseuer-Issues/files/13257093/Slot4.zip)
There is no dialog option to tell Pentti that you will make mash yourself, even though it is not completed in the Me Mash! quest

**Comment by ontrigger** [comment]
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/8556074/7667f3e6-1674-452d-9aac-5aae8b522a42)

**Comment by Zuntti** [comment]
Fixed
