### ISSUE TITLE
Dragging money out of storage now works almost opposite

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#79]
In relation to issue [#47](https://github.com/loiste-interactive/Obenseuer-Issues/issues/47) attempt to drag a money from a storage using CTRL + double mouse click results in the money stack being split in half in that storage, while the whole value of that stack being added to our pocket (when uneven, it works in our favor).

https://user-images.githubusercontent.com/44178400/233448470-f990f624-317f-4a37-8799-f02918ce4652.mp4

**Comment by Oskutin** [comment]
Fixed
