### ISSUE TITLE
Typos in dialog and tasks

### ISSUE THREAD

**Issue by gurka** [loiste-interactive/Obenseuer-Issues#790]
Dialog at start:
> Interviewer
> [player name]. We have to ask a few questions for your own safety. Some of these questions are personal. This information is important for a finding cure for fungal disease.

"for a finding" should be "for finding a"

---

Task Abandoned tenement
> They recomended to examine it first [...]

Should be "recommended"

---

Note "BRIDGE TOLL CONTACT INFO"
> P.P.S. And DON'T event think about calling me [...]

"event" should be "even" - but I guess you could argue that this is a typo by whoever wrote the note and is therefore intended :D 

---
Pate Rantanen
> I-I have been thinking about that for so long, but I just don't have right tools for it!

Seems like there is a missing "the" before "right tools"...?

**Comment by gurka** [comment]
By the way, is it worth spending time reporting typos? e.g. if there are plans of running a contextual spell checker as a part of a build pipeline or similar

**Comment by Zuntti** [comment]
Fixed
