### ISSUE TITLE
Missing collisions in Kohola apartment cabinets

### ISSUE THREAD

**Issue by CubeOfIce** [loiste-interactive/Obenseuer-Issues#792]
Two large cabinets, one in A9 and A21 in Kohola A have missing collisions.

![20231103181732_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/10001740/62e9c7ca-0636-44a7-8472-50c0fb6ed882)
![20231103181740_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/10001740/20563ab2-4bfa-45c2-89f1-287c357903a1)
![20231103181849_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/10001740/c1ffe5ad-e67e-4427-a376-92195b8206dd)

**Comment by Oskutin** [comment]
Fixed
