### ISSUE TITLE
Playtesting - A furniture bought cannot be used in crafting on the same map until map reload.

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#795]
Example, buy plastic chair at Mobelman's to craft a toilet bucket using Mobelman's workstation.

**Comment by Oskutin** [comment]
Hey, finally a reverse save load bug!

**Comment by Oskutin** [comment]
Can't reproduce this

**Comment by Orphiex** [comment]
I've experienced a similar issue; I bought one of the blue barrels from Jonasson to make a distilling station, but at the workbench, selecting the "distilling station" blueprint on the right showed I had no blue barrels, even though I could put it on the pedestal from the left side. No idea if leaving and re-entering the building would have fixed it, didn't think to check at the time.

**Comment by Kastuk** [comment]
Isn't blue barrels for fermenting station?
