### ISSUE TITLE
More visual culling at Militia

### ISSUE THREAD

**Issue by CBS-S** [loiste-interactive/Obenseuer-Issues#800]
Maybe this has already been fixed but it wasn't specifically addressed in #779. Beta branch:

![20231104202007_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/86502239/7aa1c294-1005-43e9-923f-f7227ebaf7ee)
![20231104202008_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/86502239/9c075aaa-6149-4077-a385-e40b36d7e3dd)
![20231104202013_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/86502239/22d1a557-f3a7-4c04-9a0a-66fcd9abcc2b)

**Comment by CBS-S** [comment]
![20231104202249_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/86502239/4bdd5a53-6abc-419f-9b6f-49d69365c654)
![20231104202251_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/86502239/96f35344-b40c-4c1c-a8d6-8a075c45bdf2)

**Comment by Oskutin** [comment]
The map just had un-updated occlusion data, what is now rebuild, thus fixes all odd culling issues.
