### ISSUE TITLE
Playtesting - Furniture preview room is unlit on Deekula A level (all other levels seems to have proper and consistent lighting).

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#804]

**Comment by Oskutin** [comment]
Pic?
The one in jonasson's seems to work.

**Comment by Nextej** [comment]
Correction, the issue is happening only if the furniture preview room is ran from the Samuel's store, not the workbench next to Samuel
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/46585f01-ea22-4fbd-b4ea-46e862551525)

**Comment by Oskutin** [comment]
Yeah, it's dark

**Comment by Oskutin** [comment]
Fixed
