### ISSUE TITLE
Can clip camera into Kurahaara Bros. stall

### ISSUE THREAD

**Issue by CBS-S** [loiste-interactive/Obenseuer-Issues#807]
(Playtesting branch) At the leftmost edge of the Kurahaara stall, you can clip the camera through the tarp while the place is closed.

![20231104203728_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/86502239/9f7a95bd-93a3-4c49-b7e0-d7e7ed61d1cf)
![20231104203736_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/86502239/02e5da08-fc46-423a-ae81-bf00338697cb)

**Comment by Oskutin** [comment]
Fixed
