### ISSUE TITLE
Playtesting - Rebalanced Makeshift and Shabby upgrades

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#812]
Apartment Upgrades if #905 is _**not**_ executed
- Makeshift Walls 2300 OC 75 RM | 1 days + nails narrowed down to 40
Shabby Walls 7700 OC 325 RM | 2 days

- Makeshift Bathroom 1600 OC 125 RM | 8 hours
Shabby Bathroom 6500 OC 700 RM | 12 hours

- Makeshift Kitchen 1750 OC 50 RM | 1 day 12 hours
Shabby Kitchen 5500 OC 700 RM | 2 days 12 hours

- Makeshift Balcony 7600 OC 500 RM | 2 days 12 hours
Shabby Balcony 13500 OC 1200 RM | 4 days 12 hours

Apartment upgrades if #905 is executed
- Makeshift Walls 2300 OC 75 RM | 2 days + nails narrowed down to 40
Shabby Walls 7700 OC 325 RM | 3 days

- Makeshift Bathroom 1600 OC 125 RM | 12 hours
Shabby Bathroom 6500 OC 700 RM | 1 day 12 hours

- Makeshift Kitchen 1750 OC 50 RM | 2 day 12 hours
Shabby Kitchen 5500 OC 700 RM | 4 days 4 hours

- Makeshift Balcony 7600 OC 500 RM | 3 days
Shabby Balcony 13500 OC 1200 RM | 5 days

**Comment by Nextej** [comment]
Stairs: 7000 OC 800 RM
Basement: 11000 OC 400 RM

**Comment by Nextej** [comment]
- Makeshift Courtyard 8900 OC 950 RM | 2 days
Shabby Courtyard 21000 OC 3200 RM | 3 days

- Makeshift Facade 8000 OC 1100 RM | 3 days
Shabby Facade 17000 OC 2400 RM | 4 days

**Comment by Nextej** [comment]
Alright, it's changed, Apartment Utilities look good, at best the Water would use some adjustment, rests of the Basement upgrades looks alright too. Canal Sauna seems to expensive in compare to much cheaper Basement Sauna.

For the large apartments, be sure to make the changes apply to both balconies.

In general any other upgrade if not specified if needs further balancing I'd then apply 50% less on Makeshift, 33% less on Shabby and 25% less on Decent

I skipped Decent upgrades since I think they shouldn't be available now and majority of the players won't reach it anyway with the amount of other content in the game, see first point of #848. But in general all Decent stuff will likely require that more or less 25% cheaper change.

**Comment by Oskutin** [comment]
balanced
