### ISSUE TITLE
Odd bottle crates at Teuvo's

### ISSUE THREAD

**Issue by CBS-S** [loiste-interactive/Obenseuer-Issues#813]
(Playtesting branch) In Teuvo's, you mouse over the two ground crates and see this:

![20231104204255_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/86502239/e2d53070-87f9-488c-990d-13f2897c9926)

...Unless you mouse directly over the large plastic bottle, in which case you get THIS:

![20231104204257_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/86502239/96bf10ec-5b68-4691-af40-aa7fc374f719)

It then turns out that there are a bunch of bottles stacked in that slot and you can take all of them. The second crate on the ground here is the same way.

![20231104204605_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/86502239/2d73e85a-effe-443c-9820-48cf585bae73)

The red crate doesn't have any large plastic bottles and isn't bugged.

**Comment by Oskutin** [comment]
Already fixed

**Comment by CBS-S** [comment]
You can get I think 32 bottles this way

![20231104204854_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/86502239/24e3d702-c1d1-4d0b-b6de-cbb853b1c94b)

**Comment by CBS-S** [comment]
Ah okay. I'm keeping the bottles though.
