### ISSUE TITLE
Playtesting - Tenement can still be rented to Pate, despite heating requirement not being met

### ISSUE THREAD

**Issue by CubeOfIce** [loiste-interactive/Obenseuer-Issues#814]
As I was going to rent the small apartment on the second floor to Pate Rantanen, I noticed the heating icon at the bottom left said "Does not meet requirements", yet his requirement is for a Makeshift heating setup. I have already had heat installed in this apartment before asking him if he wanted to rent. Despite it saying the requirement wasn't met, I was still able to rent the apartment anyway.
![20231104164911_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/10001740/d7ba2f7b-a662-45ff-b92e-0d63b9babca1)

**Comment by Oskutin** [comment]
AH, UI issue then

**Comment by Zuntti** [comment]
Fixed
