### ISSUE TITLE
Feedback - Standards of possible tenants are too high

### ISSUE THREAD

**Issue by CubeOfIce** [loiste-interactive/Obenseuer-Issues#815]
It's kind of confusing to me how despite a housing crisis in Open Sewer, people aren't so eager to accept housing in the tenements unless it's upgraded to their standards. I'm not sure if it's because of the size of the map and how the NPCs are distributed throughout it, but it seems really strange how people living on the street in tents within a freezing cold environment aren't so eager to accept basic housing. With level 1 upgrades missing, I can understand- but with a million things upgraded to level 2 or 3, it doesn't make much sense for some of them.

**Comment by Nextej** [comment]
More questionable is the woman who lives in a bus, with everything around her but is ready to jump in for some Makeshift Walls.

**Comment by Kastuk** [comment]
May they pay so minimal rent without expected.

**Comment by Nextej** [comment]
> May they pay so minimal rent without expected.

What do you mean, they already do that! I was promised R M S and all I'm getting is some mere OCs...

**Comment by Orphiex** [comment]
> It's kind of confusing to me how despite a housing crisis in Open Sewer, people aren't so eager to accept housing in the tenements unless it's upgraded to their standards. I'm not sure if it's because of the size of the map and how the NPCs are distributed throughout it, but it seems really strange how people living on the street in tents within a freezing cold environment aren't so eager to accept basic housing. With level 1 upgrades missing, I can understand- but with a million things upgraded to level 2 or 3, it doesn't make much sense for some of them.

I sort of agree with this? I mean, some of them make more sense than others. Anyone living in a tent on the streets should have lower standards; the police officer warming his hands at a barrel has higher standards as the woman living in the Kolhola's Hostel, or the guy in Pentti's offering a 1000-RM task reward.

On the other hand, these higher standards make sense if they already have apartments and want to trade up. Maybe just adding a line of response text after the rental query to establish that, with different responses for different degrees of requirements? Something like:

- Lowest: I'm living on the street right now, anything's better than this.
- Low: I'm sleeping under a stairwell, what do you think?
- Medium: I don't much like my current residence, what do you have on offer?
- High: My current place is pretty nice, but I could be convinced.
- Highest: I'm quite comfortable right now; it'd need to be an impressive apartment...

That way, you don't need to juggle tenement requirements as much, just establish a bit of explanation for why their standards are as high or low as they are

**Comment by CBS-S** [comment]
I agree with this.

**Comment by Zuntti** [comment]
Changed and also fixed rm income
