### ISSUE TITLE
Playtesting - Kolhola: Various larger wardrobes are not always interactable depending on the apartment; some if not all bathroom cabinets while interactable, don't have any storage slots in UI.

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#816]

**Comment by Oskutin** [comment]
Pictures of the broken ones

**Comment by Nextej** [comment]
- A3 broken slots
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/03c067f7-6a6e-4abb-a64c-96309619272f)
- A8 broken slots
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/db30a1a7-809e-4126-b558-fb0fdac65937)
- A9 unusable wardrobe
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/5851bebc-100d-4409-9db8-a60d40343d49)
always empty wardrobe
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/66b1bfba-d742-4f59-ad75-1bb71ad9d98b)
broken slots
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/18fcd9cf-1fe4-40a9-8301-f398ea7aecb9)
- A10 always empty
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/bcd6d605-6b0f-4f6b-bc56-2758a90ac2d9)
broken slots
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/5096a64d-776d-4e12-925d-3e66c553d552)
- A13 always empty
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/ba678d76-a8b6-4d97-a8c3-056286b9990f)
broken slots
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/c79a5d63-c1f8-4d70-9d00-eb9765ca47b8)
- A14 always empty
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/dce9199e-df62-4dc4-b311-5fad1e80814b)
- A21 unusable wardrobe
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/097c4f5c-c126-40ea-924d-40a4315e9cc2)
broken slots
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/8c4fa3c4-3182-432d-8aba-d0c17f4a377b)
- A22 always empty
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/b806d7c3-e497-45c0-81e7-84f3460ebde5)
broken slots
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/fa1e6822-550e-4f9a-9a5f-0d801cb504d6)

**Comment by Oskutin** [comment]
Fixed
