### ISSUE TITLE
Proposed statuses' descriptions.

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#818]
Since one of you liked my very bare #708 draft and decided to use it and some of the statuses in game still remain undescribed, I thought of writing them all a nice, consistent descriptions.

- Health
"Unkept well will drift the life away into a helpless silence."

- Bleeding
"Not aided as the time goes, will continue to constantly affect the physical health negatively."

- Thirst
"Basic need for hydration keeping the wellness of physical health."

- Hunger
"Basic need in nutrients keeping the wellness of physical health."

- Bowel and Bladder
"Unsatisfied in time will forcefully get satisfied, immediately affecting the physical health negatively."

- Tiredness
"Exceeded over physical capabilities may meet with sudden collapse into a sleep helplessly."

- Depression
"Constant growth takes away effectiveness of pleasures, exceeded may meet with sudden self-harm and reckless behaviour helplessly."

- Smoking Need
"Unsatisfied need for nicotine will drastically start to affect the mental health negatively."

- Alcohol Need
"Unsatisfied need for alcohol will drastically start to affect the mental health negatively."

- Mushroom Need
"Unsatisfied need for hallucinogenics will drastically start to affect the mental health negatively."

- Duck Need
"Unsatisfied need for a little bit of comfort _will_ suddenly start to affect the mental health negatively."

**Comment by Zuntti** [comment]
Added
