### ISSUE TITLE
Playtesting - Broken collisions in Level 3 Sauna and Level 3 Courtyard

### ISSUE THREAD

**Issue by CubeOfIce** [loiste-interactive/Obenseuer-Issues#819]
Level 3 Sauna:
-The table next to the sauna building has no collisions.
-The pipe coming off the building adjacent to the table also has no collision, allowing the player to clip through both.
-The area next to the left side of the door has no collision, allowing the player to clip inside.
-Inside the off-limits area, bottles from the case which was next to the original sauna can be seen.

https://github.com/loiste-interactive/Obenseuer-Issues/assets/10001740/775f9d2b-0ec3-4b00-b11c-f66484b13d1f

Level 3 Courtyard:
-Pieces of railing can be seen floating from behind the tenement above the sauna.
-Multiple pieces of railing have no collisions.
-The stairs near the bazaar and all of the railings on them have no collision.
![20231104203456_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/10001740/a51d24a6-9188-4e6d-b465-2aa282a4e1f6)

https://github.com/loiste-interactive/Obenseuer-Issues/assets/10001740/f7336efb-538a-4c42-9753-b5c05404bdc0

https://github.com/loiste-interactive/Obenseuer-Issues/assets/10001740/3457c9ae-9330-4756-bd6f-f4dfcb28e6d6

![20231104203153_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/10001740/1187d797-c710-4d48-93d2-16f25d1485c6)
![20231104203223_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/10001740/91f3f4a1-a576-4ff3-803d-3617670e77e5)
![20231104203236_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/10001740/7e0de535-c9c5-4352-9d8c-4752d5ce887a)
![20231104203244_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/10001740/48ef53d0-ac46-4377-b260-7bb47bd12fd9)

Sorry about the videos being so short/quick, github is absolute garbage when it comes to file sizes.

**Comment by Oskutin** [comment]
Isn't that other level 3 courtyard?

**Comment by CubeOfIce** [comment]
Yep, my bad

**Comment by Oskutin** [comment]
Did level 1 and 2 work correctly?

**Comment by Oskutin** [comment]
Fixed.

Also checked prior versions
