### ISSUE TITLE
More Savefiles issues!

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#82]
1. Winch Doors to the workshop became unusable after they were operated when loaded up from a savefile. To recreate: go open the door, save the game, load that saved game.
You'll find the doors being closed and any interaction with winch does nothing (the winch itself works, just not the doors).

2. Priest's Debt get's duplicated if we've done all the steps of the task (except the talk in the other side) before saving the gameslot, then talking with Priest and then loading up that previous save to have a talk again. It results in having to exact tasks, but the new one has limited amount of stages.
![image](https://user-images.githubusercontent.com/44178400/233456268-cda8ad1c-0c20-4925-aaf5-de43a54f67f7.png)
![image](https://user-images.githubusercontent.com/44178400/233456319-2aa1406b-6632-42b9-aacb-5fc273b10a6c.png)
Additionally in the same mission, there seems to be a mistake in dialogue, after vague information provided by the Priest, shouldn't the player be asking to be "less cryptic" instead of "more cryptic"?
![image](https://user-images.githubusercontent.com/44178400/233456585-c0fdb97a-019d-4ff2-905e-2f8c25122053.png)

3. After interaction with Red Thing in the otherside via OSRAT and the loading a savefile from before that encounter, we won't be able to start it again, despite it did not happen yet in this savefile. This applies to all Red Thing encounters.

4. Doing tasks etc. on one character and then going back to main menu, creating new character and starting new game still in the same session, results in those tasks being not available. Example: upon starting a new game, all the talks with Amanda were as if they were already happened and the did not tell us about being evicted so the mission could not be started. Seems like could be a similar as the case above. It has probably more issues like down the deeper the task and task items go. ~~It also did not give me a blueprint of our tenement which it did the first time.~~ Did not realise the blueprint is given upon pressing TEST BUTTON.

**Comment by Nextej** [comment]
Well, it's a badly written one, that in current form and given the tone of the situation, makes no sense in that context and rather rises a confusion.

**Comment by Zuntti** [comment]
Fixed main menu issue

**Comment by Oskutin** [comment]
Fixed the winch
