### ISSUE TITLE
Playtesting - Wood behind yellow shack sends player flying

### ISSUE THREAD

**Issue by CubeOfIce** [loiste-interactive/Obenseuer-Issues#821]
Just to make sure this wasn't a singular instance, I loaded the game back up again and tried it again, and found this pile of wood sends the player flying if they walk over it.

https://github.com/loiste-interactive/Obenseuer-Issues/assets/10001740/4fd5dd87-9791-4f66-9e5c-38077fd5f52e

**Comment by Oskutin** [comment]
Fixed
