### ISSUE TITLE
Max Masher's model is not aligned with collision/interaction box when kicking in his door. 

### ISSUE THREAD

**Issue by binbows** [loiste-interactive/Obenseuer-Issues#825]
When kicking in Max's door the flying back animation plays, but resets his model to where it is slightly outside the door. However the interaction/collision box seems to be where the model is supposed to be. [This was on version 0.3.14]
![Obenseuer 2023-11-05 11_52_40](https://github.com/loiste-interactive/Obenseuer-Issues/assets/87271815/f7be5a45-3b90-4ff9-9133-4a0b58d52d8d)

**Comment by Zuntti** [comment]
Fixed
