### ISSUE TITLE
Playtesting 0.3.14 - after several days of playing, mail had stopped coming in and blueprints no longer spawn (normal recipes still do)

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#827]
[Player.zip](https://github.com/loiste-interactive/Obenseuer-Issues/files/13259912/Player.zip)

**Comment by Orphiex** [comment]
> [Player.zip](https://github.com/loiste-interactive/Obenseuer-Issues/files/13259912/Player.zip)

Where does one even get mail? Has there been a tenement mailbox this whole time, and I've just never noticed it?

**Comment by Kastuk** [comment]
Under your appartment door, even if theres no door and papers is camouflaged on the rug.

**Comment by Nextej** [comment]
After over a week of not getting any mail or seeing blueprints, both began to appear again.
[Player.zip](https://github.com/loiste-interactive/Obenseuer-Issues/files/13272443/Player.zip)

**Comment by Oskutin** [comment]
Did some fixes to mail handler, and can't reproduce this
