### ISSUE TITLE
Door interaction: Unlock

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#83]
In the mines, doors leading to other maps that can be unlock have their interaction shown as red (same as locked), it may be confusing to player as they may not notice it says unlock instead of locked. In other places it is gray, same color as just "open" interaction, I'd propose changing it overall to a new color, green for example, to give player a clear visual indication a new, unique from the other to, interaction is available.
![image](https://user-images.githubusercontent.com/44178400/233459064-c396ba21-f755-4f6d-9707-f82c27b9586a.png)

**Comment by Zuntti** [comment]
Fixed.
