### ISSUE TITLE
Request: Vary window lighting

### ISSUE THREAD

**Issue by CBS-S** [loiste-interactive/Obenseuer-Issues#832]
In the Kohola building, and in the OOB tenement nearby, all the windows are lit up and all have the same bulb color. If it's not too much trouble, varying the color and intensity of the light would make the environment feel more lived-in.

![20231105221729_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/86502239/6156fc3f-f91a-441b-a898-afddf830b1ca)

**Comment by Kastuk** [comment]
Will be nice at least to disable lights for abandoned appartments without colourful lights to stay in gloomy style of Depressive named fine tenement.

**Comment by Oskutin** [comment]
Done
