### ISSUE TITLE
Hanss' Hideout key unlocks Tunnel B2 transition doors from Deekula Basement map, it shouldn't... 

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#839]
and spoils some stuff...

**Comment by Zuntti** [comment]
You can only use this key to enter the small room, but the hallway door is locked if you don't have Mike's B2 keys

**Comment by Nextej** [comment]
Yes, but in the small room you find notes explaining the tunnel. Perhaps would be better if B2 transition doors required both Hanss' key and Mike's key?

**Comment by Nextej** [comment]
bringing it up to attention to the other quest-related issues

**Comment by Zuntti** [comment]
Now you need B2 keys to unlock it from the Deekula Basement
