### ISSUE TITLE
Feedback: sauna thermometers?

### ISSUE THREAD

**Issue by Orphiex** [loiste-interactive/Obenseuer-Issues#841]
So the thermometers in the saunas show a needle moving from left to right as the temperature increases. As temperature increases, thirst and thirst growth-rate both rise. If the temperature gets high enough, the heat starts causing minor injury. So far so good.

The thing is, the thermometers don't give any warning of the danger zone; at the moment, players can only eyeball it, and duck out the moment the heat gets painfully high. Is it possible to add a visual "red zone" to the background element of the thermometer's model? That way, players have a bit more warning.

**Comment by Kastuk** [comment]
Actually 80-100°C is just steaming effect range, actual overheat is rising hiddenly in player body and over particular level start to burn you.
