### ISSUE TITLE
Playtesting - NPCs after getting a rented apartment, reappear back again in their original location after a reload.

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#842]

**Comment by Orphiex** [comment]
Seconded

**Comment by Nextej** [comment]
Yes, it seems to apply to any rentable NPC, on any map, I've got one each from Outside, Deekula A and Bus and they did reappear on each of them.

**Comment by Orphiex** [comment]
Actually, just checked this again, and the Ingrid in the tenement is flagged as "Ingrid Claesson(Clone)".
![20231106193730_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/16548338/bfbfc631-8b59-4015-a1ec-6d29e1bac9b1)

**Comment by Zuntti** [comment]
Fixed
