### ISSUE TITLE
Task triggers: Missing debitcard

### ISSUE THREAD

**Issue by Orphiex** [loiste-interactive/Obenseuer-Issues#843]
I tested whether it was possible to follow the "missing debitcard" task line without actually triggering the task at the ATM. It turns out that it is; you can call the bank, get the recipe for the debit card order form, create the form, and mail the form to the bank, all without ever triggering the task. This seems to be happening because when calling the bank, there are two separate conversation topics for requesting debit card assistance; one is available all the time, while the other only appears in the topic list once the task has been triggered.

Moreover, the sub-task "find a way to contact the bank" will only mark off as complete upon reading the Yellow Pages, even if you've already read them before and have the related note in your "Notes" menu, or if you've called the bank hotline before.

Are these deliberate design choices, or do the task's event triggers need adjustment?

**Comment by Oskutin** [comment]
Fixed
