### ISSUE TITLE
Playtesting - a dead plant root cannot be "harvested"/cleaned off on a Barrler Planter with Supports (or at least at those at Kurahaara's).

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#844]
Umm, the issue is with not being able to "hit" the object with your cursor, the root is never highlighted. Also all the plants tested used the supports, not sure if you can plant other stuff there to know if their roots are broken too.

**Comment by Zuntti** [comment]
Fixed
