### ISSUE TITLE
Playtesting - Priest Debt task got reactivated (being already once completed) after revisiting the level and entering the priest's apartment.

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#847]
[Player-prev.zip](https://github.com/loiste-interactive/Obenseuer-Issues/files/13271239/Player-prev.zip)

On that same note, the B3 apartment (the one for Radio Signal task) got locked again (I could unlock it), but it didn't got relocked any previous time I've visited the map.

**Comment by Zuntti** [comment]
Fixed
