### ISSUE TITLE
you cant pay for tv dinners in the store

### ISSUE THREAD

**Issue by Asireldreemurr213** [loiste-interactive/Obenseuer-Issues#849]
when you pick up the tv dinners in the store you cant pay for them at the counter 
![Screenshot_32](https://github.com/loiste-interactive/Obenseuer-Issues/assets/138607022/5d36f6b7-31ec-45b3-81f0-2cfd282bc53d)
![Screenshot_33](https://github.com/loiste-interactive/Obenseuer-Issues/assets/138607022/9e950805-f7d8-425e-819f-e8243033c5f0)

**Comment by Oskutin** [comment]
Already fixed
