### ISSUE TITLE
Jump uncrouching in tight spaces allows clipping through walls

### ISSUE THREAD

**Issue by ontrigger** [loiste-interactive/Obenseuer-Issues#85]
Seems like the game allows you to uncrouch in spaces you shouldn't be able to stand up, causing all sorts of wacky stuff:

https://user-images.githubusercontent.com/8556074/233503268-f8710c23-b3d4-4aee-b169-6ba07aa6f23f.mp4

It can also send you flying backwards:

https://user-images.githubusercontent.com/8556074/233503454-09559865-d820-4a98-8a9e-f48bf3fa5516.mp4

**Comment by Oskutin** [comment]
Fixed
