### ISSUE TITLE
Excessive sledge hammer swing range

### ISSUE THREAD

**Issue by CBS-S** [loiste-interactive/Obenseuer-Issues#850]
(Beta branch) The sledge can break boards from several paces back, provided they're roughly at the player's POV height. For instance, I was able to land this hit...

![20231107032601_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/86502239/740a79a0-4133-4c26-b40e-c4a968cfd046)

... while standing this far away

![20231107032627_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/86502239/65dc21ae-26d6-4806-9664-1e4ffbadc616)

**Comment by Zuntti** [comment]
Changed
