### ISSUE TITLE
Playtesting - Massive performance issues of Open Sewer Tenement the longer you play on that savefile.

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#854]
After three in-game weeks of playing, the outside's peformance dropped massively over time, comparing it from a fresh new save, I get a drop in central area from 35 FPS to 8 FPS top, other high-performing areas like around the Sauna I had a drop from 70 FPS to 12 FPS top.
[Player.zip](https://github.com/loiste-interactive/Obenseuer-Issues/files/13281874/Player.zip)
This is that character I've been playing all this time where the performance issues occur: https://drive.google.com/file/d/1_ft8FcO8Ch-H75taNkPQO3I_SVyUYEnn/view?usp=sharing
Such issues are not present on other levels.

**Comment by Nextej** [comment]
Seems like the issue may be also concerning Playerment and Kolhola, I'd imagine the cause could be items that spawn on each other with each reload, with Outside level having the most reloads overall, Playerment and Kolhola being in second.

**Comment by Oskutin** [comment]
Yeah, it was items stacking on each other (should be fixed)
