### ISSUE TITLE
Playtesting - Opening state of flooddoors from Tenement B level is not saved between reloads and the doors are always reset to be closed.

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#855]
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/6748db9d-9cad-4f83-93e6-0cd309c9fcf9)

But, I kinda like it that you need to get, find or buy, another valve to fully open jail escape path and I don't have suggestions that would preserve this mechanic and also have the doors keeping their state.

**Comment by Nextej** [comment]
I think it's fixed now? Loading a save from .14 on .15 had the state saved. I'll recheck on .15 properly when I get there on a new character.

**Comment by Oskutin** [comment]
Fixed that door
