### ISSUE TITLE
More things for Samuel to sell + make "Table Saw" buyable

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#856]
All the new machine stuff gets added both to the pool of General Store and Mobelmann's, while it seems like it logically should go to Samuel, who has just few things to offer, it feels right to have machine stuff assigned to him and stuff used in furniture crafting. So I'm proposing an addition of **Plastic Chair**, **Saw** and **Chainsaw**, **Meat Grinder**, **Metal Bucket**, **Water Cooler Bottle**, **Gas Bottle**, **Cooking Pot** to the list of thing you can buy at Samuel's.

Now the second matter, make the **Table Saw** found at Mobelmann's buyable for RMs, similarly to Lathe, also give it to Samuel's.
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/996b7863-b654-4a23-9b71-25c0319985f3)

**Comment by Nextej** [comment]
It's crucial for Samuel to sell **Water Cooler Bottle, Gas Bottle and Cooking Pot**, they are not obtainable otherwise and ones like Cooking Pot is used in the most recent recipes for Malter, which player cannot craft with it.

**Comment by Oskutin** [comment]
Cooking pot should now be obtainable from onestop/möbelmann

**Comment by Nextej** [comment]
Water Cooler Bottle and Gas Bottle are used for medium and large moonshine distilleries crafting, without those available, the blueprints are useless.
