### ISSUE TITLE
Playtesting - Non-solid passable wall between Deekula C and Bazaar border checkpoint.

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#862]
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/f8967005-42ff-439f-b10a-c79a97d385fb)
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/3f5576aa-dc8b-457f-907d-23c56e528ad3)

**Comment by Oskutin** [comment]
Fixed
