### ISSUE TITLE
Paper trash not added to inventory when picked up

### ISSUE THREAD

**Issue by CBS-S** [loiste-interactive/Obenseuer-Issues#870]
(Playtesting beta) Balled-up paper trash (ID 16) isn't added to the player inventory when you pick it up from the environment. A sound effect plays, and the world model disappears, but that's it. This is also true if you have it in your inventory, drop it, then pick it up again.

I spot-checked this with a few other items and none of them have this property.

**Comment by CBS-S** [comment]
This seems to be just for environmental pick-up trash - if you're rummaging through, say, a trash can and drag it from that inventory over to yours, it works.

**Comment by Oskutin** [comment]
Fixed
