### ISSUE TITLE
Trouble buying stuff at Eija's Grill

### ISSUE THREAD

**Issue by CBS-S** [loiste-interactive/Obenseuer-Issues#871]
(Playtesting beta) Buying stuff produces one of three seemingly random outcomes: It appears in the you-paid-for-it vending squares (the desired outcome), it appears on the ground *next* to you, or nothing happens except that you lose money. If I leave the conversation and come back, the food I paid for seems to usually be there, and if it is then the buying works normally.

**Comment by CBS-S** [comment]
Okay I unlocked the door and it looks like some of them are clipped into the storefront

![20231108023845_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/86502239/4be5196c-79ea-45b3-be96-6a1e6e82171f)

**Comment by Oskutin** [comment]
Is the eijas slots full?

**Comment by CBS-S** [comment]
No. This happens with empty slots.

**Comment by Oskutin** [comment]
Are the slots gray?

**Comment by CBS-S** [comment]
I don't think so. I didn't take a screenshot before I switched out of Windows but the interface itself looked normal as I remember it. That's part of why I was confused.

**Comment by Oskutin** [comment]
Fixed
