### ISSUE TITLE
Eija's Grill misc.

### ISSUE THREAD

**Issue by CBS-S** [loiste-interactive/Obenseuer-Issues#872]
(Playtesting beta) Other weird stuff at Eija's. I'm not sure if these are bugs or not.

- Buying stuff in the menu sometimes causes menu items to reorganize themselves
- The cashier's name is "???" which seems weird, given that you learn everyone else's name automatically *and* they're standing directly underneath a sign that says EIJA'S.
- You can ask the cashier if they have work repeatedly, even though they always say they only sell food.
- Hamburgers, hot dogs and their shroom variants seem to be non-perishable. Is that deliberate?

**Comment by Oskutin** [comment]
Lat one is already fixed

**Comment by Oskutin** [comment]
Fixed
