### ISSUE TITLE
Julius Oberg name

### ISSUE THREAD

**Issue by CBS-S** [loiste-interactive/Obenseuer-Issues#873]
(playtesting beta) When you look at Julius Oberg it says his name, but when you interact it says ???

![20231108024419_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/86502239/37fd24dd-d110-44da-b794-ffb1cbc85110)
![20231108024424_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/86502239/e406274d-1048-4ad1-8d43-62a897cb9b28)

**Comment by Oskutin** [comment]
Fixed
