### ISSUE TITLE
Everything in greenhouse is marked owned

### ISSUE THREAD

**Issue by CBS-S** [loiste-interactive/Obenseuer-Issues#875]
(Playtesting beta) Both before and after getting the turnip quest from Jomppe, all the planting spots and most of the seeds are marked owned. Picking up the seeds that say "take" still produces the handcuff icon when you have them in your inventory.

**Comment by Kastuk** [comment]
Its just maked that you will not eat crops or take them out. All need to be sell to farmer there.
