### ISSUE TITLE
Playtesting - Reloading a level causes Recipes to disappear.

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#876]

**Comment by Oskutin** [comment]
what recipes?

**Comment by Nextej** [comment]
Oven/Stove/Mashing, whatever you can find "in-the-world" laying around, hanged on walls.

**Comment by Oskutin** [comment]
So in world recipes you mean, not the ones already collected? And this is a new char?

**Comment by Nextej** [comment]
Yes, the ones collected stay, recipes as an item in the world do disappear, they seem to be the only ones, upon reloading new ones do not appear.

**Comment by Zuntti** [comment]
Seems to work for me? Saved + loaded the game and the recipe was still there

**Comment by Oskutin** [comment]
Do the log file complain about the recipes adressable path?

**Comment by Nextej** [comment]
I think the issue happens only on character from previous version, when loading an older map for the first time, at first glance, doesn't seem to happen. Or at least recipes that are near the player stay as same before and after doing a reload.

**Comment by Oskutin** [comment]
Then i think this is resolved, as there were a lot of changes to the GUIDs and adressable paths various things
