### ISSUE TITLE
Playtesting - updating a game causes issues on Playerment level.

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#877]
State of Playerment is getting reset, all the default trash and furniture are back in place, all player-placed stuff is gone, "Abandoned Tenement" task gets broken, all previously-checked apartments can be checked again, moving the counter up. In other apartments, unless already renovated, blueprints are respawned again, bricked doors are blocked again, containers spawned new items.

No other map is affected that way.

**Comment by Kastuk** [comment]
Thats why its need new start every update.
But surely need at least some console commands to switch states of appartments renovation to skip repeating of same time-consuming things every time.
