### ISSUE TITLE
Playtesting 0.15 - Bottles still world spawn bottles in certain beer crates in Playerment

### ISSUE THREAD

**Issue by snortico** [loiste-interactive/Obenseuer-Issues#878]
New save started in 0.15, beer crate by sauna canal still spawns bottles at a high rate in world as well as refreshing in beer crate. 

Have not yet had a chance to check other crates.

**Comment by Nextej** [comment]
Beer crates at Playerment (floor 2, Malone's apartment and apartment 6) do spawn bottles with each reload as well.

**Comment by snortico** [comment]
Also seems to affect firewood storage at the canal sauna? Not world spawns obviously but first visit had only ~2 stacks of firewood and it filled up quickly.

**Comment by Oskutin** [comment]
Are the all spawn bugs in playerment?

**Comment by snortico** [comment]
I have not been able to find any spawn bugs of this nature outside of playerment, notably it does not affect the liquor selling stall which it did before.

**Comment by Oskutin** [comment]
got a sace where i could check this?

**Comment by Nextej** [comment]
@Oskutin The only notable ones I found outside Playerment is on Outside level next to the Canal Sauna, otherwise I haven't seen and/or checked other spots.

**Comment by snortico** [comment]
[Slot1.zip](https://github.com/loiste-interactive/Obenseuer-Issues/files/13301762/Slot1.zip)

**Comment by Oskutin** [comment]
> stuff, like some pills stacking up in the contaminated apartment at Kolhola.

Canal sauna still counts as playerment

**Comment by Oskutin** [comment]
Fixed
