### ISSUE TITLE
Playtesting - "Start 5 Renovation" issue of the "Getting Started" task.

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#879]
It is possible that before player is tasked by Malone to start 5 more renovations, player will already start few, by this point the quest however assuemes that player had started exactly one renovation before, and won't count in additional renovations made for that 5 renovations mark of the next objective.

So, before finishing "Start renovation" objective and returning to Malone to inform him about this, player will start another renovations, when the Malone orders to start 5 more renovations, count those additional renovations in.

In my current situation I've started 2 renovations before I got the objective to "Start 5 renovations", so now I need a total of 7 renovations to complete that section of the quest, that I would otherwise need only 6 had I visited Malone sooner.

**Comment by Nextej** [comment]
bringing it up to attention to the other quest-related issues

**Comment by Zuntti** [comment]
Fixed
