### ISSUE TITLE
Tenement Overview Upgrades: Shabby sauna issues

### ISSUE THREAD

**Issue by Kastuk** [loiste-interactive/Obenseuer-Issues#881]
Playtesting version.

Toilet outside not give relief and animation of sitting.
![20231108212954_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/36314945/326b7d7d-82e0-4aad-ac31-e9ccd80e7966)

Grill outside haven't fuel slot at first untill reenter the locaton (in-out sauna).
![20231108213003_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/36314945/953090a4-02d1-4dab-9fa8-5e807141343f)

[Slot4.zip](https://github.com/loiste-interactive/Obenseuer-Issues/files/13300217/Slot4.zip)

**Comment by Oskutin** [comment]
Fixed the toilet.
That other thing is the well known slot issues...
