### ISSUE TITLE
add_money RM now produces strange results

### ISSUE THREAD

**Issue by CBS-S** [loiste-interactive/Obenseuer-Issues#884]
I see you've added decimals to the real money value. It produces strange results for me when adding money from the console. Adding 1 adds either 1.04 or 0.96, so that after doing it twice you've added two, but in the middle it's weird.

![20231108222811_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/86502239/a768cfe0-ebe9-4cf9-b358-5b5158686f75)
![20231108222824_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/86502239/57948023-9bb8-4353-a5db-6a2111cda69a)
![20231108222835_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/86502239/8f75c5fe-344f-4b78-9392-2390d353b7bc)

**Comment by CBS-S** [comment]
The problem seems to be with odd numbers. When I do it with 2, it adds 2. When I do it with 5, it adds 4.96 and then 5.04

![20231108223409_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/86502239/9c53a747-fb99-4af6-8757-402068a9ef8a)
![20231108223416_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/86502239/22f0f891-af2c-45e3-9280-40b9aa008ff9)
![20231108223424_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/86502239/92d8b4ae-8d3c-4b3f-aad3-f7ff6a0e915d)

**Comment by Zuntti** [comment]
Seems to be fixed already
