### ISSUE TITLE
Tenement Overview Upgrade. Yard, shabby level. Got stuck at planks

### ISSUE THREAD

**Issue by Kastuk** [loiste-interactive/Obenseuer-Issues#886]
At these places I'll stuck if walking up the stairs untill jump over it.
![20231109011831_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/36314945/402e6bab-4529-48ac-aaa0-bf30e7ae40aa)
At these south stairs I got stuck whenever I walk out from this platform.
![20231109012247_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/36314945/7b8e62a3-8ffa-447f-8983-d674a35a75cf)
![20231109012306_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/36314945/64b702bd-0b99-4fbc-8c78-96349de9ed62)
![20231109012228_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/36314945/865658f6-6a02-4269-b523-528518b591cc)

**Comment by Kastuk** [comment]
Save there 
[Slot10.zip](https://github.com/loiste-interactive/Obenseuer-Issues/files/13307403/Slot10.zip)

**Comment by Oskutin** [comment]
Fixed
