### ISSUE TITLE
Playtesting - Bleeding can lower the health to negative numbers without killing.

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#887]
If player is getting a health reduction caused by bleeding, the health can go below zero if the bleeding is not constantly applied, player can stay alive as long as he's not interacting with anything that causes bleeding.
How to reproduce: Go under the fence with thorns and jump until bleeding lowers the health to low values -> move away and let the bleeding drain the health below zero -> player doesn't die until touches thorns again.
[Player.zip](https://github.com/loiste-interactive/Obenseuer-Issues/files/13302232/Player.zip)

**Comment by Oskutin** [comment]
Fixed
