### ISSUE TITLE
Some feedback regarding dialogue window

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#89]
1. When you have more than 4 options to choose from, the 5th one is already cut off at the bottom (look at the Y and G)
![image](https://user-images.githubusercontent.com/44178400/233654369-8b82ba3c-3058-4839-b4f3-85c657058102.png)

2. When in a dialogue, you cannot pause the game, either allow to do it or have any potential harm that can come to the player disabled (progression of needs, etc. possibly time too), so when player is in a dialogue, they can be sure they can leave the game for a while and nothing wrong will happen to them.

**Comment by Zuntti** [comment]
It should already disable stats progression. Fixed Amanda having five dialogue options.
