### ISSUE TITLE
Draw distance irregularities in canal

### ISSUE THREAD

**Issue by CBS-S** [loiste-interactive/Obenseuer-Issues#893]
If you drop down to the edge of the canal in front of the player tenement using the gap next to the toll bridge, there are draw distance issues if you walk down toward the shipping container bridge.

![20231109015033_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/86502239/0de9dada-c142-4fc2-a7d5-68a9587ed384)
![20231109015035_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/86502239/00a4067d-3252-4d91-bf65-f96efed4e879)
![20231109015038_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/86502239/1fe2c2d8-90fe-4bb9-8393-ec26c7bb21ae)

They also happen coming back the other way:

![20231109015141_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/86502239/189a1042-810d-4f17-81fc-1b54a3c16804)
![20231109015144_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/86502239/afda0047-a457-464a-a949-d08714c62066)
![20231109015148_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/86502239/658f4324-057b-47e6-9bc0-7962d754b818)

The static shots don't really capture, it but things flicker in and out depending on exactly where you're standing.

**Comment by CBS-S** [comment]
Oddly enough it doesn't do this if you're standing on the other bank, but the sky flickers a bit.

**Comment by Oskutin** [comment]
Ah, occlusion is broken there

**Comment by Oskutin** [comment]
Fixed
