### ISSUE TITLE
Radio signal task issues

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#90]
If we activate the otherside encounter with Jacob before giving any information to Amanda beforehand (so she says she wants to get to find what really had happened there), we're stuck with "Check the Deekula apartment B3" stage and we cannot inform Amanda that the person buried in bathtub is Jacob.

If we've done everything in a proper order, as a response to revealing Jacob's identity to Amanda, she provides the same dialogue outcome as when informing her about the body "what are we going to do now", with option to tell or not the police, however there's not more dialogue available on the 112 number, and we're stuck yet again on "Check the Deekula apartment B3".

**Comment by Oskutin** [comment]
@Zuntti is this fixed?

**Comment by Nextej** [comment]
Second one for sure was not.

**Comment by Nextej** [comment]
Since update 0.3.08, it's no longer possible to report a body after calling 112, might be related to the fact an Other Side scene already took place before calling.

**Comment by Zuntti** [comment]
Fixed
