### ISSUE TITLE
Letter lights over Deekula doors only illuminated while in field of view

### ISSUE THREAD

**Issue by Orphiex** [loiste-interactive/Obenseuer-Issues#900]
All of the market-side entrances to the Deekula buildings have lit letters over them - A, B and C. I've noticed that they're only illuminated as long as a fraction of the light box is in the player's field of view; if you move them completely off-screen, even by only a millimeter, the light source goes out and the entrance is no longer illuminated. It's not noticeable at long distances, but more obvious as one gets closer to the doors.

Hardly a major issue, just thought I'd point it out. Will upload screenshots later.

**Comment by Orphiex** [comment]
Addendum: it's not only the Deekula lightboxes that do this. The "Tenement A" and "Tenement B" lightboxes share this behavior; there are also some other environments and light sources that replicate this behavior. For example, one of the renovated 2nd floor apartments inside the tenement has a "oil lantern" light source that illuminates the room in another apartment, but switches off when the lantern is out of the camera arc. May post a separate issue about this later, cross-linked to this post.

**Comment by Ryder17z** [comment]
Good to know that this isn't just happing to me.

**Comment by Zuntti** [comment]
Fixed
