### ISSUE TITLE
Playtest .15 - Rereading previously read notes does not show correct note

### ISSUE THREAD

**Issue by snortico** [loiste-interactive/Obenseuer-Issues#901]
After having read the yellow pages in the phone booth (and other notes,) went back and read yellow pages again. When the notes page opens, the Kolhola Rules note is displayed (the first one in the journal.) Attached a save but I think rereading old notes reproduces it easily?
[Slot1.zip](https://github.com/loiste-interactive/Obenseuer-Issues/files/13303854/Slot1.zip)

**Comment by Oskutin** [comment]
Fixed
