### ISSUE TITLE
Feedback/Enhancement - Scrap metal is a bottleneck

### ISSUE THREAD

**Issue by snortico** [loiste-interactive/Obenseuer-Issues#902]
While the general store sometimes stocks scrap metal, there's no reliable source of scrap metal. It feels at odds with the rest of the pace of the game so far to be revisiting places with known respawning containers to try to 'farm' scrap metal. Have gotten to the point of purchasing stations that can be deconstructed for scrap. I have not found any recipes in this save like building a sledgehammer with an iron bar that produces scrap. This still also feels a little roundabout, my player character has extensive access to plenty of metal items, but no way to convert to the usable 'scrap.'

Maybe this is solved with the Bazaar and new shops and areas, but currently it is very easy to be held up on playerment progress by a heavy amount considering it can take a whole day of hunting for enough metal for one upgrade while money accrues from rent. Suggest maybe a recipe to turn sheet metal into 1-2 scrap, or converting multiple cans or other trash into scrap? Allows players to balance spending money on sheet metal and making it into useful scrap, or scavenging items usually regarded as total trash to craft. Not sure if there is a recipe around this I have not found.

Another suggestion is to change requirements for upgrades. Things like makeshift walls taking 15 scrap, but not taking sheet metal seem a little odd. If the scrap represents fixtures, maybe it can be handled with more nails and pipes? Or if part of the scrap requirement is meant to be actual pieces of the walls, why not add sheet metal requirements?

**Comment by Kastuk** [comment]
I see recipe for Axe (steel bar, log) and hammer (metal slab, log) which produce scrap at both results, but usually its fail product.
Also mech.watches produces alot of scrap at fail, but need industrial lathe and recipe.

Really theres mostly scrap-to-product or component recipes, none otherwise

Then reliable source for scraps now is furniture disassembling, like carts and wall shelves.

**Comment by Nextej** [comment]
Would be nice if General Store had higher chances of having scrap metal to sell.

**Comment by Kastuk** [comment]
Just buyable trash is not quite good like for tarp, which not really harvestable material. Spawn rate in trashbins and crafting recipe for angle grinder feels more like scavenger way.

**Comment by Nextej** [comment]
I don't feel right about having scrap metal easily buyable, I also was unsure on tarp being more common to buy or find, but I'd prefer the game being less frustrating in that matter, perhaps scrap could be more common in locked apartments, so being a lockpicker could be more worthful. Perhaps the material storage at Samuel's could be somehow additionally marked to make clear stolen items are accepted.

**Comment by CubeOfIce** [comment]
But when it comes to scrap metal, too many upgrades require a lot of scrap metal, especially the earlier ones.

**Comment by Nextej** [comment]
As CBS-S had suggested in discord, not a bad idea would be to grind down metal cans to scrap metal using crude machine like Angle Grinder, it would give alternative early-game application to metal cans besides recycling into steel bars, which is argubly a mid-game mechanic, plus it would make an unique case where crude machine bares unique and desired modifier from a better variants.

**Comment by Kastuk** [comment]
Yeah, its working good enough as custom recipe mod.

**Comment by Oskutin** [comment]
Increased spawns for scrap
