### ISSUE TITLE
0.15 Playtest - Suitcase in player apartment duplicates weirdly

### ISSUE THREAD

**Issue by snortico** [loiste-interactive/Obenseuer-Issues#903]
The suitcase container that spawns in the player apartment, when accessed, sometimes seems 'empty' after putting items into it. If moved in the build menu, the suitcase is not highlighted, but can be selected. When moved, it moves an empty, duplicated suitcase. After this is placed, accessing the original suitcase still has whatever was placed in it. With certain angles, you can still access the original suitcase.

The suitcase was never picked up to inventory, which may be a root cause, only moved into another position.

Included an attached save, haven't tested all possible edge cases. 

Slot 2 is just entering the apartment, with the 'broken' state of the suitcase (under bed in bedroom.)
[Slot2.zip](https://github.com/loiste-interactive/Obenseuer-Issues/files/13305293/Slot2.zip)

Slot 1 is after doing the above move, new suitcase off to the foot of bed, with original still under the bed.
[Slot1.zip](https://github.com/loiste-interactive/Obenseuer-Issues/files/13305310/Slot1.zip)

**Comment by Z-O-M-B-I-E** [comment]
The same thing happens with the wardrobe

![20231111184623_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/46783282/e73e3374-ff66-4ea3-aaa9-9cc3818aec22)

**Comment by Nextej** [comment]
This is an old bug, storages duplicate if you attempt to MOVE or TAKE them when they contain items inside.

**Comment by Z-O-M-B-I-E** [comment]
> This is an old bug, all machines/furniture that can store items duplicate if you attempt to MOVE or TAKE them when they contain items inside.

But I didn't touch them...

**Comment by Nextej** [comment]
Oh... then there's that old very similar bug and a new one!

**Comment by Z-O-M-B-I-E** [comment]
There are more and more of them

![2023-11-11_22-55-56](https://github.com/loiste-interactive/Obenseuer-Issues/assets/46783282/d60a45e2-599d-4336-8140-b7478281dba7)

**Comment by Oskutin** [comment]
https://github.com/loiste-interactive/Obenseuer-Issues/issues/987

**Comment by Oskutin** [comment]
Managed to repro

**Comment by Oskutin** [comment]
Seems to be somewhat random
