### ISSUE TITLE
Playtesting: Kurahaara seed respawns

### ISSUE THREAD

**Issue by Orphiex** [loiste-interactive/Obenseuer-Issues#909]
In the Kurahaara greenhouse, there's a chest in which the greenhouse's seeds are stored. I just found that every time I leave and re-enter the greenhouse, the chest is completely restocked with a different randomly-generated set of seeds.

In practical terms, this means that I could empty out the chest, plant every seed in one of the "small farm" plots, leave the greenhouse, re-enter, and collect a whole new batch of seeds from the same chest. It also means that if I need a specific set of seeds (say, cucumber or potato), I can just leave and re-enter the greenhouse a few times, gathering the seeds I need as they appear and planting them before leaving. Convenient, but a bit game-breaking.

Also, in prior builds, I was using this chest as a storage unit for my own gathered seeds; I tried this in my most recent run, and the restock erased all of those accumulated seeds.

**Comment by Oskutin** [comment]
Is this a new save`?

**Comment by Orphiex** [comment]
> Is this a new save`?

Yes, it's a new save I started for the Ver 0.3.15 playtesting branch

**Comment by Oskutin** [comment]
Fixed
