### ISSUE TITLE
Suggestion: Anya encounter

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#91]
When we first met her via computer, the dialogue window already spoils her name before we have a chance to ask, would be better if it originally was saying something like "Unknown/Unknown Person/Voice" and once that person introduces themselves, the name displayed in dialogue window morphs into actual name of that person with random letters/characters inbetween. Same could be applied to Jacob.
![image](https://user-images.githubusercontent.com/44178400/233660615-ba95dc93-9522-441e-9eb8-fde4f309755a.png)

Edit. since it's a suggestion ticket already, would be nice if we had a neat way to track people we've met so far, their names, where they can be found (like "Somewhere in Deekula B2"), might be a little too farfetched tho.

**Comment by Zuntti** [comment]
Changed Anya dialogue
