### ISSUE TITLE
Playtesting - "Homecoming Celebration" task, if you steal the bottle before reaching back to Ville, the optional objective to "Steal the bottle" won't be checked off after. After crafting poisoned bottle, "Poison the bottle" doesn't get checked off.

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#911]
Bottle been stolen (before checking off "Report your finding to Ville") and been poisoned already (crafted, not yet placed in a present box).
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/2db92fc9-ef80-4521-b563-533bb38cffa1)

**Comment by Oskutin** [comment]
Poison the bottle needs you to put the bottle in the giftbox

**Comment by Nextej** [comment]
The objective "Poison the bottle" needs you putting the bottle into the giftbox and leave the area, should be split into two separate objectives, "Poison the bottle" for just the crafting and "Place the bottle in the giftbox and leave the area", even split it into three, "Leave the area", because it's confusing at first why the objective is not checked off after placing the bottle in the box.

**Comment by Nextej** [comment]
#1063 another reference to the issue.
