### ISSUE TITLE
Playtesting 0.3.15 - #842 is not fixed, rentable NPCs still return to the original map after a reload.

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#913]

**Comment by Oskutin** [comment]
Can't get this to happen

**Comment by Z-O-M-B-I-E** [comment]
> Can't get this to happen

Ingrid Claesson stays in two places at the same time

**Comment by Nextej** [comment]
0.3.16 now when rented, NPCs after fade-out don't disappear at all, they are always pressent during moving-in and after being moved in.
