### ISSUE TITLE
Playtesting - A list of lockpickable doors that should relock in relation to #595

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#916]
Unless it's bugged, I didn't encounter any doors that use that mechanic, and this is the list of the doors I think should utilise it:
- Outside: Transition doors to Container Shack, Wooden Shack and Yellow Shack should re-lock within a week with the same difficulty
- Outside: Doors to the container bridge should re-lock within 3 days with a higher difficulty each time
- Outside: Transition doors to Greenhouse Storage and Kurahaara should re-lock within 3 days with a higher difficulty each time
- Outside: Transition doors to Makeshift House should re-lock within 3 days with a higher difficulty each time
- Kolhola: Doors to Sauna should re-lock within a week with the same difficulty
- Kolhola: Doors to A5, A9, A11, A14, A15, A18, A19 and A22 should re-lock within 3 days with a higher difficulty each time
- Kolhola: Doors to A2, A4, A8, A10, A20 and A21 should re-lock within a week with the same difficulty
- Kolhola: Inside A6, doors to back storage and laundry room should re-lock within a week with the same difficulty
- Kolhola: Doors to A3 lobby should re-lock within a week with the same difficulty, doors to A3 apartment should re-lock within 3 days with a higher difficulty each time
- Deekula A: Doors to A1 office should re-lock within 3 days with a higher difficulty each time
- Deekula A: Doors to A2, A3 and A4 should re-lock within 3 days with a higher difficulty each time
- Deekula A: Doors to A6 should re-lock within a week with the same difficulty
- Deekula A: Doors to storages A6, A7 and A8 should re-lock within a week with the same difficulty
- Deekula B: Doors to storage B5 should re-lock within a week with the same difficulty
- Deekula B: Doors to B5, B8 and B11 should re-lock within 3 days with a higher difficulty each time (it makes additional sense for B8 since player can get a keys to this place, so they won't be needing to use lockpick otherwise).
- Deekula C: Doors to C3 should re-lock within 3 days with a higher difficulty each time
- Deekula C: Doors to storages 2, 6, 7 and 9 should re-lock within a week with the same difficulty
- Gatehouse: Doors leading down to jail should re-lock within 3 days with a higher difficulty each time
- Tenement B: Doors of the two locked storages should re-lock within 3 days with a higher difficulty each time

**Comment by Oskutin** [comment]
![kuva](https://github.com/loiste-interactive/Obenseuer-Issues/assets/5402150/5189b99d-ef32-4ce3-a31b-0d9addc48c28)
is this broken?

**Comment by Nextej** [comment]
hmm, no, it's not confirmed, from player_stats get, I have lvl 7,066, yet at this point if there was any lock, it was moderate or lower, and the whole map is unlocked anyway, so there is nothing to get unlocked anymore

**Comment by Kastuk** [comment]
Prison school of lockpicking always give new locks to break.

**Comment by Oskutin** [comment]
Fixed
