### ISSUE TITLE
Playtesting - There's two separate "Plank Stool" furniture, differing in crafting recipe.

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#917]
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/e8318131-e1b5-46e0-98c6-822d37a9bd6a)
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/970220f1-8073-4149-b2f1-4d1a2041d373)

**Comment by CBS-S** [comment]
One tells only the truth, the other only lies.

**Comment by Oskutin** [comment]
Fixed
