### ISSUE TITLE
Vertical Sync - turn off

### ISSUE THREAD

**Issue by Hiddenfoxwere** [loiste-interactive/Obenseuer-Issues#919]
Every time when Vert. sync - on , if changed location is off again. Every time.

![Screenshot_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/61855188/9c751cbb-8027-4d13-86d6-7e946b2420db)

**Comment by CBS-S** [comment]
Are you in the beta branch or the current public build? This was a problem in the last version of the public build I used before the latest beta became available, so it may already be fixed.

**Comment by Hiddenfoxwere** [comment]
![Screenshot_3](https://github.com/loiste-interactive/Obenseuer-Issues/assets/61855188/da5814ab-3641-4b5a-b038-4374d8f46e1a)
![Screenshot_5](https://github.com/loiste-interactive/Obenseuer-Issues/assets/61855188/dc25cf77-2832-40c3-8942-a02aa766ec34)
windows 10. If don't change location - setting don't change.

**Comment by CBS-S** [comment]
Ah, you're not in the beta. I think this has been fixed and will work fine in the next public build.

**Comment by Oskutin** [comment]
Yeah, this is already fixed
