### ISSUE TITLE
Random crash in Deekula C

### ISSUE THREAD

**Issue by Kastuk** [loiste-interactive/Obenseuer-Issues#920]
Similar to other crash #915 
This time I did explore boarded appartment on floor 3, got stuck there on floor ritual cricle and crash without message.
[Player.log](https://github.com/loiste-interactive/Obenseuer-Issues/files/13313197/Player.log)
[Crash_2023-11-09_220000765.zip](https://github.com/loiste-interactive/Obenseuer-Issues/files/13313206/Crash_2023-11-09_220000765.zip)

Save before, when I did gonna buy bridge access in next appartment.
[Slot5.zip](https://github.com/loiste-interactive/Obenseuer-Issues/files/13313199/Slot5.zip)

**Comment by Oskutin** [comment]
https://github.com/loiste-interactive/Obenseuer-Issues/issues/687
