### ISSUE TITLE
Infinite environmental stacking

### ISSUE THREAD

**Issue by CBS-S** [loiste-interactive/Obenseuer-Issues#923]
Because world models have collision, you can face down, drop things, jump on them and drop more. As far as I can tell there's no practical limit to this. Even if Unity has hard sky ceilings the way Source does, the one in OS is well above any of the playable areas. Behold:

![20231109234923_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/86502239/1c460d6f-b9bb-4dea-974b-ed33bab5ea21)
![20231109234926_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/86502239/7162cb85-ef21-4b2b-9acb-97d6ea4464a7)
![20231109234928_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/86502239/81693550-51fd-4e40-82d6-b85f03e86312)

The only cheating I did here was to give myself so many bottles (and I guess noclip to get down without dying).

**Comment by Oskutin** [comment]
Player's should be able to do stupid things :D

**Comment by CBS-S** [comment]
Respect.

**Comment by Kastuk** [comment]
![obenseuer shabby bridge.jpeg](https://github.com/loiste-interactive/Obenseuer-Issues/assets/36314945/76b2af2f-a7cf-44c7-83fc-1cbbd8ca42d1)

I like to do turnip things.
