### ISSUE TITLE
Lada changes color

### ISSUE THREAD

**Issue by CBS-S** [loiste-interactive/Obenseuer-Issues#924]
The Lada that previously had no collision changes color from brown to white if you get far enough away from it. It's easiest to illustrate from high up, but it's also visible from certain angles on the ground.

![20231109234603_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/86502239/c500986f-02da-4b15-aaa6-c88636ff005c)
![20231109234625_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/86502239/3d1c51aa-a01c-4cd5-a7cc-af47c7c26038)

From the ground (look through the window):

![20231109235731_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/86502239/ef07d267-f900-457f-8036-928f677ef900)
![20231109235732_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/86502239/2d8df337-db6e-45cf-89b1-7579ed1e2d90)

From the field kitchen:

![20231109235958_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/86502239/9a58fd7a-7503-464b-bfc9-b04473a3a6ec)

**Comment by Oskutin** [comment]
Fixed
