### ISSUE TITLE
Playtest .15 - Softlocked quest on finding bank for Passmore

### ISSUE THREAD

**Issue by snortico** [loiste-interactive/Obenseuer-Issues#926]
Did the Passmore bank hatch quest. Got an objective complete upon interacting with the bank hatch, went back to Passmore. He only has the option to trade and won't continue the quest for the passport (onto the photographer.)

Included a save. Admittedly did this fast and not paying attention, so not totally sure if I missed something, but after going back and also restarting the game, couldn't see a way to continue. Not sure how it bugged and unfortunately don't have a save early enough to retry, from before finding the hatch.
[Slot3.zip](https://github.com/loiste-interactive/Obenseuer-Issues/files/13316254/Slot3.zip)

**Comment by Oskutin** [comment]
Did you get the obstacle objectives?

**Comment by snortico** [comment]
Don't think I did, don't see them as completed. Didn't do anything strange, just approached and axed through

**Comment by Oskutin** [comment]
Did you get the objective?

**Comment by snortico** [comment]
Which objective? I don't think I got the obstacle objective. Also let me dig through my saves, I wonder if I can find one to retry and get a better report.

**Comment by snortico** [comment]
So, after getting the pop-up objective completion on activating the ladder at the bank, I ran back to passmore. Currently the only objective I have is "Get a passport from Passmore" and absolutely no mentions of the tunnels, completed or otherwise.

**Comment by snortico** [comment]
Earlier save, never got the objective for the obstacle even when running up against it.

**Comment by snortico** [comment]
![Screenshot (125)](https://github.com/loiste-interactive/Obenseuer-Issues/assets/112534082/b0a75b7e-eefb-4e35-bfa0-9a3529a4c634)
Taken while against the boards

**Comment by Z-O-M-B-I-E** [comment]
The same problem, I reached the hatch to the bank, but it is blocked, and I do not have any tasks to open it (playtesting)

**Comment by Z-O-M-B-I-E** [comment]
Is this really a bug or should it be? If this is a bug, how can I fix it?

![20231112030925_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/46783282/d81d6f78-9459-4c4e-b1d1-df4d764fd878)

**Comment by Oskutin** [comment]
Uh, I can't reproduce this

**Comment by snortico** [comment]
Will try again tomorrow. I don’t think I have a save prior to entering the tunnels, unfortunately, but I may be able to start from there and try again.

**Comment by snortico** [comment]
Can you share what I should look for exactly - order of objectives in tunnel and roughly when/where/how they should trigger?

**Comment by Oskutin** [comment]
Can i have a save after entering the tunnels, where you go to talk with passmore

**Comment by snortico** [comment]
Away from my box with the saves, will share tomorrow.

**Comment by Oskutin** [comment]
Actually, managed to reproduce this in build.
Adressable paths are maybe fucked or something.

**Comment by Oskutin** [comment]
Weird, works in editor, but once I made a build, it broke in it.

**Comment by Z-O-M-B-I-E** [comment]
> Weird, works in editor, but once I made a build, it broke.

Maybe you can change some parameter in the save to make it work?

**Comment by Z-O-M-B-I-E** [comment]
> Can i have a save after entering the tunnels, where you go to talk with passmore

[Slot1.zip](https://github.com/loiste-interactive/Obenseuer-Issues/files/13328119/Slot1.zip)

Maybe it can be fixed?

**Comment by Oskutin** [comment]
There is console command to force it to proceed

**Comment by Z-O-M-B-I-E** [comment]
> There is console command to force it to proceed

Which one?

**Comment by Z-O-M-B-I-E** [comment]
> There is console command to force it to proceed

Which command?

**Comment by snortico** [comment]
Unfortunately don't have a better save than the original one listed, that is after I have already been in the tunnels and come back to Passmore.

**Comment by Z-O-M-B-I-E** [comment]
> > There is console command to force it to proceed
> 
> Which command?

I suspect that this 

`set_objective taskId objectiveId Abandoned/Active/Failed/Finished)`

But how do I find out the nameid?

**Comment by CubeOfIce** [comment]
I just retried this from a save I made before I completed the task, I'm having the same issue. I found the entrance and the task was marked off as completed, yet Passmore's menu only gives me the prompts to buy something or leave.

**Comment by Oskutin** [comment]
> > > There is console command to force it to proceed
> > 
> > 
> > Which command?
> 
> I suspect that this `set_objective taskId objectiveId Abandoned/Active/Failed/Finished)` But how do I find out the nameid?
> 
> Also, and mail from the bank does not come, I think it can also be solved this way
 `set_objective GettingPassport5 FoundBank17 Active`

**Comment by Zuntti** [comment]
Fixed

**Comment by Z-O-M-B-I-E** [comment]
> `set_objective GettingPassport5 FoundBank17 Active`

Objective not found

**Comment by Z-O-M-B-I-E** [comment]
> > `set_objective GettingPassport5 FoundBank17 Active`
> 
> Objective not found

But I managed to complete one task a debit card
`set_objective debitcardquest debitcardquest_20 Fineshed`

**Comment by Orphiex** [comment]
Experiencing the same problem; found the blocked Bank entrance in the Bergmann tunnels, but Passmore's only available conversation topic is buying something.
![20231114005049_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/16548338/0bb5a627-1240-4f0c-8d99-22f703d58ce2)
![20231114005241_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/16548338/a49e7096-61f6-4ddd-82c5-75dc31b45f99)

The console command `set_objective GettingPassport5 FoundBank17 Active` is returning an `Objective not found` message for me too; I also tried varying the objectiveID value to see if it was a typo, but no success.

Also, I notice that in both Z-O-M-B-I-E and Snortico's screenshots, the "Deekula C" objective was never triggered. I think that it _should_ have triggered, given that I paid 75 RM to Mobelmann in order to get Passmore's password and there aren't any other candidates in Deekula C. Is it possible that this has something to do with why Passmore's conversation can't proceed?

**Comment by Nextej** [comment]
@Orphiex if you haven't talked to Mobelmann yet, you'll have a unique dialogue with Davin Lund, who sells cheap fake passports for 100 RM, this checks off "Find a passport seller in Deekula C" objective (you don't have to buy it actualy).

**Comment by Z-O-M-B-I-E** [comment]
> @Orphiex if you haven't talked to Mobelmann yet, you'll have a unique dialogue with Davin Lund, who sells cheap fake passports for 100 RM, this checks off "Find a passport seller in Deekula C" objective (you don't have to buy it actually, just talk about it).

Will this help to avoid a softlock?

**Comment by Z-O-M-B-I-E** [comment]
> `set_objective GettingPassport5 FoundBank17 Active`

I found out that this command is useless, it can only execute what you already have active. If you didn't get the assignment, it won't work

**Comment by Orphiex** [comment]
> @Orphiex if you haven't talked to Mobelmann yet, you'll have a unique dialogue with Davin Lund, who sells cheap fake passports for 100 RM, this checks off "Find a passport seller in Deekula C" objective (you don't have to buy it actually, just talk about it).

Huh, that's neat. I might try reloading an earlier save and see what happens when I trigger that. I presume that Lund's cheap fake passport doesn't work, so you need to find Passmore anyway?

If the Lund dialogue becomes unavailable after talking to Mobelmann, I'd suggest to @Oskutin that talking to Mobelmann before Lund should set the optional objective to "Failed". That way, it doesn't remain open to confuse players.
