### ISSUE TITLE
Playtesting - proposed changes to mushrooms and visual effects to make the mushroom addiction more accessible for the player

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#928]
- Make that different potency levels have different strength in visual effects, with low potency being the least invasive. On all potency levels, the center of the screen should not go out of focus, just the edges, perhaps the higher potency level, the smaller area in center that is. Low potency should also have only edges appear distorted.
- Less invasive visual effects should also apply to most easily made shroomed food.
- Change what types of shrooms spawn in Playerment, for player's apartment there should be mostly (if not only) low potency ones, for apartment 4, mushrooms with medium potency and for the boarded apartment 6, mushrooms with high potency. It will also make better mushrooms a little less accessible to start farming.

**Comment by CBS-S** [comment]
Huh, I thought the visual effects already scaled with potency. I definitely think I'm seeing/hearing stronger effects when I'm extra high.

**Comment by Nextej** [comment]
If they do, the the low potency should have the effect the least invasive so all the aspects in the early game are still playable, including aiming, reading and movement easily.

**Comment by Oskutin** [comment]
Looks like Zuntti added some threshold already
