### ISSUE TITLE
Hovering the mouse over an item to see its description and then closing the inventory, makes the description remain and overlap the player's view.

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#93]
https://user-images.githubusercontent.com/44178400/233663653-00fa53c3-f3f7-44d5-a73d-807fdd415b57.mp4

**Comment by Nextej** [comment]
It seems to be caused by another non-trivial issue that also disabled my crosshair and any visual indication of an available interaction, like Door (Open) or Shower (Use).
[Player.log](https://github.com/loiste-interactive/Obenseuer-Issues/files/11296758/Player.log)

**Comment by Oskutin** [comment]
This is likely fixed already (judging by the stacktrace on the log)
