### ISSUE TITLE
Playtesting - few changes to "Survive in Obenseuer" quest to help players with navigation

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#930]
- Change the task description to also contain the information that "She also told you to visit some place called Redemption... something to get some hot pea soup."
- Change the pea soup objective to "Ask for some hot pea soup", so the player doesn't mistake that for buying canned pea soup themself at O-Market.
- Change the first part of the description to include specifically that bottle recycling machine is inside O-Market, to avoid player looking around on the outside and interacting with vending machines instead. "Tatyana advised you to collect the bottles and take them to the bottle recycling machine inside the O-Market store."

**Comment by Oskutin** [comment]
done
