### ISSUE TITLE
Playtesting 0.3.15 - Few changes to apartment size preferences

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#932]
In the current version there's a lack of NPCs that could fill large apartments as well as more NPCs could use a multiple size preferences, I'd propose:
- Ville Skoldgangster to prefer small or medium apartment
- Ingrid Cleasson to prefer medium or large apartment
- Agnes Takala or Leon Borg to prefer medium or large apartment
- perhaps Sara Claine to prefer small or medium apartment, not sure about that one

**Comment by Oskutin** [comment]
This is actually done (to some degree)
