### ISSUE TITLE
Playtesting: Hostel sleeping times overrun

### ISSUE THREAD

**Issue by Orphiex** [loiste-interactive/Obenseuer-Issues#933]
With the new tenement settings making the player's bare apartment bed unsafe, I spent a few sleep periods in the hostel, rather than risk sleeping in the apartment. However! I noticed something, so I tested it. When sleeping in the hostel, the sleep times ran significantly longer than the normal timeframe. For example: 
![20231111001334_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/16548338/38752dd6-ee89-4750-9c01-892794057839)
My tenement bed, @ 71% tiredness
![20231111000653_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/16548338/e723c2c6-8859-4697-b95d-396aa937de3b)
Approx. length of time sleeping in tenement bed

![20231111000938_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/16548338/a236724a-bbb1-4458-bb51-2aa0541de95a)
Rented hostel bed, @ 72% tiredness
![20231111001152_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/16548338/617a172c-8ecf-40aa-bb63-10776fb8755a)
Approx. length of time sleeping in hostel bed

Not sure if this is deliberate, or a bug; certainly it represents a way of passing in-game time faster.

Also, aren't the hostel beds supposed to all be safe?

**Comment by Oskutin** [comment]
Fixed
