### ISSUE TITLE
Playtesting - If after a map load, the tenement UI is opened directly first (using H key or by interacting with contractor), switching to inventory tab renders it blank, re-open brings back the items

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#935]
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/b9fd0bbd-0232-4617-be37-405bb683a4ea)

**Comment by Nextej** [comment]
Actually, opening any tab other than inventory (like map M) at first after a map load, and then switching to inventory renders it empty.

**Comment by Oskutin** [comment]
https://github.com/loiste-interactive/Obenseuer-Issues/issues/434 could be same/similarish to this one
