### ISSUE TITLE
Playtesting - using backpacks on store vendors UI (and on potentially few machines) allows to remotely open that UI within level

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#940]
open store inventory -> open backpack -> leave the store -> open your own inventory -> open and close backpack -> you should see at that point store inventory switching back and forth with backpack inventory

I think that some other custom storage UI breaks that way, potentially machines with storage

**Comment by Oskutin** [comment]
Fixed
