### ISSUE TITLE
Playtesting - rent in Real Money doesn't seem to be properly added to the player's balance

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#942]
Before getting rent
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/e62bfceb-084a-4da6-8135-2067d71f6efa)
After getting rent
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/6c10ffaf-51a3-4698-bee0-1f8af245bb97)
[Player.zip](https://github.com/loiste-interactive/Obenseuer-Issues/files/13323481/Player.zip)

**Comment by Nextej** [comment]
Seems like the integer value of RM is added to the total of OC value, so effectively it's 9550 OC + only 696 OC in the example above.

**Comment by Oskutin** [comment]
Fixed
