### ISSUE TITLE
Playtesting - two separate "Big Television" furniture is available to buy

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#947]
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/a3bf29e6-5dc1-4115-bec2-151c654c4593)
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/7bc4ce2a-4e03-4a50-b9c6-4442f9dece7c)

**Comment by Oskutin** [comment]
They propably spawn from two different lists

**Comment by Zuntti** [comment]
Fixed
