### ISSUE TITLE
Playtesting - Sometimes the found stolen stackable items don't stack with each other, forming separate stacks

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#948]
These three stacks of stolen nails cannot be combined
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/cd1253db-0623-4d6b-9a31-3863b28a7ce0)
Applies to various stuff (lockpicks, building materials, valuable stuff) and is not limited to only specific types of items.

**Comment by Oskutin** [comment]
They don't stack because they have different owners
