### ISSUE TITLE
Metal gate in b9 closes and doesn't reopen after entering and leaving the cellar 

### ISSUE THREAD

**Issue by Crlangley** [loiste-interactive/Obenseuer-Issues#95]
![20230421121805_1](https://user-images.githubusercontent.com/65619937/233698614-80cf78f6-8e6a-44e9-9de5-7f974d9edf72.jpg)

Found if you go into the cellar with the gate open and come back the gate is closed again and while the animation for the winch works the gate won't open. Saving and reloading seems to fix it, though reloading an autosave does not.  I also tried without opening the gate first and it work.

**Comment by Oskutin** [comment]
Fixed
