### ISSUE TITLE
Playtesting - Leaving perishable food inside stove's UI causes stacking multiplication issues when it turns into mold

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#951]
A cooked food left in stove's UI (potentially other food crafting stations or machines in general) if left to spoil into mold, that mold will multiply within the UI when attempted to be moved around.

To recreate: place cookable meat into a stove -> cook it all so cooked meat occupies all the slots (don't move it yet) -> leave it to spoil -> attemp to move the mold around, combine into stacks, you'll it seemingly multiplying
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/656ac21a-9c57-4f17-b489-96359d89a79c)

**Comment by Oskutin** [comment]
Hmm, seems to double upon the first drag, then it fixes itself

**Comment by Oskutin** [comment]
Fixed
