### ISSUE TITLE
Playtesting - Dumpsters that never respawn items, yet they definitely should

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#956]
Out of all storages, Dumpsters are especially important in the early-game for new players as a clear indication where to look for bottles, so it should be made sure they work. Additionally I think that dumpster storages in general should resupply 2-4 times a day (min 6 hours; max 12 hours)

Near Tatyana
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/fa05754b-485f-4f01-887e-f0582066a4f8)
Near Deekula A west entrance 
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/0346947a-6e24-46d5-b5d9-f9c89baf2248)
Near bus
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/75ad9f44-0ce5-4fff-a6f3-3ca701265c11)
Behind Eija's Grill
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/971e97df-8220-4c25-a28b-affe9d2487fd)
Next to Tenement A entrance
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/a8b3c3a4-5aab-4598-90e9-2070a7fceb12)
Next to O-Market entrance
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/b539920d-40dc-4aed-a721-221bc388f8b2)
In the alleyway leading to Tenement B
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/59f080a2-b87f-40c5-a284-e9645e92c2e6)
Next to Kolhola entrance
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/e3165ba1-2a96-4c18-807a-e2d1e7c444ce)
Near the camper trailer
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/1dfe7953-ecc2-4f80-9c6c-4508f11ba783)
Near Deekula B east entrance 
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/9ffcacfa-0a32-41c4-8efd-cbd6c9f0a264)
Near Deekula A east entrance
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/fef6acb1-3d53-4e8b-9011-9afae9ea9954)
Between backyard police officer and side Playerment entrance
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/cd035e34-692c-4d08-95d6-3ebf78abd828)
Right of the two dumpsters next to the One Stop Shop
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/8f00f752-160f-4ad4-82c9-22be426f2992)
Inside Deekula A storage on the first floor
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/3fea063f-1fbb-4b3f-951f-eba26ec5cbd3)
Inside bricked room of Dr. Pena waiting room (this one never spawns any items in the first place, it should)
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/eb286eed-9dca-4f49-83ec-8f8a5a989a89)
On to top floor of Deekula A next to the Geared Head Drill (this one also never spawns any items in the first place)
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/a045c318-ec87-44cc-bd75-9639dfa5fdf8)
Next to the bottle recycling machine inside O-Market
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/376f2881-ea96-4957-b43e-19ed3574c43d)
Trashbin at the end of Deekula C storage hallway on the first floor
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/ad916056-c208-4e96-a9c8-402ce3600cd1)

**Comment by Oskutin** [comment]
Fixed
