### ISSUE TITLE
The area underneath the Sink object in B4 has no collision 

### ISSUE THREAD

**Issue by Crlangley** [loiste-interactive/Obenseuer-Issues#96]
![20230420215721_1](https://user-images.githubusercontent.com/65619937/233699608-c2434e98-4521-4e2d-b434-5527ae918f9a.jpg)
![20230420215737_1](https://user-images.githubusercontent.com/65619937/233699613-549407f4-7558-4b75-aa42-9a20154251e3.jpg)

While the top and spigot in the front seem to have a collision box the barrel and maybe the wooden legs don't. If you crouch you can get under it and clip into the barrel

**Comment by Oskutin** [comment]
Fixed
