### ISSUE TITLE
Playtesting - Aborting the started Mashing process immediately returns finished mash.

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#965]
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/9dd97c82-bd2b-4ed7-8ea5-c0d744f91e2c)

**Comment by Nextej** [comment]
Same happens for Fermenting barrel, it also raises skill for that machine, despite being marked as failed.

**Comment by Oskutin** [comment]
Fixed
