### ISSUE TITLE
Playtesting - Issues with liquid refilling between containers.

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#966]
1. If the container containing liquid is stacked, for example 2 wine bottles filled with water, an attempt to separate the stack while at the same time swapping around item, if the swapped item is stackable and the first available position (item slot) to move would be the placement of the original bottle stack or the original position of the swapped item itself, the item will disappear.
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/d9160c77-2511-4bdb-a257-cd00c3383cc7)
2. If the container didn't already had the liquid present, attempting to refill liquid to it from another container won't change it's state to look as if it contains liquid, those items are also not valid for quests. 
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/ed67d37a-6a03-4708-9303-d6ce577c578a)

**Comment by Oskutin** [comment]
Can't seem to reproduce the first one. Could be fixed by other fixes applied to item movement

**Comment by Oskutin** [comment]
Can get the second tho

**Comment by Oskutin** [comment]
Fixed
