### ISSUE TITLE
The interaction with Adam is completely broken

### ISSUE THREAD

**Issue by ontrigger** [loiste-interactive/Obenseuer-Issues#97]
https://user-images.githubusercontent.com/8556074/233724723-59d744e5-f259-466b-8901-cb17b34611b1.mp4

**Comment by Oskutin** [comment]
How to reproduce?
As this seems  to work for me.

**Comment by ontrigger** [comment]
https://user-images.githubusercontent.com/8556074/233845904-7032fbc6-c4ed-4128-b1fc-e2e916d3db8d.mp4

**Comment by Zuntti** [comment]
Fixed
