### ISSUE TITLE
Playtesting - Owned money (coins and bills) taken from owned storages (for instance from breaking down piggybanks) when NPCs are present, is not getting detected as theft, like it is with other items.

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#970]
Easiest to test is probably at hostel, at a large set of wardrobes behind clerk, if a piggybank/moneybox spawns there, taking the money won't count as theft.

**Comment by Kastuk** [comment]
Also you can Drop money from an cash register (no crime) to place which is invisible for owner so you will can steal them there without been detected.

**Comment by Oskutin** [comment]
Fixed
