### ISSUE TITLE
Playtesting - Some furniture has incorrect "preview" and a "placed" position.

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#972]
- Large Rat Cage, when trying to place the rat cage, it shows offcentered, when it's placed, it is centered in the placed position.
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/57ca214d-3b9e-4cb8-afb1-4c7765016d7b)
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/9dac0964-8178-4a8a-b180-921b71d5b3da)
- Chest Freezer rotates 180 degrees when placed in compare to its placeing preview.

**Comment by Oskutin** [comment]
Fixed
