### ISSUE TITLE
Playtesting - Mashing process stopped at 0 minutes left, the only option is to abort.

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#973]
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/7761faa3-7776-4e3a-a34e-a32d7bdd3f7f)
[Player.zip](https://github.com/loiste-interactive/Obenseuer-Issues/files/13327847/Player.zip)

**Comment by Oskutin** [comment]
You get this reliabilitly or random?

**Comment by Nextej** [comment]
Seems like its the reloading that could cause it. I'll do more tests.

**Comment by Oskutin** [comment]
what happens if you put the mashing tun on, as it is off now

**Comment by Oskutin** [comment]
Can't reproduce this with save/loading

**Comment by Oskutin** [comment]
Oh found the issue, happens if you load a save where mashing tun is off, but there is mash processing inside.

**Comment by Oskutin** [comment]
Fixed
