### ISSUE TITLE
[Playtesting] The matchboxes are positioned incorrectly

### ISSUE THREAD

**Issue by Z-O-M-B-I-E** [loiste-interactive/Obenseuer-Issues#975]
![20231112011512_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/46783282/505707a3-298b-4f06-bb15-45317da79720)
![20231112011519_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/46783282/5dd42b40-e23f-4d70-b151-bdc534b0ab7c)

**Comment by Oskutin** [comment]
Fixed

**Comment by Z-O-M-B-I-E** [comment]
And the same with bottles of wine

![20231111180525_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/46783282/bc7bc1b9-524d-4be3-8212-ca576e942c83)
![20231111180529_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/46783282/01e657f2-a96a-4d52-8355-357c7ec221d2)
