### ISSUE TITLE
[Playtesting] In this place, you can get stuck in a corner

### ISSUE THREAD

**Issue by Z-O-M-B-I-E** [loiste-interactive/Obenseuer-Issues#976]
![20231111232421_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/46783282/5b5b296a-9d86-45e6-b845-d84833281eab)
![20231111232426_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/46783282/5c1d8e7a-4898-4944-a606-5e352c978633)

**Comment by Oskutin** [comment]
Fixed
