### ISSUE TITLE
Playtesting - "No Longer Abandoned" achievement accounts also for evicted Tenants

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#978]
Having 5 currently tenned and 2 evicted, I got the achievement. Achievement wasn't granted until I had evicted and rented again an apartment.

**Comment by Oskutin** [comment]
Can you give more detailed explanation.
Were the two being evicted, or eviction already completed?

**Comment by Nextej** [comment]
One of the was already evicted a while ago, so by now I had 5 tenants in the apartment, one evicted, at no point there were six tenants, now I had evicted one tenant, waited for it to complete and in its place I've rented the apartment to a new tenant, the moment I rented, before the moving-in was completed, I received the achievement (for having 7 tenants, since I as I suppose there's 14 free apartments)

**Comment by Nextej** [comment]
On that note, the achievement should pop-up after the 7th tenant had already moved in, not when they start moving it, like it does now.
