### ISSUE TITLE
Playtesting - Brick Furnace crafting process gets corrupted upon map reload, the machine is stuck in this state and there's no way of reverting that

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#981]
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/735cf924-222e-40d9-b747-6ea69c9097ad)

**Comment by Oskutin** [comment]
Seems to be fixed by the same bug what affected mashers

**Comment by Oskutin** [comment]
But where the heck does that shroom icon come from
