### ISSUE TITLE
Playtesting - When having a selected recipe in the crafting UI, items are added to the machine's storage slots (like by finishing an ongoing crafting) that would be enough to start crafting anothe recipe that comes in order before that, that we have selected, upon attempting to start crafting the selected recipe, the that's first in order from the list will be crafted.

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#982]
For example: put two logs and two steel ingots into crafting slots of geared head drill -> select and start crafting axe, don't close the recipe -> output yields scrap metal -> attempt to craft another axe from already selected recipe will craft lockpicks

Another example was with attempt to craft Mushroom extract, but it was even more broken as upon attempting to craft, it started water purifying process, despite there not being any dirty bottle recipes, just empty bottles.

**Comment by Zuntti** [comment]
Fixed
