### ISSUE TITLE
Suggestion - Lockpicked doors become locked again

### ISSUE THREAD

**Issue by CubeOfIce** [loiste-interactive/Obenseuer-Issues#985]
With places such as Kohola and Deekula having doors that must be lockpicked, it would only make sense that the doors become locked again, especially apartments. The tenants could "change their locks" and the player would require a higher lockpicking level in order to gain entry easily, giving a bit more difficulty and incentive to gain more lockpicking skill.

**Comment by Oskutin** [comment]
Alredy done
