### ISSUE TITLE
Playtesting - Apartments that reside multiple people, spawn only one NPC inside.

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#991]

**Comment by Orphiex** [comment]
Is this one a bug? I just figured that extra character models for the apartment rentals would be added in later versions of the beta.

**Comment by Zuntti** [comment]
Some apartment sizes are still missing furniture prefabs for multiple people

**Comment by Zuntti** [comment]
Already fixed
