### ISSUE TITLE
Playtesting - "Getting Started" quest: When player is tasked to go to the Kurahaara's farm, they should be able to ask one of the brothers at Kurahaara's Stall about the farm direction.

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#993]
Players may wrongly associate the stall as the place they were meant to go to ask for the job, so the Kurahaara at the stall should be able to point them to the alleyway between O-Market and Skeida.

**Comment by Kastuk** [comment]
"Looking for our farm? Raise your head or whatever you have up here".

**Comment by Oskutin** [comment]
Done
