### ISSUE TITLE
Playtesting - "Survive in Obenseuer" task issues

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#997]
1. Closing and opening the task tab with this quest selected keeps swapping both objectives around.
2. After completing both objectives, it is requires to complete objective for the pea soup again to get the task marked off as completed, otherwise the quest remains on the list of "active tasks" while having both objectives marked as complete.
[Player.zip](https://github.com/loiste-interactive/Obenseuer-Issues/files/13341923/Player.zip)

**Comment by Zuntti** [comment]
Fixed 2

**Comment by Zuntti** [comment]
Fixed
