### ISSUE TITLE
Playtesting - After evicting a tenant, upon interaction they still respond as if they had rented apartments, they don't acknowledge eviction anyhow. It's also not possible to rent them apartment again, not sure if intentional.

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#998]

**Comment by Oskutin** [comment]
After eviction is complete or eviction still in progress?

**Comment by Nextej** [comment]
Completed.

**Comment by Nextej** [comment]
Aleksi Kivi, after completed eviction an interaction with him returns a dialogue of sort him thanking for the apartment or him saying he started writing a new book (thanks to the apartment). There's no any actual dialogue option or ability to rent him apartment again (no tenement renting UI pop up). Need a save?

**Comment by Oskutin** [comment]
yeah save would be good

**Comment by Nextej** [comment]
[Miko_Mortley.zip](https://github.com/loiste-interactive/Obenseuer-Issues/files/13353551/Miko_Mortley.zip) Slot 3 should be the latest.

**Comment by Oskutin** [comment]
Btw your furniture survived to .16. You seem to have nice turnip farming and rat business there.

**Comment by Nextej** [comment]
Turnips and carrors were meant to raise mashing skill, I found pretty neat ratios if you use 20L canisters.

**Comment by Oskutin** [comment]
Hmm, Aleksi is not rented, but neither he is in Deekula A

**Comment by Nextej** [comment]
Oh, yeah right, you gotta reload the level for him to appear. If character was rented once, on the first load of the level in that session, he will properly disapper.

**Comment by Oskutin** [comment]
Apartment 3 looks empty, despite having full 4 person family.

**Comment by Oskutin** [comment]
Same for 9

**Comment by Nextej** [comment]
Yeah, reported it on #991

**Comment by Oskutin** [comment]
I mean that it lacks furniture

**Comment by Nextej** [comment]
Huh? Like none at all or none more than makeshift stuff (which had some bed and suitcases and some other stuff).

**Comment by Oskutin** [comment]
None at all

**Comment by Oskutin** [comment]
Do they appear for you? Could be just some adressable path changes between versions

**Comment by Nextej** [comment]
Not even doors?
Apartment 3:
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/56c3ffbe-ff77-4c09-9413-8095d5b2176f)
Apartment 9:
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/940f482f-0171-4060-a035-25cabde0c11d)

**Comment by Nextej** [comment]
Toilet and the other small room also have some furnitures there

**Comment by Oskutin** [comment]
Have doors and walls, but not any furniture.
There seems to be something wrong with Aleksi, as he is not deekula A despite loading the map few times

**Comment by Nextej** [comment]
Hmmm, he loaded in to me for the first time I went there
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/798ebeaf-1bae-41dc-82a2-78beb5734f07)

**Comment by Z-O-M-B-I-E** [comment]
> Do they appear for you? Could be just some adressable path changes between versions

Have furniture

**Comment by Oskutin** [comment]
Nevertheless, i think i found the reason for not being able to rent back

**Comment by Oskutin** [comment]
Yeah got it fixed, i think that also fixed the NPC not appearing issue

**Comment by Oskutin** [comment]
Was caused by improper removal of the resident of the resident list. Aleksi was hanging around in the list even the apartment was vacated.
