### ISSUE TITLE
Dumpster labeled storage

### ISSUE THREAD

**Issue by CBS-S** [loiste-interactive/Obenseuer-Issues#999]
![20231114014424_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/86502239/1f864082-2ead-4259-8684-b874542617d1)

The identical one to the left says "dumpster."

**Comment by Orphiex** [comment]
I've noticed a few other examples of this around the map; I'm pretty sure that the dumpster in the Kolhola Hostel is also labelled "Storage". I'll go back and check later.

**Comment by Oskutin** [comment]
Where is this?

**Comment by Oskutin** [comment]
Kolhola one is already fixed
